### ISSUE TITLE
"Login error Invalid username/password" when using ldap auth

### ISSUE THREAD

**Issue by mottersen** [Requarks/wiki#100]
### Actual behavior
"Login error Invalid username/password" when ldap auth is enabled

### Expected behavior
Successful login for multiple ldap users

### Steps to reproduce the behavior
enable ldap auth and try to login with multiple different ldap accounts.  I was able to login successfully with one ldap account, but all subsequent login attempts with different ldap users were unsuccessful.  There are no errors in any of the logs.

**Comment by mottersen** [comment]
Let me know if I can provide more information.

**Comment by NGPixel** [comment]
I just tested using this test AD:
http://www.forumsys.com/tutorials/integration-how-to/ldap/online-ldap-test-server/

I was able to login using 2 users in different OU and both users are correctly listed:
![ldap-result](https://cloud.githubusercontent.com/assets/15522395/26029287/4ef78e9c-37ff-11e7-87c2-d7215af5656c.png)

Make sure the `searchBase` parameter is set correctly. It could be excluding users.

**Comment by mottersen** [comment]
@NGPixel thanks for checking this out.  I've tried changing the OU to the root of our Domain.  This didn't change the behavior.  I would note that the original ldap account of mine still works.  I can disable LDAP and it stops working as expected.  Is there any way to enable logging for ldap/authentication?  I could help troubleshoot if I had some errors to work with.

**Comment by NGPixel** [comment]
In this [file at line 55](https://github.com/Requarks/wiki/blob/master/server/controllers/auth.js#L55), insert a new line above with the following code:
```js
console.error(err)
```

You'll get the error object as returned by the LDAP driver in your logs.

**Comment by mottersen** [comment]
Hey @NGPixel, good news.  I got ldap working when I changed the search filter from the default "uid equals username" to this:
`searchFilter: '(&(objectcategory=person)(objectclass=user)(|(samaccountname={{username}})(mail={{username}})))'`
I believe the samaccountname=username was the critical part.  I've had applications use the uid attribute before, so I'm a bit curious why passport-ldapauth only wants to use the samaccountname attribute.
Here's what the logs looked like when I enabled:
`==> logs/wiki-error-0.log <==
2017-05-16T01:34:01.808Z - error: [SERVER]
2017-05-16T01:34:16.332Z - error: [SERVER]

==> logs/wiki-output-0.log <==
2017-05-16T01:35:00.104Z - info: [AGENT] Running all jobs...
`

**Comment by mottersen** [comment]
I would suggest updating the documentatoin to note that Active Directory backends should use     `searchFilter: (samaccountname={{username}})` while standard LDAP should use:     `searchFilter: (uid={{username}})
`

**Comment by NGPixel** [comment]
Added to the docs! Thanks.
