### ISSUE TITLE
https://docs.requarks.io/install/docker should be updated about the sqlite part.

### ISSUE THREAD

**Issue by tedinGH** [Requarks/wiki#1001]
![image](https://user-images.githubusercontent.com/7204092/64008767-54f67580-cb49-11e9-93db-ce40040720c9.png)
It should be "DB_STORAGE" now.

**Comment by NGPixel** [comment]
`DB_FILEPATH` is the correct variable name, as specified in the config mapping for docker: https://github.com/Requarks/wiki/blob/master/dev/build/config.yml#L10
