### ISSUE TITLE
/graphql got error reponse when the machine is offline.

### ISSUE THREAD

**Issue by tedinGH** [Requarks/wiki#1002]
I got this response from /graphql when I visited the root page.Wiki is deployed on a offline machine by docker from image requarks/wiki:beta.
`
[{"errors":[{"message":"Invalid locale or namespace","locations":[{"line":3,"column":5}],"path":["localization","translations"],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"stacktrace":["Error: Invalid locale or namespace","    at Object.getByNamespace (/wiki/server/core/localization.js:56:13)","    at translations (/wiki/server/graph/resolvers/localization.js:36:24)","    at field.resolve (/wiki/node_modules/apollo-server-core/node_modules/graphql-extensions/dist/index.js:133:26)","    at resolveFieldValueOrError (/wiki/node_modules/graphql/execution/execute.js:467:18)","    at resolveField (/wiki/node_modules/graphql/execution/execute.js:434:16)","    at executeFields (/wiki/node_modules/graphql/execution/execute.js:275:18)","    at collectAndExecuteSubfields (/wiki/node_modules/graphql/execution/execute.js:713:10)","    at completeObjectValue (/wiki/node_modules/graphql/execution/execute.js:703:10)","    at completeValue (/wiki/node_modules/graphql/execution/execute.js:591:12)","    at /wiki/node_modules/graphql/execution/execute.js:492:16","    at process._tickCallback (internal/process/next_tick.js:68:7)"]}}}],"data":{"localization":{"translations":null,"__typename":"LocalizationQuery"}}},{"errors":[{"message":"Invalid locale or namespace","locations":[{"line":3,"column":5}],"path":["localization","translations"],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"stacktrace":["Error: Invalid locale or namespace","    at Object.getByNamespace (/wiki/server/core/localization.js:56:13)","    at translations (/wiki/server/graph/resolvers/localization.js:36:24)","    at field.resolve (/wiki/node_modules/apollo-server-core/node_modules/graphql-extensions/dist/index.js:133:26)","    at resolveFieldValueOrError (/wiki/node_modules/graphql/execution/execute.js:467:18)","    at resolveField (/wiki/node_modules/graphql/execution/execute.js:434:16)","    at executeFields (/wiki/node_modules/graphql/execution/execute.js:275:18)","    at collectAndExecuteSubfields (/wiki/node_modules/graphql/execution/execute.js:713:10)","    at completeObjectValue (/wiki/node_modules/graphql/execution/execute.js:703:10)","    at completeValue (/wiki/node_modules/graphql/execution/execute.js:591:12)","    at /wiki/node_modules/graphql/execution/execute.js:492:16","    at process._tickCallback (internal/process/next_tick.js:68:7)"]}}}],"data":{"localization":{"translations":null,"__typename":"LocalizationQuery"}}}]
`
And Chrome console showed that
![image](https://user-images.githubusercontent.com/7204092/64013234-f5509800-cb51-11e9-9a06-ed1ad747d108.png)

**Comment by NGPixel** [comment]
You must sideload locale files:
https://docs.requarks.io/install/sideload
