### ISSUE TITLE
Menu/new page is broken for non-English setup

### ISSUE THREAD

**Issue by mkende** [Requarks/wiki#1005]
**Describe the bug**
When creating a page through the side menu "New page" button, if the wiki has the multi-languages namespace option disabled and is set to an non-English language (at least, French), then the "Select page location" popup has no language selected by default.

You can select your language in the drop-down but if you don't then the page is created in English and this cannot be modified later in the "Page properties" dialog when saving the page.

(as a side note, the "Select page location" popup is not localized, but this is minor)

**To Reproduce**
1. Set the wiki in French with multi-languages namespace disabled
2. Click on "New page" in the side menu ("Nouvelle page" in French)
3. Observe that the language drop-down is empty, do not select a language there.
4. Create the page
5. Save the page

**Expected behavior**
The page is in French

**Actual behavior**
During the first save of the page, the page properties dialog shows that the age will be in the English namespace, despite the fact that it is not enabled.

**Screenshots**
See a screenshot of my regionale settings and the "page location" dialog: https://imgur.com/WEpH2Lv

**Host Info (please complete the following information):**
 - OS: Debian 10 Buster
 - Wiki.js version: 2.0.0-beta.275
 - Database engine: SQLite3

**Comment by NGPixel** [comment]
Fixed for next release.
