### ISSUE TITLE
Upgrade to 275 issues. 

### ISSUE THREAD

**Issue by devp01** [Requarks/wiki#1008]
**Question**
Describe in details what you are trying to achieve and where do you need guidance.

**Host Info (please complete the following information):**
OS: [e.g. Ubuntu 18.04]
Wiki.js version: [e.g. 2.0.0-beta.275]
Database engine: [ mysql]

I have upgraded to 275. The console is showing that but when i log in the dashboard is showing incorrect information.
Console output
![image](https://user-images.githubusercontent.com/46513658/64139316-0b927880-ce1e-11e9-878a-0d1ad3a16209.png)

![image](https://user-images.githubusercontent.com/46513658/64139338-22d16600-ce1e-11e9-876b-c2a9d2da61c3.png)

Dashboard 

![image](https://user-images.githubusercontent.com/46513658/64139371-3e3c7100-ce1e-11e9-9742-19579e9f89dc.png)

**Comment by devp01** [comment]
More information regarding this issue.
The admin- General - is displaying an Unexpected error information and the Site URL and other Site Info is also not getting saved under this. After the upgrade it was all blank and I entered the information but after that it is not getting saved.

**Comment by NGPixel** [comment]
Try to logout and log back in again.

**Comment by devp01** [comment]
Thank you. I rebooted the instance and it logged back in again and it seems to be working fine now.
