### ISSUE TITLE
Group-delete is not working

### ISSUE THREAD

**Issue by devp01** [Requarks/wiki#1009]
**Question**
Describe in details what you are trying to achieve and where do you need guidance.

**Host Info (please complete the following information):**
OS: [e.g. Ubuntu 18.04,]
Wiki.js version: [e.g. 2.0.0-beta.275]
Database engine: [mysql 8.0.17]

Admin panel- Groups- Delete button is not working.

**Comment by devp01** [comment]
Host Info (please complete the following information):
OS: [e.g. Ubuntu 18.04,]
**Wiki.js version: [e.g. 2.0.0-beta.303]**
Database engine: [mysql 8.0.17]

Admin panel- Groups- Delete button is not working.

![image](https://user-images.githubusercontent.com/46513658/64955356-aae74f00-d8a5-11e9-845b-00e8c2d184e1.png)

It should delete the group.

**Comment by devp01** [comment]
The Group also allows duplicate names. 
Expected behavior- It should not allow duplicate names. There should be a validation method when we create a new group to avoid duplication of group names.

**Comment by NGPixel** [comment]
Fixed by 3befd570604d58c7b4ff6ac450ed6730973d056b
