### ISSUE TITLE
Folders not created when creating sub page first

### ISSUE THREAD

**Issue by vabene1111** [Requarks/wiki#1013]
**Describe the bug**
When i create a new page as the subpage of a page that does not yet exist it works but has several issues at multiple locations. This can be expected (since the folder does not exist) but there should either be somethign preveting me from creating a subpage of a nonexistent page or the folder should be created if it does not exist.

Errors occour for example in the git sync or 

**To Reproduce**
1. create new page
2. enter as path /some-page-that-does-not-exist/page
3. try syncing with git or deleting the page (and probably many other actions)

**Expected behavior**
Either
- prevent users from creating a page where the subfolder(s) dont exist
- create missing folders when creating the page

**Screenshots**

**Host Info (please complete the following information):**
 - OS: latest docker image
 - Wiki.js version: [e.g. 2.0.0-beta.270]
 - Database engine: postgres 12-alpine

i hope i did not miss the same report somewhere else but i could not find it

**Comment by NGPixel** [comment]
What error are you having exactly?

I was able to create a new page at `sub/second/level/test` and have it sync without any issues.

**Comment by vabene1111** [comment]
Interesting, i just tested this issue with the latest version and it seems to have resolved itself. With the update i also downgraded to postgres:11 docker image, but i dont think that this was what caused the issue.

I will close this for now and reopen in case i can recreate it.
