### ISSUE TITLE
changing user groups doesn't work

### ISSUE THREAD

**Issue by oitheatre** [Requarks/wiki#1014]
I updated to the new version of Wiki.js, created a few groups, set up add user into a group after registration and signed up myself. Then added my regular user to Adminis and other group, but still have just permission for the first group after registration. So, I can't go to admin panel.

**To Reproduce**
1. create a group
2. assigned auto adding a user into the group
3. try to add registered user in Admins group

**Host Info (please complete the following information):**
 - Docker
 - Wiki.js version: [e.g. 2.0.0-beta.275]
 - postgres 9.6.15

**Comment by NGPixel** [comment]
Did you try to logout / log back in after the change?

**Comment by oitheatre** [comment]
@NGPixel I don't know why, but it was working properly next day. Probably, I did logout and login. Can't say right now, but it's working
Closing the bug.
