### ISSUE TITLE
Wiki 2.0 registration page issues

### ISSUE THREAD

**Issue by devp01** [Requarks/wiki#1022]
**Question**
The register form is showing malformed icons.

**Host Info (please complete the following information):**
OS: [e.g. Ubuntu 18.04]
Wiki.js version: [e.g. 2.0.0-beta.275]
Database engine: [ mysql 8]

￼￼
![image](https://user-images.githubusercontent.com/46513658/64528838-11f58880-d327-11e9-97bd-110e71fd6226.png)

**Comment by devp01** [comment]
￼￼

**Comment by NGPixel** [comment]
Duplicate of #996 .

Fixed in upcoming release.
