### ISSUE TITLE
Search function works for unauthenticated users/users who do not have permissions.

### ISSUE THREAD

**Issue by oCroso** [Requarks/wiki#1023]
**Describe the bug**
An unauthenticated user is able to search and see all pages within the wiki from the homepage.  This is not a huge deal, but does disclose more information than one may want an unauthenticated user to see.

**To Reproduce**
1. Go to homepage.
2. Click on in search bar.
3. Begin typing to reveal page titles and an overview of wiki contents.
4. Uh oh!

**Expected behavior**
Unauthenticated or limited permission users should only be able to see what they are authorized to see, even via search bar.

**Screenshots**
![image](https://user-images.githubusercontent.com/14203477/64536360-f8cce780-d2e6-11e9-9814-785b6cd437c1.png)

**Host Info (please complete the following information):**
 - Kubernetes, Wikijs container.
 - Latest Wikijs Beta
 - Postgres 10.6

**Additional context**
None!

**Comment by NGPixel** [comment]
This is fixed in the upcoming beta.
