### ISSUE TITLE
Image modal not showing up

### ISSUE THREAD

**Issue by nportrait** [Requarks/wiki#1028]
**Describe the bug**
Add an Image modal doesn't display correctly.

**To Reproduce**
1. Edit a page
2. Click on the 'Insert Assets' icon on the left vertical bar.

**Expected behavior**
A modal should open displaying an interface to upload / insert an asset.

**Actual behavior**
The content of the modal doesn't display properly and is inserted at the bottom of the page instead.
Uploading an image works but there is no "Insert image" button to confirm insertion.
There is no error in the JS console.

**Screenshots**
![step1](https://user-images.githubusercontent.com/2052116/64687779-6d408b80-d48b-11e9-9eea-d3fca8398687.png)
![step2](https://user-images.githubusercontent.com/2052116/64687798-73cf0300-d48b-11e9-8f15-89292fe62a9e.png)
![step3](https://user-images.githubusercontent.com/2052116/64687808-77fb2080-d48b-11e9-9442-a5438664f184.png)
![step4](https://user-images.githubusercontent.com/2052116/64687812-7af61100-d48b-11e9-9dde-a5c761ca09b5.png)

**Host Info (please complete the following information):**
 - OS: Ubuntu 16.04 LTS
 - Wiki.js version: 2.0.0-beta.275
 - Database engine: postgreSQL 9.5.19

**Additional context**
1. Wiki.js is running behind an Apache server.
2. When the "Insert Assets" button is clicked, a graphql request shows in the network tab of the JS console :
![console](https://user-images.githubusercontent.com/2052116/64688247-3e76e500-d48c-11e9-80e9-394772f60c75.png)

**Comment by dweremeichik** [comment]
As far as the modal itself:
It appears to be a cascading issue with the CSS. The `position: fixed` property on the `editor-modal-media` class is being overridden by `position: relative` in the `v-sheet` class.

**Comment by jonathanrbowman** [comment]
For what it's worth, interestingly I have this same issue on my production server, but NOT in local development.

**Comment by dweremeichik** [comment]
Looks like this was previously an issue in #992

**Comment by nportrait** [comment]
Thanks for the info @dweremeichik, closing
