### ISSUE TITLE
Upgrader from 1.0.x to current beta version

### ISSUE THREAD

**Issue by herrlich10** [Requarks/wiki#1031]
**Question**
Is it possible to release an upgrader from 1.0.x to current beta version, so that users experiencing issues with v1 (which is no longer maintained) will at least have the choice to try the new beta version with their existing data and move on (of course, at their own risk). This will also speed up the testing process of the new version.

Thank you!

**Comment by NGPixel** [comment]
No, this is not the proper way to perform an upgrade from v1 and would likely lead to corrupt installation.

A proper tool will be available soon.
