### ISSUE TITLE
Vuetify error when navigating to admin as guest

### ISSUE THREAD

**Issue by felipeochoa** [Requarks/wiki#1033]
**Describe the bug**
When directly typing in an admin URL (e.g., /a/groups) and not logged in I received a "An unexpected error occured." message. The console had this to say:

```
[GraphQL error]: Message: Forbidden, Location: [object Object], Path: system,info,currentVersion
[GraphQL error]: Message: Forbidden, Location: [object Object], Path: system,info,latestVersion
[GraphQL error]: Message: Forbidden, Location: [object Object], Path: system,info,groupsTotal
[GraphQL error]: Message: Forbidden, Location: [object Object], Path: system,info,pagesTotal
[GraphQL error]: Message: Forbidden, Location: [object Object], Path: system,info,usersTotal
GraphQL execution errors for query 'info'
[ ... some objects ... ]
[Vuetify] [BREAKING] 'outline' has been removed, use 'outlined' instead. For more information, see the upgrade guide https://github.com/vuetifyjs/vuetify/releases/tag/v2.0.0#user-content-upgrade-guide

found in

---> <VAlert>
       <VSimpleTable>
         <VData>
           <VDataTable>
             <VCard>
               <AdminGroups> at client/components/admin/admin-groups.vue
                 <VContent>
                   <VApp>
                     <Admin> at client/components/admin.vue
                       <Root>
```

**To Reproduce**
1. Set up a fresh instance using `requarks/wiki:beta`
2. Log out from the initial admin profile
3. Navigate to 127.0.0.1:3000/a/groups

**Expected behavior**
I was checking to see if there would be some 400-type page

**Host Info (please complete the following information):**
 - OS: tested on Windows and CentOS
 - Wiki.js version: 2.0.0-beta.275 ~Not sure. Pulled docker image yesterday~
 - Database engine: postgres 11.4

**Comment by NGPixel** [comment]
The vuetify error is fixed in build 303.

**Comment by felipeochoa** [comment]
Is the graphql error fixed as well?

**Comment by NGPixel** [comment]
That's a "normal" error. You're trying to fetch resources you don't have access to.

A clearer message is displayed in the upcoming build.
