### ISSUE TITLE
Only two pages are printed when printing

### ISSUE THREAD

**Issue by Rijswijker** [Requarks/wiki#1034]
When a print job is started (via the print icon in a article), only two pages are printed instead of the entire article.
I tested it on multiple computers with the same result.
Also on the Wiki.js website > Docs > 2.0 Beta Docs, the same problem occours.

**Comment by NGPixel** [comment]
Could only replicate with Firefox.

Chrome, Edge and Safari works fine.

**Comment by NGPixel** [comment]
Fixed in 2.3
