### ISSUE TITLE
Azure Authentication and local stopped to work

### ISSUE THREAD

**Issue by D3mon86** [Requarks/wiki#1035]
After Upgrade to version 303 whet trying to use any authentication getting following error:
 Oops, something went wrong...
Expected unsigned integer at id, got 1,1

**Host Info (please complete the following information):**
 - OS: Azure Web app with docker
 - Wiki.js version: Wiki.js 2.0.0-beta.303
 - Database engine:mssql

**Comment by D3mon86** [comment]
Seems DB was corrupted after installing new version now with recreating db it start working but you are not able to create home page. Getting following error:
GraphQL error: both cols and values must have same dimensions

**Comment by RichardD2** [comment]
Exactly the same problem here.

How do you recreate the database?

**Comment by D3mon86** [comment]
Seems this issue resolved here https://github.com/Requarks/wiki/issues/1036

**Comment by RichardD2** [comment]
Thanks. After applying that fix and deleting and recreating our home page again, it seems to be working.
