### ISSUE TITLE
Searching Unicode Characters Not Working, Any plan on this?

### ISSUE THREAD

**Issue by sageahn** [Requarks/wiki#104]
### Actual behavior
search keyword with Unicode encoded is not working

### Expected behavior
search result should be displayed

**Comment by NGPixel** [comment]
By unicode characters, you mean non-latin characters like CJK or arabic? CJK and arabic will be supported in Beta 12. Otherwise please provide an example of keywords that are not working.

**Comment by sageahn** [comment]
Yes, CJK is what I mean. That's good news. Thanks alot. Your wiki project is really good and I am happy to find what I eager to have. :-)
