### ISSUE TITLE
email address mailto links don't work

### ISSUE THREAD

**Issue by ethanmdavidson** [Requarks/wiki#1041]
**Describe the bug**
When an email address (e.g. test@gmail.com) is entered in the markdown editor, it will be rendered correctly in the preview pane as a mailto link (`mailto:test@gmail.com`). However, when the page is saved, the mailto link is rendered improperly (page path is prepended, making it a link to `http://mywikijs.com/en/pagename/mailto:test@gmail.com`). 

**To Reproduce**
1. Create a new page (or edit an existing page)
2. Enter an email address in the page body (e.g. `test@gmail.com`)
3. Click on the link in the preview. It will open your email client and fill `test@gmail.com` into the 'to' field.
4. Save the page and close the editor
5. Click on the email address link on the page. Instead of the email client opening, you are directed to a page which simply displays the text "Not Found".

**Expected behavior**
Email client is opened with the 'to' field filled.

**Host Info (please complete the following information):**
 - OS: CentOS 7.6
 - Wiki.js version: 2.0.0-beta.303
 - Database engine: postgres 11.5 
- Node.js version: 10.16.3

**Workaround**
You can work around this bug by explicitly specifying the mailto link, e.g. 
`[test@gmail.com](mailto:test@gmail.com)`

**Comment by NGPixel** [comment]
Fixed by 06250c4f039b6467f9aac57e34e467e01ec43224
