### ISSUE TITLE
No search result for Chinese characters

### ISSUE THREAD

**Issue by quickerlab** [Requarks/wiki#1043]
No search result for Chinese characters when searching some strings in Chinese  article page.
When I checked the pages table in database, I found the "content" column filled with what I wrote.
But  in 'render' column, all Chinese characters converted to "xXXXX', such as: "x9996",   the unicode coding.
And the "Database - PostgreSQL" search engine uses 'render' column to index page.
https://github.com/Requarks/wiki/blob/master/server/modules/search/postgres/engine.js#L152
So you must search "x9996" to find result, not real characters.

**Comment by NGPixel** [comment]
Fixed by 744e6e3248ae4b2f60fac606375eaf1db8828723
