### ISSUE TITLE
What is the format for db.host in config.yml

### ISSUE THREAD

**Issue by K69G4JRA725W** [Requarks/wiki#1045]
I try to get the Beta version to work with MySql8.0. The database server runs without problems. But when I run "node server", I get the following message:

error: Database Connection Error: ER_NOT_SUPPORTED_AUTH_MODE undefined:undefined

config.yml content:
  type: mysql
  # PostgreSQL / MySQL / MariaDB / MS SQL Server only:
  host: localhost
  port: 3306
  user: root
  pass: G6k9q!n&S4@8
  db: test-wikijs
  ssl: false

If I change host to  http://localhost or https://localhost, I get this message:

Database Connection Error: ENOTFOUND undefined:3306

I  use Windows 10 as development platform.

**Comment by NGPixel** [comment]
https://docs.requarks.io/en/troubleshooting#mysql-client-does-not-support-authentication-protocol-requested-by-server-consider-upgrading-mysql-client
