### ISSUE TITLE
Grayed-out article if browser width is smallish

### ISSUE THREAD

**Issue by CharlesB2** [Requarks/wiki#1046]
**Describe the bug**
If browser window is small (like 1024 pix), when landing on any wiki page, the wiki article view is grayed out in favor of the side bar. To un-grey and read the article, user has to click somewhere, which can be perceived as annoying.

**To Reproduce**
Go to a wiki page with browser window width at 1024 pixels, or use [Firefox responsive design mode](https://developer.mozilla.org/en-US/docs/Tools/Responsive_Design_Mode).

![image](https://user-images.githubusercontent.com/333806/65137983-8b1d6b80-da0a-11e9-9340-ab1549167338.png)

**Expected behavior**
The page isn't greyed out

**Host Info (please complete the following information):**
Problem seen on https://docs.requarks.io/, with Wiki.js 2.0

**Comment by NGPixel** [comment]
Fixed by dd3699b5012fb5720fc28a5d24e40f41d85ed512
