### ISSUE TITLE
Admin permissions have (almost) no effect

### ISSUE THREAD

**Issue by TheMightyZeus** [Requarks/wiki#1052]
Enabling every permission available for users other than the built-in administrator doesn't allow those users to see the administration link, so they have no way of accessing navigation, users, groups, etc. I can manually navigate to /a/ and seem to be able to manage the things I have permissions for, but "An unexpected error occured." pops up, and not everything works. (For example, the badges showing number of users, roles, pages, all show 0). In fact users who aren't even signed in can access /a/ manually, though not really see anything, but that's a separate issue.

**Steps to reproduce the behavior:**
Create a group, give it some or all of the Users or Administration permissions. Sign in using an account other than the admin which is assigned to that group. Click on the profile button in the top corner, where the admin can access the administration link. There will be no such link, so the user can't manage users, groups, theme, navigation, etc.

**Expected behavior:**
Users should be able to navigate to the administration area if they have permissions that can only be used there.

Administration link (visible for admin, doesn't appear for anyone else)
![image](https://user-images.githubusercontent.com/7672450/65350632-bd1a0380-dbab-11e9-9a5b-5cbb04b53fcd.png)

 - OS: Ubuntu Linux (bionic) 18.04 x64
 - Wiki.js version: 2.0.0-beta.303
 - Database engine: PostgreSQL 10.10

**Comment by NGPixel** [comment]
Fixed by 3db491a8a4eeb3e3e120c3f11f7ed3beda7633a5
