### ISSUE TITLE
Typed text is not visible if enough tags are used in Page properties

### ISSUE THREAD

**Issue by supersasho** [Requarks/wiki#1054]
**Describe the bug**
Typed text is not visible if enough tags are used in Page properties.

**To Reproduce**
1. Create a new page
2. Click on tags textbox
3. Write down multiple tags (depending on page width, in my case 8 and above)
4. The text you are writing for next tag isn't visible, only parts of a characters

**Expected behavior**
The text should be visible on new line probably.

**Screenshots**
<img width="750" alt="2019-09-21_11:25" src="https://user-images.githubusercontent.com/1937918/65371382-5ce69880-dc63-11e9-9fbc-6db020a603a1.png">

**Host Info (please complete the following information):**
 - OS: KDE neon User Edition 5.16 + Docker version 19.03.2, build 6a30dfc
 - Wiki.js version: 2.0.0-beta.303
 - Database engine: postgres (PostgreSQL) 11.5 (Debian 11.5-1.pgdg90+1)

**Comment by patrickdemers6** [comment]
I will take a shot at this.

**Comment by NGPixel** [comment]
Fixed for 2.3
