### ISSUE TITLE
Unable to visit wiki.js 303 fresh install with MariaDB

### ISSUE THREAD

**Issue by Trexon25** [Requarks/wiki#1056]
**Describe the bug**
After a clear installation of Wiki.JS I'm unable to visit wiki.js. The error is "error: CRITICAL ERROR: Guest user is missing!" but in the database I can see the guest account.

The setup is working fine, so I can add my admin account but as soon as I want to connect to the website the wiki.js stops.

I'm using a HaProxy Setup with a MariaDB Galera cluster.

**To Reproduce**
1. fresh install (https://docs.requarks.io/en/install/linux)
2. Add Admin Account
3. Try to load wiki.js

**Expected behavior**
I expected that wiki.js would load normally

**Screenshots**
- 

**Host Info (please complete the following information):**
 - OS: Debian 10
 - Wiki.js version: 2.0.0-beta.303
 - Database engine: 10.4.7-MariaDB

**Additional context**
-

**Comment by Dymnarisk** [comment]
I just got this as well, I traced the error message to server/models/users.js, line 705: 
` const user = await WIKI.models.users.query().findById(2).eager('groups').modifyEager('groups', builder => {
      builder.select('groups.id', 'permissions')
    })
if (!user) {
      WIKI.logger.error('CRITICAL ERROR: Guest user is missing!')
      process.exit(1)
    }`

However, in my db the guest user has id 6. I changed `.findById(2)` to `.findById(6)` and the page loads.

**Comment by NGPixel** [comment]
The guest user is hardcoded to be ID 2. If it's anything else, then something went wrong during the installation.

**Comment by Trexon25** [comment]
I changed it to 3. And now it also works.
First I thought that my ID is maybe wrong because of the auto increment because I first installed WikiJS in a wrong directory. But I created a new database in MariaDB and my Guest user got ID 3 so I changed it in the code.

**Comment by NGPixel** [comment]
Added fixed IDs for next beta to prevent these issues (f9e10d5107868623b431f416bcd6241b00d3b62b)
