### ISSUE TITLE
S3 storage - Existing pages are not pushed to the S3 bucket

### ISSUE THREAD

**Issue by devp01** [Requarks/wiki#1057]
**Question**
Describe in details what you are trying to achieve and where do you need guidance.

**Host Info (please complete the following information):**
OS: [e.g. Ubuntu 18.04]
Wiki.js version: [e.g. 2.0.0-beta.303]
Database engine: [e.g. mysql 8]
Storage - S3

The existing pages are not pushed to the S3 bucket target. I created a new page that is saved on the S3 bucket. How do you push the existing pages /var/wiki/data/repo/ to S3 bucket? Why is it not pushed to the target?

**Comment by NGPixel** [comment]
You can't at the moment. Only new pages / modified pages will be pushed.

Hopefully @andrewsim can add the missing action to the storage module. (refer to the git module as reference)

**Comment by NGPixel** [comment]
Added in upcoming 2.1
