### ISSUE TITLE
Breaking Changes

### ISSUE THREAD

**Issue by rmattler** [Requarks/wiki#1059]
I've been evaluating wiki frameworks and I like the 2.0 version best.  I know you can't give me a 100% answer and I realize that I'm taking a risk using beta software.  With all that being said, do you anticipate breaking changes like new database structure before the product goes in production. The state the product is in right now works for our needs. Anybody else using the beta?

Thanks for all your hard work.

**Comment by NGPixel** [comment]
You can safely use the beta. Just make sure to have a proper backup strategy for your database.

**Comment by rmattler** [comment]
Thanks for your response.
