### ISSUE TITLE
querySelector cannot find table of contents id

### ISSUE THREAD

**Issue by rexrod** [Requarks/wiki#1061]
**Describe the bug**

Clicking on the table of contents does not find the referenced ID when there is a number at the beginning.

**Screenshots**

where was clicked:
![image](https://user-images.githubusercontent.com/3979741/65603401-97a64480-df73-11e9-8eb0-78a96d5c38b8.png)

console error:
![image](https://user-images.githubusercontent.com/3979741/65604230-164fb180-df75-11e9-972d-fd5cc08d9d71.png)

**Host Info**

 - Browser: Opera 63
 - Wiki.js version: 2.0.0-beta.303

**Additional Info**

Only happens when header starts by number.
Occurs in Markdown and Visual Editor file.

**Comment by NGPixel** [comment]
Yes this is normal, as a CSS id selector cannot start with a number. A fix to prefix these ids will be added soon.

**Comment by NGPixel** [comment]
Fixed by 37ce116dd2bee0471650c335ffb3ccf84323e5b8
