### ISSUE TITLE
[GraphQL error: Invalid locale or namespace] when use pt-br language

### ISSUE THREAD

**Issue by yanBrandao** [Requarks/wiki#1062]
**Describe the bug**
The request made by frontend is sended 'pt-BR' but in database code is saved as 'pt-br' for this, the exception is thrown *Invalid locale or namespace*.

**To Reproduce**

1. On the Admin area, go to "Locale"
2. Download any locale with country specification, like *pt-br*
3. Click on "Apply" on top-right corner

**Expected behavior**
Should load language bundle and translate variables.

**Screenshots**

File: server/core/localization.js
```java
async getByNamespace(locale, namespace) {
    if (this.engine.hasResourceBundle(locale, namespace)) {
      let data = this.engine.getResourceBundle(locale, namespace)
      return _.map(dotize.convert(data), (value, key) => {
        return {
          key,
          value
        }
      })
    } else {
      throw new Error('Invalid locale or namespace')
    }
  }
```

Database line:

![image](https://user-images.githubusercontent.com/5366951/65619527-4eafb980-df8e-11e9-960c-04516eeb96ac.png)

Frontend language request:

![image](https://user-images.githubusercontent.com/5366951/65619560-5cfdd580-df8e-11e9-914b-f8b9d34db53d.png)

**Additional context**
I think the solution is to change request in frontend or change language code to 'pt-BR'

**Comment by NGPixel** [comment]
Fixed by 41716e52a6f2be131cde38b7ee150108c13efdcf
