### ISSUE TITLE
Page with '.' in path returns 404

### ISSUE THREAD

**Issue by Znuff** [Requarks/wiki#1063]
**Describe the bug**
Creating a page with a `.` in it's path results in 404 errors

**To Reproduce**
1. Create a new page with the path as `test.com`
2. Select Markdown (probably not relevant)
3. On the next modal window, "Page Properties", the path will show up as `test`
4. Edit the path to `test.com`
5. Write the content of the page as desired
6. Click on "Create" to save the page
7. You will be directed to a "not found" page

Further more, you won't be able to edit the page if you go into `Settings -> Pages`, but you will see the page there. 

The only way to fix it is to edit the database externally.

**Comment by NGPixel** [comment]
You shouldn't put dots in your paths. This is reserved for files.

I'll add a warning if you're trying to create / save a page with a dot in the path.

**Comment by FibreFoX** [comment]
Stupid question, but why having this limitation? Wouldn't it be better to support page-paths being whatever the user (me) wants? Would be nice to have some information about the "why" 😸

**Comment by NGPixel** [comment]
Because dots are reserved for actual asset files. How is the app supposed to know if something.pdf is an actual page or a file you want to download?

It's also simply best practice to not use dots in paths unless you're referencing a file.

**Comment by FibreFoX** [comment]
How about having a "prefix" like "/file/..." as part of the URL? I don't know the internals, but it doesn't sound right :) thats why I'm asking

**Comment by NGPixel** [comment]
No, as that would break all previous installations that didn't use this prefix.

**Comment by Znuff** [comment]
Can't you just check if the file exists and is readable, first? Just a curiosity.

**Comment by NGPixel** [comment]
Which would incur a round-trip to the database every single time. If it was that simple, it wouldn't be an issue. Not mentioning the fact that this would allow users to create pages ending in common file types extensions. This is simply bad practice and will not be supported.

**Comment by FibreFoX** [comment]
I'm still having trouble to see any kind of "bad practice", it would more be a performance-issue.

**Comment by NGPixel** [comment]
Pages can no longer be created with dots or spaces in the path. (95535aa3b02982378a7f0642fb26ea7b6197eaf0)

@FibreFoX Dots are for domain name separators and file extensions, period. Even Google says it's a [bad idea](https://www.seroundtable.com/google-decimal-points-in-urls-21435.html). It causes several accessibility issues. There's literally no valid use case for using dots over industry standard separators like dashes.
