### ISSUE TITLE
[Algolia Search] - GraphQL error: Record at the position 0 is too big size

### ISSUE THREAD

**Issue by candypaint** [Requarks/wiki#1065]
### Actual behavior
When saving a page I get the error. 

GraphQL error: Record at the position 0 is too big size=11156 bytes. Contact us if you need an extended quota.

### Expected behavior
Expect the document to be saved. 

### Steps to reproduce the behavior
Create a page with a lot of content.

**Comment by candypaint** [comment]
Issue is related to Algolia integration - once the search engine was switched to PostgreSQL the issue was resolved.

**Comment by wlfcss** [comment]
same issue 
`Document exceeds maximum size allowed by Algolia.`
