### ISSUE TITLE
Home page does not sync to Git

### ISSUE THREAD

**Issue by eeshugerman** [Requarks/wiki#1067]
**Describe the bug**
The home page does not sync to the Git storage target

**To Reproduce**
1. Spin up instance using [the `docker-compose.yml` example](https://docs.requarks.io/install/docker)
2. Log in and create a home page when prompted
3. Configure Git storage in UI with basic auth, bidirectional sync
4. Wait and/or run "Add Untracked Changes" and "Force Sync" actions

**Expected behavior**
The home page is pushed to the remote Git repo

**Host Info (please complete the following information):**
 - OS: Docker
 - Wiki.js version:  2.0.0-beta.303
 - Database engine: postgres 9.6

**Additional context**
- I created a (non-home) test page which was pushed to the Git repo as expected.

- I can see the home page in the database with `psql`.

When I run "Add Untracked Changes", the logs show:
```
2019-09-27T04:17:47.649Z [MASTER] info: (STORAGE/GIT) Adding all untracked content...
2019-09-27T04:17:47.653Z [MASTER] warn: page.getFileExtension is not a function
```

**Comment by NGPixel** [comment]
Fixed by 454da698a1151090e92edc0210d231cabd26ae72

**Comment by eeshugerman** [comment]
🔥 that was fast!

**Comment by donchrizz** [comment]
Is this going to be in a next release, or can i pull it in another way?
