### ISSUE TITLE
Text in code block unreadable when printed

### ISSUE THREAD

**Issue by Rijswijker** [Requarks/wiki#1068]
**Describe the bug**
When a page is printed the text in the code block section is almost unreadable due shadow.

**To Reproduce**
Put a text in a code block and click on the printer icon and print to paper or pdf

**Expected behavior**
Black or color coded text without shadow

**Screenshots**
![2019-09-27_14-19-30](https://user-images.githubusercontent.com/4473594/65769354-ad626800-e133-11e9-84be-3f1c43a99f96.png)

CSS override does not help, the override is ignored

```
code[class*=language-],
pre[class*=language-] {
	color: #fff;
	background: 0 0;
	font-family: Consolas, Monaco, Andale Mono, Ubuntu Mono, monospace;
	font-size: 1em;
	text-align: left;
	text-shadow: none;     <-------- CHANGED VALUE
	white-space: pre;
	word-spacing: normal;
	word-break: normal;
	word-wrap: normal;
	line-height: 1.5;
	-moz-tab-size: 4;
	-o-tab-size: 4;
	tab-size: 4;
	-webkit-hyphens: none;
	-ms-hyphens: none;
	hyphens: none
}
```

**Comment by NGPixel** [comment]
Fixed by ccc6a776fc02bb39579dc1f08104ae3d059aadf5
