### ISSUE TITLE
How to create TOC

### ISSUE THREAD

**Issue by catbaxter** [Requarks/wiki#1069]
**Question**
Hi, could yot please provide step by step information how to orginize TOC like there

https://docs.requarks.io/install/requirements

So requirements -> TOC (Server Requirements, Node.js, Database and so on)

OS:  Ubuntu 18.04
Wiki.js version: Beta 2.0.0-beta.303
Database engine: Postgresql 11

**Comment by juliendms** [comment]
TOC is auto-generated based on the headers (lines that starts with #) in your markdown.

**Comment by NGPixel** [comment]
As @juliendms mentionned, it's automatically generated when you save the page, based on the headers.

**Comment by catbaxter** [comment]
Ok, could create the TOC, but how to add link to the left menu? Could you please share an example with page source?

**Comment by catbaxter** [comment]
Ah, I see, the navigation!
