### ISSUE TITLE
Healthz endpoint returning 503 rutinely 

### ISSUE THREAD

**Issue by Starefossen** [Requarks/wiki#1071]
**Describe the bug**

After about an hour of running (even without any load or traffic) the `/healthz` endpoint will start returning `"ok": false` with status code 503. No errors are displayed in the logs and the 

**To Reproduce**

Set up according to the documentation with PostgreSQL and keep it running for some time while chcking the `/healthz` endpoint.

**Expected behavior**

It shuld not give 503 error message without indicating that something is actually wrong.

**Screenshots**

```
Warning  Unhealthy  2m21s (x2952 over 45h)  kubelet, dell-01  Readiness probe failed: HTTP probe failed with statuscode: 503
```

**Host Info (please complete the following information):**
 - OS: Docker `requarks/wiki:beta` in Kubernetes
 - Wiki.js version: `2.0.0-beta.303`
 - Database engine: `PostgreSQL 11.5.0`

**Additional context**

**Comment by NGPixel** [comment]
Error 503 means the db connection pool is at 0.

Try setting `pool.min: 0` in your config.yml and restart the app.

**Comment by Starefossen** [comment]
Hi @NGPixel and thank you for the answer. I redeployd wiki with `pool.min` set to `1` and I have had no 503 errors and restarts since. Thanks a lot for making this ❤️
