### ISSUE TITLE
Configuration as code -- v1 vs v2

### ISSUE THREAD

**Issue by eeshugerman** [Requarks/wiki#1072]
Comparing the `config.yml` examples for v1 vs v2, it would appear that a number of items have been removed in the latter, eg Git connection info, admin email, theme, etc. Can these options still be specified in `config.yml` in v2? Or are there plans to add back support for any of them? Or replace with environment variables?

**Comment by NGPixel** [comment]
No. These settings live in the database, alongside the content data.

If you need to rebuild an environment, you would restore or reconnect to the same database anyway, so making all settings available from the config file is not needed.
