### ISSUE TITLE
Question about remote storage / push to target

### ISSUE THREAD

**Issue by eeshugerman** [Requarks/wiki#1073]
For S3 and Spaces storage targets, the only available mode is "Push to target":

>Content is always pushed to the storage target, overwriting any existing content. This is safest choice for backup scenarios.

If for some reason the database gets wiped, would that mean that these storage targets will be overwritten with no content (ie removed)? If so, wouldn't it make sense to enable the "Create Daily Backups" feature for these storage targets?

**Comment by NGPixel** [comment]
No, as that's not how it works.

In order to delete a file from S3, you'd need to actually perform a page deletion from the UI. Deleting records from or wiping the DB will have zero effect on the data stored in S3.
