### ISSUE TITLE
"public" rule in config.yml is broken

### ISSUE THREAD

**Issue by lnoel-everlaw** [Requarks/wiki#1077]
**Describe the bug**
Users are able to view content without authenticating even when "public" is set to: "false" in `config.yml`.

**To Reproduce**
1. Go to `config.yml`. Set `public: false`.
2. Restart the server.
3. Open an incognito browser window and view content without authentication.

**Expected behavior**
Users are required to authenticate before viewing any content.

**Screenshots**

**Host Info (please complete the following information):**
 - OS: Ubuntu 18.04.2 LTS
 - Wiki.js version: 2.0.0 beta 303
 - Database engine: postgres 10.10

**Comment by yuyudhan** [comment]
Has there been any update on this issue? Still facing the same on the stable version 2.0.12.

**Comment by yuyudhan** [comment]
Oh thanks, actually the feature is available through group permissions edit, for anyone who stubmbles upon this.

![image](https://user-images.githubusercontent.com/3090231/69545521-032e8180-0fb8-11ea-93f6-d539552a25e7.png)
