### ISSUE TITLE
User can be added more than one time in the same group

### ISSUE THREAD

**Issue by sbonaime** [Requarks/wiki#1081]
With 2.0.0 303 :
I add Guest to Admin group. 
A second time I add Guest to Admin group
Then I can see two time Guest in the admin Group
![Capture d’écran 2019-10-03 à 03-10-19 12 11 51](https://user-images.githubusercontent.com/750709/66128150-87363f80-e5ed-11e9-873e-64e44407f1a3.png)

**Comment by NGPixel** [comment]
On another note, you should never add the guest user to the admin group. You're essentially letting anyone change critical settings.

**Comment by stopcharla** [comment]
Hey @NGPixel I would like to contribute to the project. Can you please help me with the basic stuff to fix this bug?

**Comment by NGPixel** [comment]
Fixed by c5ce6bcbaa17cc3f9bbdcab592ce57344f1a7c80

Sorry @stopcharla, I just saw your comment! Let me know if there's any other bug or improvement you'd like to tackle instead.
