### ISSUE TITLE
Can’t seem to change the path of an existing page within the admin area.

### ISSUE THREAD

**Issue by jonathanrbowman** [Requarks/wiki#1082]
I’d like to change the path of a page. Trying to do it from within the page edit screen, It was grayed out. So, I moved into the Administration > Pages area and clicked on the page. I see an edit icon next to the path, but clicking it currently doesn’t do anything.

1. Go to Administration > Pages
2. Click on a page
3. Click the edit icon next to the path
4. Nothing happens

**Expected behavior**
Able to edit the page path.

 - OS: Centos7
 - Wiki.js version: 2.0.0-beta.303
 - Database engine: postgres 9.7
 - Interacting with it on a new iPad, running iOS 13

Thanks!

**Comment by ethanmdavidson** [comment]
I believe this is not yet supported, but should be [in the next release](https://requarks.slack.com/archives/C49J7AB8R/p1569685687099500)

**Comment by NGPixel** [comment]
Will be available in the next release.
