### ISSUE TITLE
Search Function hangs/throws error

### ISSUE THREAD

**Issue by fusionetics-cecelia** [Requarks/wiki#1086]
**Describe the bug**
When using the search function, if a search term is entered and then the 'Enter' key is pressed, the console throws a Type error and the search hangs. This doesn't seem to happen if you simply type the search term and then wait for results to appear without hitting 'Enter'. This occurs on the wiki.js documentation page as well.

**To Reproduce**
1. Go to wiki homepage
2. Click on search bar and type in a term then press the 'Enter' key
3. See error

```
app.9a3d737249f89b3b4388.js:89 
TypeError: Cannot read property 'length' of undefined
    at a.t (ui-extra.1b40d9638c73b36c5fef.js:2)
    at a.t._render (app.9a3d737249f89b3b4388.js:89)
    at a.i (app.9a3d737249f89b3b4388.js:89)
    at vn.get (app.9a3d737249f89b3b4388.js:89)
    at vn.run (app.9a3d737249f89b3b4388.js:89)
    at mn (app.9a3d737249f89b3b4388.js:89)
    at Array.<anonymous> (app.9a3d737249f89b3b4388.js:89)
    at Zt (app.9a3d737249f89b3b4388.js:89)
```

**Expected behavior**
Search results to appear regardless of whether user hits the 'Enter' key

**Screenshots**
Video of behavior: https://drive.google.com/file/d/1Jmf3VEnBh6ni5c0Q2B5XmHh1zo2C7NQi/view

**Host Info (please complete the following information):**
 - OS: Windows 10/Chrome Browser
 - Wiki.js version: 2.0.0-beta.303
 - Database engine: N/A

**Additional context**
This occurs at https://docs.requarks.io/ as well as on our own wiki page.

**Comment by NGPixel** [comment]
Fixed by d69dde1df5c2db74c10fe86ead50a63528c4487d
