### ISSUE TITLE
Adding my own navbar

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [Requarks/wiki#1096]
**Question**
I would like to add my website's navbar to my wikijs so that my wiki looks like its apart of my website rather than make the visitors feel like they traveled somewhere else.

**What I've tried**
* Adding it via HTML Head Injections 
  * that kind of works but it loks ugly . . .
  * my navbar covers most of wikijs's navbar 
   *after scrolling l it becomes more obvioius that my navbar was only hiding the wiki's.
* Using Javascript to alter the dom
   * didn't work at all
   * not a js programmer but I believe the header values are being dynamically generated and is unknown at initial render

**Host Info (please complete the following information):**
OS: Debian 9, Docker
Wiki.js version: 2.0.0-beta.303
Database engine: postgres 11.5

**Comment by NGPixel** [comment]
This will be possible with the introduction of themes, coming in a future build. You'll be able to completely alter the looks of your wiki.

At the moment, this is not possible and I would avoid using JS scripting to alter the look.
