### ISSUE TITLE
Create a 'Deploy to Heroku' Button

### ISSUE THREAD

**Issue by spencerthayer** [Requarks/wiki#110]
It would be super useful if we could get a `Deploy to Heroku` button which would enable users to easily deploy your software to a Heroku instance without ever leaving the web browser. And with just a little configuration on the users end they'll have something running almost instantly. I propose the button because it is ideal for communities who need to make decisions quickly with the flexibility of something like Heroku.

It's very simple to do, just make sure that an app.json file is located in the repo root directory. More about Heroku deploy buttons [here](https://devcenter.heroku.com/articles/heroku-button).

[![Deploy](https://www.herokucdn.com/deploy/button.png)](https://heroku.com/deploy?template=https://github.com/Requarks/wiki)

**Comment by NGPixel** [comment]
This is already developed and ready for the next beta release, which will be released later this week.

**Comment by spencerthayer** [comment]
```xml
<heros>You!</heros>
```

**Comment by NGPixel** [comment]
As a note, it wasn't as easy as creating an app.json 😄
Many changes had to be done to work as a stateless app.
