### ISSUE TITLE
LDAP Connection issue

### ISSUE THREAD

**Issue by Paulo-Reis243** [Requarks/wiki#1102]
**Question**
Cant config LDAP connection, when i try login the endponit get an empty response, i used the same configurations in other plataform and it works.

![issue](https://user-images.githubusercontent.com/45025471/66846662-1faeb700-ef40-11e9-94b9-60ea5c1ba6cf.png)

**Host Info**
OS: [e.g. Ubuntu 18.04, Docker]
Wiki.js version: [e.g. 2.0.0-beta.115]
Database engine: [e.g. postgres 9.7, mysql 5.7]

**Comment by NGPixel** [comment]
In the administration area, go to **Developer Tools** > **Flags** and enable the **LDAP Debug** flag (and Apply changes).

Any LDAP login attempts will now be logged to the console (or docker logs for your container) with extra debug info.

**Comment by NGPixel** [comment]
Also your Search Filter value doesn't seem right. It should be a property filter (e.g. `(uid={{username}})`), not a object query.

**Comment by vtjc2002** [comment]
@Paulo-Reis243 your search filter seems incorrect as stated by NGPixel
here is what worked for me
(&(objectcategory=person)(objectclass=user)(|(samaccountname={{username}})(mail={{username}})))
