### ISSUE TITLE
Auth0 integration doesn't work with subdomains

### ISSUE THREAD

**Issue by eeshugerman** [Requarks/wiki#1103]
**Describe the bug**
If Wiki.js is at a subdomain, eg wiki.example.com, the Auth0 integration doesn't work.

**To Reproduce**
1. Setup Wiki.js at a subdomain
   - Use the [Docker Compose example](https://github.com/Requarks/wiki/blob/master/dev/examples/docker-compose.yml)
   - Use NGINX to `proxy_pass` wiki.example.com to the host port specified in `docker-compose.yml`
2. Follow the Auth0 guide [here](https://docs.requarks.io/en/auth/auth0)
3. Logout of the Wiki.js admin account
4. Click "Auth0" on the Wiki.js login page

**Actual behavior**
Redirected to `https://example.com/login/auth0/callback?code=<...>&state=<...>`. Note the subdomain is missing. In my case, this means a 404 from NGINX.

If I add the subdomain to the "Allowed Callback URLs", "Allowed Web Origins", and "Allowed Logout URLs" fields in Auth0, (which I did not do originally because it is not present in the values under "Configuration Reference" in Wiki.js), and then try again, I am redirected to an Auth0 page with the following message:
> Oops!, something went wrong
Callback URL mismatch.
The provided redirect_uri is not in the list of allowed callback URLs.
Please go to the Application Settings page and make sure you are sending a valid callback url from your application.

**Expected behavior**
Able to login using Auth0

**Host Info**
 - OS: Docker
 - Wiki.js version: [e.g. 2.0.0-beta.303
 - Database engine: [e.g. postgres 9.6.15]

My impression is that Wiki.js is should detect that it is at a subdomain, and this should be reflected in the values under "Configuration Reference" and in the `redirect_uri` provided to Auth0. But perhaps this is actually expected behavior for my setup, and instead I need to handle this with NGINX tricks?

**Comment by eeshugerman** [comment]
Nevermind! I'd forgotten to include the subdomain in the "Site URL" field under "General" :man_facepalming: .

**Comment by JWCook** [comment]
@eeshugerman I'm glad you posted this, because I made the same silly mistake!

I used a temporary domain when originally setting up Wiki.js, forgot about it, and later when adding Keycloak auth I spent a couple hours trying to figure out why the callback URL was wrong! 🤦‍♂️
