### ISSUE TITLE
Graphql editor

### ISSUE THREAD

**Issue by arthurlogilab** [Requarks/wiki#1107]
**Question**
Testing out wikijs for a project I was attracted to the graphql functionnality, it seems to be a "placeholder" functionnality so far. Which issue can I follow to see the progress on this ? 

Other question : is it to create graphql based documents on the information in the wiki, or will it also be useful for other "external" graphql endpoints ? For example in our use case it would be to build pages with data coming from gitlab's graphql endpoint.

**Comment by NGPixel** [comment]
I believing you're referencing the API / GraphQL editor choice when creating a new page?

You'll be able to describe and document your APIs (kind of like Swagger does). As for GraphQL, you'll need to provide the endpoint and docs will automatically be generated using the introspection.

You can follow this feature:
https://wiki.js.org/feedback/p/api-graphql-docs-editor

**Comment by arthurlogilab** [comment]
OK, that seems like a useful feature. I'm following the issue on the feedback app.

But I'm not sure it's what I'm describing the original issue. Any ideas if crafting documents using an external graphql API would be possible (generate a table from a graphql query inside a wiki document that would reader at read time) ? 

Do you have any plans for a plugin type system ?
