### ISSUE TITLE
Selected search option’s text hard to read

### ISSUE THREAD

**Issue by Rexogamer** [Requarks/wiki#1108]
**Describe the bug**
When searching for something, on the highlighted result, the text is hard to read.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start a search
2. Hover over an item
3. Try to read the text

**Expected behaviour**
The text should be easy to read.

**Screenshots**
![9C3DA42D-9649-4265-A5D4-BE7B95867B75](https://user-images.githubusercontent.com/42586271/66957530-51b63b00-f05e-11e9-8ceb-7f410dfc876b.jpeg)

**Comment by NGPixel** [comment]
This is already fixed in the upcoming build release.
