### ISSUE TITLE
Not Able to Add Untracked Changes to Git/Not Able to Delete Old Pages After Enabling Git.

### ISSUE THREAD

**Issue by vulfilla** [Requarks/wiki#1109]
**Question**
After enabling the Git storage provider, cannot delete pages created before enabling git and "Add Untracked Changes" does not add previously created pages to the repo.

**To Reproduce**
1. Go to Storage in the Administratration page.
2. Configure git to the instructions at https://docs.requarks.io/en/storage/git
3. Attempt to delete page or use Add Untracked Changes
4. When deleting page get error "fatal: pathspec './pagename.md' did not match any files"
5. When using Add Untracked Changes no error is presented. systemctl status wiki shows this message:
[MASTER] info: (STORAGE/GIT) Adding all untracked content...
[MASTER] warn: page.getFileExtension is not a function

**Expected behavior**
To be able to delete pages and to add old pages to git.

**Host Info (please complete the following information):**
 - OS: Ubuntu 18.04.3 LTS
 - Wiki.js version: 2.0.0-beta.303
 - Database engine: PostgreSQL 10.10
 - git version 2.17.1

I'm unsure if I have configured something wrong or if this is a bug at this time.

**Comment by NGPixel** [comment]
Fixed in RC1
