### ISSUE TITLE
Maria Db : migration file "2.0.0-beta.1.js" failed 

### ISSUE THREAD

**Issue by Mateo111001** [Requarks/wiki#1113]
Os : ```   CentOS Linux release 7.7.1908 (Core)  ```
Node Version : ``` v12.11.1  ```
Npm Version : ``` 6.11.3 ```
Maria db version : ``` 10.4.8-MariaDB ```

hey guys , 

i'm trying to install wiki.js and its give me this error: 
```
[voipiran@vps-118-82 docs]$ node server
Loading configuration from /home/voipiran/public_html/docs/config.yml... OK
2019-10-20T08:14:32.230Z [MASTER] info: =======================================
2019-10-20T08:14:32.296Z [MASTER] info: = Wiki.js 2.0.0-beta.303 ==============
2019-10-20T08:14:32.297Z [MASTER] info: =======================================
2019-10-20T08:14:32.297Z [MASTER] info: Initializing...
2019-10-20T08:14:34.425Z [MASTER] info: Connecting to database...
2019-10-20T08:14:34.715Z [MASTER] info: Database Connection Successful [ OK ]
migration file "2.0.0-beta.1.js" failed
migration failed with error: alter table `authentication` add primary key `authentication_pkey`(`key`) - Specified key was too long; max key length is 1000 bytes
2019-10-20T08:14:35.555Z [MASTER] error: Database Initialization Error: alter table `authentication` add primary key `authentication_pkey`(`key`) - Specified key was too long; max key length is 1000 bytes
```
And this is my ```config.yml```  db configuration:
```
db:
  type: mariadb
  # PostgreSQL / MySQL / MariaDB / MS SQL Server only:
  host: localhost
  port: 3306
  user: voipiran_docsuser
  pass: mypassword
  db: voipiran_docs
  ssl: false
  # SQLite only:
  storage: path/to/database.sqlite
```

I install it on mysql and its ok , but i want to install it on mariadb.
what should i have to do?
thanks.

**Comment by mitismirza** [comment]
Can somebody help please?

**Comment by tony-nz** [comment]
I suspect this is due to the DB collation, try and change it to utf8_bin

**Comment by mohammad-mahdi-kargar** [comment]
@tony-nz DB collation was on latin and i set to utf8 but still give me exactly same error.

**Comment by mohammad-mahdi-kargar** [comment]
@NGPixel sorry , can you please take a look?

**Comment by NGPixel** [comment]
Looks like a DB configuration issue, see
https://www.google.com/search?q=mariadb+Specified+key+was+too+long%3B+max+key+length+is+1000+bytes&oq=mariadb+Specified+key+was+too+long%3B+max+key+length+is+1000+bytes

**Comment by Sicklou** [comment]
Did you find any solution ?

**Comment by Mateo111001** [comment]
@Sicklou as ngpixel says its a database configuration issues , my issue was with the unicode i maipulation migration files in `server/db/migrations` and every table have string key , change the charset to `latin1`
for example in `authentication` table:
```
    // AUTHENTICATION ----------------------
    .createTable('authentication', table => {
      if (dbCompat.charset) { table.charset('latin1') }
      table.string('key').notNullable().primary()
```

**Comment by Sicklou** [comment]
> @Sicklou as ngpixel says its a database configuration issues , my issue was with the unicode i maipulation migration files in `server/db/migrations` and every table have string key , change the charset to `latin1`
> for example in `authentication` table:
> 
> ```
>     // AUTHENTICATION ----------------------
>     .createTable('authentication', table => {
>       if (dbCompat.charset) { table.charset('latin1') }
>       table.string('key').notNullable().primary()
> ```

Thanks for your reply.
The problem I'm facing is different. My default engine is Aria. When I switch to InnoDB the problem is solved but I wish I dont have too change the default engine.
