### ISSUE TITLE
Azure Web App documentation is missing the required database port

### ISSUE THREAD

**Issue by Kyberal** [Requarks/wiki#1115]
https://docs.requarks.io/en/install/azurewebapp is missing the required port for **Azure Database for PostgreSQL** which is **5432**.

At **2.2 Configure Web App** in the table under **2.** the following needs to be added:

`DB_PORT: 5432`

Failure to configure the aforementioned will result in the following error upon an App Service deployment:

> Database Connection Error: ERR_SOCKET_BAD_PORT undefined:undefined

Additionally **Azure Web App** in the documentation should be renamed to **Azure App Service** which is the correct service name.

**Comment by NGPixel** [comment]
Added to the docs.

**Comment by skingd** [comment]
I'm still getting this error, despite DB_PORT being configured and multiple start/stop/restart attempts.
