### ISSUE TITLE
Upgrade issues -2.0.0-rc.1 - Login screen is blank

### ISSUE THREAD

**Issue by devp01** [Requarks/wiki#1116]
**Describe the bug**
After upgrading from beta 303 to 2.0.0-rc.1 cannot login to the admin console. Admin console is a blank screen.

**To Reproduce**
1. Go to the website address. (wiki can be accessed but login screen is providing a blank screen)
2. Click on Login

Error-- Displaying a blank screen and not allowing to login.

**Expected behavior**
When you click on Login -> It should display the login screen.

**Screenshots**
![image](https://user-images.githubusercontent.com/46513658/67187507-fabab800-f407-11e9-9efe-ff941e600c48.png)

**Host Info (please complete the following information):**
 - **OS: [e.g. Ubuntu 18.04, ]**
 - **Wiki.js version: 2.0.0-rc.1** 
 - **Database engine: [mysql 8.0]****

**Additional context**

**Comment by NGPixel** [comment]
Can you open the Developer Tools console in your browser (F12) and reload the page. Do you have any errors?

**Comment by devp01** [comment]
I tested this on another instance.
the stylesheet is not getting applied. Cannot see the login screen. 
![image](https://user-images.githubusercontent.com/46513658/67263335-73cc1500-f4c5-11e9-9db1-ba1060da6ffd.png)

**Comment by NGPixel** [comment]
Please post the console errors, not the network tab.

**Comment by devp01** [comment]
@NGPixel 
Rebooted the instance and it is working fine now.
