### ISSUE TITLE
Can not create Administrator account

### ISSUE THREAD

**Issue by D3mon86** [Requarks/wiki#1117]
**Describe the bug**
Fresh installation can not  create an Administrator account

**To Reproduce**
Fresh installation when trying to create Admin account get following error.

`insert into [locales] ([code], [createdAt], [isRTL], [name], [nativeName], [strings], [updatedAt]) output inserted.[code] values (@p0, @p1, @p2, @p3, @p4, @p5, @p6) - Violation of PRIMARY KEY constraint 'locales_pkey'. Cannot insert duplicate key in object 'dbo.locales'. The duplicate key value is (en).`

**Screenshots**
![WikiError](https://user-images.githubusercontent.com/39269882/67205400-5db44b00-f418-11e9-802f-be4e3d2d2a0f.PNG)

**Host Info (please complete the following information):**
 - OS: Azure WebApp Container [Docker]
 - Wiki.js version: 2.0.0-rc.1
 - Database engine:Azure SQL

**Comment by NGPixel** [comment]
Fixed by b567413feefdeb229a1632abad685498350de612
