### ISSUE TITLE
Delete page fails with error

### ISSUE THREAD

**Issue by winkelement** [Requarks/wiki#1119]
**Describe the bug**
Trying to delete a page fails with error: 
``
delete from "pages" where "id" = $1 - update or delete on table "pages" violates foreign key constraint "pagetree_pageid_foreign" on table "pageTree"
``

**To Reproduce**
1. Create a new page
2. Go to /a/pages/[pageID]
3. Try to delete the page

**Expected behavior**
Page should be deleted without error.

**Screenshots**
<img width="919" alt="Bildschirmfoto 2019-10-21 um 14 41 03" src="https://user-images.githubusercontent.com/3525191/67206933-de704880-f412-11e9-9274-9c0fd66bf8f2.png">

**Host Info (please complete the following information):**
 - OS: Docker Container
 - Wiki.js version: 2.0.0-rc.1
 - Database engine: PostgreSQL 11.4

**Comment by winkelement** [comment]
From the postgres log:
`DETAIL:  Key (id)=(4) is still referenced from table "pageTree".`

**Comment by aiveras** [comment]
I have the same issue. 
![Screenshot from 2019-10-22 13-00-10](https://user-images.githubusercontent.com/48723960/67279785-01aafe80-f4cc-11e9-9be7-1d7f6bfedac2.png)

**Comment by swesandbox** [comment]
Hi,

I have the same problem. Running on Windows Server 2019 with postgres db and version 2.0.0-rc.1.

**Comment by ade21** [comment]
Hi, same here with Ubuntu 18.04 and MariaDB 10.3.

**Comment by NGPixel** [comment]
Fixed by ab8391c085773f99ca1f5fd3fe267527e8b40757

**Comment by ade21** [comment]
Hi, the fixed does not seem to work. This is what I get starting wiki:

`2019-10-23T07:03:28.096Z [MASTER] info: =======================================
2019-10-23T07:03:28.099Z [MASTER] info: = Wiki.js 2.0.0-beta ==================
2019-10-23T07:03:28.099Z [MASTER] info: =======================================
2019-10-23T07:03:28.099Z [MASTER] info: Initializing...
2019-10-23T07:03:28.640Z [MASTER] info: Connecting to database...
2019-10-23T07:03:28.700Z [MASTER] info: Database Connection Successful [ OK ]
migration file "2.0.0-rc.2.js" failed
migration failed with error: alter table `pageTree` drop `parent` - Cannot drop index 'pagetree_parent_foreign': needed in a foreign key constraint
2019-10-23T07:03:28.801Z [MASTER] error: Database Initialization Error: alter table `pageTree` drop `parent` - Cannot drop index 'pagetree_parent_foreign': needed in a foreign key constraint`

I cannot start the wiki anymore. :-(

Node v12.11.1
MariaDB v10.3.18
Ubuntu 18.04 LTS
