### ISSUE TITLE
Folder view

### ISSUE THREAD

**Issue by thonythony** [Requarks/wiki#1121]
**Question**
I created a new page located in folder. Example : `myfolder/mypage`.
When I navigate to `myfolder`, wikijs tell me that no page exists here. It's normal because `myfolder` is supposed to be a folder and not a page. Is wikijs handle folder view for listing all pages that belongs to it ?

**Host Info (please complete the following information):**
OS: Ubuntu 18.04, Docker
Wiki.js version: 2.0.0-rc.1
Database engine: postgres 9

**Comment by NGPixel** [comment]
There's no concept of folders in Wiki.js.

(This feature is coming soon:) You'll need to create a new page at path `myfolder` and select the "Tree View" view. This will list all pages under the current path.

This feature is high priority in the list so it should be available in the next weeks.

**Comment by thonythony** [comment]
Thanks for your reply. 
Currently we use Wikijs v1 as internal wiki at work. Our collaborators and CI jobs push markdown files in git repository (markdown may be written by hand, or may be generated by tools like typedoc). Wikijs synchronize it and display them. By default the tree view is on the left panel. It's not perfect (by example the navigation is not persisted when we reload browser) but it exists automatically. In brief, we don't use Wikijs editor for write or organize our wiki, this job is done automatically by git repository structure.
In Wikijs v2, if I understand well I have to create manually a special kind of page aka tree view page (I see the disabled button on UI) for each folder created by a git synchronization. Do you think it is possible to configure globally Wikijs behavior to display a tree view automatically for each folder (tree that represents all files under the folder, of course) created when a synchronizing a source (git, or other) ?

**Comment by NGPixel** [comment]
You'll still have a site map view ( also coming soon ), similar to what you have in v1.

**Comment by TheVidAllMayThe** [comment]
@NGPixel  Any progress on this? I was in the process of migrating my companies wiki from v1 to v2 and the "site map" would be very important.

**Comment by NGPixel** [comment]
@TheVidAllMayThe it's coming in 2.1 as detailed in the docs: https://docs.requarks.io/releases

**Comment by anton-yurchenko** [comment]
@NGPixel, is the previously upcoming "Tree View" view has been canceled lately? (it is not listed as an option anymore)
The navigation tree view is awesome, but the previously planned tree view page type is an amazing addition to those who are using custom/static navigation.

**Comment by NGPixel** [comment]
It's still coming. You'll be able to include it as a "block" in any page, instead of having a dedicated full page type.

**Comment by anton-yurchenko** [comment]
Oh, amazing! I was unable to find it on the roadmap, at what version do you expect it to be released? (so we will be able to "subscribe" 😄)
