### ISSUE TITLE
Markdown table: code block on indented row entry

### ISSUE THREAD

**Issue by pagdot** [Requarks/wiki#1122]
**Describe the bug**

When creating a table in Markdown mode and indenting the first element in row with at least 4 spaces the row gets rendered as code block. I would prefer it to get rendered as table

Example Code:

```
Column 1 | Column 2
-------: | :-------
    1000 | Some Text
```
How it gets rendered (github does the same thing ☹️)

Column 1 | Column 2
-------: | :-------
    1000 | Some Text

How it should be rendered:

Column 1 | Column 2
-------: | :-------
1000 | Some Text

**To Reproduce**
1. Create/Edit a page
2. Create a table like described in the bug report

**Expected behavior**

See *How it should be rendered:*

**Host Info (please complete the following information):**
 - Docker
 - Wiki.js version: 2.0.0 RC1
 - Database engine: postgres 9

**Comment by NGPixel** [comment]
Your table syntax is incorrect. See https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#tables
