### ISSUE TITLE
Further docker ARM images of v2?

### ISSUE THREAD

**Issue by akramer-zibra** [Requarks/wiki#1123]
I love your wiki! I am using it on my RaspberryPi 3 Model B+ as a docker container.  
  
**Question**
Is it possible, that you provide us any further docker ARM images of wikijs? ...your latest available ARM build is 2.0.0-beta.303  
  
**Host Info:**
OS: Raspbian, Docker, ARM
Wiki.js version: [e.g. 2.0.0-beta.115]
Database engine: prostgres 9

Thankst in advance!

**Comment by NGPixel** [comment]
The ARM images are now live.

**Comment by akramer-zibra** [comment]
Awesome! Thank you very much @NGPixel
