### ISSUE TITLE
2.0.0-rc.1 with mssql backend fails on first startup

### ISSUE THREAD

**Issue by AchimHentschel** [Requarks/wiki#1125]
**Describe the bug**
Today I tried to upgrade from version Wiki.js 2.0.0-beta.275 docker (migration version 2.0.0-beta.242.js) to the latest beta release 2.0.0-rc.1. I skipped the last version due to the upgrade issues with mssql. Now I am experiencing a bug in the rebuild-tree.js job during startup of wiki.js. An error is throws where SQL Server complains about modification of the identity column id for which wiki.js tries to insert an explicit value (which is not possible unless set identity insert has been enabled for this table).

The log of the container contains the following error:

orpheus_wiki-test | 2019-10-22T08:01:15.001Z [JOB] info: Rebuilding page tree...
...
orpheus_wiki-test | 2019-10-22T08:01:16.506Z [JOB] error: Rebuilding page tree: [ FAILED ]
orpheus_wiki-test | 2019-10-22T08:01:16.507Z [JOB] error: insert into [pageTree] ([depth], [id], [isFolder], [isPrivate], [localeCode], [pageId], [parent],
[path], [privateNS], [title]) values (@p0, @p1, @p2, @p3, @p4, @p5, @p6, @p7, @p8, @p9), (@p10, @p11, @p12, @p13, @p14, @p15, @p16, @p17, @p18, @p19), (@p20
, @p21, @p22, @p23, @p24, @p25, @p26, @p27, @p28, @p29), ..., (@p1120, @p1121, @p1122, @p1123, @p1124, @p1125, @p1126, @p1127, @p1128, @p1129) - Cannot insert explicit value for identity column in table 'pageTree' when IDENTITY_INSERT is set to OFF.

**To Reproduce**
1. Install wiki.js version 2.0.0-beta.275 with mysql backend (as docker container)
2. Startup the container with the upgraded image.
3. Check log for identity insertion issue

**Expected behavior**
I expected the latest version of wiki.js to start up without an issue.

**Host Info (please complete the following information):**
 - OS: Debian Version 9.9, docker-ce 19.03.2
 - Wiki.js version: Wiki.js 2.0.0-beta.275
 - Database engine: mssql

**Comment by AchimHentschel** [comment]
# Quick fix
Here a quick fix for this issue, though I end up getting an error when opening the wiki:
Oops, something went wrong...
Expected unsigned integer at id, got 3,3

## How to apply
Exec into the docker container (or simply edit server/jobs/rebuild-tree.js)
```shell
docker exec -it &lt;wiki-js container name&gt; bash
```
In the container
```shell
cd /server/jobs
vi rebuild-tree.js
# scroll down to await WIKI.models.knex.table('pageTree').insert(tree) and replace the 4 rows (truncate, if, insert with the code below
```

## rebuild-tree.js
```JavaScript
...
    await WIKI.models.knex.table('pageTree').truncate()
    if (tree.length > 0) {
      const { bindings, sql } = WIKI.models.knex.table('pageTree').insert(tree).toSQL();
      if (WIKI.config.db.type === 'mssql') {
        await WIKI.models.knex.raw(sql, bindings).wrap(
          'SET IDENTITY_INSERT pageTree ON;',
          'SET IDENTITY_INSERT pageTree OFF;',
        )
      } else {
        await WIKI.models.knex.raw(sql, bindings)
      }
    }
...
```

I will try to have this change as a pull request later the day.

**Comment by AchimHentschel** [comment]
Well, I just did the RTFM and here ist the PR: https://github.com/Requarks/wiki/pull/1130

**Comment by NGPixel** [comment]
Fixed by 44a1c8699f4521d1bdeecca26c24af7cde8da3fc, 820cc77a83f1f69011fb10a1ff4538f7bad907f5

**Comment by AchimHentschel** [comment]
@NGPixel: Hi, has there been a regression when you merged https://github.com/Requarks/wiki/commit/820cc77a83f1f69011fb10a1ff4538f7bad907f5? It seems that my code changes were removed by merging this commit.

**Comment by NGPixel** [comment]
The pageTree schema was altered to remove the autoincrement, which was not used. As such, the workaround for MSSQL was no longer needed.

**Comment by AchimHentschel** [comment]
Hi @NGPixel, I had a second look at the code changes and must confess, that I overlooked the new migration script - much better solution than mine, but I did not have any contact with knex so far. Thanks for the really good maintenance of the wiki.js project!
