### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by brihanrohan** [Requarks/wiki#1133]
Wikijs v2.0.0 RC1
Docker: postgres: 9-alpine, requarks/wiki:beta

Is the idea in wiki v2 that we manually make links for each page that exists in the navigation bar? 
If so, there are a number of usability concerns i heave:

1. How are we to deal with locales? Currently i have to add the locale prefix into the link for a navigation entry for the link to work.

2. In wikijs v1 you could click on folders to see the list of child page in the sidebar. Is there a plan to be able to folders to the navigation bar?

3. Could we possibly have a new navigation item that is a search/ query of all pages that exist under a specified url?
Eg, I have a page structure like:
-Sport
--Team1
--Team2
--Team3
And then in my navigation bar i add a query item that will return a list of all pages that exist under the Sport url.

**Comment by NGPixel** [comment]
The sidebar navigation is meant to be a list of important global links. You're supposed to put links to other pages inside your content.

See how the [docs](https://docs.requarks.io/) site has links on the homepage to all major sections (some of which are duplicated in the sidebar navigation). Then click on [Installation Guide](https://docs.requarks.io/en/install) to get another list of links to various pages (none of which are in the sidebar).

1. The main site locale is used by default if no locale code is specified in the URL. At the moment, the sidebar is global across all locales. This will be improved to support different navigations for different locales.

2. This is coming in a future update.

3. Also coming in a future update.

**Comment by MichaelPaulukonis** [comment]
> You're supposed to put links to other pages inside your content.

Not everybody has that as a use-case.

The ability to dynamically create a list of pages by different criteria is quite useful:
- alphabetic list of pages
- reverse alphabetic
- list of pages by last modified date
- list of pages by last-viewed date
- list of pages by most/least number of views
- list of pages that contain a specific word or phrase
- random selection of pages from criteria
- non-documentary pages that don't link to anything, and have nothing linking to them


The page-list features in pmwiki are what have spoiled me. But I am well and tired of dealing with php and the pmwiki-project's weird DSL that has evolved.
