### ISSUE TITLE
As it is git backed; why is an SQL DB required?

### ISSUE THREAD

**Issue by hoijui** [Requarks/wiki#1135]
Hello! :-)
I am currently investigating git backed wikis, and am surprised to read that Wiki.js uses/requires an SQL-DB:

> Works on virtually any platform and is compatible with either PostgreSQL, MySQL, MariaDB, MS SQL Server or SQLite! you need guidance.

Can you explain why?
I could not find anything on the website directly or in the README.

**Comment by jimmybrancaccio** [comment]
I was wondering the same thing yesterday. I figured they ditched the Git backend though for v2, but I could definitely be wrong there...

**Comment by NGPixel** [comment]
We didn't ditch the Git backend. While it was highly recommended for v1, it was always optional. Some users don't want to rely on git and just want a simple wiki. So in v2, we made Git a storage module that you can choose to enable or not.

The database is required to store users, settings, folder structure, locales, tags, etc.

**Comment by mrquincle** [comment]
It is possible to use git as a backend to store users, settings, folder structure, locales, etc. This was also a surprise to me.
