### ISSUE TITLE
Unable to delete pages for foreign key reference

### ISSUE THREAD

**Issue by scargr** [Requarks/wiki#1136]
**Describe the bug**
Deleting a page generates an error message:
"_delete from `pages` where `id` = 36 - Cannot delete or update a parent row: a foreign key constraint fails (`wikijs`.`pageTree`, CONSTRAINT `pagetree_pageid_foreign` FOREIGN KEY (`pageId`) REFERENCES `pages` (`id`))_"

**To Reproduce**
1. Create a new page clicking on + (new page), save it.
2. Try to delete it from admin->pages->select page-> trash bin icon

**Expected behavior**
Pages should be deleted...

**Host Info (please complete the following information):**
 - OS: Ubuntu 16.04
 - Wiki.js version: 2.0.0 rc1
 - Database engine: mariadb 10.4.8

**Additional context**
The 36 in the bug description is just the 36th test: even dropping all the pages and beginning from a fresh install, the behaviour is the same.
Tried to set SET FOREIGN_KEY_CHECKS=0; and reproduce the deletion querying directly mariadb, and it worked well.
Even with foreign keys check disabled, deleting from admin pages gives the same message.
Seems something related to the folder tree. We also found some problems importing nested .md from 1.0 repos, but no problems if .md are on the same directory.

**Comment by NGPixel** [comment]
Fixed by ab8391c085773f99ca1f5fd3fe267527e8b40757
