### ISSUE TITLE
Localization files are not included and does not work

### ISSUE THREAD

**Issue by ankyfive** [Requarks/wiki#1137]
Hello,

I tried the v2.0.0.tc1 and language file were not installed !!
The machine which hosts the wiki is not connected to the internet
So I tried to download and copy it manually.
But it does not work the wiki is nice but unusable without language files

**Comment by NGPixel** [comment]
Have you read the [docs](https://docs.requarks.io/en/install/sideload)?

**Comment by ankyfive** [comment]
Thanks for the link I did not see it before.
Now it works thanks

**Comment by ankyfive** [comment]
Thanks for the link I did not see it before.
I tried to make it works one time.
So i decided to start fresh install, and it does not detect the files in data/sideload
