### ISSUE TITLE
Can't assign new user to group 

### ISSUE THREAD

**Issue by ankyfive** [Requarks/wiki#1138]
Hello,
I can't assign new users to group. The admin and guest groups are in grey in the user create/mod form
So the users can't connect.

**Comment by NGPixel** [comment]
This is by design. You need to go into the admin group, click Users and add the user from there.

As for the guests group, it makes no sense to assign a user to this group as this is the same as not being logged in.

**Comment by ankyfive** [comment]
Ok thanks i created new groups. But the user can't connect with full rights
