### ISSUE TITLE
Can't delete created users

### ISSUE THREAD

**Issue by souloftheslayer** [Requarks/wiki#1140]
HI! I can't delete any user and can't attach them to any group.

![image](https://user-images.githubusercontent.com/42668237/67492904-c9e4b800-f67f-11e9-8acb-725252ce3ec7.png)

![image](https://user-images.githubusercontent.com/42668237/67492854-bafe0580-f67f-11e9-9967-17c9d60b56fc.png)

   Host Info:
 - OS: Debian 10.1
 - Wiki.js version: 2.0.0-rc.1
 - Database engine: postgresql 11.5
 - Node.js: 12.13

**Comment by NGPixel** [comment]
User delete is coming in a future release.

As for the groups, see my response in https://github.com/Requarks/wiki/issues/1138

**Comment by neherh** [comment]
Any projections as to when that feature will be implemented? Also, is there a more manual way of deleting instead of the GUI? This is for 2.0. Also, a great job. Love the wiki.
