### ISSUE TITLE
Win10+MSSQL cannot insert explicit value for identity column

### ISSUE THREAD

**Issue by jaypoc** [Requarks/wiki#1141]
**Describe the bug**
Installation fails on MSSQL Server. UI provides the following error:

> insert into [groups] ([createdAt], [id], [isSystem], [name], [pageRules], [permissions], [updatedAt]) output inserted.[id] values (@p0, @p1, @p2, @p3, @p4, @p5, @p6) - Cannot insert explicit value for identity column in table 'groups' when IDENTITY_INSERT is set to OFF.

**To Reproduce**
1. Follow installation steps 1-5 at: https://docs.requarks.io/en/install/windows
2. Edit "db" section of config.yml

      host: "127.0.0.1"
      port: 1433
      user: username
      pass: password
      db: wiki
      ssl: false

3. Run **node server**
4. Enter Administrator Email, Password, Confirm Password and Site URL. Disable Telemetry, Click Install

**Expected behavior**
Installation should succeed.

**Screenshots**

![image](https://user-images.githubusercontent.com/579644/67509418-95113a80-f658-11e9-93e4-5f9635b1bc7b.png)

![image](https://user-images.githubusercontent.com/579644/67510237-292fd180-f65a-11e9-96be-849e403c9431.png)

**Host Info (please complete the following information):**
 - OS: Windows 10 (Version 10.0.18362.418)
 - Wiki.js version: Wiki.js 2.0.0-rc.1
 - Database engine Microsoft SQL Server (Tried two servers)

1. Microsoft SQL Server 2016 Enterprise Edition (64-bit)
2. Microsoft SQL Server 2017 (RTM) - 14.0.1000.169 (X64)   Aug 22 2017 17:04:49   Copyright (C) 

**Additional context**
I first attempted the installation on a Hosted SQL Server available to me. Although the issue appeared to be DB related, I suspected it could be due to limited permissions, so I installed SQL Server Express locally as well.

**Comment by NGPixel** [comment]
Fixed by 820cc77a83f1f69011fb10a1ff4538f7bad907f5
