### ISSUE TITLE
Language selector doesn't show all languages on mobile (missing scrollbar)

### ISSUE THREAD

**Issue by UnlimitedCookies** [Requarks/wiki#1143]
### Actual behavior
The language selector is cut off on the bottom of the screen due to not available space on mobile devices. Therefor some languages are not accessible on mobile devices.
### Expected behavior
All languages being selectable.
I suggest adding a scrollbar similar to the one used on the navbar.
For very large language selections, a pop up showing just the country codes side by side may be an option - Perhaps adding a search bar.
### Steps to reproduce the behavior
1. Go to a v2 wiki with lots of languages available (12+).
I used https://discordia.me/en/home for my testing.
2. Go to the responsive testing tab within the developer tools and select any mobile device size for testing. 
3. Try to select the 13th or so language. It's not possible. :open_mouth:

P.S.: It would be cool to have the option to use country flag symbols instead of the two-letter code.

Thanks for your contribution!

**Comment by Timeraa** [comment]
Same with desktop.

**Comment by Fruxh** [comment]
Can confirm.
![image](https://user-images.githubusercontent.com/37774297/74074062-e0cfd000-4a0c-11ea-94b3-f23743c59416.png)

**Comment by eggsywashere** [comment]
Same for almost _every_ existing laptops out there...

![image](https://user-images.githubusercontent.com/13917975/74074084-b89c9d00-4a1d-11ea-9211-9d3b333cc1d6.png)

**Comment by Fruxh** [comment]
Also thanks for fixing the remote repository import bug (v2.1.103)

**Comment by frozaum** [comment]
Can confirm³
![image](https://user-images.githubusercontent.com/34042085/74074381-90e11100-49ec-11ea-8d43-3160c5df981f.png)

**Comment by eggsywashere** [comment]
So adding just `height: 100%` to the `v-menu__content` fixes it all if anyone's interested.

![image](https://user-images.githubusercontent.com/13917975/74074400-eb936080-4a1e-11ea-9b1a-9e49081b2bd3.png)

**Comment by Fruxh** [comment]
> So adding just `height: 100%` to the `v-menu__content` class fixes it all if anyone's interested.
> 
> ![image](https://user-images.githubusercontent.com/13917975/74074400-eb936080-4a1e-11ea-9b1a-9e49081b2bd3.png)

use `max-hight: 100%;`

**Comment by eggsywashere** [comment]
damn you're smart @Fruxh 

![image](https://user-images.githubusercontent.com/13917975/74074839-04047a80-4a21-11ea-85ee-686b31e83307.png)

**Comment by NGPixel** [comment]
Fixed by 48ea692afe53164f33cab572b89bdbc196b843fb
