### ISSUE TITLE
Do Modules Require AGPL Licensing?

### ISSUE THREAD

**Issue by lorenwest** [Requarks/wiki#1145]
**Question**
Hello, I am considering writing a module using the module extension mechanism, and am wondering if the authors consider that module a modification to this source, or an "aggregate" as defined in the AGPL license?

In other words, am I required to license my module (theme/editor/renderer/etc) as AGPL also?

**Comment by NGPixel** [comment]
Modules that are bundled with Wiki.js must stay AGPL (obviously). However, any new module you write can use any license of your choice or stay private.

The intent of using the AGPL license was solely to prevent someone from taking the software, making improvements to it and sell it as a service. So if for example you need to write a module with proprietary code to integrate with other systems in your company, that's completely fine.

**Comment by lorenwest** [comment]
To be clear, if my intent was to take the software, make improvements to it, and sell it as a service that would be OK as long as those improvements were also AGPL and I made the source available as a download to everyone using the service.

Is that correct?

**Comment by NGPixel** [comment]
> To be clear, if my intent was to take the software, make improvements to it, and sell it as a service that would be OK as long as those improvements were also AGPL and I made the source available as a download to everyone using the service.
> 
> Is that correct? That's how I understand the AGPL license.

Correct.

> The finer point I was trying to see was if the improvements weren't to the software itself, but additional modules, would I also be required to license those modules as AGPL?

Additional modules (auth, search, renderer or storage) are not required to be licensed as AGPL.
