### ISSUE TITLE
Official documentation crashes on firefox

### ISSUE THREAD

**Issue by AuspeXeu** [Requarks/wiki#1147]
**Describe the bug**
Using the latest firefox, navigating the official documentation website (running wikijs) leads to a crashed tab.

**To Reproduce**
Navigate through the documentation using the latest firefox

**Expected behavior**
Don't crash.

**Screenshots**
![image](https://user-images.githubusercontent.com/2115696/67597976-69668100-f73a-11e9-885e-3b5d9a50c042.png)

**Host Info (please complete the following information):**
 - OS: Win10
- Firefox: 70.0

**Comment by NGPixel** [comment]
I was able to load the exact same URL in Firefox 70.0 on Windows 10 without any issue.

Try disabling any plugin you might have installed.

**Comment by AuspeXeu** [comment]
Will do this and report back :)

**Comment by AuspeXeu** [comment]
Tried this again with all plugins disabled. Still occurs. Maybe it's some of the any tracking features?!

**Comment by NGPixel** [comment]
There's no tracking in Wiki.js unless you specifically enable one.

The wiki.js docs website only has Google Analytics enabled.

**Comment by AuspeXeu** [comment]
Yeah, the other computer is just fine. Really no difference though between them, from what I can tell. Removed all extensions from the crashing machine as well.

**Comment by lpar** [comment]
I have the crashing problem on my Linux machine (Fedora), but not on a Mac.

**Comment by Grawl** [comment]
The same problem. It's not a stable bug.

- Firefix 70.0.1 (64-bit)
- macOS Catalina 10.15.1 (19B88)

Video proof: https://vimeo.com/grawl/review/378947813/6f3902efb3

**Comment by AuspeXeu** [comment]
@Grawl video link is dead

**Comment by Grawl** [comment]
Oh sorry I forgot to check it. I uploaded it to Imgur now
