### ISSUE TITLE
Tags not saved in markdown on git storage

### ISSUE THREAD

**Issue by davidpoza** [Requarks/wiki#1149]
**Tags are not saved in markdown files when using git storage**
Tags asigned to an entry aren't been saved in the markdown format file. **They are saved in pageTags table on database**, but no are included in markdown header comments, since the field "tags" is empty. 

Example of markdown header which should contain tags:
```
---
title: postgresql
description: 
published: true
date: 2019-10-26T08:02:52.120Z
tags: 
---
```

**To Reproduce**
1. Create a new page
2. Assign a tag to it and save it
3. Force Sync with git (or wait scheduler)
4. Pull branch from remote repository and check out markdown content of the previously created entry.

**Expected behavior**
Is expected the markdown contains a list of tags assigned to entry, separated by commas for example.

**Host Info (please complete the following information):**
 - OS: [e.g. Ubuntu 16.04, Docker]
 - Wiki.js version: [e.g. 2.0.0-rc.1]
 - Database engine: [e.g. postgres]

**Comment by NGPixel** [comment]
Fixed by 28fdf1400280bd666ad94cacb4688690a63bd6ae
