### ISSUE TITLE
Verification email generates invalid link with double-slash

### ISSUE THREAD

**Issue by weswpg** [Requarks/wiki#1151]
**Describe the bug**

The verification email sent upon self registration of new user provides a link which does not work because it begins with a double slash before the word 'verify'. The link works as soon as a slash is removed.

**To Reproduce**
1. Register a new account
2. Check the verification email sent to the new user's email
3. Click the provided link

Faulty URL: www.example.com//verify/oGmTck5vEAxTDRHC49d_P

**Expected behavior**
Proper URL: www.example.com/verify/oGmTck5vEAxTDRHC49d_P

**Screenshots**
![Capture](https://user-images.githubusercontent.com/29640351/67626347-b7998400-f80f-11e9-8e41-e2db4f966f22.PNG)

**Host Info:**
 - OS: Ubuntu Linux (bionic) 18.04 x64
 - Wiki.js version: 2.0.0-beta.241
 - Database engine: postgres 10.10

**Comment by NGPixel** [comment]
![image](https://user-images.githubusercontent.com/15522395/67627571-9d21d380-f82c-11e9-9018-3510e08bb07b.png)
