### ISSUE TITLE
New Group Bug

### ISSUE THREAD

**Issue by sbonaime** [Requarks/wiki#1153]
When I want to create a new group I have the following error
![Capture d’écran 2019-10-29 à 29-10-19 10 30 40](https://user-images.githubusercontent.com/750709/67754931-931ff080-fa37-11e9-8340-f5946229dd9b.png)

**Host Info (please complete the following information):**
Debian 4.9.189-3+deb9u1 (2019-09-20) x86_64 GNU/Linux
- 2.0.0-rc.17
 - postgres 9.6.15
- node.js 12.13.0

I install a fresh version of 2.0.0-rc.17 then I import my wikijs V1 data from a git repo WITHOUT importing users.

**Comment by sbonaime** [comment]
I remove the data/repo directory and import a second time my data. Then I was able to create a new group.

**Comment by y1zhou** [comment]
Had the same issue and solved by changing the search engine to `Database - basic` from `Database - PostgreSQL`.

**Comment by NGPixel** [comment]
@y1zhou The search engine selection is unrelated to this issue.

**Comment by jschirrmacher** [comment]
I can confirm that problem. I use docker, 2.0.0-rc.17, postgres 9.6.15 and node v10.16.3.
I get a similar message when adding a user too.

**Comment by NGPixel** [comment]
Fixed by b4cb8249f52e7d4fd2a494cd7d455ed4b18834d3

**Comment by HedgeShot** [comment]
Hi,

Thanks for this @NGPixel . Docker image doesn't seem to have this fix (beta tag), however. I still ran into this issue on a fresh new install today.

**Comment by NGPixel** [comment]
@HedgeShot Fixed simply means that it was fixed in the code, not that it was released. It will be available in the next release.

**Comment by username1222** [comment]
Thanks for fixing this issue, sweet.

@NGPixel is there an ETA for the next release?
