### ISSUE TITLE
How to add attachments to pages (Can't find it in the documentation) 

### ISSUE THREAD

**Issue by dejanmarkovic** [Requarks/wiki#1154]
**Question**
Hi friends, I love the wiki.js.
I can't find it anywhere how to add attachments to pages? 

Host Info (please complete the following information):**
Heroku image.

**Comment by NGPixel** [comment]
Which version and which editor?

**Comment by dejanmarkovic** [comment]
Hi, thank you for following up with me!
 
//Which version 
 Version: 2.0.0-beta.303

//which editor
Visual editor

Thanks

**Comment by NGPixel** [comment]
Use the Insert Image button. You can upload any type of file, not just images.

It will be made more intuitive in future releases.
