### ISSUE TITLE
New Users cant change password on login

### ISSUE THREAD

**Issue by PujagicNair** [Requarks/wiki#1156]
I set up a new Wikijs intance on Heroku and added some users whit randomly generated passwords and having them change them on the first login. 
I created a Role for those users with all content edit permissions and manage navigation and added the users to the role.
the users can log in but when the get to the change password dialog they can't change the passwords the only get this error 
![image](https://user-images.githubusercontent.com/45203762/67775994-fa519b00-fa5f-11e9-9f50-cb90de64f1a9.png)

**Host Info (please complete the following information):**
 - OS: Heroku
 - Wiki.js version: 2.0.0-rc. 17
 - Database engine: postgres

**Comment by NGPixel** [comment]
I'm unable to replicate your issue but this looks like a network issue on your side. Are you able to replicate the issue on a different computer? On a different network?

**Comment by Nairmiod** [comment]
We later found out it works on other PCs on the same network with the same accounts. 
The issue was present on 2 PCs on all browsers.
Honestly i had no idea what happened and was just posting in case it was a bug so you would know. 
Thanks for looking into it.
