### ISSUE TITLE
Can't move pages

### ISSUE THREAD

**Issue by BrandonLegault** [Requarks/wiki#116]
### Actual behavior

Moving generates this error 

> Something went wrong
> `git --git-dir=repo/.git --work-tree=repo mv home/page.md home/sub/page.md` failed with code 128

### Expected behavior

The page should move with no error

### Steps to reproduce the behavior

Create the page /home/page, now try to move that page to /home/sub/page

### Other info

I just updated to Beta 11 today. I really just want to be able to delete a page.

**Comment by bitworm** [comment]
Although not an ideal solution, you can manually delete a page by navigating via terminal and deleting file:
/wiki_folder/repo/page_to_be_deleted.md
as well as /wiki_folder/data/cache/*.json

**Comment by NGPixel** [comment]
Indeed, I can reproduce this issue when moving a page to a non-existant sub-directory.

**Comment by NGPixel** [comment]
Fixed for Beta 12 (36a6bc0827246dcbac5861f61630ea51573e1d05)
