### ISSUE TITLE
Search doesn't count newlines as word boundaries

### ISSUE THREAD

**Issue by rhettlunn** [Requarks/wiki#1160]
**Describe the bug**

**To Reproduce**
1. Create a new page - Visual Editor
2. Enter:
```
Somerandommadeupword
anotherrandommadeupword
```
3. Save the page
4. Search for `Somerandommadeupword`
5. No results!
6. (bonus round) Search for `Somerandommadeupwordanotherrandommadeupword`
7. It's found!

**Expected behavior**
Newlines should count as word-boundaries when the post is indexed into the search engine.

**Host Info (please complete the following information):**
 - OS: Ubuntu 18.04, Docker
 - Wiki.js version: 2.0.0-rc.1
 - Database engine: PostgreSQL 9.6.15
 - Search Engine: Elasticsearch 7.x

**Additional context**
As expected, viewing the data in elastic it shows as "Somerandommadeupwordanotherrandommadeupword", no space.
The same issue occurs with bullet point lists (newline + bullet point)
Adding a period just before the newline does _not_ get it to see them as separate words:
```
Somerandommadeupword.
anotherrandommadeupword
```
gets indexed as `Somerandommadeupword.anotherrandommadeupword`

**Comment by NGPixel** [comment]
Fixed by 4f8de0d50d00e76e90d6ea6c29b6148ca2bdb710
