### ISSUE TITLE
Can't select version strings on Admin - System Info page

### ISSUE THREAD

**Issue by rhettlunn** [Requarks/wiki#1161]
**Describe the bug**
On the System Info page, CSS stops the user from selecting the current version number, the database version number, and a few other things on the page.

**To Reproduce**
1. Go to /a/system (System Info page in the Admin interface)
2. Try to select `2.0.0-rc.1`
3. It doesn't select!

**Expected behavior**
It should be possible to select the version number, for ease of copying into bug reports, etc.

**Host Info (please complete the following information):**
 - OS: Docker Container (Linux, Ubuntu 18)
 - Wiki.js version: 2.0.0-rc.1
 - Database engine: PostgreSQL 9.6.15

**Comment by NGPixel** [comment]
Fixed by 3d5e4abca14c5a02dbc3d9ef658b0b8dd23a9b89

**Comment by sbonaime** [comment]
Node.js and PostgreSQL (or I imagine DB engine) versions are not selectable with 2.0.1
