### ISSUE TITLE
Markdown Formatting Help

### ISSUE THREAD

**Issue by aalmir** [Requarks/wiki#1164]
**Describe the bug**
The Help is not displayed correctly.

**To Reproduce**
1. Go to 'Markdown Editor'
2. Click on 'Question Mark'
3. Scroll down to 'see the Help'

**Expected behavior**
The Help should be in the Front of the Editor, not underneath.

**Screenshots**
-

**Host Info (please complete the following information):**
 - OS: [Windows Server/10]
 - Wiki.js version: [e.g. 2.0.0-rc17]
 - Database engine: [sqlite]

**Additional context**
-

**Comment by NGPixel** [comment]
Fixed by e764e74a73823f7c2d1aaa2f652e9f5fff8212ee
