### ISSUE TITLE
The locale is added to the /t link and breaks it

### ISSUE THREAD

**Issue by depict1** [Requarks/wiki#1165]
**Describe the bug**
When creating a hyperlink to the /t page, it automatically puts /en/ before the /t, causing it to break.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Host Info (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04, Docker]
 - Wiki.js version: [e.g. 2.0.0-beta.115]
 - Database engine: [e.g. postgres 9.7, mysql 5.7]

**Additional context**

**Comment by NGPixel** [comment]
Fixed by d78127dc2973d8e773c6ad88e44c253c7fbda1a1
