### ISSUE TITLE
Turning off locale doesn't work and still adds /en/ to my pages

### ISSUE THREAD

**Issue by depict1** [Requarks/wiki#1166]
**Describe the bug**
My wiki will be 1 language. I do not want my links to have /en/ added to them, but they do, even if I have the namespaces off.

**To Reproduce**

**Expected behavior**

**Screenshots**
https://files.slack.com/files-pri/T49HD9PCG-FPLRV3TL3/image.png
**Host Info (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04, Docker]
 - Wiki.js version: [e.g. 2.0.0-beta.115]
 - Database engine: [e.g. postgres 9.7, mysql 5.7]

**Additional context**

**Comment by NGPixel** [comment]
Fixed by d78127dc2973d8e773c6ad88e44c253c7fbda1a1
