### ISSUE TITLE
Blockquotes on small screens don't have enough padding

### ISSUE THREAD

**Issue by depict1** [Requarks/wiki#1168]
**Describe the bug**
On small screens, blockquotes look less than ideal because it clips. See image.

**Screenshots**
![image](https://user-images.githubusercontent.com/57202889/67919060-d760dd00-fb6c-11e9-8327-dbb93027e0ca.png)

**Host Info (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04, Docker]
 - Wiki.js version: [e.g. 2.0.0-beta.115]
 - Database engine: [e.g. postgres 9.7, mysql 5.7]

**Additional context**

**Comment by NGPixel** [comment]
Fixed by 57f79c19b2aa940316addeb6fa2d1fc9b9956f06
