### ISSUE TITLE
Guests cannot edit/create pages

### ISSUE THREAD

**Issue by nategasm** [Requarks/wiki#1170]
**Question**
Hi, I have just set up a new wiki but I can't seem to setup so that guests are able to edit or create pages without an account (works fine with an account). Guests can read fine.

I have already updated both the Permissions and Page Rules tabs for the "Guests" group to have write permissions. But they still never see the edit/create links.

Am I doing something wrong or is this a bug?

**Host Info (please complete the following information):**
OS: Windows
Wiki.js version: Latest 2.0.0-rc.17
Database engine: MariaDB 10.4.8

**Comment by NGPixel** [comment]
This is as designed. Guests cannot perform editing actions on the wiki. Users must register to create and edit pages.

**Comment by liudvikasakelis** [comment]
Would you consider reconsidering your design then? This seems nothing more than a moral stance (can't see how it's more difficult to implement). Could you give us an option to enable it, with a big danger sign next to it?

**Comment by NGPixel** [comment]
Create a feature request on https://wiki.js.org/feedback

**Comment by liudvikasakelis** [comment]
Thanks for a quick reply, will do!

**Comment by pho** [comment]
Hi, having the right permissions and navigating to the edit link (adding an /e/ before any page) works perfectly fine for the guests. The missing edit button is the only thing preventing them from doing it easily

Has this been reconsidered or is it a bug? Should I submit a feature request?
