### ISSUE TITLE
Status of project? When is 2.0 production ready?

### ISSUE THREAD

**Issue by einarpersson** [Requarks/wiki#1171]
I just tried 2.0 and I'm evaluating for a high school. I notice that there are many features that are marked as "Coming soon" and the last post about version 2.0 on the [blog](https://blog.requarks.io/) was over a year ago which makes me a bit concerned.

What is the status of this project? When will 2.0 be production ready? I understand that it is an impossible question but I would appreciate some thoughts so I know whether I should give Wikijs 2.0 RC a chance or if I should go down another path

**Comment by NGPixel** [comment]
Final release in the coming days.

Follow our [Twitter account](https://twitter.com/requarks) instead. The blog is barely used for news.
