### ISSUE TITLE
Source Code Formatting (XML)

### ISSUE THREAD

**Issue by MurashovAlexander** [Requarks/wiki#1172]
**Describe the bug**
Unable to quote xml code using
```
```xml
<test>test</test>
\```
```
(without '\\')

**To Reproduce**
1. Go to create new page markdown
2. Past xml code with ```

**Expected behavior**  

```xml
<test>test</test>
```

**Screenshots**
![2019-11-01 13_46_40](https://user-images.githubusercontent.com/33961658/68019952-295d4c00-fcae-11e9-9190-935f1e1f5aab.png)

**Host Info**
 - Server OS: CentOS 7
 - ClientOS: Windows 7
 - Browser: Google chrome
 - Wiki.js version: 2.0.0-rc17
 - Node.js version: 10.16.3
 - Database engine: PostgreSQL version: 9.2.24

**Comment by NGPixel** [comment]
Have you tried to actually save the page to see if this is only a preview pane issue or a page rendering issue?

**Comment by MurashovAlexander** [comment]
I not trying to save, pre rendering

**Comment by MurashovAlexander** [comment]
Only preview. After save it's working

**Comment by MurashovAlexander** [comment]
it works now. thank
