### ISSUE TITLE
Failed to Install in Win 7  with XAMPP

### ISSUE THREAD

**Issue by King-GO** [Requarks/wiki#1175]
1. download 
https://github.com/Requarks/wiki/releases/download/2.0.0-rc.17/wiki-js.tar.gz
2. Extract the package to D:\wiki.js
db: 

type:  MariaDB
`# PostgreSQL / MySQL / MariaDB / MS SQL Server only:`
host: localhost
port: 3306
user: root
pass:
db: wikijs
ssl: false

3. node server
config.yml ...OK

**invalid db type** 

**Host Info (please complete the following information):**
xampp 
OS: win7 
Wiki.js version: 2.0.0-rc.17
Database engine : 10.1.38-MariaDB

**Comment by NGPixel** [comment]
That's not a valid db type. You must use the values as listed just above:
https://github.com/Requarks/wiki/blob/master/config.sample.yml#L16-L21
