### ISSUE TITLE
 Increase the Bus Factor - Find more consistent contributors

### ISSUE THREAD

**Issue by robinhundt** [Requarks/wiki#1178]
Hello!

I'm part of the student representatives of the mathematics and computer science faculty of Göttingen (Germany). We're currently evaluating different wiki software and i stumbled upon this one. I've had a look at the v2 version and really, really like it and we're planning on using it for our internal  documentation.
The only thing which I'm feeling queasy about is the current [Bus Factor](https://en.wikipedia.org/wiki/Bus_factor) of 1 for this project. Especially for software which would be used for a longer time, storing important content, this is a non-negligible risk[1]. 

It seems like the maintainer @NGPixel would like to have more people on board as illustrated by the corresponding pages in the wiki, the blog posts and the Slack channel. However, finding more and especially recurrent contributors does not seem to work at the moment (after @NGPixel the next highest contributor has 6 commits). So why is that the case?
Here are some of my observations i made while reviewing this software:

#### Features are not planned
At the moment feature requests are submitted on https://requarks.canny.io/ . Users can upvote and comment on these features. While this is a nice way to get suggestions from people not on Github or those that might be discouraged from the developer centric ui, these feature requests are mostly not transferred back to Github.
In order to make it easier for people to contribute to this project, feature requests with enough upvotes/comments could be tracked as a Github issue with enough specification and hints where to start, such that it is possible for other people to have a go at the feature.

These planned features could be organized into Roadmaps, so that potential contributors know what to prioritise.

#### Issues have insufficient details / are sparsely labelled
Many of the current issues, especially the feature requests, lack crucial information needed for fixing the described bug or implementing the proposed feature.
Issues that have sufficient information and are not actively worked on could be labelled as `good-first-issue`, `easy`, `medium`, `hard`, etc. where applicable. This would give interested developers an easy starting point to contribute to the project.

I understand that building a community of contributors is a hard task, especially when a lot of time is invested into the project itself with the intention of maybe having it sustain oneself financially. Nevertheless I'm certain that increasing developer contribution to this project would improve the software, boost confidence in the long term availability, increase the reach and use of this wiki and ultimately also lead to more sponsors.

So, since I would very much prefer to use this project instead of the big PHP (:nauseated_face:) wikis and I know my way around Vue.js, if features are properly planned and documented, I'd happily try my best at some of them :blush: 

[1] wiki.js contributors https://github.com/Requarks/wiki/graphs/contributors compared to e.g. xwiki contributors https://github.com/xwiki/xwiki-platform/graphs/contributors

**Comment by NGPixel** [comment]
Thanks for the suggestions. You're completely right. Since I'm mostly focused on the development and not so much on planning / issues management in the little time I have to work on this project, it's definitely lacking in that regard.

The labels for issues is a really good idea and I'll definitely start using them going forward. I'll look into implementing your other ideas concerning feature planning.

As for the Bus Factor of 1, I suggest enabling the Git synchronization module which makes all your content usable by any other wiki software supporting git. ;)
