### ISSUE TITLE
Liquid hightlight

### ISSUE THREAD

**Issue by wowgamr** [Requarks/wiki#118]
### Actual behavior
If user select Liquid hightlight for code (liquid+html), HTML ignored by system.
### Expected behavior
HTML must not be converted.

### Steps to reproduce the behavior
Put on page code with Liquid Hightlight. For example:
```
{% for language in languages %}
<a href="{{ language.switch_url }}"><img src="{{ language.icon_url }}" alt="{{ language.title }}" title="{{ language.title }}"></a>
{% endfor %}
```

**Comment by NGPixel** [comment]
Fixed for Beta 12 (4632330d7c8a9fa1bfb231c222e393658b95d707)
