### ISSUE TITLE
Admin Search bug

### ISSUE THREAD

**Issue by sbonaime** [requarks/wiki#1180]
Before searching, as I have 56 pages, I have 4 pages to see in the result list. When I search something like "aaa", I still have at the bottom of the search the 4 pages icons even if I don't have any results ! 

![Capture d’écran 2019-11-05 à 05-11-19 11 25 16](https://user-images.githubusercontent.com/750709/68199985-5025c600-ffbf-11e9-9df0-7fb08a5d8983.png)

**Comment by thilak007** [comment]
@NGPixel , I would like to work on this bug as my first contribution.

**Comment by craph** [comment]
Hello @NGPixel I think you can close this issue because you already accept this PR https://github.com/Requarks/wiki/pull/4280

Best regards, 😃
