### ISSUE TITLE
Change page location bug with PostgreSQL search active

### ISSUE THREAD

**Issue by sbonaime** [Requarks/wiki#1181]
When I move a page to another directory I have this bug
![Capture d’écran 2019-11-05 à 05-11-19 11 32 30](https://user-images.githubusercontent.com/750709/68200432-215c1f80-ffc0-11e9-81a9-759b39572b9c.png)

The file of the page is not moved but the page is then reachable at the new location...

**Comment by NGPixel** [comment]
Fixed by 3183014b258856f2eb288ee31d875a71d9800641
