### ISSUE TITLE
Administrator can't delete Users

### ISSUE THREAD

**Issue by florianehmann** [Requarks/wiki#1184]
**Describe the bug**
The Administrator of the instance (user created during initial configuration and sole member of the group *Administrators*) can't delete users because the delete button is disabled.

**To Reproduce**
1. Go to *Administration*
2. Go to *Users*
3. Click on a User that is neither Administrator nor Guest
4. See disabled delete button

**Expected behavior**
As Administrator this button should not be disabled and permit the removal of the selected user.

**Host Info**
 - OS: Docker (Image by requarks)
 - Wiki.js version: 2.0.0-rc.17
 - Database engine: postgres-9.6.15 (Official Docker Image with alpine)

**Additional context**
Is this action allowed with the permission `manage:system`?

**Comment by aiveras** [comment]
Is there a workaround at the moment?

**Comment by enyachoke** [comment]
> This feature is not implemented yet and will be available in a future build.

But the project is a 2.0.1 and is marked as a stable release? So should someone considering wikijs stick to v1.x.x until issues like this are sorted out.

**Comment by FlyingBBQ** [comment]
What is the current status of this? I experience the same problem that I cannot delete users.

**Comment by NGPixel** [comment]
This is already fixed in the upcoming release:

https://docs.requarks.io/releases#upcoming-21

**Comment by julianoduarte1983** [comment]
Hello @NGPixel ,

   Could you tell us when the new version will be release?

   I need delete some user but it's not possible...

Best Regards

**Comment by gaelalso** [comment]
I'm on the same case.
