### ISSUE TITLE
Logged out and cannot log in until cookies are cleared

### ISSUE THREAD

**Issue by mandykaandorp** [Requarks/wiki#1185]
**Describe the bug**
I am editing and creating pages and after a wile i am no longer logged in, it seems like I get Read-only rights as I can only view the contents (I was logged in as admin (and did not log out or restart my browser, I just navigated to another page)). I have no users with read-only rights, i disabled all rights for the Guest account. 
I have to clear my cookies and restart my browser otherwise I cannot log in as the user I am. 

**To Reproduce**
Browse and edit for a while and all of the sudden (I don't know when or how it triggers) the icon on the top right (on mouse hover) says 'Login' instead of 'Account'.
When clicking 'Login' and then logging in I get the same screen. Only when clearing my cookies and restarting the browser I can login (with the same credentials) and I can continue editing paged etc..

**Expected behavior**
Keep me logged in. 

**Host Info (please complete the following information):**
 - OS: Linux - Ubuntu Linux (bionic) 18.0.4 x64 
 - Wiki.js version: 2.0.0-rc.17
 - Database engine: postgres 10.10

**Comment by NGPixel** [comment]
Go to **Administration** > **Authentication** and scroll down completely. Make sure Token Expiration is set to `30m` and Token Renewal to `14d`. Logout and log back in.

Open your browser Developer Tools (F12) > Application > Cookies (in chrome). Copy the value of the `jwt` cookie. Browse to https://jwt.io/ and paste the value in the **Encoded** field. Copy the value of the **Payload** box and paste it here (just replace any personal info such as your email with asterisks).

Wait 40 minutes (or when you get the issue again) and do the same process again (copy the jwt, unencode it on jwt.io and paste the payload here).

**Comment by mandykaandorp** [comment]
Thank you for your quick reply. 
The settings where as you described: 30m and 14d. 

Logged in with Token Expiration set to 30m and Token Renewal to 14d:
```
{
  "id": 1,
  "email": "**@**.**",
  "name": "Administrator",
  "pictureUrl": null,
  "timezone": "America/New_York",
  "localeCode": "en",
  "defaultEditor": "markdown",
  "permissions": [
    "manage:system"
  ],
  "groups": [
    1
  ],
  "iat": 1573112520,
  "exp": 1573114320,
  "aud": "urn:wiki.js",
  "iss": "urn:wiki.js"
}
```

Cookie after the issue happened (when on the upper right no options are available execpt login), this was about 1h and 15 minutes later: 
```
{
  "id": 1,
  "email": "**@**.**",
  "name": "Administrator",
  "pictureUrl": null,
  "timezone": "America/New_York",
  "localeCode": "en",
  "defaultEditor": "markdown",
  "permissions": [
    "manage:system"
  ],
  "groups": [
    1
  ],
  "iat": 1573116739,
  "exp": 1573118539,
  "aud": "urn:wiki.js",
  "iss": "urn:wiki.js"
}
```

And then after clearing the cookies and restarting the browser: 
```
{
  "id": 1,
  "email": "**@**.**",
  "name": "Administrator",
  "pictureUrl": null,
  "timezone": "America/New_York",
  "localeCode": "en",
  "defaultEditor": "markdown",
  "permissions": [
    "manage:system"
  ],
  "groups": [
    1
  ],
  "iat": 1573117033,
  "exp": 1573118833,
  "aud": "urn:wiki.js",
  "iss": "urn:wiki.js"
}
```

**Comment by c0ldplasma** [comment]
I have exactly the same problem.

**Host**
CentOS 7 
wiki.js 2.0.12 running with docker behind nginx reverse proxy
PostgreSQL 11.6

Token Expiration 30m and Token Renewal 14d is set.

Working Cookie:
`{
  "id": 1,
  "email": "*@*.com",
  "name": "Administrator",
  "pictureUrl": null,
  "timezone": "America/New_York",
  "localeCode": "en",
  "defaultEditor": "markdown",
  "permissions": [
    "manage:system"
  ],
  "groups": [
    1
  ],
  "iat": 1580642979,
  "exp": 1580644779,
  "aud": "urn:wiki.js",
  "iss": "urn:wiki.js"
}`


_Will add broken cookie later_

**Comment by mandykaandorp** [comment]
Hi, 

We still experience the same issue, is there something we can do to fix this?

Regards.

**Comment by c0ldplasma** [comment]
Issue is still present with Wikijs Version 2.2.51

**Comment by Smankusors** [comment]
is there any logs from Wiki.js regarding of this?

**Comment by mandykaandorp** [comment]
I just upgraded to version 2.5.144 and the issue is still present. Do you have any idea where I can find the relevant logs (log level is set to 'info')? My OS is Ubuntu. 
Help is really appreciated.

**Comment by c0ldplasma** [comment]
I did a completely fresh install of wikijs with 2.5.144 and still had the problem. I was able to fix it by changing my Nginx reverse proxy settings to the ones recommended here: https://docs-legacy.requarks.io/wiki/admin-guide/setup-nginx.

Old **_not working_** settings:
```nginx
location   /   {
                add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload";
                add_header Referrer-Policy "same-origin";
                proxy_cookie_path / "/; secure; HttpOnly";
                proxy_set_header Host $http_host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_pass http://127.0.0.1:32786;
        }
```
New _**working**_ settings:
```nginx
location / {
                proxy_set_header Host $http_host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_pass http://127.0.0.1:32786;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_next_upstream error timeout http_502 http_503 http_504;
        }
```

Don't know exactly what line exactly did the trick.

**Comment by mandykaandorp** [comment]
@c0ldplasma Thank you for your comment, I think that also fixed it for me. I only had to remove `proxy_cookie_path / "/; HTTPOnly; Secure";` to get the working settings, so it seems that line was the issue.
