### ISSUE TITLE
Page Properties should allow switching template type.

### ISSUE THREAD

**Issue by arieljake** [requarks/wiki#1186]
Not submitting a feature request...creating the issue to prompt a discussion first. If it's possible and warranted I'll submit on the wiki.

Can Page Properties offer a path to change from a Markdown page to a Code page?

**Comment by NGPixel** [comment]
It will be possible for some editors yes. For example, Markdown to Code or Visual Editor will be possible.

**Comment by albertosoho** [comment]
Hi, is this possible? Can i switch from markdown to html?

**Comment by NGPixel** [comment]
@albertosoho https://requarks.canny.io/wiki/p/switching-from-an-editor-to-another-on-an-existing-page

**Comment by regevbr** [comment]
@NGPixel I might be inclined to implement this feature :-)
I think we can start with switching between visual and html editor, and keep the more "complicated" switching to later on.
Do you have any pointers before I start or should I just go freestyle?

**Comment by NGPixel** [comment]
It should be an option in the Page Properties dialog, which calls a GraphQL resolver (e.g. pages > changeEditor) which calls a method in the pages model. Then reload the page on success, which would load the new editor.

**Comment by justein230** [comment]
This feature would be hugely helpful for my organization, and would allow me to put it into production! @regevbr I watched the GIF and the fix looks fantastic! Excited to see this in prod soon 😃

**Comment by Ximmer00** [comment]
+1 On this implementation
