### ISSUE TITLE
Find pages after upgrade and change to another lang

### ISSUE THREAD

**Issue by rickywu** [Requarks/wiki#1187]
Use en as default languadge and created some pages before, 
But after upgrade to latest version the lang. change to zh as default and not found default pages after login, I have to add en in the url to navigate to previous pages

Also not found how to change page lang after created, the props.lang only one option

**Host Info:**
OS: CentOS 7
Wiki.js version: 2.0.0-beta.rc17
Database engine: mysql 5.7

**Comment by NGPixel** [comment]
You need to migrate your old pages to the new language. You can do so in the **Administration** > **Utilities** > **Content** > **Migrate all pages to target locale**.
