### ISSUE TITLE
Colorization of the link to uploaded documents

### ISSUE THREAD

**Issue by SharkProgramming** [Requarks/wiki#1189]
**Describe the bug**
The link to the document downloaded in the article is indicated in red as if the link was pointing to an empty page .

**To Reproduce**
1. Upload a Pdf file or other extension
2. Insert link to this this document in article
3. Save the page

**Expected behavior**
The link must be colorized in blue 

**Screenshots**
![issue5](https://user-images.githubusercontent.com/33226400/68287710-7319ae00-0083-11ea-835f-b97d9caa0182.png)

**Host Info:**
 - OS: Ubuntu 18.04.3
 - Wiki.js version: 2.0.0-rc.17
 - Database engine: MariaDB 10.3.18

**Comment by devp01** [comment]
I am also experiencing the same issue. After inserting a file from the assets section the link is turned red. Is there any way in which we could change it to Blue color.

**Comment by NGPixel** [comment]
Fixed by e35e68d76403a3fa1971aeb04e9065940055ee62
