### ISSUE TITLE
Encrypted pass in config.yml

### ISSUE THREAD

**Issue by naf3a** [Requarks/wiki#1195]
Hi guys,

Thank you for your amazing job.

I was wondering, is it possible to encrypt password of the **db** (postgres) in the `config.yml` file ?

> Not a native speaker, sorry for my english mistakes.

**Comment by NGPixel** [comment]
No.

If the password was encrypted, you'd need to provide the passphrase somehow, which defeats the purpose of encrypting it in the first place.
