### ISSUE TITLE
Wiki attempts to insert new users into database when using a different login method

### ISSUE THREAD

**Issue by nesl247** [Requarks/wiki#1196]
**Describe the bug**
When I installed the wiki I created my user as the default user. I then setup Azure AD and attempted to sign in that way. Instead of it detecting the user is the same that already exists, it attempts to do a duplicate insert into the database and throws the following error:

`insert into "users" ("createdAt", "email", "isActive", "isSystem", "isVerified", "localeCode", "name", "pictureUrl", "providerId", "providerKey", "tfaIsActive", "updatedAt") values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12) returning "id" - duplicate key value violates unique constraint "users_pkey"
`

**Expected behavior**
It should know the user already exists by the email and allow the user to login
![Screen Shot 2019-11-07 at 12 37 52 PM](https://user-images.githubusercontent.com/1037526/68413051-6ec0c400-015b-11ea-9bd6-86b556f34885.png)

**Host Info (please complete the following information):**
 - OS: Docker
 - Wiki.js version: 2.0.0 (81e6eacd6ec1c8034c2d33b3034c78d4f94fcd20)
 - Database engine: postgres 11

**Comment by NGPixel** [comment]
This is already fixed. It will be available in the next release.
