### ISSUE TITLE
Updating email of a user errors saying `An account already exists using this email address.`

### ISSUE THREAD

**Issue by nesl247** [Requarks/wiki#1197]
**Describe the bug**
When trying to update the email of the first user (this is a new installation with only 1 user), it errors with `An account already exists using this email address.`.

**To Reproduce**
1. Go to Administration
2. Go to Users
3. Edit the user
4. Update the email
5. Click Update User
6. Error

**Expected behavior**
The email should be updated

**Host Info (please complete the following information):**
 - OS: Docker
 - Wiki.js version: 2.0.0 (81e6eacd6ec1c8034c2d33b3034c78d4f94fcd20)
 - Database engine: postgres 11

**Comment by NGPixel** [comment]
Fixed by d356937660be6e027315115160795574d03fe741
