### ISSUE TITLE
Edit page tags

### ISSUE THREAD

**Issue by Oleg-Imanilov** [Requarks/wiki#1199]
**Question**
Where can I edit page tags?

**Host Info**
OS: Ubuntu 19, Docker
Wiki.js version: requarks/wiki:beta
Database engine: postgres

**Comment by SpoinkyNL** [comment]
When in the editor, at the top next to the save button click PAGE

![image](https://user-images.githubusercontent.com/8858506/68471038-9f693200-021d-11ea-8617-ea17cd0d2fea.png)

Then at the bottom of the popup you can change tags
