### ISSUE TITLE
Wiki.js seems to be missing something to allow it to run, or I'm missing someting

### ISSUE THREAD

**Issue by thomasmiguelthompson** [Requarks/wiki#12]
```0|wiki     |     at Module.require (module.js:498:17)
0|wiki     |     at require (internal/module.js:20:19)
0|wiki     |     at Object.<anonymous> (/var/www/html/libs/entries.js:7:18)
0|wiki     |     at Module._compile (module.js:571:32)
0|wiki     |     at Object.Module._extensions..js (module.js:580:10)
0|wiki     |     at Module.load (module.js:488:32)
0|wiki     |     at tryModuleLoad (module.js:447:12)
0|wiki     |     at Function.Module._load (module.js:439:3)
0|wiki     |     at Module.require (module.js:498:17)
0|wiki     |     at require (internal/module.js:20:19)```
Is some of the error log I've found

**Comment by NGPixel** [comment]
Seems like native modules were not compiled properly.
Stop wiki.js (`node wiki stop`) and then run the following commands:

```shell
npm install
npm rebuild
```

**Comment by nullpixel1** [comment]
@NGPixel I ran these commands, the wiki still isn't working.

If it helps, we're not running as root, and there's nothing logged into the logs anymore

**Comment by nullpixel1** [comment]
@thomasmiguelthompson Can be closed, the wiki requires root to run.

Or you can port redirect, like me `iptables -A PREROUTING -t nat -i eth0 -p tcp --dport 80 -j REDIRECT --to-port 8080`.

This could be made clearer in the documentation.

**Comment by thomasmiguelthompson** [comment]
Thanks ❤️
It was a pain to setup, but nevertheless is not bad

**Comment by NGPixel** [comment]
I added a Troubleshooting section in the documentation:

https://docs.wiki.requarks.io/troubleshooting

There's no need to run Wiki.js as root (and not recommended either). This is an issue with Node.js in general, not specific to Wiki.js. The port redirect is good solution however, authorizing the node user to use the 80 port is even better. Check solution A in the link above.

Nick
