### ISSUE TITLE
RC-17 First new User

### ISSUE THREAD

**Issue by sbonaime** [Requarks/wiki#1200]
At the creation of the first user, I had a red error similar to this one, if I can remember

![Capture d’écran 2019-11-08 à 08-11-19 13 52 10](https://user-images.githubusercontent.com/750709/68477959-017e6300-022f-11ea-9e59-2e85e5a1fac6.png)

I try a second time with the same information and get the same error. At the third try, I was able to register without changing anything ! 

I was then redirect to this page but without anyway to move to another one. Maybe a link to the login page could be inserted on this page

![Capture d’écran 2019-11-08 à 08-11-19 13 48 45](https://user-images.githubusercontent.com/750709/68478030-296dc680-022f-11ea-989f-fd6bf827cd3c.png)

For the second new user, I didn't have this error. Maybe same kind of problem as #1153

**Comment by NGPixel** [comment]
This is already fixed for the upcoming build.
