### ISSUE TITLE
Visual Editor - Documents and archives assets are not added to page

### ISSUE THREAD

**Issue by lokzzor** [Requarks/wiki#1207]
**Describe the bug**
Hello, I’m just starting to use your product so I don’t know much and face a number of problems. Documents and archives  are not added to the home page!!!

**To Reproduce**
1) create a page
2) insert assets
3) select folder
4) upload the file
5) click add

**Expected behavior**
that the file appears on the page, plans to have something like a list view of 10-14 positions
**Screenshots**
Video
**Host Info (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04.1, localhost]
 - Wiki.js version: [e.g. 2.0.0-rc.17]
 - Database engine: [e.g. postgres 10.10]
-  Node 12.13.0

[lol-2019.zip](https://github.com/Requarks/wiki/files/3836783/lol-2019.zip)

**Comment by NGPixel** [comment]
Fixed by d6f2176de2235c789cf79b1e6d8a75ab748756c0
