### ISSUE TITLE
Table of Contents

### ISSUE THREAD

**Issue by devp01** [Requarks/wiki#1208]
**Question**
Describe in details what you are trying to achieve and where do you need guidance.

**Host Info (please complete the following information):**
OS: [e.g. Ubuntu 18.04]
Wiki.js version: [Wiki.js 2.0.0-rc.17]
Database engine: [ mysql 8]

Is there any way we could change the layout of Table of Contents to be shifted to the right hand side of the page. In one of the earlier versions it was on the right hand side of the page.

**Comment by XerqJon** [comment]
@devp01 you can do this with css injection from the admin > themes section. You'd probably want to modify some other elements to make it fit better.

I imagine that once themes are released this will be possible and more efficient to do via themes.

An example:
```
.v-navigation-drawer {
left: auto !important;
right: 0px;
}
```
![image](https://user-images.githubusercontent.com/3145572/68771525-30f9ea80-05f6-11ea-8d22-d7781edf57f7.png)

This overrides the default position of the navigation drawer
![image](https://user-images.githubusercontent.com/3145572/68771505-24759200-05f6-11ea-9291-ad2087ea9f94.png)

**Comment by devp01** [comment]
@XerqJon XerqJon
Thank you for your reply. This actually changes the alignment of the entire navigation block. I am trying to move only the Tables of Contents from Left side to Right side of the page.
![image](https://user-images.githubusercontent.com/46513658/68836266-f4a2b900-06df-11ea-8322-529bd20038b7.png)
Currently it is Navigation Menu block---Table of Contents block---- Actual Page content
I am trying to achieve it as Navigation Menu block ---- Actual Page Content ---- Table of Contents block.

**Comment by NGPixel** [comment]
It's not possible to move the table of contents to the right at the moment. It will be available later once the themes feature is released.
