### ISSUE TITLE
Git SSH Private Key Contents and New Line (LF)

### ISSUE THREAD

**Issue by seafre** [Requarks/wiki#1209]
**Describe the bug**
Git SSH Private Key Contents, must include New Line (LF) at the end

**To Reproduce**
1. Go to 'Storage - Git'
2. Click on 'B - SSH Private Key Contents'
3. Paste SSH Private Key's contents ending with `-----END OPENSSH PRIVATE KEY-----` without New Line at end
```
Load key "/home/vcap/app/wiki/data/secure/git-ssh.pem": invalid format
git@xyz.com: Permission denied (publickey).
fatal: Could not read from remote repository. Please make sure you have the correct access rights and the repository exists. error: Could not fetch origin
```

**Expected behavior**
Git: Last synchronization a few seconds ago

**Additional context**
Minor bug, but prohibitive to new users who will not find what they have done wrong when following the instructions. In addition, documents and UI do not make it clear to switch "SSH Private Key Mode" so this minor bug would likely prohibit an initial setup.

**Comment by NGPixel** [comment]
Fixed by 19e4ab69d270bf7858e4d33666cf062b5dfdd6c6
