### ISSUE TITLE
Twemojis with hyphens in shortname don't render

### ISSUE THREAD

**Issue by maxproske** [Requarks/wiki#1211]
When you type an emoji shortname that contains hyphens (-) surrounded by colons in Wiki.js, it shows up on the page as plain text, and does not render as its respective Twemoji.

**To Reproduce**
1. Create a New Page
2. Select Markdown page type
3. Type `:rice: :ear-of-rice:`

**Expected behaviour**
```
🍚 🌾
```

**Actual behaviour**
```
🍚 :ear-of-rice:
```

**Host Info**
 - OS: Ubuntu 18.04, Docker
 - Wiki.js version: 2.0.0-rc.17
 - Database engine: postgres 11.5

**Additional Info**
Twemoji shortnames referenced from [twemoji-awesome.scss](https://github.com/Requarks/wiki/blob/master/client/libs/twemoji/twemoji-awesome.scss)

**Comment by NGPixel** [comment]
Replace `-` (dash) with `_` (lodash).
