### ISSUE TITLE
Update Authentication documentation for GHE

### ISSUE THREAD

**Issue by seafre** [Requarks/wiki#1212]
**Describe the bug**
Step-by-step guidance for new GHE setup

**Solution**

GitHub Enterprise steps:
1. Go to GitHub Enterprise in to add new OAuth App (e.g. https://github.DOMAIN.com/settings/applications/new)
2. Enter an Application Name (e.g. Wiki).
3. Enter as Homepage URL the Wiki.js URL (e.g. https://wikijs.HOST.com)
4. Enter for the Authorization callback URL, the Wiki.js URL followed by /login/github/callback (e.g. https://wikijs.HOST.com/login/github/callback)
5. Click Register Application
6. Note the Client ID and Client Secret of the new OAuth App in GitHub Enterprise
7. Go to Wiki.js, click Administration
8. In the left-side menu panel, under Modules, click Authentication
9. Click GitHub
10. Add the Client ID and Client Secret
11. Click the GitHub Enterprise toggle
12. Enter the GitHub Enterprise Domain, without prefix http:// or https:// (e.g. github.DOMAIN.com)
13. Enter the GitHub Enterprise User Endpoint with prefix https:// (e.g. https://api.github.DOMAIN.com/user)
14. Click the Allow self-registration toggle
15. Ignore the email domain limitation, which will allow any user authorized through GitHub Enterprise with any email address to be registered
16. Click Assign to group, which will be default for all self-registered users

**Comment by NGPixel** [comment]
GitHub page is now online, based on your steps.

https://docs.requarks.io/en/auth/github
