### ISSUE TITLE
Fresh install with MySQL 8 on setup page cannot continue You have an error in your SQL syntax;

### ISSUE THREAD

**Issue by cdbug** [Requarks/wiki#1213]
**Describe the bug**
Fresh install of 2b. RC.17 
On the setup screen after entering email and desired password I get:

> ALTER TABLE groups AUTO_INCREMENT = 1 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'groups AUTO_INCREMENT = 1' at line 1

and setup does not continue or complete.

> ![2019-11-14_09-25-18](https://user-images.githubusercontent.com/55088829/68862519-e065b880-06ed-11ea-9801-a68621fa93d6.jpg)

**To Reproduce**
1. Fresh install and 1st step - complete setup.

**Expected behavior**
To complete setup 

**Screenshots**

**Host Info (please complete the following information):**
 - OS: CentOS
 - Wiki.js version: 2.0.0-beta.rc17
 - Database engine: MySQL v.8.0.18

**Additional context**
- No issues or error messagges during starting the `node server` - Successfully connected to the database.
- Using  "mysql_native_password"
- Tried with 2 fresh different databases and users

**Comment by NGPixel** [comment]
This is fixed in 2.0.1
