### ISSUE TITLE
Edit group page layout could be better

### ISSUE THREAD

**Issue by sbonaime** [Requarks/wiki#1218]
Selected tab on Edit group page layout could be better on large screen
![Capture d’écran 2019-11-15 à 15-11-19 10 33 41](https://user-images.githubusercontent.com/750709/68933103-43118f80-0794-11ea-9e34-539cc8361a89.png)

**Comment by NGPixel** [comment]
Fixed by bf47e310f5b87f3437e4ebbeb09423f84f75912b
