### ISSUE TITLE
Permissions for global navigation items (links).

### ISSUE THREAD

**Issue by roman-tiukh** [Requarks/wiki#1219]
**Question**
Hello, I would like for users who do not have permissions to view pages do not draw items (links) of global navigation.
A solution would also be good to set permissions for global navigation items (links).
I want users who do not have access to the page to not see these items (links) in the global navigation.

How can i do this?

PS: Google translate.

**Host Info (please complete the following information):**
OS: Debian 10.1
Wiki.js version: 2.0.0-rc.17
Database engine: postgres 11

**Comment by NGPixel** [comment]
https://wiki.js.org/feedback/p/sidebar-navigation-permissions

**Comment by roman-tiukh** [comment]
Thanks, I will wait for this feature. =)
