### ISSUE TITLE
Dashboard Subtitle says BETA in Production release

### ISSUE THREAD

**Issue by XerqJon** [Requarks/wiki#1224]
I just upgraded from beta rc17 to production 2.0.1 and noticed the admin dashboard still displays the text "BETA build - NOT FOR PRODUCTION RELEASE". Minor thing but may confuse some.

**To Reproduce**
1. Go to admin dashboard after upgrading to 2.0.1

**Expected behavior**
Display other text in this line or nothing at all

**Screenshots**
![image](https://user-images.githubusercontent.com/3145572/69052838-0634db00-09d6-11ea-8ec0-dc24f7cfba18.png)

**Host Info (please complete the following information):**
 - OS: Ubuntu 18.04, Docker
 - Wiki.js version: 2.0.1
 - Database engine:  postgres 10.10

**Comment by NGPixel** [comment]
Translation updated. Wait 24h or restart Wiki.js to get the changes.
