### ISSUE TITLE
Is there a way to change the locale namespace of Navigation

### ISSUE THREAD

**Issue by LionNatsu** [requarks/wiki#1225]
**Question**
I want to create another Navigation panel for the second language namespace, but I cannot find a way to do this... Did I miss something?

**Host Info (please complete the following information):**
OS: Linux Debian (buster) 10 x64
Wiki.js version: master
Database engine: psql

**Comment by NGPixel** [comment]
At the moment, the navigation on the left is global to all languages. This will be improved in a future release to allow for per-language nav and per-permissions.

**Comment by windware-ono** [comment]
I think this is now implemented but if I copy the navigation list from another language with 'Copy from locale...' button, it copies but whenever I edit those, they're reflected on all language namespaces. If I manually add an entry to a language namespace, they seem to remain specific to that language.

**Comment by noisymime** [comment]
I'm seeing the same result of @windware-ono here. The dropdown is there on the navigation page to select the locale, however changes in this appear to be global and the same navigation menus is always used, regardless of the selected locale.

**Comment by hallowatcher** [comment]
We're having the same issue. This needs more awareness!!

**Comment by sarajw** [comment]
Same issue here! So currently do I need to remake the navigation from scratch, in order to be able to edit it and not change the original?
