### ISSUE TITLE
New account verification email link in Wiki.js v2.0.1 results in timeout

### ISSUE THREAD

**Issue by ravenzachary** [Requarks/wiki#1227]
**Describe the bug**
I created a new account on a Wiki.js v2.0.1 instance and a verification email was received (although oddly delayed). When the verification email was received, I clicked the link and the browser just spins and spins trying to resolve the link.

**To Reproduce**
1. Register a new account.
2. Click the link on the verification email.
3. The link loads, but the browser spins and spins, and finally displays an error page. The link format is : http://wiki.mepbm.com/verify/irQczOAtqKcXaZvZu0b85

**Expected behavior**
A verification email link should result in a verified user account on Wiki.js v2.0.1..

**Screenshots**
![Screen Shot 2019-11-18 at 1 47 32 PM](https://user-images.githubusercontent.com/645975/69097093-aefd2d80-0a0a-11ea-81ec-fb1aa65d79f3.png)
![Screen Shot 2019-11-18 at 1 57 40 PM](https://user-images.githubusercontent.com/645975/69097502-86c1fe80-0a0b-11ea-8d41-bbf18df389b7.png)

**Host Info (please complete the following information):**
 - OS: Ubuntu 19.04 x64
 - Wiki.js version: 2.0.1
 - Database engine: postgres

**Additional context**

**Comment by ravenzachary** [comment]
Also, of note, it looks like the verification email is generating an HTTP link instead of an HTTPS link for some reason.

**Comment by ravenzachary** [comment]
Ok, it looks like the user was verified from the link, even if the browser never displayed a success page.

**Comment by NGPixel** [comment]
Fixed by 3d6b04f75d350291f95fb9e4edc69a2fe367eb21

@ravenzachary The link is based on the site URL you entered in Admin Area > General. Make sure it is set using HTTPS if that's the case.

**Comment by dockerdeploys1** [comment]
how to Remove email from registration field in wiki.JS

**Comment by AMDphreak** [comment]
Please fix this so that the instance determines whether HTTP or HTTPS is being used.

My users are getting links to an HTTPS page when the instance is running on HTTP instead. This bug goes both ways. Please stop hard-coding anything at all.

**Comment by NGPixel** [comment]
@AMDphreak What are you talking about. Nothing is hardcoded. **If you actually took the time to read the comments to this issue**, you would have found out that this is set **by you** in the **Admin** > **General** section. Change your site URL to use http and it will work.
