### ISSUE TITLE
Anchored header are below the nav bar

### ISSUE THREAD

**Issue by mkende** [Requarks/wiki#1229]
**Describe the bug**
When following a bug to an anchor in a page, the target header is under the navigation bar instead of being below it.

**To Reproduce**
1. Ensure that all https://docs.requarks.io tabs are closed on your browser
2. Go to https://docs.requarks.io/install/upgrade#linux-macos
3. See that the **Linux / masOS** header is not visible
4. Scroll up a little, the header becomes visible

**Expected behavior**
The header should be visible when the page has loaded.

Note that this does not occur on reload of the page after the initial load (although shift + F5 allows to reproduce the issue).

**Screenshots**

**Host Info (please complete the following information):**
 - OS: Debian buster
 - Wiki.js version: 2.0.1
 - Database engine: SQLite

 - Client browser: Chrome

**Comment by NGPixel** [comment]
I can't replicate your issue. I tested in all browsers + mobile using link https://docs.requarks.io/install/upgrade#linux-macos and the anchor is shown properly:

![image](https://user-images.githubusercontent.com/15522395/69166670-a0be1880-0ac1-11ea-8f84-7250b517d299.png)
