### ISSUE TITLE
Blockquote on multiple lines does not use the style correctly

### ISSUE THREAD

**Issue by juliendms** [Requarks/wiki#1234]
**Describe the bug**
When using blockquote on multiples lines and a custom style, eg:
```md
> Hello
> Word
{.is-success}
```
The blockquote does not use the specified style (here: success).

**To Reproduce**
1. Create a new page
2. Insert
```md
> Hello
> Word
{.is-success}
```
3. Check the preview

**Expected behavior**
The style of the blockquote should be applied just like when using one line:
```md
> Hello Word
{.is-success}
```

**Host Info (please complete the following information):**
 - Wiki.js version: 2.0.1

**Comment by NGPixel** [comment]
I can't replicate your issue. I copied your exact example code and it works just fine...

**Comment by juliendms** [comment]
My bad. There is actually an issue when the blockquote contains a list. Here is the exact syntax that does not work:
```md
> Hello Word:
> - Item 1
> - Item 2
{.is-success}
```

**Comment by juliendms** [comment]
See #1241
