### ISSUE TITLE
Wiki JS error Authentication LDAP

### ISSUE THREAD

**Issue by Yuri-Zizeko** [Requarks/wiki#1239]
Linux - Debian (linux) 10.2 x64
Node.js 10.15.2
PostgreSQL 12.1

Config:
LDAP URL: ldap://10.1.1.2:389
Admin Bind DN: cn=test,OU=MAN,OU=OLD,OU=Company,dc=test,dc=com
Admin Bind Credentials: P@$$w0rd!
Search Base: OU=MAN,OU=OLD,OU=Company,dc=test,dc=com
Search Filter: searchFilter: '(sAMAccountName={{username}})'

Error:
Invalid email / username or password.

Port 389 is open 
Checked by telnet

The domain controller responds

**Comment by Yuri-Zizeko** [comment]
Perhaps you need to install additional software?

**Comment by NGPixel** [comment]
In the admin area > Dev > Flags. Enable the LDAP Debug flag. Then look at the logs during a login attempt. You should see any error returned by the server.

**Comment by Yuri-Zizeko** [comment]
2019-11-21T08:07:57.170Z [MASTER] warn: LDAP LOGIN ERROR (c1): Invalid email / username or password.

**Comment by Yuri-Zizeko** [comment]
This configuration works successfully on v1.0.117

**Comment by NGPixel** [comment]
Can you screenshot the Search Filter field in the admin area > Auth > LDAP?

**Comment by Yuri-Zizeko** [comment]
![1](https://user-images.githubusercontent.com/57997479/69516286-4b22b980-0f62-11ea-87ca-7a7c006e4b80.png)

**Comment by Yuri-Zizeko** [comment]
Does anyone work with Ldap authentication?

**Comment by kingfisher77** [comment]
Yes, we got it to work with ldaps.

**Comment by Yuri-Zizeko** [comment]
> Да, мы получили его для работы с ldaps.

Help with authentication settings please

**Comment by pirvana** [comment]
Help with the authentication settings, please, I need you to authenticate without having to modify the "mail" field, in the ldap
![image](https://user-images.githubusercontent.com/23135703/69878112-b93ce880-12a2-11ea-8206-bb5fb778bf8f.png)

**Comment by inginheiiro** [comment]
I've the same problem.... i believe there is a bug in file server/core/auth.js
in the  authenticate function "you" do not validate the defined authentication strategy, in this case LDAP... you are assuming jwt auth...

**Comment by NGPixel** [comment]
@inginheiiro No, you're confusing the authorization strategy (always JWT) and the authentication strategy (LDAP, local, google, etc.). They are completely unrelated.

**Comment by kingfisher77** [comment]
> Help with the authentication settings, please, I need you to authenticate without having to modify the "mail" field, in the ldap
> ![image](https://user-images.githubusercontent.com/23135703/69878112-b93ce880-12a2-11ea-8206-bb5fb778bf8f.png)

You could try this:
`(|(uid=%uid)(mail=%uid))
`
Here LDAP attributes uid or mail can be used for wiki field uid.

**Comment by hbokh** [comment]
Same issue here. Using the exact same OpenLDAP credentails from wiki 1.0 in 2.0.
The `slapd` loggin is **almost** the same, except for one line: Wiki JS 1.0 has `SRCH attr=displayName name cn mail` and Wiki JS 2.0 does not:

Wiki JS v2.0.12:
```
Nov 30 14:46:43 ldap001 slapd[564]: conn=1004 fd=9 ACCEPT from IP=10.0.0.1:59926 (IP=0.0.0.0:389)
Nov 30 14:46:43 ldap001 slapd[564]: conn=1005 fd=13 ACCEPT from IP=10.0.0.1:59928 (IP=0.0.0.0:389)
Nov 30 14:46:43 ldap001 slapd[564]: conn=1004 op=0 BIND dn="cn=Manager,dc=example,dc=org" method=128
Nov 30 14:46:43 ldap001 slapd[564]: conn=1004 op=0 BIND dn="cn=Manager,dc=example,dc=org" mech=SIMPLE ssf=0
Nov 30 14:46:43 ldap001 slapd[564]: conn=1004 op=0 RESULT tag=97 err=0 text=
Nov 30 14:46:43 ldap001 slapd[564]: conn=1004 op=1 SRCH base="ou=People,dc=example,dc=org" scope=2 deref=0 filter="(uid=hbokh)"
Nov 30 14:46:43 ldap001 slapd[564]: <= mdb_equality_candidates: (uid) not indexed
Nov 30 14:46:43 ldap001 slapd[564]: conn=1004 op=1 SEARCH RESULT tag=101 err=0 nentries=1 text=
Nov 30 14:46:43 ldap001 slapd[564]: conn=1005 op=0 BIND dn="uid=hbokh,ou=People,dc=example,dc=org" method=128
Nov 30 14:46:43 ldap001 slapd[564]: conn=1005 op=0 BIND dn="uid=hbokh,ou=People,dc=example,dc=org" mech=SIMPLE ssf=0
Nov 30 14:46:43 ldap001 slapd[564]: conn=1005 op=0 RESULT tag=97 err=0 text=
Nov 30 14:46:43 ldap001 slapd[564]: conn=1004 op=2 UNBIND
Nov 30 14:46:43 ldap001 slapd[564]: conn=1004 fd=9 closed
```

Wiki JS v1.0.117:
```
Nov 30 14:49:25 ldap001 slapd[564]: conn=1006 fd=9 ACCEPT from IP=10.0.0.1:60374 (IP=0.0.0.0:389)
Nov 30 14:49:25 ldap001 slapd[564]: conn=1007 fd=14 ACCEPT from IP=10.0.0.1:60376 (IP=0.0.0.0:389)
Nov 30 14:49:25 ldap001 slapd[564]: conn=1006 op=0 BIND dn="cn=Manager,dc=example,dc=org" method=128
Nov 30 14:49:25 ldap001 slapd[564]: conn=1006 op=0 BIND dn="cn=Manager,dc=example,dc=org" mech=SIMPLE ssf=0
Nov 30 14:49:25 ldap001 slapd[564]: conn=1006 op=0 RESULT tag=97 err=0 text=
Nov 30 14:49:25 ldap001 slapd[564]: conn=1006 op=1 SRCH base="ou=People,dc=example,dc=org" scope=2 deref=0 filter="(uid=hbokh)"
Nov 30 14:49:25 ldap001 slapd[564]: conn=1006 op=1 SRCH attr=displayName name cn mail
Nov 30 14:49:25 ldap001 slapd[564]: <= mdb_equality_candidates: (uid) not indexed
Nov 30 14:49:25 ldap001 slapd[564]: conn=1006 op=1 SEARCH RESULT tag=101 err=0 nentries=1 text=
Nov 30 14:49:25 ldap001 slapd[564]: conn=1007 op=0 BIND dn="uid=hbokh,ou=People,dc=example,dc=org" method=128
Nov 30 14:49:25 ldap001 slapd[564]: conn=1007 op=0 BIND dn="uid=hbokh,ou=People,dc=example,dc=org" mech=SIMPLE ssf=0
Nov 30 14:49:25 ldap001 slapd[564]: conn=1007 op=0 RESULT tag=97 err=0 text=
Nov 30 14:49:25 ldap001 slapd[564]: conn=1006 op=2 UNBIND
Nov 30 14:49:25 ldap001 slapd[564]: conn=1006 fd=9 closed
Nov 30 14:49:25 ldap001 slapd[564]: conn=1007 op=1 UNBIND
Nov 30 14:49:25 ldap001 slapd[564]: conn=1007 fd=14 closed
```

**Comment by pirvana** [comment]
@kingfisher77 Good friend, this is what appeared to me when placing what you requested, one more thing, it only worked without the symbol "|" (tube), any other option that could help me?
![image](https://user-images.githubusercontent.com/23135703/69956804-cb579a80-14df-11ea-81f6-d93e821e26d2.png)
![image](https://user-images.githubusercontent.com/23135703/69956831-ddd1d400-14df-11ea-907e-e88e776cee67.png)

**Comment by juliendms** [comment]
Our LDAP access is configured and working well. We had some troubles with some users who did not have the `mail` field filled in the AD. It seems like the `mail` is required for self-registration, maybe you should check if you can connect with an account from the LDAP that is using the same username AND mail. Are yo using self-registration ? Are the users already created on Wiki.JS ?

**Comment by pirvana** [comment]
Thank you for responding @juliendms , I comment that users are not created yet, I would like them to be created automatically, and I answer that if I complete the "mail" field in the LDAP if it works correctly, but if it does not have that field the user cannot enter, and I need it to be created automatically, or you can log in only with your user account without requesting "mail"

**Comment by juliendms** [comment]
I _would_ guess that for now the mail field is required when creating a user, therefore if this field is empty the creation of the user fails. It is _I guess_ because this field is the username when creating a new user locally.
You might be able to do a kind of script that will fill the mail with the username from the LDAP and append a `@company.com`, that's something worth checking. Sorry I cannot help much more.

**Comment by ethanmdavidson** [comment]
@pirvana it looks like you need to change the search filter to use the attribute that is actually holding the username. For example, my company uses Active Directory and I had to use the search filter `(sAMAccountName={{username}})` because the username is stored in the `sAMAccountName` attribute. 
Try using an LDAP browser to look at all the attributes on your user object, find the one that contains the username, and change the filter to use that attribute.

**Comment by vtjc2002** [comment]
Here is what worked for me and this works with "Allow self-registration"  as well

![wikijs_ldap_config](https://user-images.githubusercontent.com/8717495/70251047-d8c58c80-174c-11ea-8368-069df9e403e0.jpg)

**Comment by pirvana** [comment]
Thanks to all, really, I tried each one of the solutions that they wrote to me but still it doesn't let me just talk to the user, without having the "mail" field, configured in the LDAP, it would be great if this did not request :(, but Thank you all, I will continue looking for some way to solve this

**Comment by Yuri-Zizeko** [comment]
000004DC: LdapErr: DSID-0C090A4C, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v3839

**Comment by dieterv** [comment]
I've been hitting the exact same "warn: LDAP LOGIN ERROR (c1): Invalid email / username or password." error for a couple of days now.

Finally solved it after:
*  resetting the password
*  setting the "user cannot change password" property
*  setting the "password never expires" property

of the Active Directory "Admin Bind DN" account.
I'm sure the exact same password was used when creating the "Admin Bind DN" account so I have no idea why this worked...

**Comment by fordanic** [comment]
Using the same setup as for my 1.0 installation but this fails for my 2.0 installation with the following error:
` warn: LDAP LOGIN ERROR (c1): Invalid email / username or password.`
Used credentials are good as they work for other services using a similar LDAP connection.

Running a docker setup of wikijs. What can I do to improve logging?

**Comment by fordanic** [comment]
To me, I in the end solved it by removing all "" that were used for bindings and similar.

**Comment by julianoduarte1983** [comment]
Hello guys,

   I was with tha same problem. 

   So, I solved it enabling auto self-registration on LDAP authentication.

   Thanks @hbokh  ;)

**Comment by SirGibihm** [comment]
Keep in mind that the same error message (see below) comes up when your Bind Credentials **AND/OR** your Login Credentials are wrong. The logging from my docker container (wikijs version 2.2.51, LDAP Logging enabled through the debug flag at Administration>Developer Tools>Flags) show for both invalid login credentials the following error: 
```bash
warn: LDAP LOGIN ERROR (c1): Invalid email / username or password.
```

In other news: My LDAPS example config that works perfectly for Wikijs 2 looks like this, I had to redact passwords etc. but I hope it helps you with syntax; everything blurred out is a normal string: 

<img width="1005" alt="Screenshot 2020-04-07 at 13 58 31" src="https://user-images.githubusercontent.com/61882185/78667256-e779a700-78d8-11ea-8f81-c27da12771d8.png">

**Comment by denisbonate** [comment]
Help me please.
![image](https://user-images.githubusercontent.com/57956632/79245731-dc7dc400-7e4e-11ea-8b3f-606f02495137.png)

**Comment by ramonjoaquim** [comment]
Try
` (sAMAccountName={{username}}*)`
and verify if your AD have the mail mapped field for e-mail, in my case I discovered the mail field are **userPrincipalName**, then my search filter looks like that
Solution
` (|(sAMAccountName={{username}}*) (userPrincipalName={{username}}*))`

**Comment by flagal** [comment]
LDAP works for me. The problem was  **Search Filter** field. I put in (mail={{username}}). In **Unique ID Field Mapping**, I put sAMAccoutName.
