### ISSUE TITLE
Can't log in after fresh install

### ISSUE THREAD

**Issue by YasOpissoCoSA** [Requarks/wiki#124]
I installed the Wiki several times in Windows Server R2. Everything seems fine except I can't get into the Wiki, I've set the admin account several times, I've also set "public" and "defaultReadAccess" to true but still can't get in, all I get is invalid login. I've disabled (and deleted) all login options except local without success. Can someone point me out in the right path, I'm I missing something?

Thanks.

**Comment by NGPixel** [comment]
Have you run the configuration wizard and entered the desired email / password for the root admin during the last step?

**Comment by YasOpissoCoSA** [comment]
@NGPixel Yes I have, I've run the configuration multiple times, I can see the entry in the Database under "admin/users" everything seems fine. Still no luck, I get Invalid Login. I've done this around 5 times already through multiple computers.

**Comment by marshallaf** [comment]
Did you use the same name of the data folder for the wiki (`./data`) as for the MongoDB path (`mongod --dbpath=./data`)? I accidentally did this and it caused the login issue that you're describing.

**Comment by YasOpissoCoSA** [comment]
@marshallaf Interesting thought, I mostly sure that's not the case but I'll check nonetheless.

**Comment by YasOpissoCoSA** [comment]
I figured the issue. When setting the database parameters I was not entering the /wiki at the end.

**Comment by NGPixel** [comment]
👍 Glad you got it resolved. Closing this issue.
