### ISSUE TITLE
Markdown target:_blank doesn't work

### ISSUE THREAD

**Issue by XerqJon** [Requarks/wiki#1240]
**Describe the bug**
When using the markdown editor and adding `{target: "_blank"} after a URL, it shows up in preview with the proper HTML attributes. Once the page is saved and loaded the attribute is missing from the href snippet.

**To Reproduce**
1. Create/edit page using markdown editor
2. Add URL
3. Add `{target: "_blank"} after the url
4. See in preview the link opens in a new tab
5. Save page and close editor - link opens in current tab

**Expected behavior**
Link should open in new window/tab.

**Screenshots**
![image](https://user-images.githubusercontent.com/3145572/69250041-f277a900-0b7c-11ea-8026-6aab8cc7097d.png)

**Host Info (please complete the following information):**
 - OS: Ubuntu 18.04, Docker
 - Wiki.js version: 2.0.1
 - Database engine: postgres 10.10

**Additional context**
From slack thread ([link](https://requarks.slack.com/archives/C49J7AB8R/p1574185465419400))

**Comment by NGPixel** [comment]
Fixed by 46630e1638a2fa749bef185f1bee123aad8e09bb

**Comment by pirvana** [comment]
It doesn't work for me, even if I add what I request above, I'm working from "docker-compose"

HELP!!!!

**Comment by NGPixel** [comment]
@pirvana This is not released yet.

**Comment by pirvana** [comment]
but indicate above that it is already corrected by "Fixed by 46630e1", just for that reason I ask for help since this solution does not work for me, thanks

**Comment by NGPixel** [comment]
Fixed doesn't mean its deployed and available right away in your installation. Bug fixes are compiled until a new release is made available.

**Comment by pirvana** [comment]
I understand, I apologize for the misunderstanding, thank you, I will be waiting for the publication of it. excellent work

**Comment by XerqJon** [comment]
@pirvana use HTML instead while waiting for a new release.

**Comment by pirvana** [comment]
Thank you @XerqJon  so I will do it while I wait for a new version Thank you
