### ISSUE TITLE
Blockquote containing a list does not use custom style

### ISSUE THREAD

**Issue by juliendms** [requarks/wiki#1241]
**Describe the bug**
When using blockquote on multiples lines that contains a list and a custom style, eg:
```md
> Hello Word
> - Item 1
> - Item 2
{.is-success}
```
The blockquote does not use the specified style (here: success).

**To Reproduce**
1. Create a new page
2. Insert
```md
> Hello Word
> - Item 1
> - Item 2
{.is-success}
```
3. Check the preview

**Expected behavior**
The style of the blockquote should be applied just like when using this code:
```md
> Hello
> Word
{.is-success}
```

**Host Info (please complete the following information):**
 - Wiki.js version: 2.0.1

**Comment by Veers01** [comment]
If that could help, I check the html and it seem that the style is apply to the <ol> element instead of the <blockquote>.

**Comment by binerf** [comment]
Interested by a fix for this bug. Thanks !

**Comment by benjamin-kirkbride** [comment]
Are you accepting contributions for this issue? I would love to have it fixed for my use case.

**Comment by NGPixel** [comment]
@benjamin-kirkbride Yes, contributions are welcome.

**Comment by NGPixel** [comment]
See https://github.com/requarks/wiki/issues/1505#issuecomment-1574758897
