### ISSUE TITLE
Can't start wiki.service - permission problem

### ISSUE THREAD

**Issue by Hannibalus** [Requarks/wiki#1245]
**Question**
Hi,
I have a problem with starting wiki.service (systemd). Error is: 

`Loading configuration from /var/www/wiki/config.yml... OK
Nov 21 06:29:06 falbala node[872]: fs.js:114
Nov 21 06:29:06 falbala node[872]:     throw err;
Nov 21 06:29:06 falbala node[872]:     ^

Nov 21 06:29:06 falbala node[872]: **Error: EACCES: permission denied, open '/var/www/wiki/package.json'**

Nov 21 06:29:06 falbala node[872]:     at Object.openSync (fs.js:443:3)
Nov 21 06:29:06 falbala node[872]:     at Object.readFileSync (fs.js:343:35)
Nov 21 06:29:06 falbala node[872]:     at Object.Module._extensions..json (internal/modules/cjs/loader.js:795:20)
Nov 21 06:29:06 falbala node[872]:     at Module.load (internal/modules/cjs/loader.js:653:32)
Nov 21 06:29:06 falbala node[872]:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
Nov 21 06:29:06 falbala node[872]:     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
Nov 21 06:29:06 falbala node[872]:     at Module.require (internal/modules/cjs/loader.js:692:17)
Nov 21 06:29:06 falbala node[872]:     at require (internal/modules/cjs/helpers.js:25:18)
Nov 21 06:29:06 falbala node[872]:     at Object.init (/var/www/wiki/server/core/config.js:59:25)
Nov 21 06:29:06 falbala node[872]:     at Object.<anonymous> (/var/www/wiki/server/index.js:19:16)
Nov 21 06:29:06 falbala systemd[1]: wiki.service: Main process exited, code=exited, status=1/FAILURE
Nov 21 06:29:06 falbala systemd[1]: wiki.service: Failed with result 'exit-code'.
Nov 21 06:29:06 falbala systemd[1]: wiki.service: Service RestartSec=100ms expired, scheduling restart.
Nov 21 06:29:06 falbala systemd[1]: wiki.service: Scheduled restart job, restart counter is at 5.
Nov 21 06:29:06 falbala systemd[1]: Stopped Wiki.js.
Nov 21 06:29:06 falbala systemd[1]: wiki.service: Start request repeated too quickly.
Nov 21 06:29:06 falbala systemd[1]: wiki.service: Failed with result 'exit-code'.
Nov 21 06:29:06 falbala systemd[1]: Failed to start Wiki.js.`

What right to set in the folder wiki?
Current state is:
root:root

Setup page in port 3000 is fine.

**Host Info:**
OS: [Debian 10 Buster 64bit]
Wiki.js version: [latest today 2.0.1]
Database engine: [mariadb-server 1:10.3.18-0+deb10u1]

Thank you very much.

**Comment by Phreeak** [comment]
Hi,

change "nobody" to "root"

`[Unit]
Description=Wiki.js
After=network.target

[Service]
Type=simple
ExecStart=/usr/bin/node server
Restart=always
# Consider creating a dedicated user for Wiki.js here:
User=**ROOT**
Environment=NODE_ENV=production
WorkingDirectory=/var/wiki

[Install]
WantedBy=multi-user.target`

**Comment by Hannibalus** [comment]
Perfect. Thank you very much.
