### ISSUE TITLE
Incorrect display of all text field - missing usage of proxy server to download translations

### ISSUE THREAD

**Issue by climblinne** [Requarks/wiki#1248]
**Describe the bug**
The wiki.js server is running on a Windows 10 computer and has no direct access to the internet. The company proxy is set in the "internet options". 
When starting the wiki, I get overall the missing text filed (instead the text id is displayed).

I tried to download the sideload packages and set `offline` in the config file to `true`. Unluckily no better result. 

What is the offical way to set an proxy server?

**Host Info (please complete the following information):**
 - OS: Win10
 - Wiki.js version: 2.0.1
 - Database engine: postgres 9.7

**Comment by NGPixel** [comment]
Try to clear your browser cache. You most likely have the translation cache from before the sideload.

Using sideloading (with offline: true) is the correct way to go in your situation.

**Comment by climblinne** [comment]
I tested it again on another machine and had the same result. So basic installation, add sideload files and set "offline" to "true". This machine had internet access and was working as I set "offline" to "false".

So I would say, it's not an proxy issue.

**Comment by parlinda** [comment]
I am running into this same issue after downloading the locale files, putting them into the /data/sideload dir, and setting offline to false. I have also attempted clearing browser cache, using another browser, and even rebuilding the sqlite DB after the sideload.

Any advice would be greatly appreciated.

**Comment by githubdave2020** [comment]
This is very similar to the issue i am seeing #1386

**Comment by d-sko** [comment]
I think I have the same issue with a new docker installation. I deployed Wiki.js with portainer following the installation guide at https://docs.requarks.io/install/portainer and it looks like the whole localization is missing:

![image](https://user-images.githubusercontent.com/5774313/72974950-3df24180-3dd0-11ea-99c0-f4a9aedfa9b6.png)

The browser console shows this error:
```
[GraphQL error]: Message: Invalid locale or namespace, Location: [object Object], Path: localization,translations
(anonymous) @ app.b98d10f6bb893bd895c4.js:2
c.ApolloLink.from.l.BatchHttpLink.includeExtensions @ app.b98d10f6bb893bd895c4.js:2
next @ app.b98d10f6bb893bd895c4.js:2
b @ app.b98d10f6bb893bd895c4.js:64
y @ app.b98d10f6bb893bd895c4.js:64
value @ app.b98d10f6bb893bd895c4.js:64
(anonymous) @ app.b98d10f6bb893bd895c4.js:2
(anonymous) @ app.b98d10f6bb893bd895c4.js:2
next @ app.b98d10f6bb893bd895c4.js:2
b @ app.b98d10f6bb893bd895c4.js:64
y @ app.b98d10f6bb893bd895c4.js:64
value @ app.b98d10f6bb893bd895c4.js:64
(anonymous) @ app.b98d10f6bb893bd895c4.js:2
Promise.then (async)
(anonymous) @ app.b98d10f6bb893bd895c4.js:2
e @ app.b98d10f6bb893bd895c4.js:64
value @ app.b98d10f6bb893bd895c4.js:64
e.consumeQueue @ app.b98d10f6bb893bd895c4.js:2
(anonymous) @ app.b98d10f6bb893bd895c4.js:2
setTimeout (async)
e.scheduleQueueConsumption @ app.b98d10f6bb893bd895c4.js:2
(anonymous) @ app.b98d10f6bb893bd895c4.js:2
e @ app.b98d10f6bb893bd895c4.js:64
value @ app.b98d10f6bb893bd895c4.js:64
(anonymous) @ app.b98d10f6bb893bd895c4.js:2
e @ app.b98d10f6bb893bd895c4.js:64
value @ app.b98d10f6bb893bd895c4.js:64
(anonymous) @ app.b98d10f6bb893bd895c4.js:2
e @ app.b98d10f6bb893bd895c4.js:64
value @ app.b98d10f6bb893bd895c4.js:64
e.getObservableFromLink @ app.b98d10f6bb893bd895c4.js:2
(anonymous) @ app.b98d10f6bb893bd895c4.js:2
e.fetchRequest @ app.b98d10f6bb893bd895c4.js:2
(anonymous) @ app.b98d10f6bb893bd895c4.js:2
(anonymous) @ app.b98d10f6bb893bd895c4.js:35
(anonymous) @ app.b98d10f6bb893bd895c4.js:35
(anonymous) @ app.b98d10f6bb893bd895c4.js:35
d @ app.b98d10f6bb893bd895c4.js:35
e.fetchQuery @ app.b98d10f6bb893bd895c4.js:2
e.observeQuery @ app.b98d10f6bb893bd895c4.js:2
i.setUpQuery @ app.b98d10f6bb893bd895c4.js:2
i.onSubscribe @ app.b98d10f6bb893bd895c4.js:2
(anonymous) @ app.b98d10f6bb893bd895c4.js:2
e @ app.b98d10f6bb893bd895c4.js:64
value @ app.b98d10f6bb893bd895c4.js:64
(anonymous) @ app.b98d10f6bb893bd895c4.js:2
i.result @ app.b98d10f6bb893bd895c4.js:2
(anonymous) @ app.b98d10f6bb893bd895c4.js:2
e.query @ app.b98d10f6bb893bd895c4.js:2
e.query @ app.b98d10f6bb893bd895c4.js:2
ajax @ app.b98d10f6bb893bd895c4.js:2
value @ app.b98d10f6bb893bd895c4.js:7
value @ app.b98d10f6bb893bd895c4.js:7
a @ app.b98d10f6bb893bd895c4.js:7
(anonymous) @ app.b98d10f6bb893bd895c4.js:7
value @ app.b98d10f6bb893bd895c4.js:7
a @ app.b98d10f6bb893bd895c4.js:7
value @ app.b98d10f6bb893bd895c4.js:7
value @ app.b98d10f6bb893bd895c4.js:7
value @ app.b98d10f6bb893bd895c4.js:7
(anonymous) @ app.b98d10f6bb893bd895c4.js:7
value @ app.b98d10f6bb893bd895c4.js:7
value @ app.b98d10f6bb893bd895c4.js:7
value @ app.b98d10f6bb893bd895c4.js:7
r @ app.b98d10f6bb893bd895c4.js:7
value @ app.b98d10f6bb893bd895c4.js:7
c @ app.b98d10f6bb893bd895c4.js:7
setTimeout (async)
value @ app.b98d10f6bb893bd895c4.js:7
init @ app.b98d10f6bb893bd895c4.js:2
(anonymous) @ app.b98d10f6bb893bd895c4.js:2
Show 35 more frames
2app.b98d10f6bb893bd895c4.js:2 Error: GraphQL error: Invalid locale or namespace
    at new n (app.b98d10f6bb893bd895c4.js:2)
    at app.b98d10f6bb893bd895c4.js:2
    at app.b98d10f6bb893bd895c4.js:2
    at Set.forEach (<anonymous>)
    at app.b98d10f6bb893bd895c4.js:2
    at Map.forEach (<anonymous>)
    at e.broadcastQueries (app.b98d10f6bb893bd895c4.js:2)
    at app.b98d10f6bb893bd895c4.js:2
    at Object.next (app.b98d10f6bb893bd895c4.js:64)
    at b (app.b98d10f6bb893bd895c4.js:64)
```

**Comment by Emusp** [comment]
We got the same translation issue as d-sko. When deploying the latest stable docker image.

**Comment by gerroon** [comment]
So what is the solution to this?

**Comment by d-sko** [comment]
> So what is the solution to this?

have not found one, moved to Bookstack

**Comment by lotusnoir** [comment]
hello, I found the solution, 
refer to this page: [https://docs.requarks.io/install/sideload](https://docs.requarks.io/install/sideload).

the Sideloading locales are missing and are not downloaded, just check if the date/sideload folder contains all the .json requiered and it should work :)

**Comment by climblinne** [comment]
So I tried the sideload documentation and I think it's not obvious, that when you load e.g. just 2 languages, that you need to reduce the locales.json file. I think a note about this in the documentation would be very nice. 
I downloaded now all files and it worked. 

Perhaps also a note/link to enable the following parameter in the configuration file:
```
offline: true
```

**Comment by NGPixel** [comment]
@climblinne That's not the issue. It worked because you restarted the server (which is what actually fixed the problem).

Locale data is not provided to the client properly the first time, until the server is restarted. This will be fixed in 2.5 update.

So just restart your wiki once if you have the issue when installing the first time.

**Comment by bestwnh** [comment]
> @climblinne That's not the issue. It worked because you restarted the server (which is what actually fixed the problem).
> 
> Locale data is not provided to the client properly the first time, until the server is restarted. This will be fixed in 2.5 update.
> 
> So just restart your wiki once if you have the issue when installing the first time.

@NGPixel I just meet this issue in the 2.5.170, restart make it work. I think this should be mention in the installation guide.

**Comment by xiepu1212** [comment]
system.currentVersion 2.5.268
I create sideload folder ，place the json files inside the folder ，set  configuration file "offline: true"，but "Error: GraphQL error: Invalid locale or namespace"still reported。
![image](https://user-images.githubusercontent.com/34331649/220868734-13415bd9-c972-41af-9373-2956d8c82520.png)
![image](https://user-images.githubusercontent.com/34331649/220868879-b0c0acc2-1103-4f2f-8e2c-7ee54cb147ac.png)
![image](https://user-images.githubusercontent.com/34331649/220869076-89bb80eb-fd18-4eb4-98a2-411688e388bb.png)
![image](https://user-images.githubusercontent.com/34331649/220869193-b8d8d627-4ff5-4cd9-af30-b14b82799efa.png)

**Comment by InsOpDe** [comment]
For me it helped to remove an active namespace and readd it again:
![image](https://github.com/requarks/wiki/assets/10099328/a9f206bf-2401-437d-81db-fed3aa5de1c1)
