### ISSUE TITLE
Create side navigation based on paths and permissions

### ISSUE THREAD

**Issue by goodmanpersonguy** [Requarks/wiki#1250]
**Question**
I have multiple groups and want to set individual access permissions for the pages. The group **Cars** should only see and access the the pages starting with **/cars** for example.

_I would like to autogenerate a sidebar based on the permissions and paths but it seems this is a feature for the future? Currently the side menu is disabled as you can see in the menu tab.

So what I do for now is to create a new page let's say `/houses/red`. I update the page rules for my cars group to

_path starts with `/cars`_

So this group can only access car pages. They can't access pages with a path starting with `/houses`. To make this new page visible in the sidebar I have to administrate the navigation. I add a link with the target `/houses/red`. Now every user is able to see this link but when they try to access it they get a access denied page.

How can I make the link visible for users with matching permissions only? Users with no permissions should not see this link... Maybe this navigation administration needs some permission settings? Maybe I can auto generate the menu in a future release?

**Host Info:**
OS: Docker Container (Linux)
Wiki.js version: 2.0.1
Database engine: PostgreSQL 9.6.15

**Comment by NGPixel** [comment]
This is coming in a future release. You'll be able to create different sidebar menus per section and you'll only see links that you have access to.

**Comment by goodmanpersonguy** [comment]
Thanks. Is there a roadmap for Features like this? I think I have to track this, right?

https://wiki.js.org/feedback/p/sidebar-navigation-permissions
