### ISSUE TITLE
Is it possible to automatically add navigation links for pages imported through Git?

### ISSUE THREAD

**Issue by subaduba** [Requarks/wiki#1252]
**Question**

Hello all - I am running Wiki.js 2.0.1, and I have a Git storage target created to pull from a remote repo. The synchronization is working fine, and I see my new Pages added. The one issue that I have is that I have to manually create the new Navigation link for each Page. What I would like to do is make automatic Navigation links for every imported page. Is that possible? Thank you!

**Host Info (please complete the following information):**
OS: Docker
Wiki.js version: 2.0.1
Database engine: Postgres (via Docker Compose)

**Comment by NGPixel** [comment]
The sidebar navigation is meant for general global links, not to have a list of every single pages in your wiki.

The ability to browse your wiki using the structure navigation is coming in a future release.

**Comment by subaduba** [comment]
Thanks for the quick reply, @NGPixel. 

So right now, there is no way for a guest to browse the available Pages without first creating them as a global link? Apologies if I am missing something.

**Comment by NGPixel** [comment]
You're supposed to use links within your pages to navigate between pages. So your homepage would contain links to page A, B and C, which would themselves contain links to other pages, etc. Kind of how Wikipedia works. You don't have a huge list of all articles in a sidebar. You either search or click on links within pages to navigate.

**Comment by subaduba** [comment]
Totally understand, got it. Thanks again for the quick reply. We are creating a Git docs repo, and I am syncing that with Wiki.js. I will just make sure we have a Navigation page within the repo itself that is updated when we add new pages, and this should totally work. I was just trying to figure out how users would discover newly created pages.
