### ISSUE TITLE
Create wiki page locally and move it to a production server

### ISSUE THREAD

**Issue by shinz4u** [Requarks/wiki#1254]
**Question**
Is it possible to create a wiki page on my local machine and then move it onto a production server later? Is there any guides for doing such a procedure? 

**Host Info (please complete the following information):**
OS: Mac OS 10
Wiki.js version: 2.0.1
Database engine: postgres 12

**Comment by NGPixel** [comment]
I would suggest to instead create a new page on your production server but on a restricted path that only you can access (using Group permissions).

If you absolutely need to create it on your local machine first, then your only option is to manually copy the contents into a new page on your production server afterwards.
