### ISSUE TITLE
Several codesegments not showing

### ISSUE THREAD

**Issue by Phreeak** [Requarks/wiki#1257]
**Describe the bug**
Several codesegments not showing 

**To Reproduce**
1. Go to Markdown Editor
2. Insert a codeblock
3. Insert code (in my case apache config)
4. Several codesegments not showing

**Expected behavior**
Code should be showing complete

**Screenshots**
![2019-11-24 15_54_36-Edit Untitled Page](https://user-images.githubusercontent.com/21967882/69496589-f5073500-0ed3-11ea-81d4-9301df8d6b02.png)

**Host Info (please complete the following information):**
 - OS: Ubuntu 18.04
 - Wiki.js version: 2.0.12]
 - Database engine: mysql 5.7

**Comment by aharbis** [comment]
I am also seeing this. Seems to break on XML / HTML tag syntax. I even tried escaping the characters, i.e. `\<foo\>` but that still did not work.

**Comment by NGPixel** [comment]
Fixed by 18b2f60b84c1201cfa7c7ba77db3155d4a3ec408
