### ISSUE TITLE
Tree view navigation in wiki.js v2.0.12

### ISSUE THREAD

**Issue by ilshatufa** [Requarks/wiki#1262]
**Question**
In the wiki.js v1, the sidebar had tree navigation. Tell me how i can make tree view navigation  in the wiki.js v2.0.12?

**Host Info (please complete the following information):**
OS:  Ubuntu 18.04, Docker
Wiki.js version: 2.0.12
Database engine:  postgres 12.1

**Comment by NGPixel** [comment]
This is coming in 2.1

**Comment by badrshs** [comment]
is this  feature is available now ? I have same issue .. Trying to create something similar to wikijs demo but I can't

**Comment by NGPixel** [comment]
No, it's been pushed back to 2.3 release.
