### ISSUE TITLE
Upgrade from RC new install - Database Initialization Error: Invalid Version: 2.0.0.js

### ISSUE THREAD

**Issue by santiagolator** [requarks/wiki#1263]
Hi! I've just upgraded to v2.0.12 from 2.0.0-rc.17 and when  tried to start the node it gives me this error:

```
# node server
Loading configuration from Z:\wiki-sm\config.yml... OK
2019-11-25T13:50:34.317Z [MASTER] info: 
=======================================
2019-11-25T13:50:34.320Z [MASTER] info: = Wiki.js 2.0.12 ======================
2019-11-25T13:50:34.321Z [MASTER] info: =======================================
2019-11-25T13:50:34.322Z [MASTER] info: Initializing...
2019-11-25T13:50:35.363Z [MASTER] info: Connecting to database...
2019-11-25T13:50:35.458Z [MASTER] info: Database Connection Successful [ OK ]
2019-11-25T13:50:35.484Z [MASTER] error: Database Initialization Error: Invalid Version: 2.0.0.js
```

I didn't change a thing in mi config, and followed the steps to upgrade from official docs.

**Host Info:**
OS: Windows server 2016
Wiki.js version: 2.0.12
Database engine: postgres 11.4
Node.js version: 12.13.1

**Comment by santiagolator** [comment]
I've created a new DB and started a new instance and started OK! Still don't know what caused the error

**Comment by quangld** [comment]
I got the same error.
Apparently, I was caused by me :)
I wrote a bash script which download latest release than extracting the file to the src folder!
some left over files in "db\migrations\" causes the semver.compare function in migrator-source.js crash
```
    return migrationFiles.sort(semver.compare).map(m => ({
      file: m,
      directory: baseMigrationPath
    }))
```
Solution for my case: I rewrote my bash script
1. Make a copy of config.yml
2. Delete the whole src folder
3. Extract the latest release

I will report the problem to semver package maintaner

**Comment by quangld** [comment]
It's actually an expected Invalid Version exception when trying to sort the version array without removing .js extension.
```
const semver = require('semver')
let noExtension = ['2.0.0-rc.2','2.0.0']
noExtension .sort(semver.compare) // this is good

let withExtension = ['2.0.0-rc.2.js','2.0.0.js']
withExtension .sort(semver.compare) // this will throw Invalid Version error
```

Fix Suggestion: remove .js extension before using semver.compare for sorting in /server/db/migrator-source.js

```
  async getMigrations() {
    const migrationFiles = await fs.readdir(baseMigrationPath)
    return migrationFiles.map(m => m.slice(0, -3)).sort(semver.compare).map(m => ({
      file: m + '.js',
      directory: baseMigrationPath
    }))
  },

```
