### ISSUE TITLE
Account verifications

### ISSUE THREAD

**Issue by Ivo-Donchev** [Requarks/wiki#1265]
**Question**
Can you somehow disable the user verification process when logged as a superuser ? Or alternatively: Does it have ability for the superuser to manually verify a user account (when adding it) ? 

The use case is: I am logged as a superuser. I want to create accounts for existing users in my web application but I don't want to make them verify their emails. Is that possible ? :slightly_smiling_face:  

**Host Info:**
OS: Ubuntu 18.04, Docker
Wiki.js version: 2.0.1
Database engine: postgres 9.7

**Comment by NGPixel** [comment]
There's no email validation for users created from the administration area.

**Comment by Ivo-Donchev** [comment]
@NGPixel I'm not sure if this is the same as email verification.

I got this error when trying to login:
```
'[{"data":{"authentication":{"login":{"responseResult":{"succeeded":false,"errorCode":1014,"slug":"AuthAccountNotVerified","message":"You must verify your account before your can login.","__typename":"ResponseStatus"},"jwt":null,"mustChangePwd":null,"mustProvideTFA":null,"continuationToken":null,"__typename":"AuthenticationLoginResponse"},"__typename":"AuthenticationMutation"}}}]\n'
```
:disappointed:

**Comment by Ivo-Donchev** [comment]
@NGPixel All good, my fault :sweat_smile:

**Comment by pirvana** [comment]
@Ivo-Donchev como soluciono el error de inicio que solicita "email"?
