### ISSUE TITLE
Permissions to exclude any others

### ISSUE THREAD

**Issue by rickywu** [Requarks/wiki#1267]
I have one group that turned off all permissions 
![image](https://user-images.githubusercontent.com/442398/69590913-01060a80-102c-11ea-9aef-51538172da7b.png)

Also I turned on page rules like this:
![image](https://user-images.githubusercontent.com/442398/69590801-a2409100-102b-11ea-9a82-db65001ee0cf.png)

But users cannot login if configed like this, I have to turn on read pages in perssmins tab, 
![image](https://user-images.githubusercontent.com/442398/69590781-8ccb6700-102b-11ea-9abb-a72f9b1a337b.png)

that is not what I want,
because I donnot want users in this group read any other paths except /cloud and /home

**Comment by NGPixel** [comment]
That's not how permissions work. Please read the [docs](https://docs.requarks.io/groups).

The `read:pages` permission must be enabled. Then you add Page Rules to limit the scope. If you want only `/cloud` and `/home` to be accessible, you need to add 2 Page Rules with a `Path matches exactly...` match type.

**Comment by rickywu** [comment]
OK, thanks.
I have to remove all permissions for Guest and add read permissions of /home to viewer group
Then the group can login and view /home, also can view such as /cloud of it's workspace, that is what I want.
