### ISSUE TITLE
Discard message: 'loose' should be 'lose'

### ISSUE THREAD

**Issue by markfox1** [Requarks/wiki#127]
### Actual behavior

I'm not usually a member of the grammar police, but... When discarding a page edit, the warning dialogue uses _loose_ where _lose_ was intended. An easy mistake to make, and just as easy to fix.

**Comment by NGPixel** [comment]
Fixed for Beta 12 (5a8c5237af82243655bfa5801f9dd7103e0deb82)

Thanks!
