### ISSUE TITLE
Admin pages available to view without login

### ISSUE THREAD

**Issue by sbonaime** [Requarks/wiki#1273]
V 2.0.12
**Describe the bug**
All admin pages like
https://docs.requarks.io/a/users
or
https://docs.requarks.io/a/mail
are available to view without login even if Guest user is not able to do anything. Fortunately Guest is not able to do anything. Maybe for security reasons,  guest for those pages should fallback to login screen

**Comment by NGPixel** [comment]
You can only view the UI, not the actual resources. There's no security risk here.
