### ISSUE TITLE
Bug in the Local Email Self-Registration

### ISSUE THREAD

**Issue by BrunoCampana** [Requarks/wiki#1274]
First of all, thanks and congratulations for this wonderful project. In my opinion, by far the best organizational wiki that the one has to deploy.

So, the bug:
When you try to make local self-register an email that IS in the "whitelist" it says "You are not authorized to register. Your domain is not whitelisted.".

**To Reproduce**
1. Go to 'Administration -> Authentication -> local -> allow self-registration'
2. Fill the 'whitelist' with the emails you want.
3. Log out.
4. Select "create an account"
5. Insert the email that IS in the whitelist.
6. See the message "You are not authorized to register. Your domain is not whitelisted." 

The correct behavior should be confirmed that the email IS in the whitelist and go to next phase of self-registration.

**Host Info (please complete the following information):**
 - OS: Ubuntu Server 16.04 LTS
 - Wiki.js version: 2.0.12
 - Database engine: PostgreSQL 9.5.19

Can you guys can help me?

**Comment by NGPixel** [comment]
The whitelist is for **domains** (example.com), not **emails** (user@example.com).

**Comment by BrunoCampana** [comment]
Thanks and sorry for the "stupid question".
