### ISSUE TITLE
Need help to configure email settings 

### ISSUE THREAD

**Issue by BrunoCampana** [Requarks/wiki#1281]
I'm trying to enable the Wiki.js to send emails, using this kind of settings:
MAIL_USERNAME = myemail@gmail.com
MAIL_PASSWORD = mypassword
SMTP_URL = smtp.gmail.com
MAIL_PORT = 587

I already set my Gmail configuration, and by the way, I already have a Rails web app using Devise which can send emails perfectly with this same configuration.

The problem is that using the 587 Port, **EMAIL SETTINGS FORM did not even ask the password from the sender email.** How can Wiki.js send emails from port 587 without knowing the password? 

Can you guys help me?

**Comment by NGPixel** [comment]
![image](https://user-images.githubusercontent.com/15522395/70281480-1d6f1900-1789-11ea-9d19-862130ce4615.png)
