### ISSUE TITLE
Lists containing paragraphs are styled incorrectly

### ISSUE THREAD

**Issue by nilium** [Requarks/wiki#1282]
**Describe the bug**
If a list on a page contains a paragraph, either because it has multiple lines or each list item is separated by a blank line, list bullets are rendered above the content of each list item, and list item content is not indented. This applies to both ordered and unordered lists (visible if you change the sample below to an ordered list).

**To Reproduce**
1. Go to any page
2. Click on the edit button
3. Add the following text:

    ```markdown
    ## Separated by Newlines
    
      - Simple list
    
      - Each item is a paragraph
    
      - Because each item is separated by a line
    
    ## Multi-line list
    
      - This list contains items with multiple lines, requiring paragraphs in the list item.
    
        That is, the list item is more complicated than just `<li>Test</li>`.
      - Once an item in a list is a paragraph, all items are paragraphs.
      - This also contains a paragraph.
    
        Just to illustrate this mid-list.
      - Another paragraph.
    
    ## Simple List
    
      - This list works.
      - It isn't separated by newlines.
      - It doesn't have multiple lines in any item.
    ```

4. Note inconsistent formatting in the preview pane. A screenshot is included below showing this in Firefox, though the behavior is consistent in Google Chrome as well.

**Expected behavior**
Lists with paragraphs should be formatted like lists. For example, the example given above is formatted as such in this issue:

---

## Separated by Newlines

  - Simple list

  - Each item is a paragraph

  - Because each item is separated by a line

## Multi-line list

  - This list contains items with multiple lines, requiring paragraphs in the list item.

    That is, the list item is more complicated than just `<li>Test</li>`.
  - Once an item in a list is a paragraph, all items are paragraphs.
  - This also contains a paragraph.

    Just to illustrate this mid-list.
  - Another paragraph.

## Simple List

  - This list works.
  - It isn't separated by newlines.
  - It doesn't have multiple lines in any item.

---

**Screenshots**

![screenshot-20191202-090301](https://user-images.githubusercontent.com/44962/69979195-b0d2f080-14e2-11ea-859c-6410f462c965.png)

**Host Info:**
 - OS: Docker (using the docker-compose.yml provided in the documentation)
 - Wiki.js version: 2.0.12
 - Database engine: Postgres 9 (`postgres:9-alpine`, per docker-compose.yml)

**Additional context**

N/A

**Comment by nilium** [comment]
Appears to format correctly if we remove the fake triangle bullet and replace it with a disclosure bullet (same-ish shape, but black) positioned outside the list item (with a left padding of 1rem):

```css
.v-content .contents ul {
    list-style: disclosure-closed outside;
    padding-left: 1rem;
}
```

![screenshot-20191202-110720](https://user-images.githubusercontent.com/44962/69987342-272c1e80-14f4-11ea-9841-54fd3ef7ce32.png)

**Comment by Veers01** [comment]
The same thing append in ordered list:

![ordered list](https://user-images.githubusercontent.com/10885532/71373618-d5703480-2585-11ea-96bd-2357908fdf14.PNG)

**Comment by nilium** [comment]
If this still happens in master, please open a new issue for it.

**Comment by Veers01** [comment]
I don't know for the master since I'm using the docker image. I'll check if I can install a test setup to check in master.
