### ISSUE TITLE
Ldap Debug Log Not Available 

### ISSUE THREAD

**Issue by mikkushukla** [Requarks/wiki#1284]
**Describe the bug**
Unable to debug ldap connection issue. 

**To Reproduce**
1. Go to '...' Administration - > Developer 
2. Click on '....' Enabled log for ldap

**Expected behavior**
LDAP CONNECTION LOG Should be printed on node server console 

**Screenshots**

**Host Info (please complete the following information):**
 - OS: Cent OS 7
 - Wiki.js version: Latest 
 - Database engine:  postgres 11

**Additional context**
There is no log file, where I can check logs. 
For check console logs I have to run
node server

**Comment by NGPixel** [comment]
There's no log file, you need to check the console output while performing an LDAP login.

**Comment by mikkushukla** [comment]
It was the issue with cache, I did ctrl+F5 and ldap option appeared like this
![image](https://user-images.githubusercontent.com/12640686/70324377-55dc2900-1855-11ea-9200-5cf807f6d704.png)
Which file , hence I am closing issue.
