### ISSUE TITLE
Redirecting to login if disable edit page at root path

### ISSUE THREAD

**Issue by borisaka** [Requarks/wiki#1287]
<img width="1368" alt="Снимок экрана 2019-12-04 в 17 53 16" src="https://user-images.githubusercontent.com/7931040/70152850-f9df9c00-16be-11ea-89fc-5bfc227b7cb0.png">
I wanted to create support team with limited access. It can:
View public documents
View, create and edit /private/support
and cant view /private 

But then I disabling editing root – it can't see main page and being redirected to login (if I going to exactly /private/support or child pages – everything is fine) 

**Host Info (please complete the following information):**
 - OS: Debian 9
 - Wiki.js 2.0.0 (displayed. Actualy it master branch)
 - Database engine: postgresql 11.6
- nodejs - 13.2.0

**Comment by AgarwalSaurav** [comment]
I think this is related to #998 
Giving any permission to a new group gives the permission to all entities, and denying permission to even a single attribute denies for everything. When we have both then it just denies everything to the group. Only happens with new groups and not the guest group.

**Comment by NGPixel** [comment]
Fixed by 7d23344c7af80909c43e42a383df4d916f7eedf6
