### ISSUE TITLE
github sync will failed if the path under another git repo parent

### ISSUE THREAD

**Issue by changsijay** [Requarks/wiki#1291]
**Describe the bug**
When we set github sync, the `./data/repo` by default if it is placed inside another git folder,
it will sync the parent git repo to github instead of `./data/repo`

**To Reproduce**
1. git clone https://github.com/Requarks/wiki on `/var/www/wiki`
2. npm install
3. npm run build
4. configure nginx, database, etc
5. setup github sync and use default `./data/repo`, which is `/var/www/wiki/data/repo`

**Expected behavior**
the content of markdown will produced and sync to github.
However, it sync the parent git repo, i.e wiki.js source code to github.

**Host Info (please complete the following information):**
 - OS: ubuntu 18.04
 - Wiki.js version: master
 - Database engine: mysql 8

**Additional context**
to fix it just specify the path which not inside another git folder.
maybe can detect it and show some error/hint message on UI.

**Comment by NGPixel** [comment]
Except you're not supposed to clone this repo (other than dev purposes). This is a standard behavior of git and will not be covered as this will never happen if you install it using the supported installation methods.
