### ISSUE TITLE
Error while importing content from Wiki.js 1.x.x or editing pages with long content

### ISSUE THREAD

**Issue by SConstantinou** [requarks/wiki#1294]
**Describe the bug**
Wiki.js 2.0.12 with DB mysql
table pageHistory column content is of type text
this causes problems when importing from Wiki.js 1.x or when using the "Import Everything" action under storage. For most entries in the table we get warnings like: "Data too long for column 'content' at row 1". The behaviour is the same when editing a pages and trying to add long content.

**To Reproduce**
Import pages with long content (over 64KB) especially entered all at once.

**Expected behavior**
Page should be updated normally without error. LONGTEXT should be used in mysql instead of text.

**Screenshots**

**Host Info (please complete the following information):**
 - OS: Ubuntu 18.04
 - Wiki.js version: 2.0.12]
 - Database engine: MariaDB 10.4.10]

**Additional context**
nsert into `pageHistory` (`action`, `authorId`, `content`, `contentType`, `createdAt`, `description`, `editorKey`, `hash`, `isPrivate`, `isPublished`, `localeCode`, `pageId`, `path`, `publishEndDate`, `publishStartDate`, `title`) values ('updated', 1,

.......

Data too long for column 'content' at row 1"

**Comment by SConstantinou** [comment]
After you get the error, then you are not able to do anything with the page as you cannot even delete content or the whole page.

**Comment by NGPixel** [comment]
The pages table is actually using LONGTEXT. however the history table is still set with normal TEXT type, which is a bug.
