### ISSUE TITLE
Headboard

### ISSUE THREAD

**Issue by pirvana** [Requarks/wiki#1295]
**Question**

Good, maybe it's not the place but, I have this query,
I would like to know how to insert this type of header to the different pages

![image](https://user-images.githubusercontent.com/23135703/70459264-95438900-1a92-11ea-9c8b-92102cabc061.png)

**Host Info (please complete the following information):**
OS: [e.g. CENTOS 7, Docker]
Wiki.js version: [e.g. 2.0.12]
Database engine: [e.g. postgres 9.7]

**Comment by pirvana** [comment]
![image](https://user-images.githubusercontent.com/23135703/70459381-d471da00-1a92-11ea-80f4-df625bebe23c.png)

**Comment by XerqJon** [comment]
Hi @pirvana , 

You can do this by adding the `.align-abstopright` attribute to an image on your page.

With markdown, that would look like ```![](https://static.requarks.io/logo/elasticsearch.svg){.align-abstopright}```

With HTML, that would be ```<img src="https://static.requarks.io/logo/elasticsearch.svg" alt="" class="align-abstopright">```

**Tip:** you can view the source of any of the Wiki.JS doc pages by adding /s/ to the URL after the domain. Example for the elasticsearch page: 
https://docs.requarks.io/en/search/elasticsearch becomes https://docs.requarks.io/s/en/search/elasticsearch

**Comment by pirvana** [comment]
wow, thank you very much for the prompt help, the page is great, and the answers are very good, thanks
