### ISSUE TITLE
The page source displays unicode HTML Entities for non-ASCII characters

### ISSUE THREAD

**Issue by snoleo** [Requarks/wiki#1296]
**Describe the bug**
When the content is non-ASCII characters Language like Chinese or Korean, the page source will display unicode HTML Entities. (Page contents display in browser is OK, only the page source when view in browser using Ctrl+u)
For example, the Chinese characters: 你好 (mean hello in English) will display in the page source as : "`&#x4F60;&#x597D;`"

I think in page source should display the original  characters: 你好. If the page source display the unicode HTML Entities, the search engine will not correctly recognize the page contents.

converter reference: https://mothereff.in/html-entities

**Screenshots**
![2019-12-10_184254](https://user-images.githubusercontent.com/1975813/70524125-7c64d180-1b7f-11ea-8cca-35373aaa5df3.jpg)

**Host Info :**
 - OS: Debian  8.9.0 _Jessie_
 - Wiki.js version: 2.0.12
 - Database engine: (PostgreSQL) 11.5

**Comment by NGPixel** [comment]
The content used for the search engine is not the same as the rendered one. You should be able to search non-latin characters just fine.

**Comment by snoleo** [comment]
I worry that the page source displays unicode HTML Entities, the search engine like google.com or bing.com will index the content as raw unicode HTML Entities, instead of the original content.

**Comment by snoleo** [comment]
This issue is fixed now.
