### ISSUE TITLE
In-line editing of a page's locale or path is not working

### ISSUE THREAD

**Issue by AuspeXeu** [Requarks/wiki#1300]
**Describe the bug**
These buttons do nothing.
![image](https://user-images.githubusercontent.com/2115696/70657273-7cb9a700-1c29-11ea-842d-9dfeb36f723d.png)

**To Reproduce**
1. Go to Administration
2. Click on Pages
3. Select a page to view its details

**Host Info (please complete the following information):**
 - OS: Docker
 - Wiki.js version: 2.0.12
 - Database engine: postgres 9.7

**Comment by NGPixel** [comment]
These are not working yet. Coming in a future release.
