### ISSUE TITLE
Current Version Does Not Change After Update

### ISSUE THREAD

**Issue by Threadgill** [Requarks/wiki#1301]
**Question**
Going from version 2.0.1 to 2.0.12 and after the update is completed refreshing current version does not show the 2.0.12 version.

Using this as the source - https://github.com/Requarks/wiki/releases/download/2.0.12/wiki-js.tar.gz

**Host Info (please complete the following information):**
OS: Centos
Wiki.js version: 2.0.1
Database engine: 10.3.14-MariaDB

**Comment by NGPixel** [comment]
Did you replace all the files? Then restarted the app / service?

**Comment by Threadgill** [comment]
Yep, I followed the Linux instructions here, even did it twice to confirm.

https://docs.requarks.io/install/upgrade

Stopped the wiki service, deleted folder, downloaded, copied files, copied back the config, restarted wiki.js

**Comment by NGPixel** [comment]
Can you verify that package.json contains version 2.0.12? If so, maybe you have a browser caching issue? Try purging your browser cache or try another browser.

**Comment by fanlix** [comment]
by the way, for docker version:
```
2.0-arm: Pulling from requarks/wiki
Digest: sha256:6731e9001b0b5b12e985221847eb1e5394c4dccce6aa098e2f3533b3e83d2518
Status: Image is up to date for requarks/wiki:2.0-arm
docker.io/requarks/wiki:2.0-arm
```
the admin - system info  shows:
**2.0.0-beta**

![wikijs version](https://user-images.githubusercontent.com/987637/70688323-79d3ba80-1cec-11ea-9264-6a862f825332.PNG)
