### ISSUE TITLE
Missing translation

### ISSUE THREAD

**Issue by AuspeXeu** [Requarks/wiki#1307]
**Describe the bug**
![image](https://user-images.githubusercontent.com/2115696/70715100-91dd1700-1cb7-11ea-9dae-c84ff277e11c.png)

**To Reproduce**
Try the 'Keyboard Key' without selecting text in the markdown editor.

**Host Info (please complete the following information):**
 - Wiki.js version: 2.0.12

**Comment by NGPixel** [comment]
Fixed.
