### ISSUE TITLE
Cannot delete users

### ISSUE THREAD

**Issue by AuspeXeu** [Requarks/wiki#1309]
![image](https://user-images.githubusercontent.com/2115696/70729191-b72a4f00-1cd0-11ea-98bc-328f26395f85.png)
The button seems to be disabled for some reason. Is this also not yet implemented?

**Comment by NGPixel** [comment]
This is coming in 2.1

**Comment by techsavyravi** [comment]
When is 2.1 coming?

**Comment by NGPixel** [comment]
@techsavyravi https://docs.requarks.io/releases
