### ISSUE TITLE
PostgresSQL Error on Windows 10

### ISSUE THREAD

**Issue by pablotj** [Requarks/wiki#1310]
Not connect to postgresSQL on windows 10

![image](https://user-images.githubusercontent.com/22442253/70821368-34da8180-1ddb-11ea-9196-11ef667fe299.png)

db:
  type: postgres
  host: localhost
  port: 5432
  user: postgres
  pass: **********
  db: wiki
  ssl: false

**Comment by NGPixel** [comment]
Have you looked at the [PostgreSQL error code list](https://www.postgresql.org/docs/9.0/errcodes-appendix.html) first? 28P01 refers to INVALID PASSWORD.
