### ISSUE TITLE
How to show all pages on navigation like 1.0x? 

### ISSUE THREAD

**Issue by LosaMatova** [Requarks/wiki#1312]
**Question**
I'd like to show all pages in navigation so that I don't have to manually create half a dozen navigation pages that all have to be updated. 

**Host Info (please complete the following information):**
OS:  Ubuntu 18.04, Docker
Wiki.js version:  2.0.12
Database engine: postgres 10.10

**Comment by NGPixel** [comment]
This is coming in 2.1
