### ISSUE TITLE
Possible to change admin password (eg. via cli)?

### ISSUE THREAD

**Issue by akramer-zibra** [Requarks/wiki#1313]
**Question**
...admin-login seems broken after my last instance update with docker "2.0-arm" image OR I messed up my login credentials. Is it possible to change "admin" user password for example with via commandline? 

**Host Info (please complete the following information):**
OS: Docker on Raspberry Pi 3 (ARM)
Wiki.js version: 2.0-arm (docker image)
Database engine: postgres 9.7

**Comment by NGPixel** [comment]
Not at the moment. You'll need to change the value directly in the DB for your user using a bcrypt generator.

**Comment by akramer-zibra** [comment]
Thanks! Changed it with `psql`. 
First connected to the database 
```
psql wiki wikijs
```
Then updated my user's password value with the new bcrypt-hashed one
```
UPDATE users
SET password = '$2b$10$LxE...'
WHERE users.email = 'ach...'; 
```
