### ISSUE TITLE
backup wikijs settings/info

### ISSUE THREAD

**Issue by vladisalv** [Requarks/wiki#1319]
**Question**
I decided to upgrade from beta version and install it on fresh system. And I dropped the disk (yes, I know I could just pull stable container. yes, I'm foolish ;) I expected, that wikijs stores its system info in my git repo, but it doesn't.

I recreated my groups, navigation panel and etc. So, everything is well, but I want to be protected in the future.

How can I backup wikijs service info about groups, users, settings and etc? Don't want to lose it twice! :)

**Host Info (please complete the following information):**
OS: Ubuntu 18.04, Docker
Wiki.js version: 2.0.12

**Comment by NGPixel** [comment]
These settings are stored in the database. You need to setup a backup strategy to regularly perform dumps of your database. There're tons of tutorials on Google on how to do that, depending on your database platform.

**Comment by winkelement** [comment]
Personally i mount the db data folder in docker to a folder in the local filesystem + i use a simple cronjob to perform a dump of the database (PostgreSQL) out of the docker-container to the local filesystem.

My cronjob looks like this and also removes old (+30 days) backups:
```
docker exec -i [database-container-name] pg_dump -U [postgres-user] [postgres-db] > /path/to/local/backup/$(date +%F_%R).dump && find /path/to/local/backup/ -type f -mtime +30 -name '*.dump' -execdir rm -- '{}' \;
```
