### ISSUE TITLE
Authorization using external API with JWT

### ISSUE THREAD

**Issue by Grawl** [Requarks/wiki#1321]
**Question**

I want to use Wiki.js as knowledge base for my app users.

I want to allow them use wiki with their logins and passwords. Or even let them be logged in if user is already logged into my app.

My app is written on Laravel 6.5 and using JWT to authenticate users.

Where can I start integrating Wiki.js authentication with my app?

**Host Info (please complete the following information):**

OS: Alpine, Docker

Wiki.js version: 2.0.12

Database engine: Postgres 11

**Comment by NGPixel** [comment]
While Wiki.js is using JWT, its used to manage sessions, not as an authentication strategy. You could use the tokens generated by Wiki.js to authenticate to your application, but I would avoid doing the reverse as you're gonna end up having issues in future updates.

The other solution is to wait for the API feature to be released, from which you could generate a Wiki.js token upon login in your application and store it alongside.
