### ISSUE TITLE
Incomplete import

### ISSUE THREAD

**Issue by mistervi** [Requarks/wiki#1322]
**Describe the bug**
I tried to migrate from version 1 to version 2, but the import process fails to create some pages.
I tried with both methods, git and local folder, same issue.

**To Reproduce**
1. Go to Utilities > Import from Wiki.js 1.x
2. Click on Start import
3. Check pages count from dashboard
4. See that a lot are missing

**Expected behavior**
Import all pages.

**Screenshots**
NA

**Host Info:**
 - OS: Debian GNU/Linux 9.7 (stretch)
 - Wiki.js version: 2.0.12
 - Database engine: postgres 9.7

**Additional context**
The error I get for each missing pages: 
`warn: (STORAGE/DISK) Failed to process page xxx/xxx/xxx`
`warn: insert into "pages" ("authorId", "content", "contentType", "createdAt", "creatorId", "description", "editorKey", "hash", "isPrivate", "isPublished", "localeCode", "path", "publishEndDate", "publishStartDate", "title", "toc", "updatedAt") values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17) returning "id" - insert or update on table "pages" violates foreign key constraint "pages_localecode_foreign"`

Thanks for your help.

**Comment by nicolasg-playster** [comment]
You have either files or folders at the root that are 2 characters long. You can't have a folder or file at the root level named e.g. /xy/something.md or /yz.md

Rename these files to respect the naming restrictions as detailed [here](https://docs.requarks.io/guide/pages)

**Comment by mistervi** [comment]
That's the case. Thanks for the quick feedback.
