### ISSUE TITLE
npm install fails in app installed from macOS install guide

### ISSUE THREAD

**Issue by Grawl** [Requarks/wiki#1325]
**Describe the bug**

`'elasticsearch6@6.8.3' is not in the npm registry.`

```
~/Sites/wiki is 📦 v2.0.12 via ⬢ v12.13.1 
➜ npm install          
npm WARN deprecated postcss-cssnext@3.1.0: 'postcss-cssnext' has been deprecated in favor of 'postcss-preset-env'. Read more at https://moox.io/blog/deprecating-cssnext/
npm WARN deprecated browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/elasticsearch6 - Not found
npm ERR! 404 
npm ERR! 404  'elasticsearch6@6.8.3' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'wiki'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/daniilpronin/.npm/_logs/2019-12-19T00_14_42_748Z-debug.log

```

**To Reproduce**

1. Go to https://docs.requarks.io/install/macos
2. Follow installation guide
3. Run `npm install` in app folder

**Expected behavior**

`npm` exits with code 0

**Host Info:**

 - OS: macOS Catalina 10.15.2 (19C57)
 - Wiki.js version: 2.0.12
 - Database engine: Postgres 12

**Additional context**

There is no `yarn.lock` in app folder I got from [URL](https://github.com/Requarks/wiki/releases/download/2.0.12/wiki-js.tar.gz) from macOS guide, but it exists in `master` and `2.0` branches. I think the problem is `"elasticsearch6": "npm:@elastic/elasticsearch@6"` not supported by NPM CLI. Yarn doing install without errors.

https://github.com/elastic/elasticsearch-js/issues/788

**Comment by NGPixel** [comment]
And why are you running `npm install`? All necessary node_modules are already included in the zip...

**Comment by Grawl** [comment]
Because there is a `package.json`

**Comment by NGPixel** [comment]
Closing this issue as nowhere in the install guide it says to run npm install.

**Comment by Grawl** [comment]
👌
