### ISSUE TITLE
problem with page title in Hebrew locale

### ISSUE THREAD

**Issue by talalvas** [Requarks/wiki#1326]
### Actual behavior
when you display a page that was created for Hebrew locale, the page title is hidden behind the Table of contents element. (marked with arrow in attached pictures).
![1](https://user-images.githubusercontent.com/9365114/71176477-a2226280-2272-11ea-89a1-5a618fa00bc2.png)

### Expected behavior
The title should be displayed after the Table of content element. like here:
![2](https://user-images.githubusercontent.com/9365114/71176479-a2226280-2272-11ea-9b0e-a1a1432fca32.png)

### Steps to reproduce the behavior
Just add a page with Hebrew locale and see the page heading.

**Comment by NGPixel** [comment]
This is a bug in the underlying UI framework:

https://github.com/vuetifyjs/vuetify/issues/6317

However it should be possible to overwrite the incorrect offset classes in the meantime, as it doesn't seem like a priority for them.

**Comment by NGPixel** [comment]
Temporary fix by 14c842ff9d26979efe08faf82368b1e3fbff479f
