### ISSUE TITLE
Problem with multi-leveled numbered lists in Hebrew locale

### ISSUE THREAD

**Issue by talalvas** [Requarks/wiki#1327]
**Describe the bug**
When displaying a page with multi leveled numbered list in Hebrew locale, the second level numbers are in the same alignment as the first.
![3](https://user-images.githubusercontent.com/9365114/71180345-a5215100-227a-11ea-8818-1c62f7aa03f9.png)

**To Reproduce**
display a page using Hebrew locale that has multi-leveled numbered list.
![1](https://user-images.githubusercontent.com/9365114/71180507-01847080-227b-11ea-9ad4-6dd90cc30767.png)

**Expected behavior**
The second leveled numbered list should be advanced with one tab in relation to the first one.
as you can see when the page is displayed with English locale.
![2](https://user-images.githubusercontent.com/9365114/71180209-5f648880-227a-11ea-9592-2d995596475c.png)

**Screenshots**

**Host Info (please complete the following information):**
 - OS: Windows Server 2019
 - Wiki.js version: 2.0.12
 - Database engine: postgres 12

**Thanks**

**Comment by NGPixel** [comment]
Fixed by 14c842ff9d26979efe08faf82368b1e3fbff479f
