### ISSUE TITLE
Underscores are removed if used in page names

### ISSUE THREAD

**Issue by mirelsol** [Requarks/wiki#133]
### Actual behavior
If you create a new page say 'my_test_page', a page called 'mytestpage' will be created instead

### Expected behavior
A page named 'my_test_page' should be created

### Steps to reproduce the behavior
* Create a new page with this name 'my_test_page': the page created will be 'mytestpage'
* Other case: if you have an existing page named 'my_old_page', it won't be found because the application will look for 'myoldpage' instead.

**Comment by NGPixel** [comment]
Underscores are invalid in page paths. The kebab-case must be used: `my-test-page`
