### ISSUE TITLE
"BETA" box still appears

### ISSUE THREAD

**Issue by pirvana** [Requarks/wiki#1332]
Good, I see that in the configuration section the "BETA" box still appears, this could be modified since the product is working stably. It's just a suggestion, thank you very much for the help always

![image](https://user-images.githubusercontent.com/23135703/71416658-2f353500-2640-11ea-8b3c-ae5334e47956.png)

https://wiki.js.org/feedback

**Comment by NGPixel** [comment]
Just validated that the text was changed in all locales.
