### ISSUE TITLE
Use Wiki.JS as Frontend

### ISSUE THREAD

**Issue by fabiodcorreia** [Requarks/wiki#1333]
**Question**
I'm using wiki.js to build an intranet website, it's kind of the center of everything from knowledgebase to documentation repository and so on.

I have several custom internal APIs (Rest and GraphQL) I was thinking if it was possible to use also the wiki.js as frontend for these backend APIs. The APIs are mostly to display data or trigger actions so the UI is very simple and can be done for example with just jQuery.

It's possible to create a wiki page and import jQuery for example and then call the APIs and show the response on that page? I tried just to import jQuery with script tag and the code appears on the page source code but doesn't get executed.

Even a simple <script>console.log("Hello")</script> is not executed but appears on the source. I also disable the option htmlSecurity on the database but I got the same result.

**Host Info**
OS: Raspbian Stretch
Wiki.js version: 2.0.12
Database engine: sqlite 3

**Comment by NGPixel** [comment]
Per page javascript is not possible at the moment. This will come in a later update (probably 2.2)

For now you need to use the code injection feature found in the Admin > Themes section.

**Comment by fabiodcorreia** [comment]
But using the code injection it will execute the code on every page right? I want to have different code per page.

I will wait for 2.2 then, would be great if we could use the wiki as frontend for other applications and keep everything centralized.

**Comment by jcklpe** [comment]
@fabiodcorreia  have you checked out NextCloud as an intranet solution? It might also fit your needs, and they have a very robust plugin api.
