### ISSUE TITLE
How to show all pages in navigation menu

### ISSUE THREAD

**Issue by mmdrn** [Requarks/wiki#1334]
**Question**
We are trying to use Wiki.js to document our projects information in our company.
But we have a question/problem and that is "How can we show all virtual folders and pages that user have permission to see?"
In other word "How user can see all virtual folders that he has access to?"

For now, for this problem, our users are forced to click on "New Page" button to see all virtual folders and then they have to open that target page in edit mode. Obviously it is not a perfect solution, since I don't have to give this permission ( create and edit pages ) to all users.

Is there any other way around it ?

**Host Info (please complete the following information):**
OS: Linux - Debian
Wiki.js version: 2.0.1
Database engine: PostgreSQL 11.4

**Comment by aniketpanjwani** [comment]
I don't quite understand what you're asking, but I think you might be asking for how you can see a sitemap. If that's your question, that's going to be coming in 2.1 ([see changelog](https://docs.requarks.io/releases)).

**Comment by NGPixel** [comment]
This is coming in [2.1](https://docs.requarks.io/releases)

**Comment by mmdrn** [comment]
> 
> 
> This is coming in [2.1](https://docs.requarks.io/releases)

Please note that I don't want a sitemap.
I want a way for my users, to they can see that virtual folders and pages that they have access to.

**Comment by NGPixel** [comment]
Like I said, this is coming in 2.1.
