### ISSUE TITLE
What is missing in config.yml to complete setup

### ISSUE THREAD

**Issue by M-LE-2020** [Requarks/wiki#1335]
as shown below i couldn't complete setup after node server command

![Image of powershell](https://i.ibb.co/0hXHTz4/00.png)

and here is my config.yml settings 

![Image of config.yml](https://i.ibb.co/yYNkGWs/2.png)

**Host Info**
Windows
Wiki.js version: 2.0.12
Database engine: postgres 10.11-3

**Comment by NGPixel** [comment]
You need to put quotes around your password value if it starts with a number.

**Comment by M-LE-2020** [comment]
it didn't work, also i changed the pass to normal text with no numbers and got the same result!!!

**Comment by NGPixel** [comment]
Have you actually tested that you can connect to your postgresql instance (e.g. using the psql client)?

**Comment by ssimontis** [comment]
Also please try using port 5432 for Postgres; that is the default port for a PostgreSQL install. If you did not explicitly change the port in your configuration, the port you listed is incorrect. If you need help finding the config file with port information, I'll be happy to help.

**Comment by M-LE-2020** [comment]
> Also please try using port 5432 for Postgres; that is the default port for a PostgreSQL install. If you did not explicitly change the port in your configuration, the port you listed is incorrect. If you need help finding the config file with port information, I'll be happy to help.

Hi Simon,

Many thanks for your reply.

well as  you see i left the default port for postgresql as it is

![port](https://i.ibb.co/KjpBSRL/1.png)


meanwhile after finishing install ion and open the pgadmin i found the port changed

![port](https://i.ibb.co/pPL4n1g/2.png)


could you please advise!!

**Comment by M-LE-2020** [comment]
> Have you actually tested that you can connect to your postgresql instance (e.g. using the psql client)?

yes and it seems connected well, also i have created the DB for wiki to connect it while installation and config the yml file

![port](https://i.ibb.co/k83n6S9/3.png)

**Comment by M-LE-2020** [comment]
This is the final error after 10 attempts to connect

![4](https://user-images.githubusercontent.com/59260385/71560332-4a090e80-2a71-11ea-8a30-52e3597f48ea.png)

**Comment by M-LE-2020** [comment]
This is the final result i got after changing port of postgre to be 5432 but it didn't continue 

![4](https://user-images.githubusercontent.com/59260385/71560502-58f0c080-2a73-11ea-835b-c8b1825e923f.png)

**Comment by M-LE-2020** [comment]
Thanks a lot guys, it works well now.

solution:

change the port at yml config from 3000 to 80
and postgre port to be 5432

**Comment by ssimontis** [comment]
For future reference, the reason that you saw the port in the 60,000s in your browser is because the pgAdmin interface uses that port to run the web server. pgAdmin is totally separate from your Postgres installation -- you will definitely use it to connect to your installation, but you can use it to connect to many servers.

You will see in the errors that it failed to start at port 3000 because you need elevated privileges -- you need to either run the command from an elevated command prompt, or choose a larger value for port. I'm honestly kind of shocked 3000 requires elevated permissions on Windows, typically it is only ports < 1024. My preference is to use ports above 50,000 for any development instances as those ports are almost never used by applications.

If you don't want to manually start the node server process, you can create a scheduled task to do so or look into utilities like [PM2](https://pm2.keymetrics.io/) to set it up as a service.

Glad you got it working and let me know if you have additional questions I can help out with!

**Comment by M-LE-2020** [comment]
> Glad you got it working and let me know if you have additional questions I can help out with!

your prompt response is highly appreciated really, well i have another two questions

i'm seeing this coming soon note on almost most of features at Wiki, are we about to receive a new update for the wiki soon ?or is there something wrong about my installation ?

![5](https://user-images.githubusercontent.com/59260385/71564327-adae2e80-2aa7-11ea-8110-8dfbd3ea8613.png)

The other thing what about those Skipped things, excuse me i'm still beginner for this and wanna be sure from its accurate before i initialize it to my company

![6](https://user-images.githubusercontent.com/59260385/71564344-f5cd5100-2aa7-11ea-92bf-e597d8f89184.png)


 The last question, are there any advises you can tell me before install the wiki to windows server instead of the local host?

Many thanks in Advance for your generous help

**Comment by ssimontis** [comment]
I think a major  Proposed release is coming up soon. I am not actually on the core team, I just try to answer questions here when I can (although I have asked about contributing more :) ).

Those lines would not be skipped in a situation where an update made a new editor, or a new search interface, or some other pluggable piece of functionality available for use.

In addition to using pm2, I would also highly recommend using a reverse proxy, which is basically a web server sitting in front of your web server. You can look into how to do so with IIS, but I am not a big fan of IIS and personally prefer NGinx. Caddy is another web server which is very easy to configure, but they aren't fully open-source if that is a concern to you. And of course there's always Apache, but I am not very familiar with Apache; I literally always use Nginx.

A reverse proxy will let you assign a TLS certificate so you can have HTTPS, it can load balance, improve logging, optimize requests and caching, and protects the identity of your original web server (you can have the reverse proxy set up on another server). 

Here are [Microsoft's standards for hardening Windows Server](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-security-baselines), I would consider following these for any Production deployment. Other than that, make sure that you have backups set up and that they work! Good luck with the deployment!

**Comment by NGPixel** [comment]
@M-LE-2020 `[ SKIPPED ]` are normal and can be ignored.

You can check the upcoming release here:
https://docs.requarks.io/releases
