### ISSUE TITLE
Style tag and class tag cannot be used in HTML tag.

### ISSUE THREAD

**Issue by touhoku-japan** [Requarks/wiki#1340]
**Describe the bug**
Style tag and class tag cannot be used in HTML tag.

**To Reproduce**
1. Code Raw HTML Editor editing.
2. Write style tag and class tag and Click on Save
3. There is no style tag.

Please display without deleting style tag.
thanks.

**Comment by ssimontis** [comment]
I believe this bug may be in the CodeMirror library which we use for the raw HTML Editor as opposed to any logic enforced by this project. The 5.50 release of CodeMirror, which is more recent than the dependency in this project (5.49.2) makes no mention of a bug fix for using style and class attributes together.

**Comment by ssimontis** [comment]
@NGPixel can we please close since it is an issue with an upstream library and not this project?

**Comment by touhoku-japan** [comment]
I thought that if the wiki editor could overwrite the style sheet, the display of the page would be freely modified, so it was prohibited.
I think this is fine. Thank you for your polite reply.
