### ISSUE TITLE
Cannot login as Administrator using username

### ISSUE THREAD

**Issue by eburgueno** [Requarks/wiki#1342]
**Describe the bug**
After a new install using the Docker Compose example from the docs, I cannot login as `Administrator` using that as the username. I can login using the email address that I set for the Administrator user though.

**To Reproduce**
1. Open an Incognito browser window and browse to localhost/ or your wiki domain
2. Click on the login icon
3. Enter `Administrator` in the username field and the admin password
4. See error: `Invalid email / username or password.`

**Expected behavior**
Using the username to authenticate should work.

**Host Info (please complete the following information):**
 - OS: Fedora 31, using the latest WikiJS from Docker Hub (`docker.io/requarks/wiki@sha256:9d30bf68173f45d86eed5464da80f7223673872441c30671293ddac8b4a54a92`)
 - Wiki.js version: 2.0.12
 - Database engine: PostgreSQL 11.6

**Additional context**
Here're the contents of the `users` table:

```
 id |        email        |     name      | providerId |                           password                           | tfaIsActive | tfaSecret | jobTitle | location | pictureUrl |     timezone     | isSystem | isActive | isVerified | mus
tChangePwd |        createdAt         |        updatedAt         | providerKey | localeCode | defaultEditor 
----+---------------------+---------------+------------+--------------------------------------------------------------+-------------+-----------+----------+----------+------------+------------------+----------+----------+------------+----
-----------+--------------------------+--------------------------+-------------+------------+---------------
  2 | guest@example.com   | Guest         |            |                                                              | f           |           |          |          |            | America/New_York | t        | t        | t          | f  
           | 2019-12-29T21:55:26.306Z | 2019-12-29T21:55:26.306Z | local       | en         | markdown
  1 | admin@10.88.0.1 | Administrator |            | $2a$12$4g<etc>/zva | f           |           |          |          |            | America/New_York | f        | t        | t          | f  
           | 2019-12-29T21:55:25.777Z | 2019-12-29T22:13:13.951Z | local       | en         | markdown
(2 rows)
```

**Comment by NGPixel** [comment]
Administrator is the display name, not a username. You're expected to login using the email, not a "username". The only login strategy that is using usernames is LDAP.
