### ISSUE TITLE
vanilla wikijs installation to homelab server keeps going down. Any help?

### ISSUE THREAD

**Issue by jcklpe** [Requarks/wiki#1346]
**Question**
I have installed wikijs manually to a homelab server and it keeps going down and IDK why? I followed the instructions here: https://docs.requarks.io/install/linux

**Host Info (please complete the following information):**
OS: Ubuntu 18.04
Wiki.js version: newest. like 2.1.1 or something. 
Database engine: postgres

Other info:

I'm running a nextcloud server I installed using an ansible script. That script installed nextcloud but also set up my original nginx server, which is using a reverse proxy to serve the wiki via subdomain. So I have cloud.jackalope.tech and wiki.jackalope.tech and the nginx config serves one or the other based upon what URL the person uses. 

Part of the nginx config is opening up a redirect to port 3000. Here's the config:

```
server {
    listen 443 ssl;
 server_name wiki.jackalope.tech;
 root /var/www/wiki/;

 

#  ssl on;


 index ./server/index.js;
    ssl_certificate /etc/letsencrypt/live/wiki.jackalope.tech/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/wiki.jackalope.tech/privkey.pem; # managed by Certbot


	location / {
	        proxy_set_header   X-Forwarded-For $remote_addr;
	        proxy_set_header   Host $http_host;
	        proxy_pass         http://127.0.0.1:3000;
	    }
}


server {
    if ($host = wiki.jackalope.tech) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


 listen 80;
 server_name wiki.jackalope.tech;
 add_header Strict-Transport-Security max-age=2592000;



}

```

Also when I initially begin the node server I'm doing so as a root user because the folders for www are set up to only be accessed by the www-data user which was set up by the ansible playbook. But I have set the wiki.service to use the www-data user for it's implementation. The problem does not seem to be the wiki starting on start up though, but rather crashing at some point after I start the node server manually via root user. Perhaps the root user causes problems for node server?

**Comment by ssimontis** [comment]
Hello,

Can you provide any logs that were produced by the application? That is probably the best place to start.

**Comment by jcklpe** [comment]
@ssimontis sure thing. Sorry I did not include that on the first post. 

Where are the logs set to go by default? This is my first time running a node app on my homelab (before now it's all been php based nginx stuff) and I'm not familar with JS backend practices. The nginx configs have the ability to specify log location but when I previously set a location for those in the wiki.conf file for nginx it doesn't output anything useful.

**Comment by jcklpe** [comment]
I have a feeling it might simply be the node process timing out, and as I am not really a node guy I haven't set any kind of "reset" to the process, maybe? 

Reading online I see that wikijs 1.0 logs were written to console when started by node. If that's the case then I don't have any logs, or need to set them up.

**Comment by NGPixel** [comment]
How are you running the node process? Using a service?

**Comment by jcklpe** [comment]
@NGPixel  yes, as per the instructions.

**Comment by NGPixel** [comment]
Then you can check the logs using `journalctl -e -u YOUR-SERVICE-NAME.service`

**Comment by jcklpe** [comment]
@NGPixel Excellent, thank you, this is super useful for me to know! 

Here's the results of me running that:

```
┌─      ~                                                                                                                              
└─➤ journalctl -e -u wiki.service             
Jan 03 16:42:37 lovelace node[1631]: Loading configuration from /var/www/wiki/config.yml... OK
Jan 03 16:42:37 lovelace node[1631]: fs.js:646
Jan 03 16:42:37 lovelace node[1631]:   return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
Jan 03 16:42:37 lovelace node[1631]:                  ^
Jan 03 16:42:37 lovelace node[1631]: Error: EACCES: permission denied, open '/var/www/wiki/package.json'
Jan 03 16:42:37 lovelace node[1631]:     at Object.fs.openSync (fs.js:646:18)
Jan 03 16:42:37 lovelace node[1631]:     at Object.fs.readFileSync (fs.js:551:33)
Jan 03 16:42:37 lovelace node[1631]:     at Object.Module._extensions..json (module.js:669:20)
Jan 03 16:42:37 lovelace node[1631]:     at Module.load (module.js:565:32)
Jan 03 16:42:37 lovelace node[1631]:     at tryModuleLoad (module.js:505:12)
Jan 03 16:42:37 lovelace node[1631]:     at Function.Module._load (module.js:497:3)
Jan 03 16:42:37 lovelace node[1631]:     at Module.require (module.js:596:17)
Jan 03 16:42:37 lovelace node[1631]:     at require (internal/module.js:11:18)
Jan 03 16:42:37 lovelace node[1631]:     at Object.init (/var/www/wiki/server/core/config.js:59:25)
Jan 03 16:42:37 lovelace node[1631]:     at Object.<anonymous> (/var/www/wiki/server/index.js:19:16)
Jan 03 16:42:37 lovelace systemd[1]: wiki.service: Main process exited, code=exited, status=1/FAILURE
Jan 03 16:42:37 lovelace systemd[1]: wiki.service: Failed with result 'exit-code'.
Jan 03 16:42:37 lovelace systemd[1]: wiki.service: Service hold-off time over, scheduling restart.
Jan 03 16:42:37 lovelace systemd[1]: wiki.service: Scheduled restart job, restart counter is at 5.
Jan 03 16:42:37 lovelace systemd[1]: Stopped Wiki.js.
Jan 03 16:42:37 lovelace systemd[1]: wiki.service: Start request repeated too quickly.
Jan 03 16:42:37 lovelace systemd[1]: wiki.service: Failed with result 'exit-code'.
Jan 03 16:42:37 lovelace systemd[1]: Failed to start Wiki.js.
```

It looks like it's a permission issue. Let me check that real quick. 
----
Just checked and yeah the owner for the /var/www/wiki is `www-data` as it is supposed to be. 

And here's the wiki.service config so you can see if I missed something:

```
[Unit]
Description=Wiki.js
After=network.target

[Service]
Type=simple
ExecStart=/usr/bin/node server
Restart=always
# Consider creating a dedicated user for Wiki.js here:
User=www-data
Environment=NODE_ENV=production
WorkingDirectory=/var/www/wiki

[Install]
WantedBy=multi-user.target
```

Also double checked this "

```
whereis node
node: /usr/bin/node /usr/local/bin/node /usr/share/man/man1/node.1.gz
```

Which seems to align with the config perfectly. Plus if this part was misconfigured we wouldn't get the eacacess errors. 

Does running the node server via www-data somehow break it? Maybe I need to install node to the www-data user? I know that when I originally tested by using `sudo -i` to start the server I had to apt install node because the root user didn't have node installed.

**Comment by NGPixel** [comment]
make sure the contents of /var/www/wiki are also owned by www-data, not just the parent directory. node is installed correctly as the loading script outputs properly. It's definitely a permission issue.

**Comment by jcklpe** [comment]
@NGPixel  oh dadgumit, sorry I thought I had double checked that but what I'd checked was chmod not chown. It's fixed! Thank you!
