### ISSUE TITLE
Hostname/IP does not match certificate's altnames: IP: 192.168.16.190 is not in the cert's list

### ISSUE THREAD

**Issue by RmondJone** [Requarks/wiki#1347]
**Question**
Send a test email when configuring the mailbox service： Hostname/IP does not match certificate's altnames: IP: 192.168.16.190 is not in the cert's list:

OS: [Linux Docker]
Wiki.js version: [2.0.12]
Database engine: [PostgreSQL 12.1]

**Comment by NGPixel** [comment]
Seems like an incorrect configuration on your side. If you're using SSL, the mail server hostname you use must match the certificate.
