### ISSUE TITLE
dead link in CONTRIBUTING.md doc

### ISSUE THREAD

**Issue by aharbis** [Requarks/wiki#1348]
**Describe the bug**

The following link is broken:

https://wikijs.canny.io/features

which I found from here:

 https://github.com/Requarks/wiki/blob/master/.github/CONTRIBUTING.md

**To Reproduce**

1. Go to https://github.com/Requarks/wiki/blob/master/.github/CONTRIBUTING.md
2. Click on https://wikijs.canny.io/features

**Expected behavior**

Link should properly redirect to feature request board.

**Screenshots**

Result of navigating to https://wikijs.canny.io/features

![image](https://user-images.githubusercontent.com/20443310/71684875-b5e6c200-2d64-11ea-82e4-d05601797a82.png)

**Comment by NGPixel** [comment]
Thanks, fixed.
