### ISSUE TITLE
notification when creating page

### ISSUE THREAD

**Issue by pirvana** [Requarks/wiki#1349]
**Question**
Good, I would like to ask you a question, is there any configuration to notify me by mail every time a page is edited or created? thank you very much for the help of always I hope you don't bother

**Host Info (please complete the following information):**
OS:  Centos 7, Docker
Wiki.js version: 2.0.12
Database engine: postgres 9.7

**Comment by ethanmdavidson** [comment]
No, I don't believe this feature currently exists, but you can make your interest known by voting/commenting on [this feature request](https://wiki.js.org/feedback/p/notifications-for-page-updates).

**Comment by XerqJon** [comment]
I think you can workaround this by using git storage and using a git repo with a built in file watcher or a third party.

**Comment by NGPixel** [comment]
As @ethanmdavidson suggested, refer to the feature request.
