### ISSUE TITLE
Blockquote stylings not working

### ISSUE THREAD

**Issue by Borf** [Requarks/wiki#135]
### Actual behavior
Blockquote styles are not working, no color is added to the background.
![image](https://user-images.githubusercontent.com/2827599/27202916-c9a64c58-5223-11e7-932d-fb5da25dec64.png)

### Expected behavior
Expected is for the different stylings to produce different color backgrounds

### Steps to reproduce the behavior
go to https://docs.requarks.io/wiki/user-guide/blockquotes  , the 'available stylings' all show the same
Reproduced in vivaldi and chrome

**Comment by NGPixel** [comment]
Fixed for Beta 13 (3218355b307551f4df4d010bef3ac6d22b10a0ee)
