### ISSUE TITLE
Page Navigation Help Needed

### ISSUE THREAD

**Issue by tectacles** [Requarks/wiki#1350]
**Question**
Navigating from `onedirectory/specificfolder` to `differentdirectory/anotherfolder` causes redirection to `onedirectory/differentdirectory/anotherfolder`.

Example: if I am viewing the page `wiki.company.org/accounting/directory` and I want to navigate to `wiki.company.org/infotech/selfhelp`, the URL will redirect to `wiki.company.org/accounting/infotech/selfhelp` when using the side navigation bar

I apologize if this was covered in the documentations/other issue posts. I tried searching for this issue for wiki.js but could not find much info out there.

Any help is greatly appreciated. Thank you!

**Host Info:**
OS: Ubuntu 18.04, Docker
Wiki.js version: 2.0.12
Database engine: PostgreSQL 11.6

**Comment by XerqJon** [comment]
In your navigation do you have a leading `/` in front of your nav item
target? I could be wrong but I think if not you can expect this result.

**Comment by NGPixel** [comment]
As @XerqJon mentionned, you need to prefix your links with `/`, otherwise links are relative to the current page. An option is coming in 2.1 to make all relative links root absolute (the behavior you expected).
