### ISSUE TITLE
Arm64 Docker container still shows beta version

### ISSUE THREAD

**Issue by kbfifi** [Requarks/wiki#1356]
**Describe the bug**
After installing WikiJs according to documentation using docker-compose everything works. (https://docs.requarks.io/install/docker). I used tag: requarks/wiki:2.0-arm because I use arm64 architecture
When I look at the installed version it shows: 2.0.0-beta

**To Reproduce**
1. Go to system info for version information

**Expected behavior**
Version 2.0 (a recent version)

**Host Info (please complete the following information):**
 - OS: Ubuntu 18.04, Docker-Compose, using: tag: requarks/wiki:2.0-arm
 - Wiki.js version: 2.0
 - Database engine: postgres version from docker-compose

**Additional context**
First of all thank you for this great project! I was using version WikiJS 1.0 and since I got my new Rock64 SBC I wanted to try out docker and quickly noticed docker-compose. Great stuff! So I docker-composed WikiJS 2.0 with arm64 support. Everything works nicely! Then I stumbled upon the version isssue. It was also mentioned in #1301 but I think it's better to make it a separate issue.

**Comment by NGPixel** [comment]
This is a build issue when the arm image was pushed. Even though it says 2.0-beta, it is running the latest version of 2.0.12. The next release will correctly show as 2.1.x.
