### ISSUE TITLE
Admin User Unable to Create Homepage after Successful Setup

### ISSUE THREAD

**Issue by Marco77577** [Requarks/wiki#1361]
### Actual behavior
After successful setup, when prompted to create the Homepage, the admin user that was created a few seconds ago is "unauthorized" to create the Homepage.

### Expected behavior
The admin user should be authorized to create the Homepage.

### Steps to reproduce the behavior
The issue only happened to me if the email address entered as the admin email address ended with a digit (e.g., email3@gmail.com).
Everything works fine when using an email address that does not end in a digit, with the exact same setup.

I am starting the Wiki using Docker compose.

I hope somebody can reproduce/confirm this issue.

I am currently using an email address without a digit at the end. So no harm done.

**Comment by xhj967** [comment]
how to change email address，i can‘t login maybe i forgot the password，how can i reset in the setup page again， when i input http:\\localhost：3000,cannot redirect setup page again but  login page instead of.

**Comment by NGPixel** [comment]
@xhj967 Please don't hijack other people's ticket with an unrelated question.

You need to drop the database and start over, or manually change the password directly in the DB using bcrypt
