### ISSUE TITLE
I think the code block style is too dark

### ISSUE THREAD

**Issue by choicky** [Requarks/wiki#137]
### Actual behavior
The code block style is too dark, comparing to the H1/H2/H3 style.

### Expected behavior
Wish wiki.js is getting more and more elegant.

### Steps to reproduce the behavior

Referring to the screen shot below, the right content area is in a light style.  [Live Demo1](https://note.fei-xing.com/)
![wiki js-home](https://user-images.githubusercontent.com/10532949/27257357-18fa810a-5406-11e7-90bf-e17c76b668dc.png)

However, when the wiki page includes code blocks, the code blocks are too dark and mismatching the previous light style. [Live Demo2](https://note.fei-xing.com/https启用记录)
![wiki js-page](https://user-images.githubusercontent.com/10532949/27257361-1fd3543e-5406-11e7-8f5a-c026a608649f.png)

BTW, Personal I prefer the H2/H3 aligning left with the H1.

**Comment by NGPixel** [comment]
You'll be able to change the UI colors in an upcoming beta.

**Comment by NGPixel** [comment]
Added light theme for code blocks in Beta 13 (e5749fc6e2f32a64800448a17d856d40142f3a27)
