### ISSUE TITLE
[Bug] In markdown, tag don't render in code

### ISSUE THREAD

**Issue by Yivan** [Requarks/wiki#1370]
Hello,

Tag don't render in code (lastest stable v2).

Code:

```
# Start
<IfModule mod_expires.c>
    ExpiresActive off
</IfModule>
# End
```

Rendering:

![image](https://user-images.githubusercontent.com/9025839/72229191-fe944b80-35ac-11ea-8487-8ab9c34f71cb.png)

Even forcing the markdown to HTML (with "```html" don't render tags).

Thanks.

**Comment by Yivan** [comment]
I must add than same problem occurs with php code.
This snippet break all the page:

```php
<?php

include __DIR__ . "/../../../vendor/autoload.php"; // chemin à adapter selon l'emplacement du script

\Pimcore\Bootstrap::setProjectRoot();
\Pimcore\Bootstrap::bootstrap();

// On peut maintenant appeler les méthodes Pimcore

// On peut aussi paramétrer PHP
error_reporting(E_ALL); // on affiche même les erreurs de niveau notice
set_time_limit(0); // pas de limite de temps
ini_set('memory_limit', '2048M'); // on alloue davantage de mémoire
```

Removing the php tag make it work, but it is part of the code.
Ading a close php tag make only a black line (all code is stripped) and this code snippet must not have php ending tag (bad practive in php).

It is really problematique as the wiki is used for devoloppers...

I hope it could be soon fixed and released exceptionnaly.

Thanks.

**Comment by NGPixel** [comment]
This is only a bug in the preview panel of the editor. Save the page and the code blocks will display just fine.

Closing this ticket as the preview bug is already being tracked by another ticket.

**Comment by Yivan** [comment]
Thanks I go on the linked issue.
