### ISSUE TITLE
GitLab Authentication Callback URI not working

### ISSUE THREAD

**Issue by hogcryat** [Requarks/wiki#1373]
**Question**
I have my own GitLab instance, and is trying to set up login via Gitlab. So I enabled GitLab Authentication in the admin settings and logged out, then clicked on Login with GitLab. After logging in from GitLab's login screen, it redirects me back to the local login screen. If I try clicking Login with GitLab again, it just keeps redirecting me back.

**My exact steps in my attempt to set up**
1. In the Admin Panel of GitLab, go to Applications, then create a new application with read_user and openid scopes enabled. The Redirect URI is copied from the "Configuration Reference" section in Wiki js Authentication settings.
2. Copy the Client ID and Client Secret from GitLab and paste them in the GitLab tab in the Authentication settings. Base URL is the URL of my GitLab instance including https://
3. Enable Self Registration
4. Enable GitLab Authentication and Apply
5. Logout from Admin account, close all my Chrome windows, then open a new Incognito window. Go to my wikijs server, then click the GitLab button under "or login using..."

**Host Info:**
OS: Ubuntu 18.04
Wiki.js version: 2.0.12
Database engine: postgres 10.10
GitLab version: 12.6.2

**Comment by NGPixel** [comment]
Did you set a group for self-registration? Does that group have read access to the homepage?

**Comment by hogcryat** [comment]
I just tried to do so, so I created a temporary test group with the following permissions

![image](https://user-images.githubusercontent.com/46261767/72460148-3ac2e880-3807-11ea-8eb8-7208c254e7c0.png)

And then changed the self-registration settings as shown

![image](https://user-images.githubusercontent.com/46261767/72460177-4ca48b80-3807-11ea-989f-4ba1cd942dd9.png)

It does not appear to make a difference.

**Comment by hogcryat** [comment]
My guess is it is not related to the user group settings, since the GitLab users does not appear in "Users"

**Comment by skapin** [comment]
I setup mien yesturday, without any trouble.

- Did you enable the gilab authentication in wiki.js ?

thsi is my settings (obfuscated)

https://snipboard.io/N8d1yt.jpg

**Comment by hogcryat** [comment]
> I setup mien yesturday, without any trouble.
> 
> * Did you enable the gilab authentication in wiki.js ?
> 
> thsi is my settings (obfuscated)
> 
> https://snipboard.io/N8d1yt.jpg

Yes I did.

May I know in your GitLab instance, in the wikijs application settings, did you set the callback URI to {Base URL}/login/gitlab/callback, and which scopes did you check?

**Comment by hogcryat** [comment]
Hmm, I deleted everything and started over and it worked. Thanks for your attention.
