### ISSUE TITLE
Bug With stars

### ISSUE THREAD

**Issue by sbonaime** [Requarks/wiki#1376]
With 2.0.12

If I write (without space)
1 * 2
I have 1*2 on the page. 

If I write  (without space) 
1 * 2 * 3
I have 123 on the page !

If I write  (without space)
1 * 2 * 3 * 4
I have 123*4 on the page !

If I don't have empty lines, I never see stars. See screenshots

![Capture d’écran 2020-01-14 à 14-01-20 17 31 20](https://user-images.githubusercontent.com/750709/72362661-d8c58e80-36f3-11ea-8bee-420638909f50.png)
![Capture d’écran 2020-01-14 à 14-01-20 17 31 05](https://user-images.githubusercontent.com/750709/72362662-d8c58e80-36f3-11ea-8678-92ca43ffe1a2.png)

**Comment by NGPixel** [comment]
You're using the markdown editor... so this is completely normal, no bug there. I suggest you read about the Markdown syntax and how to use it [here](https://docs.requarks.io/en/editors/markdown).

You need to either escape your asterisks, use inline code blocks or switch to another editor.
