### ISSUE TITLE
Adding just one forbidden page rule, dissalow viewing page, ACL broken.

### ISSUE THREAD

**Issue by Yivan** [Requarks/wiki#1377]
Hello,

It seems the ACL security is broken somewhere.
We try to make a specific folder where users can write page, and just read on the others folders of the wiki. Just put my head 2 hours in it (try even negative regex)... to finally found system is broken.

Here a simple showcase, so you can start from here to look into it.

Create a group, with all permissions like that:

![permissions](https://user-images.githubusercontent.com/9025839/72388028-31614f80-3725-11ea-97d8-93663b4dceb9.png)

And page rules like that:

![page-rules](https://user-images.githubusercontent.com/9025839/72388092-52c23b80-3725-11ea-90d3-c533fae5ba1c.png)

If you log as the user configured to this only group, he can no more view pages on `outils-developpement/...` path.

According to documentation https://docs.requarks.io/groups#overview , user should have all permissions on `outils-developpement/...` path, except delete one.

This is just an exemple, with no use case, to simply show there is a problem in denying rules, which deny even viewing pages.
Real use case is to allow creating page only in a specific directory, but it is not achievable as deny page rule seems buggy.

I must confess this is problematic, as we don't want any user edit any page, but we want to provide like a sandbox area so they can prepare pages.

Feel free to ask any further test / explaination if needed, this is top priority for us, as as it the wiki is no more usable if we cannot restrict some writing area.

Thanks a lot.

**Comment by Yivan** [comment]
I link to this issue, maybe related, i don't know : https://github.com/Requarks/wiki/issues/998

**Comment by Yivan** [comment]
For information, I tried another way, so i do not use deny rule to limit writing to a path, but it don't work too... so the problem is maybe deeper.

With same global permissions, but those page rules:

![image](https://user-images.githubusercontent.com/9025839/72388823-332c1280-3727-11ea-9adc-06bb883a3fd0.png)

User can write on any pages, but it should only be able to write on `outils-developpement/...`.
**Documentation lacks of detail on this. If no rules, path is forbidden for all action if their is at least a rule in the page rule settings ? I you could just explain this point please. Is it a DENY all by default ?**
If yes this is a bug. But if it is an allow ALL by default, so we must use block rule to restrict writing, which don't works.

Hope it helps. Thanks.

**Comment by NGPixel** [comment]
All permissions are DENY by default. I added more details to the docs to clarify this:
https://docs.requarks.io/en/groups

The bug you're having is being investigated.

**Comment by Yivan** [comment]
Thanks for having adding it to the documentation, it is helpful.

So as it is DENY by default, their is a breach as with

![image](https://user-images.githubusercontent.com/9025839/72433186-15979100-3799-11ea-937a-f1115ae3e831.png)

... users should not be able to write in any page except `/outils-development...`.
Actually they can write anywhere.
Thanks for looking into it, should be patched asap i think with a patch released as security is involved.

Best regards.

**Comment by mielipuolinen** [comment]
I was just about to report this too. For investigation purposes here's my report:

**Describe the bug**
Deny rule in page rules seems to be denying non-denied page rules too.

**To Reproduce**
Steps to reproduce the behavior:
1. Create a group
1.1 Global permissions: allow only read:pages and write:pages
1.2 Page rules:
1.2.1 delete default rule
1.2.2 create an allow rule for **read:pages** with default matching
1.2.3 create a deny rule for **write:pages** with default matching
2. Create a user and assign it to the group
3. Try logging in (can't because of wrongly denied read:pages)

**Expected behavior**
**read:pages** should be allowed and **write:pages** should be denied (as is).

**Additional context**
This issue is a substantial drawback in configurability for more complex user permissions.

**Comment by NGPixel** [comment]
Should be fixed by 7d23344c7af80909c43e42a383df4d916f7eedf6

**Comment by Yivan** [comment]
I confirm, problem has been fixed! Thanks a lot.
