### ISSUE TITLE
Can't resolve '../../util/ThemeProvider' in vuetify under version 2.2.0 of vuetify

### ISSUE THREAD

**Issue by snoleo** [Requarks/wiki#1378]
**Describe the bug**
after git pull lastest wikijs , run `npm install`,  when `yarn build`, then error occurs:

ERROR in ./node_modules/vuetify/lib/components/VDialog/VDialog.js
Module not found: Error: Can't resolve '../../util/ThemeProvider' in '/home/someuser/wikijs/node_modules/vuetify/lib/components/VDialog'
 @ ./node_modules/vuetify/lib/components/VDialog/VDialog.js 20:0-53 282:28-41
 @ ./node_modules/vuetify/lib/components/VDialog/index.js
 @ ./node_modules/vuetify/lib/components/index.js
 @ ./node_modules/vuetify/lib/index.js
 @ ./client/client-app.js
 @ ./client/index-app.js

ERROR in ./node_modules/vuetify/lib/components/VMenu/VMenu.js
Module not found: Error: Can't resolve '../../util/ThemeProvider' in '/home/someuser/wikijs/node_modules/vuetify/lib/components/VMenu'
 @ ./node_modules/vuetify/lib/components/VMenu/VMenu.js 23:0-53 423:87-100
 @ ./node_modules/vuetify/lib/components/VMenu/index.js
 @ ./node_modules/vuetify/lib/components/index.js
 @ ./node_modules/vuetify/lib/index.js
 @ ./client/client-app.js
 @ ./client/index-app.js
error Command failed with exit code 2.

**Host Info (please complete the following information):**
 - OS: Debian 8.11 jessie
 - Wiki.js sync with github lastest repo

**Additional context**
Works good under  "vuetify": "2.1.14",
After upgrade to "vuetify": "2.2", then, run `yarn build` will encounter this problem.

**Comment by NGPixel** [comment]
I can't replicate your issue. The continuous builds are running just fine as well, so it seems to be an issue on your side. Try deleting the node_modules folder and try again.

**Comment by snoleo** [comment]
Problem figured out, old vuetify files in ./node_modules/ are cached by webpack.
After deleted `rm -r .webpack-cache/` , then `yarn build` successfully.
