### ISSUE TITLE
Cannot assign users to admin role after they have registered

### ISSUE THREAD

**Issue by turekg** [Requarks/wiki#1384]
As an administrator I go to the Users admin page, click on a user and try to select the Administrator role in the Group pull down menu but it is grayed out

I should be able to select that role and have it replace the current role.

**Host Info (please complete the following information):**
Ubuntu 19.0
Wiki.js version 2.0.12
postgres 10.1

**Comment by NGPixel** [comment]
You must assign users from the Groups page. As a security measure, you cannot assign users to the root admin group from the user section.
