### ISSUE TITLE
Common users change their password

### ISSUE THREAD

**Issue by raiffsaid** [Requarks/wiki#1385]
Hello there! On our company we are trying some wikis, and until this moment, the WikiJS is by far the one that is better suited for our work. One thing that I tried to do but I couldn't find it, is if common users want to change their password a second time. Is it possible to do that or it's not implemented yet?

Thank you.

**Comment by NGPixel** [comment]
Not at the moment. Only the admin can for now.

**Comment by NGPixel** [comment]
@mikafouenski Coming in a future update

**Comment by almondevon** [comment]
I'm loving WikiJS, but this is also very important to our group.  "... password recovery capabilities." is one of the first features listed on the homepage, so I was surprised to find out this feature was dropped in 2.0.

**Comment by timmaes** [comment]
Hi,
We are also considering to use wiki.js as knowledge base for our customers. But the reset password feature is necessary in order to launch it.

Will it be integrated in update 2.3 (Inside the Major Feature "User profile/Account management"?

Thanks in advance
Tim Maes

**Comment by timmaes** [comment]
@NGPixel Would you be so kind to react to my question above, please?
Kind Regards
Tim

**Comment by sbonaime** [comment]
@timmaes

**Comment by sbonaime** [comment]
@timmaes 
Can you help for this issue  ? 

https://docs.requarks.io/en/releases/about
