### ISSUE TITLE
General rendering issues and error messages on each page after installation

### ISSUE THREAD

**Issue by githubdave2020** [Requarks/wiki#1386]
**Question**
After a brand new installation, it seems as if a file is missing that has basic title and button labels (unless what we are seeing is normal).  Also, as each page loads, we receive a message that indicates "An unexpected error occured.". When we toggle the developer tools the message indicates: "[GraphQL error]: Message: Invalid locale or namespace, Location: [object Object], Path: localization,translations 2 app.b98d10f6bb893bd895c4.js:2:2081".  This occurs on every page. 

 I have attached what we are seeing as well as the relevant information.  Are we missing something in our setup?  The "unexpected exceptions" seem to be related to the rendering of the page, but i am not certain. There is no information in the logs that we can use to determine the cause.  

Can you help us diagnose the cause of this issue?

**Host Info (please complete the following information):**
OS: Red Hat Linux (maipo) 7.7 x64
Wiki.js version: 2.0.12
Database engine: mySQL 5.7.28

![labels3](https://user-images.githubusercontent.com/59968339/72538503-90b58180-3843-11ea-99c8-416c8aea75eb.png)
![error2](https://user-images.githubusercontent.com/59968339/72538509-927f4500-3843-11ea-95b5-e3a20218d1e4.png)
![labels](https://user-images.githubusercontent.com/59968339/72538516-94490880-3843-11ea-8fd9-f0ec92499824.png)
![labels2](https://user-images.githubusercontent.com/59968339/72538533-9612cc00-3843-11ea-80ae-3493555caa3b.png)
![error](https://user-images.githubusercontent.com/59968339/72538536-97dc8f80-3843-11ea-8e5a-faca70afdcca.png)

Additionally, i have confirmed the server can reach out to the internet. I have also attempted to "sideload" the locales, and cleared the cache and still the pages do not have proper text in the labels.

**Comment by githubdave2020** [comment]
We reinstalled the application fresh and now the issue is not occurring.

**Comment by thunderbird57** [comment]
I am having the same issue. The server is connected to internet. Right after the initial installation I got an unexpected error has occurred. After that I am getting similar issues on every page

**Comment by lotusnoir** [comment]
hello
Same issue here, no solution found...
Please help
