### ISSUE TITLE
Incorrect asset ordering

### ISSUE THREAD

**Issue by hubalt** [Requarks/wiki#1387]
**Describe the bug**
Assets after num 125 appear on page 2 instead of the end.

**To Reproduce**
Upload 125+ images

**Expected behavior**
Consistent ascending/descending order

**Screenshots**
![wikijs-assets](https://user-images.githubusercontent.com/59969903/72541408-7b267300-38a8-11ea-9d1f-51c2b3f07c5f.jpg)

**Host Info:**
 - Wiki.js version: 2.0.12

**Additional**
Would be nice if the assets were displayed in reverse chronological order so the newest ones are always on page 1.

**Comment by sbonaime** [comment]
This issue should be fixed with #1501
