### ISSUE TITLE
read:source global permission has no effect

### ISSUE THREAD

**Issue by mielipuolinen** [Requarks/wiki#1388]
**Describe the bug**
A global permission read:source does not seem to have an effect. Docs states the following: "Therefore, giving no permission is the same as adding a Deny rule for all permissions. "

**To Reproduce**
1. Create a group and only select read:pages global permission
2. Create an user and assign it to the group
3. Try viewing source of a wiki page

**Expected behavior**
Access to view source should be denied by global permissions.

**Screenshots**
-

**Host Info (please complete the following information):**
 - OS: Ubuntu 18.04, unmodified docker compose file
 - Wiki.js version: 2.0.12
 - Database engine: PostgreSQL 11.6

**Additional context**
-

**Comment by NGPixel** [comment]
Fixed by 91e897ccd916aec4b1214beb03437d781ea58327
