### ISSUE TITLE
syntax of a newline

### ISSUE THREAD

**Issue by choicky** [Requarks/wiki#139]
### Actual behavior
The code block below is expected as three paragraphs.  However, it's `abc` in wiki.js.
```
a
b
c
```

It seems wiki.js is using a very traditional Markdown syntax in which a new line created by hitting "enter" key one time is not a new line.

### Expected behavior
A newline by one "Enter" key is a newline.

### Steps to reproduce the behavior

Refer to the above code block.

**Comment by NGPixel** [comment]
The official markdown syntax states you must type <kbd>Enter</kbd> twice to create a new paragraph.
If you want to force a single line change, simply add 2 spaces at the end of the line, then type <kbd>Enter</kbd>.

However I understand this behavior can be confusing at first, so I'll add an option to render single line breaks as new lines (e.g. GitHub behavior)

**Comment by NGPixel** [comment]
Added option to enable linebreaks (on by default) in Beta 13 (2380bd4bda5c4adc60a6605392e8c94dbf39a4d1)
