### ISSUE TITLE
wiki.js.org/feedback: login issue

### ISSUE THREAD

**Issue by mielipuolinen** [Requarks/wiki#1390]
Sorry, I know this isn't correct place for this but I'm not slack user either.

**Describe the bug**
Can't login into feedback/canny system. I have not logged in there before (out of licenses or something?). Tried with multiple browsers (FF & Chrome) and multiple accounts (GitHub, Google & local account)

**To Reproduce**
1. Go to wiki.js.org/feedback
2. Try commenting or voting
3. Asks for login, choose either Github, Google or local account (probably any option reproduces)
4. After login the page reloads
5. Try commenting or voting and it asks for login again

**Comment by NGPixel** [comment]
Try to login via https://requarks.canny.io/wiki
