### ISSUE TITLE
Error during upload

### ISSUE THREAD

**Issue by raikoug** [Requarks/wiki#1391]
**Describe the bug**
Uploading files generate "error during upload"
Images within 1 mb works
Something > 1,3 MB (ca) doesn't.
I don't know the extact limit but it should be 5 MB, no?
I tried in root and subfolders, same behaviour

**Host**
Version 2.0.0-rc.17
NodeJs 10.16.3
PostgresSQL 11.4
Docker container

Can't find a setting about upload size. I have more than 800 MB free.

Thanks

**Comment by NGPixel** [comment]
Upload limits are set in `config.yml` and it's 5 MB by default.

You most likely have a reverse proxy in front (nginx / apache) with a default limit of 1.3 MB. You need to modify that limit as well.

**Comment by raikoug** [comment]
You are right, totally my issue not knowing default nginx upload size is 1MB.
Sorry for bothering.
