### ISSUE TITLE
LDAP error Invalid email / username or password.

### ISSUE THREAD

**Issue by BeamerIsHere** [Requarks/wiki#1392]
**Question**
Configured LDAP authentication with all the required, but while trying to login with username and passwd, throwing "Invalid email / username or password" errror. Adding my configuration screenshot here as well. I think the issue is with the 'searchfilter'. 

**Host Info (please complete the following information):**
OS: Docker Container (Linux)
Wiki.js version: 2.0.12
Database engine: PostgreSQL version 11.6
![image](https://user-images.githubusercontent.com/42833377/72632232-e2612780-397b-11ea-8f32-08e55f82aa1f.png)

**Comment by NGPixel** [comment]
Why are you putting quotes around each value? Remove them.

**Comment by InterFelix** [comment]
I have the same problem. Not quotes, all the fields are populated correctly, as far as I can tell. My configuration is attached.
![grafik](https://user-images.githubusercontent.com/29462559/72679510-27867600-3ab0-11ea-8c74-b117081dc86a.png)

**Comment by BeamerIsHere** [comment]
@NGPixel I've removed the quotes and now able to see the "Login successful Redirecting" message and then it taking back again to the login page. Any suggestion?
![image](https://user-images.githubusercontent.com/42833377/72793355-59d6d580-3c60-11ea-8c16-ee0d540f5178.png)

**Comment by InterFelix** [comment]
Have a look at the configuration for the LDAP provider needed for the wiki to work. It is shown right below the area where you configure the LDAP module in the administration section of the wiki. I guess there is a problem with redirectURI in your case.

**Comment by BeamerIsHere** [comment]
@InterFelix Currently I'm using my server host-name (server_name.local:700) and the port to connect wiki, Do I need to create a sub-domain ( example wiki.company.com) inn order to use LDAP?

**Comment by InterFelix** [comment]
No, it should work with any valid URI

Vineesh Ramayyan <notifications@github.com> schrieb am Di., 21. Jan. 2020,
11:52:

**Comment by BeamerIsHere** [comment]
So basically, need to map wiki to any working URL?

**Comment by NGPixel** [comment]
Make sure the group you assign to new users has read permissions on the homepage

**Comment by BeamerIsHere** [comment]
@NGPixel where I can configure that?

**Comment by NGPixel** [comment]
Under Groups?

**Comment by BeamerIsHere** [comment]
Hey @NGPixel This issue resolved, I've removed the quotes and then LDAP worked, and given the read write permission for the home page . Everything seems smooth now.
