### ISSUE TITLE
When created a page in some folder, will create a duplicate page in the same folder

### ISSUE THREAD

**Issue by snoleo** [Requarks/wiki#1393]
**Describe the bug**
When created a page under a folder, will create a duplicate page in the same folder

**To Reproduce**
1. create a page "page1" under folder "folder"
2. create another page, navigate to folder , will see there are two "page1"

**Expected behavior**
will see only one "page1".

**Screenshots**
![2020-01-19_152424](https://user-images.githubusercontent.com/1975813/72676782-1baaac00-3ad0-11ea-9589-6be239d7f024.png)

**Host Info (please complete the following information):**
 - OS: Debian GNU/Linux 10 (buster)
 - Wiki.js version: latest sync with github
 - Database engine: (PostgreSQL) 12.1 (Debian 12.1-1.pgdg100+1)

**Additional context**
[only display] And there MAY be missing right ")"  in "/(root"  under "Virtual Folders"

**Comment by asalam05** [comment]
I too have the same problem :(

**Comment by annahri** [comment]
Same problem here.

**Comment by FlyingBBQ** [comment]
I also have both folder and page duplicates. Running PosgreSQL 12.1.

I have tried rebuilding the page tree with the built-in utilities:
Adminstration --> Utilities --> Content --> Rebuild page tree
But this has not effect; it didn't change anything.

**Comment by alexhocksween** [comment]
I encountered the same issue.
It looks like it's an issue on the front end as the graphql doesn't seem to have any duplicates.

**Comment by kingfisher77** [comment]
Same here. Hoped it goes away with current beta...

**Comment by FandangoInPetto** [comment]
Same issue, all pages have a duplicate in the same folder despite there only being one of each in db/graphql calls.

**Comment by asalam05** [comment]
@annahri @FandangoInPetto @kingfisher77 @alexhocksween @FlyingBBQ 

Luckily i took a back up of code and DB before upgrading to the new version and disabled the git sync before upgrading :)

I have reverted back to the old version (Wiki.js 2.0.12) using the backups to fix this issue. I will wait till the next version to see whether its fixed or not.

**Comment by NGPixel** [comment]
Fixed by 21f19d3ae60076769b5377fea58fb406bd9a41f3
