### ISSUE TITLE
Locale default blank when creating page in Administration when Locale is not English

### ISSUE THREAD

**Issue by snoleo** [Requarks/wiki#1394]
**Describe the bug**
When creating a page in Administration dashboard, and site locale is not default English, for example : Chinese. The default locale in creation panel is blank, it is should be the default locale the site administrator sets in the Administration.

While when creating a page Not in Administration dashboard (eg. in the site home page), there is no this problem.

**To Reproduce**
1. set site locale to other language
2. go to Administration -> click "New Page" in the top right corner, just beside the user icon.

**Expected behavior**
It should default set to the locale in the site's Administration locale.

**Screenshots**
![2020-01-19_160152](https://user-images.githubusercontent.com/1975813/72677395-e2c20580-3ad6-11ea-8511-acd2f13fb278.png)

![2020-01-19_153237](https://user-images.githubusercontent.com/1975813/72677369-a9899580-3ad6-11ea-88b1-68737d8b7edd.png)

**Host Info (please complete the following information):**
 - OS: Debian GNU/Linux 10 (buster)
 - Wiki.js version: latest sync with github
 - Database engine: (PostgreSQL) 12.1 (Debian 12.1-1.pgdg100+1)

**Additional context**
While when creating a page Not in Administration dashboard (eg. in the site home page), there is no this problem.

**Comment by Coconop** [comment]
Same issue:

OS: Debian GNU/Linux 9.11 (stretch)
Wiki.js: 2.0.12
Database: MySQL 10.4.11-MariaDB

It is not possible to change the locale after the page creation.
The page created in a specific locale does not appear when an other locale is selected.

**Comment by Coconop** [comment]
For information: In the administration panel > region settings you can enable space names for multiple languages.
Then you can edit a page and switch the locale back to the default one.

**Comment by NGPixel** [comment]
Fixed by a1e0e4f27a958541443966e6b435151aca848c5d
