### ISSUE TITLE
an unexpected error occured

### ISSUE THREAD

**Issue by xhj967** [Requarks/wiki#1396]
**Question**
this error display on the top of home page  when i click login button to finish install.
and take place again every time when back into home page.

**Host Info (please complete the following information):**
OS: [win7]
Wiki.js version: [e.g. 2.0.1]
Database engine: [e.g. postgres 10.11]
![err](https://user-images.githubusercontent.com/46950578/72718348-bbd80200-3bb0-11ea-8225-da6cf131f2fb.png)
![err2](https://user-images.githubusercontent.com/46950578/72718362-c6929700-3bb0-11ea-86e9-40bb1fba83b7.png)

**Comment by NGPixel** [comment]
It fails because your server is not connected to the Internet and can't download language files. If that's not possible for you, follow the instructions for sideloading these files: https://docs.requarks.io/install/sideload

**Comment by xhj967** [comment]
my wifi is not stable,thanks！
