### ISSUE TITLE
Previewer does not render when Markdown includes linked images

### ISSUE THREAD

**Issue by fireundubh** [Requarks/wiki#1398]
When an image is linked with Markdown syntax, the previewer does not or cannot render.

The previewer will render if the user scrolls beyond the point where the linked image would be displayed. If the user scrolls back to the point where the linked image would be displayed, the previewer will not render again.

From the user's point of view, while scrolling up and down, the previewer is constantly disappearing and reappearing.

I watched the HTML source in Developer Tools while reproducing the issue and I did not see any dynamic changes.

# Affecting Syntax

This is an example of how images can be linked with Markdown.

```markdown
[![Requarks Logo](https://www.requarks.io/svg/logo.svg)](https://https://www.requarks.io/svg/logo.svg)
```

# Configuration

Component | Flavor/Version
:--- | :---
OS | Ubuntu 17.10
Wiki.js | 2.0.12
DB | MariaDB 10.2.19

**Comment by isiah-lloyd** [comment]
I was not able to reproduce this bug using the latest development version.
