### ISSUE TITLE
A MD editor I like

### ISSUE THREAD

**Issue by choicky** [Requarks/wiki#140]
I like https://pandao.github.io/editor.md/ very much.  Sometimes I write down source to it and then paste it to the target page.

Specifically, I like the two features.

* Highlight the source

* live preview.

**Comment by NGPixel** [comment]
Both live preview and in-editor syntax highlighting are coming in a future release. The markdown editor already supports these, but I still need to write the rendering functions.

**Comment by NGPixel** [comment]
Implemented in 2.0.
