### ISSUE TITLE
Problem with old assets hash

### ISSUE THREAD

**Issue by mmdrn** [Requarks/wiki#1401]
**Question**
I got source of wiki from github and change some assets and then got a production version using ```yarn build```.
I copied new assets files to production server. but the server still trying to serve assets with old hash number.
Where is the problem that server is trying to serve old hash numbers ?

Note that I just copied new assets to the server and then restart the server.

**Host Info (please complete the following information):**
OS: Linux - Debian
Wiki.js version: 2.0.1
Database engine: PostgreSQL 11.4

**Comment by NGPixel** [comment]
You need to replace the full `/assets` folder. If you still get old assets, then you most likely have a caching issue either on your server or browser.
