### ISSUE TITLE
Table of Contents is not displaying correctly

### ISSUE THREAD

**Issue by ajkamath** [Requarks/wiki#1402]
After I add multiple pages, Table of contents is not getting displayed correctly.
In Admin Page, My dashboard shows these pages:
![Screenshot 2020-01-21 at 3 50 53 PM](https://user-images.githubusercontent.com/279070/72796893-28610880-3c66-11ea-8856-ec02bd6d5f49.png)

Here you can see there is /ark/1,  /ark/trial ,  /ark/aj and /ark/T4
None of them get shows in the table of contents when I got to ark page as shown below

![Screenshot 2020-01-21 at 3 53 54 PM](https://user-images.githubusercontent.com/279070/72796958-42025000-3c66-11ea-8712-f6eb6e856f3c.png)

**Host Info (please complete the following information):**
OS: [Linux - Ubuntu Linux (xenial) 16.04 x64]
Wiki.js version: [2.0.12]
Database engine: [PostgreSQL 9.5.19]
Node version: 10.18.1

**Comment by ajkamath** [comment]
Just FYI. Even If you click on "ARK" in the Table of Contents, it doesnt drop down

Also Update: After removing Ark and adding again, Now Table of content is completely disappeared. Looks like a bug
![image](https://user-images.githubusercontent.com/279070/72804205-e63fc300-3c75-11ea-83d6-b07b41c67d1e.png)

Furthermore, I have tried this on 2.0.1 also. Same issue persists.
I have also tried with Node 10.12.0 and 12.14.1. Still same issue exists

**Comment by ajkamath** [comment]
I think my understanding is incorrect. Table of contents in only visible when i use MarkDown to create Page and # gives TOC.
While Visual Editor based page doesnt create TOC.
One issue is while using Markdown, many of the features of Visual editor is not there like Video linking, Hyperlinks etc. Let me know when will this come up.

You can close this issue i think

**Comment by reedfoxy** [comment]
I have the same problem.

**Comment by XerqJon** [comment]
@ajkamath your new understanding of the TOC is correct. Currently a TOC is generated for a page based on the Header1 and Header2 sections on the page (in Markdown, I cannot comment on your finding that this is not the case in Visual Editor).

That said, the Markdown editor is capable of everything the visual editor is and more. It's actually the editor where all functionality is possible. The only difference is that currently some of the toolbar buttons on the MD editor don't function. You can add hyperlinks and link videos and much more by typing the syntax manually (you can click the ? for help on the markdown editor for examples).

**Comment by ajkamath** [comment]
Thanks for the tips
