### ISSUE TITLE
Failed to fetch folder hierarchy -- message received when uploading files to any folder other than root.

### ISSUE THREAD

**Issue by githubdave2020** [Requarks/wiki#1403]
**Describe the bug**
When uploading assets, I am able to upload any asset to the root folder.  When i select a folder _other_ than the **root** folder, I am unable to upload and receive an error response:

[HTTP/1.1 400 Bad Request 10ms]
{"succeeded":false,"message":"Failed to fetch folder hierarchy."}

**To Reproduce**
1. Go to any existing page and create a folder within the assets screen.
2. With the newly created folder selected, navigate to the upload area and upload a file.
3. Choose upload.
4. A message displays that indicates the file upload failed.

**Expected behavior**
The file should be uploaded to the requested folder.

**Host Info (please complete the following information):**
 - OS: Linux - Red Hat Linux (maipo) 7.7 x64
 - Wiki.js version: 2.0.12
 - Database engine:  mysql 5.7.28

**Additional context**
![2020-01-21_11-02-12](https://user-images.githubusercontent.com/59968339/72826158-f176fc80-3c3d-11ea-84a7-352fc95cbd6f.png)

**Comment by NGPixel** [comment]
https://docs.requarks.io/install/requirements/mysql5
