### ISSUE TITLE
OKTA Authentication - Login Failed

### ISSUE THREAD

**Issue by jnpantall** [Requarks/wiki#1408]
**Describe the bug**
Unable to login using OKTA authentication.

**To Reproduce**
1. Enable OKTA integration
2. Enter the OKTA credentials into WikiJS.
3. Click apply.
4. Attempt to sign in using OKTA credentials.
5. OKTA's logs say successful login, but after signing in through OKTA the redirect takes you back to Wiki.js login page, unauthenticated.

**Expected behavior**
Clicking OKTA login button should also authenticate user with Wiki.js and route them into the website.

**Host Info (please complete the following information):**
 - OS: Ubuntu 18.04, Docker
 - Wiki.js version: 2.0.12
 - Database engine: Postgres 11.6

Let me know if you need any additional information. Thanks!

**Comment by NGPixel** [comment]
Make sure the group you assign new users to has read access to the homepage.

**Comment by jnpantall** [comment]
Thanks, that was the problem! Appreciate it.
