### ISSUE TITLE
local accounts can't login

### ISSUE THREAD

**Issue by TTherouanne** [Requarks/wiki#1409]
**Describe the bug**
I can not longer login with a local account

**To Reproduce**
I don't know

**Host Info:**
 - OS: CentOS7
 - Wiki.js version: 2.0.12
 - Database engine: postgres 11.6
 - Nodejs: 10.18.0

**Additional context**
I can login with an LDAP account, but no longer with local accounts, after having promoted my LDAP account in the administrators group (in the database), I was able to create a new local user, but I still cannot connect.
I have no idea what may have caused this problem ...

**Comment by TTherouanne** [comment]
I have enabled SQL query logs, if that helps:
`Debug SQL:
{ method: 'select',
options: {},
timeout: false,
cancelOnTimeout: false,
bindings: [ 'admin', 'local' ],
__knexQueryUid: '88b4aae7-bf54-4428-935b-5d9e9ee7cb1a',
sql:
'select "users".* from "users" where "email" = ? and "providerKey" = ?' }
`  

The message on the UI: "Invalid email / username or password."

**Comment by rec** [comment]
I have the same issue - it applies to local accounts but not the administrator account.

I note that when you go through the login process, it claims that it has logged you in, and then says, "Redirecting", and this bring you back to the login page.

**Comment by TTherouanne** [comment]
Not really the same, in my case, my only local account is an administrator.
I use the LDAP authentication for the users

**Comment by TTherouanne** [comment]
I just realized that login works with the email address, so the problem occurs only with the username

**Comment by rec** [comment]
Hmm, interesting.  I get the issue using the email addresses to log in.

Perhaps I should file a separate issue?  It'd be nice to see the maintainers weigh in here.

**Comment by NGPixel** [comment]
@TTherouanne The emails work because you defined the search filter using the email fields. Use the username AD field instead to login using usernames.

@rec Your issue is completely unrelated. Make sure the group you assign your new users to has read access to the homepage. Otherwise they get redirected to the login page.

**Comment by TTherouanne** [comment]
Hello Nicolas, 
Thanks for your answer,
I'm using the samaccountname field in the LDAP filter, LDAP users are able to login with their username without problem.
The problem occurs only with the local account (admin), I can't login with the username, i have discovered this morning that if i use the email, it works so i have a simple workaround, not a big issue finaly...

**Comment by NGPixel** [comment]
This is the expected behavior ... Local accounts don't have usernames. LDAP is the only strategy to use usernames. All other strategies (including local) must use emails.

**Comment by TTherouanne** [comment]
Ok, I did not understand that (email/username in the 'placeholder' value of the input) ^^
I will close the issue
Thank you

**Comment by rec** [comment]
> Make sure the group you assign your new users to has read access to the homepage. Otherwise they get redirected to the login page.

Ah, interesting!  This is a fresh installation, so this is default behavior. I'll bet you get this question a lot.  :-D

You might consider an error message instead of the unintuitive behavior of giving them the login page again.
