### ISSUE TITLE
Login Flow

### ISSUE THREAD

**Issue by ryanilg** [Requarks/wiki#141]
### Actual behavior

If a user follows a link but is not logged in, it redirects the user to the front page after authenticating.

### Expected behavior

The user should be redirected back to the link/page they requested.

### Steps to reproduce the behavior

1. Ensure you are logged out
2. Try to visit a specific page
3. You are redirected to the login page
4. Log in
5. You are redirected to the front/home page

**Comment by ilyamochalov** [comment]
strangely, but I can't find this code change on the latest legacy codebase https://github.com/Requarks/wiki/blob/v1.0.102/server/middlewares/auth.js#L18
@NGPixel  do you know what has happened with that code fix
