### ISSUE TITLE
I can not log in with my administrator credentials

### ISSUE THREAD

**Issue by StavrosFerkadis** [Requarks/wiki#1410]
**Question**
I've created my own fork installation in heroku with a postgresSQL. 

The deployment is succesfull and the installation screen runs asking me to set up the administration credentials.  

I do so and then when i try to log in, I get a "Login Sucesfull... Redirecting" green box but then it just redirects me back to the log in page. 

Trying to navigate to my homepage, just redirects me to /login instead as well. 

![image](https://user-images.githubusercontent.com/2179350/73082359-3ced0d00-3ec1-11ea-9312-001da32f1c63.png)

**Host Info (please complete the following information):**
Heroku 
Wiki.js version: Latest 
Database engine: heroku postgres 11.6

**Comment by NGPixel** [comment]
If you're going to install from a fork, you need to use [a released tag](https://github.com/Requarks/wiki/tree/2.0.12). The master branch is not stable.
