### ISSUE TITLE
Image float left/right works in editor, but not on final rendered page

### ISSUE THREAD

**Issue by brewerc1** [Requarks/wiki#1413]
**Describe the bug**
In editor, if I float an image right or left, it behaves as expected. But when page is saved, the image is left aligned as a block-level element, not floated left/right.

**To Reproduce**
1. create page with visual editor, and add content (or edit existing page with the visual editor).
2. upload/choose and image
3. float image left or right.
4. save page.
5. view page and notice that image is not floated left or right.

**Expected behavior**
When floated left or right in editor

**Screenshots**
Editor: ![editor](https://user-images.githubusercontent.com/5948594/73180742-ed3a5b80-40e3-11ea-8bab-5a4a2371be93.png)
Rendered Page: ![rendered](https://user-images.githubusercontent.com/5948594/73180751-f297a600-40e3-11ea-914a-587b82188481.png)

**Host Info (please complete the following information):**
 - OS: Ubuntu 18.04 w/node.js 10.18.1
 - Wiki.js version: 2.0.12
 - Database engine: postgres 10.10

**Comment by Scrik** [comment]
UP. This bug in 2.3.81 too

**Comment by DAlperin** [comment]
I have a fix for this. I'll make a PR shortly.
