### ISSUE TITLE
Inconsistent pages when running wikijs with multiple pods on kubernetes

### ISSUE THREAD

**Issue by piyush0609** [Requarks/wiki#1419]
### Actual behavior
We have deployed wikijs on kubernetes with 2 pods. When we edit the page and save it and do a refresh. The edited page when refreshed sometimes shows the changed data and sometimes it does not show the changed data.
The same issue doesn't occur when we deploy it using 1 pod

### Expected behavior
Assuming wikijs is a stateless service, it should not matter whether we deploy wikijs on 1 instance or multiple instances behind a load balancer. But this is just an assumption
I haven't found any substantial documentation around the high level wikijs architecture to make a deduction.
Please guide me if i am missing something.

**Comment by piyush0609** [comment]
We went through the code and we found out the that the pages are being served from cache. But if any changes are made to pages, the cache is not being invalidated due to which it is returning the stale data after editing. Please let me know if you need more clarification on the issue.

**Comment by NGPixel** [comment]
Added in 2.3
