### ISSUE TITLE
Error at configuration step

### ISSUE THREAD

**Issue by onaret** [Requarks/wiki#142]
Hello requarks

### Actual behavior
First attempt to use wiki.js
At configuration step, this occur:

> I'll wait until you're done ;)(node:9417) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Command failed: node wiki configure
> /home/me/web-dev/wiki/node_modules/semver/semver.js:266
>   var s = parse(version.trim().replace(/^[=v]+/, ''), loose);
>                        ^
> 
> TypeError: Cannot read property 'trim' of undefined
>     at Function.clean (/home/me/web-dev/wiki/node_modules/semver/semver.js:266:24)
>     at exec (/home/me/web-dev/wiki/server/configure.js:104:42)
>     at ChildProcess.exithandler (child_process.js:197:7)
>     at emitTwo (events.js:106:13)
>     at ChildProcess.emit (events.js:194:7)
>     at maybeClose (internal/child_process.js:899:16)
>     at Socket.<anonymous> (internal/child_process.js:342:11)
>     at emitOne (events.js:96:13)
>     at Socket.emit (events.js:191:7)
>     at Pipe._handle.close [as _onclose] (net.js:509:12)
> 
> (node:9417) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code
> 

### Steps to reproduce the behavior

With
nodejs: v7.8.0
Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1+deb8u2 (2017-03-07) x86_64 GNU/Linux

When running
`npm install wiki.js@latest`
Choose default port of 3000
Get to the server page using  Chrome
Click on start
An error window will popup
> Network Error

The atached log is produced

**Comment by NGPixel** [comment]
Are you using Debian 8 x64? I'll spin up a VM later today to test it.

**Comment by onaret** [comment]
Yes Debian 8 x64

**Comment by onaret** [comment]
I am not accessing the server from localhost but an other machine

**Comment by NGPixel** [comment]
I was able to install Wiki.js successfully on Debian 8.

I created a page in the wiki detailing all the steps. See if you didn't miss something:
https://docs.requarks.io/wiki/admin-guide/install-debian-8

**Comment by onaret** [comment]
I still have the same issue when following those instructions (more or less). I will redo it anyway with node 6 LTS and see as I was still using 7.8. I had no problem installing it on an other PC running on Arch.
I will keep you updated when I go back to work on it.

**Comment by theodotos** [comment]
I got this two on an Ubuntu 16.04 container.

**Comment by onaret** [comment]
reproduced with node 6

**Comment by NGPixel** [comment]
What is the output of `git --version`?

**Comment by onaret** [comment]
git version 2.13.GIT

**Comment by onaret** [comment]
also 

`mongod --version`

mongod --version 
db version v2.4.10
Tue Jun 27 09:35:31.775 git version: nogitversion

**Comment by NGPixel** [comment]
Fixed for Beta 13 (9ee940f984f05abe86aea16a2b043ec42dbef8c9)
