### ISSUE TITLE
Change password input didn't clear after submit

### ISSUE THREAD

**Issue by andrelec1** [Requarks/wiki#1420]
**Describe the bug**
When user change thier password, the input isn't clear after submiting the new password...
( this can be a security issue )

**To Reproduce**
Go to the user admin page
change the password
validate
reopen the change password 
( at this point if you change the input type with the chrome debugtools, you can see the password in clear )

**Expected behavior**
Force clear value after submit

**Screenshots**
![image](https://user-images.githubusercontent.com/3273204/73442065-67711700-4354-11ea-992e-e81eaf468c59.png)

**Host Info (please complete the following information):**
 - OS:  Ubuntu 18.04
 - Wiki.js version: 2.0.12
 - Database engine: sqlite

**Comment by NGPixel** [comment]
Fixed by 4e9d4071fd78a1b1588d8f062b8baefe01d0bac1
