### ISSUE TITLE
docker canary build Wiki.js 2.1.86 -  Failed to setup HTTPS server parameters:

### ISSUE THREAD

**Issue by worryboy** [Requarks/wiki#1421]
### Actual behavior
while starting the canary build ,  
> docker container logs -f  wiki

returns **"The "path" argument must be one of type string, Buffer, or URL. Received type undefined"**
> Loading configuration from /wiki/config.yml... OK
> DB_PASS_FILE is defined. Will use secret from file.
> 2020-01-30T13:09:25.738Z [MASTER] info: =======================================
> 2020-01-30T13:09:25.740Z [MASTER] info: = Wiki.js 2.1.86 ======================
> 2020-01-30T13:09:25.740Z [MASTER] info: =======================================
> 2020-01-30T13:09:25.740Z [MASTER] info: Initializing...
> 2020-01-30T13:09:26.018Z [MASTER] info: Using database driver pg for postgres [ OK ]
> 2020-01-30T13:09:26.023Z [MASTER] info: Connecting to database...
> 2020-01-30T13:09:26.054Z [MASTER] info: Database Connection Successful [ OK ]
> 2020-01-30T13:09:26.160Z [MASTER] warn: DB Configuration is empty or incomplete. Switching to Setup mode...
> 2020-01-30T13:09:26.160Z [MASTER] info: Starting setup wizard...
> 2020-01-30T13:09:27.070Z [MASTER] info: Starting HTTP server on port 3000...
> 2020-01-30T13:09:27.070Z [MASTER] info: HTTPS Server on port: [ 3000 ]
> 2020-01-30T13:09:27.071Z [MASTER] error: Failed to setup HTTPS server parameters:
> 2020-01-30T13:09:27.071Z [MASTER] error: The "path" argument must be one of type string, Buffer, or URL. Received type undefined

### Expected behavior
wiki startup 
### Steps to reproduce the behavior
create string 
> docker create --name=wiki -e DB_TYPE=postgres -e DB_HOST=db -e DB_PORT=5432 -e DB_PASS_FILE=/etc/wiki/.db-secret -v /etc/wiki/.db-secret:/etc/wiki/.db-secret:ro -e DB_USER=wiki -e DB_NAME=wiki -e UPGRADE_COMPANION=1 -e USE_HTTPS=1 -e LETSENCRYPT_DOMAIN=wiki.xxxx.net -e LETSENCRYPT_EMAIL=xx@xxx.xx --restart=unless-stopped -h wiki --network=wikinet -p 80:3000 -p 443:3001 requarks/wiki:canary

start db as described on [FAQ](https://docs.requarks.io/install/ubuntu) 

> docker start wiki

start wiki ---- > error occurs

**Comment by hmqgg** [comment]
Try to set SSL_ACTIVE to true.

**Comment by worryboy** [comment]
> Try to set SSL_ACTIVE to true.

withou success

**Comment by hmqgg** [comment]
The cert file reading of LetsEncrypt implementation throws the exception you found.

If it's acceptable, you could set SSL_ACTIVE to false to disable the LetsEncrypt cert acquire process, and use reverse proxy with LetsEncrypt script such as Nginx + certbot (what I did).

**Comment by worryboy** [comment]
> The cert file reading of LetsEncrypt implementation throws the exception you found.

yes could be .. 

> If it's acceptable, you could set SSL_ACTIVE to false to disable the LetsEncrypt cert acquire process, and use reverse proxy with LetsEncrypt script such as Nginx + certbot (what I did).

for sure .. i aware about that.. and yes thats works 

nevertheless its a bug ;)

**Comment by NGPixel** [comment]
It should be `SSL_ACTIVE` instead of `USE_HTTPS` and the default HTTPS port is `3443`, not `3001`. I updated the documentation to reflect the latest changes.

You shouldn't get the same logs with these settings. Post them here if you still get an error.
