### ISSUE TITLE
LDAP Authentication Problem 

### ISSUE THREAD

**Issue by fatihbildiricii** [Requarks/wiki#1423]
Hello,
We live problem for LDAP configuration / authentication.

For login request we give invalid username - password error in LDAP.
And our LDAP settings in below;

Can you give any clue about this?
Can you help us to solve this?

![github](https://user-images.githubusercontent.com/40956646/73522338-30186e00-4419-11ea-90c8-97b5ea324f61.PNG)

Thanks,
Fatih

**Host Info (please complete the following information):**
OS: [Windows Server 2012]
Wiki.js version: [ 2.0.12]
Database engine: [ postgres 11.5.2.]

**Comment by pavemina** [comment]
Hi, as per the [LDAP documentation](https://docs.requarks.io/en/auth/ldap) you can enable debugs for LDAP in Administration Area > Developer Tools > Flags > LDAP Debug. You should probably look at that first while reproducing the issue. If it's unclear, you could share the output here (reasonably sanitized) for others to check.

**Comment by BeamerIsHere** [comment]
Hey @fatihbildiricii Follow the steps 
# Turning on the "Allow self-registration" button at the end of the LDAP config page.
#  also remove the space between CN and OU in the admin bind session.
#  Set unique ID field, email field mapping, display name field
#  Create a group and give read write access of home page, and also add the group name to the  assign to group field
