### ISSUE TITLE
LDAP configuration inside docker file.

### ISSUE THREAD

**Issue by BeamerIsHere** [Requarks/wiki#1426]
**Question**
Hi Team,
I'm trying to install wikijs via docker-compose, and was able to up and run the same. Now I need some clarifications. 
I want to configure LDAP authentication inside docker file or inside docker-compose file. I that possible? If yes how? 
Basically I need everything up and run by just running the docker-compose, including LDAP configuration.
A help will be much appreciated....  

**Host Info (please complete the following information):**
OS: Docker Container (Linux)
Wiki.js version: 2.0.12
Database engine: PostgreSQL version 11.6

**Comment by NGPixel** [comment]
No, LDAP configuration is done via the web UI.

**Comment by BeamerIsHere** [comment]
@NGPixel Is there any way to do that other that setting up in GUI. If we can send the LDAP configuration to the actual storage that will work right.?

**Comment by NGPixel** [comment]
No. The configuration is stored in the db, not in the storage provider.

**Comment by BeamerIsHere** [comment]
I've seen this on "https://docs-legacy.requarks.io/wiki/install/authentication" it suggests to give the LDAP configuration inside the config.yml file. 

 Under the auth section of your config.yml, enter the required info:

ldap:
    enabled: true
    url: ldap://serverhost:389
    bindDn: cn='root'
    bindCredentials: BIND_PASSWORD
    searchBase: o=users,o=example.com
    searchFilter: (uid={{username}})
    tlsEnabled: false
    tlsCertPath: C:\example\root_ca_cert.crt

**Comment by NGPixel** [comment]
This is Wiki.js 1.x documentation, not 2.0.

I already answered your question, it's not possible, period. **Use the admin UI as previously suggested.**
