### ISSUE TITLE
Sharing a PDF with password protection + hide download results in cURL error 3

### ISSUE THREAD

**Issue by sray** [Requarks/wiki#1427]
**Describe the bug**
If you share a pdf using a share link with password protection and you tick "hide download" you get the following error message: "cURL error 3: (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)"

**To Reproduce**
1. Upload a PDF
2. Click on 'the share icon'
3. Click on '+' behind the 'Share link' label
3. Enter Password (if password protection is mandatory, or activate password protection manually)
4. Click on '...' behind the 'Share link' label
5. Click on the check box 'Hide download' to activate the feature to hide the download button
6. Copy share link url
7. open then share link in separate browser window (make sure to log out first)
8. See error

**Expected behavior**
See the PDF without the inline PDF menu open (just presentation mode like you can activate with pressing F5 in most PDF reader clients) and now download button

**Screenshots**
![Screenshot from 2020-01-31 20-22-59](https://user-images.githubusercontent.com/1809538/73568458-b8722f80-4468-11ea-87f7-2471248f5d8d.png)
![Screenshot from 2020-01-31 20-24-57](https://user-images.githubusercontent.com/1809538/73568457-b8722f80-4468-11ea-8282-c0e1b7e20a05.png)

**Host Info (please complete the following information):**
 - OS: Debian 10
 - Wiki.js version: 2.0.12
 - Database engine: postgres 11

**Comment by NGPixel** [comment]
??? What are you talking about?

The screenshot and what you just described is not even wiki.js and has nothing to do with this project...

**Comment by sray** [comment]
@NGPixel ah, sorry jsut noticed, that I posted this in the wrong repo :-D That's a nextcloud bug ;-)
