### ISSUE TITLE
No need to login into wiki

### ISSUE THREAD

**Issue by fordanic** [Requarks/wiki#1428]
Have local and LDAP authentication enabled but still able to access the content of the wiki without signing in.

Running latest version using Docker.

**Comment by NGPixel** [comment]
Have you removed the read permission to the Guest group?

**Comment by eeshugerman** [comment]
see https://docs.requarks.io/groups#private-wiki

**Comment by fordanic** [comment]
My bad, thanks for the pointers guys.
