### ISSUE TITLE
Unable to publicly access wiki despite public: true

### ISSUE THREAD

**Issue by marshallaf** [Requarks/wiki#143]
### Actual behavior
After either checking the "Allow public access" checkbox in the config wizard or manually setting `public: true` in the config.yml, the guest access is still set to "Deny" in the User panel, and thus prevents public access to the wiki.

### Expected behavior
The wiki should set the guest access corresponding to what is selected during setup.

**Comment by NGPixel** [comment]
The guest permissions are set based on the `public` value the very first time Wiki.js starts. If you change the value at any point later, the guest user is already created so it is not modified.

Was Allow Public access checked the very first time you set it up?

**Comment by marshallaf** [comment]
Yep, you're right. I really thought I had it set to public when I set it up both times, but I guess I didn't. Just confirmed that it configures guest permissions correctly when setting up using either method (wizard and manual). Thanks for clearing that up!

**Comment by NateV** [comment]
Can I add public read-only access by editing the MongoDB? It kind of looks like I could change "rights:deny: true" to "false". Is that right, or will that cause something else?

**Comment by ikarulus** [comment]
Not working for me, too.
There is no setup, when I'm using Docker.
