### ISSUE TITLE
Cannot delete LDAP user or edit their email

### ISSUE THREAD

**Issue by brettwooldridge** [Requarks/wiki#1433]
**Describe the bug**
I have setup wiki.js to use LDAP authentication against Active Directory.  I successfully logged in using a domain account, and an appropriate account was created in wiki.js.

However, I noticed that the email address was incorrect in Active Directory.  Editing the address in AD did not have the affect of updating the user information stored in wiki.js upon next login -- which persisted in keeping the incorrect email address.

So, I logged in as a local admin user...

I thought I would just edit the email information for the user in wiki.js.  Unfortunately, the edit option is not available for the ``Email`` field.

Then I thought I would just *delete* the account completely in wiki.js, and login again to allow it to be created with the (now) correct information.  Unfortunately, it seems the delete button ("trashcan") is disabled for LDAP accounts.

**To Reproduce**
1. Login to an account via LDAP
2. Logout
3. Login via a local admin account and go to Administration->Users
4. Edit the LDAP user
4. Attempt the edit the ``Email`` field, or to delete the LDAP user account

**Expected behavior**
Possibly understandably the email cannot be altered once the account is created, although this would be preferable.  If a user changes their email address (for example, she marries and her last name changes) there is no way to update the wiki.js account information.

But certainly an administrator should be able to delete an LDAP user that was created automatically upon login.

**Screenshots**
<img width="1047" alt="Screen Shot 2020-02-03 at 5 58 38 PM" src="https://user-images.githubusercontent.com/1538661/73639213-42133e80-46af-11ea-8a4e-77a3599cc2fe.png">

**Host Info (please complete the following information):**
 - OS: Official Docker
 - Wiki.js version: 2.0.12
 - Database engine: postgres 11

**Comment by brettwooldridge** [comment]
Oh, I see from #905 (closed) that users cannot be deleted.  Ouch.

**Comment by BeamerIsHere** [comment]
@brettwooldridge could you explain how you configured LDAP?

**Comment by NGPixel** [comment]
This is fixed in 2.1, coming later this week (currently in beta).
