### ISSUE TITLE
bug logout

### ISSUE THREAD

**Issue by turok33gt** [Requarks/wiki#1438]
### Actual behavior

after logging out, if you make a request to any page, we go to it without any problems.

### Expected behavior

after logging out, when trying to access the page by means of a get request, we should be directed to the login page.

### Steps to reproduce the behavior

step1) login in system.
step2) click exit in the menu in the upper right corner
step 3) in the address bar we execute the request yourdomain/home

- Wiki.js 2.0.12

- 8.0.19 MySQL

- Ubuntu 18.04

- Firefox 72.0.2 (64-bit)

**Comment by isiah-lloyd** [comment]
What are your settings for the Guest group? By default guests are allowed to read wiki pages.

**Comment by NGPixel** [comment]
As @isiah-lloyd mentionned, you need to remove read access from the Guests group. By default, guests have read access.
