### ISSUE TITLE
redirect not work after login for user with limited rights

### ISSUE THREAD

**Issue by turok33gt** [Requarks/wiki#1439]
**Describe the bug**
after logging in as a user who is in a group with limited rights and has access starting from a certain path, for example, / support / test redirects back to the login page.

**To Reproduce**
1. create a page with the path / home / TEST
2. create a test group and in it allow reading and writing only starting from a certain path to. watch img1
3. create a user and add him to the test group
4. log in as created user
**Expected behavior**
after successful authorization, you will be redirected to the page specified as the initial one in the group settings. example /home TEST

**Screenshots**
IMG1
![image](https://user-images.githubusercontent.com/34717139/73854029-80893480-483a-11ea-96bb-7ea4f1a91d18.png)

**Host Info (please complete the following information):**

-     Wiki.js 2.0.12
-     8.0.19 MySQL
-     Ubuntu 18.04
-     Firefox 72.0.2 (64-bit)

**Comment by NGPixel** [comment]
Fixed by ff5acba358fcdbc8c527527b20103c412e732320
