### ISSUE TITLE
GraphQL: playground has clean session not associated with current user

### ISSUE THREAD

**Issue by akaRem** [requarks/wiki#1442]
**Describe the bug**
When GraphQL Playground is invoked from admin section, it has clean session, so that bearer token should be copied from dev console. 
This is not very convenient. 
preserved session or at least snoppet with token would be a great option.

**Host Info (please complete the following information):**
 - Wiki.js version: 2.0.12

**Comment by NGPixel** [comment]
Added a button to copy current auth token in v3.
