### ISSUE TITLE
Unable to login on self-registered accounts

### ISSUE THREAD

**Issue by tao-oat** [Requarks/wiki#1446]
**Describe the bug**
I am unable to login after creating an account through the web UI.

**To Reproduce**
1. Use a Postgres database and enable self-registration in Wiki.js.
2. Through the web UI, create an account and confirm the email.
4. Try to sign in -- you'll see a "success" notice, but then you'll be redirected to the login page.

**Expected behavior**
A "success" sign in actually signs you in.

**Host Info (please complete the following information):**
 - OS: Debian 9.9, Docker version 18.09.6, build 481bc77
 - Wiki.js version: 2.0.12
 - Database engine: Postgres 11

**Additional context**
I can sign in just fine with the admin account that was created when I set up the wiki.

**Comment by NGPixel** [comment]
Make sure the group has read access to the home page

**Comment by tao-oat** [comment]
Thank you, that resolved it. It seems odd that all users don't automatically inherit the permissions of the Guest group, but that's for another issue.
