### ISSUE TITLE
Problem Installing Wiki.js, got error "... files are missing: 2.1.85.js"

### ISSUE THREAD

**Issue by jam88881** [Requarks/wiki#1448]
Hi, 
I cannot find anything about how to solve this one on google search. 
I am running on a fresh installation of PostGreSQL. 

I have included my PowerShell output and config.yml as a txt file. (yes, I changed the port from the default to 5100)

[config.yml.txt](https://github.com/Requarks/wiki/files/4173232/config.yml.txt)
![Capture](https://user-images.githubusercontent.com/13112498/74072109-9d4c7600-49ba-11ea-83af-f27a2248c0c0.PNG)

PS Thank you NGPixel for all the help you have already provided to me and others online.

**Comment by NGPixel** [comment]
Did you try to install 2.1.103 previously and are reusing the same database?

**Comment by jam88881** [comment]
Yes, This is the second time I have tried to set this up, the first time I have done so with this success.
I had to uninstall then reinstall PostGreSQL. It works now. Thanks for the help.
