### ISSUE TITLE
Spacing between hyperlinks and text is 0

### ISSUE THREAD

**Issue by Fruxh** [Requarks/wiki#1449]
**Describe the bug**
The spacing between hyperliked text and normal text is = 0 even though the source is made with a spacing.

**Expected behavior**
The spacing would have to be at least 1 character.

**Screenshots**
Source:
![image](https://user-images.githubusercontent.com/37774297/74076022-df56d580-4a15-11ea-840b-6181fa85a0e9.png)

Visual page:
![image](https://user-images.githubusercontent.com/37774297/74076002-cb12d880-4a15-11ea-91f8-b68c6f224070.png)

**Host Info**
 - OS: Ubuntu 19.10.1
 - Wiki.js version: 2.1.103
 - Database engine: MySQL 8.0.18

**Comment by NGPixel** [comment]
Fixed by 48ea692afe53164f33cab572b89bdbc196b843fb
