### ISSUE TITLE
JavaScript is broken on Safari

### ISSUE THREAD

**Issue by jeffbr13** [Requarks/wiki#145]
### Actual behavior

Safari shows very basic HTML with all the styling and buttons broken, due to a `const` being declared twice.

![screen shot 2017-06-23 at 16 12 04](https://user-images.githubusercontent.com/558400/27488360-c3167320-582e-11e7-8d9b-3b553d91c04e.png)
![screen shot 2017-06-23 at 16 12 22](https://user-images.githubusercontent.com/558400/27488361-c339a3c2-582e-11e7-9eb7-6d096f15204d.png)

### Expected behavior

Safari should work exactly the same as Chrome and Firefox.

### Steps to reproduce the behavior

Access <https://docs.requarks.io/wiki> using Safari.

**Comment by NGPixel** [comment]
This is a bug in Safari itself, which have been fixed in the latest Safari Technology Preview. It will most likely be included in an upcoming update.

https://bugs.webkit.org/show_bug.cgi?id=171041

**Comment by localjo** [comment]
So there's no way to access Wiki.js apps on iOS Safari until the Safari fix is released? Let's find a work around.

**Comment by NGPixel** [comment]
I found a way to make it work on Safari while working on another project. I'll try to release an hotfix this week.

**Comment by localjo** [comment]
Awesome. Let me know if I can help. I was about to start debugging, but if you've already got a solution, that may be faster.

**Comment by NGPixel** [comment]
Fixed for Beta 14 (a96a7efd9d6aa16807eb0e603b5f18c236aac9d6)

**Comment by NGPixel** [comment]
Now available in 1.0.1 Release.
