### ISSUE TITLE
Sidebar locale path redirection to base locale

### ISSUE THREAD

**Issue by Fruxh** [Requarks/wiki#1450]
**Question**
I understand why non-locale paths are redirected to the bade locale but if you have multiple locales added then the sidebar redirects to the base locale every time instead of redirecting to the specific locale. Will this be changed or is there a workaround?

**Host Info**
OS: Ubuntu 19.10.1
Wiki.js version: 2.1.103
Database engine: MySQL 8.0.18

**Comment by NGPixel** [comment]
Per locale navigation is coming in 2.2

**Comment by Fruxh** [comment]
Any ETA for the RC?

**Comment by Syphdias** [comment]
ETA is March 2020 according to https://docs.requarks.io/releases

**Comment by Fruxh** [comment]
Thank you. I really appreciate your effort.
