### ISSUE TITLE
Keyboard Keys won't render

### ISSUE THREAD

**Issue by Fruxh** [Requarks/wiki#1451]
**Describe the bug**
Text containing the `<kbd>`tag`</kbd>` won't render as Keyboard Keys (as shown in the screenshots).

**Expected behavior**
The text should render as Keyboard Keys after saving the raw text in the editor.

**Screenshots**
Source/Editor (Markdown):
![image](https://user-images.githubusercontent.com/37774297/74091232-9191aa00-4ab5-11ea-823b-68de6f8efe44.png)

Visual Page:
![image](https://user-images.githubusercontent.com/37774297/74091081-dddbea80-4ab3-11ea-9cd7-d3354eeda090.png)

**Host Info**
- OS: Ubuntu 19.10.1
- Wiki.js version: 2.1.107
- Database engine: MySQL 8.0.18

**Comment by NGPixel** [comment]
Fixed by 90fbc62917196c3ba9e9bafe05fed337e066e874
