### ISSUE TITLE
Delete image bug

### ISSUE THREAD

**Issue by sbonaime** [Requarks/wiki#1458]
![Capture d’écran 2020-02-10 à 10-02-20 09 09 31](https://user-images.githubusercontent.com/750709/74132025-f1876e00-4be5-11ea-9027-cac5b36c130a.png)
**Describe the bug**
After confirming to delete an image in my case, I received a red error message

**To Reproduce**
1. Edit a Page
2. upload an image
3. click on the "..." on the right of the uploaded image 
4. click confirm click "delete". By the way, the question mark of the question should on the same line as the question
5. The error message pop up 
"Variable "$id" of non-null type "Int!" must not be null."

**Host Info (please complete the following information):**
Wikijs 2.1.107
Linux - Debian (stretch) 9.11 x64
Node.js 12.14.1
PostgreSQL 9.6.15

**Comment by sbonaime** [comment]
Now with 2.1.113, I have another popup window :
![Capture d’écran 2020-02-17 à 17-02-20 09 47 48](https://user-images.githubusercontent.com/750709/74637667-b26b9680-516a-11ea-9aa0-4f07a3727a73.png)

**Comment by JBauto** [comment]
I'm having the same issue, in version 2.1.113.

Wikijs 2.1.113
Linux - Official Docker image
Node.js 12.14.1
PostgreSQL 9.6.16

**Comment by sbonaime** [comment]
I am quite sure this bug is related to #1493. So I closed it
