### ISSUE TITLE
Task list items don't render correctly outside of preview

### ISSUE THREAD

**Issue by peregrinator** [Requarks/wiki#1463]
When using the task list style markdown `- [ ]` or `- [x]` items render correctly in the preview pane. But once the edits are saved and the regular page is viewed the html inputs that are created are just rendered as text.

**To Reproduce**
Using the lastest docker image with the `:beta` tag,
1. Add task list check box items to a markdown page
2. Save
3. View page

**Expected behavior**
The input items created should be rendered instead of displayed as text.

**Screenshots**
![image](https://user-images.githubusercontent.com/22108/74203034-1817ca00-4c23-11ea-9cf5-3c85758b2b37.png)
![image](https://user-images.githubusercontent.com/22108/74203066-31207b00-4c23-11ea-9572-8bf698434b29.png)

**Host Info (please complete the following information):**
 - OS: Docker
 - Wiki.js version: beta tag from docker hub [here](https://hub.docker.com/layers/requarks/wiki/beta/images/sha256-bb9a97b3a457b029cc2743192c1ea31a2b2824289aaab7c90e08ff8231d1ce52)
 - Database engine: postgres 11

**Comment by NGPixel** [comment]
Disable the `Sanitize HTML` option in Admin > Rendering > HTML > Security, then re-save the page.

**Comment by ibito** [comment]
Is @NGPixel 's comment a workaround? or it should render the actual checkbox instead of the html text? 🤔

**Comment by NGPixel** [comment]
it's a bug introduced with a new HTML sanitization feature introduced in 2.1.

**Comment by Naegolus** [comment]
Worked for me. Thx

**Comment by NGPixel** [comment]
Fixed by bacbe4f5430f9fdafbf4e31a2fa6b67877aa24f1
