### ISSUE TITLE
Any recommendation for wiki hosting????

### ISSUE THREAD

**Issue by han0320** [Requarks/wiki#1464]

**Comment by baer95** [comment]
You might want to have a look at https://wiki.js.org/, there's one-click installation options for digital ocean and aws :)

**Comment by han0320** [comment]
ok thank but the price is??

**Comment by baer95** [comment]
depends on the machine type you select to deploy your wiki on. digital ocean starts at $5/mo from what i saw, not sure about aws.

**Comment by NGPixel** [comment]
[DigitalOcean](https://m.do.co/c/5f7445bfa4d0) is the best and cheapest option for most people.
