### ISSUE TITLE
Page Title hidden under last author edit over Arabic locale 

### ISSUE THREAD

**Issue by MohamedAmrMahdy** [Requarks/wiki#1468]
**Describe the bug**
Page Title hidden under last author edit over Arabic locale 

**To Reproduce**
1. Go to Administration Area
2. Click on Locales
3. Click cloud icon next to Arabic to download locale
4. Set Arabic as default wiki language 
5. check any page title

**Screenshots**
![image](https://user-images.githubusercontent.com/36306971/74354321-d96d4580-4dc3-11ea-8c0b-b6411a0e539c.png)

**Comment by NGPixel** [comment]
This is fixed in upcoming 2.1
