### ISSUE TITLE
Giving write permissions to subpage requires granting write permissions to /edit/... and /create/... page

### ISSUE THREAD

**Issue by hopfenzapfen** [Requarks/wiki#147]
### Actual behavior
I just wanted gave one of my users write permissions to a subpage of my wiki. The wiki showed the `Edit` and `Create` button as expected, however, when trying to edit or create a page I got the `Permission denied` page. This kind of makes sense because I only granted read and write permissions to all paths that start `/subpage` and creating a pages opens `/create/subpage` which technically speaking is not allowed.

### Expected behavior
Even though this technically makes sense, I find it counter-intuitive to allow editing a page, but refuse access to the editing page of that page. A solution could be to add the `edit` or `create` to the end of the URL instead of to the beginning. F.e. `wiki.com/subpage/edit` instead of `wiki.com/edit/subpage`. So, when granting write permission to all paths that start with `/subpage`, the edit and create pages are automatically included.
It also not a major issue. But it is a bit strange.

### Steps to reproduce the behavior
Grant user write permissions to subpage and try editing that page as that user.

**Comment by NGPixel** [comment]
You don't need to explicitly allow /create or /edit, these should be stripped. This is a bug.
