### ISSUE TITLE
User verify email unauthorized

### ISSUE THREAD

**Issue by liscuate** [Requarks/wiki#1471]
**Describe the bug**
When I create a local account (enabled registration option) and get the verify now mail, when I click on the link in the mail I will get the screen "unauthorized"

**To Reproduce**
1. Register an account. 
2. Click the verification link in your mail. 
3. You get a page that says you are unauthorized 

**Expected behavior**
Verify account. 

**Screenshots**
https://cdn.discordapp.com/attachments/658023604633600012/677256219878096933/chrome_DxoTK9ube4.png

**Host Info (please complete the following information):**
 - OS: Windows 7
 - Wiki.js version: 2.0.12

**Comment by Smankusors** [comment]
Is this issue still happen on Wiki.js 2.4.x?

**Comment by liscuate** [comment]
I will check it out later this week.

**Comment by liscuate** [comment]
Looks like it works perfectly now, thanks!
