### ISSUE TITLE
S3 storage not compatible with Minio without s3ForcePathStyle option

### ISSUE THREAD

**Issue by raffraffraff** [Requarks/wiki#1472]
**Describe the bug**
S3 Storage target is not compatible with Minio, because it is not possible to set 's3ForcePathStyle'

**To Reproduce**
1. Go to 'Administration' -> 'Storage'
2. Click on 'Amazon S3'
3. Enter the details of your Minio S3 storage
4. Apply & Activate
5. See error

**Expected behavior**
The form for configuring S3 should include a setting for s3ForcePathStyle, so that it can be compatible with self-hosted Minio service.

** Actual behavior**
Status shows an error: 
```
Inaccessible host: `<bucket>.<endpoint>'. This service may not be available in the `<region>' region.
```

**Host Info (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04, Docker]
 - Wiki.js version: 2.0.12
 - Database engine: Postgres 12.1-1

**Comment by NGPixel** [comment]
Added S3 Generic storage module for 2.5, with extra options (including s3ForcePathStyle)

ca0708ea758c7ab36c338b0bee3da28964f28d9a
