### ISSUE TITLE
Error: Cannot read property 'isRTL' of undefined

### ISSUE THREAD

**Issue by Meti27** [Requarks/wiki#1474]
Os : `CentOS Linux 7 (Core)`
version : `Wiki.js 2.0.12`
database : `10.4.9-MariaDB`
node : `v12.13.0`
Hi , thanks for amazing wiki.
I installed a fresh wiki.js and trying to add persian language. its install the language successfully : 

![image](https://user-images.githubusercontent.com/11253027/74582524-3c342c00-4fd2-11ea-81a5-def5d47de178.png)

But when i choose `persian` and click on `Apply` button its says : 
```
Error: Cannot read property 'isRTL' of undefined
```

![image](https://user-images.githubusercontent.com/11253027/74582531-62f26280-4fd2-11ea-9cbf-77c0331d672a.png)

And after that if i refresh the page , nothing translated and no language is choosed

![image](https://user-images.githubusercontent.com/11253027/74582549-d005f800-4fd2-11ea-908b-56c9e3ab0026.png)

**Comment by NGPixel** [comment]
Upgrade to 2.1.113 and try again.

**Comment by Meti27** [comment]
I upgrade it to latest version , its still show me the same issue 

![wiki](https://user-images.githubusercontent.com/11253027/74584415-65ab8280-4fe7-11ea-993e-2e0af0f20556.gif)

**Comment by Meti27** [comment]
I upgrade to latest version but still show me same issue

![wikiii](https://user-images.githubusercontent.com/11253027/74584514-5416aa80-4fe8-11ea-894c-582f0661ab82.gif)

**Comment by Meti27** [comment]
I install last version `2.1.113` on windows :

![image](https://user-images.githubusercontent.com/11253027/74600077-25103f80-50a1-11ea-9bf7-0e6788d577dd.png)

its same problem

**Comment by NGPixel** [comment]
Do you have any error in the logs (the node process)? Looks like it fails to download the locale files properly.

**Comment by Meti27** [comment]
no errors occur when downloading  , just `Cannot read property 'isRTL' of undefined` when apply and the weird thing is that i get it now is the  problem is just for some languages not all of them i add spanish , frensh , and some other successfully .
for example for french :
![image](https://user-images.githubusercontent.com/11253027/74642341-0f297a00-5188-11ea-8cf4-e382ff20387a.png)

the logic that i get is its working for some languages thats near to 100% complete : 
![image](https://user-images.githubusercontent.com/11253027/74642431-36804700-5188-11ea-9b84-8dbfaebd94d7.png)

no other langs. i don't understand.

**Comment by sbonaime** [comment]
Maybe it is something like a nginx upload size limit ?

**Comment by NGPixel** [comment]
> Maybe it is something like a nginx upload size limit ?

Locale fetching does not go through nginx.

**Comment by Meti27** [comment]
it was a database charset issue , my database charset was `latin1` and when i download the languages that needed `utf8` charset for words like `فارسی` or `عربی`  it can't save it in `nativeName` in `locales` table in database .
Thanks for your cooperation.
