### ISSUE TITLE
LaTeX vector or square root not rendering

### ISSUE THREAD

**Issue by mattiasJohnson** [Requarks/wiki#1476]
**Describe the bug**
The LaTeX command `\vec a` should output a vector arrow over `a` in this case. The LaTeX command `\sqrt{3}` should output the square root sign. Both commands do not work.

**To Reproduce**
1. Insert the LaTeX `\vec a` or `\sqrt{3}`
2. View the page and notice the lack of vector arrow or square root sign.

**Expected behavior**
At [KaTeX.org](https://katex.org/) I get the following correct outputs
![image](https://user-images.githubusercontent.com/5561521/74588647-96e37d00-4ffe-11ea-87f0-f65366d5cc67.png)

**Screenshots**
My markdown
```
## Failed LaTeX Render
**Vector arrows not rendering**
Inline $\vec a$ example.
$$\vec a $$

**Square root not rendering**
Inline $\sqrt{3}$ example.
$$\sqrt{3}$$
```
The output at my wiki
![image](https://user-images.githubusercontent.com/5561521/74588680-df9b3600-4ffe-11ea-89a9-77f0659bdb34.png)

**Host Info (please complete the following information):**
 - OS: Ubuntu 18.04, Docker
 - Wiki.js version: 2.1.114 (although had the same problem on an earlier 2.1 release)
 - Database engine: postgres 11.6

**Additional context**
None.

**Comment by NGPixel** [comment]
Fixed by 830f51664c33daa7b79d58ee06af1a57abc7db06
