### ISSUE TITLE
http redirect to https

### ISSUE THREAD

**Issue by jicda18** [Requarks/wiki#1477]
**Question**
How can I configure automatically redirect of http port request to https port.

I see in your documentation for Let's Encrypt:

>  Once the initial verification is completed, all insecure requests made on the HTTP port will automatically be redirected to HTTPS.

but don't see how to do it used Custom Certificate

**Comment by NGPixel** [comment]
You need to turn it on under **Admin** > **SSL**.

I'll update the docs.

**Comment by jicda18** [comment]
Thank

**Comment by dev-sngy** [comment]
How do you fix the problem when you've enabled it and now it's constantly return 500 error?
Or in other words, How do I disable it without being able to access to GUI (because of the redirection and faulty SSL Cert)?

**Comment by dev-sngy** [comment]
> How do you fix the problem when you've enabled it and now it's constantly return 500 error?
> Or in other words, How do I disable it without being able to access to GUI (because of the redirection and faulty SSL Cert)?

I was able to fix this by entering the ip and port to the server and than changing the value from GUI. I assume, alternatively, you can change value in the database >> table settings > server > { sslRedir: true } but I haven't checked...
