### ISSUE TITLE
HTML button elements display code as text rather than rendering element

### ISSUE THREAD

**Issue by JakeAdmire** [Requarks/wiki#1482]
**Describe the bug**
HTML `button` elements display code as text rather than rendering element.

**To Reproduce**
1. Click on 'New Page'.
2. Choose the 'Raw HTML Code' editor.
3. Code a `<button></button>` element.
4. 'Save' & 'Close' the editor.

**Expected behavior**
Entering an HTML `button` element should render a `button`.

**Screenshots**
<img src="https://user-images.githubusercontent.com/44077214/74607389-d6a97380-5095-11ea-8d58-256cb58503f3.png">

> Entering the proper code for a basic `button` element.

<img src="https://user-images.githubusercontent.com/44077214/74607409-fa6cb980-5095-11ea-9aea-015ea74f6855.png">

> The `button` falsely rendered as text.

**Host Info (please complete the following information):**
 - OS: Heroku [Linux - Alpine Linux (linux) 3.11.3 x64]
 - Wiki.js version: 2.1.113
 - Database engine: Heroku Postgres

**Comment by NGPixel** [comment]
https://docs.requarks.io/en/troubleshooting#some-html-tags-are-rendered-as-plain-text
