### ISSUE TITLE
Code block issue in the preview panel in markdown

### ISSUE THREAD

**Issue by sbonaime** [Requarks/wiki#1484]
2.1.107 Linux - Debian (stretch) 9.11 x64 on macos
**Describe the bug**
With a markdown page and a code block. After closing or opening the preview panel in editor mode, the code block is very strange

**To Reproduce**
1) edit a markdown 
page with a simple code block like
````
```
Lorem 
```
````
![Capture d’écran 2020-02-17 à 17-02-20 09 38 22](https://user-images.githubusercontent.com/750709/74636927-49cfea00-5169-11ea-90ee-5cca0571a9da.png)

2) close the preview panel
3) open the preview panel
Now, the code block preview is not the correct 
![Capture d’écran 2020-02-17 à 17-02-20 09 38 29](https://user-images.githubusercontent.com/750709/74636939-4f2d3480-5169-11ea-8da6-ef51eefeb63a.png)

**Comment by schizophrene** [comment]
2.1.113 Docker image on Debian 10 here, and the same.

* Before hide/show preview : 
![image](https://user-images.githubusercontent.com/22858496/74658938-a1834b00-5193-11ea-9d5a-7a8fce2fd760.png)

* After : 
![image](https://user-images.githubusercontent.com/22858496/74659061-e7401380-5193-11ea-91d0-4adc1f113791.png)

Some tags disappear during the hide/show.

**Comment by NGPixel** [comment]
Fixed by bf9c6dda1c6cc8ba9760ce9d3194e53c16701ed0
