### ISSUE TITLE
Re-assign user content to another account when deleting a user

### ISSUE THREAD

**Issue by sbonaime** [Requarks/wiki#1486]
Cannot delete user. It is a different issue as #1309 (which maybe could be closed with latest released...) 

When I want to delete a user, I have the error
"Cannot delete user because of content relational constraints." 
I understand that I can't delete this user because he created some pages or made some modifications. Could it be possible to author the changes to "anonymous" for instance and force the delete  ?

**Comment by virtualcharlotte** [comment]
+1, currently switching users over from local to another authentication strategy and I'd like to purge the old local accounts rather than just deactivate them

**Comment by sbonaime** [comment]
@NGPixel  Does 1f9e5b3fd0e8329189f1eb9615465e78f42a98c2  is a fix for this issue ?

**Comment by NGPixel** [comment]
Yes, this was added in 2.4.
