### ISSUE TITLE
RTL mixed with english works only on edit mode

### ISSUE THREAD

**Issue by LtrDan** [Requarks/wiki#1491]
Hey:)
When I Mix 2 languages on RTL (edit mode) - looks fine
after saving the document - display mode looks opposite to edit mode:
- working with chrome on mac - Right Click -> Writing Direction -> Right to Left
attached screenshots

![Screen Shot 2020-02-18 at 1 57 56 PM](https://user-images.githubusercontent.com/10274719/74734549-75c99900-5257-11ea-8ffa-41c23fc38bb2.png)
![Screen Shot 2020-02-18 at 1 58 13 PM](https://user-images.githubusercontent.com/10274719/74734568-7d893d80-5257-11ea-801b-8dd17ac76336.png)

 - OS:  Docker
 - Wiki.js version: 2.1.113
 - Database engine: postgres

Thanks, Dan

**Comment by NGPixel** [comment]
RTL is based on the selected language, not on the writing direction selected from the right-click menu.

In the admin area, under Locales, select the languages you need. Then create a new page in the language you want and that page (and the editor) will work in the selected language writing direction.

**Comment by AzamAhmadloo** [comment]
Hi 
I'm using Persian language and need to RTL direction in editor But in editor page the direction is LRT and I can't change it to RTL.
Saved pages have correct direction but editor doesn't have correct direction. 


![wiki js](https://user-images.githubusercontent.com/51315380/76139278-9e2d0200-6063-11ea-8c62-0bbb37ee7258.png)

I created new page and new link but I cannot see all links in home page!.
