### ISSUE TITLE
Font Awesome 5 Icons are not displayed correctly in Navigation admin on 2.1.113

### ISSUE THREAD

**Issue by mattbryce** [Requarks/wiki#1495]
Describe the bug
Same issue as #1460 which was fixed by 9384ce1 but the icons are not displayed correctly in the admin navigation area

To Reproduce
Displayed on Navigation bar in admin area

Expected behavior
The icons should not be cropped or obscured.

Screenshots
image
![image](https://user-images.githubusercontent.com/11202857/74753078-8124c080-5267-11ea-82f6-08ddca02edae.png)

Host Info (please complete the following information):

OS: Windows_NT (win32) 10.0.14393 x64
Wiki.js version: 2.1.107
Database engine: mysql 8.0.11
Additional context
None

**Comment by NGPixel** [comment]
This is already fixed in latest version.
