### ISSUE TITLE
Multiple authentication methods create multiple accounts

### ISSUE THREAD

**Issue by CorruptComputer** [Requarks/wiki#1497]
**Question**
I setup Wiki.js today and added both GitHub and Discord Authentication methods, however its currently not possible (as far as I can tell) to combine these to one account. So a user would be able to hook their local account to these for more convenient login. 

I looked for issues here but didn't find much about this, but is something like that possible?

**Host Info (please complete the following information):**
OS: Debian 10, Docker
Wiki.js version: 2.1.113
Database engine: PostgreSQL 12.2

**Comment by NGPixel** [comment]
At the moment, you would need to use a service to Auth0 to link these accounts.

Feel free to submit a feature request on wiki.js.org/feedback

**Comment by kyawkyawsoezhu** [comment]
I also have the same issue, is there anyway to combine Local and Google authentication as a single account without using Auth0.

**Comment by NGPixel** [comment]
@kyawkyawsoezhu 
Have you read my previous reply?

**Comment by kyawkyawsoezhu** [comment]
@NGPixel, yes i read your comment, that's way i said **without using Auth0**

and as i understand  even if I use Auth0, there still be at least 2 account because can't disable `Local Strategy`.

**Comment by CorruptComputer** [comment]
I agree with @kyawkyawsoezhu and don't believe this should be closed. This is a real issue that you can't link the accounts together. This isn't simply a feature request, since this is missing core functionality, and should be considered a bug.

**Comment by NGPixel** [comment]
This is definitely not a bug. Just because it's important for you doesn't make it a "bug". Submit a feature request like suggested.
