### ISSUE TITLE
Table rendering issue 

### ISSUE THREAD

**Issue by andrelec1** [requarks/wiki#1500]
**Describe the bug**
Table missing horizontal line in redering 

**To Reproduce**
Create a page with the wysiwyg editor ( ckeditor ) 
Add simple table in the documentation... 

**Expected behavior**
Same render as in the editor 

**Screenshots**
( left consultation mode, right editing mode ) 
![image](https://user-images.githubusercontent.com/3273204/74825464-458f0280-530a-11ea-9cab-f154944057de.png)

**Host Info (please complete the following information):**
 - OS: Ubuntu 18.04
 - Wiki.js version: 2.1.113
 - Database engine: sqlite

**Comment by Motz31** [comment]
This Issues seems to have already been fixed. I tested it in Version 2.5.577 and it renders like expected.
