### ISSUE TITLE
Help with katex math plugin

### ISSUE THREAD

**Issue by justinacolmena** [Requarks/wiki#1502]
**Question**
TeX math is not displaying.

x=5

![Screenshot_wiki_js_md](https://user-images.githubusercontent.com/32494761/74865224-4a998500-52fd-11ea-8ca5-cc26446bd721.png)

**Host Info (please complete the following information):**
OS: Fedora Core 31
node v12.15.0
Wiki.js 2.1.113
PostgreSQL 11.6

**Comment by justinacolmena** [comment]
There is something with the rendering options at the time the page is created. I created a new page, and the math equation renders just fine with katex, but now the original page is rendering as html code rather than markdown.

![Screenshot_math_wiki_js](https://user-images.githubusercontent.com/32494761/74986150-76903580-53e5-11ea-9f5c-53b2eeb48b1f.png)

**Comment by NGPixel** [comment]
Please provide an example text content, not just a screenshot.
