### ISSUE TITLE
SQLITE_ERROR: too many SQL variables

### ISSUE THREAD

**Issue by EvanCarroll** [Requarks/wiki#1503]
**Describe the bug**
When rebuilding page tree, with SQL Lite I get an error.

**To Reproduce**
1. Import from Wikijs 1.
2. Start up and you'll get error
3. Go to utilities and then to Rebuild Page Tree (and you'll get the same error)

**Expected behavior**
No error

**Screenshots**
Current I'm getting an error that says 

```
insert into pageTree (depth, id, isFolder isPrivate, localeCode, pageId, parent, path, privateNS, title)
select 1 as depth, false as isfolder, 0 as isPrivate, en as localCode, 1 as pageID, null as parent, .....
Union all select ...
union all select ...
```
And so on forever, followed by,

    SQLITE_ERROR: too many SQL variables

This is not a good a way to create a select statement. I believe that you should follow the form of 

    INSERT INTO table ( col1, col2 ) VALUES (1,2), (2,3);

The SQL statement generated I believe is too massive as-is.

**Comment by NGPixel** [comment]
Statements are generated by Knex, not by hand. The issue is more likely related to the chunks size used to speed up inserts.

Current chunks of `100` should be lowered to `10` when using sqlite.

**Comment by EvanCarroll** [comment]
http://knexjs.org/#Utility-BatchInsert
I'm guessing the problem here is that we're not using batchinsert for the tree at all, and if we were we would be able to change this variable for different dbs?
