### ISSUE TITLE
Cannot navigate to 'guide' via documentation wiki breadcrumb

### ISSUE THREAD

**Issue by graft** [Requarks/wiki#1507]
While reading https://docs.requarks.io/guide/intro I find a breadcrumb at the top of the page, "home > guide > intro" - clicking on "guide" here takes me to "https://docs.requarks.io/en/guide" (rather than https://docs.requarks.io/guide as I might expect), which results in a 404. Neither is https://docs.requarks.io/guide present. However, "guide" in the breadcrumb is a navigable link, indicating this 404 is an error.

**Comment by NGPixel** [comment]
The page simply doesn't exist yet. Not a bug.
