### ISSUE TITLE
Edit document and add new tags

### ISSUE THREAD

**Issue by therealrobster** [Requarks/wiki#1509]
**Question**
Currently I can only seem to edit a document, but I can't add new tags.  For example I updated my "networking" document with my server info but can't add a "server" tag.

**Host Info (please complete the following information):**
OS: Docker]
Wiki.js version: 2.1.113
Database engine: postgres 11.7

**Comment by therealrobster** [comment]
I'm a goose, I found it.  Feel free to close and sorry for the trouble.

**Comment by cabrinoob** [comment]
I'am searching too ^^ Can you tell me how to update tags of a page please?

**Comment by therealrobster** [comment]
> I'am searching too ^^ Can you tell me how to update tags of a page please?

Be logged in.
View Document.
Edit document at bottom of screen.
Click Page at top of screen.
In the page properties, add new tags.

Hope that helps

**Comment by cabrinoob** [comment]
@therealrobster : Ok, it was in front of me, but did not see it :)

Thank you
