### ISSUE TITLE
Tree view navigation in wiki.js v2.1.113

### ISSUE THREAD

**Issue by ilshatufa** [Requarks/wiki#1511]
**Question**
In the wiki.js v1, the sidebar had tree navigation. Tell me how i can make tree view navigation in the wiki.js v2.1.113?

**Host Info (please complete the following information):**
OS: Ubuntu 18.04, Docker
Wiki.js version: v2.1.113
Database engine: postgres 12.2

**Comment by NGPixel** [comment]
Tree navigation is coming in future release 2.2
