### ISSUE TITLE
Favico 

### ISSUE THREAD

**Issue by beraybentesen** [Requarks/wiki#1512]
**Question**
How do I set favico ? Thanks,

**Host Info (please complete the following information):**
Kubernetes - Docker

**Comment by NGPixel** [comment]
It's not possible to change the favicon at the moment. Coming in a future update.

**Comment by justinacolmena** [comment]
I don't mean to barge in or interrupt; these are simply the favicons that come pre-bundled with the software: just browse in the folder after it is unpacked. If you don't like them, you edit them or preferably create your own in the drawing or paint program of your choice, brand your website with your own artwork.
```
$ ls -C1 wiki/assets/favicon*
wiki/assets/favicon.ico

wiki/assets/favicons:
android-chrome-192x192.png
android-chrome-256x256.png
apple-touch-icon.png
browserconfig.xml
favicon-16x16.png
favicon-32x32.png
mstile-150x150.png
safari-pinned-tab.svg
```
Some browsers always fetch "/favicon.ico" and expect to find that file (as it is served) at the root of your domain, or sometimes you can add a "link" in the html head. There seem to be a few different conventions for favicons.
```
<link rel="icon" type="image/png" href="http://example.com/favicon.png" />
```
There is a place to inject code similar to this in the administration area.

**Comment by beraybentesen** [comment]
@justinacolmena head injection simply worked. Thank you for reminding the code injection.

**Comment by beraybentesen** [comment]
@justinacolmena Would you mind to help me to also change the background color of left menu (the blue one) ? Thanks,

**Comment by maka1000** [comment]
#app .primary,
#app nav {
  background-color: #COLORCODE!important;
  border-color: #COLORCODE!important

**Comment by maka1000** [comment]
Favicon change in backend +1
