### ISSUE TITLE
New installation, cannot login

### ISSUE THREAD

**Issue by jam88881** [Requarks/wiki#1514]
I just completed a fresh install (postgreSQL) following the instructions [here](https://docs.requarks.io/install/windows). 

I browse to http://localhost:3000/, see a button that says "+ CREATE HOME PAGE"

I get to the url http://localhost:3000/e/en/home, it says "Unauthorized you cannot create the page"

I click on the button under Unauthorized, "LOGIN AS..."

Well, I never created a login. I didn't see anything on the instructions about creating a login. I tried the postgreSQL database login but that doesn't work. I have no idea how to login or create an account. 

I want to create the home page but I can't do that if I can't login. What should I do? Did I miss something? 

![Capture](https://user-images.githubusercontent.com/13112498/75063511-ed870600-5499-11ea-9642-aed26fc46422.PNG)

**Comment by NGPixel** [comment]
You're prompted to enter an email and password for the root administrator account when you load the site for the first time. Use that user/pass to login.

**Comment by jam88881** [comment]
I never hit that prompt. Will uninstall both wikijs and postgres and try again.

**Comment by jam88881** [comment]
I just went through a clean install. Here is my output from that install. After getting this I browse to localhost:3000, I get to the same thing as in my original post. 

Is there a file I can just open in notepad and set the username and password? 
[output.txt](https://github.com/Requarks/wiki/files/4245073/output.txt)

**Comment by NGPixel** [comment]
This is not the setup process, which means you're connecting to a DB which is already setup. You need to drop the DB and create a new one.

**Comment by jam88881** [comment]
Aha! thank you!
I had though uninstalling postgres would wipe out that old database... now I know.
![Capture](https://user-images.githubusercontent.com/13112498/75185114-62f11180-56fa-11ea-8170-5ba8e496cd29.PNG)
