### ISSUE TITLE
Delete Asset returns error "Variable "$id" of non-null type "Int!" must not be null."

### ISSUE THREAD

**Issue by alesak** [Requarks/wiki#1518]
Editing page using CKE Editor. Deleting assets fail with error unless user select the Asset row first before using context menu and selecting "Delete"

**To Reproduce**
1. Create page and use Wysiwyg editor
2. Click on icon for adding Asset in CKE editor toolbar and Upload some image
3. Click on <...> at the end of image row and select "Delete" (if the row with image was selected delete will succeed)

**Expected behavior**
Image should be deleted without error

 - OS: linux
 - Wiki.js version: 2.1.113
 - Database engine: mysql

**Comment by sbonaime** [comment]
It is more or less the same issue as #1493

**Comment by NGPixel** [comment]
Fixed in 2.3.77
