### ISSUE TITLE
Images caption has incorrect html markup

### ISSUE THREAD

**Issue by alesak** [Requarks/wiki#1519]
When using Wysiwyg based pages. Image captions html are is rendered in readable form. It worked in previous versions.

**To Reproduce**
1. Insert image into page
2. Click on inserted image and add some caption text to the input bellow image
3. Save Page
Image will have caption html rendered after itself in readable form

**Expected behavior**
Caption rendered under image as in previous versions

**Screenshots**
![image](https://user-images.githubusercontent.com/602909/75113795-e08a3280-56a4-11ea-9786-3cb885865173.png)

**Host Info (please complete the following information):**
 - OS: linux
 - Wiki.js version: 2.1.113
 - Database engine: mysql

**Comment by NGPixel** [comment]
Fixed by fba9e0058fdeaef3ebbd1ba46ffd59625922a7b6.

Workaround: **Admin** > **Rendering** > **HTML** > **Security**: Disable the **Sanitize HTML** option.
