### ISSUE TITLE
Gitlab Authentication - http Callback URL in Docker

### ISSUE THREAD

**Issue by MarauderXtreme** [Requarks/wiki#1523]
I am running the current wiki.js version in a docker container.
I have to use the custom certificate provider because I need to do dns-01 with certbot on the docker host.

I want to use Gitlab as authentication provider and have set  up everything so far.
The problem now is that when I enable Redirect to HTTPS the URLs don't change to https. (see screenshots)
Probably the same problem is for all providers as wiki js shows for everything non-https URLs.

Authentication via Gitlab works as long as I deactivate the redirect but if enabled either the callback url for Gitlab is not accepted or wiki.js shows an invalid error.

1. Obtain certificate and mount it into container
2. Configure wiki.js to serve SSL and give paths to certificate and key
3. Goto Administration -> SSL
4. Click on Turn On with Redirect to HTTPS
5. Goto Administration -> Authentication -> Gitlab
6. Paste ClientID, ClientSecret and BaseURL
7. Enable Gitlab Authentication (additional allow self-registration)
8. Save everything

**Expected behavior**
Working Authentication through Gitlab with Redirect to HTTPS enabled and custom certificate provider.

**Screenshots**
![Redirect to HTTPS](https://user-images.githubusercontent.com/6439489/75155181-c174ba80-570f-11ea-93dc-457d7dd8ec40.png)
![Gitlab Auth Configuration Reference](https://user-images.githubusercontent.com/6439489/75155239-e2d5a680-570f-11ea-8e24-436482bf8c74.png)

**Host Info:**
 - OS: Docker (Compose)
 - Wiki.js version: 2.1.113
 - Database engine: postgres 11.7

**Additional context**
I suspect that the issue could be linked to the custom certificate provider.

**Comment by NGPixel** [comment]
You need to change your **Site URL**, under **General**.

Once this is changed, you should see the proper URLs in **Authentication**.

**Comment by MarauderXtreme** [comment]
Thank you!
That was the problem.

I am sorry for bothering you with that easy thing.
