### ISSUE TITLE
No way to display all pages in sidebar??? Is this behavior on purpose?

### ISSUE THREAD

**Issue by DigitalLeaves** [Requarks/wiki#1526]
**Question**
Maybe this is a stupid question, but I can't seem to find a way to display all pages in the sidebar. I cannot think of a reason why this behavior is not desirable by default. If all my users (which are not that IT savvy after all) have to, after creating a new page, try to link it in the sidebar, I will be having more questions and time wasted than if I create the pages myself (seriously).

Been trying for half an hour unsuccessfully, is there a way to add the tree structure of pages in the sidebar at the left automatically? If not, this is a feature that I would say is essential for any Wiki.

Maybe I am doing something wrong.
Just installed the first version today, 2.1.113.

**Host Info (please complete the following information):**
OS: Debian linux on VPS
Wiki.js version:2.1.113 (how do I get this from current installation? interesting question... had to look at the website).
Database engine: mariaDb

**Comment by NGPixel** [comment]
This is coming in update 2.2 next month.

The wiki is meant to be used in the style of wikipedia where you link pages together. However not everybody wants to use it this way, which is why the option to have a tree view navigation is being added.

**Comment by blacklist-arcc** [comment]
I am using the 2.2 beta but cannot see anything about this feature. Is the code embedded in the 2.2 beta release?

**Comment by DigitalLeaves** [comment]
Hello, any news about this? It's April already, so I was wondering if this feature is finally included or not? If not, is there a way you can give us a hint on how to do it? 

Please consider the most common scenario for an organization wiki, users don't have the technical knowledge or skills to add the pages manually (including paths) to the sidebar... it is a success if you convince them to enter and write things...

**Comment by NGPixel** [comment]
It's coming in 2.3.

The sidebar is not meant to include all pages. You're supposed to add only links to major sections. Then link to other pages from within the content (wikipedia style).
