### ISSUE TITLE
Alternate locale version

### ISSUE THREAD

**Issue by toneti85** [Requarks/wiki#1527]
**Question**
I would like to create an alternate locale version of a page. Do I have to create it manually? What is it downloading localization for then?

![image](https://user-images.githubusercontent.com/33319360/75270510-fb6ebb00-57fa-11ea-8f5a-121c01ed9b20.png)

**Host Info (please complete the following information):**
OS: Windows_NT (win32) 10.0.17763 x64
Wiki.js version: 2.1.113
Database engine: postgres 12.1

**Comment by NGPixel** [comment]
The locales are for the UI.

To create an alternate localized version of a page:
1. In **Admin** > **Locale**, download all locales you want to use.
2. Enable **Multilingual Namespaces** and set the list of languages you want to allow.
3. Go the page (in english, or whichever base language you use)
4. Click the locale menu (top-right of the page) and select another language.
5. You'll get a "This page doesn't exist yet" with the option to create it.

Once that version is created, you can easily switch between locales using the menu.
