### ISSUE TITLE
Markdown / Page length longer than 1800 lines result in JSON errors

### ISSUE THREAD

**Issue by t3hpaul** [Requarks/wiki#1529]
### Actual behavior
Having migrated from 1.x, when attempting to edit pages attempting to edit pages longer than about 1800 lines, an error condition presents itself then hangs the processing loading window:
![Screenshot from 2020-02-25 15-17-00](https://user-images.githubusercontent.com/1163957/75288392-e5a0cc00-57e1-11ea-992f-0f3e50c2ca68.png)

The /graphql endpoint is returning a 413 error on save, per below:

Headers:
```
Request URL:http://<<IP>>:3000/graphql
Request Method:POST
Remote Address:192.168.3.211:3000
Status Code: 413
Version:HTTP/1.1
```
Returned page:

`Oops, something went wrong...request entity too large`

### Expected behavior

Saving of reasonably sized files doesn't fail.

### Steps to reproduce the behavior

Attempt to save a text-heavy document with about 1900 lines.

**Comment by NGPixel** [comment]
This is already fixed in upcoming 2.2

**Comment by t3hpaul** [comment]
Thanks! is there a workaround in the interim?

**Comment by NGPixel** [comment]
You can apply the specific patch directly to the file:
https://github.com/Requarks/wiki/commit/de4d407fdc001989a6ea859315bbd74b3c2bd680

**Comment by t3hpaul** [comment]
Applied the patch and that worked. Thank you.
