### ISSUE TITLE
Unable to create a page that contains numbers delimited with periods

### ISSUE THREAD

**Issue by Hasztagg** [Requarks/wiki#1530]
**Describe the bug**
When trying to access a page that contains a version number delimited with periods, for example `/foo/bar/5.0.0`, `/foo/5.0` or `/test-5.0.0-test`, Wiki.js only shows a "Not Found" page. Attempting to create such page results in `Page path cannot contains illegal characters.` error. This behavior wasn't expected, since there is no mention of periods as illegal characters in path in the docs: https://docs.requarks.io/en/guide/pages or here: https://docs.requarks.io/guide/structure.

**To Reproduce**
1. Open one of the paths: http://`<wiki>`/foo/bar/5.0.0, http://`<wiki>`/foo/5.0 or http://`<wiki>`/test-5.0.0-test
2. `Not Found` is shown instead of a proper 404 error page
3. Create new page using the *New page* button on any page and put `/5.0.0` as path.
4. Address bar shows proper page address but in *Path* window it's `/5.0`
5. Attempting to *Create* that page will result in `Page path cannot contains illegal characters.` error.

**Expected behavior**
Either docs should mention that use of periods is not possible or the page should be created as it was typed in.

**Host Info:**
 - OS: Windows 10, Chrome 80.0.3987.122
 - Wiki.js version: 2.1.113
 - Database engine: PostgreSQL 11.5

**Comment by NGPixel** [comment]
Docs have been updated to mention that periods, spaces and URL-unsafe characters are not allowed in paths.

**Comment by kfiresmith** [comment]
The approach here seems much less useful, from a user perspective, than simply adopting URL encoding like most other platforms, eg Mediawiki.
