### ISSUE TITLE
Login with username not possible (local auth)

### ISSUE THREAD

**Issue by sub0ne** [Requarks/wiki#1532]
**Describe the bug**
Login mask states you can login with username but only email-address is working

**To Reproduce**
1. Create user with username and email address
2. Try to log in with username
3. Login fails

**Expected behavior**
Login with username should be possible

**Host Info
 - OS: Ubuntu 18.04 LTS
 - Wiki.js version: 2.1.113
 - mysql 5.7

**Comment by NGPixel** [comment]
There's no username when using local accounts... only email. I think you're confusing with "Name" which is the display name, not a username.

Usernames are strictly for LDAP connections only. The wording will be changed in 2.2 to only show "Username" when selecting that strategy.
