### ISSUE TITLE
IFRAME HTML rendered as text instead of a tag

### ISSUE THREAD

**Issue by alexksso** [Requarks/wiki#1539]
**Describe the bug**
When creating a page with markdown and adding as html code an iframe, the iframe will render properly in the preview pane but will be rendered as text on the final page.

**To Reproduce**
1. Create a new page
2. Select markdown
3. paste the following iframe code:
```
<iframe width="560" height="315" src="https://www.youtube.com/embed/EbrVR_X9Ra8" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
```
4. Confirm you can play the meme video in the preview pane
5. Save and close editor
6. Confirm the video is not there anymore

**Expected behavior**
HTML tags should render properly when settings allow it
![image](https://user-images.githubusercontent.com/485530/75407793-b7e28280-58c8-11ea-8bde-f1f80243a0d1.png)

**Host Info (please complete the following information):**
 - OS: Docker
 - Wiki.js version:2.1.113
 - Database engine: PGSQL (AWS)

**Comment by NGPixel** [comment]
https://docs.requarks.io/troubleshooting#some-html-tags-are-rendered-as-plain-text

**Comment by alexksso** [comment]
@NGPixel thanks ! I looked at the options but did not expect to toggle 2 options to get the html tags to work :)

**Comment by NGPixel** [comment]
The one you mentioned only concerns Markdown specifically. The HTML rendering pipeline is still applied afterwards.
