### ISSUE TITLE
problem of git version checking

### ISSUE THREAD

**Issue by danny-idingo** [Requarks/wiki#154]
I am having the same problem as https://github.com/Requarks/wiki/issues/56.

wiki.js@1.0.0-beta.12.13 

git --version
git version 2.8.1

**Comment by NGPixel** [comment]
Fixed for Beta 13. (9ee940f984f05abe86aea16a2b043ec42dbef8c9)

**Comment by danny-idingo** [comment]
any idea when beta 13 will be released?

**Comment by NGPixel** [comment]
It is now available.
