### ISSUE TITLE
Sets authentication provider as default

### ISSUE THREAD

**Issue by rgavilan** [Requarks/wiki#1541]
**Bug description**
When configure an authentication provider, i.e. LDAP, is not possible to set it as the default login method. Anytime the users try to login, it is necessary to select "LDAP / Active Directory". That is because by default "local" is selected.

Previously, we have been using wiki.js 1.x with ldap configuration and users, both local and ldap, can authenticate without selecting the authentication strategy

**To Reproduce**
1. Configure LDAP / Active Directory Authentication strategy
2. Go to login page
3. Try to login with LDAP account
4. An error appear "Invalid email / username or password.", because it is trying to perform login via "local" strategy only

**Expected behavior**
I expect to perform login via LDAP by default or better, users could authenticate without selecting the authentication strategy

**Host Info:**
 - OS: Docker
 - Wiki.js version: 2.1.113
 - Database engine: postgres:12.2

**Comment by NGPixel** [comment]
https://requarks.canny.io/wiki/p/change-order-of-login-options

**Comment by toneti85** [comment]
Hi, it was marked as planned, but was it developed finally? I haven't found the way to do it

thx

**Comment by peteruithoven** [comment]
It's still upcoming with version 2.5, these seem good places to check up on: 
https://docs.requarks.io/releases#upcoming-25
https://twitter.com/requarks/status/1278519017456746498

**Comment by peteruithoven** [comment]
You can now change the order in the Authentication settings. And also hide local database login or even bypass the login page in the Security settings. 

![Screenshot from 2020-09-09 14-50-51@2x](https://user-images.githubusercontent.com/523210/92601264-e3e5b400-f2ac-11ea-98a1-502a51f04238.png)

**Comment by toneti85** [comment]
Hello 

I have just upgraded to last version but I cannot see this setting at authentication menu.

![image](https://user-images.githubusercontent.com/33319360/92615168-1ac3c600-f2bd-11ea-89d5-028c3c87b505.png)
![image](https://user-images.githubusercontent.com/33319360/92615240-2e6f2c80-f2bd-11ea-9f30-ed0f6a9b4052.png)

could you tell me where can I find it?

thx
