### ISSUE TITLE
Image caption showing tag <figcaption>

### ISSUE THREAD

**Issue by raiffsaid** [Requarks/wiki#1542]
Hello there! After the update to the latest stable version, after editing some pages, the image caption broke, showing the text inside the figcaption tag
### Actual behavior
Image caption showing tag figcaption
### Expected behavior
Show correct text style for image caption
### Steps to reproduce the behavior
1 - Upload an asset to the page and enter an image caption to it; or
2 - Edit an existing page.

**Comment by NGPixel** [comment]
https://docs.requarks.io/troubleshooting#some-html-tags-are-rendered-as-plain-text
