### ISSUE TITLE
Custom locale file not used in development mode

### ISSUE THREAD

**Issue by twastvedt** [Requarks/wiki#1546]
**Describe the bug**
I've followed the directions here to add custom locale resources in development mode: https://docs.requarks.io/en/dev/translations#development-mode
If I set a breakpoint in server/core/localization.js at `loadLocale`, I can see the file getting loaded, and if I run `this.engine.getResource("en", "editor", "props.customName")` at the end of that method, it returns the correct text. However, in the app I just see "props.customName".

**To Reproduce**
1. Run Wiki.js in Docker in development mode.
2. Add a custom locale file at /server/locales/en.yml.
3. Overwrite an existing resource or create a new one and add it to a view.
4. Navigate to page where resource is shown.

**Expected behavior**
When resource is shown it should show the text from the custom en.yml file.

**Host Info (please complete the following information):**
 - OS: Windows 10 (WSL), Docker
 - Wiki.js version: latest master
 - Database engine: postgres 9.6.17

**Comment by NGPixel** [comment]
You're referring to client-side code or server-side?

Client-side: your issue is most likely browser caching. From the devtools, clear the local storage then reload the page. This will force refresh the locale files.

**Comment by twastvedt** [comment]
Client side, and that did it. Sorry, I thought the "Flush Client-Side Locale Cache" in the admin settings did something similar. Thanks!

**Comment by NGPixel** [comment]
It's supposed to do that, but it's broken for some reason. ;)
