### ISSUE TITLE
Configure Page still says Minimum is Node v4.6.0

### ISSUE THREAD

**Issue by andydevs** [Requarks/wiki#155]
### Actual behavior

![screenshot 48](https://user-images.githubusercontent.com/15643511/27939851-6d3a6198-6295-11e7-9aa9-37f64abd70b4.png)

### Expected behavior

Should be v6.x.x

### Steps to reproduce the behavior

Run npm install and open configure page

**Comment by NGPixel** [comment]
Fixed for Beta 13. (8c4772a19de7699b59850d6bf4505c0da16aacc1)
