### ISSUE TITLE
Unable to add iFrame itens

### ISSUE THREAD

**Issue by failover88** [Requarks/wiki#1550]
**Question**
How can I add iframe items? 

I have already disabled that option in Administration>General 'Block iFrame embedding' but didnt happean. I have fully restarted (OS restart) wiki.js but nothing changed.

**Host Info (please complete the following information):**
OS: Debian 9.12
Wiki.js version: 9.6.17 
Database engine: posgreSQL 2.1.113

**Comment by Aranya-Emil** [comment]
+1 on this one, seems like a bug. oframe works fine in Markdown preview: https://www.screencast.com/t/Kw9G0yTB, but not on live page: https://www.screencast.com/t/UKt8dZ6p1Y. Bug @NGPixel ?

**Comment by newfoundfreedom** [comment]
Hey guys - I asked this question just recently as I too would really like to utilize embed videos that I've created for my team.  Developer NGPixel got back to me to let me know that it is not a bug, its just not in the render pipeline.  Its a planned feature but I got the impression its not no the short-list.

**Comment by eeshugerman** [comment]
I'm able to use iframes without issue in HTML and Markdown pages. Note that you need to disable HTML sanitization under Administration -> Rendering -> (HTML -> HTML) -> Security.

@newfoundfreedom maybe NGPixel was talking about the WYSIWYG editor? Idk

@failover88, the admin setting you mentioned blocks _other_ websites from embedding content _from_ your wiki, not the other way around.

**Comment by failover88** [comment]
> I'm able to use iframes without issue in HTML and Markdown pages. Note that you first need to disable HTML sanitization under Administration -> Rendering -> (HTML -> HTML) -> Security.

Thanks, now I am able to add external iframes!
