### ISSUE TITLE
413 Payload Too Large When Saving Page

### ISSUE THREAD

**Issue by Marco77577** [Requarks/wiki#1552]
**Describe the bug**
When saving a very long page (using Markdown editor), a red toast is displayed saying:
"Network error: Unexpected token < in JSON at position 0"

When opening the developer console, there is a "413 Payload Too Large" error caused by GraphQL.

Is this a Wiki issue, or is it a server configuration issue? If the problem is with my server, do you know what I need to adjust?

**To Reproduce**
1. Write very long document.
2. Try to save it.

**Expected behavior**
It should be possible to save the page no matter the length of the request.

**Screenshots**

**Host Info (please complete the following information):**
 - OS: Docker
 - Wiki.js version: 2.1.113
 - Database engine: postgres 11.6

**Additional context**

**Comment by Smankusors** [comment]
is your wiki.js behind proxy server?

**Comment by Marco77577** [comment]
It's behind a reverse proxy (traefik). Do you think traefik limits the request size?

**Comment by Smankusors** [comment]
> It's behind a reverse proxy (traefik). Do you think traefik limits the request size?

I think it is, try to increase the limit from traefik

**Comment by Marco77577** [comment]
I tried to increase it as described [here](https://docs.traefik.io/v2.0/middlewares/buffering/), but to no avail. The error is still displaying.

**Comment by Smankusors** [comment]
> I tried to increase it as described [here](https://docs.traefik.io/v2.0/middlewares/buffering/), but to no avail. The error is still displaying.

how much you increased it?

**Comment by NGPixel** [comment]
This is a bug in 2.1.

It's been fixed in the upcoming 2.2 update already. You can manually apply the [fix](https://github.com/Requarks/wiki/commit/de4d407fdc001989a6ea859315bbd74b3c2bd680) in the meantime.
