### ISSUE TITLE
Admin doesn't load correctly

### ISSUE THREAD

**Issue by Brownie95** [Requarks/wiki#1554]
**Describe the bug**
After upgrading to v2.1.113 the admin doesn't load correctly. Users, Groups, pages etc all say 0.

**To Reproduce**
1. Go to the admin after upgrading
2. You will get an error saying "An unexpected error has occurred"

**Expected behavior**
Admin to load without errors and show correct information

**Screenshots**
Console error log from devtools
![image](https://user-images.githubusercontent.com/9106322/75743708-fe6f2b80-5d65-11ea-9174-37e212dce50b.png)
Admin dashboard
![image](https://user-images.githubusercontent.com/9106322/75743824-789fb000-5d66-11ea-9242-24336d584a51.png)

**Host Info (please complete the following information):**
 - OS: Amazon Linux 2
 - Wiki.js version: 2.1.113
 - Database engine: RDS postgres 11.5

**Comment by NGPixel** [comment]
Have you tried to logout and login again?

**Comment by Brownie95** [comment]
Yes, it doesn't fix the problem.

**Comment by NGPixel** [comment]
Try clearing your browser cache.

**Comment by Brownie95** [comment]
No luck, I've also tried in firefox and get the same GraphQL error.

**Comment by Smankusors** [comment]
how is your upgrade procedure?

**Comment by Brownie95** [comment]
I follow the instructions from https://docs.requarks.io/install/upgrade
