### ISSUE TITLE
Permit actions on all pages but one

### ISSUE THREAD

**Issue by NickKaramoff** [Requarks/wiki#1555]
**Question**
I want to let the users of my wiki:
- access every page except for the admin zone
- create/edit/delete every page except for the homepage and the admin zone. 

Here's how I set up the group in question:

**Group permissions**
- `read:pages`
- `write:pages`
- `manage:pages`
- `read:assets`
- `write:assets`

**Page rules**
1. ALLOW - `read:pages`, `write:pages`, `manage:pages`, `read:assets`, `write:assets` - Path Starts With... - /
2. DENY - `write:pages`, `manage:pages`, `write:assets` - Path is Exactly... - /
3. DENY - `read:pages`, `write:pages`, `manage:pages`, `read:assets`, `write:assets` - Path Starts With... - /`admin`

However, the editing of any page is forbidden now. I understand, that rule 2 overrides rule 1 because of the matching strategy specificity, but I can't come up with a way to create the required setup.

I had an idea of making it possible with Regex:

1. ALLOW - `read:pages`, `write:pages`, `manage:pages`, `read:assets`, `write:assets` - Path Matches Regex... - /` `/
2. DENY - `write:pages`, `manage:pages`, `write:assets` - Path Matches Regex... - /`^$`/
3. DENY - `read:pages`, `write:pages`, `manage:pages`, `read:assets`, `write:assets` - Path Matches Regex... - /`^admin`/

But this now allows me to edit the main page.

What would be the best way to achieve what I'm trying to achieve?

----

**Host Info (please complete the following information):**
OS: Debian 10 x64
Wiki.js version: 2.1.113
Database engine: PostgreSQL 11.5

**Comment by NGPixel** [comment]
Your first example should work fine. However the home page is a special case. The path for this page is actually `/home`, not `/`. So you'd need to change your rule to Path is Exactly - /home

This behavior will be fixed in 2.2 to properly handle `/` as the homepage in Page Rules.

**Comment by NickKaramoff** [comment]
Ahh, makes sense. Thank you, `/home` did work!

**Comment by NickKaramoff** [comment]
Since 2.2 is out for a long time, and `/` is handled correctly I am closing this issue 👋
