### ISSUE TITLE
Long links in markdown make the preview section disappear

### ISSUE THREAD

**Issue by misharigot** [Requarks/wiki#1556]
**Describe the bug**
When inserting a long link in markdown, the preview section disappears/gets pushed away.

**To Reproduce**
1. Edit a page with the Markdown editor
2. Insert the following line (Google search for Lorem Ipsum ...):
```markdown
[Link](https://www.google.com/search?ei=Kj9eXoj6OI6xkwXZ5ZnoCQ&q=lorem+ipsum+dolor+sit+amet+consectetur+adipiscing+elit+sed+do+eiusmod+tempor+incididunt+ut+labore&oq=lorem+ipsum+dolor+sit+amet+consectetur+adipiscing+elit+sed+do+eiusmod+tempor+&gs_l=psy-ab.3.0.0l2.107651.113409..114476...0.2..0.91.1789.29......0....1..gws-wiz.......0i71j0i273j0i67.RPcqrRD7YAI)
```
3. The preview section to the side disappears.

**Expected behavior**
The preview section does not change in size.
The link is being wrapped around the editor via word wrapping.

**Screenshots**
The screenshot below is a trimmed version of the aforementioned link to demonstrate the fact that the preview section is being pushed away. (See the small white column with the *Link*)
![Screenshot of issue](https://i.imgur.com/ZZEj9Wp.png)

**Host Info (please complete the following information):**
 - OS: Ubuntu 18.04, Docker
 - Wiki.js version: 2.1.113
 - Database engine: postgres 9.7

**Comment by misharigot** [comment]
Doesn't only happen with links, but with all long strings without spaces. 

Line with a long string without spaces:
![image](https://user-images.githubusercontent.com/15928604/80289380-4e52e900-873e-11ea-84a4-8a8150539fd8.png)


Line with strings separated by spaces:
![image](https://user-images.githubusercontent.com/15928604/80289351-282d4900-873e-11ea-8984-26744d1155a3.png)

**Comment by philkells** [comment]
@misharigot - I've been using a CSS injection to achieve a workaround. If you hide the preview panel, it's not ideal - but showing it is what you are trying to achieve in the first place :)

Add this to CSS override in the Theme section of Settings
`.editor-markdown-editor {max-width:60%}`

**Comment by NGPixel** [comment]
Already fixed by #1743

**Comment by philkells** [comment]
@NGPixel, do you have a projected ETA for the 2.4 release?

**Comment by NGPixel** [comment]
In a week
