### ISSUE TITLE
HTML not rendering

### ISSUE THREAD

**Issue by isamyh** [Requarks/wiki#1557]
**Describe the bug**
HTML is not rendering properly

**To Reproduce**
Happend after upgrading to 2.1.113, before it rendered properly. 
1. Go to edit a page
2. Insert example: <iframe src= "/randomfile.pdf" width= "100%" height= "800">Lenke</iframe>
3. Save and close and it will show only raw html. HTML rendering for markdown is turned on

**Expected behavior**
The expected behavior is to render properly.

**Screenshots**
![image](https://user-images.githubusercontent.com/46595503/75793009-08495c80-5d6f-11ea-86d3-edeb845475a5.png)
![image](https://user-images.githubusercontent.com/46595503/75793116-2f079300-5d6f-11ea-8885-c4a0219151e5.png)
I know the file is not found. 

**Host Info (please complete the following information):**
 - OS: Linux - Centos (core) 7.7.1908 x64
 - Wiki.js version: 2.1.113
 - Database engine: postgres 12.0

**Comment by NGPixel** [comment]
https://docs.requarks.io/troubleshooting#some-html-tags-are-rendered-as-plain-text
