### ISSUE TITLE
Upgrade Droplet to SSL Let's Encrypt

### ISSUE THREAD

**Issue by fbarresi** [Requarks/wiki#1558]
**Question**
I had a DigitalOcean Droplet with Wiki.js 2.0.12. I now updated it to latest version of Wiki.js. What should I do in order to get SSL Encription with Let's Encrypt active?

**Host Info:**
OS: Ubuntu 18.04, Docker
Wiki.js version: 2.1.113
Database engine: postgres 11

**Comment by NGPixel** [comment]
https://docs.requarks.io/install/digitalocean#automatic-https-with-lets-encrypt

**Comment by fbarresi** [comment]
Thank you!
Wiki.js is really a great project. Thank you for your job!

**Comment by AMDphreak** [comment]
This does not work. I am submitting a new bug report, because those instructions bricked my instance. Great job.
