### ISSUE TITLE
JAVA Code block triggers an error when rendering Markdown page

### ISSUE THREAD

**Issue by juliendms** [Requarks/wiki#1559]
**Describe the bug**
The following syntaxe:

>\```java
>/**
>\* @author John Smith <john.smith@example.com>
>*/
>\```

throws the following error when used in a Markdown page and viewed:

![image](https://user-images.githubusercontent.com/41991731/75892795-3643a500-5e32-11ea-849e-48f8c3d6b1af.png)

**To Reproduce**
1. Insert the above syntax in a new Markdown page
2. Save
3. Browse the page in View mode (not edit mode). It doesn't load
4. See error in debugger

**Expected behavior**
No error

**Screenshots**
Cf. above.

**Host Info (please complete the following information):**
 - OS: CentOS
 - Wiki.js version: last version
 - Database engine: postgres

**Additional context**
The problem is not present when editing the page, the preview works.
The problem appeared in the latest releases, it used to work fine (at least in 2.0)

**Comment by Dreamerset** [comment]
I second juliendms opinion. The problem appeared in the lates release.  
Coma "," also breaks the rendering of the page with the same error message.  
This example code line can't be visualized:  
`final Map<String, Object> headers = new HashMap<>();`  
![image](https://user-images.githubusercontent.com/17952370/76001564-f3ef9600-5f0d-11ea-9663-9ede819f90a5.png)

**Comment by NGPixel** [comment]
Fixed by b529ad21c97a7093e9ecc35e2e72fb8148f0c9d0
