### ISSUE TITLE
Misbehaviour while creating new tags

### ISSUE THREAD

**Issue by soundzgoood** [Requarks/wiki#1564]
### Actual behavior
When adding a Tag to a page and clicking on the suggestion it creates the tag that you click on but also creates a new tag with the letters that you type.
i.e. you type "pub" select the prexisting tag "public" and click on save. Then the page has the tags "pub" and "public"
### Expected behavior
only create tags for tags that are selected

**Comment by NGPixel** [comment]
Fixed by 77548c8778bdd9e30379318d219fa892d5ffc112
