### ISSUE TITLE
How to set up public access on existing wiki

### ISSUE THREAD

**Issue by stefaanMLB** [Requarks/wiki#1565]
**Question**
I'm trying to set up public access to an existing wiki running on docker.  I edited the config.yaml file (added public:true) and restarted the container.
After logging out, the login page appears which, from what I read in the documentation, should not be the case with public mode active.
I read in one of the issues that the mongodb might need to be "cleared"
- Can this be done from within the UI ?
- If not, can the procedure for the clearing of the db be documented ?  I'd very much appreciate not losing any data in the process

**Host Info (please complete the following information):**
OS: docker
Wiki.js version: latest
Database engine: mongo:latest, also on docker

**Comment by Smankusors** [comment]
What actually latest version is? When you pull these wiki and mongo image?

I suspect this is not wiki latest version, because it is no longer supporting noSQL

**Comment by NGPixel** [comment]
You're mixing up v1 and v2.

v1 is using MongoDB and instructions can be found here: https://docs-legacy.requarks.io/wiki

v2 is using PostgreSQL / MySQL / MariaDB / MS SQL Server or SQLite. There's no `public: true` option. All access rights are managed via the Admin area, as documented here: https://docs.requarks.io/groups

**Comment by stefaanMLB** [comment]
OK, I had read the docs about v2 groups and implemented it.
Then the next question is: how can one log in as 'guest' ?

**Comment by NGPixel** [comment]
That doesn't make any sense. The guest account represents a non-authenticated user. You don't login as guest... You're a guest as soon as you land on the wiki.

**Comment by stefaanMLB** [comment]
OK, just found out, no need to log on, I have to send URL's to people which they can access wihout logging in.  Sorry for the question.  I have to make a guest landing page with links and distribute the URL.  Thank for the help.
