### ISSUE TITLE
Markdown Checklist not rendered

### ISSUE THREAD

**Issue by elderGinger** [Requarks/wiki#1568]
**Describe the bug**
Checklist in not corectly rendered. 

**To Reproduce**
1. Go to home page. 
2. Create a new markdown page. 
3. Write checklists like 
```markdown
- [ ] one
- [x] two 
```
4. Click save and then close. 
5. See the error. 

**Expected behavior**
![image](https://user-images.githubusercontent.com/60418032/76139768-8dde4c80-608e-11ea-8688-d3e9dd278c15.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/60418032/76139833-2f659e00-608f-11ea-8275-cc9a3c7a48c3.png)

**Host Info (please complete the following information):**
 - OS: [OSX 10.15, Docker]
 - Wiki.js version: [2.1.113]
 - Database engine: [postgres:11-alpine]

**Additional context**
none

**Comment by NGPixel** [comment]
Disable **HTML Sanitization** in Admin > Rendering > HTML > Security, then re-save the page.

This is a bug in 2.1 that will be fixed in 2.2.
