### ISSUE TITLE
Mermaid syntax 

### ISSUE THREAD

**Issue by gaelj** [Requarks/wiki#1573]
**Question**
I noticed the Mermaid module can be activated.
But I cannot find any documentation about the syntax to use, and I did not manage to guess it by myself.
What is the syntax to trigger the mermaid parser? 

**Host Info:**
OS: Fedora, Docker
Wiki.js version: 2.1.113
Database engine: postgres 9.6.17

**Comment by NGPixel** [comment]
Mermaid is not available yet. The module entry was left by mistake. So even though it can be activated, it doesn't do anything at the moment.

Mermaid support will be added in a future release.
