### ISSUE TITLE
Markdown editor: Only Insert Asset is active?

### ISSUE THREAD

**Issue by carlheinmostert** [Requarks/wiki#1574]
**Question**
I only edit in markdown because it's awesome.
On the left vertical toolbar, I only have access to the Insert Asset "button".  The rest are disabled.
I am specifically trying to insert a Youtube video.

Please assist.  Many thanks

Carl

**Host Info (please complete the following information):**
OS: Docker on Azure
Wiki.js version: Latest on Azure.
Database engine: Postgres lates on Azure.

**Comment by NGPixel** [comment]
They are disabled because they are not available yet. They will be added in future updates.
