### ISSUE TITLE
Rendering Font Awesome icons

### ISSUE THREAD

**Issue by carlheinmostert** [Requarks/wiki#1575]
**Describe the bug**
Hi

In the markdown editor I am able to add font awesome icons to the content.  This is rendered in the preview on the right, but is not rendered in normal mode. See attached.

**To Reproduce**
Just add a font awesome icons in markdown as per attached.

**Expected behavior**

**Screenshots**
If applicable, add screenshots 
![Annotation 2020-03-12 120824](https://user-images.githubusercontent.com/24290365/76510979-1ed07180-645b-11ea-83fe-2d82f926ef4b.png)
to help explain your problem.

**Host Info (please complete the following information):**
 - OS: docker on azure
 - Wiki.js version: latest
 - Database engine: latest postgres
**Additional context**

**Comment by kmpm** [comment]
I would not mind taking this somewhat further.
Something like embedding with :fas fa-running: or something like markdownmoster https://markdownmonster.west-wind.com/docs/_4ue01xl6q.htm

**Comment by NGPixel** [comment]
@kmpm Create a [feature request](https://requarks.canny.io/wiki) for it. There's a module that could be used for it: https://www.npmjs.com/package/markdown-it-fontawesome

@carlheinmostert This is fixed in the upcoming 2.4.
