### ISSUE TITLE
Authentication through Gitlab not working

### ISSUE THREAD

**Issue by chbrandt** [Requarks/wiki#1576]
**Question**
I'm trying to get WikiJS to create/authenticate users through my local (self-hosted) Gitlab instance.
The wiki is not creating the user -- note: self-registration is allowed.

I would like to know where do I check for what's happening? Where are the logs or how do I get more (debug) info?

Here is what the [docker-compose](https://docs.requarks.io/install/docker#using-docker-compose) prints out:
```
(...)
wiki_1  | 2020-03-12T11:11:23.981Z [MASTER] info: Authentication Strategy gitlab: [ OK ]
wiki_1  | 2020-03-12T11:11:23.982Z [MASTER] info: Authentication Strategy local: [ OK ]
wiki_1  | 2020-03-12T11:11:33.201Z [MASTER] info: Authentication Strategy gitlab: [ OK ]
wiki_1  | 2020-03-12T11:11:33.201Z [MASTER] info: Authentication Strategy local: [ OK ]
wiki_1  | 2020-03-12T11:13:05.787Z [MASTER] info: Authentication Strategy local: [ OK ]
wiki_1  | 2020-03-12T11:13:17.823Z [MASTER] info: Purging orphaned upload files...
wiki_1  | 2020-03-12T11:13:17.824Z [MASTER] info: Purging orphaned upload files: [ COMPLETED ]
wiki_1  | 2020-03-12T11:14:10.921Z [MASTER] info: Regenerating certificates...
wiki_1  | 2020-03-12T11:14:11.221Z [MASTER] info: Authentication Strategy local: [ OK ]
wiki_1  | 2020-03-12T11:14:11.221Z [MASTER] info: Regenerated certificates: [ COMPLETED ]
wiki_1  | 2020-03-12T11:18:27.973Z [MASTER] info: Authentication Strategy gitlab: [ OK ]
wiki_1  | 2020-03-12T11:18:27.973Z [MASTER] info: Authentication Strategy local: [ OK ]
wiki_1  | 2020-03-12T11:22:18.921Z [MASTER] info: Authentication Strategy gitlab: [ OK ]
wiki_1  | 2020-03-12T11:22:18.921Z [MASTER] info: Authentication Strategy local: [ OK ]

```

## Issue workflow

When the user clicks the Gitlab button:
![image](https://user-images.githubusercontent.com/482051/76517349-71129200-645d-11ea-95e7-b385e07d9795.png)

Redirection happens:
![image](https://user-images.githubusercontent.com/482051/76517415-92737e00-645d-11ea-9fcd-0152ae0d9cea.png)

And after "Authorize" is clicked I get:
![image](https://user-images.githubusercontent.com/482051/76517482-a9b26b80-645d-11ea-955d-96fd2f96f2f3.png)

**Host Info (please complete the following information):**
OS: Docker (requarks/wiki:2 :: 5e1244a77359)
Wiki.js version: 2.1.113
Database engine: postgres (postgres:11-alpine :: 27b97965b6bc)

**Comment by rene-s** [comment]
You need to enable scope `read_user` in Gitlab.
