### ISSUE TITLE
getting 404 error when wiki path is subpath

### ISSUE THREAD

**Issue by delta360-developer** [Requarks/wiki#1579]
**Question**

I have set up the Wiki.JS vis iisnode. It works fine except the static resource are pointing to the wrong end. I have a website @ localhost/wiki. The resource is trying to access http://localhost/js/app.8a594e130efc1d25f526.js rather than http://localhost/wiki/js/app.8a594e130efc1d25f526.js.

How do i change the wiki.js config to have /wiki as the base path.

![image](https://user-images.githubusercontent.com/54117940/76530796-a2ce2d80-644a-11ea-9448-a592cbd2b021.png)

**Comment by NGPixel** [comment]
https://docs.requarks.io/install/requirements#domain
