### ISSUE TITLE
Strange UI 

### ISSUE THREAD

**Issue by jackpgao** [Requarks/wiki#158]
#### After build wiki.js, I got such a UI, is it normal? Why so ugly?

![image](https://user-images.githubusercontent.com/3423412/28014301-bdbb9388-659e-11e7-978f-1272256a1319.png)

### How I build it 

- I use a ubuntu:14.04 Docker image, and install all nead package to build wiki.js

```
☁  wiki.js  nodejs --version
v6.11.0

☁  wiki.js  git --version
git version 2.8.1



☁  wiki.js  node wiki --version
1.0.0-beta.13

```

- it seems the js is not working well
- Who can help me?

**Comment by syssecfsu** [comment]
I have exactly the same issue on Ubuntu 16.04. Please let me know if you need any information to track the problem. Thank you.

**Comment by germora** [comment]
It 404s on "missing assets" like app.js and vendor.js

**Comment by syssecfsu** [comment]
Okay, then how do I diagnose/fix the problem? I am clueless. Thank you.

**Comment by NGPixel** [comment]
This is most likely because the host specified in the config.yml doesn't match the actual host you're using to access your wiki. The JS files (app.js and vendor.js) are therefor blocked because of the different domains.

**Comment by germora** [comment]
@NGPixel You are correct. These assets are available when you append the port number at the end of the domain. So it leaves me to believe that I need to configure my apache settings to forward my domain to that URL.

**Comment by syssecfsu** [comment]
Confirmed. 

I run wiki.js http://localhost:8000 (without a HTTP server) to try it. In the config.yml, if I changed **host** to "http://localhost:8000", the problem went away. Nice!

Thank you.

**Comment by germora** [comment]
If it helps anyone configure their Apache settings use the following settings -- enable proxy_http and proxy modules. Switch out the port number to accommodate your environment.  

<VirtualHost *:80>
	ServerName domain.com

	<Location "/">
		ProxyPreserveHost on
		ProxyPass http://domain.com:3000/
		ProxyPassReverse http://domain.com:3000/
	</Location>
</VirtualHost>

**Comment by localjo** [comment]
I'm not using apache. Any ideas how to get the port to work correctly?

config.yml originally had this;
```
host: 'http://localhost'
port: 3000
```

So I tried;
```
host: 'http://localhost/:3000'
port: 3000
```
And then did `node wiki stop` and `node wiki start` but it's still requesting resources without the port.

**Comment by NGPixel** [comment]
That's not a valid host. Remove the / before the port: `http://localhost:3000`

**Comment by localjo** [comment]
Awesome. That works. Thanks. The configuration wizard initially put `http://localhost` in there, even though I specified the port. Might be a bug. But manually changing the values in config.yml to this works;
```
host: 'http://localhost'
port: 3000
```
Thanks for the help!

**Comment by NGPixel** [comment]
`host` and `port` are not related. Host is client-side and Port is what the server listens on. Both can have different port values. So you must define the port in host if different than 80 or 443.
