### ISSUE TITLE
Katex subscript rendering issue

### ISSUE THREAD

**Issue by tionis** [Requarks/wiki#1581]
## Description
Katex rendering seems to have a bug with rendering subscript.

## To reproduce:
Bug occurrs when trying to use more than one character in subscript.
I used the Katex code `P_{static}=I_{DD}V_{DD}` and while it was rendered partly correct.
Another example would be `V_{DD}=5V`
The logs output warnings like this:
`2020-03-12T16:45:06.500Z [JOB] warn: KaTeX parse error: Expected group after '_' at position 2: I_`
`2020-03-12T16:45:06.501Z [JOB] warn: KaTeX parse error: Expected group after '_' at position 19: …static}=I_{DD}V_`

## Expected Behaviour
Katex code should have same output as on [katex.org](https://katex.org/)

## Host Info:
 - OS: Docker
 - Wiki.js version: 2.1.113
 - Database engine: postgres 11.7

**Comment by edomora97** [comment]
Still broken in v2.5.170

**Input**:
`$e^{-x^2}$`

**Result**:
![image](https://user-images.githubusercontent.com/6685454/97780277-ed401e00-1b83-11eb-9ce9-931168f7a53f.png)

**Console**:
```ParseError: KaTeX parse error: Expected group after '^' at position 2: e^̲```

-------

When using the non-inline math mode it works fine (`$$e^{-x^2}$$`). The quickest workaround seems to use double braces: `$e^{{-x^2}}$`.

And the strangest thing is that I'm using Mathjax and not Katex

![image](https://user-images.githubusercontent.com/6685454/97780391-a272d600-1b84-11eb-99f4-6423e9eebe35.png)

Of course both `Inline TeX` and `TeX Blocks` are enabled.

------

OS: Docker
Wiki.js version: 2.5.170
Database engine: sqlite3
