### ISSUE TITLE
Navigation Flyover intrusive

### ISSUE THREAD

**Issue by vincent-polite** [Requarks/wiki#1582]
There appear to be 3 breakpoints.

- >< 540px : The interaction between navigation and content works.  The nav drawer auto-minimizes on click into a hamburger icon.  It also flies "over" the content when in use.  This makes perfect sense.
- >< 504px < x < 1300px : The interaction here has two significant issues.  The flyover drawer reappears (instead of being minimized) after every navigation click to a new wiki page.  This forces users to click twice every time they navigate to new content.  It would be my contention that you would still want the navigation to remain hidden unless called for by the user -OR- always on and pushing the content over.   *NOTE* - this resolution introduces a bug if the user minimizes the menu and then expands to > 1300px.
- > 1300px - the nav drawer is always on and a part of the screen (instead of flying over the content).  This is acceptable, although if a user minimizes the menu from > 540px and < 1300px, the menu remains hidden and there is no hamburger icon to bring it back without either refreshing the screen or minimizing the screen back below 1300px.

I believe the always on Navigation is not ideal even at > 1300px.  But if it is going to be turned on, a mechanism either needs to exist to turn it off/minimize it, or make sure the navigation returns even if minimized from a lower screen width.

My suggestion is that at < 1300px, the navigation should always be minimized when going to a new page.  

And > 1300px, something needs to be added to address the idea that if the navigation is minimized that it reappears at superdesktop size no matter what the user's selection was at the lower resolution.

**Steps to reproduce unnecessary always on/flyover nav:**
- Set browser to > 540px screen width but < 1300px
- Click on site nav
- Realize that the nav is still covering content; in some cases with similar content, there is no real indication that navigation has taken place.  Nav should get minimized on a new page view.

**Steps to reproduce issue where navigation is lost:**
- Set browser to > 540px screen width but < 1300px
- Minimize navigation
- Change browser size to > 1300px
- Navigation is gone, and no way to bring it back

**Browser/OS Platform:** Using Chrome (latest build) on Windoes 10 Pro

I understand some of this is subjective, but the always on flyover behavior between 540px and 1300px is very suboptimal.  It either needs to push the content over if it's going to be always on, or it needs to minimize since site nav is usually a one-click affair.

The bug that prevents a user from accessing the site nav after minimizing and resizing is also annoying, but less so than the first bug I mention.  I've seen other folks bring up this issue; I'd be happy to code tweaks to the css or drawer invocation, but the server package I downloaded, I couldn't find the references responsible for the behavior.  (I'm a node.js newbie, but willing to learn if you could point me in the right direction and would hopefully submit a patch addressing the issue)

**Comment by vincent-polite** [comment]
Apologies this is a duplicate of #1341 - However, it is possible that the information here is useful to @NGPixel .  Thank you for acknowledging how some of the behavior is unintended.  As mentioned in #1341 - configurable would be great, but I'd settle for consistent behavior in that region between mobile and "big" desktop.  Specifically for the nav covering content on every page load.  Argh.  :)

**Comment by vincent-polite** [comment]
If you feel there is nothing else of value here, please feel free to close provided that you feel enough attention is being given to #969 and #1341.

**Comment by NGPixel** [comment]
Fixed by dd3699b5012fb5720fc28a5d24e40f41d85ed512
