### ISSUE TITLE
Building from stable release branch warns about unstable version and claims 2.0.0

### ISSUE THREAD

**Issue by WikiDebug2020** [Requarks/wiki#1583]
### Actual behavior

When building the currently last stable release of WikiJS from source the resulting application warns about running an unstable developer version not recommended for production use:
![20200313-WikiJS_BuildFromTag-2 1 113_tells-is-master-and-2 0 0](https://user-images.githubusercontent.com/62149904/76637516-2cfdbb00-654b-11ea-883d-36e15787702f.png)

and the server log outputs

```
[MASTER] info: =======================================
[MASTER] info: = Wiki.js 2.0.0 =======================
[MASTER] info: =======================================
```

### Expected behavior

See the version that correspond to the tag of that release in the logs and have no warning about unstable version.

### Steps to reproduce the behavior

In a NodeJS-v12 environment:
```
# Clone the release tag
git clone --branch 2.1.113 https://github.com/Requarks/wiki.git ./tmpwiki
cd ./tmpwiki

# Check it's the same commit
git log |head -n 1
commit 56235c6354a7982818b523a433a2a43d3f8c0e79

# Build
yarn cache clean \
 && yarn --frozen-lockfile --non-interactive \
 && yarn build \
 && rm -rf node_modules \
 && yarn --production --frozen-lockfile --non-interactive
```

**Comment by NGPixel** [comment]
This is the expected behavior. You're not supposed to build from source other than for development purposes, hence the warning message.

Please install the app by following the instructions: https://docs.requarks.io/install

**Comment by WikiDebug2020** [comment]
I don't quite understand. Am I just supposed to trust any built code and run it on my server ?

Building from source is the only way I can be sure that what is running is actually what is in the code, so at least I'd expect the release builds to be reproducible and respect the version number and behaviour of the build proposed for download to the public.

Could you please provide a way to reproduce your build so that anyone can verify the authenticity of it ?

Thanks

**Comment by justinacolmena** [comment]
Wiki.js is built on Node.js. Are you looking for basic information on how to build and deploy a Node.js project? That would be a good place to start.

I was able to muddle through it as a beginner. It can't be that hard. It's one thing if you simply want to run a production build, but quite another if you want to experiment and participate in coding.

The F.U.D. is unnecessary.

On March 13, 2020 12:31:41 PM AKDT, WikiDebug <notifications@github.com> wrote:
>I don't quite understand. Am I just supposed to trust any built code
>and run it on my server ?
>
>Building from source is the only way I can be sure that what is running
>is actually what is in the code, so at least I'd expect the release
>builds to be reproducible and respect the version number and behaviour
>of the build proposed for download to the public.
>
>Could you please provide a way to reproduce your build so that anyone
>can verify the authenticity of it ?
>
>Thanks
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Requarks/wiki/issues/1583#issuecomment-598899515

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by WikiDebug2020** [comment]
No, I'm fine with building node apps, I just would like to build my own production version of the release branch tagged '2.1.113' codebase that behaves exactly as the one proposed for download for the same version, in this case https://github.com/Requarks/wiki/releases/download/2.1.113/wiki-js.tar.gz .

I'm building most things from source and it is a common habit that releases are supposed to be reproducible by anyone. It would be nice to have somewhere in the install doc an advanced bash script that produces the downloadable archive, so that anybody can build it on its own instead of trusting a tarball.

That said, thanks for the great refactor to 2.x and the nice themes.

**Comment by justinacolmena** [comment]
A lot of dependencies have to be installed with npm, and there is a Makefile.

Have you tried steps like these?

`git clone` or download and unpack the release.

Change to the wiki directory.

```
$ npm install
$ sudo npm install --global webpack webpack-cli
$ cp config.sample.yml config.yml
```
Edit `config.yml` with your database connection details etc.
```
$ make build
$ node server
```

The thing is that npm may install more modern versions of some of the dependencies than were available at the time that particular release was built. I am no expert, but I am sure there are ways to deal with that.

I am not the coder. I just happened to stumble on an interesting project and found it helpful to organize my website.

On March 13, 2020 2:52:11 PM AKDT, WikiDebug <notifications@github.com> wrote:
>No, I'm fine with building node apps, I just would like to build my own
>production version of the release branch tagged '2.1.113' codebase that
>behaves exactly as the one proposed for download for the same version,
>in this case
>https://github.com/Requarks/wiki/releases/download/2.1.113/wiki-js.tar.gz
>.
>
>I'm building most things from source and it is a common habit that
>releases are supposed to be reproducible by anyone. It would be nice to
>have somewhere in the install doc an advanced bash script that produces
>the downloadable archive, so that anybody can build it on its own
>instead of trusting a tarball.
>
>That said, thanks for the great refactor to 2.x and the nice themes.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/Requarks/wiki/issues/1583#issuecomment-598963416

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by NGPixel** [comment]
@WikiDebug2020 See https://docs.requarks.io/en/dev/build-process

**Comment by NGPixel** [comment]
@justinacolmena If he builds from the source of a specific release tag, the npm dependencies will be locked to that specific version and should result in the exact same build package.

The main reason why building from source is discouraged is because most users will use the latest commit in the master branch, instead of a proper release tag. This results in broken builds and unnecessary support tickets.

**Comment by justinacolmena** [comment]
On March 13, 2020 3:58:47 PM AKDT, Nicolas Giard <notifications@github.com> wrote:
>@justinacolmena If he builds from the source of a specific release tag,
>the npm dependencies will be locked to that specific version and should
>result in the exact same build package.
Yes, true for those packages installed for a specific Node.js project. But that will not in general be the case for any npm "global" installations or whatever else happens to be installed on the build system at the time.

>The main reason why building from source is discouraged is because most
>users will use the latest commit in the master branch, instead of a
>proper release tag. This results in broken builds and unnecessary
>support tickets.
The latest and and greatest is not guaranteed to be buildable and usable. Same as any other open source project. Use at your own risk.

The "wiki" crowd is notorious for forking and later abandoning various projects.

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by WikiDebug2020** [comment]
Thank you both for you constructive answers,

@justinacolmena  thanks for all your indications and advices, as you can see in my original post I never intended to build master, only release branches.

@NGPixel good to know that the dependencies versions are locked, I was wondering that. The provided link is indeed what I was looking for. Is the Dockerfile for `requarks/wiki:canary` publicly available ?

I'll be trying that, have a nice weekend!

**Comment by NGPixel** [comment]
@WikiDebug2020 https://github.com/Requarks/wiki/blob/master/dev/build/Dockerfile

**Comment by coolsam726** [comment]
> ### Actual behavior
> 
> When building the currently last stable release of WikiJS from source the resulting application warns about running an unstable developer version not recommended for production use:
> ![20200313-WikiJS_BuildFromTag-2 1 113_tells-is-master-and-2 0 0](https://user-images.githubusercontent.com/62149904/76637516-2cfdbb00-654b-11ea-883d-36e15787702f.png)
> 
> and the server log outputs
> 
> ```
> [MASTER] info: =======================================
> [MASTER] info: = Wiki.js 2.0.0 =======================
> [MASTER] info: =======================================
> ```
> 
> ### Expected behavior
> 
> See the version that correspond to the tag of that release in the logs and have no warning about unstable version.
> ### Steps to reproduce the behavior
> 
> In a NodeJS-v12 environment:
> 
> ```
> # Clone the release tag
> git clone --branch 2.1.113 https://github.com/Requarks/wiki.git ./tmpwiki
> cd ./tmpwiki
> 
> # Check it's the same commit
> git log |head -n 1
> commit 56235c6354a7982818b523a433a2a43d3f8c0e79
> 
> # Build
> yarn cache clean \
>  && yarn --frozen-lockfile --non-interactive \
>  && yarn build \
>  && rm -rf node_modules \
>  && yarn --production --frozen-lockfile --non-interactive
> ```

@WikiDebug2020, I perused through the code and found a solutoin: Just set `"dev": false` in `package.json` then run `yarn build`
