### ISSUE TITLE
FreeIPA LDAP - Failed login when user has multiple email addresses in FreeIPA 

### ISSUE THREAD

**Issue by MichaelLeeHobbs** [Requarks/wiki#1585]
**Describe the bug**
When a user in FreeIPA has multiple email addresses assigned to their account Wiki.js fails to auth account via LDAP.

**To Reproduce**
1. Spin up a FreeIPA container with a dc of example.local
2. Create a user wikijs with a password and the HBAC Role: services_ldap_read_only
3. Spin up a Wikijs container.
4. Wikijs configure LDAP
*  LDAP URL: ldap://freeIPAIP:389
* Admin Bind DN: uid=wikijs,cn=users,cn=accounts,dc=example,dc=local
* Admin Bind Credentials: password from step 2
* Search Base: cn=users,cn=accounts,dc=example,dc=local
* Search Filter: (uid={{username}})
* Unique ID Field Mapping: uid
* Email Field Mapping: mail
* I turned on "Allow self-registration" during debugging but it may not be needed.
5. Create user in Wikijs that has a matching email address in FreeIPA.

**Expected behavior**
I would expect the user to be able to login in with UID with an email address as assigned in Wikijs.

**Screenshots**
2020-03-14T16:00:40.309Z [MASTER] warn: LDAP LOGIN ERROR (c2): Missing or invalid email address from profile.
2020-03-14T16:00:40.309Z [MASTER] warn: LDAP LOGIN ERROR (c1): Missing or invalid email address from profile.

**Host Info (please complete the following information):**
 - OS: [Docker]
 - Wiki.js version: 2.1.113
 - Database engine: postgres 9.6.15
 - FreeIPA, version: 4.6.5

**Additional context**
My guess would be that Wiki.js is getting back an array of emails or maybe a comma-separated list whereas it is expecting a single item.

tcpdump of ldap traffic
* single email address assigned: mail1(..mhobbs@valornetwork.com0
* two email addresses assigned: mail1(..mhobbs@valornetwork.com..test@test.com0

**Comment by NGPixel** [comment]
Try using `mail[0]` as the Email Mapping field, instead of just `mail`

**Comment by chungimo** [comment]
> Try using `mail[0]` as the Email Mapping field, instead of just `mail`

Just wanted to comment here - was running into a similar issue as OP and that worked.
