### ISSUE TITLE
Deleting users fails if password was changed

### ISSUE THREAD

**Issue by jschirrmacher** [Requarks/wiki#1586]
**Describe the bug**
If users change their password, it is not possible to delete this users any more, even they never created a page or anything else. Instead, I get a foreign constraint error in the logs:

```
ERROR:  update or delete on table "users" violates foreign key constraint "userkeys_userid_foreign" on table "userKeys"
DETAIL:  Key (id)=(18) is still referenced from table "userKeys".
```

Actually, the userKey generated for this user was already long outdated (several days), so this token was not valid any more.

**To Reproduce**
1. Create a new user and login as this user.
2. Change the password and log out again.
3. Log in as administrator, and go to user administration page
4. Try to delete the first user.

**Expected behavior**
The user should be deleted, and the token should be removed with the user (cascading). User deletion should work.

**Host Info (please complete the following information):**
 - OS: Docker
 - Wiki.js version: 2.1.113
 - Database engine: postgres:9-alpine

**Comment by NGPixel** [comment]
Fixed by fcd37afdb070b5c4685d3b81c4c9b4ea83267a06
