### ISSUE TITLE
Image caption (figcaption) not displaying correctly

### ISSUE THREAD

**Issue by acirulis** [Requarks/wiki#1587]
**Describe the bug**
When using WYSIWYG editor and inserting image with caption (<figcaption> tags), caption is not displayed in alignment with image and encoded tags (<figcaption>) are displayed on page.

**To Reproduce**
1. Create a new page with WYSIWYG type
2. Insert in image by uploading a new file
3. Add caption to image
4. Save & view page

**Expected behavior**
Caption is displayed under the image with correct alignment and formatting.

**Screenshots**
https://ibb.co/C5B0zD3

**Host Info (please complete the following information):**
 - OS: Docker Container (Linux)
 - Wiki.js version: 2.1.113
 - Database engine: PostgreSQL 12.2

**Additional context**

**Comment by NGPixel** [comment]
This is already fixed. You need to disable HTML Sanitization under Admin > Rendering > HTML > Security for now.

**Comment by acirulis** [comment]
Thanks, good luck with project!
