### ISSUE TITLE
Custom port not taken in account after upgrading

### ISSUE THREAD

**Issue by mirelsol** [Requarks/wiki#159]
### Actual behavior
In my config.yml I have a custom port (e.g. 8081). When I launch the wiki in the browser I have in the source page references to stylesheets / javascript that don't include the port, for example: src="http://localhost/js/vendor.js"
It is working in v1.0.0-beta.12 but not in v1.0.0-beta.13

### Expected behavior
References should include the port, for example: src="http://localhost:8081/js/vendor.js"

### Steps to reproduce the behavior
During configuration of the wiki, set a custom port (different from 80).

**Comment by NGPixel** [comment]
You must include the port in the `host` setting.

**Comment by mirelsol** [comment]
Ok that fixed it thanks.
