### ISSUE TITLE
Add timeout to overlay when saving page to try again

### ISSUE THREAD

**Issue by thomaskcr** [Requarks/wiki#1590]
**Describe the bug**

When saving if the connection to the server has been lost (i.e. internet connection lost) the overlay will persist even after error message is displayed. Editing CSS and removing overlay allowed for save to happen again. 

**To Reproduce**
1. Open page for editing
2. Disable network connection
3. Click save

**Expected behavior**

We should either timeout the overlay after a reasonable amount of time or on an error in addition to success.

**Comment by NGPixel** [comment]
Fixed by d3b4c64554593faacd52cc585a64c1f8a1c1b4eb
