### ISSUE TITLE
CSS Override doesn't work on Login page

### ISSUE THREAD

**Issue by trumpeteer** [Requarks/wiki#1591]
**Describe the bug**
CSS Override works on any of the other pages, but not login

**To Reproduce**
1. Go to https://wikijs.example.com/a/theme
2. Enter CSS code  ( I tested using a simple '#app { position: absolute }' )
3. Click "Apply"
4. Go to https://wikijs.example.com/login and see normal login page

**Expected behavior**
Using above example, should be screwed up

**Host Info (please complete the following information):**
 - OS: requarks/wiki:2 docker image
 - Wiki.js version:  2.1.113
 - Database engine: Postgrest 10.7

**Comment by jord8on** [comment]
We're in the same boat here. 

We'd like to hide everything on the login screen, except the login with Google or Local, buttons.  (we'd actually like to remove the "Local" login as well, but recognize that's not an option, and a totally different discussion.

We simply want employees to click the Google button to set up their account, and login. 

We tried adding all of this CSS to our overrides but this css doesn't touch the login screen, unfortunately. This basically removes everything except the Google/Local login buttons.

```
.v-card__actions.pb-3 {
    display: none!important;
}
.v-input.mt-3.v-input--hide-details.theme--light.v-text-field.v-text-field--single-line.v-text-field--solo.v-text-field--solo-flat.v-text-field--is-booted.v-text-field--enclosed.v-text-field--placeholder {
    display: none!important;
}
.v-input.mt-2.v-input--hide-details.theme--light.v-text-field.v-text-field--single-line.v-text-field--solo.v-text-field--solo-flat.v-text-field--is-booted.v-text-field--enclosed.v-text-field--placeholder {
    display: none!important;
}
.v-card__actions.pb-4 {
    display: none!important;
}
.pb-2.body-2.text-xs-center.grey--text.text--darken-2 {
    display: none!important;
}
.v-card__actions.py-3 {
    display: none!important;
}
```

**Comment by NGPixel** [comment]
CSS Override is for content pages only, not the login page. You'll be able to modify the login page to your liking in 2.5.

**Comment by peteruithoven** [comment]
Same seems to go for the HTML Injection. 

Might be good to clarify that the Code Injection area is only for the content pages in a description, because I was trying the same thing. 
(I know 2.5 is coming soon, but we have a lot of confused people at the moment)

**Comment by peteruithoven** [comment]
> You'll be able to modify the login page to your liking in 2.5.

Not really though... Can't hide the local login

**Comment by peteruithoven** [comment]
Sorry, this is actually possible, but the setting is placed in Security.  
![Screenshot from 2020-09-09 14-50-51@2x](https://user-images.githubusercontent.com/523210/92601199-d0d2e400-f2ac-11ea-98d8-18892c5fc1c7.png)

**Comment by ilium007** [comment]
2.5.314 and still can't add CSS injection to Login page despite comment from @peteruithoven above

**Comment by ilium007** [comment]
And with "Bypass Login Screen" selected I am still presented with the Google Auth Provider option instead of being redirected to Google to authenticate.

<img width="907" height="369" alt="Image" src="https://github.com/user-attachments/assets/172687ca-92f8-4b50-b3dd-e3c78b302fb3" />

<img width="739" height="297" alt="Image" src="https://github.com/user-attachments/assets/ead39346-5577-4903-ac92-ff5237fb33a9" />

**Comment by NGPixel** [comment]
@ilium007 You need to put Google auth first in the providers list.
