### ISSUE TITLE
How to activate list of all pages / global navigation in Wiki.js v2.1

### ISSUE THREAD

**Issue by thinkh** [Requarks/wiki#1592]
In Wiki.js v1 there was a global navigation point called _All pages_, where user could browser the wiki (tree) structure.

![grafik](https://user-images.githubusercontent.com/5851088/76845686-8ca3e100-683f-11ea-8973-bddec23efb2e.png)

I saw in the [Wikijs v2 introduction](https://docs.requarks.io/guide/intro) that this feature should be available from the _navigation menu_:

> Navigation Menu - Menu to go Home, **Browse the Wiki Structure** or Browse by Tags.

![grafik](https://user-images.githubusercontent.com/5851088/76845813-c1b03380-683f-11ea-8e26-a630adb4a1ae.png)

According to tickets https://github.com/Requarks/wiki/issues/21, https://github.com/Requarks/wiki/issues/1312, or https://github.com/Requarks/wiki/issues/1334 this should be available in v2.1. However, when I installed the v2.1.113 I was not able to find or activate this feature. Could you please provide some instructions how to activate this feature? Thanks in advance.

**Comment by NGPixel** [comment]
This is coming in a future release.

**Comment by thinkh** [comment]
Ok, thanks. Looking forward to this feature so that we can upgrade from v1. Wiki.js v2 looks great so far!

**Comment by sll552** [comment]
This would be a very welcome feature, is there a timeframe you can share when this will be available?@NGPixel

**Comment by EricFromCanada** [comment]
Tree-based navigation was added in [2.3.71](https://github.com/Requarks/wiki/releases/tag/2.3.71).
