### ISSUE TITLE
Azure AD redirect_uri adds additional / to value

### ISSUE THREAD

**Issue by pyralix** [Requarks/wiki#1595]
**Describe the bug**
During configuration of Azure AD Authentication, one enter the redirect URI according to the documentation: https://YOUR-WIKI.DOMAIN.COM/login/azure/callback. 

During login, a fiddler captures the GET to login.microsoftonline.com using https://YOUR-WIKI.DOMAIN.COM//login/azure/callback instead. This results in error AADSTS50011 from Microsoft.

Adding the redirect url with the extra / to Azure fixes the auth issue on the Azure side, but the callback is sent to the wrong uri for the wiki.js

**To Reproduce**
1. Install and configure a fresh wiki.js using the AWS Marketplace AMI
2. Setup Azure AD Authentication
3. Start running fiddler, filter on host login.microsoftonline.com
4. Login to your wiki.js using Azure
5. Inspect the GET query string value for redirect_uri
6. Add an additional redirect uri with the extra /
7. Login again, get a 404

**Expected behavior**
https://YOUR-WIKI.DOMAIN.COM/login/azure/callback should be used as the redirect instead of https://YOUR-WIKI.DOMAIN.COM//login/azure/callback.

**Workaround**
Edit Auth.js:
`       stg.config.callbackURL = `${WIKI.config.host}login/${stg.key}/callback`
`

**Screenshots**
![Capture](https://user-images.githubusercontent.com/18315322/77030492-2c16c000-6975-11ea-87e1-696cc62c4f6d.JPG)

**Host Info (please complete the following information):**
 - OS: AWS Marketplace AMI
 - Wiki.js version: 2.0.12

**Comment by NGPixel** [comment]
Make sure the Site URL (under Admin > General) has no trailing slash.

**Comment by pyralix** [comment]
Oh, wow... Thank you for your time 😄
