### ISSUE TITLE
Page Lost

### ISSUE THREAD

**Issue by jackpgao** [Requarks/wiki#160]
### Actual behavior
- After creating a page, and add another page, the first page gone.....
- The 'All Page' is empty, nothing at all....
- Sometimes, I create a same name page, it tells me "This entry already exists!", bug I never found where the page is...

**Comment by NGPixel** [comment]
It's not lost. You simply need to link to it.

So if you create a page `/test`, you must add a link to it (from the homepage for example):

```markdown
[Link to Test](/test)
```
