### ISSUE TITLE
Images not displayed on PUBLIC pages

### ISSUE THREAD

**Issue by DMGMalta** [Requarks/wiki#1601]
**Describe the bug**
When a page is made public (no login required), all images are broken (not displayed).

**To Reproduce**
1. Go to '.Groups & Permissions..' of GUEST (system group)
2. Click on '..Group Permissions..'; allow "read assets"
3. Click on '..Page Permissions..'; allow "read assets"' to a page begininning with ".(specific page name).."
4. No Error; able to READ the page, but the ASSETS (images) are not viewable; showing as broken

**Expected behavior**
View the assets of the page

**Screenshots**
![image](https://user-images.githubusercontent.com/62433743/77172219-e9acca80-6abd-11ea-8115-e8ea0b6c03be.png)

**Host Info (please complete the following information):**
 - OS: [Docker Container (Linux)]
 - Wiki.js version: [2.1.113]
 - Database engine: [postgres 12.2]

**Additional context**
When logged in, images can be viewed.

**Comment by rlarrode** [comment]
Hello DMG Malta, 

I had the same issue and manage it by giving read;assets right on to guest group on the assets storage path and not only to the page path.

Hoping that helps

**Comment by NGPixel** [comment]
As @rlarrode mentionned, you must allow the paths of your assets as well. Including an asset on a page doesn't automatically make it public.
