### ISSUE TITLE
Markdown lists with long lines cause misformatting

### ISSUE THREAD

**Issue by despens** [Requarks/wiki#1602]
**Describe the bug**
When a markdown list contains list entries that do not fit in one line, the list style element is placed on its own separate line. This is happening in markdown preview and the rendered wiki page.

**To Reproduce**
1. Create a markdown document
2. Create an unordered list with line breaks in between the list items

**Expected behavior**
The list should be rendered correctly.

**Screenshots**
![Peek 2020-03-20 16-37](https://user-images.githubusercontent.com/571494/77179728-2631f380-6ac9-11ea-9af0-3db75bed12ab.gif)

**Host Info (please complete the following information):**
 - OS: Ubuntu 18.04, Docker
 - Wiki.js version: 2.1.113
 - Database engine: Postgres 12

**Comment by NGPixel** [comment]
Fixed by 3402afa03c2b4995c062444f8ae4ec10cb4feab0
