### ISSUE TITLE
Scroll up button placed strangely on mobile phone

### ISSUE THREAD

**Issue by joppehoekstra** [Requarks/wiki#1606]
### Actual behavior
When scrolling down on a mobile device, a button appears at the bottom of the screen to scroll up. This button is placed slightly randomly at the right of the side navigation, even if the navigation is hidden.

### Expected behavior
It would make more sense to place it all the way to the right.

### Steps to reproduce the behavior
Scroll down on a mobile device.

**Comment by NGPixel** [comment]
This is already fixed and will be available in the upcoming update.

**Comment by joppehoekstra** [comment]
Awesome, thanks!
