### ISSUE TITLE
Changing default color scheme

### ISSUE THREAD

**Issue by DarkKingKaanMC** [Requarks/wiki#1608]
How to change the default wiki colour (blue) to something else, like orange?

I was trying to do this for 2 days now, with no success.

**Comment by Chandrasekarone** [comment]
@DarkKingKaanMC , It is possible to change the default color by overriding the existing color

Go to : administration -> theme -> inside css injection add the below code

#app .primary {
  background-color: #ff8000 !important;
  border-color: #ff8000 !important
}

**Comment by DarkKingKaanMC** [comment]
Good. It worked. Well, sort of...

What about the blue lines that appear under the heading when you create one?

# HEADING EXAMPLE
------------------------------- < this line is blue

Is it possible to change it, too?

Thanks.

**Comment by chans-me** [comment]
Yeah, it is possible to change that color as well

Follow the same steps and paste the below mentioned code

.v-content .contents h1:after {
    background: linear-gradient(90deg,#ff8000,rgba(25,118,210,0));
}

**Comment by DarkKingKaanMC** [comment]
Hmm, that didn't work.
Do I have to have both codes in the field? I tried that too.

Sorry, it's basically my first time doing this.

**Comment by Smankusors** [comment]
> Yeah, it is possible to change that color as well
> 
> Follow the same steps and paste the below mentioned code
> 
> .v-content .contents h1:after {
> background: linear-gradient(90deg,#ff8000,rgba(25,118,210,0));
> }

I think you forgot to add `!important`

**Comment by DarkKingKaanMC** [comment]
Yep, it worked.

Could you possibly also tell me how to change colour for ''TABLE OF CONTENTS'' text, since I would like everything to match.

You're in great help! Thank you so much!

**Comment by Smankusors** [comment]
> Yep, it worked.
> 
> Could you possibly also tell me how to change colour for ''TABLE OF CONTENTS'' text, since I would like everything to match.
> 
> You're in great help! Thank you so much!

here is the rule you can override

```
.v-application .primary--text {
    color: [your color] !important;
    caret-color: [your color] !important;
}
```

Also, you can find these rules by using DevTools / Inspect Element, which keyboard shortcut is F12. But it is easier for you to just right click which element you want and select inspect element. From there you can see what style rules defined and used by browser.
