### ISSUE TITLE
Search Bar(undefined) gets appended to URL. 

### ISSUE THREAD

**Issue by germora** [Requarks/wiki#161]
### Actual behavior
When a user uses the search bar and clicks on a relevant item then the URL is invalid.
https://docs.requarks.io/undefined/wiki/prerequisites

### Expected behavior
When using search the undefined parameter should not be included in the URL path.

### Steps to reproduce the behavior
- Navigate to the WIKI URL: https://docs.requarks.io/
- Search for something like prerequisites and hover over the link. Notice that there is an undefined text that gets appended to the beginning of the URL. You can also see it in the browser inspector window if you inspect the element.

**Comment by NGPixel** [comment]
Good catch.

**Comment by NGPixel** [comment]
Fixed for Beta 14 (c51d26a02dddd3e1054e374980cd287a05780037)

**Comment by NGPixel** [comment]
Now available in 1.0.1 Release.
