### ISSUE TITLE
Account activation bug; running 2.2 beta from docker-compose

### ISSUE THREAD

**Issue by zachdoty** [Requarks/wiki#1613]
https://www.loom.com/share/b3068e3ae2e54a9599fd898fefb5e1ca

**Comment by Smankusors** [comment]
Is version 2.1 stable runs fine?

**Comment by NGPixel** [comment]
Try to remove any HTML code injection you might have added and disable all analytics modules. That error doesn't come from Wiki.js itself.

**Comment by NGPixel** [comment]
The issue comes from a dependency, follow #1668 going forward. Closing this issue.
