### ISSUE TITLE
Font Awesome Icon in Navigation gets cut off

### ISSUE THREAD

**Issue by Mikes-Git** [Requarks/wiki#1617]
On navigation elements the Font Awesome 5 get cut off on bigger icons
Example:

fas fa-building
fas fa-store-alt

Maybe there is a radius in the CSS?
Regards
Mike

**Comment by Mikes-Git** [comment]
css code injection does not work for this some how
```
.v-avatar {
  border-radius: 0!important
}
.v-icon.v-icon {
  font-size: 20px!important
}
```

**Comment by chris-m92** [comment]
You should be able to use the sizing classes built into Font Awesome to resize natively `fa-sm` or `fa-xs`
