### ISSUE TITLE
SAML SP metadata

### ISSUE THREAD

**Issue by gauburtincc** [Requarks/wiki#1619]
**Question**
Hi,
We recently installed wikiJS and wonder how to get the SP metadata (XML)
We neeed them to configure the SP on the IDP Side
And also : 
IS the SP cert published in the metadata ?
Where can we address the SP about the IDP certificate ?

Thank you for advance,

Gautier

**Host Info (please complete the following information):**
OS:Linux - Debian (buster) 10 x64
Wiki.js version: 2.1.113
Database engine: postgres 9.7

**Comment by ericsopa** [comment]
Same questions.

**Comment by NGPixel** [comment]
Wiki.js implements the [passport-saml](https://github.com/bergie/passport-saml#readme) module as-is.

Refer to it's documentation for any question, as I'm not familiar enough with SAML to answer them.

**Comment by sigfriedseldeslachts** [comment]
Hey @NGPixel 

There should be a web URL which publishes the SAML metadata on the wiki application.
See: https://github.com/node-saml/passport-saml#generateserviceprovidermetadata-decryptioncert-signingcert-
It should be something like _`http://wiki.example.com/saml/metadata`_ and output an XML file.

**Comment by sylmarch** [comment]
I'm not an expert too.

Maybe the exposition of SP metadata could be easy and quick to implement?

See this StackOverflow post: https://stackoverflow.com/a/50682941
