### ISSUE TITLE
Unable to check "Send a welcome email" when creating a new user

### ISSUE THREAD

**Issue by gorgitko** [Requarks/wiki#1620]
**Question**
I am unable to check "Send a welcome email" when creating a new user - the field is disabled. However, I have properly configured the mail (no TLS, no DKIM) and it is working fine when I send a test email.

**Host Info:**
OS: Linux - Debian (buster) 10 x64
Wiki.js version: 2.1.113
Database engine: 10.3.22-MariaDB-0+deb10u1
Node.js version: 13.11.0

Thanks in advance for help!

**Comment by NGPixel** [comment]
This feature is not available yet, which is why it's disabled. Coming in a future release.

**Comment by Dharmesh-Makwana** [comment]
where is this setting ?

**Comment by jray06** [comment]
bump... still hoping for this feature.

**Comment by rainman0607** [comment]
@NGPixel  Is this still planned?

**Comment by LokeYourC3PH** [comment]
Lmao after 4 years it's still disabled, I can't even 😂

**Comment by AMDphreak** [comment]
> Lmao after 4 years it's still disabled, I can't even 😂

yeah, seriously, like what happened, did they all die?

**Comment by Sammeeeeeeee** [comment]
Bump. Spent some time troubleshooting before searching and seeing its been disabled for years :(

**Comment by dnburgess** [comment]
Seriously? It's been more than 4 years at this point. 

Why is the placeholder there if the functionality isn't built? 

I'm trying to add multiple people and I'm going to have to, what, set up each account and then manually email each person individually with their temporary password?

This is really frustrating.

**Comment by urda** [comment]
Bummer to see this is the reason! Thought I had a mail misconfiguration. I imagine this also applies to the "disabled" e-mail button on a user's password field, to ask them to reset it.

**Comment by sv-hmelevsky** [comment]
I see I'm not the only one. I thought it was a problem with the mail settings. Turns out it's a dead feature. That's sad.

**Comment by dnburgess** [comment]
Yeah. Sad that it's "Coming in a future release." nearly 5 years later.

**Comment by mh27588** [comment]
Well... 5 and a half years, the same question being asked. I can safely say this comes across as an actual joke. Why not just remove the disabled tickbox at this stage, or implement the feature?!

**Comment by Sammeeeeeeee** [comment]
Considering that in the last year there has been bearly any progress, and most of the commits are readme changes etc, I am leaving to a different project. This email issue was the last straw for me. Why on god green earth has this option been here for FIVE years?

**Comment by ibuntumain** [comment]
yeah they dont put any work into this project, its pretty much dead
