### ISSUE TITLE
WikiJS not authenticating on Gitlab -- callback ends on Proxy error 502

### ISSUE THREAD

**Issue by chbrandt** [Requarks/wiki#1621]
**Describe the bug**
I'm getting the following message from self-hosted Gitlab instance when callback WikiJS:
```
Proxy Error
The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request GET /login/gitlab/callback.

Reason: Error reading from remote server
```
**To Reproduce**

1. Create Gitlab app with callback `https://wiki.europlanet-gmap.eu/login/gitlab/callback`: set not trusted app, yes confidential; allow read_user, openid, profile, email.
2. Enable Gitlab authentication allowing for self-registration
3. Go to WikiJS and try Gitlab authentication

**Expected behavior**
The authentication of user.

**Screenshots**

![image](https://user-images.githubusercontent.com/482051/77481999-32011b00-6e25-11ea-9e3a-b425b6b64379.png)

![image](https://user-images.githubusercontent.com/482051/77481378-d1bda980-6e23-11ea-9eeb-cb6316e8095c.png)

**Host Info (please complete the following information):**
 - OS: CentOS 7
 - Wiki.js version: 2.1.113
 - Database engine: postgres 11.7

**Additional context**

**Comment by Smankusors** [comment]
Is your wiki behind proxy?

**Comment by chbrandt** [comment]
No, it was not. I was running from inside Docker though.
