### ISSUE TITLE
LDAP  getaddrinfo EAI_AGAIN 

### ISSUE THREAD

**Issue by dwdewang** [Requarks/wiki#1622]
Hi, I have a problem with the login function，When a user login in using LDAP, such an error occurs：**getaddrinfo EAI_AGAIN xxxx.com**. LDAP can be used normally at the beginning. After using it for a month, the problem suddenly appeared.
I can be sure that the LDAP service can be connected because other web services on the same machine can be used normally. But the other web services is not docker container.
I user docker compose to deploy on Debian.
`version: "3"
services:

  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wikijsrocks
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data

  wiki:
    image: requarks/wiki:2
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijsrocks
      DB_NAME: wiki
    restart: unless-stopped
    ports:
      - "80:3000"
volumes:
  db-data:
`

If you have encountered this problem or solved it, thank you very much for your help！！！

**Comment by Smankusors** [comment]
Can you give us more error details? Logs from container? Logs from client side? What is your Wiki.js exact version?

**Comment by dwdewang** [comment]
> Can you give us more error details? Logs from container? Logs from client side? What is your Wiki.js exact version?

This is the log content from docker container when I open LDAP debug flag:
**{"log":"2020-03-26T01:23:10.483Z [MASTER] \u001b[33mwarn\u001b[39m: LDAP LOGIN ERROR (c1): getaddrinfo EAI_AGAIN xxxxx.com\n","stream":"stdout","time":"2020-03-26T01:23:10.483438385Z"}**

When the user login with ldap,He could see the hint：**getaddrinfo EAI_AGAIN xxx.com**

My wikijs version is **2.1.113**
@Smankusors

**Comment by Smankusors** [comment]
where do you run this? Can you give host/server information?

**Comment by dwdewang** [comment]
> where do you run Wiki.js? Can you give host/server information?

I run Wikijs on Debian linux machine, I build server with docker compose, Others can not visit beacuse this service is built in the inline Intranet environment of our company

@Smankusors

**Comment by Smankusors** [comment]
is this happens until restart every month? Or just happens for several minutes/hours and then runs fine?

**Comment by dwdewang** [comment]
@Smankusors It appears suddenly about a month after the service is running normally. Even if the service is restarted, there are still problems. Now there are still problems too.

**Comment by dwdewang** [comment]
Now Whatever I write into the config, It occurs the same error
![image](https://user-images.githubusercontent.com/11647289/77720340-9a691b80-7022-11ea-8f16-0e65ac3cde68.png)
![image](https://user-images.githubusercontent.com/11647289/77720353-a81ea100-7022-11ea-93ed-72880860a7ea.png)
@Smankusors

**Comment by Smankusors** [comment]
It could be problem with the DNS server you are using

**Comment by dwdewang** [comment]
Then should I change the DNS configuration of docker? Or I should change the DNS configuration of the linux machine?
@Smankusors

**Comment by dwdewang** [comment]
Thank you very much for your help. I have solved this problem by modifying the DNS configuration of the docker container.But I still wonder why there was no problem in the beginning, the problem didn't appear until it was used for some time

@Smankusors Thanks

**Comment by dwdewang** [comment]
![image](https://user-images.githubusercontent.com/11647289/77742608-b0da9b80-7051-11ea-98c4-9c638d93a9ca.png)
Solved by adding dns configuration
