### ISSUE TITLE
Unable creating page for regular users

### ISSUE THREAD

**Issue by victor1234** [Requarks/wiki#1623]
After fresh installation I set admin login/pass. Signed in as admin and created home page.
After that I create users group with permission to add/del/edit pages and added one regular user to this group. But he cannot create any page.

Error:
```
Unauthorized
You cannot create the page
```

 - OS: [ 18.04 x64]
 - Wiki.js version: [2.1.113]
 - Database engine: [postgres 10.12]

**Comment by Smankusors** [comment]
Can you give us the permission details? What permissions you given for your "users" group? What is your page rules?

**Comment by victor1234** [comment]
Sure.
https://imgur.com/F4L7oYE
https://imgur.com/blgICJL

Thanks

**Comment by victor1234** [comment]
@Smankusors Thanks. You are right.
I should carefully read the tutorial.
