### ISSUE TITLE
Unable to login to newly created app

### ISSUE THREAD

**Issue by yuri-karpovich** [Requarks/wiki#1625]
**Describe the bug**
Error on login page

**To Reproduce**
1. Install from docker
2. register admin user
3. try to login

**Screenshots**
![image](https://user-images.githubusercontent.com/7230069/77621008-9d91d800-6f4c-11ea-9d6a-b51c2017f94a.png)

**Host Info (please complete the following information):**
 - OS: Docker
 - Wiki.js version: 2.1.113
 - Database engine: postgres 11

**Comment by Smankusors** [comment]
can you try with incognito mode?

**Comment by yuri-karpovich** [comment]
My bad. Sorry!

**Comment by Smankusors** [comment]
can you tell me what happened? Is using incognito mode works? Or did you already found a culprit in your Chrome profile?

**Comment by yuri-karpovich** [comment]
It works fine in incognito mode

**Comment by Smankusors** [comment]
Then your Chrome might have a extension that caused this error. You need to find this extension and disable it so you can use wiki in non incognito.

But if you fine with incognito mode, well that's okay too
