### ISSUE TITLE
script tag for asciinema player is not working

### ISSUE THREAD

**Issue by al3x609** [Requarks/wiki#1626]
**Describe the bug**
I cannot integrate asciinema player on wiki js.

**Expected behavior**
Asciinema rendering module was enabled in configuration.

**Screenshots**

<img width="726" alt="screnshot 2020-03-26 at 8 52 51" src="https://user-images.githubusercontent.com/4086644/77654538-315ca780-6f3f-11ea-9b4a-0724b0c2d391.png">

**Host Info (please complete the following information):**
 - OS: docker compose up 
 - Wiki.js version: 2:beta

**Additional context**
How can I allow script tags on my site?

**Comment by NGPixel** [comment]
Automatic asciinema is not yet available. It's coming in a future release.
