### ISSUE TITLE
WYSIWYG editor crashing on medium to large size pages

### ISSUE THREAD

**Issue by pdennis** [Requarks/wiki#1629]
**Describe the bug**
unable to create wysiwyg pages above a certain size. Roughly 92,000 characters for plain text, fewer for rich text. UI throws up this error: "Network error: JSON.parse: unexpected character at line 1 column 1 of the JSON data" and then hangs forever without saving content. 

**To Reproduce**
1. Create a new page in the WYSIWYG editor
2. Paste in roughly 100,000 characters of text, or simply a 30ish page word document with rich text
3. attempt to save

**Expected behavior**
This wiki is intended to replace a large number of unwieldy word documents, and the de facto page limit is requiring time-consuming work arounds, such as splitting them up 

**Screenshots**

**Host Info (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04, Docker]
 - Wiki.js version: 2.1.113
 - Database engine: PostgreSQL 11.6 db

Operating System: Ubuntu 18.04 (standard digitalocean 1 click setup)
Docker Container (Linux)
CPU Cores: 2
Total RAM 1.95 GB

**Additional context**
I tried bumping up my core count to to two, and ram to 2gb, but that didn't help. Suspect it's something with the database, an area i have 0 experience with.

**Comment by pdennis** [comment]
ALSO, i have received the same "Network error: JSON.parse: unexpected character at line 1 column 1 of the JSON data" on large markdown edited pages in a similar fashion, but i was always able to resolve this by finding a formatting error somewhere. Unfortunately, I do need to use the WYSIWYG editor for non-technical staff to update pages

**Comment by NGPixel** [comment]
This is fixed in 2.2.

**Comment by pdennis** [comment]
Thanks, I'll try to hold tight until that comes out.
