### ISSUE TITLE
503 error on host after browser set up

### ISSUE THREAD

**Issue by samrawks** [Requarks/wiki#163]
### Actual behavior
I'm attempting to install wiki.js on a Mac mini Server running El Capitan with Node v6.11.1, MongoDB 3.2.8 and Git 2.13.1.

Setting up wiki.js through the terminal and browser (Chrome 59) works as expected but after starting the server the host returns a 503 error any time I visit it.

### Expected behavior
Visiting our host (wiki.example.com) should show wiki.js as normal without a 503 error.

### Steps to reproduce the behavior
Before running through the wiki.js set up, I created a DNS entry in our registrar for the subdomain we'd like to use (wiki.example.com) that points to our server IP.

We're using Apache in MAMP too so I created a Virtual Host entry at /conf/apache/extra/httpd-vhosts.conf as follows:
`<VirtualHost *:80>`
    `DocumentRoot "/Users/administrator/Sites/wikijs"`
    `ServerName wiki.example.com`
    `ProxyPass / http://127.0.0.1:3000/`
    `ProxyPassReverse / http://127.0.0.1:3000/`
`</VirtualHost>`

During the wiki.js terminal/browser set up, I set the port to 80 and the host to wiki.example.com to match the above settings. Everything checks out but afterwards when I'm sent to the host all I get is a 503 error.

Checking the Apache logs I'm seeing this after each time I try to visit the host:
`Connection refused: proxy: HTTP: attempt to connect to 127.0.0.1:3000 (127.0.0.1) failed`
`ap_proxy_connect_backend disabling worker for (127.0.0.1)`

Looks like something is blocking the connection to the local URL but I have no ideas as to why this is happening. I understand that this is more to do with Apache and that wiki.js itself is likely to be working normally but any help would be appreciated if anyone's seen this kind of thing before.

The wiki.js logs say:
`Listening on port 80 requires elevated privileges!`
I also looked through the troubleshooting documentation but solutions A&B weren't particular to a Mac and solution C was what I thought I was doing with our Virtual Host entry!

Unfortunately, we have other services running off Apache on port 80 (different local ports) so I can't switch over to Nginx or use a different port to listen on.

**Comment by NGPixel** [comment]
1) You set Wiki.js to listen on port 80, but your reverse proxy is set to port 3000. They must match.

2) The error `Listening on port 80 requires elevated privileges!` means your system does not allow non-system apps to listen to port 80. Using a port above 1024 will fix this issue. However, considering you're using a reverse proxy, you should use a port like 3000 instead, not 80 (which is what Apache listens on).

**Comment by samrawks** [comment]
@NGPixel I switched the port from 80 to 3000 in the config.yml and it's all working as expected now. I suspected it would be a small misunderstanding somewhere on my part.

Thanks for your help!
