### ISSUE TITLE
Cannot load wiki.js

### ISSUE THREAD

**Issue by TheProgramSrc** [Requarks/wiki#1631]
**Describe the bug**
Every time that i use the command 'node server' this happens

**To Reproduce**
1. use the command 'node server'

**Expected behavior**
Show a message that says I can open the browser

**Screenshots**

**Host Info (please complete the following information):**
 - Ubuntu 16
 - Wiki.js version: latest
 - Database engine: mysql latest

**Error log**
let WIKI = {
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

**Comment by NGPixel** [comment]
Are you using Node.js 10.12 or later?

**Comment by Smankusors** [comment]
you describe latest version is not really helpful. You need to specify the version.

For example, you think your mysql is latest version, but you installed it from Ubuntu official repo, which is 5.7.29. But the real latest version is 8.0.19.

Btw, you tell that your Ubuntu is version 16, which I guess your node.js version could be 4.2.6, which is too old for Wiki.js

**Comment by TheProgramSrc** [comment]
yes, I'm using node 4.2.6...

**Comment by TheProgramSrc** [comment]
Now I updated node to 8.17.0

**Comment by TheProgramSrc** [comment]
Now it's working.
I used this command to update node
`wget -qO- https://deb.nodesource.com/setup_8.x | sudo bash -
sudo apt-get install -y nodejs`
