### ISSUE TITLE
Cannot start service 'wiki'

### ISSUE THREAD

**Issue by TheProgramSrc** [Requarks/wiki#1632]
**Describe the bug**
I cannot start the serve wiki

**To Reproduce**
1. Run in console 'sudo service wiki start'
2. Run in the console 'journalctl -u wiki'
3. See error

**Expected behavior**
The service starts successfully

**Log Error**
Started Wiki.js.
wiki.service: Main process exited, code=exited, status=217/USER
wiki.service: Unit entered failed state.
wiki.service: Failed with result 'exit-code'.
wiki.service: Service hold-off time over, scheduling restart.
Stopped Wiki.js.

**Host Info (please complete the following information):**
 - OS: Ubuntu 16.04
 - Wiki.js version: 2.1.113
 - Database engine: MySQL 5.7.29
 - Node Version: 12.16.1

**Comment by sbonaime** [comment]
Can you explain how you solve your problem ?

**Comment by TheProgramSrc** [comment]
I've reinstalled wiki.js
