### ISSUE TITLE
Material Icons display error

### ISSUE THREAD

**Issue by liogate** [Requarks/wiki#1635]
**Describe the bug**

Hi,

All material icons are not working on system dashboard ui.

Thank you a lot for your help.

Best regards

**To Reproduce**

1. Upgrading docker image
2. Open the dashboard

**Expected behavior**

Using right material-icons

**Screenshots**

![image](https://user-images.githubusercontent.com/17850842/77891304-0b057780-7271-11ea-8f8d-c28af72ef952.png)

**Host Info (please complete the following information):**

 - OS: Docker
 - Wiki.js version: 2.2.51
 - Database engine: postgres 9.7

**Additional context**

Bug appeared when updating 2.1.113 to 2.2.51

**Comment by sbonaime** [comment]
I have the same bug

OS: Docker
Linux - Debian (stretch) 9.12 x64
Wiki.js version: 2.2.51
Database engine: postgres 9.6.17
Node.js 12.16.1

**Comment by Smankusors** [comment]
I think this is related to https://github.com/Requarks/wiki/issues/1633, try to clear your browser cache

**Comment by liogate** [comment]
I've already tried with Cmd + Shift + R, private navigation or 
![Capture d’écran 2020-03-30 à 11 31 20](https://user-images.githubusercontent.com/17850842/77897536-14471200-727a-11ea-8138-336af63a9566.png)

But still got the same issue.

**Comment by sbonaime** [comment]
I don't have the problem with another browser. @liogate You can try with Firefox or you can open an anonymous window.

**Comment by sbonaime** [comment]
To clear the cache I successfully follow those steps :

https://pitdesigns.com/en/how-to-clear-chrome-cache-for-specific-website-only-3-steps/

**Comment by liogate** [comment]
Thanks, I did it and the cache issue still persist on chrome but not for other browsers (tested with Safari), even in anonymous window... 🤔 
Hope users will not have the same issue on each update.

**Comment by sbonaime** [comment]
@liogate Did you also clear the cookies ? With chrome, you have to click the padlock on the left of the address, click cookies and delete all.

**Comment by Smankusors** [comment]
> Thanks, I did it and the cache issue still persist on chrome but not for other browsers (tested with Safari), even in anonymous window... 🤔
> Hope users will not have the same issue on each update.

even in incognito? that's weird... how about fresh/new profile on Chrome?

**Comment by NGPixel** [comment]
Closing this issue as this is a browser caching issue and unrelated with wiki.js itself.

This change occured because the material design icons library was updated from 4.x to 5.x, which had breaking changes. The new assets have to be reloaded to display correctly again.
