### ISSUE TITLE
Update to 2.2.51 from 2.1.113 busted for MSSSQL

### ISSUE THREAD

**Issue by bsitko** [Requarks/wiki#1642]
**Describe the bug**
When trying to launch Wiki.js after updating the files, get a 500 error.

**To Reproduce**
Here are the errors:

[33mmigration file "2.2.17.js" failed[39m
[33mmigration failed with error: UPDATE "pageHistory" h1 SET "versionDate" = COALESCE((SELECT TOP 1 prev."createdAt" FROM "pageHistory" prev WHERE prev."pageId" = h1."pageId" AND prev.id < h1.id ORDER BY prev.id DESC), h1."createdAt") - Incorrect syntax near the keyword 'ORDER'.[39m
2020-03-30T20:05:47.391Z [MASTER] [31merror[39m: Database Initialization Error: UPDATE "pageHistory" h1 SET "versionDate" = COALESCE((SELECT TOP 1 prev."createdAt" FROM "pageHistory" prev WHERE prev."pageId" = h1."pageId" AND prev.id < h1.id ORDER BY prev.id DESC), h1."createdAt") - Incorrect syntax near the keyword 'ORDER'.

First, it's using a bad SQL query to update a column which does not exist in the database.The correct SQL query should look like this:

sqlVersionDate = 'UPDATE "pageHistory" SET "versionDate" = COALESCE((SELECT TOP 1 prev."createdAt" FROM "pageHistory" prev WHERE prev."pageId" = "pageHistory"."pageId" AND prev.id < "pageHistory".id ORDER BY prev.id DESC), "pageHistory"."createdAt")'

However, this needs to run AFTER it sets up the actual column in the next step. Had to run this process manually.

**Expected behavior**
The order is not correct. It should check for the prescence of the column first, if not detected, create it AND then add the default entries using the correct SQL Syntax. 

**Host Info (please complete the following information):**
 - OS: Windows Server 2019.
 - Wiki.js version:Update to 2.2.51 from 2.1.113
 - Database engine: MSSQL

[WEBSERVER-8928-stdout-1585598745578.txt](https://github.com/Requarks/wiki/files/4405222/WEBSERVER-8928-stdout-1585598745578.txt)

**Comment by burnbern** [comment]
You can still use named shortcuts in MSSQL, the fixed statement would look like this:
`sqlVersionDate = 'UPDATE h1 SET "versionDate" = COALESCE((SELECT TOP 1 prev."createdAt" FROM "pageHistory" prev WHERE prev."pageId" = h1."pageId" AND prev.id < h1.id ORDER BY prev.id DESC), h1."createdAt") FROM "pageHistory" h1'
      `

**Comment by bsitko** [comment]
I'm sorry. You're so right. Forgot about that if you just drop it at the end. Obviously I use the full name and don't abbreviate my update queries

**Comment by Smankusors** [comment]
Can you give us what Microsoft SQL version you are using?

**Comment by bsitko** [comment]
SQL server 2014

**Comment by burnbern** [comment]
We are using SQL Server 2012 (11..0.7001.0) and SQL Server 2017 (14.0.2027.2).

**Comment by andjelatomic** [comment]
Dears,

I have the other problem. I am  using the MSSQL server, on a different machine, and it was working fine with the previous version, but in the latest one there are some SQL syntax errors, like 

2020-04-02T11:29:38.416Z [MASTER] info: Database Connection Successful [ OK ]
migration file "2.2.17.js" failed
migration failed with error: UPDATE "pageHistory" h1 SET "versionDate" = COALESCE((SELECT prev."createdAt" FROM "pageHistory" prev WHERE prev."pageId" = h1."pageId" AND prev.id < h1.id ORDER BY prev.id DESC LIMIT 1), h1."createdAt") - Incorrect syntax near the keyword 'ORDER'.
2020-04-02T11:29:38.889Z [MASTER] error: Database Initialization Error: UPDATE "pageHistory" h1 SET "versionDate" = COALESCE((SELECT prev."createdAt" FROM "pageHistory" prev WHERE prev."pageId" = h1."pageId" AND prev.id < h1.id ORDER BY prev.id DESC LIMIT 1), h1."createdAt") - Incorrect syntax near the keyword 'ORDER'.
root@wiki01:~/wiki# 



MSSQL VERSION:
1> SELECT @@VERSION
2> GO

Microsoft SQL Server 2017 (RTM-CU19) (KB4535007) - 14.0.3281.6 (X64) 
	Jan 23 2020 21:00:04 
	Copyright (C) 2017 Microsoft Corporation
	Standard Edition (64-bit) on Linux (CentOS Linux 7 (Core))
(1 row affected)
1> 


Is there anywhere debugged version, or I have to debug it on my own?

Winds, galaxies and regards
Andjela

**Comment by andjelatomic** [comment]
It has been done, thank you!
A.

**Comment by iLucasBernardes** [comment]
Any tips for mariaDB?
Same mistake here.

**Comment by Smankusors** [comment]
> Any tips for mariaDB?
> Same mistake here.

MariaDB/MySQL is discussed on #1610

**Comment by NGPixel** [comment]
Fixed by 245104c6ae771076a971e92af938d85a668526f8

Thanks to @bsitko and @burnbern for the fixed statement.
