### ISSUE TITLE
Cannot login to wiki using Google.

### ISSUE THREAD

**Issue by viruscmd** [Requarks/wiki#1644]
**Question**
I have followed the instructions [here](https://docs.requarks.io/en/auth/google) to configure google login. However, after selecting the user i am redirected to a page that is reads **"Oops, something went wrong... Unauthorized"**

What am i doing wrong?

**Host Info (please complete the following information):**
OS: Amazon Linux
Wiki.js version: 2.2.51
Database engine: postgresql 9.2.24

**Comment by NGPixel** [comment]
Did you set proper page rules on the group being assigned to new users?

**Comment by viruscmd** [comment]
I think so. Do this look right?

<img width="1920" alt="Screen Shot 2020-03-31 at 2 11 01 PM" src="https://user-images.githubusercontent.com/2870626/78060501-9c501900-7359-11ea-98b8-ab4a400a45ea.png">

**Comment by viruscmd** [comment]
There was a bad character in the secret key.

**Comment by candcdev** [comment]
In my case I had the wrong secret key. Although this was difficult as not even `LOG_LEVEL=debug` helped
