### ISSUE TITLE
High availabily is flaky

### ISSUE THREAD

**Issue by rgarrigue** [Requarks/wiki#1646]
**Describe the bug**

I've a couple of HAProxy, serving (round robin) a couple of Nginx serving (round robin) a couple of local wikijs. And a postgresql database. Both haproxies and nginx are deployed identically via Ansible. WikiJS is version 2.2.51 installed from Github's tar.gz. There's `ha: True` in my config.

And I keep getting bunch of red banners around in the administration area while connected as the local Administrator. Stuff like `You are not authorized to access this resource.`. Refreshing end up with a OK. Sometimes.

**To Reproduce**

I guess running 2 wikijs served in round robin would do.

**Expected behavior**

A working wikijs, without random errors

**Host Info (please complete the following information):**

 - OS: Debian 10
 - Wiki.js version: 2.2.51
 - Database engine: postgres 11.5
- NodeJS: 10.15.2

On AWS EC2 / RDS

**Comment by NGPixel** [comment]
HA is not available yet. It's planned for 2.3.

Follow #1419
