### ISSUE TITLE
No title padding on mobile

### ISSUE THREAD

**Issue by depict1** [Requarks/wiki#1647]
**Describe the bug**
No padding on title and logo on mobile, compared to PC. 

**Screenshots**

![image](https://user-images.githubusercontent.com/57202889/78034502-6e54df80-732d-11ea-97f5-12af0d44ec05.png)

**Host Info (please complete the following information):**
 2.2.50

**Comment by sbonaime** [comment]
@depict1 you can close your issue which is solved by 19361e9
