### ISSUE TITLE
Footer copyright not appearing and license is broke

### ISSUE THREAD

**Issue by depict1** [Requarks/wiki#1649]
**Describe the bug**
Nothing shows up on footer and the labels are broke

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/57202889/78035002-1ff41080-732e-11ea-812b-60c9ec8e87f0.png)
![image](https://user-images.githubusercontent.com/57202889/78035020-25515b00-732e-11ea-8869-0dfdb087f866.png)

**Host Info (please complete the following information):**
2.2.50
docker-compose
ubuntu

**Comment by NGPixel** [comment]
Is `offline` set to `true` in your config.yml by any chance?

**Comment by depict1** [comment]
No? My wiki is viewable by thousands a day. I copied your .yml file.

`version: "3"
services:

  db:
    image: postgres:9-alpine
    restart: always
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wikijsrocks
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - wikinet

  wiki:
    image: requarks/wiki:2
    restart: always
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijsrocks
      DB_NAME: wiki
    networks:
      - wikinet
    ports:
      - "3000:3000" # <-- here you can replace with "80:3000" to listen on port 80 instead, as an example

networks:
  wikinet:

volumes:
  db-data:
`

**Comment by NGPixel** [comment]
Restart the wiki (`docker-compose restart wiki`) then post the logs (`docker-compose logs wiki`)

**Comment by depict1** [comment]
> Restart the wiki (`docker-compose restart wiki`) then post the logs (`docker-compose logs wiki`)

Nothing interesting or out of the ordinary. Just about 5000 lines of git repo messages. Anything specifically you're looking for?

**Comment by depict1** [comment]
Here is the logs after all the git stuff.

`
wiki_1  | 2020-04-01T03:31:47.446Z [MASTER] info: Syncing with storage target git: [ COMPLETED ]
wiki_1  | Loading configuration from /wiki/config.yml... OK
wiki_1  | 2020-04-01T03:34:36.639Z [MASTER] info: =======================================
wiki_1  | 2020-04-01T03:34:36.641Z [MASTER] info: = Wiki.js 2.2.50 ======================
wiki_1  | 2020-04-01T03:34:36.641Z [MASTER] info: =======================================
wiki_1  | 2020-04-01T03:34:36.641Z [MASTER] info: Initializing...
wiki_1  | 2020-04-01T03:34:36.989Z [MASTER] info: Using database driver pg for postgres [ OK ]
wiki_1  | 2020-04-01T03:34:37.002Z [MASTER] info: Connecting to database...
wiki_1  | 2020-04-01T03:34:37.026Z [MASTER] info: Database Connection Successful[ OK ]
wiki_1  | 2020-04-01T03:34:37.737Z [MASTER] warn: Mail is not setup! Please setthe configuration in the administration area!
wiki_1  | 2020-04-01T03:34:37.801Z [MASTER] info: Loading GraphQL Schema...
wiki_1  | 2020-04-01T03:34:37.938Z [MASTER] info: GraphQL Schema: [ OK ]
wiki_1  | 2020-04-01T03:34:38.224Z [MASTER] info: HTTP Server on port: [ 3000 ]
wiki_1  | 2020-04-01T03:34:38.249Z [MASTER] info: HTTP Server: [ RUNNING ]
wiki_1  | 2020-04-01T03:34:38.355Z [MASTER] info: No new analytics providers found: [ SKIPPED ]
wiki_1  | 2020-04-01T03:34:38.436Z [MASTER] info: No new authentication strategies found: [ SKIPPED ]
wiki_1  | 2020-04-01T03:34:38.451Z [MASTER] info: No new editors found: [ SKIPPED ]
wiki_1  | 2020-04-01T03:34:38.482Z [MASTER] info: No new loggers found: [ SKIPPED ]
wiki_1  | 2020-04-01T03:34:38.543Z [MASTER] info: No new renderers found: [ SKIPPED ]
wiki_1  | 2020-04-01T03:34:38.575Z [MASTER] info: No new search engines found: [SKIPPED ]
wiki_1  | 2020-04-01T03:34:38.607Z [MASTER] info: No new storage targets found:[ SKIPPED ]
wiki_1  | 2020-04-01T03:34:38.612Z [MASTER] info: Authentication Strategy local:[ OK ]
wiki_1  | 2020-04-01T03:34:38.625Z [MASTER] info: (STORAGE/GIT) Initializing...
wiki_1  | 2020-04-01T03:34:38.637Z [MASTER] info: (STORAGE/GIT) Checking repository state...
wiki_1  | 2020-04-01T03:34:38.661Z [MASTER] info: (STORAGE/GIT) Listing existingremotes...
wiki_1  | 2020-04-01T03:34:38.667Z [MASTER] info: (STORAGE/GIT) Purging existingremotes...
wiki_1  | 2020-04-01T03:34:38.673Z [MASTER] info: (STORAGE/GIT) Setting SSL Verification config...
wiki_1  | 2020-04-01T03:34:38.678Z [MASTER] info: (STORAGE/GIT) Setting SSH Command config...
wiki_1  | 2020-04-01T03:34:38.683Z [MASTER] info: (STORAGE/GIT) Adding origin remote via SSH...
wiki_1  | 2020-04-01T03:34:38.689Z [MASTER] info: (STORAGE/GIT) Fetch updates from remote...
wiki_1  | 2020-04-01T03:34:39.232Z [MASTER] info: (STORAGE/GIT) Checking out branch master...
wiki_1  | 2020-04-01T03:34:39.253Z [MASTER] info: (STORAGE/GIT) Performing pushto origin on branch master...
wiki_1  | 2020-04-01T03:34:40.098Z [MASTER] info: (STORAGE/GIT) Initialization completed.
wiki_1  | 2020-04-01T03:34:40.103Z [MASTER] info: Purging orphaned upload files...
wiki_1  | 2020-04-01T03:34:40.112Z [MASTER] info: Syncing locales with Graph endpoint...
wiki_1  | 2020-04-01T03:34:40.114Z [MASTER] info: Fetching latest updates from Graph endpoint...
wiki_1  | 2020-04-01T03:34:40.157Z [MASTER] info: Purging orphaned upload files:[ COMPLETED ]
wiki_1  | Loading configuration from /wiki/config.yml... OK
wiki_1  | 2020-04-01T03:34:40.336Z [JOB] info: Rebuilding page tree...
wiki_1  | 2020-04-01T03:34:40.378Z [MASTER] info: Fetching latest updates from Graph endpoint: [ COMPLETED ]
wiki_1  | 2020-04-01T03:34:40.397Z [MASTER] info: Syncing locales with Graph endpoint: [ COMPLETED ]
wiki_1  | 2020-04-01T03:34:40.564Z [JOB] info: Using database driver pg for postgres [ OK ]
wiki_1  | 2020-04-01T03:34:40.716Z [JOB] info: Rebuilding page tree: [ COMPLETED       `

**Comment by depict1** [comment]
> What Locale are you using?
> Please check if you can reproduce the issue with English first.

I am on English, yes.

**Comment by dcfreedom** [comment]
Looks like you have an in complete locale file.
Try to update your locale file in the admin area.
Site, Locale, Download Locale.
Make sure English has green check mark

Here's mine.

<img width="481" alt="pic20200405" src="https://user-images.githubusercontent.com/6317991/78463603-53a9ae80-7711-11ea-901f-29dc30f5bc2c.png">

**Comment by depict1** [comment]
> Looks like you have an in complete locale file.
> Try to update your locale file in the admin area.
> Site, Locale, Download Locale.
> Make sure English has green check mark
> 
> Here's mine.
> 
> <img alt="pic20200405" width="481" src="https://user-images.githubusercontent.com/6317991/78463603-53a9ae80-7711-11ea-901f-29dc30f5bc2c.png">

Thanks. Updating that fixed the "saved.saved" button being broken but the footer not showing and the drop down still being broken persists.

**Comment by NGPixel** [comment]
You have to select a footer license for it to appear.

Try to clear your cache again (F12 > Applicaiton > Clear storage > Clear site data, then reload the page).

**Comment by depict1** [comment]
> You have to select a footer license for it to appear.
> 
> Try to clear your cache again (F12 > Applicaiton > Clear storage > Clear site data, then reload the page).

I have cleared my cache, yes. Sorry, I mean that the drop downs are still not appearing.


![image](https://user-images.githubusercontent.com/57202889/78466045-8c6e6700-76c2-11ea-8b57-3bad5cdb7150.png)

![image](https://user-images.githubusercontent.com/57202889/78466046-91331b00-76c2-11ea-80a1-7d061ba5364f.png)
