### ISSUE TITLE
Port configured in config.yml but not being used to serve assets

### ISSUE THREAD

**Issue by rjkowalewski** [Requarks/wiki#165]
I have successfully install Wiki.js by completing the interactive setup. However, after I have now restarted the app with `node wiki start` the port which is configured in `config.yml` to be `3000` does not appear to be being used and therefore assets such as `.js` files are not being loaded and I have no styling etc.

**Comment by NGPixel** [comment]
You must add the port to the `host` setting as well. `port` is what the server listens to, while `host` is the client domain + port. When using a reverse proxy, they can be different.

**Comment by rjkowalewski** [comment]
Haha that simple! Cheers and great work by the way this is a really exciting project!!
