### ISSUE TITLE
Account button cutoff on mobile

### ISSUE THREAD

**Issue by depict1** [Requarks/wiki#1651]
**Describe the bug**
On my iPhone XS the Account button is cutoff. 

**To Reproduce**
1. Go on mobile and it will be cutoff.

**Expected behavior**
The button to not be cutoff.

**Screenshots**

![image](https://user-images.githubusercontent.com/57202889/78035495-ce985100-732e-11ea-933c-f87ebfc3f711.png)

**Host Info (please complete the following information):**
2.2.50

**Additional context**

**Comment by sbonaime** [comment]
@depict1 you can close your issue which is solved by #1697
