### ISSUE TITLE
Cannot write Code proberly

### ISSUE THREAD

**Issue by ViroXxZz** [Requarks/wiki#1652]
Usually I used this Code in the Visual Editor so it loooks like code in a shell: 
(look at screen shot 1 and 2)

but after the update it doesn´t work anymore (screenshot 3)

![Screenshot_1](https://user-images.githubusercontent.com/48054902/78041054-9154b300-7370-11ea-8b31-324dc2e5c00b.png)
![Screenshot_2](https://user-images.githubusercontent.com/48054902/78041060-9285e000-7370-11ea-8206-ebfda17073e3.png)
![Screenshot_3](https://user-images.githubusercontent.com/48054902/78041067-93b70d00-7370-11ea-939f-295d8d5841e1.png)

**Comment by NGPixel** [comment]
Which version are you using?

**Comment by ViroXxZz** [comment]
I‘m using the version 2.2.51
Am 31. März 2020, 17:31 +0200 schrieb Nicolas Giard <notifications@github.com>:

**Comment by NGPixel** [comment]
You can't post HTML code directly into the Visual Editor. The fact that it was working before was a rendering bug.

A proper code feature will be added to the Visual Editor in a future version. In the meantime, use the Markdown editor instead.

**Comment by ViroXxZz** [comment]
Ok thank you for your fast response.

Do you know when you are going to release Version 2.2?
Am 1. Apr. 2020, 02:34 +0200 schrieb Nicolas Giard <notifications@github.com>:
