### ISSUE TITLE
Error while using the Git syncronisation

### ISSUE THREAD

**Issue by supralow** [Requarks/wiki#1654]
**Describe the bug**
When using the GIT Storage component, with the same configuration as on 2.1.103, the syncronisation fails with the following message :

`Bad port 'undefined' fatal: Could not read from remote repository. Please make sure you have the correct access rights and the repository exists. error: Could not fetch origin`

**To Reproduce**
1. Configure the GIT storage component
2. Configuration :
**Authentication Type :** SSH
**Repository URL :** git@gitlab.fqdn:name/gitname.git
**Branch :** master
**SSH Private Key :** Content
**Path :** /my/path/key.pem (the rights are set to 600)
**Verify SSL :** No
 

**Expected behavior**
Have the Git syncronisation working

**Screenshots/Logs**
```
2020-04-01T09:26:18.213Z [MASTER] warn: Bad port 'undefined'
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
```

**Host Info (please complete the following information):**
 - OS: Docker
 - Wiki.js version: 2.2.51
 - Database engine: postgres 11

**Additional context**
I've noticed the PORT field disapeared from the UI, and also in BDD.

**Comment by NGPixel** [comment]
Fixed by 4d8d748b1110cb13ebe551cdf1bb375588eae472
