### ISSUE TITLE
Icons missing in Firefox

### ISSUE THREAD

**Issue by jbutz** [Requarks/wiki#1655]
**Describe the bug**
In Firefox many icons are either not displaying or display incorrectly

**To Reproduce**
1. Open the web app in the Firefox web browser
2. The password icon does not render correctly, also many icons in the Admin section

**Expected behavior**
All icons to display correctly instead of displaying the code used for the icon

**Screenshots**
![Screen Shot 2020-04-01 at 8 12 27 AM](https://user-images.githubusercontent.com/736696/78135935-bdb01400-73f0-11ea-913f-180384c27d5c.png)

**Host Info (please complete the following information):**
 - OS: Docker Container (Linux)
 - Wiki.js version: 2.2.51
 - Database engine: postgres 11.7

**Additional context**
I noticed this issue after upgrading from v2.1.113 to v2.2.51 via a docker-compose pull.

**Comment by sbonaime** [comment]
same as #1635 where you can find a solution. I think you can close your issue

**Comment by supralow** [comment]
Hey,

Just empty your browser cache, it should be fine after.

**Comment by jbutz** [comment]
Clearing my browser cache didn't help, but purging the CDN cache did.
