### ISSUE TITLE
Removing all rights from group "Guest" still allows to view Wiki

### ISSUE THREAD

**Issue by manraf** [Requarks/wiki#1656]
**Describe the bug**
Although I have removed all rights from the user group "Guest" (as described here: https://docs.requarks.io/groups#private-wiki), unauthorized (i.e. not logged in) users can still view all pages. 

**To Reproduce**
1. Remove all rights from user group "Guest"
2. Log out
3. Access Wiki anonymously

**Expected behavior**
Redirection to login screen or at least "You're not authorized." page.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/24991230/78144576-14890e00-7430-11ea-857e-aaa36851a58f.png)

**Host Info (please complete the following information):**
 - OS: Official Docker image
 - Wiki.js version: 2.2.51
 - Database engine: postgres 9.6.15

**Additional context**
"LDAP / Active Directory" authentication is enabled.

**Comment by rlarrode** [comment]
Hi manraf,

Can you please provide a screen shot of the PAGE RULES tab?

Thanks

**Comment by Smankusors** [comment]
I gotta say, there's something weird when I tried to replicate this. It needs several seconds/minutes before the applied permissions have effect on wiki. But if I'm using page rules, it is immediately have effect on wiki.

But if you can't wait, you can just restart the server and see if there's any effect.

**Comment by manraf** [comment]
> 
> 
> Hi manraf,
> 
> Can you please provide a screen shot of the PAGE RULES tab?
> 
> Thanks

![grafik](https://user-images.githubusercontent.com/24991230/78347840-584f5500-75a1-11ea-8681-0a1ee9820102.png)

Do those have any effect if no content permissions are enabled? The message on top ("You must enable [...] for page rules to have any effect.") suggests otherwise.

**Comment by rlarrode** [comment]
Can you please try to remove the current rule and perform new tests?

**Comment by manraf** [comment]
@rlarrode I just removed all rules from the "Guest" group, unfortunately, the problem still persists.

![grafik](https://user-images.githubusercontent.com/24991230/78789794-ed8d8780-79ad-11ea-8229-7a1b3091645c.png)

What I also tried was adding a "deny all" rule, still no effect:

![grafik](https://user-images.githubusercontent.com/24991230/78789824-f7af8600-79ad-11ea-8c42-57acaee09171.png)

I am not only using internal authentication but also LDAP, maybe this messes some things up?

**Comment by rlarrode** [comment]
@manraf i tried on my side to reproduce your behaviour wuth no success. when user is not legged in, he is automatically redirected to the logon page.

I used the same version of wiki (2.2.51 but installed using npm with no LDAP)

**Comment by Smankusors** [comment]
@manraf have you tried restarting Wiki.js?

**Comment by manraf** [comment]
I tried both things again and restarted the container each time, still no success. :(

**Comment by Smankusors** [comment]
alright, there's something I need to know. Do you mean "Guest" or "Guests"? Are you creating your own group "Guest" or using default "Guests" group? Your comments and screenshots conflicts, especially when you using quotes on your comments.

---

Anyway, try incognito, see if it's just your browser cache

**Comment by manraf** [comment]
> 
> 
> alright, there's something I need to know. Do you mean "Guest" or "Guests"? Are you creating your own group "Guest" or using default "Guests" group? Your comments and screenshots conflicts, especially when you using quotes on your comments.
> 
> Anyway, try incognito, see if it's just your browser cache

Sorry, I definitely mean the standard group called "Guests". I did try with different browsers and incognito mode, no success. I will try to spin up another container once I find the time and check if it works from scratch and then add LDAP etc.

**Comment by NGPixel** [comment]
Note that the guest permissions are cached for 1 minute. So make sure to wait at least that long before testing.
