### ISSUE TITLE
Failed to lookup view "setup" in views directory "/var/www/wiki/server/views"

### ISSUE THREAD

**Issue by noxonsu** [Requarks/wiki#1660]
**Describe the bug**
Can not start installation, see screen

![](https://screenshots.wpmix.net/putty_sizebox_peNFsfhHV1rcNfcCfen5xAkV3DBL2F2A.png)

**Comment by Smankusors** [comment]
your.... host info? please? with nodejs version?

**Comment by noxonsu** [comment]
node version 12.10, 

i think there expect "setup.pug" file but it doesn't exists  https://github.com/Requarks/wiki/tree/master/server/views

**Comment by NGPixel** [comment]
Please read the docs on how to install Wiki.js:
https://docs.requarks.io/install

You can't just clone the repo and run npm install.

**Comment by o5k4r** [comment]
I followed the installation docs for "Linux with SQLite" word by word and run into the same problem. 

I'm having the latest version of everything.

To be blunt, you feature list of Wiki.js is impressive, the documentation not so much.
