### ISSUE TITLE
Updating from 2.1.113 to 2.2.51 errors with Unknown authentication strategy 'jwt', breaks icons.

### ISSUE THREAD

**Issue by elitegoliath** [Requarks/wiki#1662]
On Digital Ocean, I used the Wiki.js 1-click install from the Docker image. I immediately created a generic Home page, then went into the Admin tools, and performed an Update. Before it was able to finish, it errors with '_Oops, something went wrong: Unknown Authentication Strategy "jwt"_'.

I saw another bug report related to that specific error, and tried to restart the wiki. The wiki boots up, but now almost every icon in the application is defaulting to a square. Not all of them, just a large majority of them.

<img width="1386" alt="Screen Shot 2020-04-02 at 1 25 56 PM" src="https://user-images.githubusercontent.com/12138681/78284794-853e3200-74e5-11ea-8f6e-c273d876ab2a.png">

**Comment by NGPixel** [comment]
You can ignore the first error. The initialization was simply not finished when you loaded the page.

As for the missing icons, you need to clear your cache.

**Comment by Naegolus** [comment]
Hi Pixel. Thank you for the answer. I have the same issue.
Could you please tell me which cache and how to clear it?
I'm new to your wiki and web dev ..

**Comment by Naegolus** [comment]
Cleared browser cache with Strg-Shift-r

Would be a useful note in
https://docs.requarks.io/install/upgrade
I think
