### ISSUE TITLE
Error "SyntaxError: Unexpected token in JSON at position 0" on large pages

### ISSUE THREAD

**Issue by ipevgeny** [Requarks/wiki#1666]
**Describe the bug**
When I'm trying to create or update a large page (57601 Chars, 7276 Words) I see the error message "SyntaxError: Unexpected token in JSON at position 0"

But if I put just 70-80% of the text - page saves successfully.

**To Reproduce**
1. Go to 'Create new page'
2. Click on 'HTML Code/MD or WYSIWYG' (it doesn't matter)
3. Past a lot of text (ex 57601 Chars, 7276 Words)
4. Click "Save"
5. See error

**Expected behavior**
Save the page...

**Screenshots**
Red message in the top of the screen

**Host Info (please complete the following information):**
 - OS: CentOS 7
 - Wiki.js version: 2.1.113
 - Database engine: PostgreSQL 9.6.17
- Nodejs: v12.16.1

**Comment by Smankusors** [comment]
Can you try to update your Wiki.js to 2.2.x?

**Comment by ipevgeny** [comment]
> Can you try to update your Wiki.js to 2.2.x? (Btw backup the database first before update it)

I've upgraded and the problem was solved! Thank you!

**Comment by witwall** [comment]
I got the same issue
OS: Ubuntu 18.04.4 LTS
Wiki.js version: 2.5.255
Database engine: PostgreSQL 14.1
Nodejs: v12.22.7
