### ISSUE TITLE
CPU usage of https://wiki.js.org/feedback

### ISSUE THREAD

**Issue by PMojito** [Requarks/wiki#1667]
Using Mozilla Firefox 74.0 on a laptop running Ubuntu 19.10, Gnome desktop.
When I navigate to this URL:
 https://wiki.js.org/feedback

one of my CPUs reaches 100% usage.  It remains at 100% until the page loses focus, or is closed.  The behavior is very repeatable.

My assumption (no evidence) is that the very-pretty particle animation in the hero section is the culprit.

Certainly not a breaking issue, but I thought I'd report it anyway.

**Comment by NGPixel** [comment]
The site was updated to resolve this.
