### ISSUE TITLE
Delete Page Button

### ISSUE THREAD

**Issue by den1622** [Requarks/wiki#167]
### Actual behavior

Have to delete page from file system or move it.

### Expected behavior

Delete button to interact with filesystem given the correct permissions.

### Steps to reproduce the behavior

Try to delete a page from wiki.js

**Comment by ggondim** [comment]
I think it is a must-have.

**Comment by chjohnst** [comment]
Really need this feature

**Comment by NGPixel** [comment]
Now available in 1.0.10
