### ISSUE TITLE
time zone

### ISSUE THREAD

**Issue by linux998** [Requarks/wiki#1677]
**Question**
Please advise how to modify the time zone. I am currently dealing with non UTC time zone!
It seems that the time in Wiki container cannot be adjusted by docker-compose environment.
Thank you very much.

OS: [e.g. Centos7.6, Docker]
Wiki.js version: [e.g. 2.2.51]
Database engine: [e.g. postgres 9.7]

**Comment by NGPixel** [comment]
Timezone support is coming in 2.3
