### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by camilodelvasto** [Requarks/wiki#168]
### Actual behavior
Search is not working, URLs are incorrect and showing an `undefined`in the path.

### Expected behavior
URLs should load properly.

### Steps to reproduce the behavior
Go here: https://docs.requarks.io/wiki - then type anything in the search box (like `database`).

Not sure if this is a bug in the software or on the site, but I wanted to know before installing and testing it. Thanks!

**Comment by NGPixel** [comment]
Duplicate of bug #161
