### ISSUE TITLE
Navigation doesn't remove old page locations after they've moved

### ISSUE THREAD

**Issue by samrawks** [Requarks/wiki#169]
### Actual behavior
When I move a page the navigation menu (wiki.domain.com/all) adds the new page entry automatically but doesn't remove the old menu entry. Currently I'm having restart the wiki process to force the navigation to update so there aren't old broken links. Any plans to make this automated?

### Expected behavior
When a page is moved the navigation menu should remove the old page entry automatically in addition to adding the new page's location.

### Steps to reproduce the behavior
1. Create a new page
2. Move the new page from say /folder/new-page to /folder/subfolder/new-page
3. Both entries should appear in the navigation menu (wiki.domain.com/all)

**Comment by BeingRemote** [comment]
Hi, is there a schedule when this will be finished? We use the wiki, but this and the 'delete page' #167 is holding us back to fully make the switch tbh.

**Comment by NGPixel** [comment]
Fixed in 1.0.6 (a5c73892069398d3ad90e57e332bba43ffb4d4ea)

**Comment by johnnyshields** [comment]
@NGPixel we are using 1.0.12 and this feature seems not to be working
