### ISSUE TITLE
Insert Assets- Upload a file - Failure

### ISSUE THREAD

**Issue by devp01** [Requarks/wiki#1690]
**Describe the bug**
The insert Assets - upload a file is showing the error upload failure.

**To Reproduce**
1. Go to '...' Any page - Edit the page
2. Click on '....' Insert Assets
3. Scroll down to '....'  Browse the file from your local-- Click on upload for uploading to a folder set up on the Assets
![image](https://user-images.githubusercontent.com/46513658/78795890-2c820400-79d3-11ea-8a07-42c21445caf2.png)

**Expected behavior**
The file should get uploaded. It used to do prior to this version
**Screenshots**

**Host Info (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04, Docker] Ubuntu 18.04
 - Wiki.js version: [e.g. 2.0.1] Wiki.js 2.1.113
 - Database engine: [e.g. postgres 9.7, mysql 5.7]

**Additional context**

**Comment by NGPixel** [comment]
- Post the browser console logs (F12) and screenshot of the network request (Networks tab).
- What's the filename of the file you're trying to upload?
- Do you have a reverse-proxy in front of Wiki.js?

**Comment by Smankusors** [comment]
Which database do you use? Postgres 9.7 or MySQL 5.7? You can't have Wiki.js running from two different database :/

**Comment by devp01** [comment]
> * Post the browser console logs (F12) and screenshot of the network request (Networks tab).
> * What's the filename of the file you're trying to upload?
> * Do you have a reverse-proxy in front of Wiki.js?

console during the issue occurs
![image](https://user-images.githubusercontent.com/46513658/78966106-8d692380-7b1c-11ea-8883-a0c8706c4d16.png)
Networks tabI 
![image](https://user-images.githubusercontent.com/46513658/78966175-bab5d180-7b1c-11ea-9fbe-58f4834978e0.png)
What I am noticing is that any file that is above 1MB in size is unable to get uploaded.
I tried to upload another file which is around 600kb and it was uploaded successfully. My understanding was that the system allows file upload of size up to 5MB in size and I can see it in the past I have uploaded files that are above 1 MB and less than 5MB in the previous wiki version. How do I verify whether this issue is related to this version or not. It would be helpful if you can shed some light on this issue.

**Comment by devp01** [comment]
An update from my side on the above issue is that I have noticed that nginx was not allowing to upload a file size > 1 MB in size. So to increase it to 5 MB change the nginx.conf file
Add the following line on the http { ......} block of the nginx.conf file.
client_max_body_size 5M;

Is there any way in which we could increase the file upload to say 50MB on wiki.js
Can we configure this via config.yml 
It would be helpful if you can provide some inputs on this.

**Comment by devp01** [comment]
> Which database do you use? Postgres 9.7 or MySQL 5.7? You can't have Wiki.js running from two different database :/

I am using mysql. My issue was due to the nginx configuration which I modified it now.

**Comment by Smankusors** [comment]
> An update from my side on the above issue is that I have noticed that nginx was not allowing to upload a file size > 1 MB in size. So to increase it to 5 MB change the nginx.conf file
> Add the following line on the http { ......} block of the nginx.conf file.
> client_max_body_size 5M;
> 
> Is there any way in which we could increase the file upload to say 50MB on wiki.js
> Can we configure this via config.yml
> It would be helpful if you can provide some inputs on this.

you can read about change the upload limit [here](https://docs.requarks.io/install/config#upload-limits).

**Comment by devp01** [comment]
Thank you. Appreciate your help.
