### ISSUE TITLE
add/remove tag from an existing page

### ISSUE THREAD

**Issue by toneti85** [Requarks/wiki#1691]
**Question**
I have a Wiki.js 2.2.51 server running with PostgreSQL. I'm using default theme.

When creating new page, there is input field for tags, but after creation I couldn't find the place to add/remove tags.

The question: how can I edit tags of my pages ?

**Host Info (please complete the following information):**
OS: [Windows Server 2019 Datacenter]
Wiki.js version: [ 2.2.51]
Database engine: [postgres 12.1]

**Comment by Smankusors** [comment]
you can open properties from page editor, by using **PAGE** button on the left of **CLOSE** button
