### ISSUE TITLE
Markdown editor doesn't have MAX-WIDTH

### ISSUE THREAD

**Issue by elderGinger** [Requarks/wiki#1692]
**Describe the bug**
Markdown editor doesn't have a max-width, after inputting a very long sentence in a single line, preview part will disappear and the contents exceeding the page's wdith are not visible on the final rendered page.  

**To Reproduce**
1. Go to 'markdown editor'
2. Click live-preview button
3. Input a very long line like 'aaa......aaa' 
4. Preview page will shrink and disappear finally 

**Expected behavior**
1. Characters exceeding the line's max-length can be put in the next line automatically 
2. The preview page stays the same

**Screenshots**
![image](https://user-images.githubusercontent.com/60418032/78853759-3eef5280-7a52-11ea-89e6-4af165c147c3.png)

![image](https://user-images.githubusercontent.com/60418032/78853978-cfc62e00-7a52-11ea-9d48-972763505307.png)
![image](https://user-images.githubusercontent.com/60418032/78853993-da80c300-7a52-11ea-8fcc-10272e1deb9a.png)
![image](https://user-images.githubusercontent.com/60418032/78853816-62b29880-7a52-11ea-953b-453c81575710.png)
![image](https://user-images.githubusercontent.com/60418032/78854011-e66c8500-7a52-11ea-9fee-6e751ccc395e.png)

**Host Info (please complete the following information):**
 - OS: [OSX 10.15]
 - Wiki.js version: [2.2.50]
 - Database engine: [mariadb ]

**Additional context**

**Comment by H1ghBre4k3r** [comment]
I guess, it has something to do with the css-class `.CodeMirror pre.CodeMirror-line [...]`.
The css-property `word-break` is set to `normal`, which explains this behaviour. Setting it to `break-word` (which is commonly supported, except IE) fixes it. 

![Screenshot (6)](https://user-images.githubusercontent.com/32372790/78944081-67f8fd00-7abd-11ea-8143-03d7111e62c8.png)
