### ISSUE TITLE
SSL Certificate for www and non-www

### ISSUE THREAD

**Issue by joppehoekstra** [Requarks/wiki#1693]
**Question**
I am trying to get our website to make the non-www domain to refer to the www domain, while enforcing SSL encryption. However, in the setup, you can only select one domain name. So I can get either the www domain to work, or the non-www domain, but not both. When using both, a warning is shown in the browser saying the certificate is not valid (at the domain that was not registered for the certificate). 

I am inexperienced with Docker and encryption certificates, so this might not actually be an issue with WikiJS, but rather with my ability to get this to work. But perhaps someone is able to help me out here?

**Host Info:**
OS: Ubuntu 18.04, Docker
Wiki.js version: 2.2.51
Database engine: postgres 9.7

**Comment by NGPixel** [comment]
You should use either www or non-www, not both at the same time. One should redirect to the other (using nginx / apache, or solutions like cloudflare).

**Comment by joppehoekstra** [comment]
Awesome, thank you. We got it to work using Cloudflare.
