### ISSUE TITLE
Uploading files in a folder or nested folders with MySQL 5.7

### ISSUE THREAD

**Issue by giv13** [Requarks/wiki#1694]
Hello! https://docs.requarks.io/install/requirements/mysql5 - here you write that the only thing for which version 8.0 is needed is uploading images to subfolders. If so, can you just rewrite the logic for loading images for MySQL 5.7? How did you do this here https://github.com/Requarks/wiki/issues/913, getting rid of `WITH RESURSIVE`. Not many hosting companies support MySQL 8.0. Thanks!

**Comment by NGPixel** [comment]
Because the workaround in MSSQL was to use `WITH` and `UNION ALL`. While MySQL supports `UNION ALL`, it doesn't support the `WITH` clause.
