### ISSUE TITLE
Navigation Feature

### ISSUE THREAD

**Issue by devp01** [Requarks/wiki#1695]
!! IMPORTANT !!
Do not submit feature requests here. Use our feature request board instead:

https://wiki.js.org/feedback
Is it possible to add a collapsible Navigation Feature.

Header1
Nav menu1
Nav menu 2
Nav menu 3
......
Header 2
Nav menu 2.1
Nav menu 2.2
Nav menu 2.3

........
Header 3
Nav menu 3.1
Nav menu 3.2
Nav menu 3.3
....

Header 4
Nav menu 4.1
Nav menu 4.2
Nav menu 4.3
.........
 So if there is a feature like where we can have a feature as follows it would be helpful
Header 1. -- When we click on Header1 --it should open Nav menu1,Nav menu2, Nav menu3 etc.
Header 2-- When we click on Header2 --- -it should open Nav menu 2.1,Nav menu2.2, Nav menu2.3 etc. and so on.
Header 3
Header 4
Header 5

It would be quite useful if this feature is added on to wiki.

**Comment by Smankusors** [comment]
that's funny you still left this on the beginning :
> !! IMPORTANT !!
> Do not submit feature requests here. Use our feature request board instead:
> 
> https://wiki.js.org/feedback

---

Anyway, why not use the feature request board instead?

**Comment by NGPixel** [comment]
Please actually read the notice before posting next time. This is for bug reports only. Submit your feature request here instead:

https://requarks.canny.io/wiki
