### ISSUE TITLE
Rending Core: no default assets path

### ISSUE THREAD

**Issue by seafre** [Requarks/wiki#1699]
**Describe the bug**
For each Page, uploading assets provides choice of entire file directory structure. New users keep placing uploaded JPG/PNG/SVG etc into root directory, and there is no option to remove this path selector.

**Expected behavior**
Option to define a default (override) assets location, such as ./assets in root directory (on Git or Object Storage locations). For additional upload assets, the path selector is no longer visible

**Comment by Smankusors** [comment]
"Rending Core"? What do you mean?

**Comment by LujienZ** [comment]
Can you not do this with right? And say user can't put asset into the root directory? I put something like this for my user and it's working well.

**Comment by NGPixel** [comment]
This is not a bug.

You can submit a [feature request](https://requarks.canny.io/wiki) instead.
