### ISSUE TITLE
Active Directory/LDAP Authentication

### ISSUE THREAD

**Issue by MDendura** [Requarks/wiki#17]
Any thoughts about doing an authentication provider for Active Directory? This would be great for an on-prem business deployment.

**Comment by NGPixel** [comment]
I can add the provider, but it would be listed as experimental, since I have no LDAP server to test it against. If you're willing to test it, I can add it to the next beta release.

**Comment by MDendura** [comment]
Absolutely, that would be great - we'd be glad to do the testing.

We're on a Windows domain and have a Server 2012 R2 Domain Controller and would look to host the wiki on a separate Server 2012 R2 box running IIS.

**Comment by MDendura** [comment]
I've seen from the the changelog you've added an experimental LDAP provider - thanks for starting this so quickly!

I've set the wiki up locally for testing and have got to the stage where the wiki will run successfully, but there doesn't appear to be any logic around querying the LDAP server yet.

Please let me know as soon as you're ready for me to start testing anything.

**Comment by NGPixel** [comment]
The LDAP integration should be ready for testing in about a week.

**Comment by NGPixel** [comment]
LDAP integration is now fully working. It will be available in Beta 9 (or you can try it right away from the master branch).

**Comment by ascheucher** [comment]
Hi, did I miss it, or isn't it possible to configure a secondary LDAP?
Would be great to be able to log into Wiki when the primary LDAP is down.
Thanks
