### ISSUE TITLE
Unable to install Wiki.js on Raspberry pi 4 (RaspBian).

### ISSUE THREAD

**Issue by Minhokn** [Requarks/wiki#1700]
**Question**
Good morning, sir,
I've tried several times to install Wiki.js v2 on Raspberry Pi 4 using the https://docs.requarks.io/install/linux procedure but it doesn't work. I tried the same with version 1 of wiki.js and it didn't work. 
Do you have a specific detailed procedure for ARM architectures ?  Do we need to use a particular OS on Raspberry Pi 4 ?
Sincerely,

**Host Info (please complete the following information):**
OS: RaspBian Buster
Wiki.js version: 2.2.51

**Comment by Smankusors** [comment]
Why it didn't work? Is there any errors? Can you show that to us?

---

Btw, there's docker image for ARM if you interested...

**Comment by NGPixel** [comment]
Please provide more details than "it didn't work".

As @Smankusors suggested, you should use the docker image for ARM:
https://docs.requarks.io/install/docker#arm-images

**Comment by Minhokn** [comment]
Sorry for the lack of information, I first wanted to know if wiki.js was functional on Raspbian.

Here's the procedure I did: 

PostgreSQL 11 installation : 
`sudo -i -u postgres createuser -P -e wikijsusr                 
`
`sudo -i -u postgres createdb -O wikijsusr wikijsbdd         
`

Docker installation : 
`curl -sSL https://get.docker.com | sh`

Docker version : 
`root@raspberrypi:/home/pi# docker version`
`Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:35:24 2020
 OS/Arch:           linux/arm
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:22 2020
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683`

When I launch the container via the command below, I can see in the logs that it fails to connect to the database 
`docker run -d -p 8080:3000 --name wiki --restart unless-stopped -e "DB_TYPE=postgres" -e "DB_HOST=localhost" -e "DB_PORT=5432" -e "DB_USER=wikijsusr" -e "DB_PASS=mdp" -e "DB_NAME=wikijsbdd" requarks/wiki:2.2-arm`

`root@raspberrypi:/home/pi# docker logs wiki`
`Loading configuration from /wiki/config.yml... OK
2020-04-12T22:07:54.469Z [MASTER] info: =======================================
2020-04-12T22:07:54.475Z [MASTER] info: = Wiki.js 2.2.51 ======================
2020-04-12T22:07:54.475Z [MASTER] info: =======================================
2020-04-12T22:07:54.475Z [MASTER] info: Initializing...
2020-04-12T22:07:55.258Z [MASTER] info: Using database driver pg for postgres [ OK ]
2020-04-12T22:07:55.271Z [MASTER] info: Connecting to database...
2020-04-12T22:07:55.296Z [MASTER] error: Database Connection Error: ECONNREFUSED 127.0.0.1:5432
2020-04-12T22:07:55.296Z [MASTER] warn: Will retry in 3 seconds... [Attempt 1 of 10]`

However, I can access with the user "wikijsusr" to the "wikijsbdd" database from the raspberry pi.
Do you have any idea where the problem might come from?

**Comment by Smankusors** [comment]
Why not use docker-compose to make your life little easier? Anyway your postgres cannot be accessed via "localhost" from the docker container. Because the docker container runs on different network. You can change DB_HOST to your host's IP and see if that's works

The alternative way, is use `--network host` on your docker run. So the docker container runs on the same network as your host.

**Comment by Minhokn** [comment]
Thanks, I just managed to install it. I did not know for this management of the network by docker.
Is it possible to set up wiki.js in a directory of a domain like "http: //xx.xx.xx.xx:80/wikijsforlder." ?

**Comment by NGPixel** [comment]
No, see [requirements](https://docs.requarks.io/install/requirements#domain)
