### ISSUE TITLE
Markdown editor scroll synced with preview

### ISSUE THREAD

**Issue by AlexFullmoon** [Requarks/wiki#1702]
I'm looking for an option to sync/lock scroll in editor and preview panes. So that preview always shows the position I am at in editor.
Not sure if this feature isn't implemented and I should request it, or I just can't find a way to enable it.

OS: Docker
Wiki.js version: 2.2.51
Database engine: mariadb 10.3.21

**Comment by NGPixel** [comment]
This is already implemented and always enabled.
