### ISSUE TITLE
Insert an iframe container in WYSIWYG-Editor

### ISSUE THREAD

**Issue by maka1000** [Requarks/wiki#1705]
**Question**
Hi
I would like to insert the following iframe container by using WYSIWYG-Editor, but in the moment it is not possible because it get this error: Network error: Unexpected token < in JSON at position 0

Is there another way to do that in WYSIWYG-Editor?

<div class="embed-container"><iframe src="videos/1%20RegistrationUndLogin/RegistrationUndLogin_player.html?embedIFrameId=embeddedSmartPlayerInstance" width="560" height="315" frameborder="0" allowfullscreen="allowfullscreen"></iframe></div>

**Host Info:**
OS: Ubuntu 18.04
Wiki.js version: 2.1.113
Database engine: PostgreSQL 9.7

**Comment by Smankusors** [comment]
I can't reproduce this. It's more likely you have a long document instead of just iframe isn't it? Is your Wiki behind reverse proxy? Because the error seems not coming from Wiki.js
---
Btw, try to uprade 2.2.x too

**Comment by maka1000** [comment]
If you mean with "reverse proxy" as example Cloudflare, then yes. Do I need to do there some changes?

**Comment by Smankusors** [comment]
Anything else than Cloudflare? Can you see the Network tab on your DevTools, and see what is server responded when it returned 403?

**Comment by maka1000** [comment]
I have 2 Load Balancer in front, of the mainserver(s). 

Yes in Network Tab i see this, looks also here, that cloudflare will be the problem?:

Request URL: https://docs.uxxxr.com/graphql
Request Method: POST
Status Code: 403 
Remote Address: [2606:4700:10::6816:1ba2]:443
Referrer Policy: no-referrer-when-downgrade
cache-control: no-cache
cf-chl-bypass: 1
cf-ray: 582e654abd05cc52-ZRH
content-encoding: gzip
content-type: text/html; charset=UTF-8
date: Sun, 12 Apr 2020 16:41:35 GMT
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
status: 403
x-frame-options: SAMEORIGIN
:authority: docs.uxxxr.com
:method: POST
:path: /graphql
:scheme: https
accept: */*
accept-encoding: gzip, deflate, br
accept-language: de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7,it;q=0.6
authorization: Bearer [Removed]
content-length: 9690
content-type: application/json
cookie: _ga=[Removed]
origin: https://docs.uxxxr.com
referer: https://docs.uxxxr.com/e/en/home
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: same-origin
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36
[{operationName: null, variables: {id: 40,…}, extensions: {},…}]
0: {operationName: null, variables: {id: 40,…}, extensions: {},…}

**Comment by Smankusors** [comment]
you are giving both response dan request header (plus request payload). But I need to see the server response data.

**Comment by NGPixel** [comment]
This error is specific to Cloudflare blocking the save request. You need to whitelist your IP or reduce the rules blocking this request.

**Comment by Smankusors** [comment]
> This error is specific to Cloudflare blocking the save request. You need to whitelist your IP or reduce the rules blocking this request.

he did say that he have same error when not using Cloudflare tho...

**Comment by maka1000** [comment]
Yes Smankusors that was really confusing me, that I had the same issue, also when I deactivate Cloudflare for this URL. But maybe Cache or something else still disturbed it, I don't know, because now I have found a solution, if someone else have the same issue:

In Firwall rules i deactivated "OWASP XSS Attacks" then it works. I don't know if it is a good solution, when I deactivate complete section "OWASP XSS Attacks". To find maybe a better solution (only do deactivate a part of it) I'm in contact with Cloudflare Support.

**Comment by maka1000** [comment]
I have solved the issue with cloudflare, but whe i want to implement an iframe in WYSIWYG Editor, it don't show it in frontend:

<div class="embed-container"><iframe src="videos/1%20RegistrationUndLogin/RegistrationUndLogin_player.html?embedIFrameId=embeddedSmartPlayerInstance" width="560" height="315" frameborder="0" allowfullscreen="allowfullscreen"></iframe></div>

I have copied it from my other website and there exactly same iframe is working.

Is it not possible to implement Iframe with the WYSIWYG Editor?

**Comment by Smankusors** [comment]
The HTML Sanitizer, disable it from Security rendering module

**Comment by maka1000** [comment]
Great thanks
