### ISSUE TITLE
Guest user doesn't see assets (images) on page

### ISSUE THREAD

**Issue by vennca** [Requarks/wiki#1707]
**Question**
Hello,
I would like to approve access for Guest to see some web pages include assets on this page (images and files).

Guest is system user. In permission of group Guest I set `read:pages, read:assets. read:comments`.
I also set page rule with `read:pages, read:assets. read:comments`. The result is that  guest is able to access to specific page but images is not loaded because permission denied.

Could someone help me please how to resolve this?
Have a nice time.
Vasek

**Host Info:**
OS: CentOS 7.7
Wiki.js version: 2.2.51
Database engine: Postgres 12.1

**Comment by Smankusors** [comment]
how many minutes you waited before see the changes? This permission is cached, so it needs time before it applied.

But if you don't want to wait, you can restart Wiki.js. Have you tried it?

**Comment by vennca** [comment]
Hello @Smankusors 
thank you for quick reponse. I was waiting more than 5 minutes. I tried restart wiki.js but the result is the same. I tried to recreate Guest user too.

**Comment by rlarrode** [comment]
Hello @vennca,
Do you also grant `read:assets` rights on the folder that contains the assets?

**Comment by vennca** [comment]
Hi @rlarrode,
good point. 

My setting:
[img1](https://itles.cz/wp-content/uploads/2020/04/wiki-js1.png)
[img2](https://itles.cz/wp-content/uploads/2020/04/wiki-js1.png)
[img3](https://itles.cz/wp-content/uploads/2020/04/wiki-js1.png)
With this setting images are not loaded.

When I added permission to dir I can access to images:
[img1](https://itles.cz/wp-content/uploads/2020/04/wiki-js4-working.png)

But Guest can access to images outside this page :/

**Comment by rlarrode** [comment]
You may need to load these assets in a dedicated folder and only grant guest access to this specific folder

**Comment by vennca** [comment]
Ohh..yes! Thank you very much @rlarrode. You saved me a lot of time.
Thank you!
[img5-ok](https://itles.cz/wp-content/uploads/2020/04/wiki-js5-ok.png)
