### ISSUE TITLE
Include html content on Raw HTML Editor dont reproduce html

### ISSUE THREAD

**Issue by luanknebel** [Requarks/wiki#1710]
When displaying a page written by HTML, the HTML code is displayed instead of reproducing the HTML content

**To Reproduce**
1 - Create a new page with Raw HTML type
2 - Include tag iframe from You Tube, example:

<iframe width="560" height="315" src="https://www.youtube.com/embed/JnLdx2FyNqg" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

3- The displayed content is the html code and not the video.
**Expected behavior**
Show video from iframe

**Screenshots**
<img src="https://serving.photos.photobox.com/0932784454a2eaa6f092dbf2388b457d4bc69be22bdea29aa6e6187a2d190ffbe3d40307.jpg" img/>

**Host Info (please complete the following information):**
 - OS: CentOS 7
 - Wiki.js version: 2.2.51
 - Database engine: postgres 10.12

**Additional context**
The content written in the HTML editor is displayed in double quotes and the browser cannot interpret the written html.

**Comment by Smankusors** [comment]
You need to disable HTML Sanitizer on Security rendering module. After that you can re-render the page and see if the iframe shows up

**Comment by joppehoekstra** [comment]
This doesn't seem like a proper way to solve this problem. The expected behaviour of the HTML sanitizer is to only remove content from 'untrustable' sources. Even when embedding videos using the visual editor, the video is not rendered on the page (it is rendered in the editor, as described in this [issue](https://github.com/Requarks/wiki/issues/1459)
#1459

**Comment by Smankusors** [comment]
> This doesn't seem like a proper way to solve this problem. The expected behaviour of the HTML sanitizer is to only remove content from 'untrustable' sources. Even when embedding videos using the visual editor, the video is not rendered on the page (it is rendered in the editor, as described in [this issue](https://github.com/Requarks/wiki/issues/1459).

well yes, but this is iframe. Anything malicious can happen. Are you really "trust your editors" about it?

**Comment by joppehoekstra** [comment]
> well yes, but this is iframe. Anything malicious can happen. Are you really "trust your editors" about it?
You're right, what I meant to say was: it would be better to wait for the implementation of rendering of videos added in the visual editor, instead of turning off the HTML Sanitizer (because as you rightly point out, this would cause security issues).

**Comment by luanknebel** [comment]
Thanks for this support, I initially disabled HTML Sanitize for now.

**Comment by Smankusors** [comment]
> Thanks for this support, I initially disabled HTML Sanitize for now. We can close this issue?

if your issue is resolved, feel free to close yourself 🙂
