### ISSUE TITLE
GraphQL API ignores valid Tokens

### ISSUE THREAD

**Issue by HerrBlauzahn** [Requarks/wiki#1713]
**Bug description**
When trying to use the GraphQL API I always get the following error message:
```json
{
  "data": {},
  "errors": [
    {
      "message": "API Key is invalid or was revoked.",
      "path": []
    }
  ]
}
```
The API-Key was generated with full permissions and should be valid. The API was enabled.

**To Reproduce**
1. Log in as Admin
2. Go to the Settings
3. Create API-Key and tick the full permissions box
4. Activate the API
5. Go to the GraphQL playground (https://host/graphql) (I also tried it with Insomnia)
6. Set the HTTP Header to `{"Authorization":"Bearer <Token>"}`
7. Create a valid request
8. Get the error.

**Expected behavior**
Expected some useful output of the API other than "API Key is invalid or was revoked."

**Host Info (please complete the following information):**
 - OS: Raspbian Linux 4.19.66-v7+, Docker
 - Wiki.js version: 2.2.51-arm (latest as of 2020-04-14)
 - Database engine: SQLite

**Additional context**
I don't know if it matters, but I removed all permissions (e.g. read) from the guest user.
Also: Since my installation is in another language, some descriptions might not be 100% accurate but that shouldn't be a problem.

**Comment by NGPixel** [comment]
You need to restart Wiki.js to reload the API keys table after adding a new key. This is fixed in the upcoming 2.3 update.
