### ISSUE TITLE
Visualize Pages "Unexpected Error"

### ISSUE THREAD

**Issue by gordosgithub** [Requarks/wiki#1715]
**Describe the bug**
Upon pressing the "visualize pages" button in the admin panel, an "unexpected error has occurred" dialogue pops up and the page says "Looks like there's no data to graph!"

This occurred in both Chrome and Firefox (latest versions), and seems to be related to SQLITE. Console output is visible in my screenshot below.

**To Reproduce**
1. Go to the admin panel
2. Click on the pages button
3. Click on visualize pages (any type of visualization)

**Expected behavior**
Pages would be displayed in a visual array.

**Screenshots**
![visPages-error](https://user-images.githubusercontent.com/30273077/79183959-9128ce80-7dd8-11ea-8876-51a4216a7e7f.png)

**Host Info (please complete the following information):**
 - OS: Ubuntu 18.04
 - Wiki.js version: 2.2.51
 - Database engine: SQLITE

**Comment by t-jeyan** [comment]
Was able to reproduce the same error with 20+ pages. 

OS: Mac  10.15.3
Wiki.js version: 2.2.51
Database engine: MySQL

**Comment by siddhartha-lal** [comment]
I am also getting the same error. I have tried versions 2.2.51, 2.2.73, and 2.2.77.

**Comment by regevbr** [comment]
@NGPixel can you please close this issue as well as it was addressed in #2104
