### ISSUE TITLE
Insert data directly from sql server into div blocks. Give me some advice

### ISSUE THREAD

**Issue by Aphrod1** [Requarks/wiki#1716]
I need help creating a connector for sql server. Need to insert tables directly from sql server

OS: Ubuntu
Wiki.js version: 2.2.50
Database engine: mssql

**Comment by Smankusors** [comment]
But why? How about Wiki.js API?

**Comment by Aphrod1** [comment]
> But why? How about Wiki.js API?

are there any links or documentation?

**Comment by NGPixel** [comment]
https://docs.requarks.io/dev/api
