### ISSUE TITLE
"Permission denied" for a user that should have access

### ISSUE THREAD

**Issue by Orilcious** [Requarks/wiki#1718]
**Question**
I have read https://docs.requarks.io/groups yet cannot apply the concept. 
Here are the steps I have taken:
- created a page "/de/hzw"
- created a user "ori"
- created a group "hzw admins"
- applied all the settings available under "permissions" to "hzw admins"
- applied all settings available under "page rules" for "path starts with - any locale - /hzw"
- clicked on "update group"
- added the user "ori" to the group "hzw admins"
- opened an  incognito tab
- logged in as the user "ori"

This is where I see "not authorized" directly after trying to login.
Any Idea what I might me doing wrong?

**Host Info (please complete the following information):**
OS: Ubuntu 18.04, installed without docker like described here https://docs.requarks.io/install/linux
Wiki.js version: 2.2.51
Database engine: 10.3.18-MariaDB

**Comment by Smankusors** [comment]
have you tried restarting the Wiki.js?

**Comment by Orilcious** [comment]
Hello Smankusors,

yes I have tried that.
The issue is Reboot / Service Restart persistent.

Is there maybe a loglevel that I can increase and logfiles I can provide?

Kind regards,
Ori

**Comment by Orilcious** [comment]
Figured it out.
There needs to be a rule for / ...
Otherwise logging in you start at / and have no rights to access that page...
Feels a bit unintuitive.

Maybe suggest that such a rule could be missing in the access denied error message for / ?
