### ISSUE TITLE
Cant delete Imagefile

### ISSUE THREAD

**Issue by REOLDEV** [Requarks/wiki#1720]
**Describe the bug**
When i try to remove a File out of the Image Browser i get this error
"Variable "$id" of non-null type "Int!" must not be null."
**To Reproduce**
1. Go to File/Image Browser
2. Click on "Actions", click on "Delete" and accept the Modal
3. See error

**Expected behavior**
The Imagefile should be deleted

**Screenshots**
![https://i.imgur.com/XMznx0b.png](https://i.imgur.com/XMznx0b.png)

**Host Info (please complete the following information):**
 - OS: Ubuntu 18.04 LTS Docker
 - Wiki.js version: 2.2.51
 - Database engine: MariaDB 10.3

**Additional context**

**Comment by sbonaime** [comment]
@REOLDEV It is a known issue. you can close this one and follow
#1518
#1674
or
#1493
