### ISSUE TITLE
Trying to integrate Wiki.js with Nextcloud

### ISSUE THREAD

**Issue by dmigis** [Requarks/wiki#1722]
**Question**
Describe in details what you are trying to achieve and where do you need guidance.
Hello! I'm trying to integrate Wiki.js with Nextcloud for SSO (Nextcloud is identity frovider via OAuth2) and common media storage. That's why I have several questions:
1. Do I understand correctly, that I need to modify this module in order to achieve Nextcloud OAuth2 support (https://github.com/Requarks/wiki/blob/master/server/modules/authentication/oauth2/authentication.js)? Also, are there any plans to support Generic OAuth or Nextcloud Oauth out of the box?
2. Is it possible to acess Nextcloud storage (for example, via WebDav) in order to be able to use content from there in the wiki? If no, are there any plans to implement such feature?
Thanks in beforehand.

**Host Info (please complete the following information):**
OS: Ubuntu 19.10, Docker
Wiki.js version: 2.2.51
Database engine: postgres 9.7

**Comment by NGPixel** [comment]
OAuth2 is not yet available. Coming in a future release.

For WebDav, submit a [feature request](https://wiki.js.org/feedback/).
