### ISSUE TITLE
Downloading uploaded files with .txt or .html extension

### ISSUE THREAD

**Issue by vennca** [Requarks/wiki#1723]
**Question**
Hello,
how can I download uploaded files with extension .txt or .html? 
```
For download [here](/dir/name.file)    - can be downloaded
For download [here](/dir/name.txt)     - returns PAGE NOT FOUND
For download [here](/dir/name.html)    - returns PAGE NOT FOUND
```

**Host Info:**
OS: CentOS 7.7
Wiki.js version: 2.2.51
Database engine: Postgres 12.1

**Comment by NGPixel** [comment]
.md, .txt and .html files are considered pages, not files. Zip these files instead.

**Comment by Hallo5000** [comment]
For anyone looking into the same problem: A simple workaround is to just remove `txt` from the page extensions under Settings > General.
