### ISSUE TITLE
Have some bugs with attributes clipping after upgrade to v. 2.2.51

### ISSUE THREAD

**Issue by giv13** [Requarks/wiki#1724]
**Describe the bug**
All description in screenshots.

**Screenshots**
https://yadi.sk/i/Qu0joUwZujogmg
https://yadi.sk/i/lv0B9hW3TISsow

**Host Info (please complete the following information):**
 - OS: Linux
 - Wiki.js version: 2.2.51
 - Database engine: MySQL 5.7

**Comment by Smankusors** [comment]
you should.... create separate issue (and then explaining it) instead of merging them together.

Anyway, for the first photo, try to disable HTML Sanitizer on Security rendering module and see if that works

**Comment by giv13** [comment]
Yes, the problems are similar. Thank, it works for me! But what if protection against XSS-attacks is needed? The list issue is critical, I think. Closing the issue at your discretion. Thank you for your work!)

**Comment by Smankusors** [comment]
> Yes, the problems are similar. Thank, it works for me! But what if protection against XSS-attacks is needed? The list issue is critical, I think. Closing the issue at your discretion. Thank you for your work!)

you can disable HTML Sanitizer if you "trust" with all of your editors. Anyway this <i> tag should not be wiped by the sanitizer module tho...

On the other note, upcoming comments feature, it could be separate security module I think

**Comment by NGPixel** [comment]
1. Fixed by 2ff3abe0d832c65289e302b43433ffbc08cf0cd2
2. Fixed by 17f833509f1466654e138ff4c468ab8f651da019
