### ISSUE TITLE
EACCES: permission denied, mkdir '/home/wiki'

### ISSUE THREAD

**Issue by jiihkui** [Requarks/wiki#1725]
EACCES: permission denied, mkdir '/home/wiki' <--- appears after editing and save.

OS: [e.g. Ubuntu 18.04, Docker] - Wiki.js on Digital Ocean 
Wiki.js version: 2.2.51
Database engine: Postgresql 11

**Comment by Smankusors** [comment]
how you runs this Wiki.js docker container?

**Comment by jiihkui** [comment]
pre-installed with digital ocean

**Comment by peteblank** [comment]
did you try writing sudo before mkdir?

**Comment by borrrsch** [comment]
I had have the same issue. Even folder permission set 777 and user/group set as server process user, that problem still appears. Resolved only if backup folder placed into working wiki folder.

**Comment by NGPixel** [comment]
The backup folder must be located at `/wiki/data/content` when using docker. This path is predefined in the dockerfile as a volume and with the correct permissions (allowing you to mount it as well).

**Comment by jiihkui** [comment]
Thanks. Reinstalled in DigitalOcean droplet using manual Ubuntu method instead.
