### ISSUE TITLE
url is not a valid url

### ISSUE THREAD

**Issue by peteblank** [Requarks/wiki#1727]
**Question**
Hello, I've successfully configured wikijs on my site civilizationfromscratch.xyz.
However when I fill out the information and input the domain name, it says my url is not a valid url. 

**Host Info (please complete the following information):**
OS:Linux instance-2 4.9.0-12-amd64 #1 SMP Debian 4.9.210-1 (2020-01-20) x86_64 GNU/Linux
Wiki.js version: Wiki.js 2.2.51
Database engine: psql (PostgreSQL) 12.2

**Comment by Smankusors** [comment]
do you already begin your URL with `http://` or `https://`?

**Comment by peteblank** [comment]
I tried with and without http://
I 'm running it again so you can see
http://civilizationfromscratch.xyz/

**Comment by Smankusors** [comment]
I can't reproduce your error. Your wiki.js already setup with your domain name.

**Comment by peteblank** [comment]
well that's odd. Thank you. 
What's my username and password by the way?

**Comment by Smankusors** [comment]
I recommend to reset the DB, back to the setup, and set your own credentials. Also, screenshot what you entered on the setup

**Comment by peteblank** [comment]
Okay I deleted the database and started it up again.
Same issue.:(

**Comment by Smankusors** [comment]
Do you already solved the issue? Where's the screenshot? :/
