### ISSUE TITLE
Installation fails with permission error

### ISSUE THREAD

**Issue by xTNTx** [Requarks/wiki#173]
### Actual behavior

Installation fail to install `yarn` globally when executed as non-privileged user:
```
✖ Error: Command failed: npm install -g yarn
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/yarn
npm WARN checkPermissions Missing write access to /usr/lib/node_modules
```

### Expected behavior

Installation finishes successfully

### Steps to reproduce the behavior

Run `npm install wiki.js@latest` as non-root user

### Additional

Wiki version - `1.0.1`. Looks like it started happening after https://github.com/Requarks/wiki/commit/4b027b137b502732156b4e3a333f17ff01fdc9ed

**Comment by NGPixel** [comment]
Fixed in release 1.0.3
