### ISSUE TITLE
can't install wiki.js as a service

### ISSUE THREAD

**Issue by peteblank** [Requarks/wiki#1730]
Okay so I'm almost there but I'm having one issue. 
I'm not able to start wiki.js as a service. 
Here's my configuration settings for wiki.service:

> 
[Unit]
Description=Wiki.js
After=network.target
[Service]
Type=simple
ExecStart=/usr/bin/node /usr/local/etc/server
Restart=always
Consider creating a dedicated user for Wiki.js here:
User=blankmail89
Environment=NODE_ENV=production
WorkingDirectory=/usr/local/etc/wiki
[Install]
WantedBy=multi-user.target

And here's the journalctl error
>Apr 16 08:16:59 instance-2 systemd[1]: Started Wiki.js.
Apr 16 08:16:59 instance-2 systemd[1]: wiki.service: Main process exited, code=exited, status=210/CHROOT
Apr 16 08:16:59 instance-2 systemd[1]: wiki.service: Unit entered failed state.
Apr 16 08:16:59 instance-2 systemd[1]: wiki.service: Failed with result 'exit-code'.
Apr 16 08:16:59 instance-2 systemd[1]: wiki.service: Service hold-off time over, scheduling restart.
Apr 16 08:16:59 instance-2 systemd[1]: Stopped Wiki.js.

I'm also running it on the google cloud.
Please help, I just need to solve this issue so I can start the website. Thanks in advanced. 

**Host Info (please complete the following information):**
OS: Debian GNU/Linux 9.12 (stretch)
Wiki.js version:  2.2.51
Database engine: psql (PostgreSQL) 12.2

**Comment by Smankusors** [comment]
Do you follow the [installation guide](https://docs.requarks.io/install)? What node.js version do you use?

**Comment by peteblank** [comment]
Yes I followed the installation guide. 
I even tried changing the user to root, new user and the main account on the config.yaml file and tried to extend the source folders so instead of just being /wiki it'd be usr/local/wiki and such
I'm using node v10.20.1

**Comment by Smankusors** [comment]
If you run wiki.js manually (not from services), will it run normally?

**Comment by peteblank** [comment]
yes

**Comment by Smankusors** [comment]
isn't this line :
```
ExecStart=/usr/bin/node /usr/local/etc/server
```
should be this?
```
ExecStart=/usr/bin/node server
```

**Comment by peteblank** [comment]
Yeah, I've tried that. 
Same error.
