### ISSUE TITLE
Administrator user unable to perform any administration

### ISSUE THREAD

**Issue by markjlyon** [Requarks/wiki#1735]
### Actual behavior
All admin functions while logged on as the Administrator generate an error stating insufficient rights.

### Expected behavior
Logging on as Administrator should all the use of admin functionality.

### Steps to reproduce the behavior
Install a new version of wiki.js. Set up and email and password for the administrator account. Log out. Log in. Try to add new groups or users.

**Comment by NGPixel** [comment]
What error do you get exactly?
