### ISSUE TITLE
Improving support of RTL languages (Persian)

### ISSUE THREAD

**Issue by qpsamet** [Requarks/wiki#1738]
**Description:**

Specific Persian/Farsi letters are shown in wrong position including:
(KAF) ک , (GAF) گ , (CHE) چ , (YEH) ی

**Screenshot:**

![image](https://user-images.githubusercontent.com/13497158/79607885-44f7ca00-8109-11ea-9c44-db7df0a7d0aa.png)

**Host Info:**
 - OS: FreeBSD 12.1
 - Wiki.js version: 2.2.51
 - Database engine: postgres 12.1

**Comment by sesajad** [comment]
This issue is solved in #1871.
