### ISSUE TITLE
Wiki's locale not taken into account in the group page rules options

### ISSUE THREAD

**Issue by mkende** [Requarks/wiki#1739]
**Describe the bug**
In a wiki with multilingual namespace deactivate and configured in a non-English locale (French in my case), in the "page rules" options of a group, there is the option to apply a rule to "any locale" or to only "English".

**To Reproduce**
1. On the wiki locale setting, deactivate the multilingual namespace
2. Set the wiki locale to French (or, probably, anything else than English).
3. Save
4. Go to a group "page rules" page

**Expected behavior**
Page rules can be configured to apply to any locale or to the current locale (French).

**Actual behavior**
Page rules can be configured to apply to any locale or to English only.

**Screenshots**
![locale settings](https://i.imgur.com/22LW9Lg.png)
![page rules](https://i.imgur.com/sJUp6Wi.png)

**Host Info (please complete the following information):**
 - OS: Debian stable
 - Wiki.js version: 2.2.51
 - Database engine: SQLite

**Comment by NGPixel** [comment]
Fixed by 8aba5305d87bea8841e414735da9fa46e9f3debb
