### ISSUE TITLE
LDAP Authentication results in "unable to verify the first certificate"

### ISSUE THREAD

**Issue by GV-007** [Requarks/wiki#1741]
**Question**
My LDAP server requires encryption, but is using self-signed certificates. It seems certificate checking fails (which is logic), how can i disable cert verification ?

**Host Info (please complete the following information):**
OS: Ubuntu 18.04, Docker swarm
Wiki.js version: requarks/wiki:2
Database engine: postgres:11-alpine

**Comment by NGPixel** [comment]
Added option to disable cert check for 2.3 (d1dd1f195bac97449048ccf318bbc4f5a7254eb8)
