### ISSUE TITLE
Login fails with username

### ISSUE THREAD

**Issue by JJ1LFC** [Requarks/wiki#1742]
**Describe the bug**
When giving local username to the login page, login fails with error `Invalid email / username or password.`
We are currently using emails to log in with the local accounts.

**To Reproduce**
1. Log in with a local account using the username.

**Expected behavior**
Succeed in log in with the username.

**Screenshots**
Log in screen
![Screenshot from 2020-04-21 06-42-01](https://user-images.githubusercontent.com/39832857/79802670-5952f580-839b-11ea-984b-a45d05a83764.png)
User management screen
It's localized for Japanese, but the same issue confirmed in English one.
`メールアドレス` is `Email`, and `表示名` is `Display Name`.
![Screenshot from 2020-04-21 06-42-31](https://user-images.githubusercontent.com/39832857/79802744-7f789580-839b-11ea-990b-a98c5ed29b85.png)

**Host Info (please complete the following information):**
 - OS: Docker Container (Linux)
 - Wiki.js version: 2.2.51
 - Database engine: PostgreSQL 11.7

**Additional context**
`Username` in the login screen may not be `Display Name` and this issue may natural (not a bug), but it's very confusing for users.

**Comment by TheWesDias** [comment]
We can't login with username, only with email. 
What would be the best solution here, maybe change the message to not mislead the user ?

**Comment by JJ1LFC** [comment]
> We can't login with username, only with email.

It seems it depends on the authentication method.
In my environment, we can login only with email to local method, and only with username to LDAP.

So, we need to check which ID is available for each method if we change the message.

**Comment by NGPixel** [comment]
Fixed by be499e5795a66e2293ae0159e61c2ff263fbc2cf
