### ISSUE TITLE
https://docs.requarks.io/ 503 Service Unavailable

### ISSUE THREAD

**Issue by warezit** [Requarks/wiki#1744]
**Question**
Describe in details what you are trying to achieve and where do you need guidance.

Trying to load https://docs.requarks.io/ in my web browser

**Host Info (please complete the following information):**
OS: Windows 10
Browser: Firefox

https://docs.requarks.io/ fails to load, and reports:
Docker Flow Proxy: 503 Service Unavailable
No server is available to handle this request.

Screenshot:
![image](https://user-images.githubusercontent.com/8278779/79816022-c341af80-8347-11ea-9774-7a92ed811968.png)

**Comment by Alan-Liang** [comment]
![](https://user-images.githubusercontent.com/16379418/79815818-3d0f8280-83b4-11ea-8496-b3232cedc1d0.png)

**Comment by warezit** [comment]
Back online! :)

Thank you!
