### ISSUE TITLE
Dark mode: Registration Page: BG color makes text input unreadable

### ISSUE THREAD

**Issue by warezit** [Requarks/wiki#1748]
**Question**
Describe in details what you are trying to achieve and where do you need guidance.

Trying to modify the Dark Mode Registration / Login page to textinput area background color to make text input readable.

**Host Info (please complete the following information):**
OS: Centos (core) 7.7.1908 x64
Wiki.js version: 2.2.51
Database engine: postgres 9.2.24
Node: 10.20.0

With dark mode enabled, background color in the text input boxes on the Registration page is nearly impossible to read.

Registration Page screenshot: 
![image](https://user-images.githubusercontent.com/8278779/79850791-0886d100-838a-11ea-9db6-e3b132914e37.png)

Also, with Dark mode enabled, the form styling is different on the Login page.

Login page screenshot here:
![image](https://user-images.githubusercontent.com/8278779/79850892-26543600-838a-11ea-9f7e-d053e493911c.png)

Also, here is a video, detailing what I am experiencing, and how I am trying to fix it (with no luck):
https://www.dropbox.com/s/ibnh1lc7s3gglmp/2020-04-21_04-28-18.mp4?dl=0

**Comment by NGPixel** [comment]
This is already fixed in 2.3

**Comment by warezit** [comment]
> 
> 
> This is already fixed in 2.3

Awesome! Thank you! :)

**Comment by KaKi87** [comment]
Hello,
How were you able to enable the Dark Mode on the login page ?
Thanks
