### ISSUE TITLE
git storage - move page 2.3.51 

### ISSUE THREAD

**Issue by sbonaime** [Requarks/wiki#1750]
with 2.3.51 I moved a page from 
/admin 
to 
/admin/home
using the move/rename tool on the page. 
The page was actulay moved and rename but I had the following error

<img width="527" alt="Capture d’écran 2020-04-21 à 21-04-20 15 03 19" src="https://user-images.githubusercontent.com/750709/79869388-904bfa00-83e1-11ea-87c0-27a08dbac703.png">

**Comment by NGPixel** [comment]
Which storage target(s) are you using?

**Comment by sbonaime** [comment]
I'am using Git and local storage

Node.js 12.16.1
PostgreSQL 9.6.17

**Comment by kingfisher77** [comment]
The same effect here. We use just Git-Storage.

**Comment by NGPixel** [comment]
Fixed by 566043ec4353bfc5188f1ee45fc76a68ae4422db

**Comment by sbonaime** [comment]
With  2.3.77, I have another error. In this example, I move a page from /help to /help/home

ENOENT: no such file or directory, stat '/home/wiki/wiki/data/repo/help.md
<img width="603" alt="Capture d’écran 2020-04-27 à 27-04-20 11 19 32" src="https://user-images.githubusercontent.com/750709/80356240-75fa9c00-8879-11ea-85a5-b72ddfac3683.png">
