### ISSUE TITLE
redirect_uri: Not a well formed URL.

### ISSUE THREAD

**Issue by Indom-hub** [Requarks/wiki#1752]
**Describe the bug**
Setting up Discord Authentication (as well as GitHub and Twitch). I get an error stating:

`{"redirect_uri": ["Not a well formed URL."]}`

or similar from other sites. It was working fine earlier today on all the sites linked and nothing was changed on my end.

I have noticed that when trying to log in with GitHub, I get an error screen from wiki.js saying:

> The redirect_uri MUST be a valid URL.

The redirect_uri I have on GitHub is the same that was provided from the administration menu:

`https://civlife.theco-op.dev/login/github/callback`

However, I've noticed in the administration menu there is a space between .dev and /login. Looking like this:

`https://civlife.theco-op.dev /login/github/callback`

I'm not sure if Wiki.js thinks that space should be there, or if there is another error.

**To Reproduce**
1. Attempt to log in via Discord, Twitch, or GitHub integration
2. Receive an error screen stating something along the lines of "Invalid URI/Callback URL"

**Expected behavior**
After authenticating with 3rd party, login in or create an account on Wiki. 

**Screenshots**
Discord: https://prnt.sc/s3quao
GitHub: https://prnt.sc/s3qugi
Twitch: https://prnt.sc/s3qu2q

**Host Info (please complete the following information):**
 - OS: Docker Container (Linux)
 - Wiki.js version: 2.2.51
 - Database engine: PostgreSQL 11.7

**Additional context**

**Comment by NGPixel** [comment]
In Admin > General, do you have a trailing slash and/or a space at the end of the Site URL?

**Comment by co-op-deneb** [comment]
There was a space there, yes. I just removed the space. I’ll try again in a few minutes to login via Discord
