### ISSUE TITLE
Google Authentication not working - redirecting to landing page

### ISSUE THREAD

**Issue by rajeevsdm** [Requarks/wiki#1754]
**Question**
Upon login attempt with Google Auth, the user is redirected back to the home page and need to login again. i.e Unable to login with no error.

**Host Info:**
OS: Ubuntu 16.04
Wiki.js version: 2.2.51
Database engine: 12.1

**Comment by NGPixel** [comment]
Did you give read access to the homepage for that group?

**Comment by rajeevsdm** [comment]
Created a group 'general' which have the following permissions:
read: pages
read: assets
read: comments
write: comments

apart from these any one else is needed?

**Comment by NGPixel** [comment]
You need to set page rules as well.

**Comment by rajeevsdm** [comment]
Thanks for your support!!!
It's working well now.
