### ISSUE TITLE
Unable to display tree-based nav with MySQL

### ISSUE THREAD

**Issue by takumi9942** [Requarks/wiki#1756]
**Describe the bug**
If wikijs using mysql for database, tree-based navigation cause error.

**To Reproduce**
1. Create a page or open page in the folder (``/test/testpage``).
2. Try to enable tree-based navigation from sidebar.
3. See error - ``An unexpected error occured.``

**Expected behavior**
Tree-based navigation should be displayed without error.

**Screenshots**
![Screenshot from 2020-04-22 20-19-52](https://user-images.githubusercontent.com/18533151/79977261-eea7d400-84d8-11ea-8714-9167aef93e27.png)

**Host Info (please complete the following information):**
 - OS: Linux
 - Wiki.js version: 2.3.51
 - Database engine: mysql  Ver 15.1 Distrib 10.4.12-MariaDB

**Error detail**
```
[GraphQL error]: Message: select * from `pageTree` where (`localeCode` = 'ja' and `parent` = 5 or `id` in '[5]') order by `isFolder` desc, `title` asc - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''[5]') order by `isFolder` desc, `title` asc' at line 1, Location: [object Object], Path: pages,tree
```

**Comment by NGPixel** [comment]
Fixed by 7c59bfed084139fc6bc316981d206aab2ef3b410
