### ISSUE TITLE
Is it possible to add time code to the video?

### ISSUE THREAD

**Issue by Scrik** [Requarks/wiki#1758]
**Question**
Is it possible to add time code to the video? 

Like on youtube 1m43s

**Host Info (please complete the following information):**
OS: Centos 7
Wiki.js version: Stable 2.2.51
Database engine: postgres 11

**Comment by NGPixel** [comment]
https://www.google.com/search?q=youtube+embed+timestamp

**Comment by Scrik** [comment]
and if you upload your video, not from youtube?

**Comment by Scrik** [comment]
UP

**Comment by NGPixel** [comment]
You'd have to use javascript, which is not possible in the current version.

**Comment by Scrik** [comment]
In which version will it be available?
