### ISSUE TITLE
Passing an ssl cert from the host into the docker container

### ISSUE THREAD

**Issue by UnlimitedCookies** [Requarks/wiki#1759]
Hi! Is it currently possible to pass an HTTPS Certificate from the host machine to the docker container with an environment variable? And if not can this get implemented?

I think the use of a volume would be needed for this.

We generate the ssl certs in one place, but prefer to use an environment variable instead of and using the config file - this way we can still have all our configuration in the docker compose file.

Thanks!

**Comment by Smankusors** [comment]
so your wiki.js is directly connected to the node.js server? Not through a reverse proxy?

**Comment by UnlimitedCookies** [comment]
There is a reverse proxy in between. We generally don't want to have unencrypted traffic in between the node.js server and the reverse proxy, which sits in a different network. And yes I know we could spin up a reverse proxy on the host itself, but that seems unnecessary.

In general, it would seem plausible that when adding an auto generated Let's Encrypt Cert with an ENV variable would be supported, but a custom cert file not.

**Comment by Smankusors** [comment]
Why not implement SSL on the reverse proxy instead of Wiki.js? What I meant is SSL on the reverse proxy to the internet, not between reverse proxy and Wiki.js

**Comment by UnlimitedCookies** [comment]
I've understood what you mean. But like I said, we try to avoid an unencrypted connection between the reverse proxy and the wiki.js server, because that would be the case if we implemented the ssl on the rev proxy. (For obvious security reasons)

Wiki.js already supports using your own ssl cert, I just ask to be able to configure this with a docker environment variable.

**Comment by NGPixel** [comment]
It's not possible to pass the certificate as env variable at the moment. The only option for a custom cert is to mount a volume into the container. Feel free to submit a [feature request](https://wiki.js.org/feedback) though.

**Comment by cyayung** [comment]
Is this not gona work?

`docker create --name=wiki -e DB_TYPE=postgres -e DB_HOST=db -e DB_PORT=5432 -e DB_PASS_FILE=/etc/wiki/.db-secret -v /etc/wiki/.db-secret:/etc/wiki/.db-secret:ro -e DB_USER=wiki -e DB_NAME=wiki -e UPGRADE_COMPANION=1 --restart=unless-stopped -h wiki --network=wikinet -p 80:3000 -p 443:3443 -e "LETSENCRYPT_DOMAIN=wik.dev852.com" -e "LETSENCRYPT_EMAIL=cyayung@gmail.comm" -e SSL_ACTIVE=1 requarks/wiki:2`
