### ISSUE TITLE
I need a linked image on a page

### ISSUE THREAD

**Issue by navjotk** [Requarks/wiki#1760]
**Question**
I would like to add links to social media pages on my home page - with the logos for the corresponding social networks. I understand that this is not possible with the visual editor. I understand that this could be done with Markdown though. Can I write parts of the page in Markdown while still using the visual editor? I imagine I can't change the editor of the home page now. I also tried sshing into the VM (this is running on DigitalOcean) to just change the MD file on disk. Could not locate it. I have installed using the DigitalOcean marketplace image with no changes. 

**Host Info (please complete the following information):**
OS: Ubuntu 18.04/Docker/DigitalOcean Image 
Wiki.js version: 2.2.51
Database engine: postgres 11

**Comment by Smankusors** [comment]
FYI, there's no physical files for each pages. All of it saved on the database. That is, including the assets you uploaded.

**Comment by navjotk** [comment]
Thanks. I feel stupid looking for them on the filesystem now. 

However, the other part of my question still stands. It would be much cleaner if I could embed a Markdown snippet while still using the visual editor. Is that possible?

**Comment by NGPixel** [comment]
Not yet but planned for a future release.
