### ISSUE TITLE
 there will be ntlm support?

### ISSUE THREAD

**Issue by Scrik** [Requarks/wiki#1764]
Hello
there will be ntlm support?

**Comment by NGPixel** [comment]
Submit a [feature request](https://wiki.js.org/feedback/).

However this could challenging to implement as it only provides a username. Wiki.js requires an email address and a display name to be returned as well.

**Comment by Scrik** [comment]
@NGPixel , please, help.
A very important function that will make it easier to access the documentation
I submitted a feature request on May 19, 2020, will there be any response?
https://requarks.canny.io/wiki/p/add-ntlm-support

**Comment by Scrik** [comment]
NTLM will give the username, then make a request to AD to get Email and first name last name.
Compare the login from NTLM with AD and take the necessary information from AD

**Comment by Scrik** [comment]
especially since NTLM is configured on the web server. Next, Node.js receives information about the user's login. We look at this login in AD and take email, first and last name from AD. If there is no user, then in the transparent user mode we create and operate transparent authorization. Those. the user does not enter a username and password. If a user has already been created with such a login, then he simply has authorization without a login and password. It's easier than typing your credentials and remembering your password every time. Even if you changed it.
