### ISSUE TITLE
Unable to fix path for page after saving ending path with a trailing slash.

### ISSUE THREAD

**Issue by Sousaplex** [Requarks/wiki#1769]
Bug Description:
When changing the path of a page to instead end with a trailing "/" (eg. "name1/name2" -> "name1/") the original page will become inaccessible. Requests to name1/ will redirect to a page name1 which does not exist.

Attempts to fix this mistake by editing the path in Administration/Pages (/a/pages/[pageid]) does not work. Attempts to edit the page lead to page for creating a new page. Attempts to edit the path of the page in the properties panel also do not work as the edit button is unresponsive.

Reproduction Instructions:
1. Create a page with a path called "name1/name2"
2. Change the path of this page to "name1/"
3. Attempt to edit the path in Administration/Pages in the properties panel

Host Info:
 - Marketplace image from DigitalOcean
 - OS: Ubuntu 18.04, Docker 19.03
 - Database: PostgreSQL 11
 - Wiki.js version: 2.2.51

Additional Context:
I'm extremely new to wikijs and made what I feel is a stupid mistake. I don't have much experience with docker, otherwise I would have tried to open up the database and update the path directly, but was unable to find the postgres db in the terminal.

If saving a page with a trailing slash breaks it in this way, I would suggest that the trailing slash is automatically removed before saving. Again, I'm new to wikijs so I'm not sure if it ending in a trailing slash serves some other important function.

**Comment by NGPixel** [comment]
You're right that it should be automatically removed. This is fixed by 7306fabdbaad9aca0a91b1dbf72fc458caa0550e for 2.3.

To fix your current page, you'll need to delete it and create it again with the correct path.

**Comment by Sousaplex** [comment]
That would mean that all the content in that page is lost? Is there no way to go into the database and update the path?

**Comment by NGPixel** [comment]
Just edit the page, copy the content, delete it, create a new one and paste the content.

Yes you can also edit the entry directly in the DB but you'll need to flush the cache afterwards.
