### ISSUE TITLE
Is it possible to migrate pages from one wiki to another?

### ISSUE THREAD

**Issue by mottersen** [Requarks/wiki#177]
I have a messed up instance of wikijs, so I'd like to bring up a new one and move the data over.  Is that currently possible in any automated fashion?

**Comment by NGPixel** [comment]
It's actually quite easy. Simply copy your `/repo` folder (or specific pages) to the new instance and start/restart your wiki.

**Comment by mottersen** [comment]
Awesome, that will work out well.
