### ISSUE TITLE
Google Cloud deployment

### ISSUE THREAD

**Issue by tenwalls** [Requarks/wiki#1771]
**Question**
I've deployed the marketplace Docker image advertised on Google Cloud Platform. It's the current stable release (2.2.51). I'd like to track the development release which I understand is 2.3 as it contains a feature I very much want now. How can I achieve this? And for my own knowledge, what is the typical release cadence/ time lag, to promote a Dev release to stable branch.

**Host Info**
OS: [GCP Docker instance]
Wiki.js version: [2.2.51]
Database engine: [postgres 11.7]

**Comment by NGPixel** [comment]
2.3 is now released.

The best way to track new stable and beta releases, is to follow us on twitter: https://twitter.com/requarks

In general, a new release is published every month or so.
