### ISSUE TITLE
Errors in Code, Please modify!

### ISSUE THREAD

**Issue by ZhiShiMao** [Requarks/wiki#1772]
createPage in file (server/models/pages.js) 

line 217: opts.path.index('\\')
should be: opts.path.indexOf('\\') >= 0

lien 222: if (opts.path.endsWidth('/')) {
should be: if (opts.path.endsWith('/')) {

**Comment by NGPixel** [comment]
Fixed by 89debd57f7d250a5f7450738435f2c51c9e9deed
