### ISSUE TITLE
WIki.js suggests to upgrade to an older version

### ISSUE THREAD

**Issue by sebster** [Requarks/wiki#1773]
**Describe the bug**
The wiki says a newer version is available and shows an older version, not a newer version.

**To Reproduce**
1. Go to 'Administration'

**Expected behavior**
The wiki does not say there is a newer version available.

**Screenshots**
![bug](https://user-images.githubusercontent.com/1171798/80275255-9850b600-86cf-11ea-86cc-92edcd1a1e23.png)

**Host Info (please complete the following information):**
 - OS:Ubuntu 18.04, Docker Compose
 - Wiki.js version: 2.3.73
 - Database engine: postgres 11.7

**Additional context**
None.

**Comment by NGPixel** [comment]
An hotfix release will be published shortly to address this issue.
