### ISSUE TITLE
Navigation contents disappears when upgrading to 2.3.73

### ISSUE THREAD

**Issue by JJ1LFC** [Requarks/wiki#1774]
**Describe the bug**
After upgrading from 2.2.51 to 2.3.73, custom navigation menu contents disappear.

**To Reproduce**
1. Set a custom navigation menu.
2. Upgrade wiki.js to 2.3.73.
3. See the navigation menu or 'navigation' tab in the administration screen.

**Expected behavior**
Hold the whole contents after the upgrade.

**Screenshots**
![Screenshot from 2020-04-25 17-45-10](https://user-images.githubusercontent.com/39832857/80275505-99f49b00-871c-11ea-90a5-cfa9b9cf0220.png)
![Screenshot from 2020-04-25 17-45-27](https://user-images.githubusercontent.com/39832857/80275507-9c56f500-871c-11ea-9085-e53cca4b619d.png)

**Host Info (please complete the following information):**
 - OS: Docker Container (Linux)
 - Wiki.js version: 2.3.73
 - Database engine: postgres 11.6

**Additional context**

**Comment by JJ1LFC** [comment]
I noticed the `label` fields are not accepting direct typing of the Japanese language. I need to type the words somewhere else and copy&paste them into the `label` fields, otherwise, the words I typed disappears when focusing the cursor on other places.

**Comment by winkelement** [comment]
I can confirm the issue. Upgraded from `2.2.51` to `2.3.72` in a docker container. No errors in the log.
I highly recommend stating or **warning** or **pulling back the 2.3.72 release** completely until this is fixed.

**Comment by Naegolus** [comment]
++confirm;

**Comment by Naegolus** [comment]
For me, the fast reporting of issues on new versions is a sign that the update process of this wiki is really easy :)

**Comment by winkelement** [comment]
I'll just quote Nicolas from the Slack Thread:

> It's not lost. You need to enable multilingual namespacing and make sure English is in the list of active namespaces. Then go back to navigation and switch to English to see your navigation.
> I'm working on a fix to migrate navigations to other languages.

**Comment by NGPixel** [comment]
Added copy from locale feature in a4e5276922f8d56005abc6b9de163dbfed7ba74d

An hotfix release will be published shortly.

**Comment by JJ1LFC** [comment]
I just tried 2.3.77. `label` fields still denying direct input of the Japanese language, but navigation bar for each locale seems working well.

**Comment by Naegolus** [comment]
Have the same behaviour with 2.3.77
