### ISSUE TITLE
Icons not showing correctly after upgrade to 2.3.72 (When using IIS Reverse Proxy), but did work before with 2.1.113

### ISSUE THREAD

**Issue by NickHough5** [Requarks/wiki#1775]
### Actual behavior
Icons don't display correctly after upgrading to latest version (from 2.1.113 to 2.3.72)
Image below shows no icons showing in 2.3.72
![2 3 72 Image](https://user-images.githubusercontent.com/61250207/80278290-e7591400-86ec-11ea-9276-5ff0d7a75093.png)

Note the grey boxes or incorrect icons displayed!

Do note that this happens throughout the site and the admin panel is even worse, all navigation links on the left have a "grey" box where the nav icon should be.

### Expected behavior
Icons to show correclty, as they were in 2.1.113 (had to rollback files and Database), see below for working in 2.1.113.
![2 1 113](https://user-images.githubusercontent.com/61250207/80278349-723a0e80-86ed-11ea-8d36-549d35db2754.png)

### Steps to reproduce the behavior
Install fresh copy of 2.1.113 of WikiJS
Update to 2.3.72 of WikiJS
Make sure to use IIS with Reverse Proxy (guide here - https://medium.com/@harshamw/deploying-a-node-js-application-in-iis-using-a-reverse-proxy-process-management-using-pm2-3d59b83d7f76)
Do note here that it does work without issue when using localhost and the port number specified. But this also works as expected in 2.1.113 both locally and externally (using the URI)

**Comment by NGPixel** [comment]
You need to clear your browser cache and any reverse-proxy cache as well.

**Comment by NickHough5** [comment]
Already tried to clear browser cache and the reverse proxy is setup as a URL Rewrite rule.
I'm not using any form of ARR caching either.

**Comment by NickHough5** [comment]
Ignore me, it was being cached by Cloudflare, completely forgot i had that in front of my webserver :)
Thanks
