### ISSUE TITLE
Site Tree navigation mode does not work

### ISSUE THREAD

**Issue by siddhartha-lal** [Requarks/wiki#1776]
**Describe the bug**
When I use the side tree navigation mode or No navigation, no changes are implemented in the wiki.

**To Reproduce**
Change navigation mode and reload the wiki.

**Expected behavior**
Choosing side tree navigation or no navigation should produce the desired results.

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/56102539/80280777-42f6c200-872c-11ea-96e4-9d8464d61359.png)
![Untitled1](https://user-images.githubusercontent.com/56102539/80280780-4427ef00-872c-11ea-82fc-eecc6e267357.png)

**Host Info (please complete the following information):**
 - OS: Ubuntu 18.04
 - Wiki.js version: 2.3.72
 - Database engine: MySQL 5.7.29

**Comment by NGPixel** [comment]
Fixed by c15d1a49675017144fd7f8796555653d6a622582

An hotfix release will be published shortly.
