### ISSUE TITLE
git synchronize non-standard port

### ISSUE THREAD

**Issue by vladisalv** [Requarks/wiki#1777]
I updated to version 2.3.73 and my git synchronization is broken. Checked few things:
* I can clone my repo with non-standard port on server outside of docker container
* I can clone it using my deploy key

Log from container:
```
2020-04-25T13:00:39.088Z [MASTER] info: (STORAGE/GIT) Initializing...
2020-04-25T13:00:39.110Z [MASTER] info: (STORAGE/GIT) Checking repository state...
2020-04-25T13:00:39.205Z [MASTER] info: (STORAGE/GIT) Listing existing remotes...
2020-04-25T13:00:39.223Z [MASTER] info: (STORAGE/GIT) Purging existing remotes...
2020-04-25T13:00:39.241Z [MASTER] info: (STORAGE/GIT) Setting SSL Verification config...
2020-04-25T13:00:39.256Z [MASTER] info: (STORAGE/GIT) Setting SSH Command config...
2020-04-25T13:00:39.285Z [MASTER] info: (STORAGE/GIT) Adding origin remote via SSH...
2020-04-25T13:00:39.297Z [MASTER] info: (STORAGE/GIT) Fetch updates from remote...
Connection closed by 134.209.251.51 port 22
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
error: Could not fetch origin

```
I noticed in log wiki.jk reports "Connection closed by 134.209.251.51 **port 22**". I'm definitely using record `ssh://git@my_server:3333/user/myrepo.git` and `SSH Port: 3333` in wikijs admin panel. Checked twice ;)

my configuration:
 - Ubuntu 18.04
 - docker container with wiki.js 2.3.73

**Comment by valderaplets** [comment]
same here https://github.com/Requarks/wiki/issues/1746

**Comment by valderaplets** [comment]
Anyway, wikijs writes an SSHCommand in .git/config with port 22:(. This overloads the custom ssh port

**Comment by NGPixel** [comment]
Explicit ssh port removed in b2931471c0796dc8989d1b5779bce7c17887dadd

Not sure why this was needed in the first place but it's gone now and shouldn't cause anymore issues.

An hotfix release will be published shortly.

**Comment by vladisalv** [comment]
@NGPixel just updated wikijs and the problem is gone! Thanks!

**Comment by JeremyKennedy** [comment]
For those coming to this issue later, wondering why Git is using port 22 when you specify it in the URL, this is what fixed it for me.

In the WikiJS UI, it gives the example format: 
```git@github.com:org/repo.git```
So I adapted my instance with the port:
```git@mydomain.com:1234/username/wiki.git```
But really you should be using this format if you want to use a custom port:
```ssh://git@mydomain.com:1234/username/wiki.git```

I was using a docker container, and working directly with the Git repo was handy in debugging this, if you need to do that it's stored in the container under `/wiki/data/repo`. When running `git fetch` there wouldn't work, I knew it was an issue with my Git config and not WikiJS.

**Comment by Syphdias** [comment]
> I knew it was an issue with my Git config and not WikiJS

Indeed `git` assumes http with a username if you don't specify the protocol for a remote url. If you are able to clone the repo with `git clone $url`, WikiJS should be able as well.
