### ISSUE TITLE
requarks/wiki:2.3-arm from docker shows v.2.0 development version

### ISSUE THREAD

**Issue by manfr3do** [Requarks/wiki#1779]
**Describe the bug**
Version 2.3-arm shows Development Version 2.0

**To Reproduce**
Pull the image requarks/wiki:2.3-arm
Run the container
Open the WikiJS administration page

**Expected behavior**
Expected a stable 2.3 version

**Screenshots**
![grafik](https://user-images.githubusercontent.com/28313168/80287103-ce258700-872f-11ea-89d6-9f45a8f19e16.png)

**Host Info (please complete the following information):**
 - OS: Docker on Raspberry Pi 4
 - Wiki.js version: 2.3-arm
 - Database engine: postgres 12

**Additional context**
Thanks for the hard work!

**Comment by NGPixel** [comment]
Fixed by a1515e3f3e290656033cf4e61ff3af748fffeb2a

An updated version for arm will be published soon.

**Comment by NGPixel** [comment]
New image is now live. Let me know if you still get the wrong version / dev mode.

**Comment by manfr3do** [comment]
It works just fine now :)

![grafik](https://user-images.githubusercontent.com/28313168/80289899-06ce5c00-8742-11ea-8ace-db05b4cbb9ab.png)

Thank you for the quick response and this awesome project.
Have a nice day
