### ISSUE TITLE
GIT version check fails on CentOS 7

### ISSUE THREAD

**Issue by HaruIjima-kun** [Requarks/wiki#178]
I installed all the dependencies and prerequisites before installing WikiJS but always in CentOS I need a later version of GIT of 2.7.4

This is the version of GIT that I have currently installed.
git --version
git version 2.14.0-rc1

He tested several versions of GIT, including the minimum missing for WikiJS to work but there is no way to get it from here...

Help please!

**Comment by NGPixel** [comment]
I was able to install wiki.js successfully on CentOS 7 x64.

If you installed a new version of Git during or after running the wiki.js configuration wizard, it will not be detected right away (`git --version` will still return the old version to that process). You must terminate the process and the session. Start a new one and run `node wiki configure` from the wiki.js folder to start the configuration wizard again.

**Comment by HaruIjima-kun** [comment]
I installed the dependencies before running the installation and configuration wizard, I will also try to finish the process and the session, and then run "node wiki configure".

The order of installation of the dependencies that I follow is:
Npm
Nodejs
Mongodb
Git
WikiJS

**Comment by NGPixel** [comment]
Closing for now. Reopen ticket if you still need help.
