### ISSUE TITLE
Error when starting V2.3.77 with systemmd after migrating from V2.2.51

### ISSUE THREAD

**Issue by rlarrode** [Requarks/wiki#1781]
**Describe the bug**
When i reboot my server, service failed to start wikijs
```
systemd[1]: Started Wiki.js.
node[1508]: Loading configuration from /var/www/html/wiki2/config.yml... OK
node[1508]: 2020-04-25T22:25:53.570Z [MASTER] info: =======================================
node[1508]: 2020-04-25T22:25:53.572Z [MASTER] info: = Wiki.js 2.3.77 ======================
node[1508]: 2020-04-25T22:25:53.573Z [MASTER] info: =======================================
node[1508]: 2020-04-25T22:25:53.574Z [MASTER] info: Initializing...
node[1508]: (node:1508) UnhandledPromiseRejectionWarning: /var/www/html/wiki2/node_modules/fs-extra/lib/mkdirs/make-dir.js:86
node[1508]:       } catch {
node[1508]:               ^
node[1508]: SyntaxError: Unexpected token {
node[1508]:     at createScript (vm.js:80:10)
node[1508]:     at Object.runInThisContext (vm.js:139:10)
node[1508]:     at Module._compile (module.js:617:28)
node[1508]:     at Object.Module._extensions..js (module.js:664:10)
node[1508]:     at Module.load (module.js:566:32)
node[1508]:     at tryModuleLoad (module.js:506:12)
node[1508]:     at Function.Module._load (module.js:498:3)
node[1508]:     at Module.require (module.js:597:17)
node[1508]:     at require (internal/module.js:11:18)
node[1508]:     at Object.<anonymous> (/var/www/html/wiki2/node_modules/fs-extra/lib/mkdirs/index.js:3:44)
node[1508]:     at Module._compile (module.js:653:30)
node[1508]:     at Object.Module._extensions..js (module.js:664:10)
node[1508]:     at Module.load (module.js:566:32)
node[1508]:     at tryModuleLoad (module.js:506:12)
node[1508]:     at Function.Module._load (module.js:498:3)
node[1508]:     at Module.require (module.js:597:17)
node[1508]: (node:1508) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwin
node[1508]: (node:1508) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise reje
systemd[1]: wiki.service: Service hold-off time over, scheduling restart.
systemd[1]: Stopped Wiki.js.
```
But when i launch manually the server usin node server command it works fine
To configure the auto start, i followed the instructions availables in the installation guide

**To Reproduce**
1. Have an instance of wiki on 2.2.51
2. migrate this instance to 2.3.77 following upgrade guide
3. reboot server
4. See error using journalctl -u wiki

**Expected behavior**
Wiki auto start after rebbot

**Host Info (please complete the following information):**
 - OS: Dbian 9.10 on AWS EC2
 - Wiki.js version: 2.3.77
 - Database engine: postgress 9.5.20
- Node: 10.12.0

**Additional context**
Thank you for the great work you are doing with this project

**Comment by aptiko** [comment]
Are you absolutely certain that systemd and manual are using exactly the same node.js version?

I'm on Ubuntu 18.04. I tried to run Wikijs 2.3.77 with the OS-packaged node.js 8.10 and it crashed with this message. But if I run it with node.js 12.16 there' s no such problem.

Wikijs 2.2.51 behaves differently. When run with node.js 8.10, it starts alright, and when you visit it with your browser to complete setup then it tells you at some point that your node.js is too old.

**Comment by rlarrode** [comment]
Hi @aptiko, thank you for your remark, it appears that the version of nodejs installed in the exec start folder ahas been downgraded and the 10.12 installed in another location. i changed the exec start path and now it's working fine
Thx
