### ISSUE TITLE
Custom Layout

### ISSUE THREAD

**Issue by robinslange** [Requarks/wiki#1782]
**Question**
Trying to configure the wiki.js layout to fit in with an existing brand theme. This includes layout changes to just about every element of the pages. We're not worried about the dashboard, editor or user profiles at this stage and just want to change the 'wiki' part of the layout, if that makes sense.

**Host Info (please complete the following information):**
OS: Ubuntu 18.04.3 LTS
Wiki.js version: 2.3.71
Database engine: postgres 10.12

I see there's some configuration options within the default theme already but I don't know if any of that yet works. If yes, how do I enable this? If not, how would I best go about restructuring the layout?

**Comment by NGPixel** [comment]
See https://docs.requarks.io/dev/themes on how to create a custom theme.

However, this is very alpha and not supported. Proper theme support will be added in a future release.

**Comment by robinslange** [comment]
Upon trying that and following instructions to the letter all I end up with is a broken site giving the following errors:
