### ISSUE TITLE
Link page selector in visual editor adds bracket

### ISSUE THREAD

**Issue by joppehoekstra** [Requarks/wiki#1788]
**Describe the bug**
Inserting a link to an internal page using the new page selector in the visual editor adds a bracket ")" after each link, causing the link not to work.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open the visual editor.
2. Click the "Insert Link to Page" button.
3. Choose any page and click select.
4. The link will now refer to "path/to/page)"

**Expected behaviour**
Not to add a bracket behind every link.

**Host Info:**
 - OS: Ubuntu 18.04, Docker
 - Wiki.js version: 2.3.77
 - Database engine: Postgres 11.7

Thanks for maintaining this project!

**Comment by NGPixel** [comment]
Fixed by a3a1dc1267c1c86a632de2fa32da980dbb594692
