### ISSUE TITLE
Embedding Custom css/html in a page

### ISSUE THREAD

**Issue by MGodbey-developer** [Requarks/wiki#1790]
**Question**
I am trying to embed custom css style and html into a page. Code is inserted below. I am using the markdown editor - it renders perfectly in the editor. But when I go to the page the styles are not applied. I also disabled the Security sanitation setting in the administration/rendering/html security setting.

It is new fresh install  version 2.3.77, Linux Docker, Postgres 11.7, Node 12.16.1

Here is the code..

<style type="text/css">
      #content .wrap-collabsible {
        margin-bottom: 1.2rem 0;
      }

      input[type='checkbox'] {
        display: none;
      }

      .lbl-toggle {
        display: block;

        font-weight: bold;
        font-family: monospace;
        font-size: 1.2rem;
        text-transform: uppercase;
        text-align: left;

        padding: 0.3rem;

        color: #3782C4;
        background: #C0CCD6;

        cursor: pointer;

        border-radius: 7px;
        transition: all 0.25s ease-out;
      }

      .lbl-toggle:hover {
        color: #7C5A0B;
      }

      .lbl-toggle::before {
        content: ' ';
        display: inline-block;

        border-top: 5px solid transparent;
        border-bottom: 5px solid transparent;
        border-left: 5px solid currentColor;
        vertical-align: middle;
        margin-right: .7rem;
        transform: translateY(-2px);

        transition: transform .2s ease-out;
      }

      .toggle:checked + .lbl-toggle::before {
        transform: rotate(90deg) translateX(-3px);
      }

      .collapsible-content {
        max-height: 0px;
        overflow: hidden;
        transition: max-height .25s ease-in-out;
      }

      .toggle:checked + .lbl-toggle + .collapsible-content {
        max-height: 100vh;
      }

      .toggle:checked + .lbl-toggle {
        border-bottom-right-radius: 0;
        border-bottom-left-radius: 0;
      }

      .collapsible-content .content-inner {
        background: rgba(250, 224, 66, .2);
        border-bottom: 1px solid rgba(250, 224, 66, .45);
        border-bottom-left-radius: 7px;
        border-bottom-right-radius: 7px;
        padding: .5rem 1rem;
      }
  
</style>
<fieldset >
  <h3> Mission: To provide a mechanism to have a data drive view of risks across Aviation through dashboarding and analytics. </h3>
  
  <div class="wrap-collabsible">
    <input id="collapsible" class="toggle" type="checkbox">
    <label for="collapsible" class="lbl-toggle">Overview</label>
    <div class="collapsible-content">
      <div class="content-inner">
        <p>
          QUnit is by calling one of the object that are embedded in JavaScript, and faster JavaScript program could also used with
          its elegant, well documented, and functional programming using JS, HTML pages Modernizr is a popular browsers without
          plug-ins. Test-Driven Development.
        </p>
      </div>
    </div>
  </div>
    
</fieldset>

**Comment by NGPixel** [comment]
You need to add custom CSS via Admin > Theme. CSS within page content is not yet supported (coming in a future release).

**Comment by MGodbey-developer** [comment]
Thank you for the quick response - I will definitely try that! Do I need to do anything special to get them scoped to content vs global? Like do I just prefix the css with .content?

example if my css looks like  .wrap-collabsible { margin-bottom: 1.2rem 0; }
Do I change it to?                  #.content  .wrap-collabsible { margin-bottom: 1.2rem 0; }

**Comment by NGPixel** [comment]
Correct, e.g.:
```css
.content .wrap-collapsible {
  margin-bottom: 1.2rem 0;
}
```
