### ISSUE TITLE
Tree Site Navigation - Can't access selected folder

### ISSUE THREAD

**Issue by brendantop** [Requarks/wiki#1792]
**Describe the bug**
I can't access any page, via the Site Tree navigation, if it has subpages. 

**To Reproduce**
For example on your docs site, https://docs.requarks.io/, If I click on "Installation", at the top I can see
\(root)
    Installation

Below that and above "current directory", is a page link for Installation. I do not see those links for our pages.

**Expected behavior**
I should be able to access parent pages via Site Tree navigation.

**Screenshots**
I attached screenshots that illustrate your site vs ours.
![Screenshot 2020-04-26 at 11 22 18 PM](https://user-images.githubusercontent.com/55155765/80340093-df948f00-8814-11ea-843b-65e57767f2b0.png)
![Screenshot 2020-04-26 at 11 22 05 PM](https://user-images.githubusercontent.com/55155765/80340095-e02d2580-8814-11ea-9d57-22319e7c8f96.png)

**Host Info (please complete the following information):**
 - OS: Linux - CentOS (core) 7.7.1908 x64
 - Wiki.js version: 2.3.77
 - Database engine: 10.4.12-MariaDB

**Comment by NGPixel** [comment]
The docs website is running an unreleased version of Wiki.js, which includes a fix to display pages that have children. This is coming in 2.4.

**Comment by brendantop** [comment]
Ah, thank you for clarifying. One thing I noticed on your docs site that when you use that link to click on a parent page the tree navigation reverts to its parent rather than stay on the view in the tree you had. Is that the planned behaviour?

**Comment by NGPixel** [comment]
This will be fixed for 2.4.
