### ISSUE TITLE
sidebar.root displayed in the navigation menu while browsing a subfolder

### ISSUE THREAD

**Issue by rgarrigue** [Requarks/wiki#1793]
**Describe the bug**

There's a weird `sidebar.root` displayed, looks like a variable not interpreted

**To Reproduce**
1. In the navigation menu, click on browse
2. Navigate to any folder
3. The top tree element display `/ sidebar.root`

**Expected behavior**

Just displaying a `/` would do I guess

**Screenshots**

![image](https://user-images.githubusercontent.com/1872031/80349702-e8667e80-886f-11ea-8ebc-0d5ab051fc5a.png)

**Host Info (please complete the following information):**
 - OS: a couple of Debian 10 in HA mode
 - Wiki.js version: 2.3.77
 - Database engine: postgres

**Comment by NGPixel** [comment]
Clear your browser cache.

**Comment by rgarrigue** [comment]
Ok, thanks

**Comment by rgarrigue** [comment]
All good, thanks
