### ISSUE TITLE
Editor + Comments in admin panel

### ISSUE THREAD

**Issue by siddhartha-lal** [Requarks/wiki#1794]
**Question**
Is there any way to change the editor being used after the wiki has been installed? Editor, Comments, Logging options in the admin panel are all greyed out.

**Host Info (please complete the following information):**
OS: Ubuntu 18.04
Wiki.js version: 2.3.77
Database engine: MySQL (latest version)

**Comment by NGPixel** [comment]
You mean after a page is created? No, but it's coming in a future release.

These options are greyed out because they are not available yet.
