### ISSUE TITLE
GraphQL reponse for Page.single.toc: String cannot represent value: "..."

### ISSUE THREAD

**Issue by rtc11** [Requarks/wiki#1798]
**Describe the bug**
When fetching a single Page, toc returns an error and value `null` in the data response. 
My Table of Contents looks likt this:
- Method
- Preparation
- Instructions

**To Reproduce**
1. Create a new Page with at least one Heading 1 element.
2. Figure out the correct ID of this page
3. query:
```graphql
{
  pages {
    single(id: 7) {
      toc
    }
  }
}
```

**Expected behavior**
Content in field `toc` in the response other than `null`.

**Host Info (please complete the following information):**
 - OS: Docker Container (Linux)
 - Wiki.js version: 2.3.77
 - Database engine: PostgreSQL:11.7

**Comment by did** [comment]
I'm facing the same error. In my case, the page was written in Markdown in case it helps.

**Comment by 540240126** [comment]
same here

**Comment by 540240126** [comment]
same here
