### ISSUE TITLE
New Page? Linking? Search?

### ISSUE THREAD

**Issue by vlos** [Requarks/wiki#18]
Not really sure where this falls as an issue.
I created a new page (showing "new-page.md" in my repo directory.

Yet when I search for the page, nothing comes up.

On my sidebar (under navigation) it does not show, but if I navigate to it /new-page it comes up fine. 

Also I would change "Start" to "Top of Page" - much clearer. Maybe even put "Contents" as "Page Contents" (as compared to "Wiki Contents". Originally thought it was the contents of my wiki, like most wikis have). Normally I expect an index or such along side bar. Not page contents.

**Comment by NGPixel** [comment]
Indeed, pages were not added to the index upon creating the page for the first time. Editing a page was updating the index though. This will be fixed in the next build.

I also changed the text you suggested, it makes sense.
