### ISSUE TITLE
Connectivity issues PostgreSQL

### ISSUE THREAD

**Issue by Tzeenchist** [Requarks/wiki#1800]
**Question**
I have never used PostgreSQL before. I'm having problems connecting to different versions of Linux. Please tell me what I'm doing wrong, and how I should do it right.

**Host Info (please complete the following information):**
OS: Ubuntu 20.04 LTS (GNU/Linux 5.4.0-26-generic x86_64)
Wiki.js version: 2.3.77
Database engine: PostgreSQL 12.2 (Ubuntu 12.2-4) on x86_64-pc-linux-gnu

```
sudo apt install unzip curl nano nginx mc wget tar postgresql postgresql-contrib
sudo apt update
usermod -a -G sudo postgres
sudo -i -u postgres
psql

CREATE USER wuser WITH PASSWORD 'pass';
CREATE DATABASE wiki WITH OWNER = wuser;
\q

exit

curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
sudo apt-get install -y nodejs

mkdir /var/www/wiki && cd /var/www/wiki
wget https://github.com/Requarks/wiki/releases/download/2.3.77/wiki-js.tar.gz && tar -xvf wiki-js.tar.gz
rm wiki-js.tar.gz
cp config.sample.yml config.sample.yml.back && mv config.sample.yml config.yml && nano config.yml

db:
  type: postgres
  host: localhost
  port: 5432
  user: wuser
  pass: pass
  db: wiki
  ssl: false

node server

[MASTER] info: =======================================
[MASTER] info: = Wiki.js 2.3.77 ======================
[MASTER] info: =======================================
[MASTER] info: Initializing...
[MASTER] info: Using database driver pg for postgres [ OK ]
[MASTER] info: Connecting to database...
[MASTER] error: Database Connection Error: 28P01 undefined:undefined
[MASTER] warn: Will retry in 3 seconds... [Attempt 1 of 10]
...
```

**Comment by Tzeenchist** [comment]
A similar situation exists in another OS.

Host Info :
OS: CentOS Linux release 8.1.1911 (Core)
Wiki.js version: 2.3.77
Database engine: PostgreSQL 12.2 on x86_64-pc-linux-gnu

```
dnf -y install epel-release nano curl tar unzip nginx mc wget && yum -y update
dnf install https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm
dnf -qy module disable postgresql
dnf install postgresql12-server
/usr/pgsql-12/bin/postgresql-12-setup initdb
systemctl enable postgresql-12 && systemctl start postgresql-12
sudo su - postgres
psql

CREATE USER wuser WITH PASSWORD 'pass'
CREATE DATABASE wiki WITH OWNER = wuser
\q

exit

sudo curl -sL https://rpm.nodesource.com/setup_12.x | sudo bash -
sudo yum install -y nodejs

mkdir /var/www/ && mkdir /var/www/wiki && cd /var/www/wiki
wget https://github.com/Requarks/wiki/releases/download/2.3.77/wiki-js.tar.gz && tar -xvf wiki-js.tar.gz
rm wiki-js.tar.gz
cp config.sample.yml config.sample.yml.back && mv config.sample.yml config.yml && nano config.yml

db:
  type: postgres
  host: localhost
  port: 5432
  user: wuser
  pass: pass
  db: wiki
  ssl: false

node server

[MASTER] info: =======================================
[MASTER] info: = Wiki.js 2.3.77 ======================
[MASTER] info: =======================================
[MASTER] info: Initializing...
[MASTER] info: Using database driver pg for postgres [ OK ]
[MASTER] info: Connecting to database...
[MASTER] error: Database Connection Error: 28000 undefined:undefined
[MASTER] warn: Will retry in 3 seconds... [Attempt 1 of 10]
...

```

**Comment by Smankusors** [comment]
I think it's just better to use docker instead you manually install them?

Anyway the error 28000 is about `INVALID AUTHORIZATION SPECIFICATION` and 28P01 is about `INVALID PASSWORD`. It's mentioned [here](https://www.postgresql.org/docs/9.0/errcodes-appendix.html). Have you tried to login PostgreSQL with your own created user?

**Comment by madisonblue** [comment]
what do you have in **pg_hba.conf**?

**Comment by Tzeenchist** [comment]
> pg_hba.conf

# Database administrative login by Unix domain socket
local   all             postgres                                peer

# TYPE  DATABASE        USER            ADDRESS                 METHOD

# "local" is for Unix domain socket connections only
local   all             all                                     peer
# IPv4 local connections:
host    all             all             127.0.0.1/32            md5
# IPv6 local connections:
host    all             all             ::1/128                 md5
# Allow replication connections from localhost, by a user with the
# replication privilege.
local   replication     all                                     peer
host    replication     all             127.0.0.1/32            md5
host    replication     all             ::1/128                 md5

**Comment by madisonblue** [comment]
and can you connect to the DB from CLI with those credentials? 
`psql wiki wuser`

**Comment by Tzeenchist** [comment]
> и вы можете подключиться к БД из CLI с этими учетными данными?
> `psql wiki wuser`

```
psql wiki wuser
psql: error: could not connect to server: FATAL:  Peer authentication failed for user "wuser"
```

**Comment by Tzeenchist** [comment]
> and can you connect to the DB from CLI with those credentials?
> `psql wiki wuser`

I add Ubuntu user:

```
sudo adduser wuser
...
sudo -u wuser psql wiki
could not change directory to "/root": Permission denied
psql (12.2 (Ubuntu 12.2-4))
Type "help" for help.

wiki=>

```
The connection was successfully established

**Comment by Tzeenchist** [comment]
> I'll try to repeat in Centos

In Centos, there is a CLI, but in the master this error did not disappear

**pg_hba.conf** 
```
# TYPE  DATABASE        USER            ADDRESS                 METHOD

# "local" is for Unix domain socket connections only
local   all             all                                     peer
# IPv4 local connections:
host    all             all             127.0.0.1/32            ident
# IPv6 local connections:
host    all             all             ::1/128                 ident
# Allow replication connections from localhost, by a user with the
# replication privilege.
local   replication     all                                     peer
host    replication     all             127.0.0.1/32            ident
host    replication     all             ::1/128                 ident
```

**Comment by Smankusors** [comment]
> > and can you connect to the DB from CLI with those credentials?
> > `psql wiki wuser`
> 
> I add Ubuntu user:
> 
> ```
> sudo adduser wuser
> ...
> sudo -u wuser psql wiki
> could not change directory to "/root": Permission denied
> psql (12.2 (Ubuntu 12.2-4))
> Type "help" for help.
> 
> wiki=>
> ```
> 
> The connection was successfully established
> 
> After these steps, I was able to complete the installation in Ubuntu (with other errors). I'll try to repeat in Centos

That I'm afraid, is not `wuser`, but rather `root` user. So adding new user to Ubuntu is not making any difference. You can check it by executing this query :

```
SELECT current_user;
```

**Comment by Tzeenchist** [comment]
> Are you prompted for password when executing this command?

No, the password was not requested. However, in Ubuntu, when running the _node server_ command, error _28P01_ disappeared.

**Comment by madisonblue** [comment]
```
#"local" is for Unix domain socket connections only
local   all             all                                     peer
```

[auth-pg-hba-conf](https://www.postgresql.org/docs/12/auth-pg-hba-conf.html)
[auth-peer](https://www.postgresql.org/docs/12/auth-peer.html)

**Comment by Tzeenchist** [comment]
> ```
> #"local" is for Unix domain socket connections only
> local   all             all                                     peer
> ```
> 
> [auth-pg-hba-conf](https://www.postgresql.org/docs/12/auth-pg-hba-conf.html)
> [auth-peer](https://www.postgresql.org/docs/12/auth-peer.html)

After changing to the value md5, this error disappeared.

**Comment by Tzeenchist** [comment]
Rebuilt. Does not work =D

**Comment by NGPixel** [comment]
Why don't you use Docker? It would greatly simplify your setup...

https://docs.requarks.io/install/ubuntu

**Comment by Tzeenchist** [comment]
> Why don't you use Docker? It would greatly simplify your setup...
> 
> https://docs.requarks.io/install/ubuntu

I like to do everything step by step). If I install MariaDB, then there are no problems. However, it is recommended to install with Postgrescl. It doesn’t work. I am a newbie in many ways, perhaps my mistakes will help someone make the right thing.

**Comment by Smankusors** [comment]
> > Why don't you use Docker? It would greatly simplify your setup...
> > https://docs.requarks.io/install/ubuntu
> 
> I like to do everything step by step). If I install MariaDB, then there are no problems. However, it is recommended to install with PostgreSQL. It doesn’t work. I am a newbie in many ways, perhaps my mistakes will help someone make the right thing.

Do you mean, step by step as barebone as possible? Because, the link provided by @NGPixel is also step by step, but made simpler with Docker.

Anyway to be honest I'm never touched PostgreSQL, but I'm able to set it up quickly with Docker. So I can just forget about technical details of PostgreSQL... :slightly_smiling_face: 

Since you are newbie, it's just recommended to use Docker. You don't need to have any trouble like this.

**Comment by Tzeenchist** [comment]
> > > Why don't you use Docker? It would greatly simplify your setup...
> > > https://docs.requarks.io/install/ubuntu
> > 
> > 
> > I like to do everything step by step). If I install MariaDB, then there are no problems. However, it is recommended to install with PostgreSQL. It doesn’t work. I am a newbie in many ways, perhaps my mistakes will help someone make the right thing.
> 
> Do you mean, step by step as barebone as possible? Because, the link provided by @NGPixel is also step by step, but made simpler with Docker.
> 
> Anyway to be honest I'm never touched PostgreSQL, but I'm able to set it up quickly with Docker. So I can just forget about technical details of PostgreSQL... 🙂
> 
> Since you are newbie, it's just recommended to use Docker. You don't need to have any trouble like this.

I do not deny that the solution with the help of docker is the simplest and most problem-free. I appreciate and respect that. But I’ll try again, I don’t want to give up.

**Comment by Tzeenchist** [comment]
With this configuration of file **pg_hba.conf**, the error disappears. I replaced all **ident** with **md5**. I can’t say that this is a better solution, because I can’t explain it. 

```
# TYPE  DATABASE        USER            ADDRESS                 METHOD

# "local" is for Unix domain socket connections only
local   all             all                                     peer
# IPv4 local connections:
host    all             all             127.0.0.1/32            md5
# IPv6 local connections:
host    all             all             ::1/128                 md5
# Allow replication connections from localhost, by a user with the
# replication privilege.
local   replication     all                                     peer
host    replication     all             127.0.0.1/32            md5
host    replication     all             ::1/128                 md5

```

**Comment by lidaof** [comment]
Thank you @Tzeenchist! I have same issue and your post solved it, thanks!
