### ISSUE TITLE
History for WYSIWYG editor shows complete file as changed

### ISSUE THREAD

**Issue by Baschdl** [Requarks/wiki#1804]
**Describe the bug**
The history for the WYSIWYG editor is not working as expected as all content is on one line. `git diff` displays everything as changed.

**To Reproduce**
1. Create page with WYSIWYG editor
2. Make changes
3. View history

**Expected behavior**
The history should show the diff clearly.

**Fix**
Write each `<p> </p>` on separate line

**Comment by NGPixel** [comment]
Fixed by fd91565e61105e1808f9d1e3dd7c18f338fddc15
