### ISSUE TITLE
Run the project Remote Containers - Reopen in Container Windows 10 

### ISSUE THREAD

**Issue by lavebug** [Requarks/wiki#1810]
**Describe the bug**
Installing dockerized development environment on Windows 10 getting an error

**To Reproduce**
1. Clone github repo.
2. Install Docker Desktop (includes Docker Compose) Windows 10 pro 1903.
3. Install Visual Studio Code, install extension Remote Development, click green button selected Remote Containers - Reopen in Container.
4. Got this:
ERROR: create containers_db-data: volume name "containers_db-data" cannot be a reserved word for Windows filenames
[6599 ms] Command failed: docker-compose --project-name containers -f c:\Users\alex.gontcharov\Desktop\Projects\wikiDocker\dev\containers\docker-compose.yml up -d --build

**Expected behavior**
Have dev enviroment running without errors

**Screenshots**
![image](https://user-images.githubusercontent.com/2514455/80773992-df4c0a80-8b18-11ea-8804-fa7b21b313a2.png)

**Host Info (please complete the following information):**
 - OS: Windows 10 Pro 1903, Docker desktop 2.2.0.5, Engine 19.03.8 Compose 1.25.4
 - Wiki.js version: 2.0.0
 - Database engine: postgres 11.7-4 64bit

**Comment by NGPixel** [comment]
I'm on Windows 10 Pro 1909, same versions for docker, and it works just fine.

Try upgrading to Windows 1909? As this seems to be the only difference.

**Comment by lavebug** [comment]
Same thing on 1909. I do not have WSL. Can I do it without VSCode Remote Development extention?
![image](https://user-images.githubusercontent.com/2514455/80820470-275c4300-8b94-11ea-9e3c-cf69ec447505.png)

**Comment by NGPixel** [comment]
See https://docs.requarks.io/dev#using-docker-generic for instructions without using VS Remote Dev
