### ISSUE TITLE
My nginx reverse proxy breaks some icons

### ISSUE THREAD

**Issue by msvendsentan** [Requarks/wiki#1811]
**Question**
Did a manual install on a new DO droplet (not via docker, it will be a multi-purpose droplet). Got wiki.js set up. When navigating to http://ipaddress:3000, everything loads fine and as expected. When navigating to http://subdomain.domain.com via a nginx reverse-proxy I had set up, icons break (as shown below). Many aren't loaded, some are in the wrong places.

![image](https://user-images.githubusercontent.com/18708553/80777140-33171d80-8b32-11ea-8599-1d66b87318dc.png)

**Host Info (please complete the following information):**
OS: Debian 10.3
Wiki.js version: Tested on 2.2.51, 2.3.77, problem exists for either.
Database engine: postgres 11

**Reverse Proxy**

```
server {
        listen 80;
        listen [::]:80;
        server_name subdomain.domain.com www.subdomain.domain.com;

        location / {
                proxy_set_header Host $http_host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_pass http://127.0.0.1:3000;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_next_upstream error timeout http_502 http_503 http_504;
        }
}
```

I suspect this is me not understanding nginx properly, but after a few hours of searching, I can't seem to find what I'm missing. Can anyone help?

Thanks in advance!

**Comment by Smankusors** [comment]
can you please screenshot your "Network" tab on browser's DevTools (shortcut is F12)?

**Comment by msvendsentan** [comment]
Hello,

In a really bizarre set of circumstances, it started working just fine this morning. Last night I had also checked it on incognito mode, and it was working, while it wasn't for regular browsing (despite clearing all data for the site). I can only chalk it up to a weird DNS issue? I had _just_ redone my name servers and pointed the domain at the ip. It's not something I know much about.

Anyway, I can't exactly pin down what was causing the issue as I can't recreate the issue anymore.

Thanks!
