### ISSUE TITLE
Edit header toolbar logo css, remove name

### ISSUE THREAD

**Issue by ElPolako** [Requarks/wiki#1812]
**Question**
Hello, I'd like to remove site name from header toolbar and change size of logo,
I was trying to inject css in Administration like
.v-avatar--tile {height: 64px!important; width: 155px!important}
but whole menu have changed, how can I make these changes?

**Host Info**
OS: Centos7
Wiki.js version: 2.3.77

**Comment by Smankusors** [comment]
you need more specific css rule instead of just `.v-avatar--tile`. Something like `.v-toolbar__content .v-avatar--tile`

**Comment by ElPolako** [comment]
Oh, thank you, I'v notice that,
last step, how to remove site name from header toolbar without removing it from title?

**Comment by Smankusors** [comment]
> Oh, thank you, I'v notice that,
> last step, how to remove site name from header toolbar without removing it from website title?

just set it with `display: none`?

**Comment by ElPolako** [comment]
Let it be 🤣 Thank you
