### ISSUE TITLE
Date is not rendered according to locale

### ISSUE THREAD

**Issue by systolan** [Requarks/wiki#1813]
**Description**
Regardless of selected locale, the date in the middle column of the rendered page (where it says "edited by...") is always rendered in american format.

**Expected behavior**
The dates should be rendered in the locale of the page selected or the format needs to be controlled from elsewhere (general settings?).

**Screenshots**
![image](https://user-images.githubusercontent.com/50365162/80813171-cfd8ca00-8bc9-11ea-89b3-39f4095ae295.png)

**Comment by NGPixel** [comment]
Added date format override in d2b99a2032aa6fead54d4b70f955f740ecc5308a for 2.4.
