### ISSUE TITLE
[MASTER] error: Error: Failed HTTP-01 Pre-Flight / Dry Run.

### ISSUE THREAD

**Issue by ntrview0** [Requarks/wiki#1814]
**Question**
Describe in details what you are trying to achieve and where do you need guidance.

During initial setup of wiki.js:  execute "/usr/local/wiki/node server" fails with error "(LETSENCRYPT) Error: Error: Failed HTTP-01 Pre-Flight / Dry Run."

Generation and installation of an SSL certificate via "certbot --apache" reported success. 
 
http-to-https redirects appear to be working. I used the certbot automation to rewrite the <VirtualHost> directive so it rewrites the plaintext http address with its secure equivalent. When I access http://art.thomas.treder.co , it successfully redirects to https://art.thomas.treder.co, and returns the site's index.html page.

Is it possible the "HTTP-01 Preflight/Dry Run" itself is what's failing?  More likely I've misunderstood a direction or overlooked some detail, but there are some inconsistencies between standard output and the logs:
 0.) Standard Output of the command indicates it has set the http challenge for my domain, art.thomas.treder.co 
1.) No POST operation is logged in /var/log/httpd/access_log during the timeframe of the HTTP-01 Dry Run. 
2.) The mtime of /var/www/html (the DocumentRoot) does not change before and after the test.     

Adding up 0-2, above, it looks like the process never attempted to write out that document containing the key which subsequent steps attempt to retrieve.  

I've attached, in tar.gz format, my httpd.conf. httpd-le-ssl.conf, config.yml, /var/log/httpd/access_log, Qualy Labs webpage testifying my certbot setup was successful, and firewall rules as the output of "iptables -L".

**Host Info (please complete the following information):**
OS: CentOS 7.8
Wiki.js version: 2.2.51
Database engine: postgres 12.2
node.js v12.16.2
apache 2.4.6

[05-03-2020 deleted attachments now that they've been read]
[05-03-2020 ok, so with edit history you can't really delete attachments, ever, apparently.]

**Comment by Smankusors** [comment]
You are using apache as reverse proxy. Unless your Wiki.js directly connected to the internet, you should use certbot apache instead.

**Comment by ntrview0** [comment]
Thank you.  Maybe I need to understand the I used "certbot --apache' as noted above.  
I've set "ssl: enabled: false".  Now "node server" stops at
 "[JOB] info: Rebuilding page tree: [ COMPLETED ]

**Comment by ntrview0** [comment]
Thanks for the clarity.  I decided to skip the added complexity of a reverse proxy for now.  Set "listen: 80" and "ssl: true", ran "node server", successfully accessed https://[domain], and am now about to click on "Create Home Page"
