### ISSUE TITLE
Will an AWS Reserved Instance work? 

### ISSUE THREAD

**Issue by RickCogley** [Requarks/wiki#1815]
**Question**

I'd like to know if I have a reserved instance on AWS EC2, will the marketplace flavor of Wiki.js use that?

**Comment by NGPixel** [comment]
I couldn't find any info on the subject.

A workaround would be the follow these steps to install Wiki.js, which is identical to what the marketplace image does:
https://docs.requarks.io/install/ubuntu

**Comment by rlarrode** [comment]
Hello,
You have to pay attention on the reserved instance you have provisionned on your EC2 page (number, type, location).
When you deploy the marketplace image, you have to choose an instance supported in your reserved instance list (and be sure to have provisionned enough instances)

Your new instance should be automatically covered

**Comment by RickCogley** [comment]
thanks @NGPixel @rlarrode! I did some more research, and the AWS docs say that reserved instances are just for discounting. They don't themselves run. If you have a running EC2 instance on a specific type, and then you buy a reserved instance of the same type, the discount represented by the reserved instance pricing (discount for volume) gets applied. If you have a pre-purchased reserved instance of the same type, its discount will get applied.
