### ISSUE TITLE
Footnote items do not have ID attr, marker anchors don't work

### ISSUE THREAD

**Issue by Pwuts** [Requarks/wiki#1819]
The footnotes are referenced correctly, except for one thing: the `<li class="footnote-item">`s at the bottom of the page are missing the `id` attribute, so the footnote markers in the text don't work as shortcuts to the corresponding footnote.
This problem arises in the rendered page only; in the (markdown) editor it works fine.

I tried it with numbers (`[^1]`; `[^1]: link`) as well as text (`[^fn1]`; `[^fn1]: link`).

I am having this problem on a freshly fetched docker image, newest available version, with the default rendering settings (except for "Automatically convert line breaks" which I turned off).

**Expected behavior**
As in the editor, the `<li class="footnote-item">` for `[^1]` should have an `id="fn1"` attribute, and so when a footnote marker is clicked, the viewport should jump to the corresponding footnote.

**Host Info:**
 - OS: Docker
 - Wiki.js version: 2.3.81
 - Database engine: Postgres 9.5.19

**Comment by NGPixel** [comment]
Fixed by c81ba5a5039d394193605c2fa0b9fa398eb41210
