### ISSUE TITLE
Downloading forever

### ISSUE THREAD

**Issue by broonu** [Requarks/wiki#182]
I'm following this guide: https://docs.requarks.io/wiki/install
Installation hangs forever in this message:
⠉⠙ Remote wiki.js tarball found. Downloading...

**Comment by NGPixel** [comment]
Make sure the process can access the internet + has write permissions to the folder it is being installed to.

**Comment by michielbeijer** [comment]
I'm having the same issue here. Working on a Ubuntu Server in Virtualbox. A lot of folders do get downloaded. Managed to run install.js in the node_modules/wiki.js folder. Allowed me to run the web based configuration (on port 3000), but after that the wiki doesn't start. No error message, but 'node wiki stop' claims there is no such process.

**Comment by TorbenJ** [comment]
I'm having the same issue running the installation in a docker container running debian.
I tried the same procedure a couple of days ago and it worked without any issues.

As I'm running docker on a windows machine I double checked with a docker instance on a linux machine, no success either.
I then tried to download the `wiki-js.tar.gz` archive as suggested in the `"Behind a proxy?"` section on https://docs.requarks.io/wiki/install.
Now I don't have the issue with the stuck "[..] Downloading..." message but instead with the "Local tarball found. Extracting..." message - on both machines.

**Comment by marc-fun** [comment]
Same problem with me on 2 different machines (a virtual in France, an other one hosted on Infomaniak).

I managed to extract manually wiki-js.tar.gz and node_modules.tar.gz (in node_modules) and modified the node_modules/wiki.js/install.js by removing :
```
then(() => {
  isContainerBased && console.info('>> Fetching tarball...')
  return tasks.installFromLocal().then(succeeded => {
    return (!succeeded) ? tasks.installFromRemote() : true
  })
})
```
If I run `node wiki configure`, server works up to the mongodb configuration and then it stops with a `✖ Not Found` message.
If I manually configure the config.yml, I can run `node wiki start`, it works but I have no admin account...

**Comment by NGPixel** [comment]
See #193
