### ISSUE TITLE
Change initial page path from home to something else

### ISSUE THREAD

**Issue by tiagobugarin** [Requarks/wiki#1824]
**Question**
Describe in details what you are trying to achieve and where do you need guidance.
At the moment of installation it guided me to create a first page, `/home` as path (the default, at the first moment I didn't knew about this), in `en` language (the only one available at the moment).
Then I setup my preffered language as `pt-br` (as my wiki will serve a brazilian user base) and created a new page to be the origin and give it a `/inicio` path (just to clarify, I am representing with the slash so you know it is at the root of the page structure, it actually does not have the slash at the page setup).
The thing is, how do I change the default first page the WikiJS displays from `home` to `inicio`, or any other for that matter?

Things I have tryed without success.
I tryed removing the `home` page and the  system simple behave as if there was no initial page at all letting me create a new `home`.
I looked at a dump of the SQL to see if there was anything there that would do the trick but I was not convinced I have found the thing to change, so I left this approach.

**Host Info (please complete the following information):**
OS: Debian 10 Buster, tar.gz install)
Wiki.js version: 2.3.81
Database engine: mariadb (15.1 Distrib 10.3.22-MariaDB)

**Comment by NGPixel** [comment]
No, `home` is always the homepage and cannot be changed. However you don't need to see it at all. If you type just `/`, it will load the `home` page.
