### ISSUE TITLE
Modified title and save bug

### ISSUE THREAD

**Issue by sbonaime** [Requarks/wiki#1826]
**Describe the bug**
Page is not marked as saved although is is ! 

**To Reproduce**
1. Edit any page
2. Click on the top center title of the page and modify the title
3. Click save. The page is saved but the button "save" does not change to "saved"
4. Click close for closing editor => A popup appears warning that the page is not saved. If ignore, the page title is the new one. So the page was really saved at step 3

I have the same problem if I modify the page title or description using the dedicated page editor menu

**Comment by kmpm** [comment]
Same if changing tags

**Comment by NGPixel** [comment]
Fixed by a75ead44d0122cf9080ec545adfa041c0df5ce7a
