### ISSUE TITLE
Page hidden if sub page

### ISSUE THREAD

**Issue by max13fr** [Requarks/wiki#1827]
**Describe the bug**
When you create subpage, the current page become inaccessible from the navigation because it's now a directory.

**To Reproduce**

First create a page **/test** with some content. The page is correctly displayed in the navigation.
Then create a sub page **/test/subpage**.

Now you can only display subpage from navigation but not test page because test became a directory instead of page.

**Expected behavior**

Always display a link to the page in navigation menu even if a directory has the same name.
I think the best way is to directly open the page when clicking on a directory with the same name (if the page is existing).

**Host Info (please complete the following information):**
 - OS: Docker Container (Linux)
 - Wiki.js version: 2.3.81
 - Database engine: postgres 12

Thanks in advance,
Max

**Comment by NGPixel** [comment]
This is already fixed in 2.4
