### ISSUE TITLE
Trouble Setting up Email Connection

### ISSUE THREAD

**Issue by b-zurg** [Requarks/wiki#1828]
**Question**
I'm trying to set up email sending and am having an impossible time to send an email through a gmail account.  

I also couldn't find any documentation on the topic for wiki.js (though admittedly it seems quite straightforward)

What are some troubleshooting steps? I tried following google's documentation about connecting through smtp.google.com or with gsuite smtp-relay.google.com with a gsuite account and any combination of ports, hosts, username and password were not working  and I always end up with the following message, which is quite vague.

![image](https://user-images.githubusercontent.com/57298613/80964058-e1fc7780-8e18-11ea-858f-1998cf87333a.png)

Additionally I'm unsure what implications the sender name + email will have for the final email. 

Could the gmail account being set up with 2FA have implications for this?  Is there any way to see the connection logs to identify more granularly what's going on beyond the generic message the user sees?

**Host Info (please complete the following information):**
Ubuntu 18.04, Docker
Wiki.js version: [e.g. 2.0.1]
Database engine: postgres 11.7

**Comment by Smankusors** [comment]
what is your mail configuration on Wiki.js side? (maybe screenshot it, but blur things that you think confidential)

If you have 2FA enabled, then you need to use App Passwords, as documented in [here](https://support.google.com/accounts/answer/185833).

**Comment by b-zurg** [comment]
This is the configuration - with the domain and email address changed.  

I did generate an app password and am using it here.  

![image](https://user-images.githubusercontent.com/57298613/81006173-bba9fc80-8e57-11ea-94e8-7d7911d03741.png)

**Comment by Smankusors** [comment]
the sender email field.... Isn't it should be user@domain.org?

**Comment by b-zurg** [comment]
Totally right.  

So I got a more helpful error message after that.  I was confused by the @ symbol next to the sender email and thought it was supposed to be the second half of the email...

It might be helpful to choose a different icon 🤷 

I think I might also have to enable insecure apps to set up an smtp connection with a google account.  Will report back :)

**Comment by silverprize** [comment]
@b-zurg May help you? https://support.google.com/mail/answer/185833?hl=en
And you have to save configuration before click "SEND EMAIL"
