### ISSUE TITLE
How to redeploy/upgrade Heroku install?

### ISSUE THREAD

**Issue by localjo** [Requarks/wiki#183]
What is the best way to upgrade a Heroku deployment? Or to makes changes to the code and redeploy? I'm having trouble with 1.0.0 Beta 13, and I'd like to upgrade to the latest version and potentially fix bugs myself.

### Actual behavior

Trying to upgrade a Heroku install to the latest version doesn't work. Logs show;

```
> wiki.js@1.0.4 postinstall /app/node_modules/wiki.js
> node install.js

module.js:487
    throw err;
    ^

Error: Cannot find module 'bluebird'

...

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wiki.js@1.0.4 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wiki.js@1.0.4 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

### Expected behavior

Latest version of Wiki.js should be installed.

### Steps to reproduce the behavior

`heroku run npm install wiki.js@latest`

**Comment by NGPixel** [comment]
You can't just run that command. Heroku apps are stateless. You must create a new one with the same settings + copy the existing MongoDB URI.

**Comment by localjo** [comment]
Ideally I'd like to have a setup where Heroku will automatically redeploy when I push a new commit. But I'm trying to figure out exactly how to fit all of the pieces together.

**Comment by NGPixel** [comment]
You should clone this repo and customize it to your needs:
https://github.com/Requarks/wiki-heroku

**Comment by localjo** [comment]
I'm trying to do that, but it seems like wiki.js is installed in the same directory, overwriting files that belong to the repo like `LICENSE` and `README.md`. I'm playing around with `.gitignoring` those files, but it's less than ideal. I'm trying to figure out if this is a problem that hasn't been solved yet, or if I'm approaching the install the wrong way.

**Comment by localjo** [comment]
It seems like wiki.js should be installed in `/node_modules` instead of the project root.

**Comment by NGPixel** [comment]
Wiki.js is an app that relies on node_modules, it's not a dependency itself. What you can do though is create a subfolder /wiki and use this folder as the root.

**Comment by localjo** [comment]
Is it possible to install wiki.js inside a subfolder like that? Experimenting now, but I'm not sure it's that simple.

**Comment by NGPixel** [comment]
Simply change the install command:
`mkdir -p wiki && cd wiki && npm install wiki.js@latest`

and the run command:
`web: cd wiki && node server`

**Comment by localjo** [comment]
Hmm, changing the install command still ends up installing in the root. And I'm not sure where the run command is.

**Comment by NGPixel** [comment]
install: package.json
run: Procfile

**Comment by localjo** [comment]
Changing the `postinstall` command in package.json to `mkdir -p wiki && cd wiki && npm install wiki.js@latest` still installs in the root, which overwrites `LICENSE`, `README.md` and most importantly, `package.json`. :( I think that's because the pwd passed to `npm install wiki.js@latest` is the pwd where the `postinstall` script is run from (it doesn't change with the `cd` command).

**Comment by localjo** [comment]
I'm still reading, trying to figure out the right way to do things here, but I think basically what we need to make this work the right way is a custom Heroku buildpack.

**Comment by localjo** [comment]
Heroku buildpacks are a little bit more complex than I originally thought. It's not just a matter of changing a quick build directory where `npm install` is run. It may actually be a rather hacky approach to workaround the problem. Right now the Wiki.js core app and the `wiki-heroku` app are installed in the same root, and since they have conflicting files one of them has to be moved. The `wiki-heroku` app can't really be removed from the root.

The standard way to do this in a node app would be to install wiki.js in `/node_modules` instead of root. This is basically what you suggested with the `/wiki` subdirectory, but using the standard place for dependencies.

I'm not sure if that's the full solution, but I'm having trouble articulating the rest of my thoughts. I'm going to continue attempting solutions to see if that clarifies anything for me.

**Comment by localjo** [comment]
Ideally we should be able to use Wiki.js as a dependency and an app that uses it could have a package.json that looks something like this;

```
{
  "name": "wiki-heroku",
  "dependencies": {
    "wiki": "1.0.4"
  },
  "scripts": {
    "start": "cd node_modules/wiki && node server"
  }
}
```

And there should be no need for a custom Procfile, since Heroku's default run script is `npm start`.

**Comment by NGPixel** [comment]
**Update**: The heroku installation script was updated to run wiki.js inside a subfolder and no longer uses npm install.
