### ISSUE TITLE
LDAP documentation page is not loading

### ISSUE THREAD

**Issue by palanjam** [Requarks/wiki#1831]
**Describe the bug**
The page at https://docs.requarks.io/auth/ldap does not load.

**To Reproduce**
1. Go to https://docs.requarks.io/auth/ldap
2. See blank page

**Expected behavior**
A page with documentation

**Host Info (please complete the following information):**
Tried on firefox and safari on mac and firefox on android

**Comment by winkelement** [comment]
`{{username}}` in the text is somehow interpreted as a variable by some js leading to an error.
See https://github.com/Requarks/wiki-docs/blame/master/auth/ldap.md#L19

**Comment by NGPixel** [comment]
Fixed
