### ISSUE TITLE
Non-Administrators cant upload image from PC

### ISSUE THREAD

**Issue by VasekProchazka** [Requarks/wiki#1835]
**Describe the bug**
The user cant upload image from PC. It is work only if the user has administrators privileges.

**To Reproduce**
1. Create new group
2. add user to group
3. edit some page with user account
4. try upload image

**Expected behavior**
The image should upload

**Host Info (please complete the following information):**
 - OS: Ubuntu 18.04, Docker
 - Wiki.js version: 2.3.81
 - Database engine: postgres 9.6.17

tested on MacOs and Windows

**Comment by winkelement** [comment]
Have you verified the correct group permissions are set?

<img width="525" alt="Bildschirmfoto 2020-05-05 um 13 59 45" src="https://user-images.githubusercontent.com/3525191/81063847-dd979380-8ed8-11ea-9817-39b7d5f5b67c.png">

**Comment by VasekProchazka** [comment]
Yes. I have set all content rights except delete pages.

**Comment by winkelement** [comment]
Then also make sure you have them enabled in the page rules.
<img width="853" alt="Bildschirmfoto 2020-05-05 um 14 23 40" src="https://user-images.githubusercontent.com/3525191/81065741-5e0bc380-8edc-11ea-9d1c-97e06fa63be9.png">

**Comment by VasekProchazka** [comment]
I checked it  and everything is set correctly. I also add screenshot here, how the problem looks. Because for me, it does not look like permission problem. On the other hand I can upload image in administration group with no problem.
<img width="377" alt="Snímek obrazovky 2020-05-05 v 13 41 55" src="https://user-images.githubusercontent.com/13906845/81066021-be9b0080-8edc-11ea-96db-8b585bb40192.png">

**Comment by Smankusors** [comment]
Can you screenshot your Network tab on DevTools (shortcut: F12)? Open it before uploading, try to reproduce again, and screenshot the contents of your Network tab

**Comment by VasekProchazka** [comment]
<img width="1680" alt="Snímek obrazovky 2020-05-05 v 18 06 48" src="https://user-images.githubusercontent.com/13906845/81088490-498af380-8efb-11ea-8521-efca35f2a8a3.png">
<img width="1677" alt="Snímek obrazovky 2020-05-05 v 18 06 36" src="https://user-images.githubusercontent.com/13906845/81088503-4d1e7a80-8efb-11ea-91e4-cb20f7523044.png">

**Comment by Smankusors** [comment]
have you tried to restart Wiki.js?

**Comment by VasekProchazka** [comment]
Yes. Before I created the issue, we also upgraded to last version, but it also does not help.

**Comment by NGPixel** [comment]
Can you post a screenshot of the group Permissions tab and Page Rules tab?

**Comment by VasekProchazka** [comment]
Sorry for late response. The screenshots:

<img width="551" alt="Snímek obrazovky 2020-05-12 v 13 20 24" src="https://user-images.githubusercontent.com/13906845/81680509-74250100-9453-11ea-9162-927d6c259910.png">
<img width="1373" alt="Snímek obrazovky 2020-05-12 v 13 20 59" src="https://user-images.githubusercontent.com/13906845/81680534-7e46ff80-9453-11ea-9a39-f3f67b079898.png">

**Comment by NGPixel** [comment]
Unless your users are uploading files to a folder named `advert`, then it's normal they can't upload anything.

If you want users to upload files in any location, you need to create another rule just for assets at path `/`

**Comment by VasekProchazka** [comment]
Thanks for help.
