### ISSUE TITLE
In menu, folder does not re-render the page.

### ISSUE THREAD

**Issue by VasekProchazka** [Requarks/wiki#1836]
**Describe the bug**
If i click in menu on folder, which I created, the content and url does not change

**To Reproduce**
1. Click on folder in menu

**Expected behavior**
the content should re-render and the url should change. 

**Host Info (please complete the following information):**
 - OS: OS: Ubuntu 18.04, Docker
 - Wiki.js version: 2.3.81
 - Database engine:  postgres 9.6.17

**Additional context**
Tested on macos and windows

**Comment by NGPixel** [comment]
This is already fixed for 2.4
