### ISSUE TITLE
Mermaid diagrams render in markdown editor preview but not in final page

### ISSUE THREAD

**Issue by dfsnow** [Requarks/wiki#1839]
**Describe the bug**
Per the release notes [here](https://docs.requarks.io/releases), Mermaid diagrams are supported in wiki.js version >= 2.3.71. Mermaid diagrams render correctly in the markdown live editor, but fail to render in the generated page. This seems to be the result of a missing dependency.

**To Reproduce**
Using wiki.js release 2.3.81, the bug can be reproduced using the following steps:

1. Create a markdown document with a mermaid diagram using the following syntax:

> \## Diagram
> 
> \```mermaid
> graph TD
>   A[Christmas] -->|Get money| B(Go shopping)
>   B --> C{Let me think}
>   C -->|One| D[Laptop]
>   C -->|Two| E[iPhone]
>   C -->|Three| F[fa:fa-car Car]
> \```

2. Save the page. The diagram renders correctly in the preview.
3. Go to the saved page. The diagram renders as a code block rather than as a diagram.

**Expected behavior**
Mermaid diagrams should be rendered in the final page but are only rendered in the markdown editor preview.

**Additional context**
Looking in the console, it seems like there might be a mermaid dependency missing. I get the following error:

```
Failed to load resource: the server responded with a status of js/prism/prism-mermaid.min.js:1 404 (Not Found)
```

**Comment by b-zurg** [comment]
Reproduced.  This is a truly amazing feature by the way.

**Comment by NGPixel** [comment]
The error you mentionned is completely unrelated and doesn't affect the rendering of mermaid diagrams.

Have you tried to clear your browser cache?

**Comment by dfsnow** [comment]
Missing `prism-mermaid.min.js` is not related to rendering mermaid? This missing lib error only appears on rendered pages that have mermaid diagrams.

**Comment by NGPixel** [comment]
prism-mermaid is only used to color highlight the mermaid code, it has nothing to do with actually generating the diagram.

**Comment by dfsnow** [comment]
Ah, apologies, that makes sense. I tried clearing the browser cache, bypassing my reverse proxy, and restarting the container. Still no luck :/

**Comment by b-zurg** [comment]
I tested in incognito chrome and edge,

What I see in preview:
![image](https://user-images.githubusercontent.com/57298613/81475260-c4ae1b80-9213-11ea-8e8f-9e33c90ed166.png)
What see rendered:
![image](https://user-images.githubusercontent.com/57298613/81475245-b5c76900-9213-11ea-988f-7416010f1fc3.png)

In preview I do see the following console message:
```
/js/prism/prism-sh.min.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
```
In rendered I see the following console messages:
```
![image](https://user-images.githubusercontent.com/57298613/81475315-050d9980-9214-11ea-99a5-41dab8aa861b.png)
```

**Comment by NGPixel** [comment]
Is the mermaid module enabled in **Administration** > **Rendering** > **HTML** > **Mermaid**?

**Comment by dfsnow** [comment]
Yep, toggled it off/on multiple times, cleared cache, tried a new window, etc. No effect. This is true for both Firefox and Chrome.

**Comment by kbfifi** [comment]
I had a problem with plantuml then NGPixel said to re-save the page with plantuml.

Now back to your problem. I can reproduce it. I was not aware of a mermaid setting. Enabled it. Reloaded the page => no rendenring. Then in analogy of my problem saved the page again => bingo, the mermaid diagram renders

**Comment by dfsnow** [comment]
> Now back to your problem. I can reproduce it. I was not aware of a mermaid setting. Enabled it. Reloaded the page => no rendenring. Then in analogy of my problem saved the page again => bingo, the mermaid diagram renders

That did the trick! Thanks @kbfifi, it's a great short term solution.

**Comment by MRIIOT** [comment]
DO Docker, v2.5.201

Mermaid renders in preview, but not on final page.

![image](https://user-images.githubusercontent.com/48079336/129486222-0021f8d1-0cf5-4203-af3a-84538af84952.png)
