### ISSUE TITLE
What is "Mail" used for?

### ISSUE THREAD

**Issue by ccolella-mdc** [Requarks/wiki#1841]
**Question**
So, I setup the Mail stuff in the Admin panel, but what is it used for and when does it get used? What should I expect to get emails about?

**Host Info**
OS: Windows Server 2012 R2
Wiki.js version: 2.3.81
Database engine: MS Sql Server 2016

**Comment by b-zurg** [comment]
At the very least I think local user password recovery. But I think it would be cool if you got notifications when someone else edited a page you interact with. 

Not sure though - Just as curious as you!

**Comment by ccolella-mdc** [comment]
Definitely would be cool to be able to turn on and off certain notifications.

- Certain page gets edited
- New Page added
- Page deleted
- Admin Settings changed maybe

**Comment by NGPixel** [comment]
It's used to send new account invitations, password reset, etc.

In the future, it will be used to send notifications as well.
