### ISSUE TITLE
No way to exit "low distraction mode"

### ISSUE THREAD

**Issue by madduck** [Requarks/wiki#1843]
After entering low-distraction (full page) mode, there seems to be no way to close the window, or even save the page:

![image](https://user-images.githubusercontent.com/195073/81234106-39365e00-904c-11ea-8346-7e8857095ff2.png)

If I'd try to "go back", I'd lose all changes. The only way I found thus far was copy all text, go back, re-edit, paste, save…

**Host Info (please complete the following information):**
 - OS: Debian 10
 - Browser: Firefox 75, clean profile
 - Wiki.js version: 2.3.81
 - Database engine: PostgreSQL 11.7

**Comment by NGPixel** [comment]
Press ESC

**Comment by madduck** [comment]
Ah, `esc` is used by an extension here, that is why. Still might want to consider putting a note about this somewhere.
