### ISSUE TITLE
Debug logging does not seem to go anywhere

### ISSUE THREAD

**Issue by madduck** [Requarks/wiki#1844]
I've set
```
logLevel: debug
```
in `config.yml`, but there is nothing but `info` log entries in the `stderr` output. I also cannot find any files being created anywhere else.

**Host Info (please complete the following information):**
 - OS: Debian 10
 - Browser: Firefox 75
 - Wiki.js version: 2.3.81
 - Database engine: PostgreSQL 11.7

**Comment by Smankusors** [comment]
What exactly you looking for?

**Comment by madduck** [comment]
Leads and hints when debugging problems as I encounter them? Information to augment bug reports? If I wanted to stab at problems with a stick in a dark room, I'd run Microsoft or Apple. :)

**Comment by NGPixel** [comment]
You won't get much more logs by changing the level to debug. Info already reports most of what can be reported.

In Administration > Dev > Flags, you can enable SQL logging and LDAP debugging, but that's pretty much it.

**Comment by WestFarmer** [comment]
I think it's kind anti-pattern, if Info already reports most of what can be reported, the logging should be refactored.

You guys can't just closed issues like this.
