### ISSUE TITLE
Rights assigned to Guest group have no effect

### ISSUE THREAD

**Issue by madduck** [Requarks/wiki#1847]
I can assign modify and delete rights for pages to the Guest group, and also to the page rules, but guest users still cannot edit the site. Apparently this is by design, and the guest user is always read-only.

If that must be the case, then I think the permissions should not be editable.

However, it would be better if the guest user could be configured to have write rights, maybe with a warning, but there are going to be legitimate use cases for this.

**Host Info (please complete the following information):**
 - OS: Debian 10
 - Wiki.js version: 2.3.81
 - Database engine: PostgreSQL 11.7

**Comment by NGPixel** [comment]
Guests cannot modify content and there's no plan change this behavior for now.
