### ISSUE TITLE
Should Markdown Definition Lists work?

### ISSUE THREAD

**Issue by JetForMe** [Requarks/wiki#1848]
**Question**
I'd like to create a [Definition List](https://www.markdownguide.org/extended-syntax/#definition-lists), but it doesn't seem to render properly.

![Screen Shot 2020-05-06 at 17 26 21 ](https://user-images.githubusercontent.com/401600/81241296-ba471400-8fbe-11ea-98d2-a2efb79cb4a7.png)

**Host Info (please complete the following information):**
Hosted at Digital Ocean using the container they provide.

**Comment by NGPixel** [comment]
Definition Lists are not supported but you can create a feature request for it:
https://wiki.js.org/feedback/

**Comment by JetForMe** [comment]
Something's really broken in your feedback on Safari. Works okay in Chrome, but runs into issues on Safari.

**Comment by NGPixel** [comment]
Yes, being an iframe it will start to fail as more browsers are blocking cross-site requests.

It will be changed soon to a direct link to https://requarks.canny.io/wiki
