### ISSUE TITLE
cuestion wiki.js

### ISSUE THREAD

**Issue by ireneca** [Requarks/wiki#1849]
We are making a concept proof for a platform based in free software. And are very happy for having found your code. But we need to use APIs. Are you implementing any kind of APIs? If not, what way you recommend for integrating your wiki.js engine in our project? We have several tools to implement (wiki, wall, chat...)

**Comment by Smankusors** [comment]
cuestion?

Anyway, you can use GraphQL API exposed by Wiki.js. More on that [here](https://docs.requarks.io/dev/api).
