### ISSUE TITLE
Navigation: Option to open an external link in a blank page

### ISSUE THREAD

**Issue by kingfisher77** [Requarks/wiki#1850]
**Question**
By using the navigation panel we would like to use the option to open en external link in a blank window. It is marked as completed here: [https://requarks.canny.io/wiki/p/external-linkin](https://requarks.canny.io/wiki/p/external-linkin)

**Host Info (please complete the following information):**
Wiki.js version: 2.3.81

What do we miss?

**Comment by Smankusors** [comment]
Your link is broken.

Anyway it's for wiki content.

**Comment by kingfisher77** [comment]
Sorry, the correct link is: [https://requarks.canny.io/wiki/p/external-linking](https://requarks.canny.io/wiki/p/external-linking)

My question reflects on the Navigation-Menu. An option for opening the target in a blank window.

**Comment by Smankusors** [comment]
Yeah and this is better to create a new feature request instead.

**Comment by kingfisher77** [comment]
Okay :-) https://requarks.canny.io/wiki/p/opening-a-navigation-target-in-a-blank-window
