### ISSUE TITLE
SAML Login error

### ISSUE THREAD

**Issue by rfrizani** [Requarks/wiki#1851]
### Actual behavior

Folks
We have the following problem.

We configured SAML 2.0 apparently functional, but after login the following message appears:

**Oops, something went wrong...
Missing or invalid email address from profile.**

Our version of the Wiki is 2.3.81.

Thanks.

### Steps to reproduce the behavior

Login with SAML on the login page

**Comment by Smankusors** [comment]
Do you configured the email address correctly on the SAML? Wiki.js needs an email to be returned from SAML.

**Comment by rfrizani** [comment]
Thanks @Smankusors for your answer.

The only configuration field for this is urn: oasis: names: tc: SAML: 1.1: nameid-format: emailAddress and on the other side of SAML, the authentication user is email, I can do it through a Chrome extension (SAML message decode) that everything works, the only problem is that when logging on the wiki side, he does not find any email in the profile, nor when it is a new user who will self-register or when it is an existing user on the wiki with the email field created in the profile.


I don't even have an error in the log files, it doesn't tell me that the user doesn't exist and if I activate self-registration it doesn't register the user.

Thanks.

**Comment by Smankusors** [comment]
The **email field mapping**, how do you configure it? Is your SAML return email? Then you need to map to the correct key on the Wiki.js side.

**Comment by Naxest** [comment]
I have the same issue and I can see on SAMLResponse the email field (urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress).

This is a fragment of the SAMLResponse:
```
...
<saml2:Subject>
  <saml2:NameID Format="urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress">email@domain.com</saml2:NameID>
  <saml2:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
    <saml2:SubjectConfirmationData NotOnOrAfter="2020-11-23T16:34:02.005Z" Recipient="https://mywikijs.com/login/xxxxxxx-xxxxxx-xxxxxx-xxxxxxx-xxxxxxxxxx/callback"/>
  </saml2:SubjectConfirmation>
</saml2:Subject>
...
```
