### ISSUE TITLE
Prevent XSS attacks when opening target="_blank"

### ISSUE THREAD

**Issue by daneallen** [Requarks/wiki#1852]
When enabling the rendering module html-core "Open external links in a new tab" the external links will get the target="_blank" added to them automatically. Referencing the below link the additional rel attribute should be automatically added to prevent against XSS attacks. 

https://developers.google.com/web/tools/lighthouse/audits/noopener

**Comment by daneallen** [comment]
PR titled #1853: XSS attack fix attempts to address this issue.

**Comment by NGPixel** [comment]
PR merged.
