### ISSUE TITLE
Changing Favicon (Using Docker)

### ISSUE THREAD

**Issue by anhuntz** [Requarks/wiki#1854]
We are running Wiki.js through a docker container. How can the favicon be changed? _I don't want to risk changing it manually by going into the docker container files_, and I can't seem to find an option to change it within the site itself. Help!

Host Info:
OS: Ubuntu 18.04, Docker
Wiki.js version: Latest

**Comment by Smankusors** [comment]
Just bind mount the `/wiki/assets/favicon.ico` file and `/wiki/assets/favicons/` folder. You don't manually "change" the docker container files, but "override" them.

**Comment by jord8on** [comment]
> It's better make via docker-compose.yaml
> in your wiki image config remap folder from container to the host and put favico to this folder
> 
> ```
> volumes:
>       - /path/to/your/host/folder/favicons:/wiki/assets/favicons
> ```
> 
> Regards!

I'm also using Docker via DigitalOcean droplet and I'm not super familiar with how to get to a folder in the app, from Linux. 

I am able to login to my wiki.js instance via SSH [following these instructions](https://www.digitalocean.com/docs/droplets/how-to/connect-with-ssh/openssh/). I just don't know what to do next.

Can someone provide the commands I should enter to get to this /wiki/assets/favicons/ folder, and how to substitute the default favicon with our new one?

**Comment by nideKer** [comment]
> I'm also using Docker via DigitalOcean droplet and I'm not super familiar with how to get to a folder in the app, from Linux.

You need to know how your container is started - via `docker-compose` or `docker run` command - there is different commands to solve it.

**Comment by nethoncho** [comment]
@jord8on This works with the Digital Ocean droplet. Skip the line with `-e LETSENCRYPT_DOMAIN` if you are not using ssl. Note that this will NOT erase any of your content. The wiki docker us just the front end.

`docker stop wiki`
`docker rm wiki`
`docker create --name=wiki \`
`-e LETSENCRYPT_DOMAIN=YOUR_HOST_NAME -e LETSENCRYPT_EMAIL=YOUR_EMAIL_ADDRESS -e SSL_ACTIVE=1 \`
`-e DB_TYPE=postgres -e DB_HOST=db -e DB_PORT=5432 -e DB_PASS_FILE=/etc/wiki/.db-secret \`
`-v /etc/wiki/.db-secret:/etc/wiki/.db-secret:ro -e DB_USER=wiki -e DB_NAME=wiki -e UPGRADE_COMPANION=1 \`
`-v /etc/wiki/custom-assets/favicons:/wiki/assets/favicons \`
`-v /etc/wiki/custom-assets/favicon.ico:/wiki/assets/favicon.ico \`
`--restart=unless-stopped -h wiki --network=wikinet -p 80:3000 -p 443:3443 requarks/wiki:2`
`docker start wiki`
`docker logs wiki`
