### ISSUE TITLE
open id connect with fusion auth?

### ISSUE THREAD

**Issue by nktech1135** [Requarks/wiki#1855]
**Question**
I have a fusion auth server and am trying to use the generic openid connect auth provider on wiki.js to connect to it. However, i'm not very familiar with how this is supposed to work, so was wondering, Could someone tell me what value goes into issuerer, email claim, and user claim?

Thanks.

**Host Info (please complete the following information):**
OS: ubuntu 20.04

**Comment by NGPixel** [comment]
Which version of Wiki.js are you using?

**Comment by nktech1135** [comment]
I'm using wikijs version 2.3.77.

However, since then my issue has changed a bit. I'm now trying to use gluu instead of fusionauth. I have it working with our discourse forum but when trying with wiki.js i get the following error after login.

Oops, something went wrong...
failed to obtain access token

Where are logs that would tell me more?

Thanks.

**Comment by NGPixel** [comment]
openidconnect module is incomplete and not supported. It's coming in update 2.5.
