### ISSUE TITLE
plantuml not rendering anymore

### ISSUE THREAD

**Issue by kbfifi** [Requarks/wiki#1857]
**Describe the bug**
Suddenly a page I created with plantuml diagram gives an error message and the drawing is no longer rendered

**To Reproduce**
Open a page with plantuml (that used to work)

**Expected behavior**
Page loading normally with rendered plantuml diagram

**Screenshots**
![image](https://user-images.githubusercontent.com/35601089/81434073-db963480-9165-11ea-8d1f-315a14e3eed1.png)

**Host Info (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04, Docker-compose]
 - Wiki.js version: [e.g. 2.3-arm tag] Note that the problem was also there in arm-2.2
 - Database engine: [e.g. postgres 9.7, mysql 5.7]

**Comment by NGPixel** [comment]
Fixed by 6a4b25bc28b748cc6a9cf13f186e8616cace32d2
