### ISSUE TITLE
Where are detailed server logs?  Getting "The mail configuration is incomplete or invalid." and can't figure out how to debug

### ISSUE THREAD

**Issue by SimonKaluza** [Requarks/wiki#1859]
**Question**
Would like to investigate the Wiki.js server logs to debug why my SMTP configuration isn't working using the default Ubuntu 18.04 docker installation instructions.  

Is there an environment variable or value I can set to specify to output logs in the Docker container?

After examining the Dockerfile it seems that a /log directory should be created at the Docker volume root, but after running Bash alongside the server process it seems the root directory only contains:

```
ubuntu@ip-10-1-1-136:~$ docker container exec -it wiki bash
bash-5.0$ ls
LICENSE       assets        config.yml    data          node_modules  package.json  server
bash-5.0$
```

OS: Ubuntu 18.04, Docker
Wiki.js version: 2.3.81
Database engine: Postgres 11

**Comment by NGPixel** [comment]
```
docker logs wiki
```

**Comment by Smankusors** [comment]
that is not the root directory. This docker image starts with current directory of `/wiki`
