### ISSUE TITLE
Would like a "parcel" branch to work on migrating to Parcel from Webpack

### ISSUE THREAD

**Issue by unquietwiki** [Requarks/wiki#1861]
I haven't been happy with using Webpack on other JS-based projects, and worry that it tries to do too much in making it hard to debug CSS & runtime issues. I've mostly figured out how to switch it to Parcel; there are still some CSS-related quirks remaining, which I'm not sure are related to other changes, or from abandoning the use of Webpack.

- https://github.com/unquietwiki/wiki/tree/parcel -> branch I want to bring over
- https://parceljs.org/ -> ParcelJS website

**Comment by unquietwiki** [comment]
Being more specific, there's a "darken" function being called in the current code, that doesn't seem to be currently enabled in the software. I know from my searches that it's a function in the "utils" for Vuetify.

**Comment by NGPixel** [comment]
Is webpack harder to configure? Yes, definitely. Does it have any major issue that Parcel would solve? Not really.

The majority of frameworks used in the project have native support for webpack (Vue, Vuetify, etc.). Also this project makes heavy use of dynamic code splitting and with upcoming theme bundles, it's gonna be even more important. Webpack is light years ahead on that front compared to Parcel.

If you need total flexibility and best compatibility, webpack is still the industry-standard. I'm not going to switch the whole project over to a different bundler based just on your personal preference of parcel over webpack. Unless it brings actual major improvements, the project will keep using webpack.

**Comment by unquietwiki** [comment]
Hey there. I agree with you on the majority of what you said. My concern in
this matter is determining if the backlog of open issues are related to the
fine tuning needed for webpack to operate correctly. I have my own website
using WikiJS, and it's got a quirk or two with layout I didn't expect.
Another friend of mine, I did a similar setup for, and now he wants to go
to Drupal because of CSS & other issues.

I'm not making this suggestion lightly; I'm speaking as someone that's lost
probably 20-40 hours on Webpack-induced headaches. This change itself took
5-10 hours to figure out.
