### ISSUE TITLE
How can i restore old pages from v2.1.113 database ?

### ISSUE THREAD

**Issue by MohamedAmrMahdy** [Requarks/wiki#1863]
**Question**
How can i restore old pages from v2.1.113 database ?
i've updated my wiki.js as listed on https://docs.requarks.io/install/upgrade but there was an error after i runned node server so i've made a clean install but cant restore my old pages

so where does the pages text stored ?

**Host Info (please complete the following information):**
OS: [e.g. Ubuntu 18.04, Docker] Windows
Wiki.js version: [e.g. 2.0.1] 2.1.113
Database engine: [e.g. postgres 9.7, mysql 5.7] mysql

**Comment by Smankusors** [comment]
what is the error? can you show us?
