### ISSUE TITLE
Installation on planethoster mutualize webhoster (old version of postgres)

### ISSUE THREAD

**Issue by Benjer** [Requarks/wiki#1864]
**Question**
Hello.

I am looking to install wiki.js on my PlanetHoster shared server.
When I launch the application I have database errors during migration (A priori due to an incompatibility of version of the database): "Secified Key is too long in Index ...."

![error_nodejs_ph](https://user-images.githubusercontent.com/13748948/81504744-4cb32480-92eb-11ea-81c9-46635d0a659e.jpg)

Do you have an idea to avoid this incompatibility?
Otherwise what version of wiki.js would be compatible with the version of postgres imposed by my host (9.2.24)?

Thanks you!

**Host Info (please complete the following information):**
OS: Red Hat 4.8.5-36 (PlanetHoster Webhoster)
Wiki.js version: 2.3.81 And 2.1.113
Database engine: Postgres 9.2.24

**Comment by Benjer** [comment]
Or maybe a compatibility with pcloud drive storage?

**Comment by Smankusors** [comment]
Please read the [requirements](https://docs.requarks.io/install/requirements).

Anyway, if you are using PostgreSQL, why are you using mysql driver?

**Comment by Benjer** [comment]
Because i make a test with a mysql database, no results.
In the requirements i see the postgres version needed but i can't use this version because i'm in a provider mutualized

**Comment by NGPixel** [comment]
Closing this ticket as you're using an unsupported version of Postgres. Read the requirements.

The error posted in the screenshot is because you're trying to install on a non-empty database.
