### ISSUE TITLE
Shared webhosting: wiki.js?

### ISSUE THREAD

**Issue by raked3** [Requarks/wiki#1866]
**Question**
I want to install wiki.js on a shared webhosting with plesk onyx and node.js support. I need to have an app.js file to start node but in the guthup repo isnt any. Can you help me?

**Host Info (please complete the following information):**
OS: Shared webhosting - netcup 4000
Wiki.js version:  2.0.1
Database engine:

**Comment by NGPixel** [comment]
The entry file would be `server/index.js`, but the working directory still needs to be the project root, not `server`.
