### ISSUE TITLE
Browser connection timeout

### ISSUE THREAD

**Issue by remissao** [Requarks/wiki#1867]
I installed Wiki.js on Ubuntu 20.04 LTS using this guide: https://docs.requarks.io/install/ubuntu

After I enter the server IP I get an ERR_CONNECTION_RESET on my browser.

The SSH and my Rocket.Chat server still work on the same server.

Do I need to edit the config.yml file and add the server IP address to it?

If so, where is the file located?

**Comment by Smankusors** [comment]
are you sure your Wiki.js running? How many minutes are you waiting? Can you check `docker ps` output?

**Comment by remissao** [comment]
I tried running start commands again:
`docker start db
docker start wiki
docker start wiki-update-companion`

Afterwards I got this output from `docker ps`:

![image](https://user-images.githubusercontent.com/4529190/81572165-2a7cdd80-93a3-11ea-9487-6c61cbe968d3.png)

The browser still can't reach it. I get a response almost immediately.

**Comment by Smankusors** [comment]
the `db` container is restarting... why is that? Can you show us the output of `docker logs db`?

btw, I think this is your first time using docker, yes?

**Comment by remissao** [comment]
@Smankusors 
That's right, I've never used docker before.

I don't get any output from `docker logs db`

If I do `docker logs wiki` I get:
```
Loading configuration from /wiki/config.yml... OK
DB_PASS_FILE is defined. Will use secret from file.
>>> Failed to read Docker Secret File using path defined in DB_PASS_FILE env variable!
EISDIR: illegal operation on a directory, read
```

**Comment by NGPixel** [comment]
Make sure the file `/etc/wiki/.db-secret` exists, has a random key inside and is readable by the docker process.

**Comment by remissao** [comment]
@NGPixel 

This file does not exist. Shouldn't it have already been created when simply copying and pasting the commands from this guide? https://docs.requarks.io/install/ubuntu

I looked into the `docker secret create` but I'm running into more issues.

Is there a step by step guide on how to install Wiki.js on Ubuntu Server 20.04 LTS?

**Comment by Smankusors** [comment]
> @NGPixel
> 
> This file does not exist. Shouldn't it have already been created when simply copying and pasting the commands from this guide? https://docs.requarks.io/install/ubuntu
> 
> I looked into the `docker secret create` but I'm running into more issues.
> 
> Is there a step by step guide on how to install Wiki.js on Ubuntu Server 20.04 LTS?

welp I see how this goes. Are you just copy paste without reading any output? There could be permission denied that you missed when you copy pasting.

**Comment by remissao** [comment]
@Smankusors 
I did read the output from the installation. No errors. However after the installation is complete etc/wiki/ is empty.

I've tried deleting the containers and the database and redoing the installation. Same result.

I noticed that the guide I followed was created fro Ubuntu 18.04 LTS and I'm using 20.04 LTS.

Not sure this is worth the trouble, though. Maybe will just try Digital Ocean or use DocuWiki instead.

**Comment by Smankusors** [comment]
how about this command output?

```
openssl rand -base64 32 > /etc/wiki/.db-secret
```

**Comment by remissao** [comment]
nothing

**Comment by Smankusors** [comment]
and is the `/etc/wiki/` folder still blank or you have a file named `.db-secret`?

**Comment by remissao** [comment]
thank you for your support, but I decided I won't go further with wiki js
