### ISSUE TITLE
Wiki.js instance on Heroku loses data

### ISSUE THREAD

**Issue by bennyn** [Requarks/wiki#187]
I was able to setup a Wiki.js installation on Heroku (thanks to https://github.com/Requarks/wiki/issues/181#issuecomment-318237477). 

Wiki.js greeted me with a "Create Home Page" button which I clicked to create an entry point to my site. After I created the home page (and some other wiki pages), I checked my "Config Variables" on Heroku to edit the "WIKI_TITLE" environment variable. When I saved the "WIKI_TITLE", my Heroku instance got restarted and I lost all my data. I was able to login with my admin account but all wiki entries were gone. 😢 

I also realized that there was nothing uploaded to the Git repository which I specified during the [Heroku installation](https://heroku.com/deploy?template=https://github.com/requarks/wiki-heroku).

How can I help you debugging this issue? Because I really would like to us Wiki.js with my teammates.

**Comment by NGPixel** [comment]
Wiki.js syncs the git repository every 5 mins + on terminate event. So unless you made everything under 5 mins, your content should have been synced with your remote git repository at least once + during the terminate event as a fail-safe.

I suggest you make sure your Git settings are correct. Check the logs for any git connection errors that would have prevented the sync to occur.

**Comment by bennyn** [comment]
When I found the error, more than 5 minutes had passed. 

What worries me more than the GitHub backup is that I'm losing my data when setting a new environment variable (like `WIKI_TITLE`). You can see the issue in my YouTube video: https://youtu.be/6yYHD6WYA1Q


Aren't the articles stored in a Mongo database? Might it a problem that I run the wiki on a Heroku free tier (with a free MongoDB from mLab)?

**Comment by NGPixel** [comment]
No content is stored in the DB.

Heroku apps are stateless, which means that changing any env variable will result in Heroku launching a completely new instance. Which is why making sure your remote git backup is working correctly. If you can't see changes replicated to your remote git after 5 mins or after your instance is terminated, then your git settings are wrong.

If they are correct and you can see the changes replicated to your remote git, you may still see the Welcome page when the new Heroku instance is started. Simply wait a bit and reload the page, you should see the homepage you created earlier. The git sync occurs in the background so the content may not yet be available and indexed by the time you load the page the first time.

**Comment by bennyn** [comment]
@NGPixel, thanks for the update.

Maybe you can help me verifying my Git stettings (because I don't see any commit coming from Wiki.js):
- WIKI_GIT_BRANCH: `master`
- WIKI_GIT_PASSWORD: Well 😄 
- WIKI_GIT_URL: `https://github.com/bennyn/dci-wiki`
- WIKI_GIT_USERNAME: `welovecoding-ci-travis` ([this account](https://github.com/welovecoding-ci-travis) is a collaborator at [dci-wiki](https://github.com/bennyn/dci-wiki) with push access to the repository)

So it looks good to me but I don't see any Git activity . 😢

**Comment by NGPixel** [comment]
Look at the logs. In your Heroku app dashboard, click the <kbd>More</kbd> button at the top right of the page and click **View logs**. Then click <kbd>More</kbd> > **Restart all dynos**. Any error will appear in the logs as it restarts.

**Comment by bennyn** [comment]
Ah, I see. Looks like it doesn't work with completly empty Git repositories because it reports:

> 2017-08-01T21:42:57.234534+00:00 app[web.1]: 2017-08-01T21:42:57.234Z - error: [AGENT] Unable to fetch from git origin!
2017-08-01T21:42:57.234712+00:00 app[web.1]: 2017-08-01T21:42:57.234Z - error: [AGENT] Unable to push changes to remote Git repository!
2017-08-01T21:42:57.238266+00:00 app[web.1]: 2017-08-01T21:42:57.235Z - error: [AGENT] One or more jobs have failed:
2017-08-01T21:42:57.238268+00:00 app[web.1]: { code: 1,
2017-08-01T21:42:57.238268+00:00 app[web.1]:   message: '`git --git-dir=repo/.git --work-tree=repo pull origin master` failed with code 1',
2017-08-01T21:42:57.238269+00:00 app[web.1]:   stderr: 'fatal: Couldn\'t find remote ref master\n',
2017-08-01T21:42:57.238269+00:00 app[web.1]:   stdout: '' }

So I should at least create a `README.md` and push it to `master`?

```bash
echo "# Hello World" >> README.md
git init
git add README.md
git commit -m "first commit"
git remote add origin git@github.com:bennyn/dci-wiki.git
git push -u origin master
```

**Comment by NGPixel** [comment]
The remote git repo must be initialized. So yes you should create at least the README.md.

**Comment by bennyn** [comment]
**Ok, now it works!** Thanks for being so patient with me. 🙂 When I now change environment variables on Heroku, the wiki saves its entries via a Git push before it gets restarted. That's nice.

But it was still a strange first time user experience. I created a wiki and lost my data when changing the name of it. It would be great if Wiki.js would handle this use case and init the repo instead of failing because there is no master branch.

Another improvement would be to give an administrator the control (from the Wiki.js UI) to trigger a Git push (in addition the 5 minutes interval).

**Comment by davedub** [comment]
I'm still confused by the issue flagged here. I don't understand the workflow between the remote Git repository and the Heroku app. If the "Local Repostory Path" is ./repo on the Heroku app, and (as the setup process notes) "All content is then regularly kept in sync with a remote git repository," then specifying the Github repo and the password to access that repo in the config vars should mean that anything I edit on the local repo will be backed up to the Github repo. Is that what "kept in sync" means? But I don't see that happening. I also get content flushed and don't see any way to restore it when a Heroku dyno restarts. What documentation should I be looking at to understand this better?
