### ISSUE TITLE
migrate confluence to wiki.js

### ISSUE THREAD

**Issue by agnelbruce** [Requarks/wiki#1875]
**Question**
i want to migrate from confluence to wiki.js.i am a new to this project,kindly suggest me to achieve this.

**Host Info (please complete the following information):**
OS: ubunt server
Wiki.js version: [e.g. 2.3.81]
Database engine: MS SQL

**Comment by baer95** [comment]
the first problem you are going to have is the fact that confluence is not markdown based, but wikijs is. There is no "exact" conversion between these two formats, so there is no way around at least some manual work to correct conversion errors.
I suggest looking for confluence to markdown converters, the Atlassian marketplace might be a good starting point for this (https://marketplace.atlassian.com/apps/1221351/markdown-exporter-for-confluence?hosting=cloud&tab=overview).

Some more things i found with a quick google search:
 * https://community.atlassian.com/t5/Confluence-questions/export-to-markdown/qaq-p/307481
 * https://community.atlassian.com/t5/Confluence-questions/Does-anyone-know-of-a-way-to-export-from-confluence-to-MarkDown/qaq-p/921126
 * https://github.com/EWhite613/Confluence-to-Github-Markdown
 * https://github.com/meridius/confluence-to-markdown

Hope this helps!

**Comment by agnelbruce** [comment]
Thank you so much for your information
