### ISSUE TITLE
PostgreSQL connect via unix socket

### ISSUE THREAD

**Issue by zenlord** [Requarks/wiki#1876]
### Actual behavior
Wiki.js is unable to connect to my postgres database/table with this configuration:

    db:
      host: "socket:/run/postgresql?db=wiki"

(my postgresql instance is set up to allow connections via unix sockets - and I'm using that connection type for other apps)

### Expected behavior
I would expect wiki.js to connect to the database socket. 

Although I cannot seem to find any information on the capability of wiki.js to connect to a database using its unix socket, I did find out that node.js has that capability and supports the above format, which either means that his feature is not implemented in wiki.js, or that it is implemented but requires specific configuration, or that it is implemented but contains a bug.

**Comment by Smankusors** [comment]
How do you run Wiki.js?

**Comment by zenlord** [comment]
I have installed wiki.js manually on a Debian Buster server. The packages nodejs (v 2.19) and postgresql (v11) are all installed from the buster repo's. I have other applications running on the same machine, although none of those are based on node.js. 

The relevant bit from my config.yml:

    db:
      type: postgres
      host: socket:/run/postgresql?db=wiki

I have used the systemd service example from the wiki.js docs.

The error I'm seeing is:

    node[5419]: [MASTER] info: Using database driver pg for postgres [ OK ]
    node[5419]: [MASTER] info: Connecting to database...
    node[5419]: [MASTER] error: Database Connection Error: ENOTFOUND undefined:5432

Thx!

**Comment by zenlord** [comment]
My apologies - apparently pg had crashed due to a typo in my pg_hba.conf. Once corrected, I was able to connect via the unix socket using these configuration settings:

    db:
      type: postgres
      host: '/run/postgresql'
      user: postgres
      db: wiki

Closing.
