### ISSUE TITLE
My friend can't edit pages.

### ISSUE THREAD

**Issue by TH3-UNKNOWN** [Requarks/wiki#1877]
**My friend can't edit pages.**
When my friend has permissions
![image](https://user-images.githubusercontent.com/48633565/81822850-9c6b3900-9501-11ea-8247-10b5c593aafc.png)
He is my co-owner and we're colab and idk how to use it
![image](https://user-images.githubusercontent.com/48633565/81822900-aa20be80-9501-11ea-9921-f6cffc6dfc3d.png)
Website: http://unknown-information.glitch.me/
**Host Info (please complete the following information):**
OS: [e.g. Ubuntu 18.04, Docker]
Wiki.js version: [e.g. 2.0.1]
Database engine: [e.g. postgres 9.7, mysql 5.7]

**Comment by Smankusors** [comment]
Are you already give the permission on page rules?

**Comment by TH3-UNKNOWN** [comment]
How do i do this?

**Comment by Smankusors** [comment]
> How do i do this?

it is second tab from your screenshot

**Comment by TH3-UNKNOWN** [comment]
wait, ima try

**Comment by TH3-UNKNOWN** [comment]
its just that its not loading :|

**Comment by TH3-UNKNOWN** [comment]
![image](https://user-images.githubusercontent.com/48633565/81827757-1520c400-9507-11ea-9688-4b6472c23b7d.png)
keeps on loading

**Comment by TH3-UNKNOWN** [comment]
I fixed it!
