### ISSUE TITLE
Migration 2.4.13 failed on mysql 8.0.16

### ISSUE THREAD

**Issue by kellycampbell** [Requarks/wiki#1878]
**Error:**
```
migration file "2.4.13.js" failed
migration failed with error: alter table `pages` add `extra` json not null default '{}' - BLOB, TEXT, GEOMETRY or JSON column 'extra' can't have a default value
```

**Host Info (please complete the following information):**
 - OS: Docker, Kubernetes
 - Wiki.js version: build from master 5/13/2020
 - Database engine: mysql 8.0.16 on AWS RDS

**Additional info:**

Couldn't easily rollback to previous version we had deployed so we had an outage until I was able to work around this. This was the error:

```
2020-05-13T15:11:01.483Z [MASTER] info: Database Connection Successful [ OK ]
2020-05-13T15:11:01.507Z [MASTER] error: Database Initialization Error: The migration directory is corrupt, the following files are missing: 2.3.10.js, 2.3.23.js
```

**Comment by NGPixel** [comment]
> Couldn't easily rollback to previous version we had deployed so we had an outage until I was able to work around this.

Which is why you're not supposed to use dev builds in production? And to have a DB backup before  upgrading?

**Comment by NGPixel** [comment]
Fixed in latest beta.
