### ISSUE TITLE
How do i move the files

### ISSUE THREAD

**Issue by TH3-UNKNOWN** [Requarks/wiki#1879]
**How do i move the files*

![image](https://user-images.githubusercontent.com/48633565/81834994-b57ae680-950f-11ea-8721-e8cc7517533f.png)
I whant to move the files, since its not in order
**Host Info (please complete the following information):**
OS: [e.g. Ubuntu 18.04, Docker]
Wiki.js version: [e.g. 2.0.1]
Database engine: [e.g. postgres 9.7, mysql 5.7]

**Comment by TH3-UNKNOWN** [comment]
Anybody?

**Comment by NGPixel** [comment]
The tree view is ordered alphabetically. If you want to control the order, you need to use the static menu option in Admin > Navigation.
