### ISSUE TITLE
Migrate from MariaDB to PostgreSQL

### ISSUE THREAD

**Issue by aqustiq** [Requarks/wiki#1881]
**Question**
I want to migrate my WikiJS DB from MariaDB 10.4 to PostgreSQL 10.
What is your advise for best practice? Thx

**Host Info (please complete the following information):**
OS: Debain 10
Wiki.js version: 2.3.81
Database engine: MariaDB 10.4.12

**Comment by winkelement** [comment]
Never tested it myself but maybe worth to have a look: https://github.com/dimitri/pgloader

**Comment by NGPixel** [comment]
I would suggest exporting all your content (either via the Local Disk or Git storage module), install a new instance with Postgres, then import back the content.

Using tools to convert schemas and data from mariadb to postgres might work, but you risk introducing an incompatible schema that could break down the line with future updates.
