### ISSUE TITLE
Help in setting up wiki.js using docker image on PCF(Pivotal Cloud Foundry)

### ISSUE THREAD

**Issue by deepaklearner** [Requarks/wiki#1885]
**Question**
Help in setting up wiki.js using docker image on PCF(Pivotal Cloud Foundry)
 db: mysql cleardb

I have created a service key for the database service in PCF. But not able to create the container using the docker image and service key configuration.

**Comment by Smankusors** [comment]
Hmm... What do you mean by "not able to create the container"? Is there any error? Or are you confused how to setup Wiki.js?

**Comment by deepaklearner** [comment]
I am trying to use requarks/wiki official image and configure with PCF database mysql database.
I got confused with setting the Environment Variables mentioned at https://docs.requarks.io/install/docker link. I am trying to deploy on https://run.pivotal.io/ (PCF).

**Comment by Smankusors** [comment]
> 1. Error in public PCF:  [MASTER] error: Database Initialization Error: create table `analytics` (`key` varchar(255) not null, `isEnabled` boolean not null default '0', `config` json not null) default character set utf8mb4 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'json not null) default character set utf8mb4' at line 1

hmm what version MySQL do you use? It's recommended to use MySQL 8.x for Wiki.js

**Comment by deepaklearner** [comment]
In PCF, they are providing not mysql. Its actually Cleardb, which I dont see in the website of wiki.js in supported list. I think this may be reason. Please can you double check.

**Comment by Smankusors** [comment]
> Cleardb

Cleardb is not the database engine. With Cleardb you can choose from MySQL, PostgreSQL, Oracle, or MSSQL.

**Comment by deepaklearner** [comment]
Yes I chose MySQL in Cleardb. But I got error: "Error in public PCF: [MASTER] error: Database Initialization Error: create table analytics (key varchar(255) not null, isEnabled boolean not null default '0', config json not null) default character set utf8mb4 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'json not null) default character set utf8mb4' at line 1"   What should I check now?

**Comment by NGPixel** [comment]
The version of MySQL is most likely too old.

Do yourself a favor and stop using ClearDB. They are extremely overpriced and using outdated tech.
