### ISSUE TITLE
Embedding page to page

### ISSUE THREAD

**Issue by qonstantin** [Requarks/wiki#1893]
Hello!

Could you please help to understand if it is possible to embed page to page. Looked everywhere but could not find an answer.
I am not talking about links but to implement one page to be the part of another page with proper indicating of headers in content when implemented.

If not possible that would be a great feature if implemented.

Thank you!

**Comment by NGPixel** [comment]
This is not possible at the moment.

Follow this thread to be notified when it is:
https://requarks.canny.io/wiki/p/templates
