### ISSUE TITLE
Crash on /a/auth page

### ISSUE THREAD

**Issue by Piotrovskyi** [Requarks/wiki#1894]
**Describe the bug**
When I am open /a/auth page getting exception
![image](https://user-images.githubusercontent.com/11422892/82067665-b52e4700-96d9-11ea-8318-1ad0fc576167.png)

**To Reproduce**
1. Go to 'Administration.'
2. Click on 'Authorization'
4. See error in console and page is not responsible

**Expected behavior**
Page is working

**Screenshots**
![image](https://user-images.githubusercontent.com/11422892/82067844-eb6bc680-96d9-11ea-9551-3ef963f7621f.png)

**Host Info (please complete the following information):**
 - OS: [Macos Mojave client, server running latest docker ]
 - Wiki.js 2.3.81
 - Database engine: PostgreSQL 11

**Additional context**
My organization has custom logo on GSuite
This page was working fine for some time
then I found this crash, In addition i can't login with google mail
![image](https://user-images.githubusercontent.com/11422892/82068432-a5633280-96da-11ea-8025-b9cab78cfebb.png)

**Comment by Smankusors** [comment]
The reproduce steps seems to have something missing. You mention custom logo on GSuite right? Can you complete the reproduce steps?

**Comment by Piotrovskyi** [comment]
Somehow without any changes, it become works today. Feel free to close
