### ISSUE TITLE
Blocknote logos?

### ISSUE THREAD

**Issue by TH3-UNKNOWN** [Requarks/wiki#1896]
**Blocknote logos?**
On the docs, they have that danger sign
![image](https://user-images.githubusercontent.com/48633565/82101497-a4320580-96da-11ea-8c22-ff53cb363a69.png)
On mine, it has none, btw the book is from :book: 
![image](https://user-images.githubusercontent.com/48633565/82101518-b1e78b00-96da-11ea-99a4-bc0684d07553.png)

**Host Info (please complete the following information):**
OS: [e.g. Ubuntu 18.04, Docker]
Wiki.js version: [e.g. 2.0.1]
Database engine: [e.g. postgres 9.7, mysql 5.7]

**Comment by NGPixel** [comment]
This is coming in 2.4.

**Comment by TH3-UNKNOWN** [comment]
Okay! Thanks!
