### ISSUE TITLE
Please add Bengali language. I am looking to help. 

### ISSUE THREAD

**Issue by faisalakandha** [Requarks/wiki#1898]
Hello I was looking for the Bengali language in Wiki.js but couldn't find. I also visited the translator tool Lokalise but couldn't find Bengali. How this language can be added in Lokalise ? It's very important because Bengali is the 7th language of the world by total number of speakers. It is a very important language for a software like Wiki.js. If you give me the opportunity, I would be honored to work on this language for Wiki.js UI. Thanks in Advanced.

**Comment by NGPixel** [comment]
Added

**Comment by faisalakandha** [comment]
Thanks a lot mate. I've already started working on it :)
