### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by freis** [Requarks/wiki#19]
Have you planned down the row to have an auto navigation being created when pages are added or deleted under the Navigation menu?

**Comment by NGPixel** [comment]
The issue with having a navigation created is that you would have quite a long list of entries in that sidebar. Imagine having 50-100 entries at the root. So I'm not convinced this would be a good idea. I prefer leaving to the users the task of creating their own navigation. They can arrange it like they want and omit pages if needed.

What I could do however, is add an option to display a link (e.g. All Pages) in the navigation menu, which links to a special page where all articles are listed in a tree.

**Comment by freis** [comment]
what you're saying is that there is a way to get a menu into navigation? Did I miss something in the docs? 
And if there is a way is like a collapsible menu?

The All Pages idea is a great idea also.

**Comment by NGPixel** [comment]
No, the sidebar contains the Home, Parent Page and Account links. There's also the Page Contents which lists the headers of the current page for quick access. The sidebar is already busy enough so adding a list of pages as well would be too much.

What I mean by creating your own navigation is using the homepage (or another page) to create a list of links which points to all your articles. For example: https://docs.wiki.requarks.io/

So in addition to the 3 links I listed above, I'll add the option to display an "All Pages" link.

Nick

**Comment by freis** [comment]
Yup that was what I was going for also to mitigate it. Nice thanks
