### ISSUE TITLE
Moving from 1.0 to 2.0

### ISSUE THREAD

**Issue by rylancole** [Requarks/wiki#1907]
**Question**
I have spent the last couple days trying to get my Wiki.js up and running and now after following many different tutorials and trying various solutions, I was successful. However, I somehow ended up with Wiki.js 1.0 and not 2.0 like I wanted. Is there any easy path from 1.0 to 2.0 or do I have to start over and install 2.0?

**Host Info (please complete the following information):**
OS: Ubuntu 16.04.6 LTS Xenial
Wiki.js version: 1.0.117
Database engine: mongoDB 2.6.10, postgreSQL 9.5.21 (but I don't pSQL ever got hooked up)

Note that ```npm upgrade``` gives me the following error:

npm ERR! code EEXIST
npm ERR! path /var/www/wikijs/node_modules/.bin/raven
npm ERR! Refusing to delete /var/www/wikijs/node_modules/.bin/raven: is outside /var/www/wikijs/node_modules/raven and not a link
npm ERR! File exists: /var/www/wikijs/node_modules/.bin/raven
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.

**Comment by NGPixel** [comment]
https://docs.requarks.io/install/migrate
