### ISSUE TITLE
task list with bold don't work

### ISSUE THREAD

**Issue by tsohst** [Requarks/wiki#1908]
Using wikijs 2.3.81
### Actual behavior
`- [x] **test**: 1234` in markdown site creates the following string -> **test** `**test**: 1234`

### Expected behavior
- [x] **test**: 1234

### Steps to reproduce the behavior
Create `- [x] **test**: 1234` in markdown site and create `**test**: 1234`
It's a problem when using together with task list.

**Comment by bmann** [comment]
Any sort of formatting -- including markdown links `[links](/path/to/page)` or bare links `https://example.com` don't work with task lists.

**Comment by bmann** [comment]
Duplicate of https://github.com/Requarks/wiki/issues/1856, https://github.com/Requarks/wiki/issues/1860
