### ISSUE TITLE
Search H1 tags

### ISSUE THREAD

**Issue by integritek** [Requarks/wiki#1909]
**Question**
Describe in details what you are trying to achieve and where do you need guidance.
- We want the search all H1 tags in the wiki. Is this possible?

**Host Info (please complete the following information):**
OS: Ubuntu 18.04
Server: DO
Wiki.js version: Newest
Database engine: [e.g. postgres 9.7,]

**Comment by NGPixel** [comment]
You need to switch your search engine from "DB - Basic" to "DB - Postgres".

**Comment by integritek** [comment]
I can confirm that we did do that. Would you like our dns?

**Comment by NGPixel** [comment]
So what is the problem exactly? I searched for "welcome" and it found the homepage just fine...

**Comment by integritek** [comment]
Ok, I talked to the co-worker that is asking about it, he's asking how can it scroll down to the h1 tag that was searched. Should it do that already?

Also, if you escape search while it's searching, your :loading prop is still set to true on the v-text-field.

**Comment by NGPixel** [comment]
1) Search doesn't go to a specific location in a page. Submit a feature request for that here: https://requarks.canny.io/wiki

2) Yes, this is a known bug, already tracked in another ticket.
