### ISSUE TITLE
HTTPS doesn't work

### ISSUE THREAD

**Issue by inprimex** [Requarks/wiki#1911]
**Question**
Http works well but https not. Plz help localize the problem. Looks like wiki did not open port 3443 for HTTPS connection...

Docker run command:
docker run -d -p 80:3000 -p 443:3443 -e "SSL_ACTIVE=1" -e "LETSENCRYPT_DOMAIN=wiki.site.come" -e "LETSENCRYPT_EMAIL=info@site.come" --name wiki --restart unless-stopped -e "DB_TYPE=postgres" -e "DB_HOST=172.17.0.1" -e "DB_PORT=5432" -e "DB_USER=wikijs" -e "DB_PASS=pass" -e "DB_NAME=wiki" requarks/wiki:2

Host Ubuntu has letsencrypt certificate after the command:
certbot certonly --standalone -d wiki.site.com
List of files /etc/letsencrypt/live/wiki.site.com:
cert.pem  chain.pem  fullchain.pem  privkey.pem  README

Firewall settings (UFW):
Apache Full                ALLOW       Anywhere
OpenSSH                    ALLOW       Anywhere
5432                       ALLOW       172.17.0.0/24
Apache Full (v6)           ALLOW       Anywhere (v6)
OpenSSH (v6)               ALLOW       Anywhere (v6)

Docker network interface nmap -v 172.17.0.1
PORT     STATE    SERVICE
22/tcp   open     ssh
80/tcp   filtered http
443/tcp  filtered https
5432/tcp open     postgresql
8081/tcp open     blackice-icecap

Docker container nmap -v 172.17.0.1
PORT     STATE SERVICE
3000/tcp open  ppp

In docker log I see only 3000 port opening but not 3442 (https):
{"log":"2020-05-19T08:41:35.415Z [MASTER] \u001b[32minfo\u001b[39m: 
HTTP Server on port: [ 3000 ]\n","stream":"stdout","time":"2020-05-19T08:41:35.416241165Z
"}
{"log":"2020-05-19T08:41:35.470Z [MASTER] \u001b[32minfo\u001b[39m: 
HTTP Server: [ RUNNING ]\n","stream":"stdout","time":"2020-05-19T08:41:35.471228402Z"}
{

**Host Info (please complete the following information):**
OS: Ubuntu 20.04, Docker
Wiki.js version: 2.3.81
Database engine: postgres 10

**Comment by Smankusors** [comment]
FYI, you don't need to generate letsencrypt certificate on Ubuntu host, as Wiki.js will try to generate it own.

Have you waited long enough?

**Comment by inprimex** [comment]
Thank you @Smankusors ...noted regarding host letsencrypt.

docker container ls -a

more than 23 hours waiting...

looks like potentially not a docker issue port mapping ok:
0.0.0.0:80->3000/tcp, 0.0.0.0:443->3443/tcp

**Comment by NGPixel** [comment]
Please post the logs (`docker logs wiki`), we can't help you if we don't know what the process does.

**Comment by inprimex** [comment]
Hi Nicolas

Please find the full log attached.

[de723e5d8db4fbf7bad2c95a77ecf25fe97f82e5973621ab53acaf91916bafe7-json.log](https://github.com/Requarks/wiki/files/4659050/de723e5d8db4fbf7bad2c95a77ecf25fe97f82e5973621ab53acaf91916bafe7-json.log)

**Comment by inprimex** [comment]
Hello Nicolas
Could you suggest what we should fix on our side?

**Comment by Smankusors** [comment]
Can you try to bind HTTPS port on 3443? So the command will be `-p 3443:3443`?

**Comment by inprimex** [comment]
[d56f2a70af4c56828c67e3d3c4526ee5e838c2441ab70ff231072efd9ee5aed6-json.log](https://github.com/Requarks/wiki/files/4673526/d56f2a70af4c56828c67e3d3c4526ee5e838c2441ab70ff231072efd9ee5aed6-json.log)

Hi Antony

it works! ) Log attached.

How to bind a classic 443 port?

**Comment by NGPixel** [comment]
Check that the 443 port isn't already taken by another process and that the node process has the proper permissions to bind to this port.
