### ISSUE TITLE
reset admin password

### ISSUE THREAD

**Issue by slylander** [Requarks/wiki#1918]
Hi,

Is there a way to reset the admin password without losing already built pages? after unsuccessful LdapS cofiguration, I can't even login using the local admin account.
the wiki.js installation is on windows 2016, version. 2.1.113, running on PostgreSQL.

Thank you,

Willie

**Comment by winkelement** [comment]
If you have access to your postgres db you can change the pw manually `update users set password = '[bcrypthash]' where email = 'yourname@domain.com'`
You need to encrypt your new PW with bcrypt and insert the hash, you can use this tool for example https://bcrypt-generator.com/

**Comment by Smankusors** [comment]
Are you still have local authentication enabled?

**Comment by slylander** [comment]
Thank you all for responding, 
@winkelement, I will try reset password on local postures db.
@Smankusors, the local authentication is enabled.

**Comment by NGPixel** [comment]
Added a new entry to the troubleshooting docs on how to reset your password:

https://docs.requarks.io/en/troubleshooting#how-to-manually-reset-the-admin-password
