### ISSUE TITLE
Latest arm-2.3 docker image is developer version 2.0

### ISSUE THREAD

**Issue by kbfifi** [Requarks/wiki#1920]
**Describe the bug**
The latest available docker arm-2.3 version appears to be a developer version 2.0 

**To Reproduce**
Use the latest arm-2.3 image

**Expected behavior**
A quick fix was made available with the SAME docker tag as before: arm-2.3
I expected the version number in WikiJS to be accurate and something along the remark in the release notes:
"Users that upgraded to versions < 2.3.81 should upgrade immediately to 2.3.81"
So I did. My concern is that this is still not a correct version (not 2.3.81) and I still run the risk to upgrade in the future.

**Screenshots**
![image](https://user-images.githubusercontent.com/35601089/82660620-fcad5980-9c2a-11ea-84aa-118adb210382.png)
![image](https://user-images.githubusercontent.com/35601089/82660679-151d7400-9c2b-11ea-9d87-f4a5ae5f89c1.png)

**Host Info (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04, Docker]
 - Wiki.js version: arm-2.3
 - Database engine: [e.g. postgres 9.7, mysql 5.7]

**Additional context**

**Comment by maximegy** [comment]
I have the same problem, I tried to build the image from the git repo but I can't find the folder named assets

**Comment by robdegraaf** [comment]
I also have the same problem with tag 2.3-arm.
For now i deployed a container with 2.2-arm, that worked.

**Comment by natelandau** [comment]
same issue here...

**Comment by NGPixel** [comment]
Do a docker pull on `2.3-arm` and try again.

**Comment by kbfifi** [comment]
Thanks! Reporting 2.3.81 now

**Comment by robdegraaf** [comment]
Same here. Thank you :-)
