### ISSUE TITLE
postinstall is very slow

### ISSUE THREAD

**Issue by Magicloud** [Requarks/wiki#193]
### Actual behavior
```
> wiki.js@1.0.4 postinstall /home/local/ANT/shida/wiki/node_modules/wiki.js
> node install.js

 __    __ _ _    _    _
/ / /\ \ (_) | _(_)  (_)___
\ \/  \/ / | |/ / |  | / __|
 \  /\  /| |   <| |_ | \__ \
  \/  \/ |_|_|\_\_(_)/ |___/
                   |__/

⢃⠀ Remote app tarball found. Downloading...
```
The downloading takes forever.
### Expected behavior
I have no idea.
### Steps to reproduce the behavior
npm --version
5.3.0
node --version
v8.2.1

**Comment by Magicloud** [comment]
Using local tarball works.

**Comment by surchs** [comment]
I have the same issue, also with local tarball. 

have a bunch of idling `/usr/bin/mongod --config /etc/mongodb.con` processes and the `Local tarball found. Extracting...` status is stuck forever.
Worked fine just yesterday

**Comment by Magicloud** [comment]
Oh, yes. Local tarball extracting took forever just now. And now I dropped with everything.

**Comment by NGPixel** [comment]
Reopening this issue for further investigation

**Comment by zhang98722** [comment]
i meet this issue too,both remote and local tarball

**Comment by TorbenJ** [comment]
Related to #182

**Comment by marc-fun** [comment]
Same problem with me on 2 different machines (a virtual in France, an other one hosted on Infomaniak).

I managed to extract manually wiki-js.tar.gz and node_modules.tar.gz (in node_modules) and modified the node_modules/wiki.js/install.js by removing :
```
then(() => {
  isContainerBased && console.info('>> Fetching tarball...')
  return tasks.installFromLocal().then(succeeded => {
    return (!succeeded) ? tasks.installFromRemote() : true
  })
})
```
If I run `node wiki configure`, server works up to the mongodb configuration and then it stops with a `✖ Not Found` message.
If I manually configure the config.yml, I can run `node wiki start`, it works but I have no admin account...

**Comment by NGPixel** [comment]
**Update:** Heroku installs are now 100% bash script. So this issue should no longer occur.

A fix for other environments will be provided tomorrow.

**Comment by NGPixel** [comment]
**Update:** New linux / macOS script for installation: https://docs.requarks.io/wiki/install

Windows powershell script will be available later today.

**Comment by NGPixel** [comment]
**Update**: Windows powershell installation script is now available!

Read the new installation instructions for all platforms (Linux, macOS and Windows):
https://docs.requarks.io/wiki/install

Closing this issue. Create a new one if you're having trouble with the new installation scripts.
