### ISSUE TITLE
How to hide the Browse Button on the Navigation Pane

### ISSUE THREAD

**Issue by mk-rocket** [Requarks/wiki#1930]
**Question**
Is there a way to hide the "Browse" (folder tree) on the left navigation pane? I can't find anything on the administration page. Perhaps a CSS code can hide it? Thanks.

**Host Info (please complete the following information):**
OS: [Windows Server 2019 - IIS]
Wiki.js version: [2.3.81]
Database engine: [MSSQL]

**Comment by NGPixel** [comment]
Coming in 2.4
