### ISSUE TITLE
Search in non active Tabs

### ISSUE THREAD

**Issue by sbonaime** [Requarks/wiki#1933]
It is not possible to search in non active tabs. I know that tabs are not released yet.

For example in this page
https://docs.requarks.io/editors/markdown
I can't find the word 'warning' if the 'styling' tab is not active. It is a little frustrating if you want to search something on a help page...

**Comment by NGPixel** [comment]
That's how tabs work... Don't use them if you want your content to be searchable by the browser. This is true of any website using tabs.

Your content will still be indexed by the site search. But for browser search, there's not much I can do...
