### ISSUE TITLE
Logout does not end Keycloak session

### ISSUE THREAD

**Issue by preems1** [Requarks/wiki#1934]
**Describe the bug**
I logged in with the Keycloak authentication module. I can successfully log out of wiki.js but logging out does not end the session in Keycloak. So, when I click login, I get auto logged into the previous account.

**To Reproduce**
1. Enable Keycloak in Wiki.js
2.Log in using Keycloak
3. Logout of Wiki.js
4. Click Login
5. Be auto logged-in to previously logged-out account

**Expected behavior**
Keycloak session should be ended and users should be directed to login page

**Host Info (please complete the following information):**
 - OS: Docker version 19.03.8
 - Wiki.js version: 2.3.81
 - Database engine: postgres:11-alpine

**Comment by divialth** [comment]
Sorry for spamming that issue, but is there a chance, that this will be fixed in the 2.5 release of Wiki.js?
Or does anyone have a workaround for that?

**Comment by NGPixel** [comment]
Added in 062a0b79793daf06089bb6c994bf6b8d2d1c1d3c

However I don't have a keycloak instance to test with, so if someone could test it in the upcoming beta it would be great.
