### ISSUE TITLE
Let's Encrypt - Option to save to .pem file instead of or as well as DB

### ISSUE THREAD

**Issue by sammyt291** [Requarks/wiki#1936]
**Question**
I would like the option to save the generated letsencrypt certificates to file in order to allow apache reverse proxies to path to it.

I thought id post a Q here just incase iv missed a way in which the below is possible currently,
Cheers!

**For background:**
I run an apache webserver that utilizes ports 80 and 443 already.
By default wikiJS uses 3000 and 3443 which is fine.
however the letsencrypt requires port 80 to verify the generated cert.

to get around this I am wanting to setup a reverse proxy on my apache server to pass the requests to wikiJS on a certain URL, which works fine and the letsencrypt requests succeed and the cert is stored to the DB.

In order to pass requests on port 433 my apache server needs access to the cert also.
which as far as I can see currently only exists in the DB and not as a .pem file.

**Host Info (please complete the following information):**
OS: Windows Server 2019
Wiki.js version: 2.3.81
Database engine: mysql 8.0.18

**Comment by NGPixel** [comment]
Why do you want to use SSL on Wiki.js if you're already using a reverse-proxy? You're overthinking this. Apache should handle the SSL termination and Wiki.js should only serve on port 3000.
