### ISSUE TITLE
Unknown authentication strategy "jwt"

### ISSUE THREAD

**Issue by oshybrid** [Requarks/wiki#1937]
Sorry, new to servers, and setting up apps... ESPECIALLY in the area of databases.

Installed and configured (Ubuntu server 10.04).

Got to entering in admin information by browsing to the IP of the server.
I don't have a URL so I left that field alone.

The web page gave me an error in the subject bar.  Although the log in the terminal said everything was fine.

I stopped the server and started it up again, thinking I probably should have blanked out the URL field instead of leaving the example given in the Admin page.
But the web page came up fine.  It gave me an error of an "Unauthorized User" but then I went to the next web page to change the user to the Admin I created and got in fine.

1).  Should I be concerned about 'Unknown authentication strategy "jwt"' error I got on the first attempt to fire up the server.
2). Should I go hunting for the example URL and remove it?
3). As I said above I am very green in the area of DBs.  I created the user (non-SU), the DB and granted the user to connect to the wiki DB.  But in searching how to do all the above I saw it is normal to grant usage on a schema.  I did not see that info on the install and config docs.  Do I need to do that?  Should I give the user SU access?
4). Anything else to dealing with the Postgres DB I should be configuring on it?  NOTE is did add the entry in the docs "CREATE EXTENSION pg_trgm;"

**Comment by NGPixel** [comment]
1) No
2) You need to set an URL. If you only have an IP then use it (e.g `http://11.22.33.44`). You can change it in the admin > general
3) No
4) No
