### ISSUE TITLE
Migrating from xwiki to wikijs ?

### ISSUE THREAD

**Issue by Lange23** [Requarks/wiki#1938]
**Question**
Is there any best practice or does anyone has an idea how to migrate from xwiki to wikijs ?
Fortunately the wiki isn't that big at this moment, but I don't like to copy paste every page :-(

An Idea is to export all pages in html and than get the html snippet which has the page content and than put it in another html file which can be imported with wikijs.

But even thats sounds more complicated than copy/paste :-)

**Host Info (please complete the following information):**
OS: Ubuntu 18.04, Docker
Wiki.js version: [e.g. 2.3.81]
Database engine: [postgres]

**Comment by NGPixel** [comment]
You can export to HTML in XWiki (https://www.xwiki.org/xwiki/bin/view/Documentation/UserGuide/Features/Exports#HHTMLExport)

Then enable the Local Storage module in Wiki.js and point to the folder where you exported the HTML files. Then click the Import All action.

**Comment by Lange23** [comment]
Hi and thanks for the information.

I did it with html export and could import the hmtl code to wikijs, the only problem is, that it's pretty messie because of ht ehole xwiki CSS, JAVA and Script Codes inside that html file.

And it's a LOT OF WORK :-)

Another method could be to convert the articles markup language to html but tahts also a lot of work.

I think I'm gonna go with copy and paste and give a trainee a good week to work :-)
