### ISSUE TITLE
Hide / show Table of contents 

### ISSUE THREAD

**Issue by chans-me** [Requarks/wiki#1939]
Is there an option to hide and show table of contents in the the UI. 

Table of contents occupies some area, if needed the user can expand and collapse

Is this already implemented, please let us know how to handle this

**Comment by NGPixel** [comment]
This is not implemented yet. It will be an option in a future release.

**Comment by giesberge** [comment]
@chans-me you can css code inject the following
`.page-col-sd {
  display: none
}
.flex.page-col-content.xs12.lg9.xl10 {
  flex: 1;
  max-width: 100%
}`
