### ISSUE TITLE
Site not rendered correctly

### ISSUE THREAD

**Issue by ChristianAEDev** [Requarks/wiki#194]
### Actual behavior
The site is not rendered correctly. (See screenshot: ![screenshot from 2017-08-07 18-27-10](https://user-images.githubusercontent.com/10501258/29038131-7b25b84e-7b9e-11e7-92df-03106439f22f.png))

### Expected behavior
Side renders probably as seen on wiki.js.org

### Steps to reproduce the behavior
Install wiki.js running `./install.sh` connecting it to a locally running MongoDB instance inside of a docker container.
Open the configured page http://localhost:8033 and log in.

**Comment by NGPixel** [comment]
Your `host` config value is wrong. You must enter exactly the host/domain as entered by the client, including the port if different from 80 /443.

**Comment by ChristianAEDev** [comment]
That did the trick. Must have missed it in the docs.

Thank you!

**Comment by NGPixel** [comment]
Newsletter will launch with 2.0 (along with a new website). In the meantime, Twitter is the best way to get news:

https://twitter.com/requarks
