### ISSUE TITLE
Recycle Bin not working

### ISSUE THREAD

**Issue by misharigot** [Requarks/wiki#1940]
**Describe the bug**

The recycle bin seems to be disabled, making me not able to restore deleted pages.

**To Reproduce**

1. Delete a page
1. Go to pages in the admin area (http://wiki.example.com/a/pages).
1. The button 'RECYCLE BIN' is disabled.

**Expected behavior**

1. Delete a page
1. Go to pages in the admin area (http://wiki.example.com/a/pages).
1. The button 'RECYCLE BIN' is clickable.
1. Click on the 'RECYCLE BIN' button and navigate to the recycle bin, allowing me to restore deleted pages.

**Screenshots**
![image](https://user-images.githubusercontent.com/15928604/82900603-16b5a780-9f5d-11ea-9bf7-30c488db11eb.png)

**Host Info (please complete the following information):**
 - OS: Docker
 - Wiki.js version: 2.3.77
 - Database engine: postgres 12.2

**Comment by NGPixel** [comment]
Not a bug, this feature is simply not done yet. It's coming in a future release.

**Comment by misharigot** [comment]
Ah okay, might be nice for UX to add a popup saying it's coming in a future release.

**Comment by misharigot** [comment]
@NGPixel I also noticed just now that when attempting to delete a page, a modal is shown with the text:

> The page can be restored from the administration area.

I think it's better to replace that with some text indicating that it is currently not possible to restore deleted pages.

**Comment by peteruithoven** [comment]
I added this feature request to Canny: https://requarks.canny.io/wiki/p/recycle-bin

**Comment by SanQianQVQ** [comment]
Nearly five years on, I know it's impossible to ask too much of an open source project, but this module is important, has there been any progress at all, or is there a wait for v3?
