### ISSUE TITLE
upgrade to 2.3.81 do not have folder structure and all my folder were linear

### ISSUE THREAD

**Issue by elaheh-ha** [Requarks/wiki#1947]
I have a question , in we use 2.0.12 wiki version and 4 weeks ago we upgrade this to 2.3.81 , we suddenly saw that all the navigation list when we click on new page were list without any structure and it seems like we do not have any parent-child structure. immediately we restore last 2.0.12 version and now we need to upgrade our version for new features and we don't know this problem will happen again or not. would you please help us to solve this problem? can you suggest some solutions? 

thank you

OS: Ubuntu
Wiki.js version: [2.0.12]
Database engine: [postgres]

**Comment by winkelement** [comment]
> [...] we suddenly saw that all the navigation list when we click on new page were list without any structure

Can you explain what you mean? If you struggle to describe the problem add screenshots for example.
 
> [...] and it seems like we do not have any parent-child structure.

See above.

**Comment by elaheh-ha** [comment]
I do not have any screenshot of that situation because we went back to previous version immediately. I can explain more: When we click on newpage button a browse window will open [to select path] and then we saw all the folders show without any folder / sub folder.....  in the one level.

**Comment by NGPixel** [comment]
Closing as I can't replicate your issue nor can you provide screenshots / in-depth info. So this won't go anywhere.

If you experience the issue again, I'll re-open the ticket so we can investigate further.
