### ISSUE TITLE
footnote in markdown does not generate id

### ISSUE THREAD

**Issue by joshuaavalon** [Requarks/wiki#1948]
**Describe the bug**
If you have the following content

```markdown
foo [^1]

[^1]: Bar
```
It generate the footnote. However, `foo [^1]` link is broken with the following error in console.

```
Uncaught Error: Target element "#fn1" not found.
    at S (app.3db9914c6708a1a6227a.js:35)
    at Object.E (app.3db9914c6708a1a6227a.js:35)
    at HTMLAnchorElement.e.onclick (theme0.bd020700eb70775eec26.js:1)
```

It seems that footnotes does not have the ids in the elements.

**To Reproduce**
1. Add the following content in the page

```markdown
foo [^1]

[^1]: Bar
```
**Expected behavior**

Click and scroll to the footnote.

**Screenshots**

**Host Info (please complete the following information):**
 - OS: Docker Container (Linux)
 - Wiki.js version: 2.3.81
 - Database engine: postgres

**Comment by NGPixel** [comment]
This is already fixed in 2.4.
