### ISSUE TITLE
docs: How to delete content?

### ISSUE THREAD

**Issue by bennyn** [Requarks/wiki#195]
I created some Wiki pages and I can edit them but I don't know how to delete them. From the UI I cannot find a "Delete" button (only "Move", "Source", "Edit" and "Create" are available). I couldn't find anything related in [your documentation](https://docs.requarks.io/) so I hope that you can help me here.

**Comment by NGPixel** [comment]
You can't from the UI at the moment. This feature is coming in 2.0.

For now, you must delete the file from disk and restart Wiki.js.

**Comment by bennyn** [comment]
Ok, I deleted the files from my Git repository (which is used for remote sync) and afterwards I restarted all my dynos on Heroku (which are serving my Wiki.js installation). This worked. Thanks! 👍
