### ISSUE TITLE
Braces does not work in markdown inline math block

### ISSUE THREAD

**Issue by 6cdh** [Requarks/wiki#1952]
**Describe the bug**
Braces do not work in markdown inline math block. I must use double braces to make it work.

**To Reproduce**
1. Create a new markdown page.
2. type `$e^{x}$`

**Expected behavior**
e power of x.

**Screenshots**
![Screenshot_20200528_232645](https://user-images.githubusercontent.com/39000776/83162315-2d662500-a13c-11ea-8fd9-4450dd1e8c1c.png)

**Host Info (please complete the following information):**
 - OS: Linux - Manjaro Linux 20.0.1 x64
 - Wiki.js version: 2.3.81
 - Database engine: postgres 12.2

**Comment by gzzchh** [comment]
try adding "\" before braces
