### ISSUE TITLE
ARM Latest Tag

### ISSUE THREAD

**Issue by maximegy** [Requarks/wiki#1960]
**Describe the bug**
Docker image latest tag does not contain the ARM OS/ARCH

**To Reproduce**
1. Go to https://hub.docker.com/r/requarks/wiki/tags
2. See the latest Tag
3. Under OS/ARCH
4. See that there's only "linux/amd64"

**Expected behavior**
Adding "linux/arm64" and "linux/arm/v7" OS/ARCH to this tag to allow ARM users to use it and automate container updates.

**Screenshots**
![image](https://user-images.githubusercontent.com/18288976/83282930-a320ce00-a1da-11ea-967a-7c712e00e295.png)

Thank you.

**Comment by NGPixel** [comment]
All arch are now under a single tag since 2.4.
