### ISSUE TITLE
Start Fresh From Git Repo

### ISSUE THREAD

**Issue by hexbinedit** [Requarks/wiki#1961]
**Can we flush the database based modifications?**
Our team has gone through several iterations of working with the wiki and work in a one-directional sync from our remote git repository. There are older iterations of the remote repository that have complicated clean up and changes that have been made through the GUI that have created conflicts.

Our remote repository has been shored up and is ready for production.

We are happy with the server configurations, we just want our pages to rebuild once from git so that we can continue to make changes from there.

Should I be focusing on the database directly or is there a feature within wiki.js to purge all local pages in the database and reload the remote git repository from scratch.

Also, would a clean postgres database allow us to accomplish this or would we lose a lot of the wiki.js navigation configurations along the way. That would be okay, but what else would we lose?

Lastly, with the locally stored repo created through the GUI, if I cloned our remote repo to the wiki.js application directory and ran the 'Import Everything' feature, would that purge the unwanted content?

Thank you for the help!

**Host Info:**
OS: Ubuntu
Wiki.js version: 2.3.81
Database engine: postgres 12.1

**Comment by NGPixel** [comment]
Starting from a fresh DB would be the best solution. You would loose your sidebar navigation, users + groups and site settings.

**Comment by hexbinedit** [comment]
That would be all site settings under the administration section including for example the remote git settings correct?

Thank you again!
