### ISSUE TITLE
Video embed

### ISSUE THREAD

**Issue by bggo** [Requarks/wiki#1962]
**Question**
Hey guys after many years using mediawiki and tikiwiki, Wiki.js its been amazing =D 

I was just wondering if simple features like embed video in the pages will take much longer to be available! It seams to be a simple thing that will enable a lot to us!

Hope to here from you guys soon!

Regards

**Host Info (please complete the following information):**
OS: [e.g. Ubuntu 18.04, Docker]
Wiki.js version: [e.g. 2.0.1]
Database engine: [e.g. postgres 9.7, mysql 5.7]

**Comment by NGPixel** [comment]
You can already embed videos (with a `<video>` or `<iframe>`) using the code editor or by using HTML in the markdown editor.

A more "visual" way will be added in a future release. No ETA.
