### ISSUE TITLE
I turned off the iframe but the iframe doesn't show up.

### ISSUE THREAD

**Issue by touhoku-japan** [Requarks/wiki#1968]
**Describe the bug**
I turned off the iframe but the iframe doesn't show up.

https://wiki.japanclan.tokyo/ja/hardware/DELL-Inspiron-17-3000

**To Reproduce**

1. Security
2. Block iframe Embedding is turn off
3. refresh iframe page
4. HTML tag is always show

**Expected behavior**
Please reflect the iframe as HTML.

**Screenshots**

**Host Info (please complete the following information):**
 - OS: Windows 10 64bit Chrome latest
 - Wiki.js version: latest Wiki.js 2.3.81

**Additional context**
The old version was more stable.

**Comment by winkelement** [comment]
Go to **Administration** > **Rendering** > **html -> html** > **Security** and disable **Sanitize HTML**.
After that you need to edit and save the page again to render the iframe.

![Bildschirmfoto 2020-05-31 um 20 07 11](https://user-images.githubusercontent.com/3525191/83359576-5c1e0e80-a37b-11ea-84d5-f57ccfc0cc1b.png)

The setting you changed prevents **other sites** from embedding your site.

**Comment by Smankusors** [comment]
don't forget, you need to "re-save" the page so the wiki will re-render it again

**Comment by touhoku-japan** [comment]
I'm thrilled with the very quick response. I am very grateful. thank you very much.
