### ISSUE TITLE
docs: How to create side navigation?

### ISSUE THREAD

**Issue by bennyn** [Requarks/wiki#197]
In the [Wiki.js documentation](https://docs.requarks.io/) I have seen that it's possible to create a very nice looking side navigation (like "All Pages" -> "Wiki.js" -> "Admin Guide"). How can this be achieved? I already created directories and subdirectories in my GitHub repository (which syncs with my Wiki.js installation) but these directories don't show up as clickable menu items. 😢 

This is what I want to build:

![unbenannt](https://user-images.githubusercontent.com/469989/29047723-5cb574e2-7bcd-11e7-9aaf-377fa1ff878c.png)

**Comment by NGPixel** [comment]
Directories are not actual pages. You must create a page inside for them to appear in the navigation.

**Comment by bennyn** [comment]
I created a Markdown page inside the newly created directories but they didn't show up in my navigation. 😢 

I looked up [this directory](https://github.com/Requarks/docs/tree/master/wiki/admin-guide) to get a grasp of what's going on. In the screenshot it's shown that the sidebar navigation is named "Admin Guide" but the folder inside the "Requarks/docs" repo is just called "admin-guide", so how does the translation (from "admin-guide" directory to "Admin Guide" navigation) happen?

**Comment by NGPixel** [comment]
Your folders (and files) must follow the kebab case naming if you create them outside Wiki.js. Otherwise they won't be indexed properly.

Names are automatically converted back to normal case when displayed. e.g. `admin-guide` becomes `Admin Guide`

**Comment by bennyn** [comment]
**Thanks for the info!** 

Instead of naming my directory "Curriculum", I named it "the-curriculum" and it was picked up by the automatic GitHub synchronization. 👍

**Comment by el3ctrician** [comment]
can we keep this sidebar fixed ? when you open a page it disappears is there is a way to keep the folder structure ?

**Comment by Frankstar** [comment]
@el3ctrician i would love this feature too - but i dont think it makes sense to discuss it here - open a new issue/feautre request

the best solution would be to have an option to fix it or show breadcrumbs top/bottom of the page
(mayb this is planned for 2.0 anyways)

**Comment by AritroMukherjee** [comment]
Having followed the steps mentioned in the installation guide,
These are the default pages coming up. 


![wikiwelcomepage](https://user-images.githubusercontent.com/15279722/38801757-5bd3f662-4188-11e8-972b-2bea29de09b0.PNG)

![wikicreatehomepage](https://user-images.githubusercontent.com/15279722/38801762-61d8385c-4188-11e8-9533-c7ef1058a42c.PNG)


Can you kindly assist me with the creation of markdown pages in wiki, after this.
