### ISSUE TITLE
Update wiki version to 2.4.75, Errors with garbled codes

### ISSUE THREAD

**Issue by wlfcss** [Requarks/wiki#1971]
**Describe the bug**

**To Reproduce**
- none
**Expected behavior**
- none

**Screenshots**
![image](https://user-images.githubusercontent.com/12138285/83381017-16605500-a412-11ea-81b7-d78466d6874f.png)

**Host Info (please complete the following information):**
 - OS: [Ubuntu 18.04]
 - Wiki.js version: [2.4.75]
 - Database engine: [postgres]

**Additional context**

**Comment by Grinsens** [comment]
Also a problem with the encoding

![one](https://cdn1.savepice.ru/uploads/2020/6/1/8c683447d3edeb0a071d2edc5cceb961-full.jpg)
![two](https://cdn1.savepice.ru/uploads/2020/6/1/5784cf95939492fcfc3b4d8c2308b364-full.jpg)
![three](https://cdn1.savepice.ru/uploads/2020/6/1/06053313dde9853d948fd86ff26dd708-full.jpg)
