### ISSUE TITLE
The page path field allows invalid character sets.

### ISSUE THREAD

**Issue by nktech1135** [Requarks/wiki#1982]
**Describe the bug**
The page path field allows leading and trailing slashes.

**To Reproduce**
1. Create a new page in wikijs.
2. Edit the page
3. in path add a slash at the beginning and click ok and save.
4. Try editing the page, You should get a 502 error from the browser.

**Expected behavior**
When clicking ok or save you should get an error informing the user that slash is not a valid first character.
Validation should also be added to block trailing slashes and double slashes. with appropriate error messages.

**Host Info (please complete the following information):**
 - OS: [Ubuntu 20.04
 - Wiki.js version: 2.3.77
 - Database engine: [postgresql 12.2

**Comment by NGPixel** [comment]
Fixed by 65f71d8e3bbeccc7fa3d0bfb86a1e6c3b3aac27d
