### ISSUE TITLE
How to add pages to Global Navigation

### ISSUE THREAD

**Issue by davepile** [Requarks/wiki#1985]
**Question**
I have just installed Wiki js and added some pages but cannot see how to add these to the Global Navigation sidebar.

The only reference to Global Navigation I can find in the docs is in /guide/intro but nowhere does it say how to add items.

Currently my Global Navigation only has a Home icon and Browse/ Main Menu togggle in the first row and in the second row a nav item for Home. Nothing else

I am getting an error on saving of a new page. Hard to get any idea what the problem is as it just briefly flashes a red message "Unexpcted error".
Unsure if it is preventing the pages being automatically added to Global Nav as I am unsure what should be happening.

**Host Info (please complete the following information):**
OS: Windows 2012 R2
Wiki.js version: 2.3.81
Database engine: postgresql 12.3.1 x64

**Comment by NGPixel** [comment]
Under Admin > Navigation

**Comment by davepile** [comment]
aha, thank you
