### ISSUE TITLE
Violating foreign key constraint "pages_editorkey_foreign"

### ISSUE THREAD

**Issue by matthew-dean** [Requarks/wiki#1987]
**Describe the bug**
The GraphQL mutation query says it requires a string for the editor type. However, it doesn't specify with any more granularity what that type must be, and I don't see a query for editors.

**To Reproduce**
Create a GraphQL pages / create query.

**Expected behavior**
The GraphQL docs should either restrict the editor field by a specific narrower type than string, or there should be a query that lists all the valid keys for an editor that can be assigned to a page. Ideally, the editor field would not be required.

In the meantime, what's the foreign key for the "html" editor type?

**Comment by NGPixel** [comment]
A query for editors is coming in a future version. You must use one of the editor keys as listed here:
https://github.com/Requarks/wiki/tree/master/server/modules/editor

The raw HTML editor is `code`.

**Comment by matthew-dean** [comment]
@NGPixel Is `code` the WYSIWYG editor?

**Comment by NGPixel** [comment]
ignore `wysiwyg`, its an old editor that was never completed.
