### ISSUE TITLE
git sync not working as understood

### ISSUE THREAD

**Issue by hexbinedit** [Requarks/wiki#1988]
**New files added to the git repository are not having pages built**
New files added to the git repository are not having pages built for them in the wiki. Likewise, removal of files is not represented in the pages on the GUI. Changes to existing files that are then synced are propagating into the wiki just fine.

**New markdown files**
New markdown files added under new directories in the repo, created on a separate branch, are merged to the master and then synced with the wiki. Said new files should have pages built for them.

**Usage: git add, commit, push, subsequent merge**
Am I misunderstanding the purpose of the git sync functionality. The new pages are propogated into the local repo and I can use the option to import everything to add the new files, but this is not a feature I want to hand out. Plus with files being removed from the repo, why can't the wiki determine that the page should be removed? What should the expected functionality be?

Thank you for your time!

Host Info:
OS: Ubuntu
Wiki.js version: 2.3.81
Database engine: postgres 12.1

**Comment by Mpic** [comment]
Excuse me, but what is the answer to this ? I have the same question, evaluating wiki.js for a team wiki and preferring to edit local Markdown files synced with git.

**Comment by hexbinedit** [comment]
Here are my notes for fast rebuild:

Use links with repo as root. if your repo is Project1 start under that with /use/this/path/home.md

Manage Assets (imgs, files) as part of the git repository with similar linking

For quick rebuild 

**use this advice with care depending on how far behind your repository might be behind any changes made directly through the GUI as those database changes and additions will be lost if you don't backup your database**

1. Stop Wiki.JS service
2. Delete all information in the database of page related tables and asset(if you don't have any in the db only) related tables
3. Make sure to sync through the GUI and your local repo is current
4. Use the Import Everything feature from the GUI under Storage.

That method should allow for the rebuilding of pages from the current state of the git.
