### ISSUE TITLE
How to set up mail with mailgun?

### ISSUE THREAD

**Issue by j0w0** [Requarks/wiki#1989]
**Question**
I'm Trying to set up mail with mailgun, but i get 501 invalid command or cannot parse from address (i'm using the correct settings i got from mailgun, i think)
![image](https://user-images.githubusercontent.com/24716467/83706787-ebd7ed00-a607-11ea-8502-0f3da1caa6c1.png)
not sure if im doing something wrong, if this is a wiki.js problem or if its a mailgun problem
**Host Info (please complete the following information):**
OS: Ubuntu 20.04, Docker
Wiki.js version: 2.3.81
Database engine: postgres 11.8

**Comment by Smankusors** [comment]
The sender email format should be [name]@[host]. Do you enter it with [host] only?

**Comment by NGPixel** [comment]
> The sender email format should be [name]@[host]. Do you enter it with [host] only?

Probably the issue yes. That icon was changed in 2.4 to clear any confusion.

**Comment by j0w0** [comment]
OH I SEE THANKS
