### ISSUE TITLE
Can't figure out how to enable HTTPS

### ISSUE THREAD

**Issue by j0w0** [Requarks/wiki#1993]
**Question**
Couldn't find any guide on the wiki for getting https to work
SSL admin page shows this: 
![screenshot  20-06-04 15-30-22](https://user-images.githubusercontent.com/24716467/83769814-d4cce580-a66f-11ea-81c0-205c9cc35b63.png)
going to the https version of the site results in a "cant establish a connection"
i don't see a clear way to enable https, could someone show me how?

**Host Info (please complete the following information):**
OS: Ubuntu 20.04, Docker
Wiki.js version: 2.3.81
Database engine: postgres 11.8

**Comment by winkelement** [comment]
Have you set `SSL_ACTIVE=true`?
Have you mapped a port on your host machine to the wiki.js container port `3443`?
What is the output of `docker ps`?

**Comment by NGPixel** [comment]
https://docs.requarks.io/install/docker#https

**Comment by j0w0** [comment]
im not entirely sure how to translate this into the "ubuntu" setup which uses `docker start` to run the wiki and not `docker run`
im a bit of a docker noob sorry 
how do i pass environment variables? do i need to redo stuff?

**Comment by NGPixel** [comment]
Use this guide, starting at step 4:
https://docs.requarks.io/install/digitalocean#automatic-https-with-lets-encrypt

**Comment by j0w0** [comment]
managed to get it work thanks :)
