### ISSUE TITLE
Getting there

### ISSUE THREAD

**Issue by NigelLuckie** [Requarks/wiki#1994]
**Question**
I can't seem to configure mail.  I keep getting the error "self signed certificate"
"

I have configured LDAP, and it appears to be correct, but I still can't add users using LDAP.  I suspect mail must be working first, but there's no test button to confirm the settings.

When I'm finished with the configuration how do I switch to running mode?

**Host Info (please complete the following information):**
OS: Windows 2016
Wiki.js version: 12.16.3
Database engine: postgres 12

**Comment by Smankusors** [comment]
mail is not required. Do you enable TLS/SSL on your LDAP? Do you use self signed certificate on the LDAP?

**Comment by NigelLuckie** [comment]
According to what I'm seeing in Powershell, DLAP is configured correctly after I set it, but I can't search users in Active Directory.  When I type a name from AD in it does not display under Users.

Is there some special format I need to use to search users with LDAP?

**Comment by NigelLuckie** [comment]
Is the mail not supported yet?

**Comment by winkelement** [comment]
> According to what I'm seeing in Powershell, DLAP is configured correctly after I set it, but I can't search users in Active Directory. When I type a name from AD in it does not display under Users.
> 
> Is there some special format I need to use to search users with LDAP?

Enable self registration and login with LDAP user credentials.

**Comment by winkelement** [comment]
> Is the mail not supported yet?

Mail is working fine. What is your mail setup?

**Comment by NigelLuckie** [comment]
I've tried 2 different methods.  

We use and MDaemon server for the gateway.  As long as I add the IP of the WIKI server as trusted it doesn't require a logon

I also tested using the Exchange server with credentials.

Whenever I try to send a test email it responds with a self signed certificate error

The Exchange server is not using a self-signed certificate for IIS, but all Exchange servers do use a self-signed internal certificate.  There is no button to ignore the error.

**Comment by Smankusors** [comment]
oh yeah you mentioned this on the beginning

```
Wiki.js version: 12.16.3
```

Is this.... nodejs version? Rather than Wiki.js version?

**Comment by NigelLuckie** [comment]
I followed the setup steps from the Wiki.js website.  NodeJS was needed for the install.

https://docs.requarks.io/install/windows

Do you have a different link for the install and configuration?  I'm having a lot of trouble finding setup documentation.

**Comment by winkelement** [comment]
So everything (including LDAP login) is working now except your E-Mail setup?

Have you tried **disabling Verify SSL Certificate** in mail settings?

**Comment by NigelLuckie** [comment]
Secure (TLS) is turned off.

I can't find a button/control called Verify SSL Certificate under Mail.

It's set to use port 25 with no authenticaion to a server that doesn't require authentication

When I run test I get a popup "self signed certificate"

Am I missing some controls on the page that should be there?

**Comment by NigelLuckie** [comment]
![image](https://user-images.githubusercontent.com/65965135/84035376-a0a43e00-a969-11ea-949f-cfa99d5f6392.png)

This what keeps popping up but the settings do not use SSL.

**Comment by NigelLuckie** [comment]
Secure TLS is not enabled.

![image](https://user-images.githubusercontent.com/65965135/84035547-ee20ab00-a969-11ea-8d38-831237dfb55d.png)

**Comment by winkelement** [comment]
What version of Wiki.js you are using? The option to disable _Verify SSL Certificate_ was added in v2.4

**Comment by NigelLuckie** [comment]
Thank you.  Currently on 2.3.81.  Just looking for how to download the and install the update now.

**Comment by NigelLuckie** [comment]
I updated to the latest version

![image](https://user-images.githubusercontent.com/65965135/84045758-31354b00-a977-11ea-921b-00ff0d8dbf75.png)

I updated mail to not check SSL

![image](https://user-images.githubusercontent.com/65965135/84045790-3c887680-a977-11ea-8f00-11ae77729806.png)

I'm still getting the self signed certificate warning.  What am I missing?

**Comment by NigelLuckie** [comment]
Powershell shows that LDAP is configured correctly.

![image](https://user-images.githubusercontent.com/65965135/84046076-9f7a0d80-a977-11ea-9153-e2a32a384024.png)

When I check users, I can't search LDAP for users.

![image](https://user-images.githubusercontent.com/65965135/84046125-aef95680-a977-11ea-8e9a-1309d49f738a.png)


Am I using the Users section incorrectly?

**Comment by winkelement** [comment]
> > According to what I'm seeing in Powershell, DLAP is configured correctly after I set it, but I can't search users in Active Directory. When I type a name from AD in it does not display under Users.
> > Is there some special format I need to use to search users with LDAP?
> 
> Enable self registration and **login with LDAP user** credentials.

**Comment by NigelLuckie** [comment]
The self-registration options are greyed out so they can't be used.

![image](https://user-images.githubusercontent.com/65965135/84052266-56798780-a97e-11ea-834f-b84cae7ea451.png)

**Comment by winkelement** [comment]
Mhm something looks off with your installation where are your radio buttons? 😕 

![Bildschirmfoto 2020-06-08 um 19 00 14](https://user-images.githubusercontent.com/3525191/84059264-9199ac00-a9ba-11ea-82e1-544e4879b7fe.png)

**Comment by NigelLuckie** [comment]
I tried something.  I restarted Powershell as Administrator.  Mail is now working.

Self-registration is still greyed-out though.

![image](https://user-images.githubusercontent.com/65965135/84093911-88640b80-a9c9-11ea-88cb-5ef68e6ebb2b.png)

**Comment by NigelLuckie** [comment]
Ok.  I figured it out.  didn't realize there was a slider bar to activate.  Self-registration is now enabled.

**Comment by NigelLuckie** [comment]
The last step now is to activate it so it listens on 443 instead of 3000.   How do I do that?
