### ISSUE TITLE
Bulk import feature

### ISSUE THREAD

**Issue by pauhaith360** [Requarks/wiki#1996]
I was hoping for help with bulk importing users. I see the button when I go to create a new users but it is grayed out. I'm not sure if there is a setting or something I need to do to use this feature. 

My implementation of Wiki.js inlcudes a connection to OpenLDAP. What I would like to do is when a user signs in they are automatically added to a specific Wiki.js group based on their OU. I wasn't able to find anything that would assist with this. 

So I figured if I could bulk import users ahead of time. With the groups they are supposed to be in already set. This should get me where I want to be. But creating users one at a time would be a bit cumbersome. I was hoping to use the bulk import feature to add multiple users at once. 

Any help would be greatly appreciated. Thanks! 

**Host Info (please complete the following information):**
OS: [Ubuntu 16.04, Docker]
Wiki.js version: [e.g. 2.3.81]
Database engine: [postgres 11.8]

**Comment by Smankusors** [comment]
you can just activate the self registration feature in the authentiation module. Which will automatically create a new user (if not exists) when logged in via LDAP.

**Comment by pauhaith360** [comment]
Hi @Smankusors , Thank you for the response! I have done just that and it works great. But for my use case, it may not be the best solution. 

What I'm trying to do, is say I have a 3 class rosters of students from 3 different schools. I want them each to have only the access provided by their group, say a group for each school. With self registration, as they all log in they all will end up in the same group or groups listed in the self registration, such as guest. I would then have to go in and move the students to their respective school groups. 

What I'm hoping to do, is use the bulk import feature to import multiple users that belong in the same group. For this example, I would have 3 bulk import templates for each student list from each school. This would allow me to have their accounts pre ready with the correct group. Then when they sign in, they are already in their correct group. Hoping this would be a way to keep from having to move users after they sign in. 

I realize there may be a better way to do this, as I'm just starting to use Wiki.js. Any help or suggestions is greatly appreciated! Thanks again.

**Comment by winkelement** [comment]
As far as i can see right now there is no way for a more granular automatic group assignment then the Auth provider itself. 
There is a feature request already out there though regarding LDAP groups https://requarks.canny.io/wiki/p/map-ldap-groups-as-roles

**Comment by NGPixel** [comment]
Closing this ticket. Follow the above feature request instead.
