### ISSUE TITLE
Question: GraphQL Permissions/Access to create Page via Admin GraphQL Console

### ISSUE THREAD

**Issue by cdesch** [Requarks/wiki#1999]
**Question**
I'm trying to use a graphQL mutation to create a page from the admin panel. When I try, I get a "forbidden" response.

How do I provide access to the GraphQL to create a page?

Here is my Query:

```
mutation {
  pages {
    create(
      content: "Mycontent"
      description: "MyDescription"
      title: "here"
      editor: "markdown"
      isPublished: true
      isPrivate: false
      locale: "en"
      path: "home"
      tags: []
    ) {
      page {
        id
      }
    }
  }
}
```

**Host Info (please complete the following information):**
OS: Docker
Wiki.js version: requarks/wiki:beta - 2.4.75
Database engine: postgres:11-alpine

Screenshot:
![Screen Shot 2020-06-05 at 10 02 45 AM](https://user-images.githubusercontent.com/1207795/83885617-96d5cd00-a714-11ea-949b-ceb239249f70.png)

**Comment by NGPixel** [comment]
You need to provide an API key in the Authorization header.
