### ISSUE TITLE
docs: How to order items in the sidebar?

### ISSUE THREAD

**Issue by bennyn** [Requarks/wiki#200]
I created two pages and it looks like the latest one shows up on top in the sidebar. How can I change that?

**Screenshot**

![screenshot](https://user-images.githubusercontent.com/469989/29149212-f14746d4-7d72-11e7-8079-0550c84e978b.png)

**Comment by NGPixel** [comment]
Items are listed alphabetically, the order cannot be changed.

**Comment by bennyn** [comment]
Ok, then I will prefix items with `1.`, `2.`, `3.`, etc.
