### ISSUE TITLE
text alignment in markdown editor for RTL pages

### ISSUE THREAD

**Issue by talalvas** [Requarks/wiki#2004]
**Describe the bug**
When editing a page using the Markdown editor for RTL locale pages (like Hebrew), the page is align to left instead of being aligned to right.
I've already reported this bug (#1578) but it must have been missed between all the other bugs.
The problem was fixed before but returned on one of the previous updates.

**To Reproduce**
To reproduce this bug you just need to create a new page for Hebrew local (or any other RTL I presume) and watch.

**Expected behavior**
The edit section should be on the **right side** and the text written in it should be aligned to the **right**.
The preview section should be on the **left side** and the text written in it should be aligned to the **right**.

**Screenshots**
![1](https://user-images.githubusercontent.com/9365114/83964793-09cb7900-a8b8-11ea-95ef-564bad34e83a.png)

**Host Info**
 - OS: Windows_NT (win32) 10.0.17763 x64
 - Wiki.js version: 2.4.105
 - Database engine: PostgreSQL 12.1, compiled by Visual C++ build 1914, 64-bit

**Comment by sesajad** [comment]
#1578 it's the same. @NGPixel you can close this I guess
