### ISSUE TITLE
Server requests authentication error on MySQL 8.0 "Server requests authentication using unknown plugin sha256_password."

### ISSUE THREAD

**Issue by phyozawtun** [Requarks/wiki#2006]
**Error Message**
Server requests authentication using unknown plugin sha256_password. See TODO: add plugins doco here on how to configure or author authentication plugins.

**Question**
I am using node 12.18 and npm 16.4
While I am trying to install wiki.js on my Digital Ocean server, after I type `node server`, I got the above error message.

**System Information**
OS: Ubuntu 18.04.4 LTS, Droplet
Wiki.js version: 2.0
Database engine: 8.0.20 - MySQL Community Server - GPL

**Comment by winkelement** [comment]
Check your mysql configuration. Looks like you are using an non-default authentication plugin.

> 
> In MySQL 8.0, `caching_sha2_password` is the default authentication [...]
> [...] `sha256_password` is deprecated and will be removed in a future MySQL version

https://dev.mysql.com/doc/refman/8.0/en/sha256-pluggable-authentication.html

**Comment by phyozawtun** [comment]
In my authentication plugin, I switch to `caching_sha2_password` from `mysql_native_password`. Now it is work and thank you for the quick response.
