### ISSUE TITLE
PostgreSQL search not working

### ISSUE THREAD

**Issue by MagnumDingusEdu** [Requarks/wiki#2008]
**Describe the bug**
The search functionality isn't working for me. It shows Unexpected error occurred. 

**To Reproduce**
1. Enable the pg_trgm extension. `CREATE EXTENSION pg_trgm;`
2. select  "Database - PostgreSQL" as the search engine.
2. Search for something.
3.  shows "unexpected error occured". Search does not work. 

Logs : 
```
2020-06-07T12:17:58.170Z [JOB] info: Using database driver pg for postgres [ OK ]
2020-06-07T12:17:58.355Z [JOB] info: Rebuilding page tree: [ COMPLETED ]
2020-06-07T12:18:05.925Z [MASTER] warn: Search Engine Error:
2020-06-07T12:18:05.925Z [MASTER] warn: SELECT word, word <-> $1 AS rank FROM "pagesWords" WHERE similarity(word, $2) > 0.2 ORDER BY rank LIMIT 5; - operator does not exist: text <-> unknown
```

**Expected behavior**
The basic search is working, but postgres based is not. It should work. 

**Host Info (please complete the following information):**
 - OS: Linux - Ubuntu (bionic) 18.04 x64
 - Wiki.js version: 2.4.105
 - Database engine: postgres 10.12
 - Node js : 12.18.0

**Comment by winkelement** [comment]
Are you sure you have enabled `pg_trgm` for the correct database? It has to be set **per database**.

**Comment by MagnumDingusEdu** [comment]
Thank you ! It's working now. My bad.

**Comment by winkelement** [comment]
I added a [PR](https://github.com/Requarks/wiki-docs/pull/10) to add this info to the docs.

**Comment by ba-moun** [comment]
Hello, I've got the same problem. How do I enable pg_trgm?

**Comment by MagnumDingusEdu** [comment]
Yep. That's the command. But you have to specify the database too. I'm assuming you've already made a database and a user for wiki.js. 

The way I did it is:
```bash

# Connect to the wiki.js database
psql --host=localhost --dbname=wikijs --username=wikiuser 

# Enable the extension
CREATE EXTENSION pg_trgm;
```

What's the error you're getting ?

**Comment by ba-moun** [comment]
Thank you very much @MagnumDingusEdu .

I had the permission denied error.

ERROR:  permission denied to create extension "pg_trgm"

I mitigated the issue like this:
# su postgresql -c "psql --dbname=<wikijsdb> -c 'CREATE EXTENSION pg_trgm;'"

**Comment by MagnumDingusEdu** [comment]
Great !
