### ISSUE TITLE
How do I customize the ckeditor that is builtin?

### ISSUE THREAD

**Issue by dickyj** [Requarks/wiki#2009]
Hi,
If I wish to add new plugins to the ckeditor that is builtin, are there any instructions on how I can go about doing so? Thanks.

**Host Info (please complete the following information):**
OS: Docker
Wiki.js version: 2.4.15
Database engine: postgres 9.7

**Comment by NGPixel** [comment]
You'd need to fork this repo:
https://github.com/Requarks/wiki-ckeditor5

Make your changes then replace the `@requarks/ckeditor5` in your forked version of Wiki.js.
