### ISSUE TITLE
no login (username/password) boxes shown when using ldap only

### ISSUE THREAD

**Issue by wookoouk** [Requarks/wiki#201]
### Actual behavior

No login option shown

### Expected behavior

a login option

### Steps to reproduce the behavior

disabling all authentication methods except LDAP

**Comment by wookoouk** [comment]
So, I looked at the code, the local username/password are passed to ldap auth IF local auth failed AND ldap is enabled.
so ldap will not work if local is turned off, fair enough.
a side effect is that the text `Or, log in using...` shows when local and LDAP are the only options enabled, this seems incorrect (as there would be no options under the text to use).

**Comment by wookoouk** [comment]
this effect is caused because ldap gets caught up int the 'socialEnabled' flag in the code.
a work around for this is to change `server/libs/config.js`
```
appconfig.authStrategies = {
    list: _.filter(appconfig.auth, ['enabled', true]),
    socialEnabled: (_.chain(appconfig.auth).omit('local', 'ldap').filter(['enabled', true]).value().length > 0)
  }
```
to 
```
appconfig.authStrategies = {
    list: _.filter(appconfig.auth, ['enabled', true]),
    socialEnabled: (_.chain(appconfig.auth).omit('local').filter(['enabled', true]).value().length > 0)
  }
```

**Comment by NGPixel** [comment]
Fixed for 1.0.6 (a5c73892069398d3ad90e57e332bba43ffb4d4ea)

**Comment by vaindil** [comment]
@NGPixel I just installed Wiki.js fresh, first time ever using it, and I have this issue. I'm on 1.0.11, latest version as of this comment. The workaround above does not work either: When I do that, the text comes back saying "Log in using..." but no text boxes appear.

**Comment by wookoouk** [comment]
This is exactly what I had, I will have a look what I did to solve it and
get back to you asap (if I forget, bug me)

**Comment by Smuggla** [comment]
This is due to 

`npm install wiki.js@latest`

installing `1.0.5`

Looks like the docker container has the same issue too...

Thanks!

**Comment by NGPixel** [comment]
@Smuggla No, `1.0.5` is the version of the npm package, NOT the wiki.js installation version. Use the recommended installations method as detailed in the docs and not npm.

**Comment by timonstr** [comment]
@vaindil Do you keep “enabled” for local?  It's necessary even if you use LDAP auth.
