### ISSUE TITLE
Can't view stored PDF's

### ISSUE THREAD

**Issue by count0x00** [Requarks/wiki#2010]
Dear people,

I've installed Wiki.js locally according to the Requarks instructions.
Then I've uploaded some PDF's to asset folders I've created.
The PDF's are linked by .md links like: [nl202005.pdf](/assets/elektor/nl202005.pdf)
I use the wizzard to build the link too avoid typos.
I also wrote the links myself.

When I click the link the browser starts working but nothing ever downloads.

Much appriciation !

**Comment by Smankusors** [comment]
Where is your host info?

**Comment by count0x00** [comment]
Of course, does this suffice?

Ubuntu 10.10
MariaDB 10.4.13
WikiJS 2.3.81

**Comment by count0x00** [comment]
I've followed instructions from https://docs.requarks.io/install/linux Got backup to Git working. All seems to be running OK except I haven't figure out how to access the logfiles. The logging icon in the administration area is greyed out.

**Comment by count0x00** [comment]
Got some insights

* Uploaded a 30 GB asset
* Wiki.js complained 30 GB is above the threshold defined in config.yaml
* Set the threshold from 5MB to 50 MB
* Restarted
* This new set  threshold is not reflected in the upload window. It still reads max 5 MB max 10 files
* Now it is possible to upload a 30 GB asset
* It is possible to link this asset to a page
* When clicking the link the browser waits for some minutes then quits. (0 bytes downloaded)

* Uploading assets smaller than 5 MB can be linked and accessed trough the link without any problem.

I see the latest stable removed the upload treshold from config.yaml and made it controllable from the admin pages.
Going to try 2.4.105

Best

**Comment by NGPixel** [comment]
Storing 30 GB assets directly in the wiki is really not a good idea and is very likely to cause issues. Host them in proper storage service (like AWS S3, Azure Blob Storage, etc.) and simply link to them.

Assets in a wiki are meant for images, small documents, etc, not for extremely large files.
