### ISSUE TITLE
Error message when attempting to save pages

### ISSUE THREAD

**Issue by GabImmo** [Requarks/wiki#2016]
**Describe the bug**
Hi, I set up a Wiki.js server few days ago. I didn't have any problem at first, but now, when I attempt to save pages which have been edited, I receive the following error message: GraphQL error: cannot read property 'code' of null. Also, the message "conflict" appears in the upper part of the window.
What could it be?
Thanks for your time
**To Reproduce**

**Expected behavior**

**Screenshots**

**Host Info (please complete the following information):**
 - OS: macOS Mojave 10.14.5
 - Wiki.js version: [ 2.3.81]
 - Database engine: [Percona 5.7]

**Additional context**

**Comment by Smankusors** [comment]
Can you try with Wiki.js 2.4.x?

**Comment by GabImmo** [comment]
Hi, thanks for the reply.
I tried with 2.4 version (the latest released) and Mariadb 10.3 instead of Percona 5.7, and now i'm not having that problem anymore. So i can save and edit pages.
Thanks for the support, have a good day
