### ISSUE TITLE
Automate Import from Local Repo

### ISSUE THREAD

**Issue by hexbinedit** [Requarks/wiki#2017]
**Is there a way to tell the wiki.js from the CLI to implement the "Force Sync" and "Import Everything" feature under Storage?**

We have a use case scenario where we may need to quickly rebuild content from the remote > local repository. Is it possible to do so from the CLI?

Much thanks!

Host Info:
OS: Ubuntu
Wiki.js version: 2.3.81
Database engine: postgres 12.1

**Comment by NGPixel** [comment]
No. The changes made remotely will be picked up during the scheduled sync. You can always shorten the delay between syncs.
