### ISSUE TITLE
 Error: config.yml file is not writable by Node.js process

### ISSUE THREAD

**Issue by appleramos** [Requarks/wiki#202]
Errors occurred while extracting dependencies
`ERROR: Can not create symbolic link : Access is denied.`

so when i try to run it, there's an error
`Error: ENOENT: no such file or directory, open 'C:\Users\MangoSoft 2\Documents\Sources
\wikijs\config.yml'`

**Comment by capttrousers** [comment]
I had the same error but on linux. I changed the ownership of that file to the same user as the rest of the contents of the install, as that was the only file that was owned by root. That fixed the problem, but I think in the install script, where it copies the config.sample.yml to config.yml, the command is being run as the same user as runs the install script, so when I ran it as `sudo bash install.sh` it copies the config file and sets the ownership as root.

**Comment by appleramos** [comment]
Solved this by extracting the zip file with administrator access
