### ISSUE TITLE
Tabs

### ISSUE THREAD

**Issue by raining-tr** [Requarks/wiki#2024]
Hello,

I was trying now for hours to make tabs work in the HTML editor, since the Visual and the Markdown editor didn't give me the results I wanted - so I switched over to HTML.

I tried things with CSS and HTML, from Codepen, Stackoverflow and so on, seems not to working quite. Has anyone a simple solution for this?

**Comment by NGPixel** [comment]
The Visual Editor doesn't support tabs yet. Use the [Markdown](https://docs.requarks.io/en/editors/markdown#content-tabs) or the [Raw HTML](https://docs.requarks.io/en/editors/code) editor. Both links have code examples on how to write them.

**Comment by raining-tr** [comment]
That does not work.

`
<h2 class="tabset">Tabs</h2>

<h3>First Tab</h3>
<p>Any content here will go into the first tab...</p>

<h3>Second Tab</h3>
<p>Any content here will go into the second tab...</p>

<h3>Third Tab</h3>
<p>Any content here will go into the third tab...</p>`

[https://imgur.com/dXyXMlY](url)

**Comment by raining-tr** [comment]
That does not work as intendet.

```
<h2 class="tabset">Tabs</h2>

<h3>First Tab</h3>
<p>Any content here will go into the first tab...</p>

<h3>Second Tab</h3>
<p>Any content here will go into the second tab...</p>

<h3>Third Tab</h3>
<p>Any content here will go into the third tab...</p>
```

Looks like https://imgur.com/Q2njjvT
