### ISSUE TITLE
Batch upload markdown files to create wiki web pages

### ISSUE THREAD

**Issue by snoop2head** [Requarks/wiki#2025]
## Question
* How do I batch upload markdown files to create multiple wiki pages? Markdown files does not contain any images, but are consisted with plain texts only. 
* Any wiki.js API guidelines available for importing markdown files? I've managed to find GraphQL error codes only in [official docs](https://docs.requarks.io/dev/api).

## Host Info (please complete the following information)
* OS: Linux, Docker Container from AWS Marketplace
* Wiki.js version: 2.3.81
* Database engine: PostgreSQL 11.7

**Comment by winkelement** [comment]
The easiest way would be to set up a git repository as a storage strategy then push the md. files to that repo and let Wiki.js do the snyc.

See https://docs.requarks.io/storage/git

**Comment by snoop2head** [comment]
@winkelement 
Thanks for the help! Now I imported markdown files in repository to wikipedia. 
* Github repo: https://github.com/snoop2head/wiki-js-storage
* Wiki: http://ec2-3-34-99-110.ap-northeast-2.compute.amazonaws.com/

But it seems like error to write on github repository occurs! 
> fatal: could not read Username for 'https://github.com': No such device or address
Is the "Default Author Name" section for my id(snoop2head) or my name(Young Jin Ahn) registered on github?

**Comment by winkelement** [comment]
What does your git configuration in Wiki.js looks like?
