### ISSUE TITLE
MathJax /Katex vdots do not render properly

### ISSUE THREAD

**Issue by petruccigp** [Requarks/wiki#2026]
**Describe the bug**
The vdots command displays a strange vertical bar instead of the three dots.

**To Reproduce**
1. Create a new wiki page (with math display render activated)
2. Enter as content:

```
$\vdots$
$$\vdots$$
```

**Expected behavior**
The vertical lines should be displayed instead of the strange block.

**Screenshots**

Code:
![image](https://user-images.githubusercontent.com/658179/84146933-c9593000-aa5c-11ea-8ce0-fd42d72cf46c.png)

Behavior:
![image](https://user-images.githubusercontent.com/658179/84146968-d9710f80-aa5c-11ea-90d4-5b2a1918a441.png)

**Host Info (please complete the following information):**
 - OS: Heroku deployed as WikiJS template (Linux - Alpine Linux (linux) 3.11.6 x64)
 - Wiki.js version: 2.4.105
 - Database engine: postgresql 12.3

**Comment by NGPixel** [comment]
Please post an example as text, so that it can be reproduced.

**Comment by petruccigp** [comment]
1. Create a new Markdown page
2. Enter as text the following:

```
$\vdots$
$$\vdots$$
```

3. The rendering will show up as the image I've pasted.

Please let me know if you need more directions to reproduce.

Thanks for taking a look!
