### ISSUE TITLE
{target=_blank} doens't work anymore in version 2.4.105

### ISSUE THREAD

**Issue by cjs1976** [Requarks/wiki#2027]
Hi,

in the past I could use a {target=_blank} (see https://requarks.canny.io/wiki/p/link-open-in-another-tab) at the end of a link to open the link in a new browser window.

Since I updated to version 2.4.105 the {target=_blank} at the end of a link is ignored. The link is always opened in the same briwser window.

Is this a bug, or is there any new setting or keyword I need to use?

Thanks,
Christian.

**Comment by NGPixel** [comment]
Already fixed for 2.5. Disable HTML Security module as a workaround in the meantime.
