### ISSUE TITLE
Unknown authentication strategy "jwt"

### ISSUE THREAD

**Issue by KevinGP10** [Requarks/wiki#2028]
**Describe the bug**
Sometimes when I visit my page I get the error:
Unknown authentication strategy "jwt"

**To Reproduce**
go to my page https://wiki.pretorius.family, maybe it also gives you the error.
Sometimes it doesn't, sometimes it does
not sure why... after refreshing the page, it works again

**Expected behavior**
Take me to the home page

**Screenshots**
![Snag_165c52b2](https://user-images.githubusercontent.com/65260115/84171313-f74d6d00-aa7a-11ea-9f1a-d0e9359db0d9.png)

**Host Info (please complete the following information):**
 - OS: Linux - Ubuntu (bionic) 18.04 x64
 - Wiki.js version: 2.3.81
 - Database engine: PostgreSQL 11

**Additional context**

**Comment by NGPixel** [comment]
Happens when you load the site before the server is done initializing. Only occurs when starting the server the first time.

If you get the error regularly, then your server may be crashing or restarting randomly.

**Comment by KevinGP10** [comment]
Ok, yeah it is a cloud instance that scales to zero if it is not being used. That explains it then.

Thank you.

**Comment by palicea** [comment]
Hey @NGPixel, if you add require('./passport')(passport) on the server\controller\auth.js file it will solve the problem when loading wiki site for the first time.
