### ISSUE TITLE
CAS, OpenID Connect, and OAuth2 authentication sources are broken

### ISSUE THREAD

**Issue by Maffsie** [Requarks/wiki#2030]
**Describe the bug**
Despite seemingly being fully functional, the Generic OpenID Connect, Generic OAuth2 and CAS authentication sources appear as disabled.

**To Reproduce**
1. On a fresh install of Wiki.js, log in as administrator
2. Load the Administrator interface
3. On the left-hand side, click Authentication under Modules
4. Observe that Generic OpenID Connect is not selectable

**Expected behavior**
OpenID Connect, OAuth2 and CAS would be available.

**Host Info:**
 - OS: Docker, `requarks/wiki:2`
 - Wiki.js version: 2.4.105
 - Database engine: postgres 11

**Additional context**
It appears that these authentication sources in particular are missing the `isAvailable` property in their `definition.yml` files. When the client application queries for available authentication sources via GraphQL, these missing properties are normalised to `null`, which is treated as `false`, resulting in the authentication sources being unavailable.

**Comment by NGPixel** [comment]
They are simply not yet available.
