### ISSUE TITLE
LDAP Search Failing Due To Spaces Inserted In baseDN

### ISSUE THREAD

**Issue by dimicha** [Requarks/wiki#2032]
**Describe the bug**
When the LDAP baseDN contains multiple "dc" parts, when the wiki attempts to search, it inserts spaces between each of the "dc" values. IE. dc=dimi,dc=id,dc=au becomes dc=dimi, dc=id, dc=au when an LDAP search is performed.
**To Reproduce**
Configure LDAP in wiki.js with a baseDN with multiple "dc" values ie. dc=dimi,dc=id,dc=au

**Expected behavior**
The baseDN should not have spaces inserted between "dc" values when an LDAP search is performed.

**Screenshots**
LDAP configuration:
![image](https://user-images.githubusercontent.com/24503930/84244077-b6665e80-ab35-11ea-844d-e3fcda340fc2.png)

**Host Info (please complete the following information):**
 - OS: Ubuntu 18.10
 - Wiki.js version: 2.4.105
 - Database engine: psql (PostgreSQL) 10.9 

**Additional context**
LDAP logs when a user attempts to login using LDAP auth in wiki.js:

`Jun 10 08:11:14 glauth glauth64: 08:11:14.548006 Bind ▶ DEBU 00a Bind request: bindDN: cn=serviceuser,ou=svcaccts,dc=dimi,dc=id,dc=au, BaseDN: dc=dimi,dc=id,dc=au, source: 192.168.0.14:59960
Jun 10 08:11:14 glauth glauth64: 08:11:14.548090 Bind ▶ DEBU 00b Bind success as cn=serviceuser,ou=svcaccts,dc=dimi,dc=id,dc=au from 192.168.0.14:59960
Jun 10 08:11:14 glauth glauth64: 08:11:14.549959 Search ▶ DEBU 00c Search request as cn=serviceuser,ou=svcaccts,dc=dimi,dc=id,dc=au from 192.168.0.14:59960 for (uid=dimicha)
Jun 10 08:11:14 glauth glauth64: 2020/06/10 08:11:14 handleSearchRequest error LDAP Result Code 50 "Insufficient Access Rights": Search Error: search BaseDN dc=dimi, dc=id, dc=au is not in our BaseDN dc=dimi,dc=id,dc=au`

If the baseDN is just dc=dimi.id.au then (and LDAP configuration is changed to match) then then it works fine:
`Jun 10 08:25:05 glauth glauth64: 08:25:05.046776 Bind ▶ DEBU 008 Bind request: bindDN: cn=serviceuser,ou=svcaccts,dc=dimi.id.au, BaseDN: dc=dimi.id.au, source: 192.168.0.14:60280
Jun 10 08:25:05 glauth glauth64: 08:25:05.046874 Bind ▶ DEBU 009 Bind success as cn=serviceuser,ou=svcaccts,dc=dimi.id.au from 192.168.0.14:60280
Jun 10 08:25:05 glauth glauth64: 08:25:05.048508 Search ▶ DEBU 00a Search request as cn=serviceuser,ou=svcaccts,dc=dimi.id.au from 192.168.0.14:60280 for (uid=dimicha)
Jun 10 08:25:05 glauth glauth64: 08:25:05.048611 Search ▶ DEBU 00b AP: Search OK: (uid=dimicha)
Jun 10 08:25:05 glauth glauth64: 08:25:05.050783 Bind ▶ DEBU 00c Bind request: bindDN: cn=dimicha,ou=admin,dc=dimi.id.au, BaseDN: dc=dimi.id.au, source: 192.168.0.14:60282
Jun 10 08:25:05 glauth glauth64: 08:25:05.050875 Bind ▶ DEBU 00d Bind success as cn=dimicha,ou=admin,dc=dimi.id.au from 192.168.0.14:60282`

If you need any clarification or more info, please let me know.

**Comment by dimicha** [comment]
@Diorso666 
> Spaces can cause issues with openldap if they are not escaped properly.

Sure, but that's not what the problem is. There are no spaces in the baseDN entered into configuration. Refer to the screenshot for this. 

> To avoid issues, enclose the entire BINDDN with single quote

There is no issue with the bindDN, wiki.js can bind with out issues (see logs), the issue is with the baseDN. Enclosing the baseDN with single quotes just breaks it even more. Wiki.js can bind but then doesnt perform a LDAP search and the user is left with a loading message until it times out.

`
Jun 11 00:23:19 glauth glauth64: 00:23:19.568779 Bind ▶ DEBU 010 Bind request: bindDN: cn=serviceuser,ou=svcaccts,dc=dimi.id.au, BaseDN: dc=dimi.id.au, source: 192.168.0.14:53854
Jun 11 00:23:19 glauth glauth64: 00:23:19.568877 Bind ▶ DEBU 011 Bind success as cn=serviceuser,ou=svcaccts,dc=dimi.id.au from 192.168.0.14:53854

`
I appreciate the input, but what you are talking about isn't the issue I am having here.

**Comment by NGPixel** [comment]
All options are passed as-is to the passport-ldapauth module. Open a ticket with them instead: https://github.com/vesse/passport-ldapauth
