### ISSUE TITLE
Github repository filesystem location

### ISSUE THREAD

**Issue by GabImmo** [Requarks/wiki#2034]
**Question**
Hello,
I'd like to know, for backup purposes, if there is a place in the wiki working directory where I can find info about the Github repository that I specified in the Storage section of the program. 
Thanks for your time
**Host Info (please complete the following information):**
OS: [Debian 9]
Wiki.js version: [2.4]
Database engine: [Mariadb10.3]

**Comment by winkelement** [comment]
![Bildschirmfoto 2020-06-10 um 13 12 14](https://user-images.githubusercontent.com/3525191/84261536-37186100-ab1c-11ea-875f-aa9132c8e90d.png)

**Comment by GabImmo** [comment]
Thanks! I didn't think about checking if there were hidden files in the directory. Now I've found what I was looking for in ./data/repo/.git/config
Thanks again and have a good day
