### ISSUE TITLE
Receiving Unauthorized message for all users after upgrade from 2.0.12 to 2.1.113

### ISSUE THREAD

**Issue by godambrosio** [Requarks/wiki#2046]
**Describe the bug**
After upgrade from 2.0.12 to 2.1.113 I receive Unauthorized error each time that I want to edit a page with an not admin user.

Note: I'm using wikijs as a docker stack

**To Reproduce**
1. Upgrade from 2.0.12 to 2.1.113
2. Login as Non admin user
3. Try to some page
4. You receive Unauthorized page

**Expected behavior**
You can edit and save the page

**Screenshots**

**Host Info (please complete the following information):**
 - OS: Ubuntu 18.04
 - Docker version: 19.03.9
 - Wiki.js version: 2.0.12
 - Database engine: postgres-11

**Additional context**
Running wikijs as a swarm stack (Docker)

**Comment by Smankusors** [comment]
Are you sure already "logged in"? There's case where you see already logged in, but it's only on your browser, while server denied you because you are actually not logged in.

Btw if you use incognito mode, do the message appear again?

**Comment by winkelement** [comment]
Check and revise your permissions and page rules for that user group.

**Comment by godambrosio** [comment]
Thanks for your help

@Smankusors  yes I even tried to log out and logging several times, I also tried to create a new group with all the content permissions given but I'm having the same error.

@winkelement  yes I checked all the permissions, all the content permissions are given for this group

I will try to reproduce it from scratch with an empty instance of wikijs.

**Comment by winkelement** [comment]
You absolutely sure you also set the correct **page rules**?

**Comment by godambrosio** [comment]
@winkelement  I didn't set any page rule.

I tried with a totally new environment from scratch and I'm receiving the new behavior when update from 2.0.12 to 2.1.113.
![imagen](https://user-images.githubusercontent.com/8494720/84755394-e8f2da00-afc1-11ea-9920-ce89059c9af7.png)

**Comment by Smankusors** [comment]
you need to correctly set the page rules first.

**Comment by godambrosio** [comment]
@Smankusors  thanks for your answer but I don't understand.
I have one user that have all the content's permissions 
![imagen](https://user-images.githubusercontent.com/8494720/84771674-1e0b2680-afda-11ea-971d-1d5d607dd8a7.png)
 
After that I have one user assigned to this group, when I try to edit one page with this user:
- It works in version 2.0.12
- It doesn't work in all newest versions

Why I didn't set page rules first and now I need to do it ? This is a new functionality ?

**Comment by winkelement** [comment]
Image it like this: You specified **WHAT** the user(group) can do in general (permissions) but also you have to specify **WHERE** the user(group) can do that (page rules).

And i think you are correct in early 2.x release you did not have to explicitly set the page rules but now you have to. 
Although i can understand it might seem a little laborious at first if you think about it and dig into it it really gives you a great level of flexibility for your access rights settings IMO.

**Comment by godambrosio** [comment]
@winkelement thanks, now it works.
