### ISSUE TITLE
Logo Fitting issue

### ISSUE THREAD

**Issue by oshybrid** [Requarks/wiki#2048]
No matter how I resize the company logo, it keeps showing truncated (the exact same way).  See the enclosed pic for an example.  The site says it supports 34 x 34 or bigger, but what is the top end px size limits?  Yes, I did say apply after each resizing.  It shows the same truncated logo in the top left.

<img width="678" alt="2020-06-11_17-18-08" src="https://user-images.githubusercontent.com/44711163/84451650-89cf4700-ac08-11ea-8540-118fdef6e1ca.png">

**Comment by Smankusors** [comment]
I guess your image is not in square ratio, it's stated on the description there.

**Comment by oshybrid** [comment]
Yup you are right, sorry about that

**Comment by Smankusors** [comment]
If your issue is resolved, feel free to close this issue 🙂
