### ISSUE TITLE
"Missing or invalid email address from profile." when having multiple E-Mail addresses in LDAP Profile

### ISSUE THREAD

**Issue by jonasjoest** [Requarks/wiki#2050]
**Describe the bug**
Logging in via LDAP Strategy throws an error "Missing or invalid email address from profile." when logging in with an LDAP profile that has multiple email addresses in it's mail-attribute.

**To Reproduce**
1. Go to login page
2. Click on 'login via LDAP / Active Directory'
3. login with user that has multiple email addresses

**Expected behavior**
Log-In succeeds, uses first (primary) email address

**Screenshots**
![image](https://user-images.githubusercontent.com/41778330/84483637-eaf32b00-ac99-11ea-839c-f1e8d894c4f3.png)

**Host Info (please complete the following information):**
 - OS: Ubuntu, Docker
 - Wiki.js version: 2.5.8
 - Database engine: postgres 11

**Additional context**
Using FreeIPA as LDAP Server

**Comment by Smankusors** [comment]
hmm isn't the mapping field capable for array indexing? like "email[0]"?

**Comment by jonasjoest** [comment]
well it returns a comma separated list of e-mail addresses

**Comment by jonasjoest** [comment]
ah... now I understand what you mean... Trying this out, one moment...

**Comment by jonasjoest** [comment]
you're right, the field accepts array indexing if the mail field is actually an array.

So `email: _.get(profile, conf.mappingEmail, '')[0]` would work as long as there are multiple email addresses assigned.
But this doesn't work if there is only one email address assigned, since array indexing on a string returns the corresponding char.

So either there needs to be some kind of type check or you convert it to a string and split.
It's just a matter of code style. I personnaly have no preference.

What do you think?

**Comment by Smankusors** [comment]
IMO, I think it's better with currently implemented. But this thing needs to be written in the documentation.

Better ask the developer anyways 😅 @NGPixel

**Comment by mleone87** [comment]
mail attribute is multi-value, so it should always managed as that :)

https://ldapwiki.com/wiki/0.9.2342.19200300.100.1.3

**Comment by NGPixel** [comment]
Fixed by #2051
