### ISSUE TITLE
Port problems

### ISSUE THREAD

**Issue by TancsicsGergely** [Requarks/wiki#2052]
**Question**
Recently I have installed Wiki.js and set it up, but I can't get it working in the meaning of the URL. When I start it, it stars on the 3000 port (I have apache installed as well so I can't use the 80). I can't make an A record (not supporting port). Now, the only way to access the wiki is if I go to the IP then put :3000 after it which I don't want to do. Any solutions/ideas?

**Host Info**
OS: Ubuntu 20.04
Wiki.js version: 2.4.105
Database engine: MySql 8.0.20

**Comment by winkelement** [comment]
Check out how to setup your apache as a reverse proxy.

https://httpd.apache.org/docs/2.4/howto/reverse_proxy.html

https://www.digitalocean.com/community/tutorials/how-to-use-apache-as-a-reverse-proxy-with-mod_proxy-on-ubuntu-16-04

**Comment by TancsicsGergely** [comment]
Thanks, I'll take a look

**Comment by Smankusors** [comment]
if your issue is resolved, feel free to close this one 🙂

**Comment by MagnumDingusEdu** [comment]
Would it be possible to add this to the docs under the "Installation" section, with guides for both nginx and apache ?
I'd like to work on it, if it's okay.

**Comment by winkelement** [comment]
IMO this is out of scope of the Wiki.js documentation but would be the exact use case for a community tutorial as proposed here https://requarks.canny.io/wiki/p/tutorials-section-in-docsrequarksio
