### ISSUE TITLE
Nedd help in configuring elasticsearch on Wiki.js

### ISSUE THREAD

**Issue by AkhilaGarlapally** [Requarks/wiki#2053]
**Question**
Describe in details what you are trying to achieve and where do you need guidance.

**Host Info (please complete the following information):**
OS: [e.g. Ubuntu 18.04, Docker]
Wiki.js version: [e.g. 2.0.1]
Database engine: [e.g. postgres 9.7, mysql 5.7]

**Comment by Smankusors** [comment]
what is your question and host info?

anyway how about [the documentation](https://docs.requarks.io/en/search/elasticsearch)?
