### ISSUE TITLE
LDAP Login Overwrites Fields Set by User on Profile

### ISSUE THREAD

**Issue by andybond006** [Requarks/wiki#2054]
**Describe the bug**
If a user logs in using LDAP / AD Authentication, and self-registration is turned on, the user is added to the wiki properly with the fields populated as set in the LDAP mapping. 

However, at our organization our `displayName` field has our names in the format "Bond, Andy (ORG)". Due to users not having images set in AD, our "avatar" image appears as a circle with "B(" instead of nicer initials. Some of our users tried to fix that by editing their display name through the wiki interface, but we have found that it gets overwritten by LDAP each time they log in.

**To Reproduce**
1. Go in for first time with LDAP
2. Edit Profile to have a different name than is stored in LDAP
3. Log out
4. Log back in, your custom name will be replaced by what is in LDAP

**Expected behavior**
I think the correct behavior would be to do exactly what it is currently doing but only on user creation. After that, it should respect the user's settings. It would be nice if the user could change their avatar image as well and ignore the LDAP one (especially if there is no LDAP one). It would be an added bonus if you could click a "reset to default" for the user to overwrite the settings manually with what LDAP contains.

**Host Info (please complete the following information):**
 - OS: Docker
 - Wiki.js version: 2.4.105
 - Database engine: postgres 11.8

---

Awesome wiki, by the way. We're hopefully going to fully switch to it from DokuWiki. Just a few features missing from ones we liked on DokuWiki. Thanks for your hard work!

**Comment by whitbur** [comment]
I can validate that this happens for the Discord authentication strategy as well. This potentially affects all non-local strategies.

**Comment by NGPixel** [comment]
This is actually by design so that the login provider is the source of truth for user profile data (e.g. you login with Google, you expect that any change to your google account (e.g. your name or profile picture) will reflect in Wiki.js).

But I can see there's a case where you don't want this behavior and it could be added as an option in the admin settings.

Can you create a feature request on https://requarks.canny.io/wiki to that its easier to keep track?

**Comment by andybond006** [comment]
Created a feature request: https://requarks.canny.io/wiki/p/overwrite-profile-fields

Thanks for the great work! Excited for v3!
