### ISSUE TITLE
Context-based occurrence research / page section redirecting

### ISSUE THREAD

**Issue by GabImmo** [Requarks/wiki#2055]
**Question**
Hello,
I'd like to know if there's a way to configure the Wiki so that when I search for a match between a word that I give in input with a page which contains that word, I can also obtain as a result the specific context (like obtaining the line in which the word is contained + the upper line).
Also, I wonder if there's a way to obtain an automatic redirection to the specific section of the page in which the word I give as input is contained.
I explored the Database-PostgreSQL Search Engine a bit, and for what I could see the differences between that and the default one are the Content-based research, the "maybe you were looking for" utility, and the automatic input correction when searching for a word. Is that correct or I missed something?
Thanks for your time 
**Host Info (please complete the following information):**
OS: [Debian 9]
Wiki.js version: [2.4]
Database engine: [postgres 9.6]

**Comment by NGPixel** [comment]
This is not possible at the moment. Add your vote to this [feature request](https://requests.requarks.io/wiki/p/detailed-search).
