### ISSUE TITLE
All pages page?

### ISSUE THREAD

**Issue by mikosullivan** [Requarks/wiki#2059]
**Question**
Is there a way to have a page that lists all pages? I've seen some vague references to such a feature but can't actually figure out how to do it. I don't want to list all the pages in the left hand sidebar, I just want that sidebar to have a link to the all-pages page.

**Host Info (please complete the following information):**
OS: Ubuntu 18.04, Docker
Wiki.js version: 2.4.107
Database engine: 11.7

**Comment by NGPixel** [comment]
There's no "All Pages" in 2.0. This functionality is replaced with a browse sidebar navigation. Assuming you enabled "Custom Navigation" in Admin > Navigation, you'll get a "Browse" button in the sidebar which lets you browse all the pages on the site. Or select the "Site Tree" option to show that feature at all times.

**Comment by mikosullivan** [comment]
Ah ha! Got it. Thanks! Perhaps the screen from custom navigation could include a picture of what the top part of a custom navigation would look like.
