### ISSUE TITLE
Create pidfile to monitor service with monit (or any other service watcher)?

### ISSUE THREAD

**Issue by vizcay** [Requarks/wiki#206]
I've installed WikiJS in a VPS for my organization and I want to monitor it with monit, the tool I usually use to watchdog my services and ruby applications (I'm not a node developer so forgive my ignorance about how this is handled in the node server world).

I've looked for some way to start wiki.js with a pidfile parameter (standard practice for services) to configure monit to watch for it and restart if needed, but still no luck. As far as I can see, there is some overlaping with the pm2 module but not sure exactly how much.

Why I want to use monit? well because is a tool that I know and just works with different technologies (C, Ruby, Python etc), so I don't want to spend time learning something new that does exactly the same just for the node world.

**Comment by NGPixel** [comment]
Use `node server` to start Wiki.js without pm2.  You can create a standard service which calls this command, effectively bypassing pm2 management.

**Comment by vizcay** [comment]
@NGPixel yes I understand how to start / stop wikijs.. but I need a PID file to monitor it effectively. That's standard practice with any service in the linux world and the main way for services watchdogs to work.. no way to create one?

**Comment by vizcay** [comment]
Okey, fair enough.. to resume to only way to get a pidfile is through pm2.
