### ISSUE TITLE
internal/modules/cjs/loader.js:969   throw err;

### ISSUE THREAD

**Issue by abkiwi9** [Requarks/wiki#2061]
**Question**
Describe in details what you are trying to achieve and where do you need guidance.

**Host Info (please complete the following information):**
OS: [e.g. Ubuntu 18.04, Docker]
Wiki.js version: [e.g. 2.0.1]
Database engine: [e.g. postgres 9.7, mysql 5.7]

**Comment by abkiwi9** [comment]
Hi, trying to install and get wiki.js working as a standard install as follows:

OS: uBUNTU 18.04 (Apache2)
Wiki.js version: 2.4.107
Database engine: MariaDB 10.3.23
Node.js 1218.0 & npm 6.14.5

I am at the instruction stage #6 Run Wiki.js "node server"

root@vmi398904:~# node server
internal/modules/cjs/loader.js:969
  throw err;
  ^
**Error: Cannot find module '/root/server'**
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

I have tried everything I know to fix this but not working, does anyone know how to make this work?

Thanks
Regards
Aaron

**Comment by Smankusors** [comment]
Hmm I have questions...

1. Why logged in as root?
2. Is /root/server exists?
3. What is Node.js 1218.0? That version didn't exist yet. Do you mean 12.18.0?

FYI, you can edit your posts/comments instead of creating new comments.

**Comment by winkelement** [comment]
You need to run this command **in the directory where you installed Wiki.js**. [See step 2](https://docs.requarks.io/install/linux) `cd ./wiki`.
Then run `node server`.

**Comment by abkiwi9** [comment]
Thanks got it, was not paying to much attention to the directory :)
