### ISSUE TITLE
Markdown URL syntax being autocompleted by a path to another page

### ISSUE THREAD

**Issue by pavemina** [Requarks/wiki#2062]
**Describe the bug**
When typing the syntax for links in markdown (`[name](url)`), the editor keeps pasting in a path to a different page in the wiki (always the same).
More specifically this happens whenever after a closing bracket `]` I type an opening parenthesis `(`. It does not need to be typed immediately in a sequence, for example typing a word after `]`, deleting it, and then typing `(` produces the same result.

**To Reproduce**
1. Edit page in markdown
2. Start typink a link: `[blabla]`
3. Continue with open parenthesis `[blabla](`
4. Parenthesis immediately replaced with a path to another page and a closing parenthesis, e.g.:
`[blabla]/some/other/page)`

**Expected behavior**
Markdown editor shouldn't autocomplete link syntax with a "random" page path.

**Host Info (please complete the following information):**
 - OS: Docker on Arch linux
 - Wiki.js version: 2.4.107 (issue was also present in 2.3.77, not sure if before that)
 - Database engine: postgresql 12.1

**Additional context**
Additional things tested below. Issue persists even if:
- tried in a different page, even created a new one (happens with any)
- tried with different keyboard layout/language
- tried in chrome incognito
- tried in a different browser (tested Chrome and Firefox)
- tried on a different PC
- tried with freshly created user account
- tried with all cookies deleted

When I rename (move) the /path that keeps inserting itself, the path in the unexpected "auto-completion" also changes to that.

I honestly hope that it's just something stupid, so I'd be happy to be educated that it's just something weird I somehow enabled somewhere.

**Comment by ParkHost** [comment]
got same issue here

**Comment by greenitthe** [comment]
Same issue. Generates links like "[example]/home)", which in my case is my ID 1 page.

OS: Linux - Ubuntu (bionic) 18.04 x64
Wiki JS: 2.5.132
Node: 12.18.3
Database engine: PostgreSQL 10.14

**Comment by peteruithoven** [comment]
If I understand it this was fixed in #2452 right? So this one could be closed?

**Comment by NGPixel** [comment]
Correct
