### ISSUE TITLE
 Moving the panel to the other side

### ISSUE THREAD

**Issue by Scrik** [Requarks/wiki#2064]
**Question**
Can this panel be moved to the right side? And how to do it?
![image](https://user-images.githubusercontent.com/5807097/84764759-e353bf00-afd6-11ea-91cb-b89597030ff7.png)

**Host Info (please complete the following information):**
OS: Centos 7
Wiki.js version: Stable 2.4.107
Database engine: postgres 11

**Comment by Smankusors** [comment]
currently, no.

but, you can inject your own CSS rules via theme menu

**Comment by Scrik** [comment]
Can you tell me how to do this through CSS?

**Comment by Scrik** [comment]
please, help
