### ISSUE TITLE
Port XX is already in use! / Listening on port XX requires elevated privileges!

### ISSUE THREAD

**Issue by jezzaleong** [Requarks/wiki#2065]
Hi. I'm trying to install wiki.js on Windows 10, but I'm running into problems.

I try to launch the site in powershell by entering "node server", and it connects to the database, however, when I use postgres, it gives me the error of "Port XX is already in use". I have changed the postgres port to many different random ones and it returns the same error so I don't think it's because the port is being used by something else.

I have also tried with mysql and mariadb which give me a different error of saying "Listening on port XX requires elevated privileges!" no matter what port I assign it. I have tried to allow the port with windows firewall and have run powershell in administrator but nothing seems to work.

I'd massively appreciate some help!

-----
OS: Windows 10
Wiki.js version: 2.4.107
Database engine: latest versions of postgres, mysql, mariadb
![Capture](https://user-images.githubusercontent.com/12214374/84778744-56f7cb00-afdb-11ea-85c9-56970fe7f7bf.PNG)

**Comment by Smankusors** [comment]
you already have other application run at port 5432. Please use other port instead.

Look who is using 5432 by looking at Network > Listening Ports from Resource Monitor.

**Comment by winkelement** [comment]
`5432` is your postgres db port it seems. So the node http server can not use it. Change your http port to something like 3000. See https://docs.requarks.io/install/config

**Comment by jezzaleong** [comment]
> `5432` is your postgres db port it seems. So the node http server can not use it. Change your http port to something like 3000. See https://docs.requarks.io/install/config

Thank you so much! I got confused and thought that both "ports" in the config.yml file had to be identical.
