### ISSUE TITLE
Docker Container: 404 js/prism/prism-cisco.min.js

### ISSUE THREAD

**Issue by selloween** [Requarks/wiki#2066]
I'm running wiki.js in a Docker container using the latest image from DockerHub: `requarks/wiki:latest` 

I'm getting a 404  for `js/prism/prism-cisco.min.js` resulting in Cisco Syntax highlighting not working. View screenshot containing the console output of Chrome. 

![404-cisco-prism-js](https://user-images.githubusercontent.com/35191120/84783838-ec01c080-afe9-11ea-843a-f7813ca60cc7.PNG)

**Comment by NGPixel** [comment]
cisco is not a valid language:
https://prismjs.com/#supported-languages

**Comment by selloween** [comment]
Thx. I did not realize until now that `prism-cisco.min.js` wasn't a acctual file.
