### ISSUE TITLE
Link to Windows shares

### ISSUE THREAD

**Issue by saschafiedler** [Requarks/wiki#2068]
**Question**
Hi!
I could swear I read somewhere that Wiki.js supports linking to Windows shares/UNC. But how can I activate it or link to a folder? Or is it not possible after all?

Cheers!

**Host Info:**
OS: CentOS (core) 7.8.2003 x64
Wiki.js version: 2.4.105
Database engine: 10.3.23-MariaDB

**Comment by NGPixel** [comment]
See my reply in Slack.
