### ISSUE TITLE
Visual Editor.  Thumbnails ?

### ISSUE THREAD

**Issue by Scrik** [Requarks/wiki#2069]
**Question**

How to make miniature images inserted into the article, and when you click on the image a large picture appears?

**Host Info (please complete the following information):**
OS: Centos 7
Wiki.js version: Stable 2.4.107
Database engine: postgres 11

**Comment by sbonaime** [comment]
It is not possible and not planned. 

But you can  vote for this feature here
https://requarks.canny.io/wiki/p/images-and-galleries

or create a new feature request
https://requests.requarks.io/wiki

**Comment by Scrik** [comment]
i voted "yes"
https://requarks.canny.io/wiki/p/images-and-galleries
