### ISSUE TITLE
any  one packge for all deploy method?

### ISSUE THREAD

**Issue by zhang98722** [Requarks/wiki#207]
in my product enviroment
the server cant reach internet
so i have to upload some offline packge to the server and run it
i think i can install the dependency but i dont know how to install wiki.js

**Comment by zhang98722** [comment]
i read the .sh file,seems its not that hard~

**Comment by NGPixel** [comment]
1. Download the `wiki-js.tar.gz` and `node_modules` packages from https://github.com/Requarks/wiki/releases
2. Extract `wiki-js.tar.gz` to `./`
3. Extract `node_modules.tar.gz` to `./node_modules`
4. Rename `config.sample.yml` to `config.yml`
5. Edit `config.yml` and set proper values.
6. Start Wiki.js `node wiki start`
