### ISSUE TITLE
Delete page with comments fails with error 

### ISSUE THREAD

**Issue by ptptakakumum001** [Requarks/wiki#2078]
**Describe the bug**
Trying to delete a page fails with error:
`delete from "pages" where "id" = $1 - update or delete on table "pages" violates foreign key constraint "comments_pageid_foreign" on table "comments"`

**To Reproduce**
1. Administrator. Create a new page
2. User. Make a comment
3. Administrator. Try to delete the page

**Expected behavior**
Page should be deleted without error.

**Host Info (please complete the following information):**
 - OS: Debian
 - Wiki.js version: 2.4.105
 - Database engine: PostgreSQL 11.7

**Comment by ptptakakumum001** [comment]
Similar task: https://github.com/Requarks/wiki/issues/1119

**Comment by Smankusors** [comment]
> Similar task: #1119

yeah it's already fixed. Please update your Wiki.js version. 🙂

**Comment by ptptakakumum001** [comment]
> yeah it's already fixed. Please update your Wiki.js version. slightly_smiling_face

What version is fixed? I have a 105 version, and the last one is 107.

**Comment by NGPixel** [comment]
Please write the correct version. You most likely mean 2.4.105. 105 is simply the build number, not the full version.

**Comment by ptptakakumum001** [comment]
> Please write the correct version. You most likely mean 2.4.105. 105 is simply the build number, not the full version.

by package.json
`  "name": "wiki",
  "version": "2.4.105",`

**Comment by ptptakakumum001** [comment]
Guys?

**Comment by NGPixel** [comment]
@ptptakakumum001 Please **READ** this page before posting these kind of comments:
https://docs.requarks.io/releases/about

**Comment by ptptakakumum001** [comment]
> @ptptakakumum001 Please **READ** this page before posting these kind of comments:
> https://docs.requarks.io/releases/about

Sorry, I didn’t know that you were alone.
