### ISSUE TITLE
Line number larger than 1000 are cut off in code blocks.

### ISSUE THREAD

**Issue by MagnumDingusEdu** [Requarks/wiki#2079]
**Describe the bug**
Large line numbers are cut off in code blocks

**To Reproduce**
1. Make a code block more than 999 lines in length.
2. The thousandth's digit is partially cut off, and rest of the digits to the left are totally cut off. 

**Expected behavior**
The line number column should expand in width when line numbers increase.

**Screenshots**

e.g. the "3" is partially cut off. 
![image](https://user-images.githubusercontent.com/55412084/84955130-51ea6700-b114-11ea-80af-18124f91ca3b.png)

**Host Info (please complete the following information):**
 - OS: Linux - Ubuntu (bionic) 18.04 x64
 - Wiki.js version: 2.4.105
 - Database engine: postgres 10.12
 - Node js : 12.18.0

**Comment by NGPixel** [comment]
Code blocks are not really meant to display that many lines of code... Maybe consider linking directly to the source code in a code repository instead...

**Comment by MagnumDingusEdu** [comment]
Okay , Will do. Thank you !
