### ISSUE TITLE
ERROR 502: Proxy Error.

### ISSUE THREAD

**Issue by CraftingGamerTom** [Requarks/wiki#2080]
**Describe the bug**
There is an issue setting up the docker image to properly redirect to secure (443) from (80) and display the site

**To Reproduce**
1. Create configuration file (environment vars) [Info from https://docs.requarks.io/install/docker ]
`nano /path/example.env`
```
DB_TYPE=postgres
DB_HOST=XXX.XXX.XXX.XXX
DB_PORT=5432
DB_USER=user
DB_PASS=password
DB_NAME=wiki_db_name
#DB_SSL=true
#DB_SSL_CA=
#DB_PASS_FILE=

SSL_ACTIVE=true
LETSENCRYPT_DOMAIN=wiki.example.com
LETSENCRYPT_EMAIL=example@domain.com
```

2. Set Apache conf ( `/etc/apache2/sites-available/000-default.conf` )
```
<VirtualHost *:80>
        ServerName wiki.example.com

# FOR TESTING
#        ProxyPreserveHost On
#        ProxyPass               "/" "http://localhost:3001/" timeout=600 connectiontimeout=600
#        ProxyPassReverse      "/" "http://localhost:3001/"


        RewriteEngine On
        RewriteCond %{SERVER_PORT} !443
        RewriteRule ^(/(.*))?$ https://%{HTTP_HOST} [R=301,L]

</VirtualHost>

<VirtualHost *:443>
        ServerAdmin example@domain.com

        ServerName wiki.example.com
        Header always set Strict-Transport-Security "max-age=63072000; includeSubdomains; preload"

        <Proxy *>
            Require all granted
        </Proxy>

        SetEnv proxy-nokeepalive 1
        SetEnv proxy-initial-not-pooled 1

        ProxyPreserveHost On
        ProxyRequests Off
        ProxyVia Full
        ProxyPass               "/" "http://localhost:4001/"
        ProxyPassReverse      "/" "http://localhost:4001/"

        SSLEngine On
        SSLCertificateFile /etc/letsencrypt/live/wiki.example.com/fullchain.pem
        SSLCertificateKeyFile /etc/letsencrypt/live/wiki.example.com/privkey.pem
        Include /etc/letsencrypt/options-ssl-apache.conf
 </VirtualHost>
```

3. Run a docker command to start the service and set the ports
```
docker run -d -p 3001:3000 -p 4001:3443 --name wiki --restart unless-stopped --env-file /path/example.env requarks/wiki:2.4.107
```

**Expected behavior**
Access the website in a secure way (SSL). Site should show up with no Proxy error.

**Screenshots**
wget (ignoring ssl) on local machine via `localhost` (4001 is pointing to the port set up for docker 3443 or whatever it is for wiki.js - I know the port is fine for my implementation)
```
user@server:~$ wget --no-check-certificate https://localhost:4001/login
--2020-06-18 01:01:10--  https://localhost:4001/login
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:4001... connected.
WARNING: no certificate subject alternative name matches
        requested host name ‘localhost’.
HTTP request sent, awaiting response... 200 OK
Length: 1714 (1.7K) [text/html]
Saving to: ‘login’

login                                                  100%[===========================================================================================================================>]   1.67K  --.-KB/s    in 0s      

2020-06-18 01:01:10 (309 MB/s) - ‘login’ saved [1714/1714]
```

wget (ignoring ssl) on local machine via actual URL
```
--2020-06-18 01:26:27--  https://wiki.example.com/
Resolving wiki.example.com (wiki.example.com)... XXX.XXX.XXX.XXX
Connecting to wiki.example.com (wiki.example.com)|XXX.XXX.XXX.XXX|:443... connected.
HTTP request sent, awaiting response... 502 Proxy Error
2020-06-18 01:26:27 ERROR 502: Proxy Error.
```

From client (different computer)
![image](https://user-images.githubusercontent.com/10101712/84982216-37a88d00-b104-11ea-976a-9e9ade86b21d.png)

**Host Info (please complete the following information):**
 - OS: Ubuntu 16.04 Server
 - Wiki.js version: 2.4.107
 - Database engine: postgres

**Additional context**
Possibly relates to #1803 

I did at one point have access to the `http` version (apache settings did not redirect - see FOR TESTING section) but now even with that set up I cannot get to the `http` version because I believe I set wiki.js to redirect to the ssl version for me. It seems to work but of course I have a Proxy issue.

**Comment by Smankusors** [comment]
> I did at one point have access to the http version (apache settings did not redirect - see FOR TESTING section) but now even with that set up I cannot get to the http version because I believe I set wiki.js to redirect to the ssl version for me. It seems to work but of course I have a Proxy issue.

Hmm... You don't need to enable SSL on Wiki.js if you will use apache2 as reverse proxy

**Comment by NGPixel** [comment]
remove SSL_ACTIVE and LETSENCRYPT env variables. Your reverse proxy is already handling SSL termination.

**Comment by CraftingGamerTom** [comment]
I did that and recreated the container (stop, rm, start) just to be safe. Same result.

Decided to wipe delete all tables in `public` and reinstall accessing through port 80 (http). I also removed the redirect in my apache conf and changed it to allow connecting over 80 (To test and try connecting to the set up page)

On the install page, once I hit install I receive an error popup "Couldnt fetch resource" (or similar) the page is stuck there forever (I believe, waited awhile) and after that i can no longer access port 80 and 443 continues to get a Proxy Error page (opened in other tabs still waiting for page to finish setting up the site - 'initializing'). (I did this twice. Once I gave the site url with "https" the next time I did "http" same result both times)

Is something not clearing? I have also cleared my firefox cache. Chrome and Firefox both seem to cache the redirect

**Comment by CraftingGamerTom** [comment]
I'm just a dumb dumb :laughing: 

Once SSL env vars are removed / commented out from the `env` file I needed to update my apache config to properly point the 443 port to 3001 (as I custom defined above) rather than 4001 since the Wiki.js server was no longer handling SSL traffic

This is all set. Thanks for the help guys!!
