### ISSUE TITLE
Too similar colours for LDAP and Local strategies and unnoticeable shadow

### ISSUE THREAD

**Issue by NickKaramoff** [Requarks/wiki#2081]
**Describe the bug**
When both Local and LDAP strategies are present, it's super hard to recognize, which one is currently selected, especially considering their very similar colours

**To Reproduce**
Steps to reproduce the behaviour:
1. Make sure you have both Local and LDAP strategies set up
2. Go to login page
3. Click on LDAP
4. Barely see the difference between pressed and "depressed" buttons

**Expected behaviour**
One can clearly see the difference between a selected strategy and every other

**Screenshots**
![image](https://user-images.githubusercontent.com/6566248/84996963-42880f80-b14e-11ea-9200-dc4edac18561.png)

**Host Info (please complete the following information):**
 - OS: Debian 10.4
 - Wiki.js version: 2.3.81
 - Database engine: PostgreSQL 12.1

**Proposed solution**
Perhaps it would be better to distinguish the selected/unselected button not by using a drop shadow, but by using regular/outlined or regular/link-style buttons

**Comment by NGPixel** [comment]
This will be addressed in the upcoming 2.5 update.
