### ISSUE TITLE
One click page creation?

### ISSUE THREAD

**Issue by ovgeorge** [Requarks/wiki#2090]
**Question**

I want to create new page in as few clicks as possible. How to achieve this by setting reasonable defaults?  So, for example, instead of selecting editor, I want markdown editor to be selected by default. Instead of selecting category it would go to the default one, etc.

My workflow is that I create lots of pages and then sort them later.

**Comment by NGPixel** [comment]
That's not possible yet. Submit a feature request on https://requests.requarks.io/wiki
