### ISSUE TITLE
In multi langage menu on the left points to the wrong lang

### ISSUE THREAD

**Issue by guizmoau** [Requarks/wiki#2092]
**Describe the bug**
I have a wiki with two langages English and French.

When I am into a french page and I click on the side menu it brings me to english pages only.
If you are not speaking english you can browse in french...it is not practical the menu shall link to the current langage pages, in that case french.

all pages in english are translated in french and works singularly but not via the menu on the left.

**To Reproduce**
1. Go to 'create new pages in two langages'
2. Click on 'the second langage'
3. Scroll down to 'the menu on the left to another page'
4. See error that it link to english not to french

**Expected behavior**
I want to have the link on the left that give the same langage

**Screenshots**

**Host Info (please complete the following information):**

**Additional context**

**Comment by NGPixel** [comment]
Please fill in the Host info section... Which version are you using?

by "menu on the left", do you mean the browse mode or the static menu?

**Comment by guizmoau** [comment]
version  Wiki.js 2.4.105

the browse mode

![Screenshot 2020-06-23 at 15 34 40 - Edited](https://user-images.githubusercontent.com/5398689/85410345-43161100-b567-11ea-8bbc-b89364be34b9.png)
![Screenshot 2020-06-23 at 15 34 50 - Edited](https://user-images.githubusercontent.com/5398689/85410352-45786b00-b567-11ea-9667-360acd63d463.png)

**Comment by NGPixel** [comment]
This is already fixed for 2.5.
