### ISSUE TITLE
Custom modules

### ISSUE THREAD

**Issue by GabImmo** [Requarks/wiki#2093]
**Question**
Hi, is it possible to add self-developed custom modules on Wiki.js? I'd like to add a new search engine module according to my needs. Thanks
**Host Info (please complete the following information):**
OS: [e.g. Ubuntu 18.04, Docker]
Wiki.js version: [e.g. 2.0.1]
Database engine: [e.g. postgres 9.7, mysql 5.7]

**Comment by NGPixel** [comment]
Yes, see the documentation:
https://docs.requarks.io/dev/search

and check the existing modules as an example:
https://github.com/Requarks/wiki/tree/master/server/modules/search
