### ISSUE TITLE
feature discussion - adding spell checks

### ISSUE THREAD

**Issue by regevbr** [Requarks/wiki#2094]
As asked for in https://requarks.canny.io/wiki/p/spell-check I would like to work on adding spell checking to the editors.

After some searching, it seems that CodeMirror is not supporting or going to support native browser spell checks. I found some snippets that allow to use an external spell checking tools and it seems messy heavy and will require some css tricks for it to look nice.

I have a simpler approach - why don't we allow to switch to a new `raw` mode during editing, that will put the raw text of the page inside a plain textarea component (just like when editing comments in GitHub). When we switch to that mode, the native browser spell checker can kick in and we can make any edits we want and then we can switch back to the code mirror editor.

@NGPixel what do you say? I don't mind working on a PR just want to make sure in advance that it is an acceptable solution for you...

**Comment by NGPixel** [comment]
I experimented a bit on your idea, but instead using the preview panel. This way we don't loose the editor current state by switching between modes.

The user can then view any errors and fix them immediately in the editor side. As soon as you click outside the preview panel, the spellcheck mode automatically turns off (as focus is required for spellcheck to work).

See abe86928fb2455dd4389e36c30124e24ff109902

---

For the visual editor, it was simply an option that needed to be enabled for spellchecking to work.

**Comment by regevbr** [comment]
@NGPixel that is awesome thanks! works nicely :-)
