### ISSUE TITLE
How to create folders in Wiki

### ISSUE THREAD

**Issue by anurajsl** [Requarks/wiki#2095]
I want to create folders and create pages inside those folders. how is it possible ?

**Host Info (please complete the following information):**
OS: e.g. Ubuntu 18.04, Docker]
Wiki.js version: 2.4.107

![image](https://user-images.githubusercontent.com/13132309/85316732-d9e8bc00-b4da-11ea-99df-01f892d06d1c.png)

**Comment by anurajsl** [comment]
https://take.ms/vFbNr

**Comment by NGPixel** [comment]
https://docs.requarks.io/guide/structure
