### ISSUE TITLE
Migrating database data from old Wiki v1.x to Wiki.js v2.x using backups

### ISSUE THREAD

**Issue by ArlenNY** [Requarks/wiki#2096]
**Question**
Is it possible to export data from Wiki.js v1.0.78 database (MongoDB 3.4.18) to a Wiki.js v2.4.107 (PostGreSQL) DB without having both installations online? Meaning, is it possible to have only the data exported from the Wiki v1 instance and import it into the Wiki.js V2 instance? I searched the documentation and found the steps to migrate but only found the way to do it by having both servers online and swinging the data from one database to the other using steps in "Migrate from Wiki.js v1.x" on https://docs.requarks.io/install/migrate.

Below are the file I currently have backed up from the old wiki db:
-rw-r--r-- 1 root root  150 Jun 19 14:56 bruteforces.bson
-rw-r--r-- 1 root root   88 Jun 19 14:56 bruteforces.metadata.json
-rw-r--r-- 1 root root  534 Jun 19 14:56 entries.bson
-rw-r--r-- 1 root root   84 Jun 19 14:56 entries.metadata.json
-rw-r--r-- 1 root root 2104 Jun 19 14:56 sessions.bson
-rw-r--r-- 1 root root  176 Jun 19 14:56 sessions.metadata.json
-rw-r--r-- 1 root root    0 Jun 19 14:56 settings.bson
-rw-r--r-- 1 root root  163 Jun 19 14:56 settings.metadata.json
-rw-r--r-- 1 root root 4033 Jun 19 14:56 uplfiles.bson
-rw-r--r-- 1 root root   85 Jun 19 14:56 uplfiles.metadata.json
-rw-r--r-- 1 root root  261 Jun 19 14:56 uplfolders.bson
-rw-r--r-- 1 root root  169 Jun 19 14:56 uplfolders.metadata.json
-rw-r--r-- 1 root root 1893 Jun 19 14:56 users.bson
-rw-r--r-- 1 root root  161 Jun 19 14:56 users.metadata.json

Thanks for your help!

**Host Info (please complete the following information):**
OS: Red Hat Enterprise Linux Server 7.7 (Maipo)
Wiki.js version: 1.0.78
Database engine: MongoDB 3.4.18

**Comment by NGPixel** [comment]
You don't need both online...

You need the mongo database to be accessible (only if you want to keep users).
Content simply needs to be in a folder accessible by your 2.x installation.

You can't use db backups from v1 as that's not where content is stored and the schema are completely different.
