### ISSUE TITLE
To create the personal space.

### ISSUE THREAD

**Issue by Meet116** [Requarks/wiki#2098]
**Question**
Is it possible to create a personal space? For eg in an institute, there are many departments. So for every department, there is a space associated to that particular department. So that no other department user can access there file.

**Host Info:**
OS:  Ubuntu 16.04
Wiki.js version:  2.4.107
Database engine: postgres:11-alpine docker image

**Comment by NGPixel** [comment]
This can be achieve with Page Rules: https://docs.requarks.io/groups

give each department their own subfolder (e.g. /dep-a, /dep-b) and give them only access to that folder.
