### ISSUE TITLE
REST API for account creation / auth?

### ISSUE THREAD

**Issue by HiveMindNet** [Requarks/wiki#2099]
**Question**
Keen to get details of REST API so that I can create users and authenticate in Wiki.js based on a Wordpress site with many users. Doesn't have to be REST API, but preferable to oauth.

What's currently available to create and enable new users rather than allowing registration or manual create, neither of which are an option.

Thanks so much in advance
OS: [Docker: latest]
Wiki.js version: [Wiki.js 2.4.107]
Database engine: [Docker: latest]

**Comment by NGPixel** [comment]
Have you read the docs?
https://docs.requarks.io/dev/api
