### ISSUE TITLE
Add All Pages link option to Navigation

### ISSUE THREAD

**Issue by NGPixel** [Requarks/wiki#21]
As #19 , add an **All Pages** link to the sidebar navigation. Such link would point to a special page where all articles are listed in a hierarchical view.

**Comment by koallen** [comment]
This would be super useful! Sometimes I could lose track of what articles I just added and right now there is no way to find out.

**Comment by choicky** [comment]
looking forwards to beta 11 😀

**Comment by koallen** [comment]
Just curious, are you gonna provide the "All Pages" link in all pages or just in the home page?

**Comment by NGPixel** [comment]
It will be accessible from everywhere.

**Comment by NGPixel** [comment]
Now available in Beta 11
