### ISSUE TITLE
Configuration for GCloud App Engine

### ISSUE THREAD

**Issue by LMarlette** [Requarks/wiki#2102]
**Question**
Id like to create a gcloud installation of wiki.js. Is it possible with either, sql Postgres db and either app engine or firebase?  
**Host Info (please complete the following information):**
OS: pushing from macOS to gcloud
Wiki.js version: 2.0.1
Database engine: postgres 12 

Thanks!

**Comment by NGPixel** [comment]
You can use Cloud SQL for Postgres, but Wiki.js cannot be installed on a serverless environment (so no firebase). So while it could technically work on App Engine (flexible type), you would likely run into problems over time as these instances are not meant to run indefinitely. You should instead use a standard VM or container instance.

**Comment by LMarlette** [comment]
thanks for the info!
