### ISSUE TITLE
To change the home page redirection.

### ISSUE THREAD

**Issue by Meet116** [Requarks/wiki#2106]
**Question**
Whenever the user login it redirects to the, create new page window. Where else some user don't have the permission to create the new page. So it shows an error that the user is unauthorized you cannot have access to this page. Is there anything to change for this type of user to redirect directly to its profile page?

**Host Info:**
OS: Ubuntu 16.04
Wiki.js version: 2.4.107
Database engine: postgres:11-alpine( Docker alpine image )

**Comment by Meet116** [comment]
If anyone just wants to see the document then also he/she have to go through the create page window.

**Comment by NGPixel** [comment]
Have you created the homepage? That page is only shown when no homepage exists yet. Create it and it will not be shown again.
