### ISSUE TITLE
markdown blockquote bug

### ISSUE THREAD

**Issue by ParkHost** [Requarks/wiki#2108]
## Inside blockquote's you may not end with the md-command (un)ordered list, it will change automatically to the 'standard' blockquote.

# example
```

 >  - test
{.is-warning}
```

**Comment by fireundubh** [comment]
More information:

The CSS class is added to the `ul` tag instead of `blockquote`.

**Comment by Veers01** [comment]
This is a duplicate from https://github.com/Requarks/wiki/issues/1241
