### ISSUE TITLE
Background login customization

### ISSUE THREAD

**Issue by ankyfive** [Requarks/wiki#2111]
**Question**
Hello,
I would like to know if and how is it possible to customize the login interface background like it was possible on the V1 ?
Thanks

**Host Info (please complete the following information):**
OS: Debian 9.6
Wiki.js version: 2.4.107
Database engine: postgres 9.7

**Comment by NGPixel** [comment]
Coming in 2.5 update.

**Comment by peteruithoven** [comment]
I'm not finding this option in 2.5.126

**Comment by peteruithoven** [comment]
After digging into the code I just found the relevant settings under Security...
