### ISSUE TITLE
When loading any page: "An unexpected error occured."

### ISSUE THREAD

**Issue by git-eugene** [Requarks/wiki#2112]
**Describe the bug**
When loading any page I get an error: "An unexpected error occurred."

**To Reproduce**
1. Open any page
2. See error

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/44470735/85851807-0db43200-b7b8-11ea-9dc4-8fcb9022741e.png)

**Host Info (please complete the following information):**
 - OS: Fedora 30
 - Wiki.js version: 2.4.107
 - Node.js version: 10.19.0
 - Database engine: PostgreSQL 12.3

**Additional context**
New installation.
Selinux is off.
Dedicated user for Wiki.js service and directory.

**Comment by Smankusors** [comment]
It seems localization fails to load. Is this reproduceable in incognito mode?

Also, can you screenshot your browser's DevTools (while opening Console tab at DevTools)?

**Comment by git-eugene** [comment]
Yes, it's reproducible in incognito mode.
And you are absolutely right, it's an invalid locale:

![image](https://user-images.githubusercontent.com/44470735/85990155-404d6d00-b9fa-11ea-8b0c-0398afb865bb.png)

Is there any solution to the issue?

**Comment by git-eugene** [comment]
Ok, fixed it.
Just use this guide:
https://docs.requarks.io/install/sideload

Thanks!)
