### ISSUE TITLE
How to redirect all users from the Create Home Page page to my home page?

### ISSUE THREAD

**Issue by RaikasCoding** [Requarks/wiki#2113]
**Question**
All my users will be on that create home page-page how to fix this?

**Host Info (please complete the following information):**
OS: Heroku
Wiki.js version: 2.4.107
Database engine: postgres 12.3

**Comment by NGPixel** [comment]
The Create Home Page only appears if the home page is not yet created (first time you install Wiki.js). Once it's created, that page is never shown again.
