### ISSUE TITLE
Matomo integration when javascript is disabled

### ISSUE THREAD

**Issue by g4laad** [Requarks/wiki#2115]
**Describe the bug**
The tracker for when javascript is disabled doesn't take into account the id entered in the administration page.

**To Reproduce**
1. Go to Analytics
2. Put  an id of 3
3. Go to one of your page
4. You can see this: <noscript><p><img src="https://analytics.xx.com/matomo.php?idsite=**2**&amp;rec=1" style="border:0;" alt="" /></p></noscript>

**Expected behavior**
The parameter "idsite" should be of 3, or more generally, of the id entered before.

**Host Info (please complete the following information):**
 - OS: Debian 10
 - Wiki.js version: 2.4.107
 - Database engine: postgresql 11.7

**Comment by NGPixel** [comment]
Fixed by 2409b286da2b48fd277462fcb73da28b6c8f2a72
