### ISSUE TITLE
How to debug LDAP / AD connections

### ISSUE THREAD

**Issue by ankyfive** [Requarks/wiki#2122]
**Question**
Hello,
I am trying to connect to Active Directory with smaccountname or mail.
I tested my query with ldapquery under OS, I set logLvel to debug and I set click on Developer Tools in the sidebar, then on Flags. Enable the LDAP Debug flag but the only message I get is :
warn: LDAP LOGIN ERROR (c1): Invalid email / username or password.
Any help would be appreciated to debug
Regards

**Host Info (please complete the following information):**
OS: [Debian 9.6]
Wiki.js version: [2.4.107]
Database engine: [postgres 9.7]

**Comment by ankyfive** [comment]
Yes it does not match it is different email and different username
How to have more logs cause what is said in the doc for logs does not work for me

**Comment by 3DPhantom** [comment]
The LDAP sync issue could come from a few things.

- Have you tried pinging your LDAP server to see if you can reach the port 389?
- Is the search base configured according to your Active Directory?
- Have you change your SearchFilter?
- May look stupid, but have you click on AD Login (the default option is set to Local login)?

**Comment by ankyfive** [comment]
- Yes I used ldapsearch to test my query and it works
- Yes and I checked it in AD
- Yes I use (sAMAccountName={{username}})
- Yes I did that also

**Comment by Smankusors** [comment]
if your issue is resolved, feel free to close this issue 🙂

**Comment by ankyfive** [comment]
Done thanks
