### ISSUE TITLE
Email not working behind SSL-Reverse-proxy

### ISSUE THREAD

**Issue by smilebasti** [Requarks/wiki#2129]
**Question**
I just installed the most recent version of Wiki.js successfully. Almost everything worked.
Everything is behind a ReverseProxy which has the SSL-Certificate. This works when Wiki.js is on http.

Now i wanted to add the settings for Mail but it gives me following Error:  139813787309888:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../ssl/record/ssl3_record.c:331:

Is there a way i don't have to give wiki.js a ssl certificate directly to use mail in my configuration?

Thanks ahead 

**Host Info (please complete the following information):**
OS:  Ubuntu 20.04
Wiki.js version: 2.4.107
Database engine: mysql 8.0.20-0

**Comment by NGPixel** [comment]
Mail is completely unrelated to whether you use HTTP / HTTPS / reverse-proxy for Wiki.js.

The error means your mail configuration is incorrect. Most likely you didn't enable TLS or the port is wrong.
