### ISSUE TITLE
Editor does not work

### ISSUE THREAD

**Issue by MrWakeCZ** [Requarks/wiki#213]
### Actual behavior
<img width="1264" alt="wiki-bug" src="https://user-images.githubusercontent.com/8173177/29459715-57178632-8425-11e7-9e24-01dd5397ebe3.png">
<img width="1082" alt="wiki-bug-2" src="https://user-images.githubusercontent.com/8173177/29459716-571938e2-8425-11e7-9518-e81d13a17c62.png">

### Expected behavior
Working editor 

### Steps to reproduce the behavior
When I click on edit button editor can not be loaded. I use the latest version of Wiki.js. I tried a reinstall with saved config.yml but nothing works.

**Comment by NGPixel** [comment]
Which browser (and version) are you using and what OS?

**Comment by MrWakeCZ** [comment]
**Browser:** Chrome (version: 60.0.3112.101)
**OS:** MacOS 10.12.5
