### ISSUE TITLE
Github authentication error: Failed to fetch user profile when trying to log in

### ISSUE THREAD

**Issue by jennuineness** [Requarks/wiki#2131]
**Describe the bug**
Hi! :) When trying to authenticate using Github OAuth, I received the error: `Failed to fetch user profile`.

**To Reproduce**
1. Login with a user who has administrator privileges
2. Go to the administrator panel and click on the Github page under the Modules section
3. On Github, create the OAuth app with the callback url given from step 2
4. Going back to Wikijs on the administrator panel --> Github page, add in the Client ID and Client Secret given in step 3 and click on the [Apply] button
5. Log out of Wikijs app
6. Login using Github

**Expected behavior**
Expect to login to Wikijs application using the Github credentials

**Screenshots**
<img width="396" alt="image" src="https://user-images.githubusercontent.com/43213151/86288754-4a5ca080-bb9f-11ea-88de-bcbe33699465.png">

**Host Info (please complete the following information):** 
 - OS: Docker
 - Wiki.js version: 2.4
 - Database engine: PostgreSQL 12.3

**Additional context**
I had another docker container running Wikijs created on June 4th and the Github authentication was successful using Wikijs Docker tag 2.3 (requarks/wiki:2.3). 

The error occurred when I tried to create a new Wikijs container yesterday using a different PostgreSQL database. I also tried recreating the container using different Docker tags (2.2, 2.3, 2.4) and the problem still persists.

**Comment by jennuineness** [comment]
Hi! I was able to figure out what I did incorrectly! I needed to change the domain for the user endpoint to point to the Github enterprise domain. 

Sorry about this! Was able to login now using Github authentication :)

**Comment by uxinkc** [comment]
I'm having this same issue as pictured above, but we don't use Github Enterprise. What are the possible issues I should look into?
