### ISSUE TITLE
About reset password issue.

### ISSUE THREAD

**Issue by HyunminAlexLee** [Requarks/wiki#2133]
**Question**
When I try to reset password, It shows message "Coming soon!".
Does the Wiki.js (ver. 2.3.81) not provide password reset function?
If I forgot my password, how can I change my password?

**Host Info (please complete the following information):**
OS: Ubuntu 16.04 LTS 
Wiki.js version: 2.3.81
Database engine: postgres 11.7
![reset_password](https://user-images.githubusercontent.com/40203155/86433240-2ba5f900-bcc8-11ea-9a50-1222ce5ba7ff.png)

**Comment by NGPixel** [comment]
Ask your wiki administrator to change it for you.

If you're the admin, follow these instructions:
https://docs.requarks.io/troubleshooting#how-to-manually-reset-the-admin-password
