### ISSUE TITLE
sidebar.xxxx still displayed in the navigation after clearing the browser cache

### ISSUE THREAD

**Issue by kadeeee** [Requarks/wiki#2135]
**Describe the bug**
After upgrading to 2.4.107, sidebar.mainMenu, sidebar.root and sidebar.browse are still diplayed in the navigation even if I have cleared the browser cache. Could you please help to identify the reason why variables are appearing instead of the correct word.

**Expected behavior**
The correct word should be displayed not the variable

**Screenshots**
![P1](https://user-images.githubusercontent.com/67794463/86478856-54bb9d80-bd4b-11ea-934e-6cec45786dac.PNG)
![P2](https://user-images.githubusercontent.com/67794463/86478878-5b4a1500-bd4b-11ea-972b-39285a6a07c9.PNG)

**Host Info (please complete the following information):**
 - OS: Linux - Red Hat Linux (maipo) 7.7 x64
 - Wiki.js version: 2.4.107
 - Database engine: postgres 12.2

Thank you for your help.
Kadee.

**Comment by Smankusors** [comment]
Hmm if you are using incognito mode, is this still happens?

Which locale do you use?

Are your Wiki.js is on offline mode?

**Comment by kadeeee** [comment]
Hello,

Thank you for your reply. Yes, it's still happens when I am using icognito help. I am using fr locale and my Wiki.js is indeed on offline mode.

**Comment by Smankusors** [comment]
Locale files is not directly tied on wiki.js version. So upgrading Wiki.js doesn't mean the locale will be updated.

You can read more about it [here](https://docs.requarks.io/install/requirements/internet).

**Comment by NGPixel** [comment]
As @Smankusors said, you need to download the latest locale files when using the offline mode. Follow the instructions at https://docs.requarks.io/install/sideload

Make sure to restart the server once more (as explained in the warning on step 3). You can then clear your browser cache and it should work fine.

**Comment by kadeeee** [comment]
Hello, thank you both of you. I will follow the instructions. Thank you again.
