### ISSUE TITLE
Horizontal scrolling

### ISSUE THREAD

**Issue by AuspeXeu** [Requarks/wiki#2136]
When creating a table with a content wider than the screen size of the machine you're viewing it on, it gets truncated instead of offering a way to scroll horizontally.

In the editor:
![image](https://user-images.githubusercontent.com/2115696/86479502-98fb6d80-bd4c-11ea-8806-3f849ec496d2.png)
Output:
![image](https://user-images.githubusercontent.com/2115696/86479537-a57fc600-bd4c-11ea-979e-649fbc94486b.png)

The output is only visible until column "Model" and the rest is truncated. No scrolling available.

**Comment by Smankusors** [comment]
Duplicate of #2091

**Comment by NGPixel** [comment]
Not the same thing @Smankusors , this is for tables. Unrelated to the scrolling the content tabs specifically.

**Comment by Smankusors** [comment]
uh oh, sorry. I think I have seen this before. How about #1314? 😅

**Comment by NGPixel** [comment]
Duplicate of #1314

**Comment by AuspeXeu** [comment]
#2340
