### ISSUE TITLE
Github authentication does not work

### ISSUE THREAD

**Issue by raboof** [Requarks/wiki#214]
### Actual behavior

When a user logs in with github, he is presented with the error "You have not been authorized to login to this site yet. Oops, something went wrong"

### Expected behavior

The user is successfully logged in

### Steps to reproduce the behavior

I configured github authentication as documented [here](https://docs.requarks.io/wiki/install/authentication#git-hub). The 'login with github' button correctly appears and I'm asked to verify the login at github, but then I'm redirected back to 'https://smartlab-wiki.herokuapp.com/login/github/callback?code=XXXX' (with a 'real' code instead of XXXX) and the above error is shown.

What could I do to track down this issue?

**Comment by NGPixel** [comment]
This is the standard behavior. A user is not given access via social login unless its first authorized. To authorize a user, go into **Settings** > **Users** and click **Create / Authorize User**. Choose Github as the provider and enter the email address.

If you want any user to be authorized (read access) by default, you must fork this [repo](https://github.com/Requarks/wiki-heroku) and modify the `wiki/config.yml` file to set the `defaultReadAccess` property to `true`. Then simply install wiki.js to Heroku from your fork.

**Comment by raboof** [comment]
Aaah makes sense thanks! Sorry about the noise :)
