### ISSUE TITLE
Visual Editor. Table borders

### ISSUE THREAD

**Issue by Scrik** [Requarks/wiki#2142]
**Question**
How to add highlight table and row borders style "border: 1px solid #000;" ?
![image](https://user-images.githubusercontent.com/5807097/86535532-aa2db100-bee9-11ea-8fdb-4ef0b4f6166d.png)

**Host Info (please complete the following information):**
OS: Centos 7
Wiki.js version: Stable 2.4.107
Database engine: postgres 11

**Comment by NGPixel** [comment]
Not possible in the current version. This feature was added in upcoming 2.5 update.
