### ISSUE TITLE
White page after upgrade in latest version

### ISSUE THREAD

**Issue by valvin1** [Requarks/wiki#2145]
**Question**
I've just upgraded in latest version and some of my pages are not rendering until I edit/save again.

First one mention in javascript console there was not wiki_js_version defined which I solved by editing and saving it. If I refer to the git commit, it adds the editor in metadata : [commit here](https://framagit.org/valvin/wiki/-/commit/928a7c67fe1298bf3e4c1aeadb790ce9f395bd33)

 Second one I've not yet done any action : https://wiki.valvin.fr/devops/prometheus ; and here the issue is : `ReferenceError: "$labels is not defined"`. If I refer to the [content](https://framagit.org/valvin/wiki/-/blob/master/devops/prometheus.md) there is not the editor metadata.

Is there some post action to do after an upgrade? Do I need to add editor metadata everywhere ?

**Host Info (please complete the following information):**
OS: Docker
Wiki.js version: 2.4.107 (after upgrade)
Database engine: postgres 11.7

**Comment by holen82** [comment]
Experiencing the same, but not able to edit/save, as the whole page is completely white. Console error logged:
VM1713:37 ReferenceError: Key is not defined
    at Mn.eval
OS: Docker
Wiki.js version: 2.4.107 

Some of my pages still work as normal, but others are completely white.

**Comment by valvin1** [comment]
@holen82 have you tried in tools section to re-render ? Tools / Content / Rerender All Pages ?

I was wondering if it could help me faster when I had the issue.

**Comment by holen82** [comment]
Thanks for the tip @valvin1 - it resolved my issues 👍

**Comment by valvin1** [comment]
You're welcome, it looks to be the good procedure. I'm closing the issue.
