### ISSUE TITLE
Wiki failed while installing

### ISSUE THREAD

**Issue by sol-malisani** [Requarks/wiki#2147]
When i get into the installation page, after i filled all the fields the following message pop ups:
"Unexpected token < in JSON at position 0"
And it keeps loading indefinetly.

wiki.js version: 2.0.107

![image](https://user-images.githubusercontent.com/66799118/86623284-b1ab9380-bf97-11ea-942e-8c8b5ef2a86f.png)

**Comment by Smankusors** [comment]
Have you tried with Wiki.js 2.4.x?

**Comment by sol-malisani** [comment]
Yes, i wrote the version wrong sorry... it was a database problem. thanks!!
