### ISSUE TITLE
git.branch is not working 

### ISSUE THREAD

**Issue by Bamieh** [Requarks/wiki#215]
### Actual behavior
in the `config.yml` adding the following does not do anything

```yml
git:
  branch: content
```

### Expected behavior
The wiki to sync with "content" branch

### Steps to reproduce the behavior
change `git.branch` to any branch in the yml file.

The wiki still pushes to master regardless. I tried `origin/content` aswell, same issue. The branch is created on github already, but it didnt work neither way. I am using ssh to authenticate github

**Comment by NGPixel** [comment]
Indeed... I'll push a fix in the coming days.

In the meantime, as a workaround, you can set the branch to use by modifying this file:
https://github.com/Requarks/wiki/blob/master/server/libs/git.js#L24

**Comment by Bamieh** [comment]
@NGPixel thanks, but the npm package is still not upto date. I am using docker so i npm install the wiki. I assume most users do, rather than copying the source code

**Comment by NGPixel** [comment]
@Bamieh Packages are no longer published to npm. See the [docs](https://docs.requarks.io/wiki/install) for the new install method. The npm package (wiki.js) is simply calling these scripts from now on.

I changed the CI flow recently and still have a few bug to fixes (hopefully by tomorrow), so your changes won't be included until this is fixed.

If you're using docker, you can use the official image: https://docs.requarks.io/wiki/docker
This image already includes your changes.

**Comment by Bamieh** [comment]
@NGPixel the docker image uses `npm install`. Can you direct me to the source code of the docker image? The change is still not reflected

**Comment by NGPixel** [comment]
Are you using the [latest docker image](https://hub.docker.com/r/requarks/wiki/)?

npm install isn't used in the docker image... If you want to see how the image is built, you can check the [wercker.yml](https://github.com/Requarks/wiki/blob/master/wercker.yml) file.

**Comment by Bamieh** [comment]
I see, let me debug further into it then
