### ISSUE TITLE
<script> tag gets stripped

### ISSUE THREAD

**Issue by jelle619** [Requarks/wiki#2150]
**Question**
I am trying to embed a JavaScript embed from Pastebin on my Markdown page. A Pastebin embed looks something like this:
```javascript
<script src="https://pastebin.com/embed_js/9AQBkE6s"></script>
```
I have turned off HTML Sanitize in the rendering options for HTML, and it still isn't working. I can confirm it also doesn't work when using the Raw HTML editor. I have tried the HTML in Codepen where is does seem to work. I have inspected the page and I can confirm the ``script`` tag is indeed missing. Anyone who knows why this happens?

**Host Info (please complete the following information):**
OS: Ubuntu 20.04, Docker
Wiki.js version: 2.4.107
Database engine: postgres 12.3

**Comment by Smankusors** [comment]
After you turned off HTML Sanitizer, are you do "re save" the page?

**Comment by jelle619** [comment]
Dfter turning it off I created a brand new page to try it on and I also re-rendered all existing pages just to be sure. Still no luck. @Smankusors

**Comment by TheSynus** [comment]
I also have this problem. I already tried to disable the Security module in the rendering pipeline, stopping the server and dropping all server caches The script tag still gets stripped after re-rendering.

**Comment by EsEnZeT** [comment]
I see exact same behavior after turning all security related stuff and creating page again. Tried to add js graph and <script> tag is always stripped.

@NGPixel can you please comment on that?

**Comment by NGPixel** [comment]
Scripts will not work when added to a page. It's simply not possible to execute JS via a vue rendered page.

You need to either put them globally via Admin > Theme > Code Injection or per page in the Page Properties dialog, under Scripts.
