### ISSUE TITLE
wikijs with ipv6

### ISSUE THREAD

**Issue by AgnerSecurity** [Requarks/wiki#2155]
**Question**
hello, how can i make wikijs in centos 7, run ipv6 as web server?

**Host Info (please complete the following information):**
OS: Centos 7 
Wiki.js version: 2.0.1
Database engine: mariadb

**Comment by justinacolmena** [comment]
I have an admittedly very nonstandard setup for my homepage https://www.colmena.biz/ with nginx to forward IPv6 requests to the wikijs/nodejs server. Otherwise I think IPv6 support is more of a general issue to take up with the nodejs developers, not specific to wikijs or any particular application on nodejs.

On July 7, 2020 3:02:10 PM AKDT, Luis Carlos Agner Claro - Agner Security <notifications@github.com> wrote:
>**Question**
>hello, how can i make wikijs in centos 7, run ipv6 as web server?
>
>**Host Info (please complete the following information):**
>OS: Centos 7 
>Wiki.js version: 2.0.1
>Database engine: mariadb
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Requarks/wiki/issues/2155

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by AgnerSecurity** [comment]
hello, could you teach me how to put ipv6 on wikijs?

**Comment by justinacolmena** [comment]
As I mentioned I am running nginx. Here is an excerpt from my `/etc/nginx/nginx.conf`. The wikijs server is running at its default port on localhost `http://127.0.0.1:3000`, and nginx is configured to forward (most) external "https" requests directly to the wikijs server. The Strict-Transport-Security preload setting is intended to enhance the enforcement of https sercurity on the domain, but your mileage may vary.

    server {
        listen       443 ssl http2 default_server; # IPv4
        listen       [::]:443 ssl http2 default_server; #IPv6
        server_name  www.example.biz example.biz _;
        root         /var/www/html;

        charset UTF-8;
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload";

        ssl_certificate "/etc/letsencrypt/live/example.biz/fullchain.pem";
        ssl_certificate_key "/etc/letsencrypt/live/example.biz/privkey.pem";
        ssl_session_cache shared:SSL:1m;
        ssl_session_timeout  10m;
        ssl_ciphers HIGH:!aNULL:!MD5;
        ssl_protocols TLSv1.3 TLSv1.2;
        ssl_prefer_server_ciphers on;

        # Load configuration files for the default server block.
        include /etc/nginx/default.d/*.conf;

        # ...
        location / {
                proxy_set_header   X-Forwarded-For $remote_addr;
                proxy_set_header   Host $http_host;
                proxy_pass         http://127.0.0.1:3000;
        }
        # ...
    }

**Comment by NGPixel** [comment]
You need to define the `bindIP` parameter in your config.yml. See https://docs.requarks.io/install/config#bind-ip

Either set the IPv6 address of your network interface or use `::`
