### ISSUE TITLE
Discord Login Failing

### ISSUE THREAD

**Issue by dylanjames-js** [Requarks/wiki#2164]
**Question**
For some reason, my discord login is failing for the wiki for my discord server. This is kind of important because members can only use discord to signin, the admin account it the only local account. All the discord secret and keys are correct as I've double checked them, it says the following message on every login.

Oops, something went wrong...
Failed to obtain access token

but yet in the url it shows the token to my understanding? 
https://wiki.*******.***/login/discord/callback?code=czI4XllvZNLCaEK4YwhyknvYJqNdfP

**Host Info (please complete the following information):**
OS: Glitch.com
Wiki.js version: 2.3.81
Database engine: sqlite 3.30.1

**Comment by NGPixel** [comment]
Try updating to 2.4 and see if you still have the issue.

The discord module was updated in the upcoming 2.5 update, to address the change from discordapp to discord domain. You can manually apply this fix by editing the file directly:
https://github.com/Requarks/wiki/pull/2117/files

**Comment by RuscalWorld** [comment]
I have the same issue. Tried to change authorization URL, but it still not working. Wiki 2.4.107 in Docker, database: postgres 11.8
