### ISSUE TITLE
enclosed documents.

### ISSUE THREAD

**Issue by oshybrid** [Requarks/wiki#2165]
Is enclosing documents into a wiki considered an asset and thus I am limited to just 10?
Because I need to enclose many PDFs on my group's wiki.

Thank You.

**Comment by Smankusors** [comment]
You can change that from the config. Read more about it [here](https://docs.requarks.io/install/config#upload-limits).

FYI, the assets will be saved on the database instead of physical files.

**Comment by NGPixel** [comment]
The limit is simply per upload. You can upload as many PDFs as you want, in batch of 10.

That limit can be increased via the **Admin** > **Security** page.
