### ISSUE TITLE
Linking style

### ISSUE THREAD

**Issue by jterpstra1** [Requarks/wiki#2166]
**Question**
I''m trying to make a wiki for my own guides I personally use but I've seen linking styles in the docs 
![image](https://user-images.githubusercontent.com/49212524/87221483-aa580180-c36c-11ea-9433-bbe33ac38bdd.png)
Which I'd like to use myself, except I cannot find anything about it or if and how I can use it.

I hope it's available and if so can anyone help me find it?

**Host Info (please complete the following information):**
OS: Docker (Digital Ocean Droplet)
Wiki.js version: 2.4.107
Database engine: postgres 11.7

**Comment by winkelement** [comment]
https://docs.requarks.io/en/editors/markdown#unordered-lists

You can always check the source code of a wiki.js page by inserting `/s` to the url.
See https://docs.requarks.io/s/install

**Comment by jterpstra1** [comment]
That's exactly it! thanks :)
