### ISSUE TITLE
Cannot see cloud icon to download new locales

### ISSUE THREAD

**Issue by tobx** [Requarks/wiki#2170]
### Actual behavior

At my typical browser width (around 2500 px on a retina screen) I cannot see the cloud icon at the right of the locales (administration area). It took me quite a while to understand how to download new locales, because I had to resize my browser window for it.

### Expected behavior

The Icon should always be visible.

### Steps to reproduce the behavior

Resize the browser width to different sizes until the cloud icon disappears behind the browser window frame.

**Comment by Smankusors** [comment]
well yeah that's what happened to me while ago. Currently there's a horizontal scroll so you don't need to resize your browser.

**Comment by tobx** [comment]
Ah yes, no scrollbars shown on a mac and I did not expect the inner panel to be scrollable.

**Comment by tobx** [comment]
From my side this can be closed, but generally speaking, I guess it would be better that all UI elements are always visible. Otherwise users always have to check if panels are scrollable to not miss out certain options.

**Comment by NGPixel** [comment]
What screen resolution are you using? Is your browser window maximized?

**Comment by tobx** [comment]
I have tried several resolutions: 3840 x 2160 and 2880 x 1800. It happens at around 2500px width when the layout adjusts for a larger window width, but at full screen I can see the cloud icons again. Here is a small screen recording, I hope you can see it:

![edited](https://user-images.githubusercontent.com/6427718/88490239-6d118780-cf9a-11ea-9669-7cf9376509a3.gif)

So not really an issue, but if your browser width happens to be at this range, you might be confused, because you generally do not search for UI components but expect them to be visible.
