### ISSUE TITLE
How is this formatting accomplished?

### ISSUE THREAD

**Issue by hwwilliams** [Requarks/wiki#2172]
**Question**
In the [official documentation for editors](https://docs.requarks.io/editors) I noticed a format for listing links that I can't seem to find information on. How is this accomplished?

![image](https://user-images.githubusercontent.com/20447447/87312852-1cf0ea80-c4ef-11ea-8852-34d8931e20cf.png)

**Comment by winkelement** [comment]
https://docs.requarks.io/en/editors/markdown#unordered-lists

You can always check the source code of a wiki.js page by inserting /s to the url.
See https://docs.requarks.io/s/editors

**Comment by hwwilliams** [comment]
Thank you!
