### ISSUE TITLE
Frontend should use encodeURIComponent(path) when navigating to a document + opinions on path limitations

### ISSUE THREAD

**Issue by finalchild** [Requarks/wiki#2174]
**Describe the bug**
The page navigation fails when creating a document on paths like "%20" or "\t".

**To Reproduce**
Try to create a document on paths like "%20" or "\t".

**Expected behavior**
The frontend should properly escape the document path.

**Screenshots**

**Host Info (please complete the following information):**
Not relevant to this issue.

**Additional context**
Two limitations on document paths can be lifted. (server/models/pages.js createPage(), movePage())
1. DOT (.) should be allowed if they don't constitute . or .. path segment. They are useful in representing versions.
2. SPACE should be allowed. In certain wikis, users could find URLs like "https://somewiki.net/some document name" simple and convenient.

The frontend should use encodeURIComponent(path) instead of the plain path when navigating to a document. This allows navigating to document paths including reserved characters.

I don't exactly understand the current trimming behavior of server/helpers/page.js/parsePath(), but it should be consistent with limitations at createPage/movePage. Unaccessible pages should not be allowed to be created.

**Comment by NGPixel** [comment]
**No.**

Spaces in URLs doesn't make any sense. Having encoded characters in URLs is ugly and adds unnecessary complexity to path parsing. It's neither simple or convenient.

Dots are not allowed because they are reserved for assets. This is how the URL parser knows whether it's a page or an asset file without having to do extra DB lookups. You can just as well represent "versions" with dashes.

The bug where pages with some invalid paths are allowed to be created is being addressed in the next update.

**Comment by finalchild** [comment]
Encoded characters are particularly useful for regions not using the Roman alphabet. For example, many Koreans would prefer https://example.com/튜토리얼 to https://example.com/tutorial. That's also the rationale of IDNs. Thus, the parser should unescape the URL anyways.

I understand the style of document URL can be opinionated. But in many wikis (English or Korean, my native language), users can just type the title of a document after the root URL to directly navigate to the page, and simply disallowing that style doesn't bring much good. IMO, the choice of the URL style should be left to the wiki owners, not forced by the software.
+ In modern browsers, spaces in URLs are presented seamlessly.

Dots at the start of the segment represents hidden items, but the others are not. A simple code change could allow URLs like https://example.com/changelog/1.0.0 . /changelog/1-0-0 looks ugly to me.

**Comment by finalchild** [comment]
Oh, I just understood what you meant by assets. Sorry.
For my wiki, I'll just have to edit the source code to limit the file extensions to some common ones and lift the dot restriction.
