### ISSUE TITLE
webhooks & editor are greyed out in admin sidebar

### ISSUE THREAD

**Issue by devkonvert** [Requarks/wiki#2176]
webhooks & editor are greyed out in admin sidebar

OS: Centos 8
Wiki.js version: 2.4.107
Database engine: postgres 10.6-1

**Comment by Smankusors** [comment]
You can edit your issue instead of creating a new one (#2177). I suggest you to close this one and track this issue on #2177.

**Comment by Smankusors** [comment]
oof sorry about my previous deleted comment.

If it's greyed out, it means it's not implemented yet.
