### ISSUE TITLE
Path wiki.domain.com/a/navigation is visible to everyone

### ISSUE THREAD

**Issue by DanielDamito** [Requarks/wiki#2178]
In our wiki, we are restricting the navigation bar to some groups, but the path site/a/navigation is visible to everyone, even if we restrict the permission of guest group.

To reproduce this behavior, you can access the path wiki.yourdomain.com/a/navigation without being logged into the system, as you can see in the following screenshot: https://ibb.co/R01RptZ

You can not see or edit the contents, but seeing all the articles of the navigation bar can expose the contents of the wiki, which is a undesired behavior, as we have a page to each customer we have.

I tried the following page rule to restrict this access, but not succesfully: https://ibb.co/CtnY2Rw

Host info:
S.O: CentOS (core) 7.8.2003 x64
Wiki version: 2.4.107
Database: 10.3.23-MariaDB
Node.js: 12.18.2

Do you have any suggestion to avoid it?

**Comment by yoshz** [comment]
This counts for all admin pages. Even if you get the "You are not authorized..." message, you don't want to display any forms to anonymous users.

**Comment by NGPixel** [comment]
Fixed by 4f16dd0c81d3aa4e60f337e573895192ae6a7f83

**Comment by DanielDamito** [comment]
Sorry me, I dont understand the dynamic of the github. But, as you fixed the error, what should I do to apply this fix to our wiki also?

**Comment by qubidt** [comment]
@DanielDamito you'll have to wait for the release where that fix is applied. I assume it's included in the 2.5 release. You can run the 2.5 beta but that's not recommended for a production site.

**Comment by DanielDamito** [comment]
Thank you, @qubidt !

**Comment by NGPixel** [comment]
There's no 2.5 beta yet. Wait for the actual stable 2.5 release.
