### ISSUE TITLE
WikiJS port 80 + SSL

### ISSUE THREAD

**Issue by AgnerSecurity** [Requarks/wiki#2180]
**Question**
Hello, how to run WIKIJS on port 80? I don't want to use port 3000, however when changing config.yml to port 80, it doesn't work.
another question, when i set ssl = true in wikijs, it just doesn't open, being custom or letsencrypt.
Do I need to configure something for wikijs to use ports 80 and 443?

**Host Info (please complete the following information):**
OS: Centos 7 Minimal
Wiki.js version: 2.0.1 (most recent)
Database engine: mariadb

**Comment by winkelement** [comment]
How are you running wiki.js? You are using docker? Which [installation guide](https://docs.requarks.io/install) did you follow? 

> it doesn't work.

What does that mean exactly? You see an error in the logs?

For SSL: Which guide to setup HTTPS did you follow? You made sure you have a valid certificate? You have a reverse proxy in front of wikijs? Are there other servers running on the same machine (apache, nginx,...)?

**Comment by AgnerSecurity** [comment]
hello, I managed to configure the virtual host with apache, much simpler
