### ISSUE TITLE
Wrong article creation date in docker version

### ISSUE THREAD

**Issue by RamBumBada** [Requarks/wiki#2186]
**Question**
Hi, first things first. I’m new to Docker and Wiki.js. With your step for step guide, I managed it to install the latest Docker Version on Ubuntu Server 20.04 LTS. My problem is following. The creation time of every newly created article is 2 hours behind my local time. I live in Germany so the timezone should be ‚Europe/Berlin‘, but I don’t know where and how to change it. Can you please give me an advice or a step to step guide!?

Thanx in advance and keep save!

Kind regards
Thomas 

**Host Info (please complete the following information):**
OS: Ubuntu 20.04, Docker
Wiki.js version: 2.4.107
Database engine: postgres latest

**Comment by winkelement** [comment]
You can change the timzone in your profile https://yourwiki.com/p/profile

There are feature requests regarding defining the default timezone https://requarks.canny.io/wiki?search=timezone

**Comment by RamBumBada** [comment]
@winkelement 

Thanx for your quick reply and the solution! It‘s so easy, but I missed it... ;)
Keep save and kind regards!

Thomas
