### ISSUE TITLE
Form fields should use inputmode

### ISSUE THREAD

**Issue by JetForMe** [Requarks/wiki#2188]
**Describe the bug**
Form fields should have appropriate `inputmode` attributes. This comes up in the login form, for example, where the login field should have `inputmode="email"`. Without it, iOS (and I'd guess Android, too) auto-capitalizes the first letter when someone types in their login.

Couple with the fact that login is doing a case-sensitive match (it [shouldn't](https://github.com/Requarks/wiki/issues/2014)), causes people a lot of problems logging in.

**To Reproduce**
Login on iOS by typing the login.

**Expected behavior**
Fields should present keyboards best suited for the type of input.

**Comment by NGPixel** [comment]
Fixed by 26af63a80b185c245d1da722c72e58613a409f18
