### ISSUE TITLE
How to delete an asset folder

### ISSUE THREAD

**Issue by parthi2929** [Requarks/wiki#2195]
**Describe the bug**
I am new wiki user and we host it in our VM. While editing a page, I accidentally created wrong assets folder. How could I delete them? I could not find any option going to assets option. 

**To Reproduce**
1. Go to assets option in editor page (markdown)
2. Create a folder
3. Try deleting it

**Expected behavior**
A clear option well placed to enable us to delete asset folders

**Screenshots**
Here I want to delete temperature folder which I created at same level as sensors, but it should be within sensors. 
![image](https://user-images.githubusercontent.com/11896263/87749300-f647f200-c815-11ea-9455-c28e47d3aec3.png)

**Host Info (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04, Docker]  Ubuntu 18.04
 - Wiki.js version: Wiki.js 2.4.105
 - Database engine: As requested by Wiki.js 2.4.105 (is this needed, I have to ask admin, if so I will raise request and get it)

**Comment by 3DSkaoi** [comment]
From the doc, https://docs.requarks.io/guide/assets, it is written that it's coming soon.
