### ISSUE TITLE
HA: Setup Wizard not notified if another replica completes setup

### ISSUE THREAD

**Issue by axisofentropy** [Requarks/wiki#2201]
### Steps to reproduce the behavior
Configure a highly available deployment of Wiki.js on Kubernetes. Set `HA_ACTIVE = true` and database connection environment variables.  Minimum three replicas.  Connect to the load balancer and complete the setup installation.

### Expected behavior
Installation should complete and redirect to creating the home page, no matter which replica handles your HTTP request.

### Actual behavior
If the load balancer directs your HTTP request to one of the other repliacs (not the replica you just finished setup upon) then you'll again be presented with the setup wizard. If you try to complete setup again, you'll just get this error:
```
delete from "locales" where "code" != $1 - update or delete on table "locales" violates foreign key constraint "users_localecode_foreign" on table "users"
```

**Comment by NGPixel** [comment]
Yes this is a limitation right now. You must install with a single replica first, then scale up afterwards.

There's already a warning in the [Kubernetes docs page](https://docs.requarks.io/install/kubernetes) but I'll add it to the configuration page as well.
