### ISSUE TITLE
Reset password is not working

### ISSUE THREAD

**Issue by anhit07** [Requarks/wiki#2207]
**Describe the bug**

I tried to test "Forgot your password" function, but I do not receive any email from wiki after hitting "Reset password" button
The email function works properly when I tested "Send a test email" function from Administration Area page.
And other settings of database connection is correct

I am using wiki version 2.4.107
Has anyone experienced the same issue as me? Is there any configuration or dependencies I need to update for wiki?

I appreciate any comments and help

Thank you
Anh Nguyen

**Comment by RPeacan** [comment]
We're also using version 2.4.107 and we aren't receiving emails when resetting a password. It just says "Coming Soon!" which I hope is referring to the email, and not the feature. haha

We also are able to receive an email when using the Send a Test Email feature.

**Comment by NGPixel** [comment]
Reset password is coming in 2.5 update. In the meantime your administrator can reset the password from the Administration Area.
