### ISSUE TITLE
Where are detailed server logs? I also cannot find any log files

### ISSUE THREAD

**Issue by AmazingTai** [Requarks/wiki#2208]
**Question**
I want to find log files like xxxx-json.log,but I cannot find any local files.
Cloud you help me a path that I can find these log files :)

**Host Info (please complete the following information):**
OS: [Centos 7,2]
Wiki.js version: [releases 2.4.75]
Database engine: [sqlite]

**Comment by NGPixel** [comment]
Logs are output to the console.

If running as a service, you can automatically forward the console output to log file in your systemd service definition. Or you can use journalctl to fetch the logs.
