### ISSUE TITLE
Seamless auth with Keycloak (or any other SSO provider if any other fits better)

### ISSUE THREAD

**Issue by diericx** [Requarks/wiki#2210]
**Question**
Hey, I'm currently working on a project where I'd like to host a wiki along side a forum. The goal is to use something like Keycloak for authentication and have that work seamlessly between the two. I've got Keycloak setup, but there are some quirks that are making the experience a bit clunky..  

Here are some main issues I'm trying to fix but can't quite figure out. Any help finding resources on this would be super helpful!

#### 1. Default to Keycloak sign in

Right now if someone comes to the wiki and is already signed into Keycloak, they need to go to the auth page, select "sign in with Keycloak" and then just get redirected back to wiki. Is there any way to just set the default login url to keycloak? I want to use Keycloak for all my authentication, so no need to let users enter a select screen.

#### 2. Along those same lines, is it possible to just detect/use a Keycloak session?

Is there any way to completely bypass the user having to sign in on the wiki, and just use the keycloak session? So if the user is signed into keycloak (from some other section of the website) and then visit the wiki that session will just be carried over. Similarly if they sign out via keycloak their session with wikijs ends and will need to sign in again. This would actully solve all my auth problems!

#### 3. Is there really no way to customize the header?

I'm trying to make all of these apps look the same, and not being able to customize the header would be a real deal breaker. [This section of the docs](https://docs.requarks.io/dev/themes#what-can-be-customized) states it cannot be customized which would be a huge bummer because I really want to use wikijs!

**Host Info (please complete the following information):**
OS: Ubuntu 18.04 host, running in Docker
Wiki.js version: 2.3.81
Database engine: Postgres 12.2

**Comment by NGPixel** [comment]
1. This is coming in 2.5 update.
2. No, as Wiki.js doesn't use the keycloak session (even if that's your login provider). Keycloak is only used for login, not for session or authorization purposes.
3. You can customize the colors of the header using CSS. However, the header HTML layout itself is not customizable.
