### ISSUE TITLE
Changing opening page

### ISSUE THREAD

**Issue by BenHirschbergCa** [Requarks/wiki#2217]
**Question**
Hi

I have redesigned the opening page of my wiki, I created a new page and worked on it. Now I want to publish it and make it the opening page of the wiki.

I don't find how I can change the opening page (called /home) to my new page (/welcome)

(simple copy paste is not a solution, the current page is markup the new is in HTML)

Thanks
Ben

**Host Info (please complete the following information):**
OS: [e.g. Ubuntu 18.04, Docker]
Wiki.js version: 2.4.107
Database engine: postgres 11.5

**Comment by BenHirschbergCa** [comment]
I've found a solution: delete the current opening page (/home) and rename/move the one I want to be the new opening page to /home

**Comment by 3DSkaoi** [comment]
That feature should be released with version 2.6 (no ETA at the moment). So, it is kind of a solution for the moment. Also, note that in 2.5 it will be possible to have different welcome pages based on the user's group.

https://docs.requarks.io/releases

**Comment by NGPixel** [comment]
`/home` will always be the opening page. You can copy the contents of your new page into the home page.

As @3DSkaoi mentionned, you'll be able to define different landing pages based on the group in update 2.5, or create a redirect as the homepage in 2.6.
