### ISSUE TITLE
Increase Upload size not applying

### ISSUE THREAD

**Issue by scarecrowddb** [Requarks/wiki#2221]
**Describe the bug**
Increasing the Maximum Upload Size or Max Files per Upload is not increasing it in the actual upload screen, and is not permitting larger file uploads.

**To Reproduce**
1. Go into Administration > Security and increase the Max Upload Size and the Max File per upload, 
2. Now go to upload a file, the upload window still says Max 10 files, 5MB each and the files do not permit large file uploads.

**Expected behavior**
The upload window should match the maximum upload size in the Administration > Security Screen, and it should permit large uploads

**Screenshots**
![image](https://user-images.githubusercontent.com/57271083/88242218-e88be400-cccf-11ea-9927-ae20b46c3a74.png)
![image](https://user-images.githubusercontent.com/57271083/88242281-13763800-ccd0-11ea-964b-c47db201a3d1.png)

**Host Info (please complete the following information):**
 - OS: Ubuntu 18.04.4 LTS, Docker
 - Wiki.js version: 2.4.107
 - Database engine: PostreSQL 11.7

**Additional context**
This was a droplet deployed through Digital Ocean

**Comment by farzadpanahi** [comment]
This problem still exists. See #6440
