### ISSUE TITLE
Unauthorized User Access to Administration Area

### ISSUE THREAD

**Issue by Stathis90** [Requarks/wiki#2222]
**Describe the bug**
There is no redirection for an authorized user if she/he tries to access an administration area page. 

**To Reproduce**
1. Go to any administration page ex. https://docs.requarks.io/a/pages or https://docs.requarks.io/a/utilities
2. An error is shown but an unauthorized user can see and interact (not actually) with the page

**Expected behavior**
A direction to the login page 

**Screenshots**
![image](https://user-images.githubusercontent.com/15157178/88280796-2b10e900-ccef-11ea-9124-115d29566491.png)
![image](https://user-images.githubusercontent.com/15157178/88280954-7d520a00-ccef-11ea-9083-a4c76121228f.png)
![image](https://user-images.githubusercontent.com/15157178/88281004-95298e00-ccef-11ea-8d59-b937ee2c4d30.png)

**Host Info (please complete the following information):**
 - OS: Docker Container (Linux)
 - Wiki.js version: 2.4.107
 - Database engine: postgres 11.8

**Comment by 3DSkaoi** [comment]
You can mitigate that, in the case that it is _possible_ for you, by limiting access to your network only. That's the only way I found to prevent this behavior.

**Comment by NGPixel** [comment]
Already fixed in upcoming update.
