### ISSUE TITLE
Generic User Authentication

### ISSUE THREAD

**Issue by AbdulMoeedfieldforce** [Requarks/wiki#2224]
If the user login to our system  (our personal application) it also gets authenticate in wiki js application. We don't want to use OKTA or any third-party app is there anything like wiki js API which we can use to achieve this.

**Comment by Smankusors** [comment]
you can use OAuth 2 (coming soon) or SAML if you don't want third party app

**Comment by NGPixel** [comment]
As @Smankusors said, you need to use OAuth2 to achieve that, which is coming in the 2.5 update. It will also be possible to use the API to generate a token but you would be responsible for saving it as a cookie in the same top level domain.

**Comment by nssnl** [comment]
@NGPixel I can’t find any documentation on retrieving a token through the API, that I can set by myself to authenticate users (as part of my custom authentication process). Would you be able to point me in the right direction? Thanks

**Comment by NGPixel** [comment]
There's no endpoint to generate arbitrary user tokens at the moment. You should instead let Wiki.js handle the authentication through a central auth system via OAuth2.
