### ISSUE TITLE
Creat for Guests

### ISSUE THREAD

**Issue by KallerTobias** [Requarks/wiki#2226]
Is it possible to allow creation for guests? I don't want the visitors to create a user account to create content.

**Comment by 3DSkaoi** [comment]
It is possible. Have you looked at the permission in your WIKI.JS Administration panel? If not, have a look at User and add the needed permission to the Guest user.

**Comment by NGPixel** [comment]
No, guests cannot create or edit content.

Although I don't recommend it, a workaround would be to create a generic user with a simple user/pass, and display that user/pass on the homepage for everyone to use.
