### ISSUE TITLE
Can't embed iframes in Markdown editor

### ISSUE THREAD

**Issue by JacobDB** [Requarks/wiki#2228]
**Question**
I'm trying to embed an iframe on a Markdown page, but it just keeps outputting `<div></div>`. Is it not possible to embed iframes in Markdown?

**Host Info (please complete the following information):**
OS: Ubuntu 18.04
Wiki.js version: 2.4.107
Database engine: postgres 10.12

**Comment by Smankusors** [comment]
Duplicate of #1539

**Comment by JacobDB** [comment]
Hmm. Even with those settings configured, it still doesn't seem to work.

![image](https://user-images.githubusercontent.com/1123997/88427056-d9806100-cdb7-11ea-8a94-ee3286128075.png)

![image](https://user-images.githubusercontent.com/1123997/88427082-e309c900-cdb7-11ea-83c6-9dacdbbe6845.png)

Also tried turning off "Sanitize HTML," didn't seem to make any difference. Resaved the page after every setting update.

**Comment by JacobDB** [comment]
Oh! Restarting the server fixed it.

**Comment by Smankusors** [comment]
Oh yeah I forgot this thing, you need to "resave" the page so it re render again 😅
