### ISSUE TITLE
Turkish translation doesn't work

### ISSUE THREAD

**Issue by sensahin** [Requarks/wiki#2230]
**Describe the bug**
Turkish translation seems %100 completed. However upon installing the translation some words still keep staying in English. For example; TAGS, TALK, View Discussion, New comment, post comment, posting as.., comments, be the first to comment.

**To Reproduce**
1. Go to [this](https://kriptowiki.com/) website.
2. See above words appear on homepage in English which they are supposed to be in Turkish.

**Expected behavior**
If it says Turkish translation is completed %100 then i expect that all translation is complete.
<img width="541" alt="Screen Shot 2020-07-25 at 13 47 39" src="https://user-images.githubusercontent.com/802267/88455374-748f3e80-ce7d-11ea-93ca-262bab6cc564.png">

**Screenshots**
(i highlighted all wordings)
<img width="1164" alt="wikijs" src="https://user-images.githubusercontent.com/802267/88455337-35f98400-ce7d-11ea-894f-f74de7647080.png">

**Comment by Smankusors** [comment]
Are you already set the language to Turkish? Also you need to download the language pack first. Scroll to the right to see the download button.

**Comment by NGPixel** [comment]
These has been fixed in the upcoming 2.5 update.

Not all text is localized yet. More strings are added over time.
