### ISSUE TITLE
Wikijs loading slow / does not pass Google pagespeed tests

### ISSUE THREAD

**Issue by sensahin** [Requarks/wiki#2231]
**Describe the bug**
I am not sure if this is a bug or performance improvement but i am experiencing slowness loading/transition pages.
I performed couple of pagespeed tests for Wikijs own website (https://docs.requarks.io/) and the score is way below the average.

I perform the same test on my own website and results is same. It is way lower than the average speed.

**To Reproduce**
1. Go to https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fdocs.requarks.io%2F
4. See speed results.

**Expected behavior**
I am expecting a high speed score and fast transition between pages.

**Screenshots**
<img width="784" alt="Screen Shot 2020-07-25 at 13 58 48" src="https://user-images.githubusercontent.com/802267/88455568-fc297d00-ce7e-11ea-9ef1-9d937634156a.png">

**Host Info (please complete the following information):**
 - Ubuntu 18.04, Docker
 - Wiki.js version: 2.4.107
 - Database engine: postgres 11.8

**Comment by NGPixel** [comment]
2.x doesn't have server-side rendering, which accounts for most of this score. It's planned for the 3.0 release.

Also, that score is the mobile score. Switch to desktop and it's going to be 50. Still not great but not abysmal either.
