### ISSUE TITLE
Git storage didn't work

### ISSUE THREAD

**Issue by Fantasia1999** [Requarks/wiki#2235]
**Question**
Describe in details what you are trying to achieve and where do you need guidance.
After configure Git storage, my github repository is still empty, No document was commited.
what's more the status shows green.
**Host Info (please complete the following information):**
OS: heroku
Wiki.js version: 2.4.107
Database engine: postgres 12

**Comment by NGPixel** [comment]
You need to run **Add Untracked Changes**, then **Force Sync**. Your existing pages won't be added to git unless you run these actions manually.

**Comment by Fantasia1999** [comment]
> You need to run **Add Untracked Changes**, then **Force Sync**. Your existing pages won't be added to git unless you run these actions manually.

Thanks for your help. I made it just now.
It had been confused me for a while.
I think adding this description to the Git document is a good choice.

**Comment by NGPixel** [comment]
It's documented in the [docs](https://docs.requarks.io/storage/git#missing-content-in-remote-repository).
