### ISSUE TITLE
Plantuml embedded hyperlink not interactive

### ISSUE THREAD

**Issue by mlafrance-complianceds** [Requarks/wiki#2242]
**Describe the bug**
When using the plantuml syntax to embed a hyperlink in an activity diagram, the link itself when rendered into the graphic is not interactive ie I cannot click it.

**To Reproduce**
1. use markdown editor
2. create a plantuml activity diagram
(sample code to use)

```plantuml
start
[[http://plantuml.com]]:Some activity;
:Some [[http://plantuml.com link]];
end
```

3. In viewer try to click link. It is not interactive.

**Expected behavior**
When clicking the link it should take action to direct to the specified URL

**Host Info (please complete the following information):**
 - OS: Linux - CentOS (core) 8.1.1911 x64
 - Wiki.js version: 2..4.105
 - Database engine: Microsoft SQL Server 2017

**Additional context**
https://plantuml.com/link

**Comment by bharatrajagopalan** [comment]
@mlafrance-complianceds  I think this is what you are looking for?

https://github.com/Requarks/wiki/pull/1337
