### ISSUE TITLE
How to get SSL working with both www and plain domain?

### ISSUE THREAD

**Issue by dr107** [Requarks/wiki#2245]
**Question**
Hey developers,

Wiki.js is working great so far, I'm just having a little trouble with the SSL config. The `docker create` invocation in the [AWS Install ](https://docs.requarks.io/install/aws) guide only has a place for one domain. I chose do use www.<my-domain> for this. However, when I go to <my-domain> in a browser (without the www), I get NET::ERR_CERT_COMMON_NAME_INVALID. I tried deleting and re-creating the docker container with `-e LETSENCRYPT_DOMAIN` twice, one for the plain domain and one for the www, but it was the same deal, and in the logs only the www is mentioned in the lets encrypt setup (and it re-uses the same cert). 

Is there any way to use the docker startup to get a cert that works for both the www and plain domains? 

**Host Info (please complete the following information):**
OS: Ubuntu 18.04 (default AWS install)
Wiki.js version: 2.4.107
Database engine: postgres 11.8

**Comment by NGPixel** [comment]
You can't use 2 domains at the same time. Choose either one and redirect the other to the primary.
