### ISSUE TITLE
Explain Navigation modes

### ISSUE THREAD

**Issue by MadsBen** [Requarks/wiki#2271]
Can someone explain the different navigation modes? - Some examples would really help.

Screen capture is from a 1920x1080 screen, but as you can see, the text is cut off.
![navigation_mode](https://user-images.githubusercontent.com/19872434/89531708-f58cf500-d7f0-11ea-9410-b36aed1c8baf.PNG)

Furthermore, the Docs mentions nothing about these different modes:
https://docs.requarks.io/guide/structure

Version: wiki.js 2.4.107

**Comment by NGPixel** [comment]
https://docs.requarks.io/en/navigation
