### ISSUE TITLE
AWS Privacy question

### ISSUE THREAD

**Issue by jezzaleong** [Requarks/wiki#2272]
Hi, 
The software looks great.
I'm thinking of using the AWS image for documentation. What is the privacy status? Can the wiki.js team access my data?

**Comment by prasadkumar013** [comment]
These are simply machines pre-configured with auto updating Wiki.js, db docker instances. There should be no privacy concern associated with this. However you can also manually deploy Wiki by yourself on AWS or any cloud provider if you chose to.
You can refer here for setup instructions for other platforms: https://docs.requarks.io/install

**Comment by NGPixel** [comment]
As @prasadkumar013 mentionned, these images are simply preconfigured images. They run on your own account and only you has access to it. This is the same as booting an empty Linux machine but with docker and wiki.js container already preloaded, nothing more.
