### ISSUE TITLE
Port in the URL.

### ISSUE THREAD

**Issue by kommandantjut** [Requarks/wiki#2273]
**How do you remove the port from the url?** 
In example to access it requires going to :3000 instead of just the url.
wiki.website.com:3000 instead of wiki.website.com

As a sidenote we use apache and nginx.

**Host Info (please complete the following information):**
OS: CentOS Linux release 7.8.2003 (Core)
Wiki.js version: 2.4.107
Database engine:  10.3.23-MariaDB - MariaDB Server

**Comment by Smankusors** [comment]
Hmm are you using Nginx as reverse proxy and Apache as the real web server? Or something else? If you use Nginx as reverse proxy, you can setup Nginx to do it like you did for Apache.

**Comment by kommandantjut** [comment]
Firstly I appreciate you reaching out
We did tried doing the following and it didn't appear to work.

```
{
listen 80;
server_name example.com;
server_name_in_redirect off;
proxy_set_header Host $host:$server_port;
location / {
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_pass http://localhost:3000;
}
access_log off;
}
```

**Comment by Smankusors** [comment]
How it's "didn't appear to work"? It's opened wrong site? Or there some error shown? Or something else?

**Comment by kommandantjut** [comment]
It still shows the port still. It requires you to use website.com:3000 to access the wiki

**Comment by Smankusors** [comment]
> It still shows the port still. It requires you to use website.com:3000 to access the wiki

Eh... Huh? Is website.com redirecting you to website.com:3000? Or you just want to block port 3000 went public?

**Comment by kommandantjut** [comment]
Going to wiki.website.com will redirect you to wiki.website.com:3000. What I want to do is hide that port from the URL, but still have the user sent there.

**Comment by kommandantjut** [comment]
I reconfigured wikijs to listen on port 443 for SSL instead of another port, but it shows me the directory tree for the subdomain rather than the home page of the wiki. I also tried port 80, but it did the same thing.

**Comment by Smankusors** [comment]
> I reconfigured wikijs to listen on port 443 for SSL instead of another port, but it shows me the directory tree for the subdomain rather than the home page of the wiki. I also tried port 80, but it did the same thing.
> 
> In console the following error:
> warn: listen EACCES: permission denied 0.0.0.0:80
> warn: listen EACCES: permission denied 0.0.0.0:443

eh you can't change it to 80 and 443 because on your system is already used by your nginx.

Btw, what is "site URL" you set on?

**Comment by kommandantjut** [comment]
When you say the site URL do you refer to what's used in nginx? Or are you referring to the actual site url.
We use a subdomain for our wiki.js if that matters.

P.s thank you so much for your help! We love wiki.js and are eager to get it working.

**Comment by Smankusors** [comment]
> When you say the site URL do you refer to what's used in nginx? Or are you referring to the actual site url.
> We use a subdomain for our wiki.js if that matters.
> 
> P.s thank you so much for your help! We love wiki.js and are eager to get it working.

the site URL I mean is on Wiki.js settings (Administration Area > General)

**Comment by kommandantjut** [comment]
It is : 
https://wiki.website.com
which matches what the url should be.

**Comment by Smankusors** [comment]
> It is :
> https://wiki.website.com
> which matches what the url should be.

But if you visit that URL it redirects you to https://wiki.website.com:3000? Hmm... Can you try with incognito? It could be browser cache 🤔

**Comment by kommandantjut** [comment]
Negative, when you visit that url it tries to bring you to the file directory for wiki.js 
The issue we are having is the port we are using is :3000 and the wiki only loads if you go to https://wiki.website.com:3000.
We want to be able to access the wiki with just typing the URL and not having to include or specify a port.

We tried nginx reverse proxy and we tried switching the port to apache's port numbers (8080 & 8443 respectively) and we tried just using port 80 and 443 in the config.

**Comment by Smankusors** [comment]
> Negative, when you visit that url it tries to bring you to the file directory for wiki.js
> The issue we are having is the port we are using is :3000 and the wiki only loads if you go to https://wiki.website.com:3000.
> We want to be able to access the wiki with just typing the URL and not having to include or specify a port.
> 
> We tried nginx reverse proxy and we tried switching the port to apache's port numbers (8080 & 8443 respectively) and we tried just using port 80 and 443 in the config.

hmm the directory for wiki.js... It seems you have misconfigured the reverse proxy. What is your current settings anyway?

**Comment by kommandantjut** [comment]
We tried both of the following neither worked.
```
 GNU nano 2.3.1                   File: /etc/nginx/vhosts/wikijs.conf

# Wikijs Nginx configuration file
server {
    listen      80;
    server_name wiki.website.org;

    location / {
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_pass http://127.0.0.1:3000/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_next_upstream error timeout http_502 http_503 http_504;
    }
}
```

```
  GNU nano 2.3.1                   File: /etc/nginx/vhosts/wikijs.conf
server {
        listen       80;
        server_name  wiki.website.org;
        location / {
            proxy_pass         http://127.0.0.1:3000;
            proxy_redirect     off;

            proxy_set_header   Host             $host;
            proxy_set_header   X-Real-IP        $remote_addr;
            proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;

            client_max_body_size       10m;
            client_body_buffer_size    128k;

            proxy_connect_timeout      90;
            proxy_send_timeout         90;
            proxy_read_timeout         90;

            proxy_buffer_size          4k;
            proxy_buffers              4 32k;
            proxy_busy_buffers_size    64k;
            proxy_temp_file_write_size 64k;
        }
}
```

**Comment by Smankusors** [comment]
what happens if you use my config?

```
proxy_set_header X-Forwarded-For $remote_addr;
proxy_set_header X-Forwarded-Host $host;
proxy_set_header Host $host;
#proxy_set_header X-Forwarded-HTTPS on;
proxy_set_header X-Forwarded-Proto $scheme;
#proxy_set_header X-Forwarded-Port 443;
proxy_set_header X-Url-Scheme $scheme;
proxy_pass http://127.0.0.1:3000;
proxy_pass_request_headers on;
```

**Comment by prasadkumar013** [comment]
Hi, were you able to get it resolved?
Are you currently using SSL/HTTPS on your domain name?
Here is a simple config I was able to use on one of my machines:

```
server {
        listen 80;
        server_name wiki.website.org;
        proxy_set_header Host   $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        location / {
                proxy_pass http://localhost:3000;
        }

}
```

**Comment by kommandantjut** [comment]
We tested each of your suggestions separately and the terminal spat out 
`nginx: [warn] conflicting server name "wiki.example.org" on 0.0.0.0:80, ignored`

Appreciate your help!

**Comment by Smankusors** [comment]
> We tested each of your suggestions separately and the terminal spat out
> `nginx: [warn] conflicting server name "wiki.example.org" on 0.0.0.0:80, ignored`
> 
> Appreciate your help!

eh huh? You seems to have duplicate configuration?

**Comment by kommandantjut** [comment]
You mean duplicate reverse proxy entry or something else?

**Comment by Smankusors** [comment]
> You mean duplicate reverse proxy entry or something else?

yes, you have duplicate server name somewhere in your nginx

**Comment by kommandantjut** [comment]
There isn't a duplicate for wiki.js in nginx:
The wiki.js subdomain was created through cpanel and the website has multiple other subdomains that all run on apache and nginx without issue.

**Comment by Smankusors** [comment]
> There isn't a duplicate for wiki.js in nginx:
> The wiki.js subdomain was created through cpanel and the website has multiple other subdomains that all run on apache and nginx without issue.

but you got "conflicting server name".

Maybe you can just grep wiki (use case insensitive) in Nginx config directory and make sure there isn't any duplicates?

**Comment by kommandantjut** [comment]
we found the autogenereated sub domain config. We changed the ports that were relevant to what is being processed 
It listens on 80 and proxies to 8080 and changed it 3000(http)and 3500(https) respectively.

This worked to an extent as it loads the title of the page but not the fav icon or the page itself. This is the case for both HTTP and HTTPS. However, if you visit the wiki using the ports the page still loads. 

Do you have any idea on the solution to the page being completely blank? 

Thanks again so much for your help!

**Comment by Smankusors** [comment]
eh which one became reverse proxy? Nginx or Apache2? That error come from Apache2...

Isn't this should be Nginx -> Wiki.js, not Nginx -> Apache2?

**Comment by kommandantjut** [comment]
Apache2 and Nginx run together. Nginx listens to port 80 and 443, apache2 works on port 8080 and 8443. In the subdomain config, Nginx proxy passes 8080 and 8443 respectively. I attempted to change that to 3000 and 3500 for Node.js instead. The title bar displays the correct page name, but the page content itself does not display.

**Comment by Smankusors** [comment]
btw, why did you use HTTPS behind reverse proxy? 🤔

**Comment by kommandantjut** [comment]
SSL isn't in use right now but it was figured that the configured SSL port in the wikijs conf should be used.
Regardless of that the content doesn't display on pages for http or https(ssl)

**Comment by Smankusors** [comment]
> SSL isn't in use right now but it was figured that the configured SSL port in the wikijs conf should be used.
> Regardless of that the content doesn't display on pages for http or https(ssl)

I mean... you don't need to enable HTTPS on your Apache2 and Wiki.js, just let Nginx handle it. Unless Apache2 and Wiki.js exposed directly to public network...

**Comment by kommandantjut** [comment]
It's just configured there and isn't in use. Access via HTTP regardless does not yield page content.

**Comment by Smankusors** [comment]
> It's just configured there and isn't in use. Access via HTTP regardless does not yield page content.

your Nginx should not contact Apache2 because Wiki.js have it's own web server...

btw, can you find something on the browser console / network tab (DevTools), maybe find something to troubleshoot further?

**Comment by KGBicheno** [comment]
Sorry if this has been covered, but my topology is router -> nginx reverse proxy box -> server with wiki

I have my router forwarding port 80 to nginx to the main server, which serves a website as per normal, but then in /etc/nginx/sites-available I have the file reverse-proxy.conf with the contents

```
server {
        server_name wiki.example.com;
        location / {
                proxy_pass http://192.168.1.8:3000;
        }

```

This passes the external request to the wiki's built-in server on port 3000 on the separate server hosting wiki.js. Oddly enough, I don't have port 3000 forwarded on my router and external traffic is still able to reach the wiki perfectly fine.

Mind you, I did have to set up my DNS host to have a cname record for wiki.example.com as well. Keep in mind you have to have a simlink from sites-availble to sites-enabled (Fairly sure you know that though).

Sorry if I've covered old ground here, but this has worked for me since day dot)

**Comment by kommandantjut** [comment]
![unknown (1)](https://user-images.githubusercontent.com/69328404/90339976-bfa2fa00-dfc2-11ea-814d-144d882a0134.png)
I killed any and all references to the subdomain in Apache while leaving the Nginx config in tact, but it still throws these 404s when trying to access anything.

**Comment by 3DSkaoi** [comment]
Here is what I'd do. 
- Confirm server_name is my config file.
- Validate listening ports.

If you get to your http://<IPAddress>, what do you have? Does it return Apache2 or NGINX page?

**Comment by kommandantjut** [comment]
It serves the file directory and Apache was killed leaving only Nginx config as previously stated.

**Comment by Smankusors** [comment]
> I killed any and all references to the subdomain in Apache while leaving the Nginx config in tact, but it still throws these 404s when trying to access anything.

btw if you open those 404 URLs on your browser, what is shown?

**Comment by kommandantjut** [comment]
As the files that are 404ing are in the /assets folder, the expected behaviour would be either a blank page as described or a 404 from either nginx or apache (since the browser console itself is unable to connect). However, upon opening one of the files it shows the code as if it is connecting properly.

**Comment by Smankusors** [comment]
> As the files that are 404ing are in the /assets folder, the expected behaviour would be either a blank page as described or a 404 from either nginx or apache (since the browser console itself is unable to connect). However, upon opening one of the files it shows the code as if it is connecting properly.

bear in mind that those asset files doesn't translate to physical location, and it should be handled by Wiki.js, not Nginx or Apache.

Also, it's `/_assets` not `/assets`.

**Comment by kommandantjut** [comment]
Hope everyones been well, just curious if anyone has any ideas @NGPixel @Smankusors 
Thank you!

**Comment by NGPixel** [comment]
Remove the try_files block, it doesn't make any sense to have this block on a reverse proxy to wiki.js. This isn't a Static HTML / PHP website...
```
        location / {
                try_files $uri @wawa;
        }
```

A simple config like below should work (replace `wiki.example.com` and `localhost:3000` with the proper values):
```
server {
        listen 80;
        server_name wiki.example.com;
        proxy_set_header Host   $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        location / {
                proxy_pass http://localhost:3000;
        }
}
```

If you can't get it to work, I suggest asking the help of someone who knows nginx to fix it for you, as this isn't a Wiki.js issue.
