### ISSUE TITLE
How do you 're'-create the menu from https://docs.requarks.io/?

### ISSUE THREAD

**Issue by BazzlineABS** [Requarks/wiki#2280]
Hello,

I'm a new user and I want to get some feeling of the possibilities of wiki,js.
So I start with trying to recreate some of an example I see.

So how do make the header 'Getting Started' in the main menu on https://docs.requarks.io/?
And how do I use the different icons in front of the menu items?

And more important is there any more documentation. I would like not to ask a question every time...

**Comment by sbonaime** [comment]
Click on the top right icon => administration => Navigation

**Comment by NGPixel** [comment]
https://docs.requarks.io/en/navigation
