### ISSUE TITLE
Not able to connect to git repository - fatal: unable to access

### ISSUE THREAD

**Issue by benchvondaranch** [Requarks/wiki#2281]
**Describe the bug**
Hi guys,

until today I was using wikijs v1 and thought it is time to move forward to v2. Unfortunately I am not able to connect to my .git repository. I am always getting the error message: fatal: unable to access 'https://@github.com/USERNAME/REPO' Could not resolve host: @github.com error: Could not fetch origin.

I have tried it via SSH and Basic Authentication with no success. Also setting up a new Git-Repository did not help to fix the problem...

Probably somebody could help me in this case... 
Best Regards

**To Reproduce**
1. Go to 'Administration Panel'
2. Select Storage option
3. Select "Git" as a Target.
4. Configure the connection attributes

**Expected behavior**
Connecting to Git with success :-)

**Host Info (please complete the following information):**
 - OS: Ubuntu 18.04, Docker
 - Wiki.js version: 2.4.107
 - Database engine: postgres 11.8
 - nginx as a reverse proxy

**Comment by sbonaime** [comment]
Can you put a screenshot of your git settings ? I don't have any problem with my github configuration

**Comment by Smankusors** [comment]
wait what? https://@github.com? Are you sure the address is correct?

**Comment by sbonaime** [comment]
For the git url I have git@github.com:MY_USER/MY_REPOT.git

**Comment by Enzosbruder** [comment]
> wait what? https://@github.com? Are you sure the address is correct?

This is just what the error message says...I copied the URI from Git itself so the URI is correct.

**Comment by Enzosbruder** [comment]
> Can you put a screenshot of your git settings ? I don't have any problem with my github configuration

sure...here we go:

![gitconfig_part1](https://user-images.githubusercontent.com/31693685/89794890-fa6ee300-db27-11ea-815c-648b41663da5.png)
![gitconfig_part2](https://user-images.githubusercontent.com/31693685/89794894-fba01000-db27-11ea-8eda-6921a468235e.png)

**Comment by sbonaime** [comment]
1. change the authentification type. See the documentation here https://docs.requarks.io/en/storage/git 
1. change the repository url to git@github.com:Enzosbruder /WikiJs.git

Check the documentation

**Comment by NGPixel** [comment]
As @sbonaime mentionned, you should be using SSH auth. There's no reason to be using basic auth with Github.

**Comment by Enzosbruder** [comment]
> As @sbonaime mentionned, you should be using SSH auth. There's no reason to be using basic auth with Github.

In my first try i used SSH auth (that is what I have described) but thought I got the same error.

I have tried once again and for some reason get an error when trying to use the path mode.

"Load key "path to the key in the docker container": Permission denied git@github.com: Permission denied (publickey) " - i definitely did something wrong...As the error message says I guess there is a lack of permission... as soon as I have figured it out I will paste my solution here...


Finally I tried it with the content option and it works now!

Thank you guys for your help...although I still do not understand why it is only working with ssh and contents mode...

**Comment by Enzosbruder** [comment]
*UPDATE*

OK - Layer 8 Problem... as wikijs runs in the docker container it was not able to access my private key. I needed to change the file permissions to read for others to make it work.


So connecting with Git works with SSH now for both the path and the contents mode. 


BUT I still do not know why basic auth is not working...but as I have a working solution this is ok for me.


Thanks again guys

**Comment by Smankusors** [comment]
nice, if your issue is solved, feel free to close this issue 🙂

**Comment by parksj10** [comment]
Thanks for the pointer @benchvondaranch, more details here for my fix:

for anyone else stumbling upon this and following the guide here [https://docs.requarks.io/storage/git](https://docs.requarks.io/storage/git), I had made the `/etc/wiki/github.pem` via `ssh`. I had to modify this to read for all users:

```sh
chmod 744 /etc/wiki/github.pem
```
