### ISSUE TITLE
Unable to get inline scripts to execute.

### ISSUE THREAD

**Issue by aaSpider15** [Requarks/wiki#2286]
**Question**
I am in the process of migrating from wiki.js 1.0 to wiki.js 2.4. Previously I have used several inline <script> sections to render elements on the page however I have been unable to get any inline scripts to work with the new version.

I have turned off Sanitize HTML under Rendering->html->Security and I can see the script sections in the source however they do not execute and are not in the DOM.

Is there a way to get inline scripts to work?

**Host Info:**
OS: Windows Server 2016
Wiki.js version: 2.4.107
Database engine: MySQL 8.0.21

**Comment by NGPixel** [comment]
Inline scripts will be possible in the upcoming 2.5 release. They will not work on current releases.

**Comment by aaSpider15** [comment]
Thank you Nicolas for your response. I will wait until the new release.
