### ISSUE TITLE
User cannot login using LDAP auth

### ISSUE THREAD

**Issue by YuriMri** [Requarks/wiki#2290]
**Describe the bug**
One of our users in domain environment cannot log in to Wiki.js recently (for about 2 weeks).
Other users so far don't have this problem.

One user receives error:
insert into "users" ("createdAt", "email", "isActive", "isSystem", "isVerified", "localeCode", "name", "pictureUrl", "providerId", "providerKey", "tfaIsActive", "updatedAt") values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12) returning "id" - invalid byte sequence for encoding "UTF8": 0x00

**To Reproduce**
1. Go to wiki.js page
2. Click on LDAP/Active Directory
3. enter username + PW
4. Click Log In

**Expected behavior**
Login to wiki

**Screenshots**
![image](https://user-images.githubusercontent.com/69195129/90108914-48affc00-dd4b-11ea-9ee8-082e3d119eaf.png)

**Host Info (please complete the following information):**
 - OS: 
> NAME="CentOS Linux"
VERSION="8 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="8"

 - Wiki.js version: 2.4.107 (also testing wiki has same issue version 2.3.81), Node.js = 14.6.0 (also testing wiki has same issue version 12.18.0)
 - Database engine: postgresql 12.3

**Additional context**

**Comment by NGPixel** [comment]
This is a known bug related to the user picture field containing binary data. Replace the Avatar Picture Field Mapping with something else in the meantime.

#849
