### ISSUE TITLE
Change Auth0 logo in login page

### ISSUE THREAD

**Issue by Simerca** [Requarks/wiki#2291]
**Question**
Hi !
We want to change Auth0 logo inside login page, 
We have make change inside the definition.yml but the logo appear only on admin settings page.

2scnd question,
is it possible to set auth0 as default provider.

Thank you by advance !

**Host Info (please complete the following information):**
OS: [e.g. Ubuntu 18.04, Docker]
Wiki.js version: [e.g. 2.0.1]
Database engine: [e.g. postgres 9.7, mysql 5.7]

**Comment by NGPixel** [comment]
Both will be possible in the upcoming 2.5 release.
