### ISSUE TITLE
Issue trying use FB and github authentication on DEV & PROD environment 

### ISSUE THREAD

**Issue by Khayz** [Requarks/wiki#2292]
**Question**
Hi, I'm trying to add facebook and github authentication on my prod env, but when i set all the configuration, passing the ID and Token by the FB app or github, when i try to login this doesn't works, the callback url its been executed, sends an error saying "this site can't be reached"  

![image](https://user-images.githubusercontent.com/42689081/90154345-a21a2a00-dd4f-11ea-8afe-6f0974abace6.png)

**Host Info (please complete the following information):**
OS: [e.g. Ubuntu 18.04, Docker]
Wiki.js version: [e.g. 2.0.1]
Database engine: [e.g. postgres 9.7, mysql 5.7]

**Comment by Smankusors** [comment]
It's non existent domain, probably you mistyped the domain name. Please make sure your callback URL is correct.

**Comment by Khayz** [comment]
Yes, was i mistyped the domain, now taking your attention, I'm using the
dev version of wikijs, and when i try to login with some strategy, the app
throw me an error message, saying this, can i do something to resolve this
issue?, btw thanks for the help!
[image: image.png]

**Comment by Smankusors** [comment]
eh no, you can't send images via email. It's not shown here....

**Comment by NGPixel** [comment]
The dev version is not ready and should not be used. Please don't report issues concerning the dev branch.

**Comment by Khayz** [comment]
Thanks for the answers!, so a last question, in the documentation of wikijs
said something about developers, you can clone the github repository and
get access to all the code about the wiki, and modified, are 4 sections in
the development field on the documentation page, and one of this said
something about create your own auth strategy, but in this case if i want
to use github strategy didn't work, and if i create my own strategy and use
them, got the same issue, so why is the purpose of the dev env if cannot
use or improve some features, can i use this dev branch for deploy on
heroku or its only to play with the wiki, see how works from behind the
scenes, like if i add a new auth way or added a new feature this cannot be
deployed and used right? ,and the only way for deploy the app is using the
version of wiki that you provided for deploy in heroku, docker, etc?

**Comment by NGPixel** [comment]
The login system is currently being reworked which is why it doesn't work.
