### ISSUE TITLE
Self promotion security bug

### ISSUE THREAD

**Issue by sgeofrank** [Requarks/wiki#2294]
**Describe the bug**
A user with write groups can self promote to manage groups and manage administration features. The write:groups feature suggests they can only edit content permissions and shouldn't be able to mess with user or administration permissions

**To Reproduce**
1. Provision a user group with some content permissions and write:users, manage:users, and write:groups.
2. Add a user to that group, and only that group.
3. Log in as that user, and go to administration.
4. Have them change the permissions of their own user management group to allow them to manage:groups, manage:navigation, manage:theme, manage:api

**Expected behavior**
A user with only write:groups cannot manage any settings in Users or Administration, on Content.

**Screenshots**

**Host Info (please complete the following information):**
 - OS: Docker (Linux)
 - Wiki.js version: 2.4.107
 - Database engine: postgres 11.6

**Additional context**

**Comment by NGPixel** [comment]
Fixed in 2.5.132
