### ISSUE TITLE
systemctl start wiki.service fails

### ISSUE THREAD

**Issue by jronpaul** [Requarks/wiki#2296]
hello,
if i run node server it works fine..
if i create a systemctl file .. it fails but doesnt give me much info.
here is the file.. im on a rhel 7.8 machine.

cat /etc/systemd/system/wiki.service
[Unit]
Description=Wiki.js
After=network.target

[Service]
Type=simple
ExecStart=/usr/local/node-v12.18.3-linux-x64/bin/node server
Restart=always
# Consider creating a dedicated user for Wiki.js here:
User=nobody
Environment=NODE_ENV=production
WorkingDirectory=/opt/wiki

[Install]
WantedBy=multi-user.target

here is the status

● wiki.service - Wiki.js
   Loaded: loaded (/etc/systemd/system/wiki.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since Fri 2020-08-14 17:16:42 EDT; 6min ago
  Process: 8172 ExecStart=/usr/local/node-v12.18.3-linux-x64/bin/node server (code=exited, status=1/FAILURE)
 Main PID: 8172 (code=exited, status=1/FAILURE)

Aug 14 17:16:42 wiki.js.domain.com systemd[1]: wiki.service: main process exited, code=exited, status=1/FAILURE
Aug 14 17:16:42 wiki.js.domain.com systemd[1]: Unit wiki.service entered failed state.
Aug 14 17:16:42 wiki.js.domain.com systemd[1]: wiki.service failed.
Aug 14 17:16:42 wiki.js.domain.com systemd[1]: wiki.service holdoff time over, scheduling restart.
Aug 14 17:16:42 wiki.js.domain.com systemd[1]: Stopped Wiki.js.
Aug 14 17:16:42 wiki.js.domain.com systemd[1]: start request repeated too quickly for wiki.service
Aug 14 17:16:42 wiki.js.domain.com systemd[1]: Failed to start Wiki.js.
Aug 14 17:16:42 wiki.js.domain.com systemd[1]: Unit wiki.service entered failed state.
Aug 14 17:16:42 wiki.js.domain.com systemd[1]: wiki.service failed.

**Comment by coamtaker618** [comment]
I don't have my config in front of me, but it may be as simple as changing user from nobody to, well, an existing user  on the line `User=nobody`

Also, I find "journalctl -xe" to be much more detailed than "systemctl status" for systemd/systemctl failures.  Maybe that will give you more insight?

**Comment by jronpaul** [comment]
ok.. i tried that...  it didnt work..  journalctl -xe does provide more info.. but im not sure why it says
" Error: Cannot find module '/opt/wiki/server'"
its there... thats the correct path.. if i run node manually it works. but i did notice that i need to be in /opt/wiki
for node to work manually as well because it expects to see a config.yml in whatever my PWD is..
any other suggestions?
thanks

[root@wiki system]# journalctl -xe
Aug 17 08:45:03 wiki.fqdn.com node[15966]: internal/modules/cjs/loader.js:968
Aug 17 08:45:03 wiki.fqdn.com node[15966]: throw err;
Aug 17 08:45:03 wiki.fqdn.com node[15966]: ^
Aug 17 08:45:03 wiki.fqdn.com node[15966]: Error: Cannot find module '/opt/wiki/server'
Aug 17 08:45:03 wiki.fqdn.com node[15966]: at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
Aug 17 08:45:03 wiki.fqdn.com node[15966]: at Function.Module._load (internal/modules/cjs/loader.js:841:27)
Aug 17 08:45:03 wiki.fqdn.com node[15966]: at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
Aug 17 08:45:03 wiki.fqdn.com node[15966]: at internal/main/run_main_module.js:17:47 {
Aug 17 08:45:03 wiki.fqdn.com node[15966]: code: 'MODULE_NOT_FOUND',
Aug 17 08:45:03 wiki.fqdn.com node[15966]: requireStack: []
Aug 17 08:45:03 wiki.fqdn.com node[15966]: }
Aug 17 08:45:03 wiki.fqdn.com systemd[1]: wiki.service: main process exited, code=exited, status=1/FAILURE
Aug 17 08:45:03 wiki.fqdn.com systemd[1]: Unit wiki.service entered failed state.
Aug 17 08:45:03 wiki.fqdn.com systemd[1]: wiki.service failed.
Aug 17 08:45:03 wiki.fqdn.com systemd[1]: wiki.service holdoff time over, scheduling restart.
Aug 17 08:45:03 wiki.fqdn.com systemd[1]: Stopped Wiki.js.

**Comment by coamtaker618** [comment]
What did you change the 'User=nobody' line to?

Also try moving the "WorkingDirectory" line above the "ExecStart" line (and the Environment line) so that "WorkingDirectory" is 

> but i did notice that i need to be in /opt/wikifor node to work manually as well because it expects to see a config.yml in whatever my PWD is..

"PWD" is short for "Path of Working Directory" aka, "your current location in the file system".  With any luck moving that line (or changing the user) will fix the PWD issue!

**Comment by jronpaul** [comment]
ok... moving the PWD up in the config and changing the permissions of the wiki DIR to the wiki owner worked !!

now its running from the start script..  
thanks a lot for all your help !

**Comment by coamtaker618** [comment]
@jronpaul glad that worked :)

**Comment by maicol07** [comment]
Hi,

I have the same problem but the suggestion given here: https://github.com/Requarks/wiki/issues/2296#issuecomment-675202039 didn't work. How can this be solved?

Thanks

My service file:

```
[Unit]
Description=Wiki.js
After=network.target

[Service]
Type=simple
Restart=always
StartLimitIntervalSec=0
# Consider creating a dedicated user for Wiki.js here:
User=wikijs
WorkingDirectory=/var/www/html/docs
Environment=NODE_ENV=production
ExecStart=/usr/bin/node server

[Install]
WantedBy=multi-user.target
```

**Comment by coamtaker618** [comment]
@maicol07 just to confirm in your case, does manually running the command below start your server?  From what I'm piecing together from your script, I believe it should?

`/usr/bin/node /var/www/html/docs/server`

**Comment by maicol07** [comment]
> @maicol07 just to confirm in your case, does manually running the command below start your server?  From what I'm piecing together from your script, I believe it should?
> 
> `/usr/bin/node /var/www/html/docs/server`

Well, I use `sudo node server` in the `docs` directory

**Comment by maicol07** [comment]
Changing `User=wikijs` to `User=root` solved the issue

**Comment by coamtaker618** [comment]
@maicol07 I suspect someone here can tell you the dangers of running wikijs as sudo, but I'm leave that to them.  I'm just glad you got systemctl working :)
