### ISSUE TITLE
Email Template lost some image

### ISSUE THREAD

**Issue by RainshawGao** [Requarks/wiki#2298]
**Describe the bug**
In https://github.com/Requarks/wiki/blob/dev/server/templates/test.html#L236 and https://github.com/Requarks/wiki/blob/dev/server/templates/account-verify.html#L236
there is a `<%= logo %>`, but in https://github.com/Requarks/wiki/blob/dev/server/core/mail.js#L59 
the `logo` was passed as null, so in receiver's mailbox, the image was lost.

**To Reproduce**
1. Go to admin panel and fill the mail
2. Click on 'send test mail'
3. Go to the mailbox and check the test mail

**Expected behavior**
There is a logo in the header of mail.

**Screenshots**

**Host Info (please complete the following information):**
 - OS:  Docker
 - Wiki.js version: 2.4.107
 - Database engine: postgres 11
**Additional context**

**Comment by kumaranshu72** [comment]
@NGPixel I would like to pick this up.

**Comment by NGPixel** [comment]
Fixed by ae733392f32b3c3079d22376c903067992a7cfe1
