### ISSUE TITLE
All pages public

### ISSUE THREAD

**Issue by gm7** [Requarks/wiki#2299]
**Question**
I have a fresh installation of wiki.js version 2.4.107 running behind an Nginx reverse-proxy. The Letsencrypt Certbot was used to add certificates to the domain inside Nginx. The redirection of HTTP to HTTPS is also enabled inside Nginx.
Wiki.js is installed locally on port 3000 using a postgres (12) database. The forwarding is working well and there are no issues with the rendering.

The problem is that you do not need to log in to access *any* page. All web pages have public access, including the configuration of the wiki. In other words, an anonymous user can administer my wiki site. 

Could you point me to what I have wrong in my configuration?

**Host Info (please complete the following information):**
OS: Ubuntu 20.04
Wiki.js version: 2.4.107 (local installation using node v10.19.0)
Database engine: postgres 12.2

**Comment by supersasho** [comment]
To disable the public access you need to alter the Guest account, please see documentation below on how to do it.

https://docs.requarks.io/groups#private-wiki
