### ISSUE TITLE
Users cannot edit pages

### ISSUE THREAD

**Issue by OfficialCRUGG** [Requarks/wiki#2303]
**Question**
Hey there! I'm currently using WikiJS and created some Pages with the Admin Account. I've also created a Role with all Permissions except that one that can't be enabled. It has Write Access. However, when a User in that Group tries to edit one of the Pages, they get an Error daying that they don't have Access.

**Host Info (please complete the following information):**
OS: Debian 9, Docker 19.03.12
Wiki.js version: 2.4.107
Database engine: MySQL Ver 8.0.20 for Linux on x86_64 (MySQL Community Server - GPL)

**Comment by Smankusors** [comment]
have you already set the page rules?

**Comment by OfficialCRUGG** [comment]
Page rules? Where can I find that?

**Comment by Smankusors** [comment]
> Page rules? Where can I find that?

the same page when you set the permissions, well it's next tab from permissions...

**Comment by NGPixel** [comment]
https://docs.requarks.io/groups
