### ISSUE TITLE
Change font styles application wide

### ISSUE THREAD

**Issue by roshanjonah** [Requarks/wiki#2307]
**Question**
What is the easiest way to change font styles from Roboto to Lato? I can't find the client folder or the scss files on the docker digital ocean image? Any help would be much appreciated. I just want to keep branding consistent across sites. 

**Host Info (please complete the following information):**
OS: Ubuntu 18.04 Docker - DigitalOcean Marketplace Image
Wiki.js version: latest as of 19 Aug 2020
Database engine: postgres

**Comment by Smankusors** [comment]
You can do CSS injection via Administration > Theme

**Comment by roshanjonah** [comment]
Tried that but it doesn't change all the interface and administration part of it, unfortunately :(

**Comment by Smankusors** [comment]
ou, the administration area will not get CSS injection btw

**Comment by roshanjonah** [comment]
Yea realized that by now :) Thanks for your help!
