### ISSUE TITLE
Error saving with JSON code block

### ISSUE THREAD

**Issue by roshanjonah** [Requarks/wiki#2311]
**Describe the bug**
It wouldn't save if I have a JSON code block while using a markdown page.

**To Reproduce**
1. Create a new page and choose "Markdown" as the type
2. Insert an example JSON code inside a code block or inline code 
3. Save the page

**Expected behavior**
To save successfully

**Screenshots**
<img width="1487" alt="Edit_Mailwizz_Development___Internal_Knowledgebase" src="https://user-images.githubusercontent.com/20136098/90705475-1e2fe700-e2e7-11ea-8fb6-3cc17e495dfa.png">

**Host Info (please complete the following information):**
 - OS: Ubuntu 18.04 Docker DigitalOcean Image
 - Wiki.js version: Latest DigitalOcean image as at 20 Aug
 - Database engine: Postgres

**Comment by NGPixel** [comment]
Are you using Cloudflare or some other firewall in front of wiki.js?

**Comment by roshanjonah** [comment]
Umm, yes I am using Cloudflare for sure. I will try disabling performance and see if that fixes it. Do you think they are messing with the JS files? As soon as I remove the code block, it saves without issues!

**Comment by NGPixel** [comment]
You need to whitelist your IP address.

Cloudflare well block requests that looks malicious, and that includes code blocks in this case.

**Comment by roshanjonah** [comment]
For anyone else having similar issues, this is how you get yourself unblocked from CF Firewall Rules

<img width="1077" alt="Firewall___jonahnz_com___Account___Cloudflare_-_Web_Performance___Security" src="https://user-images.githubusercontent.com/20136098/90706719-ef674000-e2e9-11ea-9182-40c22dd106f5.png">
