### ISSUE TITLE
user and group permissions

### ISSUE THREAD

**Issue by jronpaul** [Requarks/wiki#2314]
Hi,
im trying to isolate groups to specific pages..
which i have working however I can only log in via the direct path.. not the home page..
is there anyway to get users to be put in their designated area?
for example, if i have a user in a group that is only allowed to see /home/IT
i get denied if i try to log in as the user on the default page but if i do http://ip/home/IT
it works.. It seems like a bug but im not sure.

Host Info (please complete the following information):
Red Hat Enterprise Linux Server release 7.7 (Maipo)
Wiki.js 2.4.107
postgres12

**Comment by NGPixel** [comment]
You need to give read access to the homepage (`/home`) to everyone, as this is the default landing page upon login. In 2.5 update, you'll be able to redirect groups directly to specific paths upon login.

Also, I would avoid using `home` as a root directory. It's unnecessary to add another layer... Just keep in mind you can't use 2 letters folder in root.
