### ISSUE TITLE
Possible to crash a wiki by placing JS in the Site Title

### ISSUE THREAD

**Issue by someguynamedmatt** [Requarks/wiki#2315]
**Describe the bug**
An administrator can put incorrect input into the Site Title and create an irrecoverable crash in the wiki. **Don't do this unless you have an easy way of getting into the source. This will make the wiki inoperable.**

**To Reproduce**
1. Go to a Wiki's Dashboard
2. Click on General
3. Put some arbitrary HTML/JS as the Site Title value, e.g. "<script>console.log('hi')</script>" (quotes for emphasis, don't use)
4. Save the page
5. Refresh the page
6. See error on the page and in the console (see screenshots, below)

**Expected behavior**
Input should be sanitized

**Screenshots**
(any page on the wiki renders as...)
![Screen Shot 2020-08-20 at 14 41 43](https://user-images.githubusercontent.com/17413539/90828775-6bb25100-e2f3-11ea-89be-5b97b425bba9.png)

![Screen Shot 2020-08-20 at 14 44 41](https://user-images.githubusercontent.com/17413539/90828925-b764fa80-e2f3-11ea-9612-52216077e167.png)

**Comment by NGPixel** [comment]
Not sure why you would do that in the first place, but fixed by 8c205b69505b8c2873c0fb5461e482fe545ee683
