### ISSUE TITLE
Email address saved in Chrome keeps getting autofilled to top search bar

### ISSUE THREAD

**Issue by saulimus** [Requarks/wiki#2324]
**Describe the bug**
The search field on top sometimes randomly autofills with my saved user/password when browsing pages in Chrome.

**To Reproduce**
1. Open site in Chrome
2. Register new user and save user/pass to Chrome
3. Go to your own user profile
4. Click around and at some point the top search bar should fill with the email address, and most likely also complain that there are no pages that fit your search query.

**Expected behavior**
The email address should only be filled when on the login page, nowhere else.

**Screenshots**
![Screenshot 2020-08-22 at 20 43 14](https://user-images.githubusercontent.com/2675404/90962386-3efb6680-e4b8-11ea-9ac4-a91d3db825a9.png)
![Screenshot 2020-08-22 at 20 42 25](https://user-images.githubusercontent.com/2675404/90962388-40c52a00-e4b8-11ea-92d4-d2b32a9034c8.png)

**Host Info (please complete the following information):**
 - OS: Mac OS X 10.14.6 + Docker
 - Wiki.js version: 2.4.107
 - Database engine: PostgreSQL 11 Alpine

**Additional context**
None.

**Comment by NGPixel** [comment]
Fixed by 48d93877e33fdeb642001ade7a2a6d40d0a38aec
