### ISSUE TITLE
Invalid email address when adding a user

### ISSUE THREAD

**Issue by jonathan-arrender-smith** [Requarks/wiki#2327]
**Question**
I am trying to add a new user to a very straightforward install of Wiki.js in a Digital Ocean droplet. The user has a valid gmail address. I have had no problem adding other users, even those with similar gmail addresses.

**Host Info (please complete the following information):**
OS: Ubuntu 20.04 LTS 
Wiki.js version: 2.4.107
Database engine: sqlite

**Comment by Smankusors** [comment]
hmm adding a screenshot would be helpful here...

**Comment by NGPixel** [comment]
Closing as no further info was provided.
