### ISSUE TITLE
Azure Login Callback

### ISSUE THREAD

**Issue by jungival** [Requarks/wiki#2332]
Hi there

I have successfully installed wiki.js on a local machine with the IP 192.168.2.7 Now I want to configure the access via Azure and I followed the instructions exactly. After I have done the configuration and entered the login information I am referred to the Callback URI https://192.168.2.7/login/azure/callback which gives me an error (no permission Unable to connect Firefox can’t establish a connection to the server at 192.168.2.7.)Chrome Error: This site can’t be reached192.168.2.7 refused to connect.

**Did I miss something during the installation to configure?**

**Host Info (please complete the following information):**
OS: Ubuntu 20.04.1 LTS (desktop)
Wiki.js version: 2.4.107
Database engine:PostgreSQL 11.9; Node.js 12.18.0
using: firefox and chrome

**Comment by Smankusors** [comment]
https or http? Do you use HTTPS to access your Wiki.js?

**Comment by jungival** [comment]
Hi
Bingo! I don’t use HTTPS yet and this must be the cause.

I followed this guide: https://docs.requarks.io/install/ubuntu
And will follow. This guide now to establish HTTPS: https://docs.requarks.io/install/config

Thanks alot!
