### ISSUE TITLE
Missing SSL on docker

### ISSUE THREAD

**Issue by pbdco** [Requarks/wiki#2333]
Hi, I have installed Wiki using docker on ubuntu according to this guide: https://docs.requarks.io/install/ubuntu but SSL is not working. How should I install it? Thanks

PS: Nice app!

**Comment by andeedotnet** [comment]
Hi pbdco, you can use nginx or traefik als reverse proxy to your docker container:

https://www.digitalocean.com/community/tutorials/docker-explained-how-to-containerize-and-use-nginx-as-a-proxy
https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-18-04
https://www.digitalocean.com/community/tutorials/how-to-use-traefik-as-a-reverse-proxy-for-docker-containers-on-ubuntu-18-04

**Comment by pbdco** [comment]
Hi @andeedotnet thank you very much for your kind reply, I will use nginx. 

Anyways, how can docker listen to port 80 without a reverse proxy installed as a server? I'm very new into docker and I have this serious doubt 😳  
I have installed Wiki using the mentioned guide on my post, and if I access from the IP i can actually work on Wiki (without ssl obviously).. 🤔

**Comment by andeedotnet** [comment]
You can start docker container with the option -p <yourporthere>:3000

EDIT: Wiki.js supports ssl directly. Just configure it in https://docs.requarks.io/install/config#advanced

**Comment by BuhtigithuB** [comment]
@NGPixel, I craft nginx.conf and tweak docker-compose.yml incorporating nginx as a reverse proxy... Are you taking it as a contrib?

**Comment by BuhtigithuB** [comment]
@pbdco, the only tricky part with nginx container is that your redirection to wikijs container shall use the name you specified for the wiki container in the docker-compose.yml...

proxy_pass http://**wiki**:3000;

Where **wiki** is the name give in the docker-compose.yml : 

```
...
  wiki:
    image: requarks/wiki:2
    depends_on:
      - db
    environment:
...
```

So nginx will finally understand that you refer to docker network...

**Comment by NGPixel** [comment]
> @NGPixel, I craft nginx.conf and tweak docker-compose.yml incorporating nginx as a reverse proxy... Are you taking it as a contrib?

Wiki.js doesn't need a reverse-proxy. The only reason to use one is when you need a very custom configuration or you have other sites running on the same server.

Custom certificates and Let's Encrypt are already supported natively by Wiki.js.

**Comment by ryprfpryr** [comment]
Thank you all!
