### ISSUE TITLE
Comment alert

### ISSUE THREAD

**Issue by MurashovAlexander** [Requarks/wiki#2338]
**Question**
How do I set up sending mail notifications to receive alerts when I write comments?
A notice must be sent to all article authors and all commentators.

**Host Info (please complete the following information):**
OS: CentOS 7
Wiki.js version: 2.4.105
Database engine: postgres 9.2.24
Provider: only GitLab

**Comment by NGPixel** [comment]
See https://requarks.canny.io/wiki/p/review-all-site-comments
