### ISSUE TITLE
How do I install wiki.js via helm?

### ISSUE THREAD

**Issue by rx570gtx1060** [Requarks/wiki#2339]
**Question**
I attempted to install Wiki.js via helm by going to the Wiki.js helm repo page.However, when I clicked on the link ,i couldn't as the documentation didn't clearly state on how to install it correctly.The address of the repo that was meant to be fetched using helm repo add command weren't stated in the documentation.It also didn't make clear what steps had to be taken to install wiki.js via helm,therefore making me very lost.
**Host Info :**
OS: [OpenSuse Leap 15.2, Helm]
Wiki.js version: [e.g. 2.0.1]
Database engine: [e.g. postgres 9.7]

**Comment by jochen-st** [comment]
As written on https://github.com/Requarks/wiki/tree/dev/dev/helm#introduction you will need to clone the github repo to your local machine.

The helm chart ist not available in an online repo (yet).

So please:
- `git clone https://github.com/Requarks/wiki.git`
- `cd dev/helm`
- Follow the instruction, e.g. `helm install myrelease .`

**Comment by rx570gtx1060** [comment]
Thank you
