### ISSUE TITLE
Big Tables break Mobile UI

### ISSUE THREAD

**Issue by tionis** [Requarks/wiki#2340]
**The Problem**
When Tables have too much content in them, they break the UI on small Screens.

**To Reproduce**
Create a table with much text in many columns and open it on a small screen

**Expected behavior**
The tables should get their own scrollbars independent from the rest of the page

**Screenshots**
![Phone Screenshot](https://i.imgur.com/ZuU9ak6.jpg)

**Host Info:**
 - OS: Docker(Linux)
 - Wiki.js version: 2.4.107
 - Database engine: postgres 11.8

**Comment by Gururek** [comment]
I am also having the same problem.

**Comment by tionis** [comment]
Duplicate of #1314 .
