### ISSUE TITLE
Pandoc and Puppeteer extensions not detected

### ISSUE THREAD

**Issue by tech62** [Requarks/wiki#2344]
**Describe the bug**
After execute npm i puppeteer, the extension wasn't detected.
[MASTER] info: Optional extension puppeteer was not found on this system. [ SKIPPED ]

**To Reproduce**
apt-get install build-essential make gcc
Install latest wiki.js version and nodejs14
npm i puppeteer && npm i pandoc

npm i puppeteer

> puppeteer@5.2.1 install /var/wikijs/node_modules/puppeteer
> node install.js
> 
> Downloading Chromium r782078 - 126.4 Mb [====================] 100% 0.0s
> Chromium (782078) downloaded to /var/wikijs/node_modules/puppeteer/.local-chromium/linux-782078
> npm WARN eslint-plugin-import@2.20.2 requires a peer of eslint@2.x - 6.x but none is installed. You must install peer dependencies yourself.
> npm WARN eslint-plugin-vue@6.2.2 requires a peer of eslint@^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
> npm WARN pug-loader@2.4.0 requires a peer of pug@^2.0.0 but none is installed. You must install peer dependencies yourself.
> npm WARN pug-plain-loader@1.0.0 requires a peer of pug@^2.0.0 but none is installed. You must install peer dependencies yourself.
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/@babel/cli/node_modules/fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> 
> 

**Expected behavior**
 [MASTER] info: Optional extension puppeteer was not found on this system. [OK]

**Host Info :**
 - OS: [Debian Buster]
 - Wiki.js version: [2.4.107]
 - Database engine: [mysql  Ver 15.1 Distrib 10.3.23-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2]

**Comment by NGPixel** [comment]
Not a bug. Extensions are not finished and neither puppeteer or pandoc are implemented yet. Only git is completed and detected properly.

**Comment by tech62** [comment]
Just for information, sharp is properly detected
