### ISSUE TITLE
How to reference the Wiki.js style sheet in our 3rd party documentation site

### ISSUE THREAD

**Issue by jord8on** [Requarks/wiki#2346]
**Question**
Disclaimer: I'm not a software developer. I mostly work on the front end, with HTML and CSS. 

We like the styling used in our Wiki.js instance and are using this as our main documentation repo. We'd like to be able to copy/paste content directly from wiki.js into our community application where we serve up our user guides. 

We really like the styling for the .tabset-tabs and the various blockquotes, in the Wiki.js documentation.

Can the styling for these components be easily referenced in the </head> of our customer-facing documentation platform?

Currently, we reference some other stylesheets in the HEAD of our current site, following this convention...

`$('<link href="https://SAMPLE-URL.css" rel="stylesheet">').prependTo('head');`

Any suggestions here would be great!

**Host Info (please complete the following information):**
OS: DigitalOcean - Docker/Linux (one-click wiki.js installation from their marketplace)
Wiki.js version: 2.4.107
Database engine: PostgresSQL 11.8, Node.js 12.18.0

**Comment by Smankusors** [comment]
you could do head HTML injection via Administration Area > Theme

**Comment by jord8on** [comment]
> you could do head HTML injection via Administration Area > Theme

@Smankusors could you help me with a code snippet that I could inject in our /HEAD, which would reference the style guide?

<link type="text/css" rel="stylesheet" href="**STYLESHEET.CSS**">

is there a simple bit of code like that ⬆︎  which we could use? Would we be referencing the CSS here on github or the stylesheet/s from our site?

We are using wiki.js as our documentation repo and this documentation will be visible to customers, via ZenDesk. So if I could put a snippet(s) in the /Head of Zendesk, and maintain styling, that would be ideal!

**Comment by Smankusors** [comment]
> `<link type="text/css" rel="stylesheet" href="**STYLESHEET.CSS**">`

hmm what's the problem with this?

**Comment by jord8on** [comment]
@Smankusors - I don't know what to replace with `STYLESHEET.CSS`  ¯\_(ツ)_/¯

**Comment by Smankusors** [comment]
I thought you already have an external CSS file hosted somewhere? Then you just replace that with the URL?

**Comment by jord8on** [comment]
Oh I see how I threw you off! I did mention that we were referencing an externally hosted css file.

I'm trying to figure out if there's a way to reference the default CSS of Wiki.js in the /Head of our new site. But I don't know that the source of the wiki.js file is... that we should be using for "STYLESHEET.CSS" (which encapsulates the default styling of wiki.js)

**Comment by Smankusors** [comment]
I mean, just replacing the STYLESHEET.CSS with your externally hosted css file URL should works?

**Comment by jord8on** [comment]
Here's what I see in the /Head of my Wiki.js site:

<link type="text/css" rel="stylesheet" href="/_assets/css/app.10236313cd42380aeca2.css">
<script type="text/javascript" src="/_assets/js/runtime.js?1592151807"></script>
<script type="text/javascript" src="/_assets/js/app.js?1592151807"></script>

I took a look in that .css file and couldn't see anything about the markdown styling for  blockquote "is-success" or "is-warning" for example. 

If I were to copy the "source" of a page from Wiki.js and paste it in my documentation site, I want tabs, blockquotes, etc. to look identical to how they look on Wiki.js.

Sorry if I'm missing the obvious here.

**Comment by Smankusors** [comment]
hmm perhaps [this](https://github.com/Requarks/wiki/tree/dev/client/scss) and [this](https://github.com/Requarks/wiki/blob/dev/client/themes/default/scss/app.scss) could help you?

or maybe, just inspect element it by using dev tools?

**Comment by NGPixel** [comment]
I suggest copying the styles you need from the source:
https://github.com/Requarks/wiki/blob/dev/client/themes/default/scss/app.scss

What you're trying to do by linking directly to the wiki.js css will certainly not work as expected.
