### ISSUE TITLE
AWS Wiki.js site unreachable after install.

### ISSUE THREAD

**Issue by dbnumberiv** [Requarks/wiki#2347]
Does the WIki.js need a public IP?

We want this to be an internal Wiki, and the instance only has private IP. Is the instance looking for its own public IP when it doesn't have one? Or should it already be using the Private IP assigned to it.

**Comment by NGPixel** [comment]
The AWS image is using standard docker port binding.

[Read the Docker docs](https://docs.docker.com/config/containers/container-networking/) on how to bind the container to a specific interface IP, instead of eth0.
