### ISSUE TITLE
PWA and offline capabilities

### ISSUE THREAD

**Issue by alxlg** [Requarks/wiki#2349]
Progressive Web App (PWA) is a set of feature some website provides:

https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps 

I think it would be useful to be able to "install" a wiki.js instance on your device and/or partially browse it offline.

Also while you could click on a button to save a wiki page for offline reading on most browsers, Chrome has also an API to list saved page in its Downloads section:

https://web.dev/content-indexing-api/

Other PWA-like features include push notifications and [shortcuts](https://web.dev/app-shortcuts/).

**Comment by Smankusors** [comment]
this is a feature request, and there's already existing one [here](https://wiki.js.org/feedback/p/progressive-web-app).

**Comment by alxlg** [comment]
@Smankusors thanks, how does one subscribe to a ticket in that feedback app? Even after registration there is no 'subscribe' button. I suspect that app is just to rank feature requests, not to discuss.

**Comment by NGPixel** [comment]
@alxlg You simply vote up. You'll be notified on any update on that feature. You can also post comments.

**Comment by sokai** [comment]
JFYI: the _new_ feedback link is https://feedback.js.wiki/wiki/p/progressive-web-app
