### ISSUE TITLE
uploaded files

### ISSUE THREAD

**Issue by jronpaul** [Requarks/wiki#2351]
hello,
when i upload png images to display in a document, my standard user just sees a broken image icon but as administrator
i can see the images in the page.

permissions for non admin are set to all. for the /home path and the path where the doc is..
i can get the doc and read it but i just cant see the images.. i assume its a permissions thing?
i also dont know where nodes is logging errors...
![perm](https://user-images.githubusercontent.com/62318524/91753098-6081df80-eb95-11ea-817c-c7403261061e.png)

**Comment by rdecaneva** [comment]
+ 1. Same issue.

**Comment by RainshawGao** [comment]
why not list your permissions to make others more clear with what happened, and so your image url

**Comment by jronpaul** [comment]
you mean expanded?
like this ?
![infra](https://user-images.githubusercontent.com/62318524/92027949-3d8c3280-ed31-11ea-8c94-1e7347cf22d9.png)
![home](https://user-images.githubusercontent.com/62318524/92027954-40872300-ed31-11ea-90ea-3e23d74d3564.png)

**Comment by jronpaul** [comment]
here is what the view looks like from a regular user.

![broken](https://user-images.githubusercontent.com/62318524/92028708-7bd62180-ed32-11ea-8040-c52f5815ef6b.png)

**Comment by MarsWarrior** [comment]
> the INFRA permissions are all..
> the /home are read pages, upload, edits and deletes, read comments, createcomments
> 
But the "Read / Use Assets" checkbox is unchecked. And images are assets I guess??

**Comment by jronpaul** [comment]
That's a good catch.. I can't believe I missed that.. But..
I selected it and the images still don't load for users.. Only the admin 🤔

**Comment by MarsWarrior** [comment]
Did you restart Wikijs to make sure that it is not a problem with changing the permissions?

And I always check first with full permissions, before I bring them 'down' to only the ones needed!

**Comment by jronpaul** [comment]
yes... i have restarted postgres and apache.. its been rebooted too.
ill try full permissions. and remove 1 at a time

**Comment by jronpaul** [comment]
odd.. enabled all permissions..
still cant see the images..
so i created a new page as the non admin user.. and even then i cant even upload images.

**Comment by jronpaul** [comment]
i figured it out..
you need to give some permissions to / since that is where the uploads are put.
![image](https://user-images.githubusercontent.com/62318524/92936547-34c5eb80-f418-11ea-9609-74d55c05658a.png)

**Comment by MarsWarrior** [comment]
Ah! Great find.

But you don't make separate folders for each /group/user to upload images?

I do. So now I understand why it works for me, and not in your case.
In your example I would have pages in /INFRA, and made a folder /INFRA in the assets root also.

**Comment by jronpaul** [comment]
I didn't know I could dictate where the assets go

**Comment by MarsWarrior** [comment]
You can create and select folders in the asset add screen:
![image](https://user-images.githubusercontent.com/1220775/92952655-a1fd6f00-f460-11ea-8503-33d1056cd899.png)
