### ISSUE TITLE
How to setup Elasticsearch APM RUM

### ISSUE THREAD

**Issue by abolinhas** [Requarks/wiki#2352]
**Question**
I would like to know how to setup Elasticsearch APM RUM, i already have installed elk + amp server 7.9 but i can't see any data comming from wiki to amp.
![amp](https://user-images.githubusercontent.com/3245485/91776903-5cca7900-ebe6-11ea-8231-b292147eecad.png)

**BUG**
Using ff debug tools i found this error when the wiki loads
**Uncaught ReferenceError: elasticApm is not defined
    <anonymous> httpsxyz.com/:6**

**Host Info (please complete the following information):**
OS: Debian 10
Wiki.js version: 2.4.107
Database engine: postgtes

**Comment by NGPixel** [comment]
Fixed by 9f1ba0a32f80b2b9f99307d82da8523162362b6f
