### ISSUE TITLE
Import Backup

### ISSUE THREAD

**Issue by aaditgupta21** [Requarks/wiki#2355]
**Question**
I am running wiki js on digitalocean and installed it from the marketplace. I have set it to backup on local file system every day and delete it after a month. I want to know how I can use this backup if I ever need to.
**Host Info (please complete the following information):**
OS: [e.g. Ubuntu 18.04, Docker, DigitalOcean]
Wiki.js version: [e.g. 2.4]
Database engine: [e.g. postgres 9.7]

**Comment by NGPixel** [comment]
Simply setup local file system storage module on a new wiki, point to the folder containing the extracted files from the backup archive and click "Import Everything".
