### ISSUE TITLE
Tags under different locales

### ISSUE THREAD

**Issue by jdmaudio** [Requarks/wiki#2357]
**Question**
It doesn't seem possible to have a Master Tag list per language?  We currently have English and Chinese configured on our wikijs with more languages to add, however all tags from both languages show on the /t page which is confusing for anyone wanting to search by tag.

Thanks

OS: [Docker Container (Linux)]
Wiki.js version: 2.4.107
Database engine: [mysql ]

**Comment by NGPixel** [comment]
Open a feature request [here](https://requests.requarks.io/wiki).
