### ISSUE TITLE
Explorer-like treeview

### ISSUE THREAD

**Issue by devkonvert** [Requarks/wiki#2359]
It would be handy to have the possibility to use an explorer-like treeview / page tree on the left pane to navigate through the wiki.

Examples 
https://www.jqueryscript.net/other/File-Explorer-Tree-View-Plugin-jQuery.html
http://wwwendt.de/tech/fancytree/demo/#
https://examples.sencha.com/extjs/7.2.0/examples/classic/tree/locking-treegrid.html

**Comment by NGPixel** [comment]
It's already possible...?

https://docs.requarks.io/en/navigation

**Comment by devkonvert** [comment]
Hi,

Correct in the sense that there is an option to choose a treeview layout. It gives you kind of a treeview (atlassian style), but not a real explorer like treeview. I find the explorer paradigm much nicer and clearer. In explorer like treeview - which every windows user knows how to use - you expand/collapse different parts of the tree simultaneously. It is much easier to keep an overview.

Current treeview:
![image](https://user-images.githubusercontent.com/68285364/92450284-86be0580-f1bb-11ea-8d8a-2ac3e1d4abe3.png)

Explorer Treeview:
![image](https://user-images.githubusercontent.com/68285364/92450422-b5d47700-f1bb-11ea-95a9-e03bb065cdac.png)
