### ISSUE TITLE
page renaming in multilingual setup

### ISSUE THREAD

**Issue by devkonvert** [Requarks/wiki#2360]
**Describe the bug**
When you add a new language version of a page and you change the 'path' to a different url then the main page, the page gets lost. But it is still in the 'pages' table in the database. Change the path field in the database to the same as the primary page makes the page reappear.

For example, main language 'Dutch' and we have a dutch page like this
![image](https://user-images.githubusercontent.com/68285364/92127916-19e4ed00-ee02-11ea-9f0e-e890f9a4ae09.png)

we create a french page, but we use a different path!!
![image](https://user-images.githubusercontent.com/68285364/92128142-60d2e280-ee02-11ea-81d5-df5c20d29cb4.png)

when opening the dutch page and then choosing the french language:
![image](https://user-images.githubusercontent.com/68285364/92128512-c45d1000-ee02-11ea-8311-21ce34d14245.png)

When we then search the record in the pages table in the database and change the path field back from
ICT/Software/Konvert_Match/Release_notes/20-09-02_Appointment_SMS-thiswillmakeitdisappear
to
ICT/Software/Konvert_Match/Release_notes/20-09-02_Appointment_SMS

the french page is found again...

**Comment by NGPixel** [comment]
This is not possible at the moment. Pages must have the same path in all languages.

It will be addressed in a future release.
