### ISSUE TITLE
How to complete setup without a graphical interface in Linux

### ISSUE THREAD

**Issue by JoaoAugustoGuedes** [Requarks/wiki#2361]
**Question**
Hi. I'm trying to install the wiki following the installation guide by platform (Linux) on my server and stopped at step 8. My Linux server doesn't have a graphical interface. I use a terminal to access it. How can I complete the setup in this case?
Thanks.

![image](https://user-images.githubusercontent.com/9055854/92126774-f6f11380-edd6-11ea-9e44-3d30dfbf000e.png)

**Host Info (please complete the following information):**
OS: Oracle Linux Server 6.10
Wiki.js version: 2.4.107
Database engine: (PostgreSQL) 9.6.19

**Comment by NGPixel** [comment]
Just load the site from your browser? It doesn't have to be done from the machine hosting the wiki...

http://YOUR-SERVER-IP:12380/
