### ISSUE TITLE
Can't seem to setup TLS...

### ISSUE THREAD

**Issue by AugmentedThunder** [Requarks/wiki#2362]
I've just installed via the DigitalOcean auto-install, and I can't figure out how to setup TLS... Can't find any config files, and I have no idea how to use Docker... can't find any help on that either.

**Comment by NGPixel** [comment]
Have you [read the docs](https://docs.requarks.io/install/digitalocean#automatic-https-with-lets-encrypt)?

**Comment by AugmentedThunder** [comment]
Missed that part... Just went to the config bit which didn't explain how to do it with DigitalOcean, thanks.. and the TLS auto config is strong, nice work.
