### ISSUE TITLE
LDAP Authentification failed since 2.5.105

### ISSUE THREAD

**Issue by valderaplets** [Requarks/wiki#2365]
since 2.5.105, no more authentification LDAP

**To Reproduce**

1. Go to 'wiki.mondomain.com'
2. Click on 'LDAP / AD'
3. Enter login + password'

In logs : 

`[MASTER] warn : " cb is not a function"`

![Capture du 2020-09-04 15-22-25](https://user-images.githubusercontent.com/63161106/92244416-2b41fe00-eec3-11ea-8332-c1c73ac6cd7d.png)

 - OS: debian buster 10.5
 - Wiki.js version: 2.5.105
 - Database engine: postgres 11.7

**Comment by NGPixel** [comment]
Fixed by 17f8071abe0eb78b33b63b2c66807a8f271dd6ad
