### ISSUE TITLE
Typed characters not shown in dark mode in 2.5 beta

### ISSUE THREAD

**Issue by JJ1LFC** [Requarks/wiki#2366]
**Describe the bug**
When dark mode is enabled in 2.5 beta, any characters I type on login screen cannot be seen (white characters on white background).
This was not happened when dark mode was disabled.

**To Reproduce**
1. Go to `/login`
2. Type something in a field

**Expected behavior**
Characters can be seen (black characters on white background, or white characters on black background for dark mode).

**Screenshots**
![Screenshot from 2020-09-05 01-55-43](https://user-images.githubusercontent.com/39832857/92266919-f5306880-ef1a-11ea-9015-aafa50c6db18.png)
(`test` in both ID and password field)

**Host Info (please complete the following information):**
 - OS: Docker compose on Ubuntu 18.04
 - Wiki.js version: 2.5.105 beta
 - Database engine: postgres 11.9

**Comment by NGPixel** [comment]
Fixed by 715364de1d186484e114e34aece577c747bfa833
