### ISSUE TITLE
migration file "2.5.1.js" failed

### ISSUE THREAD

**Issue by iamernie** [Requarks/wiki#2368]
**Describe the bug**
Upgrading from Wiki.js 2.4.105 to 2.5.105 docker The following message is in the log

wiki    | Loading configuration from /wiki/config.yml... OK
wiki    | 2020-09-04T18:30:24.729Z [MASTER] info: =======================================
wiki    | 2020-09-04T18:30:24.730Z [MASTER] info: = Wiki.js 2.5.105 =====================
wiki    | 2020-09-04T18:30:24.731Z [MASTER] info: =======================================
wiki    | 2020-09-04T18:30:24.731Z [MASTER] info: Initializing...
wiki    | 2020-09-04T18:30:25.074Z [MASTER] info: Using database driver pg for postgres [ OK ]
wiki    | 2020-09-04T18:30:25.078Z [MASTER] info: Connecting to database...
wiki    | 2020-09-04T18:30:25.102Z [MASTER] info: Database Connection Successful [ OK ]
wiki    | migration file "2.5.1.js" failed
wiki    | migration failed with error: delete from "authentication" where "isEnabled" = $1 - update or delete on table "authentication" violates foreign key constraint "users_providerkey_foreign" on table "users"
wiki    | 2020-09-04T18:30:25.134Z [MASTER] error: Database Initialization Error: delete from "authentication" where "isEnabled" = $1 - update or delete on table "authentication" violates foreign key constraint "users_providerkey_foreign" on table "users"

**To Reproduce**
1. Pull the latest beta image
2. run docker-compose up -d

**Expected behavior**
Database upgrades and site launches

**Host Info (please complete the following information):**
 - OS:  Ubuntu 18.04, Docker
 - Wiki.js version: 2.5.105 docker
 - Database engine:  postgres 9.7 docker

**Additional context**

**Comment by BBISupport** [comment]
Having the same issue on my test machine.

OS: Docker on Windows - using Ubuntu with WSL2 (test machine)
Wiki,Js Version: 2.5.105 (upgrade from 2.4.107) - docker
Database Engine: PostgreSQL 12.4 - docker

**Comment by DecisionIT** [comment]
Having the same issue on my test machine.

OS: Docker on Windows - using Ubuntu with WSL2 (test machine)
Wiki,Js Version: 2.5.105 (upgrade from 2.4.107) - docker
Database Engine: PostgreSQL 12.4 - docker

**Comment by NGPixel** [comment]
You have some users that are using an authentication strategy that is not enabled. Can you try to either enable that strategy OR delete these users, then try the upgrade again?

**Comment by iamernie** [comment]
Removed the users.  Upgraded successfully.  Thanks!
