### ISSUE TITLE
Apache + Node.Js SSL Instructions Unclear

### ISSUE THREAD

**Issue by GothicKitsune** [Requarks/wiki#2369]
**Question**
I am trying to set up the SSL for Wiki.js, but the instructions are very unclear as to how to do this. I am running Apache for other pages and subdomains, and have reverse proxied just fine for regular http. However, upon use of https I either get the file directory (unproxied), This site can't be reached (took too long to respond), or Error 500 - Internal Server Error. 

What I've done is simply add the line `ProxyPass / https://guide.example.org:3000/` to the user defined config, and that worked just fine for http. For https, I first tried the config.yml defined SSL port (which was 3443), and as that returned Error 500 I attempted to just use port 3000 again which also returned a Error 500. That is with the following code:
`SSLProxyEngine On`
`SSLProxyCheckPeerCN on`
`SSLProxyCheckPeerExpire on`
`ProxyPass / https://guide.example.org:3000/`

The docs say if you have Apache in front of Wiki.js, the SSL should be handled by that and not Wiki.js, but I am not sure how to make that happen. SSL is currently disabled in the config.yml, although I have it filled out just in case. It should be noted that even through the direct port, https://guide.example.org:4000, it returns with "This site can't be reached" with the config.yml SSL enabled and no proxying. Attempting to proxy with it disabled returns the 500. 
**Host Info (please complete the following information):**
OS: CentOS 7.8.2003
Wiki.js version: 2.4.107
Database engine: MariaDB 10.3.23

**Comment by NGPixel** [comment]
If Apache is handling SSL termination, Wiki.js should run in normal HTTP mode. Any SSL settings should be off.

Both HTTPS and HTTP Apache configs should point to the Wiki.js HTTP port (3000).

**Comment by GothicKitsune** [comment]
Oh wow, yeah pointing the Apache HTTPS config to http port 3000 worked. It hadn't previously during troubleshooting, even though I restarted Apache. Thank you so much.

**Comment by nik2208** [comment]
Actually, using this suggested configuration, I get:

```Proxy Error
The proxy server could not handle the request
Reason: Error during SSL Handshake with remote server

Apache/2.4.41 (Ubuntu) Server at wiki.tourismapp.it Port 443
