### ISSUE TITLE
Javascript MIME type seems wrong?

### ISSUE THREAD

**Issue by BhavinIoT** [Requarks/wiki#237]
### Actual behavior
The scripts don't load on any of the pages. Console gives the following error:
`Refused to execute script from 'http://localhost:7777/js/vendor.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.`

### Expected behavior
Scripts should have MIME Type `text/javascript`

### Steps to reproduce the behavior
Just did a fresh install on `node v6.10.3 / npm v4.6.1` as well as `node v8.5.0 / npm v5.4.2`. Tried both Firefox & Chrome. Got the same results

```
$ uname -a
Linux ideapad 4.4.0-93-generic #116-Ubuntu SMP Fri Aug 11 21:17:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

I did check the views files and the MIME type seems to be set correctly in there. Eg lines 21,22 from `login.pug`:
```
script(type='text/javascript', src=appconfig.host + '/js/vendor.js')
script(type='text/javascript', src=appconfig.host + '/js/app.js')
```

Thanks in advance!

**Comment by NGPixel** [comment]
Your path is set wrong: `localhost:7777/localhost`

Make sure you’ve set the host parameter correctly in your config.yml

**Comment by moonmeister** [comment]
I'm getting this issue in my dev environment and my host is set correctly.

**Comment by NGPixel** [comment]
What's the error you're getting and what are the values of `host` and `port` in your config.yml?

**Comment by moonmeister** [comment]
Config:

```
# ---------------------------------------------------------------------
# Full public path to the site, without the trailing slash
# ---------------------------------------------------------------------
# INCLUDE CLIENT PORT IF NOT 80/443!

host: http://localhost:8080

# ---------------------------------------------------------------------
# Port the main server should listen to (80 by default)
# ---------------------------------------------------------------------
# To use process.env.PORT, comment the line below:

port: 8080
```

Error:
```
login:1 Refused to execute script from 'http://localhost:8080/js/vendor.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
login:1 Refused to execute script from 'http://localhost:8080/js/app.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
```

i've run `npm install` then `node wiki start`.

**Comment by BhavinIoT** [comment]
> Your path is set wrong
That was a typo. Updated the comment now. I'm running it on port 7777, so that's not a misconfiguration eithe

**Comment by moonmeister** [comment]
@BhavinIoT I'm not sure what this is suppose to mean but it makes no sense and I still have this issue.

**Comment by BhavinIoT** [comment]
@moonmeister Closed it by mistake (I need some sleep :| ). The comment was in response to NGPixel not you, sorry for the confusion

**Comment by moonmeister** [comment]
@NGPixel FYI I have no issues in production (npm install) or with the pre built docker container. just running native. I'm on a macOS High Sierra.

**Comment by moonmeister** [comment]
Functional Wiki:
![screen shot 2017-10-05 at 3 59 25 pm](https://user-images.githubusercontent.com/2730871/31256263-3f851e1c-a9e6-11e7-90b3-16477b7bf17c.png)

Non Functional local:
![screen shot 2017-10-05 at 3 59 06 pm](https://user-images.githubusercontent.com/2730871/31256271-4d3a70fc-a9e6-11e7-93f6-dac879e02971.png)

**Comment by sivaprakasham** [comment]
Hi, I had this type of error, what can I do now?

Refused to execute script from 'http://localhost:3000/assets/header.js?body=1' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

**Comment by sivaprakasham** [comment]
I need your help guys this issue is on ruby on rails

**Comment by millman2394** [comment]
Wonderful, no solution. I have this problem.

This is after successful config

`Refused to execute script from 'http://localhost:8080/login' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.`

```
host: 'http://localhost:8080'
port: 8080
```

**Comment by sanion** [comment]
I feel like I'm joining the club.
My name is Elvin and I have the same problem!

**Comment by ChristianSchmitz81** [comment]
Did anyone solve this issue? I am getting it, too.

**Comment by fuegod03** [comment]
Same issue here, hoping for a hero to come and save me

**Comment by mxdlx** [comment]
Is there a spare chair here? Same issue.

**Comment by sindunuragarp** [comment]
Same issue in 2019. It seems that the issue only occurs when running locally though

**Comment by Zerokk** [comment]
Same issue here...
