### ISSUE TITLE
Content Security Policy for Wiki.js Server

### ISSUE THREAD

**Issue by msvendsentan** [Requarks/wiki#2371]
**Question**
I've put Wiki.js behind a reverse proxy (nginx), and everything works fine on that front. However, when I try to add a CSP header, the site just gives me a completely white screen. I don't know much about CSPs, but from what I understand, the site's still working fine, it's just that nginx is blocking it / not serving it to my browser? Full security headers are below, and based off of the boilerplate generated by DO's [NGINXConfig tool](https://www.digitalocean.com/community/tools/nginx). The problem line is the Content-Security-Policy. If I comment it out, everything's fine. Why is that default boilerplate breaking things? Any help is greatly appreciated!

**Host Info (please complete the following information):**
OS: Debian 10, manual install
Wiki.js version: 2.4.107
Database engine: sqlite3

**security.conf**
```
# security headers
add_header X-Frame-Options           "SAMEORIGIN" always;
add_header X-XSS-Protection          "1; mode=block" always;
add_header X-Content-Type-Options    "nosniff" always;
add_header Referrer-Policy           "no-referrer-when-downgrade" always;
add_header Content-Security-Policy   "default-src 'self' http: https: data: blob: 'unsafe-inline'" always;
add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

# . files
location ~ /\.(?!well-known) {
    deny all;
}
```

**Comment by NGPixel** [comment]
CSP works at the browser level, not the server. It's the browser that will refuse to load / display content, not the server.

**Comment by msvendsentan** [comment]
Okay, so nginx is properly serving it to my browser, but my browser is throwing up a fuss. I think I understand that. Would you know what in the "default-src 'self' http: https: data: blob: 'unsafe-line'" always; CSP is causing the browser to not load the content?

**Comment by shriker** [comment]
I ran into this the other day while setting up. I had to add `unsafe-eval` to my CSP. Note that this will make things more insecure and remove protection from XSS eval() attacks. I haven't dug too deep yet, but it looks like part of what is being blocked is the mermaidAPI diagram script.

```
add_header Content-Security-Policy    "default-src 'self' http: https: data: blob: 'unsafe-inline' 'unsafe-eval'" always;
```

**Comment by msvendsentan** [comment]
Thanks @shriker, that addition fixed things. I don't know how much having 'unsafe-inline' + 'unsafe-eval' defeats the purpose of CSP, but I'm happy to just be able to uncomment out that line of code regardless.
