### ISSUE TITLE
Reachability Test

### ISSUE THREAD

**Issue by oshybrid** [Requarks/wiki#2372]
I did not see anything like this, but...  I was wondering if there was a reachability test (Ping) from the actual wiki.js app (like under 'Administration')?  Or a way to launch a web-based CLI cut-through session (pop-up)?

Brad

**Comment by NGPixel** [comment]
From the app itself? What are you trying to do exactly?

**Comment by oshybrid** [comment]
Oh just trying to initiate a ping without having to launch a terminal window.
The Wiki server I am using is somewhat uniquely position to also be a jump server to a network that users of the Wiki site access.  But they have to do basic troubleshooting on that network.  I was wondering if there was a basic set of admin tools in Wiki.js for testing if devices on that network are in fact “Up”. No biggie, I was just wondering.

**Comment by NGPixel** [comment]
There's no such feature in the UI.
