### ISSUE TITLE
editing error after updating

### ISSUE THREAD

**Issue by 40foot** [Requarks/wiki#2374]
after updating to 2.5.115 I receive the error "Cannot read property 'css' of null" when trying to edit any page. tried ver. 2.5.117 also, same result. how to revert to previous version I just don't know... Any ideas?

OS: Docker install under UNRAID
Wiki.js version: 2.5.117
Database engine: mysql 5.7.31

**Comment by kommandantjut** [comment]
I also have this issue after updating.
I also get the same error when I try to view some pages (although if you refresh the page it loads) although this same tactic doesn't appear to work for editing in which it just doesn't load.

**Comment by Mark-Powers** [comment]
Here is the stacktrace I am getting with this error
````
TypeError: Cannot read property 'css' of null
    at /home/mark/wiki/server/controllers/common.js:152:31
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
````

**Comment by guoyl-ll** [comment]
The same problem, my old articles cannot be edited again

**Comment by neilcameronwhite** [comment]
Can also confirm the problem.
We are using the docker images: requarks/wiki:2.5
Tried switching to latest, issue persists.

**Comment by Moebyte** [comment]
Problem still exists. I cannot edit the page.

**Comment by nibbleshift** [comment]
Issue confirmed on latest tag.  Unable to edit pages and log is full of messages:

```
MASTER] warn: Cannot read property 'css' of null
```

**Comment by jdmaudio** [comment]
Same issue - unable to edit pages

**Comment by cgaspard** [comment]
We are experiencing the same issue. 

The issue is happening here:

https://github.com/Requarks/wiki/blob/dev/server/controllers/common.js#L152

There needs to be a null check for page.extra and / or the extra database field should be set to '{}'.  By default.   Right now the extra field in the database are all null after the upgrade.

Running this on my database solved the problem for us.

update pages set extra = '{}' where extra is null

**Comment by nibbleshift** [comment]
> We are experiencing the same issue.
> 
> The issue is happening here:
> 
> https://github.com/Requarks/wiki/blob/dev/server/controllers/common.js#L152
> 
> There needs to be a null check for page.extra and / or the extra database field should be set to '{}'. By default. Right now the extra field in the database are all null after the upgrading.
> 
> Running this on my database solved the problem for us.
> 
> update pages set extra = '{}' where extra is null

Confirmed.  This corrects the issue.

**Comment by 40foot** [comment]
yes, this database update solves it, thx.

**Comment by onfire4g05** [comment]
Thanks @cgaspard for the sql update, fixed for us, too.
