### ISSUE TITLE
cannot Login with LDAP / Active Directory

### ISSUE THREAD

**Issue by KleepX** [Requarks/wiki#2378]
### Actual behavior
After the newest Update (2.5.117) when trying to log in using the LDAP / Active Directory login, an Error is occuring: "undefined passed as a property in argument #0 for 'where' operation. Call skipUndefined() method to ignore the undefined values."

### Expected behavior
It logs me into the Server per LDAP / Active Directory

os: Linux - Ubuntu (bionic) 18.04 x64
Version: 2.5.117
Database engine: PostgreSQL  10.14

Best Regards
KleepX :)

**Comment by lzimao** [comment]
I have a same problem
`2020-09-07T07:22:14.546Z [MASTER] warn: LDAP LOGIN ERROR (c1):  undefined passed
 as a property in argument #0 for 'where' operation. Call skipUndefined() method
 to ignore the undefined values.`

**Comment by Hannibalus** [comment]
Hi all,

I have same problem. It's a big problem.

`undefined passed as a property in argument #0 for 'where' operation. Call skipUndefined() method to ignore the undefined values.`

**Comment by lotusnoir** [comment]
Hello, i was going to open an issue when i just saw this one, i made the upgrade twice to be sure it wasn't my mistake but no... looks to be a bug in version 2.5.117
Other identification method like keycloak is working fine

**Comment by ruohki** [comment]
Running into the same issue after an upgrade the ldap login is not working anymore

**Comment by JJ1LFC** [comment]
I have the same problem after upgrading from 2.5.107.

**Comment by dunxiii** [comment]
I also have the same issue with the latest docker version.

**Comment by AlmightyMiniMoose** [comment]
I have the same error after upgrading to 2.5.117 from 2.4.107
PostgresSQL: 11.7 
Node.js: 10.21.0
Debian: 10 x64

Now I am stuck at 2.5.117 with no ldap login, because downgrade doesnt work.

**Comment by andrenasturas** [comment]
Same.

PostgresSQL: 12.0
Node.js: 12.13.0
OS : Windows Server 2016

**Comment by cjs1976** [comment]
Hi, same issue after upgrading from 2.4.x to the newest 2.5.x from today. I run wiki.js in a virtual machine on my VMware ESXi. Made a snapshot before upgrading. Restored snapshot in less than 5 minutes. Old system up and running again, so no big deal. Maybe this is an idea for further updates for some of the users here who are now not able to use their wiki.js ...

**Comment by ruohki** [comment]
also clicking ldap multiple times in the login page yields errors in the console

**Comment by NGPixel** [comment]
Fixed by 78417524b3d00adcb6f5596a4bdf4dc0287dff39

A new release is currently compiling and will be published soon. (v2.5.126)
