### ISSUE TITLE
Use a new Azure Active Directory

### ISSUE THREAD

**Issue by whelan9453** [Requarks/wiki#2379]
**Question**
Hi,
We use Azure Active Directory as our login method and everything is great until one operation accidentally remove the AAD app registration.

We create another AAD app registration and update Identity end point and client id in the admin settings auth page but login is still broken ever since. 

After AAD login we always see this page.
![image](https://user-images.githubusercontent.com/8610392/92362673-e916f780-f122-11ea-93a8-b94edc78b5bc.png)

Is there any way to fix this problem?
Thank you.

**Host Info (please complete the following information):**
OS: Docker
Wiki.js version: requarks/wiki:2.4
Database engine: postgres 11

**Comment by krishRamalingam** [comment]
Seems like it is possible to have only one Azure AD connection in Wiki JS. This will become broken after you add a new AD. All you have to do is remove the excess Azure AD strategies and resave the single strategy, then it will work again. From the browser you need to clear the cache obviously.
