### ISSUE TITLE
Error during WebSocket handshake: Unexpected response code: 400

### ISSUE THREAD

**Issue by vizcay** [Requarks/wiki#238]
Suddenly the wiki stopped working, first noticed when we open the "All pages" in the navbar but nothing happens. The browser console shows:

```WebSocket connection to 'ws://xxxxxx/socket.io/?EIO=3&transport=websocket&sid=EqijzsiJb_qIBb1DBBAP' failed: Error during WebSocket handshake: Unexpected response code: 400"```

I'm running on 1.0.8. Any ideas what this is related to?

Edit: I'm not running behind HTTPS (we use NGINX as a reverse proxy).

**Comment by vizcay** [comment]
I manually restarted the wiki and the /all page started working again, but the error persists, so it's unrelated.

This of the "All" pages section getting out of sync happens often?

**Comment by NGPixel** [comment]
You must configure your nginx to allow web sockets. Look at the docs example for http:
https://docs.requarks.io/wiki/admin-guide/setup-nginx

**Comment by choicky** [comment]
Currently I'm using caddy server.

The configuration as follows works for me.  If "websocket" is not added, the 400 error of WebSocket handshake will be reproduced.
```
law.iplaws.cn {
    gzip
    tls zhoucaiqi@gmail.com
    proxy / localhost:3000 {
        websocket
        transparent
    }
}
```
