### ISSUE TITLE
"Bypass Login Screen" may not working properly

### ISSUE THREAD

**Issue by stevenxi** [Requarks/wiki#2382]
**Question**
We're upgraded to 2.5 and may found some issue in "Bypass Login Screen"
1.  In the help description it says "Should the user be redirected automatically to the first authentication provider."
     But unfortunately in the Authentication cannot change provider's order. (Can change it, but not able to save. After refersh the order restored).

2. Is there'a failback url after turning on "Bypass Login Screen"? If we need to use local database user to login as admin in case of any other auth provider gets configuration issue, what should we do?

Thanks in advance .

**Host Info (please complete the following information):**
OS: Ubuntu 18.04, Docker
Wiki.js version: 2.5.117
Database engine: postgres 9.7

**Comment by andrenasturas** [comment]
Adding `?all` to the login URL makes the local provider visible when it is hidden in security settings, so I suppose it should work as well when login bypassing is enabled.

Furthermore I confirm that providers order configuration is not persistent.

OS: Windows Server 2016
Wiki.js version: 2.5.117
Database engine: Postgres 12.0

**Comment by NGPixel** [comment]
Sort order fixed by dab5dcfbc14b452ebe1b887579472799642dee4b

As @andrenasturas mentionned, you can add `?all` to the login URL if you need to login using the local provider.

**Comment by stevenxi** [comment]
Hi, @NGPixel @andrenasturas ,
When "Bypass login screen" on, there's no chance to use the ?all option anymore.
The login URL redirects to 3rd party login page straight without a chance allowing to choose any other login method.

Is it possible to reopen this issue?

**Comment by stevenxi** [comment]
I see, before turning on "Bypass login screen", adding ?all is enough. But after, need to add "?all=true"
