### ISSUE TITLE
Can't connect with Wiki.js 2.5.117

### ISSUE THREAD

**Issue by DinghyRed** [Requarks/wiki#2383]
**Question**
Hello, while deploying wiki.js via heroku, I can't connect. I have the new page displayed but no box to fill in. I tried with Mozilla or Edge. I also tried to re-deploy the version (via the button in the site help).

![msedge_1JTGvNY5WS](https://user-images.githubusercontent.com/36588095/92380548-a85eb480-f109-11ea-9b58-1e6f048fc013.jpg)

**Host Info (please complete the following information):**
OS: Heroku
Wiki.js version: 2.5.117
Database engine: No idea, I don't have access to the administration panel.

**Comment by plezervi** [comment]
I experience the same
