### ISSUE TITLE
TabSet termination

### ISSUE THREAD

**Issue by ruohki** [Requarks/wiki#2384]
Hey, 
iam fiddling with tabsets in markdown and i try to embed a tabset between 2 paragrahps. However the last tab seems to swallow the last paragraph.

Is there a way to close the tabset without the need of a new headline?

**Comment by NGPixel** [comment]
Posting an example would help...

**Comment by ruohki** [comment]
yeh sure thought it would be clear

```markdown
1. Point 1
# Commands {.tabset}
## Windows
```cmd
dir c:\
```
## Unix
```bash
ls
```
2. Point 2

**Comment by NGPixel** [comment]
That's the intended behavior. Tabsets are simply a UI trick on normal Markdown header syntax. You can't put headers inside a list children...

I suggest using headers instead of a numbered list:

```markdown
# Point 1
## Commands {.tabset}
### Windows
dir c:\
### Unix
ls

# Point 2
```
