### ISSUE TITLE
Is there a way to change the domain that you initially set in the setup?

### ISSUE THREAD

**Issue by PyroFD3S** [Requarks/wiki#2386]
**Question**
Is there a way to change the domain that you initially set in the setup?

**Host Info (please complete the following information):**
OS: Ubuntu 18.04, Docker
Wiki.js version: 2.5.121
Database engine: mariadb

I'm trying to set up google authentication but I put in garbage for my domain when I initially set it up to test with

**Comment by RainshawGao** [comment]
in the admin area, you should find it easily

**Comment by NGPixel** [comment]
Admin > General

**Comment by PyroFD3S** [comment]
thanks
