### ISSUE TITLE
Some items are grayed out

### ISSUE THREAD

**Issue by Igorgro** [requarks/wiki#2388]
Some items in page administration menu are grayed out:
![image](https://user-images.githubusercontent.com/22894169/92416604-fe157a00-f166-11ea-9ac0-8b15a8d09080.png)
But they are available through other places (page properties, etc.). Is it a bug?

**Comment by NGPixel** [comment]
They are simply not implemented in the admin yet.

**Comment by jsarnowski96** [comment]
then why put them there in the first place? same goes for many other sections of admin panel.
