### ISSUE TITLE
Change page editor

### ISSUE THREAD

**Issue by oshybrid** [Requarks/wiki#2389]
I kept forgetting to ask this question.

If I used one editor to initially create a wiki Page in Wiki.js.
How do I select to use a different editing style if I want to update it?

EX:  I use Markdown, or Template to create a page.  
But I want to update and fix it with WYSIWYG editor a few weeks later.

Because right now it looks like if you created a page using one editor, you have to maintain that in the same editor later on down the road.

**Comment by NGPixel** [comment]
It's not possible at the moment, but will be in a future update.
