### ISSUE TITLE
Unable to logout with "Bypass Login Screen" on

### ISSUE THREAD

**Issue by stevenxi** [Requarks/wiki#2395]
**Describe the bug**
Technically it's minor issue. But still, not fully working as user expected:

When "Bypass Login Screen" on, with a 3rd party auth provider (in our case, the generic OpenID), the "Logout" button doesn't work any more.  Easy to explain this behaviour, when logout, the wiki.js itself did logout. But the auth portal wasn't. So back to "login screen" which been bypassed, user been login form the OpenID again. So the "Logout" will never work unless the auth provider been logout.

Suggested solution would be 
- either 1. not by pass the login screen if it's a redirect from an logout action;
- or 2. Provide a confugration that allow customize the "Logout" link, so by clicking it, invoke a logout on the 3rd party identity provider's logout.
- or 3. Remove the "Logout" button, although this is not a good option.

Another small issue (inrelevant to the above) was in Generic OpenID Connect's "Configuration Reference", "Logout URL" is incorrect. But this is not impacting anything apart from initial configuration. So very minor issue.

**To Reproduce**
1. Config using a 3rd party authentication provider
2. Turn on "Bypass Login Screen"
3. Try logout
4. Cannot logout

**Expected behavior**
There's a way make user feel the "logout" works.

**Host Info (please complete the following information):**
 - OS: Ubuntu 18.04, Docker
 - Wiki.js version: 2.5.126
 - Database engine: postgres 9.7

**Comment by stevenxi** [comment]
Same time, the other issue #2382 may need to be reopened. As the https://url/login?all option doesn't work when "Bypass login screen" on.

**Comment by iWangJiaxiang** [comment]
I think there should be an url option field to setup the auth portal logout url endpoint, which would be accessed when "logout" button's clicked.

**Comment by NGPixel** [comment]
The logout URL refers to the URL where the user should be redirected after logout, not the Wiki.js logout URL (that would result in an infinite redirect loop).

**Comment by NGPixel** [comment]
Fixed by f988c5f8116258735fc058551beb6a11f94cc900

**Comment by stevenxi** [comment]
> The logout URL refers to the URL where the user should be redirected after logout, not the Wiki.js logout URL (that would result in an infinite redirect loop).

I don't think that's right.  The logout URL should be an Wiki.js endpoint that revoke user's Wiki.js credential. 
So all logout using a OpenID . User invokes the logout point from identity provider.  And identity provider will revoke all its own user credential, same time redirect user to a logout page that it hosted. In that page, embeded all clients' logout URL that revokes each's user credential.


It's not a redirect after logout, becuase that doesn't make sense:  When user logout, user's OpenID provider may provided login action to multiple applicaitons, not just wiki.js.  Why would OpenID provider requires an page after logout?

**Comment by NGPixel** [comment]
Some providers do. The configuration reference is provided as "reference" only and doesn't mean every config is needed or makes sense for that provider. Some requires you to enter an "authorized" logout redirection URL on the provider side.

The upcoming hotfix release adds a new logout endpoint option where the user will be redirected upon logout.

**Comment by stevenxi** [comment]
Thanks for the update and release.
But how do I update the "logout url" for an existing OpenID auth provider?  I can see it if add new OpenID auth provider, but not existing..

**Comment by stevenxi** [comment]
Ok, sorted by using the graphql.  Thanks.
