### ISSUE TITLE
ENOENT: no such file or directory, mkdir

### ISSUE THREAD

**Issue by cjs1976** [Requarks/wiki#2396]
Hi, I updated today to version 2.5.126 and now I get the error "ENOENT: no such file or directory, mkdir" everytime I try to edit a wiki page.

**Comment by cjs1976** [comment]
Additional informations:

1. It also happens for the administrator
2. It also happens if I want to create a new page
3. Even with the error, changes on the pages or the new pages are there

**Comment by Smankusors** [comment]
please, where's the host information?

**Comment by cjs1976** [comment]
That's the strangest. I tried it now multiple times, and now it seems to work!?

1. Restore Backup, make upgrade = error
2. Restore Backup = error ??? i was working daily with this version, and never had a problem!
3. Restore Backup = ok ??? same backup like minutes before
4. upgrade to newest version = ok
5. reboot
7. still everything fine with the newest version

no idea, but it works....
