### ISSUE TITLE
Navigation menu editing not work for non-admin users

### ISSUE THREAD

**Issue by HeavenBay** [Requarks/wiki#2399]
Hi,
Thanks for a nice app! I probably faced with a bug when tried to enter to administration tools with regular LDAP user and got error "You are not authorized".

### Actual behavior
Page with "You are not authorized".

### Expected behavior
Seeing navigation menu tool.

### Steps to reproduce the behavior
1. Grand to special users group manage:navigation access.
2. Add user to the group.
3. Login as this regular LDAP user with the group membership -> Open administrator page - See error page with "You are not authorized".

In previous version of WikiJS I saw error "You are not authorized" on the top of the page in red square but web console allowed me to see admin tools with navigation page in menu. When I updated to the last version 2.5.126 I started seeing only red page with "You are not authorized" in the center.

Only local admin has navigation:management privileges now. 
Thanks!

**Comment by NGPixel** [comment]
Fixed by 5295e413be9d661e39b020521ff025f17933a13f
