### ISSUE TITLE
Creating Navigation

### ISSUE THREAD

**Issue by n3rve** [Requarks/wiki#240]
Great product, I've made good progress setting up documentation for my organization, but I can't figure out how to create navigations like the attached screen shot. Any help is appreciated

![screenshot 2017-09-20 22 06 03](https://user-images.githubusercontent.com/1202767/30667581-efc91e06-9e4f-11e7-8eff-d6eace94bc92.png)

**Comment by n3rve** [comment]
Figured it out, you just have to create directories under the repo folder and place the .md files in there. Pretty neat, thanks!

**Comment by Indenex** [comment]
Very helpful! I didn't see this feature documented anywhere but it's pretty awesome.

**Comment by NGPixel** [comment]
No need to create the folders or move files manually. Just create new pages from the UI by entering the path you want (e.g. `folder1/page1`). The folder will be created automatically.
