### ISSUE TITLE
Email address for login is case-sensitive

### ISSUE THREAD

**Issue by MarsWarrior** [Requarks/wiki#2400]
**Describe the bug**
The email address appears to be case sensitive, ie email@example.com is a different user than Email@example.com and email@Example.com.

This is very confusing

**To Reproduce**
1. Register with an email address
2. Try to login with the same email, but having different upper/lowercase characters

**Expected behavior**
email is not case sensitive!

**Screenshots**
N/A

**Host Info (please complete the following information):**
 - OS: Docker
 - Wiki.js version: as of 2.4
 - Database engine: postgres 11.9

**Additional context**
It took me some time to find out why certain users had problems logging in, as the email was ok, and the password was ok, until I found out the email is case sensitive...

**Comment by NGPixel** [comment]
Fixed by aa96e9702874471f64a9df86758240d0bfd0f8d9
