### ISSUE TITLE
Where is the upload limit setting? 

### ISSUE THREAD

**Issue by PyroFD3S** [Requarks/wiki#2402]
**Question**
It says on the docs that the option is deprecated and configured in the administration web interface, but I don't see the setting anywhere in there?

**Host Info (please complete the following information):**
OS: Ubuntu 18.04, Docker
Wiki.js version: 2.5.121
Database engine: mariadb

**Comment by Igorgro** [comment]
It is located in security section

**Comment by PyroFD3S** [comment]
oh.... 

Thanks
