### ISSUE TITLE
Migrate Wiki.js from one server to another [INSTRUCTIONS] ✅

### ISSUE THREAD

**Issue by pbdco** [Requarks/wiki#2403]
**Hi, here I want to share you the detailed steps and instructions for migrating a Wiki.js installation from one server to another.**

###### We have been struggling on this for some weeks because there are not any clear instructions on the official docs and no one replied our tickets/issues with useful information, but just vague instructions that made us even more confused. 

**After lots of tries, I want to share your the definitive guide to do it in less than 10 simple steps:**

Before you begin
------

**_First, you obviously want to install Wiki.js on your new server. If you have already done it ignore this step. If not, you can use this guide for your full setup (Docker + DB + UFW + Wiki): https://docs.requarks.io/install/ubuntu --> This guide will use this setup instructions as reference._** _Edit: These steps should also work if you are moving Wiki.js from / to a marketplace one-click deployment like Digitalocean's._

On the OLD server:
------
Go to the OLD server and execute the following commands. Before you run these make sure your old Wiki.js (the one you want to move) is currently working and the docker containers are running (you can check doing: _docker ps_ )

**1. Make a database backup. Note: in this case: "db" is our postgres container name, "wiki" is the username of our DB and "wikibackup" is the backup filename. If you have followed the official setup manual this should work. Otherwise, please replace the name with your container / db / username.**

```
cd ~/
docker exec db pg_dumpall -U wiki > wikibackup
```

**2. Move your database backup you just made"wikibackup" from your old server over to your new server. You can use rsync like this (make sure you replace this example your new server ip):**

```
rsync -rP ~/wikibackup root@new.server.ip.address:~/
```

**3. Copy your old db pass to your new server (Again, please note this should only work if you used the official documentation setup instructions. If you changed your wiki postgres db password manually or used other custom file location, please make sure you copy it from correctly):**

```
cat /etc/wiki/.db-secret
123456789=#! ---> copy your old db password!
```

On the new server:
------

**4. On the new server replace the .db-secret file with your old db password. (Replace 123456789=#! with your old server password..)**

```
mv  /etc/wiki/.db-secret  /etc/wiki/.db-secret.BAK
echo "1233456789=#!" >> /etc/wiki/.db-secret
```

**5. Stop the wiki and wiki-update-companion containers:**

```
docker stop wiki
docker stop wiki-update-companion
```

**6. Remove the default database:**

```
docker exec -it db dropdb -U wiki wiki
```

**7. Create a new empty db:**

```
docker exec -i db createdb -U wiki wiki
```

**8. Restore your db backup:**

```
cat ~/wikibackup | docker exec -i db psql -U wiki
```

**9. Start your containers:**

```
docker start wiki
docker start wiki-update-companion
```

Enjoy :)

**Comment by NGPixel** [comment]
The stop/start wiki-update-companion step is not necessary. This container doesn't need to be stopped or restarted for this procedure.

Thank you for taking the time to document step by step. I'll make sure to add it to the official docs.

**Comment by NGPixel** [comment]
https://docs.requarks.io/install/transfer

**Comment by antoinebio** [comment]
maybe that path ? ![Image](https://github.com/user-attachments/assets/602daca2-4823-4cd2-a170-8b48ec99f188)

and that entire folder would be the the default path ?
![Image](https://github.com/user-attachments/assets/dcf8889d-0bad-42f8-ba08-0c3ee62b6a2b)

again I've followed the basic tutorial on my local PC [https://docs.requarks.io/install/docker-desktop](url)

**Comment by NGPixel** [comment]
Don't copy the postgres data directly. Export your db and re-import it using the steps in the tutorial.

**Comment by antoinebio** [comment]
@NGPixel ok thanks for the reply

in docker desktop I don't really catch the access to absolute path [for that backup command ](https://docs.requarks.io/en/install/transfer#h-2-backup-database )tring to get access to that "db",  even if I use internal terminal (powershell)
![Image](https://github.com/user-attachments/assets/d6f1765f-b9be-4a06-bf19-66194f45c5d5)


![Image](https://github.com/user-attachments/assets/6b5dbad1-3763-484a-a362-fae22a550445)


...

On top of that, When using docker destop for windows,  a LINUX partition is being visible but not has it is detailed in the tutorial

here is what I have got on a windows PC :

![Image](https://github.com/user-attachments/assets/68374ca1-c7b8-498d-8c98-a3c6ee1a7155)

![Image](https://github.com/user-attachments/assets/b7335190-8da7-46c4-a7ea-cc787ab15ffe)


Not really what I can see inside the yalm folder I have created at that step https://docs.requarks.io/install/docker-desktop#h-2-create-the-installation-folder


I could clone also that way directly from docker toolbox ... ? not sure it's satisfy 

![Image](https://github.com/user-attachments/assets/0d5b3e71-f332-4cc0-97c1-fcf998e15b19)

**Comment by antoinebio** [comment]
is it possible to directly move those images instead ? using docker ps

 ![Image](https://github.com/user-attachments/assets/d0eb1625-1a4e-4a5c-935f-e41c21054d25)

i mean 

(on my local machine with docker desktop)

1. Export the Docker Container to an Image
2. Save the Image to a Tarball
3. Transfer the Tarball to the New Server

(on new server)

1.  Load the Image from the Tarball
2. Create a New Container from the Image

**Comment by antoinebio** [comment]
found a solution [following the tutorial](https://docs.requarks.io/install/transfer#h-2-backup-database)

just a tips for the transfer of wikibackup.dump
if you work with windows on one side (local PC) you can better use filezilla and sftp to transfer your wikibackup.dump
instead of using rsync (which is not natively working on windows, needs Cygwin and many more settings).

**Comment by 4321louis** [comment]
I had some trouble with migrating from a windows machine.
Turns out the following command in windows encodes the file in utf-16 which can't be read by the new server:
`docker exec db pg_dump wiki -U wiki -F c > wikibackup.dump`
I used the following instead
`docker exec db pg_dump wiki -U wiki -F c -E UTF-8 -f wikibackup.dump`
