### ISSUE TITLE
504 Gateway time-out on edit

### ISSUE THREAD

**Issue by Mark-Powers** [Requarks/wiki#2404]
**Describe the bug**
When I go to edit existing pages, I get a 504 Gateway Time-out error. The editor will open correctly when I click "create page". There is no message in stdout or stderr. Nginx error log contains `upstream timed out (110: Connection timed out) while reading response header from upstream`. The last editor field is not modified in the admin panel of the wiki.

**Expected behavior**
I would expect to be able to edit any page. I did not have this error prior to the upgrade to 2.5. 

**Host Info (please complete the following information):**
 - OS: Ubuntu 18.04
 - Wiki.js version: 2.5.126
 - Database engine: mysql 5.7

**Additional context**
Behind nginx/1.14.0 reverse proxy

**Comment by MarsWarrior** [comment]
Did you also test without the nginx proxy?

I have experienced with several installations that the 2.5 version has more problems with proxy settings than the 2.4 version.
I could pinpoint a lot of troubles to the (in my case) Apache proxy, as a direct connection the wikijs simply worked flawlessly!

**Comment by Mark-Powers** [comment]
I ran the fix from #2374, and I am no longer having this issue.
