### ISSUE TITLE
Converting from mediawiki

### ISSUE THREAD

**Issue by BEDNAGITU** [Requarks/wiki#2406]
**Question**
Is there a way to convert from mediawiki to wiki.js ?

**Host Info (please complete the following information):**
OS: Linux - CentOS (core) 8.2.2004 x64
Wiki.js version: 2.4.107
Database engine: PostgreSQL 12.3

**Comment by MarsWarrior** [comment]
I thought that imports are on the planned list for future versions.

**Comment by NGPixel** [comment]
No built-in import functionality for MediaWiki at the moment. However you can a MediaWiki to Markdown converter online to achieve similar result.
