### ISSUE TITLE
Locked out from admin area

### ISSUE THREAD

**Issue by joppehoekstra** [Requarks/wiki#2409]
**Question**
With an admin account, I am unable to access the admin area, edit any page, nor am I able to visit the profile page with any user. Both show the 'unauthorised' page. I am still able to log in with my accounts though.

I am not quite sure what has caused this issue, nor how to resolve it.
- I did not change any permissions recently.
- I did change the JWT Audience field recently, perhaps it has something to do with that?
- I also recently updated to version 2.5.117, maybe it has something to do with that?

Because I have no way of accessing the admin area, I cannot change any settings any more. Is there any way, for example, to change the JWT Audience variable by accessing the docker database directly?

**Host Info (please complete the following information):**
OS: Ubuntu 18.04, Docker
Wiki.js version: 2.5.117
Database engine: postgres

**Comment by Smankusors** [comment]
perhaps you are not logged in. The administration area currently not redirecting you to login page if you logged out.

**Comment by joppehoekstra** [comment]
I am able to log in successfully. However, after being logged in, I still cannot access the admin area, edit a page or view my profile page.

**Comment by joppehoekstra** [comment]
I was able to resolve the issue without any data loss by reverting a backup, and then syncing with our GitHub mirror.
