### ISSUE TITLE
Avatar asset permissions

### ISSUE THREAD

**Issue by rafacouto** [Requarks/wiki#2411]
**Describe the bug**
When an user has avatar (imported from LDAP in my case) it is not shown by permissions (GET is forbidden).

**To Reproduce**
1. Configure LDAP auth
2. Login the first time with an user with avatar image in LDAP
3. Review avatar image is not appearing
4. Add the user to the Administrators group
5. Review avatar image is appearing

**Expected behavior**
User avatar must appear to the user itself.

**Screenshots**
![user menu without avatar image](https://i.imgur.com/tNznmSb.png)
![user menu with avatar image](https://i.imgur.com/I6d37wO.png)

**Host Info (please complete the following information):**
 - OS: Docker
 - Wiki.js version: 2.5.126
 - Database engine: postgres 10.4

**Additional context**
- Access control on code: [common.js](https://github.com/Requarks/wiki/blob/68d31af7af252faa8ca43cdba541f6d9977ea448/server/controllers/common.js#L396)

**Comment by NGPixel** [comment]
Is the user part of a group with `read:pages` permission?

**Comment by NGPixel** [comment]
That's not necessary, it's the global permission `read:pages` that is checked, not a page rule.

**Comment by NGPixel** [comment]
Fixed by 5295e413be9d661e39b020521ff025f17933a13f
