### ISSUE TITLE
How to add Robots.txt on aws docker container

### ISSUE THREAD

**Issue by jlippold** [Requarks/wiki#2412]
**Question**

I'd like google not to index my wiki. I won't be adding users aside from our admin login. 

Whats the recommended way to add a robots.txt in an AWS docker container?

**Host Info (please complete the following information):**
OS: AWS Docker Container
Wiki.js version: 2.5.126
Database engine: postgres 11.8

**Comment by NGPixel** [comment]
under Admin > General
