### ISSUE TITLE
Is there a way to create assets with the GraphQL API?

### ISSUE THREAD

**Issue by kurtis318** [Requarks/wiki#2413]
**Question**
I have been able to create an HTML page with the GraphQL API and now I want to create an asset using the same API.
The PlayGround schema browsers only shows functions to create a folder, rename an asset, delete an asset and flush uploads.  Unless I am missing something, it appears this is not possible.  Can someone confirm?

Here is the shema doc browser I am basing my understanding on. 
![image](https://user-images.githubusercontent.com/8187747/92658316-fc10ff80-f2bb-11ea-8ff2-197bc7cd5495.png)

**Host Info (please complete the following information):**
OS: Fedora 32 Server
Wiki.js version: 2.5.126
Database engine: 12.4

**Comment by NGPixel** [comment]
No, uploads are handled by a standard REST API:

**POST** `/u`
Body must be a multipart/form-data and have a file array field named `mediaUpload`.
You must still pass the authorization jwt in the header just like you do for any GraphQL query.
