### ISSUE TITLE
Multi projects/nav menus in single Wiki.js instance

### ISSUE THREAD

**Issue by iWangJiaxiang** [Requarks/wiki#2414]
**Question**

Hi, developers. Thank you for bringing us such an awesome oss wiki solution!

If my team has many projects that need to be documented in **Wiki.js**, do I need to deploy multi **Wiki.js** instance for each one of project? 

Is there an elegant way to host projects' docs in single **Wiki.js** instance?

The virtual folder struct could handle the hierarchy of projects but I could not setup multi nav menus for each one the project.

Do you have any suggestion?

**Host Info (please complete the following information):**
OS: Docker
Wiki.js version: 2.5
Database engine: postgres 9.7

**Comment by MarsWarrior** [comment]
Seems you want something like Bookstack is using: shelves and books.

If you open a Book, you only see the menu/toc for that Book.

You can have hundreds of Books without having a single menu for all those books...

**Comment by MarsWarrior** [comment]
Some sort of "namespace" feature would be nice in that case, where you can create a menu per namespace.
A namespace can be a team or group (or in Bookstack terms a shelf).

I also thought that collapsible menu's are coming to WikiJs as you can see here: https://requarks.canny.io/wiki/p/dropdown-navigation-items
That would already greatly enhance the overview on the menu.
Each collapsible menu can be considered a Book in Bookstack terms...
