### ISSUE TITLE
Sideloading locale files

### ISSUE THREAD

**Issue by SRHarrison13** [Requarks/wiki#2419]
Hello,

I have installed Wiki.js for an offline environment using the installation guide below (modified for CentOS):
https://docs.requarks.io/install/ubuntu

Because it is an offline environment, Wiki.js throws a general error regarding being unable to download locales. I downloaded the Wiki.js locale files from the wiki-localization github, and attempted to sideload the files as described in:
https://docs.requarks.io/install/sideload

However, the files do not load, and when viewing the "Locale" section in the administration area, the "Sideload" section is greyed out, with a "Coming soon" message.

Is the sideloading feature supported currently? If so, do I seem to be missing any steps to be able to sideload the locale files?
**Note: I first attempted this with version 2.4.107, and again with version 2.5.126. 

**Host Info (please complete the following information):**
OS: Docker
Wiki.js version: 2.5.126
Database engine: postgres 12.3

**Comment by NGPixel** [comment]
Have you set the offline flag to true in your config.yml?

**Comment by SRHarrison13** [comment]
Yes, I did, and nothing appeared to change. Below is my config.yml:

`port: 3000`
`bindIP: 0.0.0.0`
`offline: true`
`db:`
`  type: $(DB_TYPE)`
`  host: '$(DB_HOST)'`
`  port: $(DB_PORT)`
`  user: '$(DB_USER)'`
`  pass: '$(DB_PASS)'`
`  db: $(DB_NAME)`
`  storage: $(DB_FILEPATH)`
`  ssl: $(DB_SSL)`
`ssl:`
`  enabled: $(SSL_ACTIVE)`
`  port: 3443`
`  provider: letsencrypt`
`  domain: $(LETSENCRYPT_DOMAIN)`
`  subscriberEmail: $(LETSENCRYPT_EMAIL)`
`logLevel: info`
`ha: $(HA_ACTIVE)`

Perhaps I put the flag in the incorrect section? I am fairly new to Docker.

**Comment by SRHarrison13** [comment]
Nevermind, I was dumb and restarted the wrong container. After restarting the container with both the altered config file AND the sideload folder, the locales loaded correctly. Thank you!!!
