### ISSUE TITLE
Are LDAP users supported with with GraphQL API?

### ISSUE THREAD

**Issue by kurtis318** [Requarks/wiki#2420]
**Question**
I now have a Wiki.js site running using LDAP authentication.  My LDAP userid is in the Administrators group and I can log into the web site and access all Administrator functions (GraphQL does not work).  When I try to perform a login, I must specify a **strategy** field as input.  For local users I specify 'local'.  I tried 'ldap' and 'LDAP' and both give me: **"message": "Invalid authentication provider."** in the **responseResult**.  I am not able to find any documentation of what valid values of the **strategy** field are.  Maybe LDAP users are not supported?   I was able to run the login mutation with a local user with Administration authority.  Anyone know for sure?

**Host Info (please complete the following information):**
OS: Fedora 32 Server
Wiki.js version: 2.5.126
Database engine: 12.4

**Comment by NGPixel** [comment]
The provider is a unique UUID key, not the authentication module ID. You can list active strategies and their UUID using query:
```gql
{
  authentication {
    activeStrategies {
      key
      displayName
    }
  }
}
```
