### ISSUE TITLE
Logged out users can see everything

### ISSUE THREAD

**Issue by lcalem** [Requarks/wiki#2421]
**Question**
I have created users with a given set of permissions allowing them to access only folder X (out of all folders X Y Z available). Login works fine, user only sees folder X, however when logging out via the Logout button, I'm not redirected to the login page, instead I'm logged out and can see all X Y Z folders on the left bar.
What I should do in the configuration to redirect logged out users to the login page?

**Host Info (please complete the following information):**
OS: [Container Alpine Linux v3.11]
Wiki.js version: [2.5.126]
Database engine: [postgres 11.9]

**Comment by Igorgro** [comment]
You should edit permissions for 'Guests' group

**Comment by lcalem** [comment]
Perfect thanks!
