### ISSUE TITLE
unable to run 'node server'

### ISSUE THREAD

**Issue by TECH-JEFF** [Requarks/wiki#2422]
Hi,

Trying out Wiki.js to install in a Windows Server 2016 Standard. Been following the directions and I'm on the part where I have to execute a cmdlet 'node server' basically to run the service I assume but it shows me the term 'node' is not recognized. 

Tried to install nodejs but unsuccessful. 

Wiki.js version: 2.5.126
Postgres version: not sure but it shows 9.5 or later

Appreciate any help on this.

Thanks and have a great day!
TECH-JEFF

**Comment by Smankusors** [comment]
Have you installed the Node.js?

**Comment by TECH-JEFF** [comment]
@Smankusors 
I did download from this URL: https://nodejs.org/en/ using version 12.18.3 LTS

**Comment by Smankusors** [comment]
Perhaps you are not adding the node.js to PATH variable? Can you check the PATH variable, is it contains your node.js path installation?

Or maybe.... try to open the new fresh Command Prompt?

**Comment by TECH-JEFF** [comment]
Sorry for the incomplete post, yes I did check the path and this is what's inside the path

%USERPROFILE%\AppData\Local\Microsoft\WindowsApps
C:\Program Files\nodejs

**Comment by TECH-JEFF** [comment]
I think it worked now and all I did was reboot, 

thanks for the inputs

**Comment by TECH-JEFF** [comment]
as I continue in following the instructions, now it recognize the 'node' command as soon as I execute the command in step 8 in the URL below:

https://docs.requarks.io/install/windows

It shows the below error message

PS D:\wiki> node server
node : FAILED
At line:1 char:1
+ node server
+ ~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (FAILED:String) [], RemoteExceptio 
   n
    + FullyQualifiedErrorId : NativeCommandError
 
end of the stream or a document separator is expected at line 13, column 1:
    port: 3000
    ^
>>> Unable to read configuration file! Did you create the config.yml file?

Though I've already renamed the config file changing port to 3000 and made sure postgres is selected

**Comment by TECH-JEFF** [comment]
nvm my post above, it's resolved.

**Comment by Smankusors** [comment]
hmm well... if you issue is resolved, feel free to close this issue.
