### ISSUE TITLE
Portuguese translation

### ISSUE THREAD

**Issue by guimachadooo** [Requarks/wiki#2428]
Hi people, everything fine?

Just a doubt, is there some forecast for complete portuguese translation?

Because we love the tool and we start to use it for our customers, but they really need
to read all in portuguese and some elements don't get the translation, here's an example:

![image](https://user-images.githubusercontent.com/54110006/92967267-50001d80-f44f-11ea-947b-2e577366201b.png)
![image](https://user-images.githubusercontent.com/54110006/92967286-5abab280-f44f-11ea-864c-2d5353d8a73d.png)

**Comment by NGPixel** [comment]
Translations are entirely provided by the community... You can't expect the maintainer of this project to know 30+ languages.

Feel free to contribute [here](https://docs.requarks.io/dev/translations)
