### ISSUE TITLE
Animated svg not working

### ISSUE THREAD

**Issue by Igorgro** [Requarks/wiki#2433]
**Describe the bug**
Inline animated SVGs not working in HTML editor.

**To Reproduce**
1. Create HTML page
2. Add SVG like this one:
```xml
<svg width="300" height="100">
  <rect x="0" y="0" width="300" height="100" stroke="black" stroke-width="1" />
  <circle cx="0" cy="50" r="15" fill="blue" stroke="black" stroke-width="1">
    <animate
       attributeName="cx" from="0" to="500"
       dur="5s" repeatCount="indefinite" />
  </circle>
</svg>
```
3. Render page and watch svg turned into
```xml
<svg height="100" width="300">
  <rect stroke-width="1" stroke="black" height="100" width="300" y="0" x="0"></rect> 
  <circle stroke-width="1" stroke="black" fill="blue" r="15" cy="50" cx="0"></circle>
</svg>
```
without animation

**Expected behavior**
The 1:1 SVG with animation.

**Host Info:**
 - Wiki.js version:  2.5.132

**Comment by NGPixel** [comment]
You need to disable HTML Sanitization (under Admin > Rendering > HTML > Security).

DOMPurify (the sanitization module) considers the animate tag as a potential XSS attack vector, which is why it's stripped from the output.
