### ISSUE TITLE
Inserting login screen background image from assets does not work

### ISSUE THREAD

**Issue by madodig** [Requarks/wiki#2437]
**Describe the bug**
Selection and insertion of the image asset under _Administration / Security / Login / LOGIN SCREEN / Login Background Image URL_ does not set the value of the _Login Background Image URL_ field to the asset path.
Typing or pasting the asset path in the filed, and then selecting _Apply_, works.

**To Reproduce**
1. Navigate to _Administration / Security_;
2. Click on image folder button under _Login / LOGIN SCREEN / Login Background Image URL_;
3. Select the asset and click on _Insert_.
    _Login Background Image URL_ field remains empty.
    Applying settings does not change the login screen background (due to the empty field).
4. Manually edit the asset path in the _Login Background Image URL_ field;
5. Click on _Apply_;
    Login screen background image is changed.

**Expected behavior**
_Login Background Image URL_ field value should be automatically set to the path of the 'inserted' asset.

**Host Info:**
 - OS: CentOS Linux release 8.2.2004 (Core)
 - Wiki.js version: 2.5.136
 - Database engine: PostgreSQL 12.1

**Comment by NGPixel** [comment]
Fixed by a381d4f31424cffc14182ca341cd483850ff830d
