### ISSUE TITLE
Login screen is not fully localised

### ISSUE THREAD

**Issue by madodig** [Requarks/wiki#2438]
**Describe the bug**
Terms "Select Authentication Provider" and "Enter your credentials" in Login screen are not shown in Base locale (they are shown in English) because they are hard-coded (assets/js/login.js).

**To Reproduce**
1. Change Base Locale under Administration / Locale / Locale Settings to a language other than English and click Apply;
2. Logout;
3. Navigate to Login screen;
4. Login screen is shown in selected Base locale, except for the terms:
   - "Select Authentication Provider";
   - "Enter your credentials".

**Expected behavior**
Login screen is fully localized.
To fix, please switch from hard-coding to localization keys for the values, e.g.:
```
"auth:strategy.title": "Select Authentication Provider",
"auth:credentials.title": "Enter your credentials"
```
**Host Info:**
 - OS: CentOS Linux release 8.2.2004 (Core)
 - Wiki.js version: 2.5.136
 - Database engine: PostgreSQL 12.1

**Additional context**
Tested with Croatian Base locale, verified in the corresponding assets JS file.
Bug is not specific to the latest version.
There are other terms that are not localized as well, but they are under Administration area hence they do not impact UX of a regular user. It would be great to have wiki completely localisable, though.

**Comment by NGPixel** [comment]
Fixed by e782f85a1da9f2a9c1dd5659777e3cf134b5e1cb
