### ISSUE TITLE
Login bypassing doesn't work 

### ISSUE THREAD

**Issue by yesyesiamkamil** [Requarks/wiki#2440]
**Question**
Hi! I'm enabled bypassing in the security settings but when i'm trying to login it's opening the /login page with list of auth providers. 
I'm expecting that bypassing feature will open the auth0 page when i'm going to /login without classic Wiki.js interface with providers list. Am i right? 

Using Wiki.Js from Digital Ocean Marketplace
https://yadi.sk/i/O0EA6v7tVHoWpA
https://yadi.sk/i/XhOQ6ZtH0EUf5Q

**Host Info (please complete the following information):**
OS: [e.g. Ubuntu 18.04, Docker]
Wiki.js version: [e.g. 2.5.136]
Database engine: [e.g. postgres 11.8, mysql 5.7]

**Comment by NGPixel** [comment]
Is Auth0 the first provider in the list? It won't work if Local Auth is in first place. Re-order your providers so that Auth0 is first place and Local Auth second.
