### ISSUE TITLE
Auth0 icon not visible on login screen

### ISSUE THREAD

**Issue by eeshugerman** [Requarks/wiki#2441]
**Describe the bug**
The Auth0 icon is not visible on the login screen because the icon color is the same as the background color. It does appear faintly on hover, however.

**To Reproduce**
1. Enable the Auth0 module
2. Observe the login screen

**Expected behavior**
Auth0 icon is visible

**Screenshots**
![image](https://user-images.githubusercontent.com/25518211/93030490-abade080-f5e0-11ea-8433-4e2f3342f7f0.png)

**Host Info (please complete the following information):**
 - OS: Docker
 - Wiki.js version: 2.5.136
 - Database engine: PostgreSQL 12.4

**Additional context**

**Comment by NGPixel** [comment]
Fixed by 6340f21969608a766d4d9bdde295dacecedc8151
