### ISSUE TITLE
White screen on Microsoft Edge (without Chromium)

### ISSUE THREAD

**Issue by LuckyF** [Requarks/wiki#2447]
**Describe the bug**
When opening the main page on Microsoft Edge (without the Chromium engine), the browser only shows a white screen.
Everything works fine on Chrome and Chromium-Edge.

Was Microsoft Edge Support dropped on v2.5?

**To Reproduce**
1. Go to 'Home'
4. See white page

**Expected behavior**
Show homepage

**Host Info (please complete the following information):**
 - OS: Docker
 - Wiki.js version: 2.5.144
 - Database engine: postgres

**Additional context**
The Keycloak plugin is used to login.

**Comment by NGPixel** [comment]
Considering the legacy Microsoft Edge will no longer be supported by Microsoft in March 2021 and that the new chromium Edge has been pushed to all users, this issue will not be investigated.
