### ISSUE TITLE
How or where can email templates be adjusted / set?

### ISSUE THREAD

**Issue by HiveMindNet** [Requarks/wiki#2450]
**Question**
How or where can email templates be adjusted / set?

**Host Info (please complete the following information):**
OS: Latest Docker
Wiki.js version: 2.5.136
Database engine: postgres (PostgreSQL) 11.8

I finally managed to enable creation of accounts using Graphql, but can't enable sendWelcomeEmail:true or notify new account holders that they now have an account.

I can do it on my other app, but it seems like there's templates already for pwd reset so wondered if I was just missing something?

Any pointers are much appreciated.

Thanks in advance

**Comment by NGPixel** [comment]
Email templates are located in `/server/templates`:
https://github.com/Requarks/wiki/tree/dev/server/templates

**Comment by HiveMindNet** [comment]
Thanks @NGPixel - but there’s no setting then? I ask as using Docker makes editing source files not persistent after updates; obviously. 

If you know a way or if it’s a future feature, do let me know. Thanks :)

**Comment by NGPixel** [comment]
These are not editable via the UI or settings no.
