### ISSUE TITLE
Trying to connect with MSSQL: EINSTLOOKUP Error

### ISSUE THREAD

**Issue by Yorams** [Requarks/wiki#2451]
**Question**
Trying to connect with MSSQL but i get the error:
`error: Database Connection Error: EINSTLOOKUP undefined:undefined`

I've searched via google but all the answers I get do not apply to wiki.js. I understood that wiki.js uses the nodejs package Tedious. So I looked at their website: https://tediousjs.github.io/tedious/frequently-encountered-problems.html
I have Enabled TCP/IP port via SQL Configuration Manager.

They say that MSSQL express doesn't work with Tedious, does it?

My configuration is:
```
type: mssql
host: localhost\\SQLEXPRESS
port: 1433
user: wiki
pass: wikiuser
db: wiki
```

**Host Info:**
OS: Windows 10 v2004
Wiki.js version: 2.5.144
Node.js version: 12.18.3
Database engine: MSSQL Expresssql 2019 (i guess latest, i downloaded it today from the microsoft website.)

**Comment by NGPixel** [comment]
MSSQL Express is not supported. While it's supported by tedious, it requires some additional parameters to be set (e.g. Instance Name) which will not be added to Wiki.js. Please use the standard MSSQL Server.
