### ISSUE TITLE
JWT config - no login possible

### ISSUE THREAD

**Issue by TriathlonDivIT** [Requarks/wiki#2456]
Hello,

I set the JWT-Field in the page security in wiki.js administration to my valid Domain and can´t log in with my admin-account anymore. System resets to login-page.
Can I change it and re-login without setting up a new system?

many thanks in advance
Ricardo

Host Info:
OS: Ubuntu, Wiki.js 2.4.107, Docker
Wiki.js version: 2.5.144
Database engine: postgres 9.7

**Comment by madodig** [comment]
Hi,

did you restart your Wiki service?

If restarting doesn't help, try changing the value directly in the database, but be very careful.

Steps:
1) Connect to the server remotely
2) Stop Wiki service
3) Backup Wiki database
4) Connect to the database:
`sudo -u <DB_USER> psql -d <YOUR_DB_NAME>`
; EXAMPLE:
`sudo -u postgres psql -d wiki-db`
5) Get current configuration:
`SELECT * FROM settings WHERE key='auth';`
; EXAMPLE OUTPUT:
```
 key  |                                                                        value                                                                         |        updatedAt
------+------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------
 auth | {"autoLogin":false,"enforce2FA":false,"hideLocal":false,"loginBgUrl":"","audience":"urn:wiki-error.js","tokenExpiration":"30m","tokenRenewal":"14d"} | 2020-09-15T17:18:10.889Z
(1 row)

```
6) Copy entire value, and change urn value to what you had previously (e.g. from "urn:wiki-error.js", to "urn:wiki.js")
7) Update auth settings
`UPDATE settings SET value='<YOUR_SETTINGS>' WHERE key='auth';`
; EXAMPLE:
`UPDATE settings SET value='{"autoLogin":false,"enforce2FA":false,"hideLocal":false,"loginBgUrl":"","audience":"urn:wiki.js","tokenExpiration":"30m","tokenRenewal":"14d"}' WHERE key='auth';`
8) Close database connection
`exit`
9) Start Wiki service

**Comment by TriathlonDivIT** [comment]
Hi madodig,

everything works perfekt after a restart of the docker service. That was ist. 
Thank you very much for the help and also the tutoral you prepared.

**Comment by madodig** [comment]
Hi,

     no problem, glad you've solved it!

**Comment by Smankusors** [comment]
if your issue is resolved, feel free to close this issue 😉
