### ISSUE TITLE
Did update. Site unreachable.

### ISSUE THREAD

**Issue by rwmia** [Requarks/wiki#2457]
I performed the update to 2.5.144  in the wiki admin, now the site is unreachable. Connection refused.
 
Unfortunately the droplet on digital ocean was not being backed up. Fail on my part.

Is there any way to restore from droplet ssh? Please help.

Wiki.js 2.5.117 on Ubuntu 18.04 droplet.

**Comment by rwmia** [comment]
Reading the docker logs, I get an error for SSL. Rate limit reached for Lets Encrypt. Never happened before.

**Comment by rwmia** [comment]
I have narrowed down the issue to the SSL certificate renewal via LetsEncrypt. The update companion seems to be stuck trying to renew the certificate, but LetsEncrypt 

{\"type\":\"urn:ietf:params:acme:error:rateLimited\",\"detail\":\"Error creating new order :: too many certificates already issued for exact set of domains

Is it possible to either stop the update companion or wikijs from constantly trying to renew the cert? How about turning off SSL and SSL redirect?

**Comment by NGPixel** [comment]
The update companion doesn't do anything related to SSL.

You can disable SSL by recreating the docker container without the LETSENCRYPT and SSL env variables. See
https://docs.requarks.io/install/ubuntu#setup-containers (line 15)

**Comment by rwmia** [comment]
Direct IP works, non ssl. 

I created a fresh container for wikijs, disabling SSL (-e SSL_ACTIVE=0) , but it seems that the http to https redirect is still enabled from prior install?

**Comment by NGPixel** [comment]
You need to disable that flag in the DB. In the settings table.

**Comment by rwmia** [comment]
Unfortunately I am a novice in postgres within docker. Is there a simple `docker run db 'SET...' `you could provide.

**Comment by NGPixel** [comment]
See https://docs.requarks.io/en/troubleshooting#for-docker-users-1
