### ISSUE TITLE
need help to import markdown dump data to wiki.js..  however i have configured wiki.js for test run internally in my system.  Need someone to contact me and guide. i am reachable+91 8978979990

### ISSUE THREAD

**Issue by Thanigi** [Requarks/wiki#2460]
**Question**
Describe in details what you are trying to achieve and where do you need guidance.

**Host Info (please complete the following information):**
OS: [e.g. Ubuntu 18.04, Docker]
Wiki.js version: [e.g. 2.0.1]
Database engine: [e.g. postgres 9.7, mysql 5.7]

**Comment by NGPixel** [comment]
This isn't a free service where we guide you through installation on the phone.

Either write a proper ticket with detailed info here (and NOT all in the title like you did) or hire a dev/sysadmin for help somewhere else (here is not the place).
