### ISSUE TITLE
Unable to view images - res.SendFile

### ISSUE THREAD

**Issue by wrongecho** [Requarks/wiki#2463]
**Unable to view images - res.SendFile**
Unable to view images after update. Console shows an error and the page just shows the filename instead of an image.
`[MASTER] error: path must be absolute or specify root to res.sendFile`

**To Reproduce**
Updated from version 2.4.107 to 2.5.144 and can no longer view images.

**Expected behavior**
The images should show.

**Screenshots**
![image](https://user-images.githubusercontent.com/32306651/93363073-a8179500-f83e-11ea-8b6c-61b61d73b3e7.png)
![image](https://user-images.githubusercontent.com/32306651/93363094-afd73980-f83e-11ea-929c-bb1b9f9b0816.png)

**Host Info (please complete the following information):**
 - OS: Windows
 - Wiki.js version: 2.5.144
 - Database engine: Postgres 11

**Additional context**
If images are deleted and re-uploaded, they display fine. If you navigate to where an image used to be directly, you get an Internal Server Error.

**Comment by NGPixel** [comment]
Have you tried to clear the server cache first?
Admin > Utilities > Flush Cache

**Comment by wrongecho** [comment]
Hi @NGPixel. Thanks for getting back to me! Flushed the Pages and Assets Cache, Temp Upload and local browser cache and then restarted the server also. Still getting the error regarding the absolute path or specifying a root path to res.SendFile. Any ideas?

**Comment by czabak** [comment]
Any news? We updated WikiJS to the newest version but it did not help.

**Comment by wrongecho** [comment]
@czabak, unfortunately not. We only had 30 or so pages so just spun up another instance of Wiki JS on a different port and manually re-created all the pages.

**Comment by czabak** [comment]
I've just figured that when I upload new files they are working correct. I found that when I upload the same file - overwrite it everything is ok.
Is it a solutions to "refresh" all of uploaded files or do I have to upload it manually?

**Comment by Fakhri-Hasanzadeh** [comment]
Suggested solution:


this line:
```yaml
await sendFile(cachePath, { dotfiles: 'deny', root: "/opt/wiki/" })
```


replace with this line:
```yaml
try {
await sendFile(cachePath, { dotfiles: 'deny' })
}catch (error) {
await sendFile(cachePath, { dotfiles: 'deny', root: '/opt/wiki/' })
}
```

**Comment by lucas-it** [comment]
I'm having the same issue with the latest version of WikiJS (2.5.276). Is a fix will be available soon ? I tried to to flush cache in ``Admin > Utilities > Flush Cache`` but it doesn't fix.

**Comment by Hagbrain** [comment]
> Suggested solution:
> 
> this line:
> 
> ```yaml
> await sendFile(cachePath, { dotfiles: 'deny', root: "/opt/wiki/" })
> ```
> 
> replace with this line:
> 
> ```yaml
> try {
> await sendFile(cachePath, { dotfiles: 'deny' })
> }catch (error) {
> await sendFile(cachePath, { dotfiles: 'deny', root: '/opt/wiki/' })
> }
> ```

Were using WikiJS and have the same issue, in wich file do i need to change the code?

Kind Regards
Dom

**Comment by CanYellow** [comment]
the file path is  [wikipath]/server/model/assets.js.

**Comment by Ionys320** [comment]
I suggest you to use `WIKI.ROOTPATH`:

```js
try {
    await sendFile(cachePath, { dotfiles: 'deny' })
} catch (error) {
    await sendFile(cachePath, { dotfiles: 'deny', root: WIKI.ROOTPATH })
}
```

**Comment by SanQianQVQ** [comment]
same problem in 2.5.306

**Comment by jonadias1** [comment]
> > Solución sugerida:
> > Esta línea:
> > await sendFile(cachePath, { dotfiles: 'deny', root: "/opt/wiki/" })
> >     
> >   
> > Reemplazar con esta línea:
> > try {
> > await sendFile(cachePath, { dotfiles: 'deny' })
> > }catch (error) {
> > await sendFile(cachePath, { dotfiles: 'deny', root: '/opt/wiki/' })
> > }
> 
> Estoy usando WikiJS y tengo el mismo problema, ¿en qué archivo necesito cambiar el código?
> 
> Un cordial saludo, Dom

Utilice esta solucion y me funciono aplicandola dentro del docker en el archivo `server/models/assets.js`
