### ISSUE TITLE
GraphQLSchema Fatal Error

### ISSUE THREAD

**Issue by axisofentropy** [Requarks/wiki#2464]
**Describe the bug**
After installation, the wiki.js container crashes around the time it loads the GraphQL Schema. See the log entries at the end of this report.

All of the 2.5 releases on Docker Hub seem to be affected, but the `2.4` tag works ok.  Also I built an image on my workstation from the `dev` branch and it works ok. This may be a build-time fault.

Of course I'm surprised to not see this issue reported so I wonder if there's something specific to our environment, but I'm not a node.js developer so I'm not sure where to look.

**To Reproduce**
Start a new container connected to a new Postgres database. Complete installation. Check logs.

**Host Info (please complete the following information):**
 - OS: Google Kubernetes Engine 1.17.9
 - Wiki.js version: several 2.5 builds on Docker Hub. 2.4 not affected.
 - Database engine: postgres 11

**Additional context**

this commit was between 2.4 and 2.5 and may be relevant? https://github.com/Requarks/wiki/commit/52125eee73f826bae5d03791607efaea8c8bcbf3

Log entries:
```
2020-09-16T18:29:05.479Z [MASTER] [32minfo[39m: Loading GraphQL Schema...
2020-09-16T18:29:11.177Z [MASTER] [32minfo[39m: GraphQL Schema: [ OK ]
2020-09-16T18:29:12.877Z [MASTER] [31merror[39m: Cannot use GraphQLSchema "[object GraphQLSchema]" from another module or realm.
{}
Ensure that there is only one instance of "graphql" in the node_modules
directory. If different versions of "graphql" are the dependencies of other
relied on modules, use "resolutions" to ensure only one version is installed.
{}
https://yarnpkg.com/en/docs/selective-version-resolutions
{}
Duplicate "graphql" modules cannot be used at the same time since different
versions may have different capabilities and behavior. The data from one
version used in the function from another could produce confusing and
spurious results.
```

**Comment by NGPixel** [comment]
This is definitely specific to your environment as nobody else reported this issue and the 2.5 docker image has been used extensively since the commit you mentioned. Do you have the same issue with `requarks/wiki:canary-2.5.143`?

**Comment by axisofentropy** [comment]
Yes, this is a weird one. What could be specific about any environment that would cause a node library issue like this?

I'm not able to reproduce with any version right now but I'll keep trying.

**Comment by axisofentropy** [comment]
Looking closer at container logs from this morning, it was in a crash/restart loop for an hour or two but then started showing a different error:

```
2020-09-16T17:51:09.243Z [MASTER] [32minfo[39m: Database Connection Successful [ OK ]
2020-09-16T17:51:09.534Z [MASTER] [31merror[39m: Database Initialization Error: The migration directory is corrupt, the following files are missing: 2.5.1.js, 2.5.12.js
```

Do you have any insight into how these things could be connected?

**Comment by axisofentropy** [comment]
We've tried to reproduce this all afternoon without luck. I'll dig deeper if we see it again. Thanks for your patience.
