### ISSUE TITLE
raw wiki content

### ISSUE THREAD

**Issue by BuhtigithuB** [Requarks/wiki#2466]
**Question**
I am searching a way to convert page content (the raw content put in the wiki) something like http://wiki/s/en/home (notice the "s" in the url)... Although that view which display wiki content is embeded in whole site I would rather want to have a way to get the raw content of the wiki (like raw function in github)... Also "s" view appears to be only available if someone is logged in which doesn't help... Anyway to get the raw content?

I am writting my own pandoc page converted tool.

Thanks

**Comment by NGPixel** [comment]
You need to use the GraphQL API to get raw content..

**Comment by BuhtigithuB** [comment]
ok thanks, I am going to learn that... :)
