### ISSUE TITLE
docker - data persistence

### ISSUE THREAD

**Issue by sebz1504** [Requarks/wiki#247]
Hi,

I'm trying to set data persistence in docker. 
I set both directories as volume: 
- /var/wiki/repo
- /var/wiki/data

After container delete/recreate, I can see the files under repo and data (.md for example),  but nothing is displayed when navigating on "All pages" menu (/all).

What is the correct way to do it ?

Thanks

**Comment by NGPixel** [comment]
You shouldn't.

`/var/wiki/data` should definitely not be persisted. It contains temporary data only.
As for `/var/wiki/repo`, unless you have git sync disabled, there's no need to persist that folder either.

Check in your `/logs` folder for errors.

**Comment by sebz1504** [comment]
Ok that was the reason, I wasn't using git sync. Now, I configured git, and removed the volumes. Everything is working fine.
Thank you !
