### ISSUE TITLE
Generic OpenID Connect / OAuth feature doesn't work as expected

### ISSUE THREAD

**Issue by jschirrmacher** [Requarks/wiki#2474]
**Describe the bug**
I configured OIDC to authenticate by Rocket.Chat.
After clicking on the authenticate button in the Wikijs login page, I'm redirected to Rocket.Chat, and after logging in there, I'm redirected to the Callback-URL / Redirect-URI which is specified in the Wikijs authorization configuration (https://my-wiki-host/login/<code>/callback with parameters `code` and `state`.
However, the URL returns  HTTP 500 with HTML content containing "Oops, something went wrong...Invalid email / username or password".

Regrettably the log doesn't show anything, and due to #1902 the log level can not be increased.

**To Reproduce**
1. Set up WikiJS and Rocket Chat via docker
2. Configure WikiJS to authenticate via Rocket Chat (configuration on both sides)
3. Try to authenticate in WikiJS via Rocket.Chat
4. See the error page from WikiJS

You might check that by creating an account on https://community.xcamp.co/ and then try to login on https://wiki.xcamp.co/  via "XCamp Community".

**Expected behavior**
I would expect WikiJS to log in the authenticated user.

**Host Info (please complete the following information):**
 - OS: Docker (Alpine)
 - Wiki.js version: 2.5.144
 - Database engine:postgres 9

**Comment by NGPixel** [comment]
That's because while Rocket.chat supports OAuth2, it doesn't support OpenID Connect, which is what you're trying to use. I added a new auth module specific to rocket.chat which fetches the user profile via the REST API instead (b0f61d66055aefd6fc52069be2e4e8ad57cff9c1)
