### ISSUE TITLE
Navigation menu breaks when new pages are imported from Git

### ISSUE THREAD

**Issue by eeriksp** [Requarks/wiki#2476]
**Describe the bug**
After importing some `.md` files from Git, no pages are shown in the navigation drawer and the loading circle in the top right corner will be looping endlessly. On the console there is the message `Could not find current page in page tree listing!`.

**To Reproduce**
1. Set up Git integration
2. Go to Administration area > Storage > GIt and click "Force Sync" and then "Import Everything"
3. Go to the home page and look at the navigation menu which might not be showing properly

However, this does not always produce a bug. Usually it worked just fine. In the folder which produced the problem, there was one file without the the `.md` extension, perhaps this causes the problem.

**Screenshots**
![image](https://user-images.githubusercontent.com/35540617/93735652-57a98a00-fbe6-11ea-860d-b9773989321e.png)

**Host Info (please complete the following information):**
 - OS: Ubuntu 20
 - Wiki.js version: 2.5.144
 - Database engine: sqlite

**Additional context**

I have tried to fix the error by going to the Administration area > Utilities and executing

1. Content > Rebuild Page Tree
2. Content > Rerender All Pages

**Comment by pchinery** [comment]
This is the same bug as in #1503 and can be hot-fixed as mentioned in #2553 (I had the same issue and have just verified this with my instance)
