### ISSUE TITLE
Page Redirect setting for Groups

### ISSUE THREAD

**Issue by jpc54321** [Requarks/wiki#2478]
Despite the setting within the Group allowing for a redirect as documented here:

https://docs.requarks.io/groups (scroll down to the bottom)

![image](https://user-images.githubusercontent.com/71628021/93739071-4b6dfe80-fbdf-11ea-9ed9-32431c87d5a4.png)

It does not work.

All users, who are members of a private group are logged on to the default home page.

**Comment by jpc54321** [comment]
I have since noticed that if you use the 'Login As' button when you get an 'Unauthorised' login you can actually login with the same credentials and you are taken to the correct page as specified with the redirect on group. But, you end up with the permissions set again the group and not the permissions as specified with the page rules.

**Comment by dominicgermain** [comment]
exact same issue here... redirect only work after hitting the "Unauthorise" page

**Comment by betepok13** [comment]
I noticed this problem as well. I haven't found a solution yet. I had to create a common start page for all so that all users after authorization would go to it. And only then did they manually follow the link to their category / directory.

**Comment by NGPixel** [comment]
Is the user part of multiple groups? Redirect won't work as expected if the user is part of multiple groups. The system will simply take the first group and use the redirect setting for that group.

**Comment by betepok13** [comment]
> 
> 
> Is the user part of multiple groups? Redirect won't work as expected if the user is part of multiple groups. The system will simply take the first group and use the redirect setting for that group.

No. The user is only in one group.

**Comment by NGPixel** [comment]
I'm unable to replicate your issue. Can you provide a detailed step by step guide on a clean installation to replicate the issue?

e.g.
1) create page at path `/special`
2) remove `read:pages` permission from Guests group
3) create group A with permissions X,Y,Z and page rules A,B,C and set redirect after login setting to `/special`
4) create local user U assigned to group A
5) Login with user U

**Comment by betepok13** [comment]
> I'm unable to replicate your issue. Can you provide a detailed step by step guide on a clean installation to replicate the issue?

1. Installed on new server: Ubuntu Server 20.04 LTS
2. Installed Wiki.js according to instructions: https://docs.requarks.io/install/ubuntu
3. Configured initial admin access (email and password)
4. Created the first page: **/home**
5. Created  page: **/special**
6. I went to the admin panel, deleted in group "**Guests**" following access rights: **read:pages**, **read:assets**, **read:comments**. Now the "**Guests**" group does not have access rights on the "**Permissions**" tab.
7. Created a group "**Others**", set a redirect to the page "**/special**" (did not change access rights)
8. Created a second user and added him to the group "**Others**"
9. I closed the admin panel, logged out of the admin account. Logged in as the second user. **Redirect to page "/special" didn't work.** I was directed to the "**/**" page.

### You can see the settings for yourself. Here is my server where Wiki.js is installed:
**http://213.183.45.136/**

**Administrator login and password:**
admin@gmail.com
admin123

**Login and password of the second user:**
test@gmail.com
test123
### Request to other users: do not change the settings on my server.

**Comment by NGPixel** [comment]
@betepok13 Ok I found the issue. It only happens in a very specific case. You can remove the access to your server.

**Comment by jpc54321** [comment]
Thank you to all of the contributors to this. @NGPixel - we will look forward to a resolution as soon as you can.

**Comment by NGPixel** [comment]
Fixed by fe890979afe04e43d90486aaaeda4abd587d62b9
