### ISSUE TITLE
Slack integration

### ISSUE THREAD

**Issue by skapin** [Requarks/wiki#248]
when I try to log with slack, the url link with the SLACK Id is truncated (miss like 8 charactere at the end of the url and so the APP_ID)

Land me a slack error then, but if i past the full id the URL, it's good

The link 
`https://slack.com/oauth/authorize?response_type=code&redirect_uri=http%3A%2F%2F51.15.70.144%3A9999%2Flogin%2Fslack%2Fcallback&scope=identity.basic%20identity.email&client_id=155901121142.XXXXX`

(I replace the end by X with same amount of char.)

this is my conf file (obfuscated)

```slack:
    enabled: true
    clientId: 155901121142.XXXXXXXXXXXX
    clientSecret: XXXXXX```

**Comment by skapin** [comment]
Well after said "okay" to slack, back to WIKI, i got 

```
json is not defined
Oups, une erreur s'est produite

**Comment by skapin** [comment]
I just started the docker-compsoe file, with my custom conf file.

I tried loggin with gihut too, works well but WIKIJS wont let mpe log, telling me my account is log allowed yet. But how can I 1st log to allow my account then ?

**Comment by NGPixel** [comment]
Added quotes in config.sample.yml to force string value. 54107d5041f3a346fce8f9bd1d35392b43d65739
