### ISSUE TITLE
Empty page for Wiki Admin

### ISSUE THREAD

**Issue by sandsturm** [Requarks/wiki#2483]
Hi all. I am running a personal wiki.js using docker behind a reverse proxy. Since the latest update I cannot access the admin page. I get an empty page. The debug console of the browser shows this warning: `Loading failed for the <script> with source "https://notes.mydomain.test/_assets/js/admin.js?1600047985"`. The content of this file is: `/*! Wiki.js - wiki.js.org - Licensed under AGPL */`. I think this could be a wrong asset but it is odd that nobody else seems to have the same issue. 

Any idea what went wrong? I googled the potential source of error since quite some time with success.

**Comment by Smankusors** [comment]
try to open your Wiki on incognito? It could be browser cache issue.
