### ISSUE TITLE
Special Characters “ ' “ Problem

### ISSUE THREAD

**Issue by robertbur** [Requarks/wiki#2493]
**Describe the bug**
When I’m typing a text, and I add something like “'”, example: There's . This gives all the time error json.

**Host Info (please complete the following information):**
 - OS: [ Debian 10, Docker]
 - Wiki.js version: [ 2.5.114]
 - Database engine: [ MariaDB]

**Comment by NGPixel** [comment]
Are you using a reverse proxy like Cloudflare or nginx in front of Wiki.js?

**Comment by robertbur** [comment]
Hi @NGPixel,

Sorry for the delay, affirm. However, I did some tests yesterday and today and is working. Looks like the restart of the Nginx resolved all the issues.

Kind Regards
