### ISSUE TITLE
Markdown Preview always converts line breaks.

### ISSUE THREAD

**Issue by dli7319** [Requarks/wiki#2498]
**Describe the bug**
After disabling 'Automatically Convert Linebreaks' for markdown, the preview still converts soft line breaks into hard line breaks even though the final render does not contain hard line breaks.

**To Reproduce**
1. Go to Administration->Rendering->Markdown
2. Disable 'Automatically Convert Linebreaks'
3. Create a new markdown page with soft line breaks.
4. Line breaks appear in the preview but not in the final render.

**Expected behavior**
Line breaks should not appear in the markdown preview.

**Screenshots**
The preview is incorrect:
![image](https://user-images.githubusercontent.com/27523415/94207007-b4ca6780-fe94-11ea-9592-23c2b6a4bf5e.png)
The rendered page is correct:
![image](https://user-images.githubusercontent.com/27523415/94207063-cf044580-fe94-11ea-847c-e283e84a59d7.png)

**Host Info (please complete the following information):**
 - OS: Docker
 - Wiki.js version: 2.5.144
 - Database engine: Postgres

**Additional context**

**Comment by NGPixel** [comment]
https://requarks.canny.io/wiki/p/mirror-renderer-settings-for-markdown-preview
