### ISSUE TITLE
run wiki error what happen 

### ISSUE THREAD

**Issue by realYangex** [Requarks/wiki#2500]
{"message":"Failed to lookup view \"setup\" in views directory \"D:\\chromeDowload\\wiki-2.5.144\\server\\views\"","error":{}}

**Comment by Smankusors** [comment]
do you, follow the instructions provided [here](https://docs.requarks.io/install/windows) correctly?

**Comment by NGPixel** [comment]
You downloaded the source code instead of a proper release package. Follow the [installation instructions](https://docs.requarks.io/install).
