### ISSUE TITLE
Debug-Dev mode issues

### ISSUE THREAD

**Issue by Maxzor** [Requarks/wiki#2504]
- **Env vars ?** When I debug with node.js preview in vscode (other targets do not work here), the env variables are still production.
- **Hot reload ?...** Do you setup a trigger on file save that will recompile and hot reload the site?
- **... Incremental builds ?** When saving a file and running a new debug session, it seems like webpack does not rebundle properly.
I currently restart from scratch after each change :
commit change, erase all but .git in the project dir, run ```git restore --source=HEAD --staged --worktree -- .```, then ```docker container rm "*"```, rebuild the containers and ```yarn dev``` again...
which is less than ideal :upside_down_face:

**Comment by Maxzor** [comment]
`yarn dev`

**Comment by jcalfee** [comment]
Is it meant to crash every time a server file is saved?
