### ISSUE TITLE
Normal users cannot load images normally

### ISSUE THREAD

**Issue by miocoo** [Requarks/wiki#2505]
**Question**
Normal users cannot load images normally

**Host Info (please complete the following information):**
OS: centos7, Docker
Wiki.js version: 2.5.144
Database engine: postgresq 12

Using the administrator to edit, the picture display is normal：
![image](https://user-images.githubusercontent.com/13830794/94355860-5ed70900-00ba-11eb-86b7-d9cc819be61a.png)

![image](https://user-images.githubusercontent.com/13830794/94354534-8b852380-00ae-11eb-8b10-5d3594bbfc5a.png)

However, after logging in with other users, the images cannot be displayed normally，the group to which the user belongs has been granted read permission：
![image](https://user-images.githubusercontent.com/13830794/94354499-35b07b80-00ae-11eb-84c2-2608114864f6.png)

**Comment by NGPixel** [comment]
But were read:assets permissions added to the group for the path where the asset is, not just the page?

If you upload an image to /some/path/image.jpg, then the group must have `read:assets` permission to the path `/some/path` as well.

**Comment by shegren** [comment]
Noticed this behavior when permissions (`read:pages` and `read:assets` in my case) are provided via `Tag Matches...`. With paths works fine, didn't test on regex though.
