### ISSUE TITLE
DB Connection - mariaDB

### ISSUE THREAD

**Issue by christhirst** [Requarks/wiki#2508]
**Describe the bug**
Can't connect to db-Database with version 2.5:latest. 2.3 and 2.4 works.
I set up wiki.js with 2.3 and wanted to update to 2.5 but it didn't connect to the database.
Both are running in a container with Podman.
I updated to 2.4 now and that works perfectly. So it has to be a bug in 2.5

but get the same environment file. So nothing is different except the versions.

**To Reproduce**
doesn't work:
podman run -d --name wiki --rm -p 8080:3000 --env-file .env.wikijs docker.io/requarks/wiki:2.5
works:
podman run -d --name wiki --rm -p 8080:3000 --env-file .env.wikijs docker.io/requarks/wiki:2.4
podman run -d --name wiki --rm -p 8080:3000 --env-file .env.wikijs docker.io/requarks/wiki:2.3

**Behavior**
2.5:
info: Connecting to database...
error: Database Connection Error: ENOTFOUND undefined:undefined
warn: Will retry in 3 seconds... [Attempt 1 of 10]
info: Connecting to database...
error: Database Connection Error: ENOTFOUND undefined:undefined

**Expected behavior**
2.4:
info: Connecting to database...
info: Database Connection Successful [ OK ]

**Additional context**
podman version 1.6.4
Centos8.2

**Comment by Smankusors** [comment]
what is your contents of ".env.wikijs" file?

**Comment by christhirst** [comment]
DB_TYPE=mariadb
DB_HOST="DB_HOST"
DB_PORT="3306"
DB_USER="wikijs"
DB_PASS="DB_PASS"
DB_NAME="DB_NAME"

**Comment by Smankusors** [comment]
hmm do you fill DB_HOST with IP address or host name?

**Comment by christhirst** [comment]
IP.

**Comment by NGPixel** [comment]
All builds are tested against all supported database engines and they all succeeded. You're the only one that reported an issue with mariadb.

`ENOTFOUND` means the driver can't find the hostname. This is a low level error from the DB driver and unrelated to Wiki.js itself. I suggest investigating whether the wiki container has proper access to the DB.

I was able to connect just fine using this basic example:
```
docker run -d --name mariadb -p 3306:3306 -e MYSQL_ROOT_PASSWORD=123456 -e MYSQL_DATABASE=wiki -e MYSQL_USER=wiki -e MYSQL_PASSWORD=123456 mariadb

docker run -d --name wiki -e DB_TYPE=mariadb -e DB_HOST=172.17.0.1 -e DB_NAME=wiki -e DB_USER=wiki -e DB_PASS=123456 -e DB_PORT=3306 -p 3000:3000 requarks/wiki:2.5
```

**Comment by christhirst** [comment]
Alright found it out.
For some reason it doesn't work with the quotation marks. Without the quotation marks it works now.
Sry for the inconvenience.
