### ISSUE TITLE
Application merging

### ISSUE THREAD

**Issue by boytoycommunity** [Requarks/wiki#2509]
**Question**
Am I able to merge Wiki.js with my current application or does it have to be a standalone application?

**Host Info (please complete the following information):**
OS: Heroku
Wiki.js version: [e.g. 2.0.1]
Database engine: [e.g. postgres 9.7, mysql 5.7]

**Comment by NGPixel** [comment]
Standalone.

Is it technically possible? Yes but so complex I don't see how it would be worth the effort.
