### ISSUE TITLE
Unexpected Error Occurred when using Azure Cognitive Search

### ISSUE THREAD

**Issue by Saldash** [Requarks/wiki#2513]
**Describe the bug**
I have setup Azure Search and rebuilt the search indexes as documented. Checking the index directly in the Azure portal confirms that the documents are present and searchable. Searching through the Wiki UI fails to return any results and instead the error message `Unexpected error occurred` is displayed momentarily.

**To Reproduce**
1. Configure Azure Search both on the Azure Portal and within Wiki as documented
2. Rebuild the search indexes to populate the azure document store & confirm searchable within the portal
3. Within the UI of Wiki, attempt to search for any term.
4. No results are displayed, the error message `An unexpected error occurred.` is displayed.

**Expected behavior**
Expected the Wiki UI to return a list of search results relevant to the search term.

**Screenshots**
https://i.ibb.co/Y71K5d4/Screenshot-2020-09-29-at-00-40-58.png

The error produced by the graphql endpoint in Wiki;
`[{"errors":[{"message":"Cannot read property 'results' of undefined","locations":[{"line":3,"column":5}],"path":["pages","search"],"extensions":{"code":"INTERNAL_SERVER_ERROR"}}],"data":{"pages":null}}]`

**Host Info (please complete the following information):**
 - OS: [unRaid, Docker]
 - Wiki.js version: [2.5.144]
 - Database engine: [SQLite]

The following is repeated in the logger for my container;
```
2020-09-28T23:39:18.829Z [MASTER] [33mwarn[39m: Unknown scoring profile 'fieldWeights'.
Parameter name: scoringProfile
2020-09-28T23:45:01.220Z [MASTER] [33mwarn[39m: Search Engine Error:

2020-09-28T23:45:01.220Z [MASTER] [33mwarn[39m: Unknown scoring profile 'fieldWeights'.
Parameter name: scoringProfile
2020-09-28T23:45:07.391Z [MASTER] [33mwarn[39m: Search Engine Error:

2020-09-28T23:45:07.391Z [MASTER] [33mwarn[39m: Unknown scoring profile 'fieldWeights'.
Parameter name: scoringProfile
2020-09-28T23:47:27.952Z [MASTER] [33mwarn[39m: Search Engine Error:

2020-09-28T23:47:27.953Z [MASTER] [33mwarn[39m: Unknown scoring profile 'fieldWeights'.
Parameter name: scoringProfile
2020-09-28T23:47:58.203Z [MASTER] [33mwarn[39m: Search Engine Error:
```

**Comment by Saldash** [comment]
I've resolved this myself through trial and error.
Your documentation on [setting up an Azure Search instance](https://docs.requarks.io/en/search/azure) lacks any information on what fields to specify or that a search profile must be configured to prevent my error above - I've had to dig through your source code to find it in the azure search module.

Please can you update your documentation as I've had several issues trying to get WikiJS to work that I've had to guess the issue / fix that could have easily been included in the documentation.

**Comment by NGPixel** [comment]
You shouldn't have to configure any search profile or fields. This is supposed to be done automatically when initializing the search module, which is why there's no such info in the documentation.

**Comment by Saldash** [comment]
It would be useful then to include in the documentation, a side note as to what Azure Search configuration should be user entered when creating a new instance and what is expected to be automatically generated by Wiki.

Documentation in general appears to be very sparse - see my open issue #2512 about not being able to connect our custom OAuth provider, which after some random troubleshooting is still an ongoing problem.
