### ISSUE TITLE
Blockquotes in Visual Editor

### ISSUE THREAD

**Issue by ethxrnity** [Requarks/wiki#2517]
**Question**
Can i make a warning blockquote in Visual Editor and if so, how?

**Host Info (please complete the following information):**
OS: [Latest Ubuntu]
Wiki.js version: [2.5.144]
Database engine: [mysql]

**Comment by ethxrnity** [comment]
Or can i at least somehow rewrite page written with Visual Editor to MarkDown?

**Comment by NGPixel** [comment]
Blockquotes variations are not yet available in the Visual Editor. Use Markdown instead.

It's not possible to convert an existing page from VisualEditor to Markdown yet. You need to delete it and create a new one.
