### ISSUE TITLE
Impossibility to create an administrator account with an arbitrary address

### ISSUE THREAD

**Issue by Aphr0di** [Requarks/wiki#2519]
Created a wiki on my server. Created an administrator account with an address not @gmail.com and after that does not allow it to the server during authorization.

Error: "Invalid email / username or password."

Login and password are identical when creating...

 - OS: Ubuntu 20.04 LTS
 - Wiki.js version: Wiki.js 2.5.144
 - Database engine: postgres

**Comment by NGPixel** [comment]
You can use any email address during setup (even if it doesn't exist), as long as it's a VALID email format.
