### ISSUE TITLE
Change editor for page irespective of editor used to create it

### ISSUE THREAD

**Issue by deathsfaction** [Requarks/wiki#2520]
**Question**
Is it possible to edit a page using the Rich Text editor when the page was *created* using raw HTML?
We'd be looking to move from an existing wiki setup to Wiki.js and want to copy and paste some content but need to be able to 'choose' the editor when it comes editing pages/content that has been copied over. Is this possible?

**Host Info (please complete the following information):**
OS: CentOS 8
Wiki.js version: 2.5.144
Database engine: MariaDB (will be moving to postgres post evaluation)

**Comment by Maxzor** [comment]
https://wiki.js.org/feedback/p/switching-from-an-editor-to-another-on-an-existing-page

As a workaround for now, you should be able with direct access to postgresql to make an in-place update in the page table, and change `editorKey`, `content`, `render`.

**Comment by deathsfaction** [comment]
Thanks - i saw that post about an hour after I posted my question. Hopefully it gets some traction soon!

**Comment by andybond006** [comment]
I believe a PR was already submitted that would allow this, though it hasn't been reviewed yet: #2190
