### ISSUE TITLE
Default timezone

### ISSUE THREAD

**Issue by JJ1LFC** [Requarks/wiki#2523]
**Question**
How can I change default timezone for new users?
It's fixed to be `America/New_York`, but most of our users are living in Japan, so I'm asking every users to change their timezone manually.

**Host Info (please complete the following information):**
OS: Ubuntu 18.04, Docker
Wiki.js version: 2.5.144
Database engine: postgres 11.9

**Comment by lodi-g** [comment]
Maybe it can be set as a config or env variable (name?) and then used in the DB migration? 
I can probably do a PR if you agree with the implementation.

**Comment by JJ1LFC** [comment]
What do you mean "config"?
I think users (administrators) should be able to change that setting from administration web GUI.

**Comment by lodi-g** [comment]
Yeah it seems legit indeed. If @NGPixel agrees I can do a PR.

**Comment by mbotmcc** [comment]
if it speeds things up, env var would be good, an option in the web UI would be better but w/e is quicker to implement I'd say. It's not like this will be changed post deployment

**Comment by windsIT** [comment]
@JJ1LFC  We have the same Question.
Temporary solution: Modify the default value of `timezone` field in `users` table .
`ALTER TABLE users ALTER COLUMN timezone SET DEFAULT 'Asia/Shanghai'::character varying;`

**Comment by windsIT** [comment]
@JJ1LFC  We have the same Question.
Temporary solution: Modify the default value of `timezone` field in `users` table .
```sql
ALTER TABLE users ALTER COLUMN timezone SET DEFAULT 'Asia/Shanghai'::character varying;
```

**Comment by NGPixel** [comment]
Added in 3.0.

**Comment by PinguDEV-original** [comment]
How can I change the timezone? I can't find any documentation

**Comment by greenbigfrog** [comment]
Where was this added?
Editing a users timezone is possible after they've been created, but I can't find the option to define a default.

**Comment by q-wertz** [comment]
> Where was this added?
> Editing a users timezone is possible after they've been created, but I can't find the option to define a default.

Latest stable version is `2.5.314`. According to the comment of the author, this was added to 3.0. So if you cannot find it, it was most probably not backported and you need to wait for 3.0

**Comment by greenbigfrog** [comment]
Oh, right. My bad.
Since the comment was from 2021, I kind of had assumed it was in a released version by now.
Thanks 👍🏻
