### ISSUE TITLE
administrator account password not working

### ISSUE THREAD

**Issue by peterchi2** [Requarks/wiki#2532]
**Question**
I installed Wiki JS and created an administrator account with a random password generator. After installation, the password would not work. I went into the Postgresql DB and changed the user's password in the "password" column with a new Bcrypt formatted value, however that new password still does not work (found manually changing administrator password here: https://docs.requarks.io/troubleshooting)

Am I missing something? I do see the administrator user in my DB table called "users" and the Bcrypt value matches the string (according to https://bcrypt-generator.com/)

Thanks

**Host Info (please complete the following information):**
OS: Docker
Wiki.js version: latest
Database engine: Postgres 12.3

**Comment by AmeliaMesdag** [comment]
I just set up WikiJS and encountered the same issues with sqlite3. There is an issue with case-sensitivity and local email accounts. Try using an Administrator email with all lowercase letters which worked for me.

**Comment by peterchi2** [comment]
That did it!

Thanks!
