### ISSUE TITLE
Discord authentication and user group

### ISSUE THREAD

**Issue by madhushankarox** [Requarks/wiki#2534]
Is there a way to authenticate with discord and add discord premium users to a specific group while authenticating without editing user manually?

**Comment by Maxzor** [comment]
Would be nice to add channel id on top of serverid, if this is feasible.

**Comment by Smankusors** [comment]
I think this is a feature request. There's existing one [here](https://wiki.js.org/feedback/p/sync-users-groups-with-discord-groups), you can vote that instead

**Comment by NGPixel** [comment]
Follow thread linked above ^^

**Comment by Maxzor** [comment]
The feature request was to be able to categorize users inside on server.
This might not be the place, but the request is not adressed.
