### ISSUE TITLE
non check telemetry config for install

### ISSUE THREAD

**Issue by yasokada-lc** [Requarks/wiki#2535]
Hi I have a question.

server setup.js

L354, for example, checks the telemetry config. 

But when an error occurs, such as L371 and L393, no checks are performed.
This does not appear to match the agreement at INSTALL time.

Is okay?

**Comment by NGPixel** [comment]
A check is performed before sending the error in:
https://github.com/Requarks/wiki/blob/31a18c8a67ef68ba0221fa57d79965c1ad478289/server/core/telemetry.js#L24-L33

The telemetry.isEnabled config is false by default, hence it will not send anything until it is enabled by the user.
