### ISSUE TITLE
Documentation lists hotfix 3, 4 and 5 as 3

### ISSUE THREAD

**Issue by djagoo** [Requarks/wiki#2538]
https://docs.requarks.io/releases lists hotfixes 3, 4 and 5 as 3,3 and 3.

https://github.com/Requarks/wiki-docs/blame/master/releases.md#L49
https://github.com/Requarks/wiki-docs/blame/master/releases.md#L50

Is there a better way to report documentation errors or contribute to documentation?

**Comment by NGPixel** [comment]
Fixed thanks
