### ISSUE TITLE
Advanced footer?

### ISSUE THREAD

**Issue by Wani4ka** [Requarks/wiki#2546]
**Question**
I want to add a link, like `Powered by <a href="...">Wiki.js</a>`, to a footer. But, when I try to do this, HTML tags aren't applied. Is there a way of doing this?

![](https://i.imgur.com/bHPOMWU.png)

**Host Info:**
OS: Ubuntu 16.04
Wiki.js version: 2.5.159
Database engine: mysql 5.7.31

**Comment by NGPixel** [comment]
No.

Only way would be to edit the source files and compile a new version with the modified footer.

**Comment by YerikYuan** [comment]
> 
Hi, NG.
Same needs here.
Are there more detailed tutorials for the edition, for example, which file should be edited, and how to re-compile?

**Comment by NGPixel** [comment]
@YerikYuan https://github.com/Requarks/wiki/blob/dev/client/themes/default/components/nav-footer.vue
