### ISSUE TITLE
Issue with some special words.

### ISSUE THREAD

**Issue by robertbur** [Requarks/wiki#2548]
Hello @everyone, 

I found this bug after a lot of investigation, looking at the previous issues I didn't found anything. 

**Describe the bug**
When I type, "select" or "()" the systems all the time gives me an error (Json). Example: If I write: "I select this car", this doesn't work and I need to change to "I choose this car".

**Host Info (please complete the following information):**
 - OS: [Docker]
 - Wiki.js version: [2.5.199]
 - Database engine: [MariaDB]

Thanks in advance.

**Comment by Jhobean** [comment]
Where you type this text?

**Comment by robertbur** [comment]
Hi @Jhobean,

Yesterday we did a change at the Nginx + Cloudflare, and we are testing now. Looks like this works, but I need to test it more. 

Kind regards
