### ISSUE TITLE
Unable to upload huge file

### ISSUE THREAD

**Issue by lyandr** [Requarks/wiki#2556]
**Question**
Hello I have installed wikijs on Openshift. It is working well but i had trouble to upload huge files (200Mo).
In the interface the uplaod goes to 100% and after i have a popup message error. And i have the following errors in logs:

```
2020-10-09T15:36:07.648Z [MASTER] warn: update "assetData" set "data" = $1 where "id" = $2 - Connection terminated unexpectedly
--
  | Connection Error: Connection ended unexpectedly
  | 2020-10-09T15:36:08.230Z [MASTER] warn: the database system is in recovery mode
  | 2020-10-09T15:36:08.230Z [MASTER] warn: the database system is in recovery mode
```

I have configured max uplaod size to 524288000 and Max file per uplaod to 5 but in the uploadd interface i can see the default configuration: Max 10 files, 5 MB each.

Do i have to restart the openshift pod in order to be taken into account? or is it something else?

**Host Info (please complete the following information):**
OS: Wikijs Docker image
Wiki.js version: 2.5.144
Database engine:  postgres 9.6.10

**Comment by NGPixel** [comment]
Your database is simply refusing such big payload.

It's usually not a good idea to store such big files in the wiki directly. Consider using a proper storage location, like AWS S3 or Azure Blob Storage.

**Comment by lyandr** [comment]
Hello, thanks for the answer but i configured the local file system so i don't understand why you talked about the database.
I have also configured a generic S3 storage but it is always the same:
After uplaod reach 100% i have a popup error message: Network Error: Response not successful: Received status code 500

and in the logs this the same messages as my previous message.

**Comment by NGPixel** [comment]
All uploads are saved in the database. The S3 storage is irrelevant to your issue and is only used as **backup**, not the primary storage source.

**Comment by lyandr** [comment]
So how is it possible to solve my problem? Or does it means that wikijs don't allow such big files (200Mo for a video for exemple) and i have to store it somewhere else and just put links?

**Comment by lyandr** [comment]
any idea or advice?

**Comment by NGPixel** [comment]
Like I said, uploading big video files to the database is not a good idea. Use a more appropriate storage platform instead. The upload in wiki.js is meant for documents and images.

**Comment by lyandr** [comment]
ok thanks for the advice
