### ISSUE TITLE
Cant edit page metadata after saving

### ISSUE THREAD

**Issue by mpr555** [Requarks/wiki#2557]
**Describe the bug**
I would like to go back and change the description of the page (metadata). But I cannot ses a button or option for this.

As you can see under the edit page, there is not metadata option.

You can always return to the Page Metadata dialogue later by clicking the Page button, located in the upper-right corner of the page.

This is located under User Guide - Basics

**To Reproduce**
Steps to reproduce the behaviour:
I have attached three screenshots to show you what I can see and I can't see the option to change metadata

I have tested this in Chrome and Brave

**Expected behaviour**

**Screenshots**
![bug01](https://user-images.githubusercontent.com/7525273/95603929-dc9dfb80-0a4e-11eb-8d56-0c366cec6440.PNG)
![bug02](https://user-images.githubusercontent.com/7525273/95604049-06efb900-0a4f-11eb-8238-d3817dc4824f.PNG)
![bug03](https://user-images.githubusercontent.com/7525273/95604125-24248780-0a4f-11eb-89d8-b36d543d0b63.PNG)

**Host Info (please complete the following information):**
-Running in Docker version: 19.03.5
-Wiki JS version: 2.5.159

Any help would be great, as this looks like an epic piece of software.

**Comment by NGPixel** [comment]
![image](https://user-images.githubusercontent.com/15522395/95611648-1d3a4c80-0a30-11eb-8df3-7baf67d84619.png)

**Comment by mpr555** [comment]
Its been a long day!!!!!!!  How could I missed that?  Thank you very much for the quick response!
