### ISSUE TITLE
How to insert a fixed item in the menu

### ISSUE THREAD

**Issue by brunoseco** [Requarks/wiki#256]
### How to insert a fixed item in the menu

Is it possible to fix a url or choose some article generated by the wiki in the menu?

Thanks

**Comment by NGPixel** [comment]
You can manually edit the sidebar links by editing file https://github.com/Requarks/wiki/blob/af80404ee70948e94aa7777ab0e037fa7d33fcc5/server/views/pages/view.pug#L44

Be aware that any upgrade would overwrite that file!

Adding links will be officially supported in 2.0
