### ISSUE TITLE
Wiki.js doesn't support custom git ssh port?

### ISSUE THREAD

**Issue by lukonin** [Requarks/wiki#2560]
I'm setting up a Repository URI as: git@domain:8722/username/repo.git
But in the tshark dump I see:

172.18.0.3 → 192.168.25.105 TCP 68 40250 → 22

172.18.0.3 is IP of Wiki.js in Docker.
192.168.25.105 is IP of Docker server.

**Steps to reproduce the behavior:**
1. Go to 'Settings' → 'Storage' → 'Git'
2. Set the 'Repository URI' with a custom SSH port.
3. Run tshark on Docker server.
4. See a default SSH port instead of given in 'Repository URI'.

**Host Info:**
 - OS: Debian 10.6, Docker
 - Wiki.js version: 2.5.159
 - Database engine: postgres 11.9

**Comment by derdeagle** [comment]
I have the same problem and with some manual adjustments it is working now. **Explicitly not a fix** but maybe interesting to get rid of a blocker.

1. Login as the node-user `docker exec -it <container> bash`
2. Switch to the Git directory (for me it was `cd /wiki/data/repo`)
3. Create a file there and push it to the repo (to initialize everything)
3.1 `echo "testfile" > test`
3.2 `git add test`
3.3 `git commit -m "init"`
3.4 `git push origin <branch>` (the branch in my case was **master**)
3.5 `git rm test`
3.6 `git commit -m "cleanup init"
3.7 `git push origin <branch>`

After that it was working for me.
What is now in the `.git/config` that wasn't there before the manual changes is

```ini
[branch "master"]
	remote = origin
	merge = refs/heads/master
```
