### ISSUE TITLE
Could not renew Let's Encrypt SSL cert so disabled SSL redirection as per Wiki. Now nothing works.

### ISSUE THREAD

**Issue by ilium007** [Requarks/wiki#2569]
**Question**
I could not renew Let's Encrypt SSL cert so I disabled SSL redirection as per Wiki. Now nothing works. I get the error, "Oops, something went wrong... Unknown authentication strategy "jwt""

**Host Info (please complete the following information):**
OS: Docker on Digital Ocean
Wiki.js version: 2.5.159
Database engine: postgres 11

```
root@wikijs-ubuntu-sgp1-01:~# docker exec db psql -U wiki -d wiki -c "DELETE FROM settings WHERE key = 'server';"
DELETE 1
root@wikijs-ubuntu-sgp1-01:~# docker restart wiki
wiki
root@wikijs-ubuntu-sgp1-01:~#
```

<img width="586" alt="image" src="https://user-images.githubusercontent.com/732766/95692921-06386c00-0c75-11eb-92c8-5cf1ddbd3563.png">

**Comment by Smankusors** [comment]
Seems related to #1822
