### ISSUE TITLE
New pages are not shown or searchable

### ISSUE THREAD

**Issue by patriciunista** [Requarks/wiki#258]
### Actual behavior
When I create a new page, it does not appear in the nav bar and in the "All Pages" link nor while I try to search it in the search bar, but the page is created properly and I can access it by url. My Wiki is private, only accessible by logged in users.

If I run `pm2 logs wiki` that's the error I see in the logs.

```
0|wiki     | 2017-10-05T08:26:13.659Z - error: [AGENT]  MongoError: exception: Mod on _id not allowed
0|wiki     |     at Function.MongoError.create (/var/www/node_modules/mongodb-core/lib/error.js:31:11)
0|wiki     |     at /var/www/node_modules/mongodb-core/lib/connection/pool.js:497:72
0|wiki     |     at authenticateStragglers (/var/www/node_modules/mongodb-core/lib/connection/pool.js:443:16)
0|wiki     |     at Connection.messageHandler (/var/www/node_modules/mongodb-core/lib/connection/pool.js:477:5)
0|wiki     |     at Socket.<anonymous> (/var/www/node_modules/mongodb-core/lib/connection/connection.js:331:22)
0|wiki     |     at emitOne (events.js:115:13)
0|wiki     |     at Socket.emit (events.js:210:7)
0|wiki     |     at addChunk (_stream_readable.js:266:12)
0|wiki     |     at readableAddChunk (_stream_readable.js:253:11)
0|wiki     |     at Socket.Readable.push (_stream_readable.js:211:10)
0|wiki     |     at TCP.onread (net.js:587:20)
```

I'm running Wiki.js inside a Docker container.

### Expected behavior
I expected to see the page in all these three sections.

**Comment by NGPixel** [comment]
Does restarting your wiki (the docker container in this case) fixes the issue?

**Comment by patriciunista** [comment]
No, the pages are not shown even if I restart, and I got the same error from Mongo.

MongoDB version: 2.4.10
Git version: 2.14.2
Node.js version: 8.6.0

**Comment by Zajozor** [comment]
Install mongoDB v3.4, helped me fix this.
example tutorial ~ https://www.theo-andreou.org/?p=1744

**Comment by patriciunista** [comment]
I installed MongoDB v3.4 and solved my problem. The pages are now searchable and I can see them in the "All Pages" section. Thank you @Zajozor!

**Comment by NGPixel** [comment]
FYI, the documentation clearly states MongoDB 3.2 or later is required.

https://docs.requarks.io/wiki/prerequisites
