### ISSUE TITLE
[Markdown] Inconsistent parsing between tables in the preview VS generated page

### ISSUE THREAD

**Issue by juliendms** [Requarks/wiki#2580]
**Describe the bug**
The preview page does support the syntax to merge cells of a table vertically using the syntax: `^^`

**To Reproduce**
1. Open a new page
2. Enter the following markdown
```md
| A | B |
|-|-|
| Cells merged vertically | but not this one |
|^^| proof is here ! |
```
3. The preview merges cells A2 and A3.
4. Save the page and browse it
5. The cell A3 contains `^^`

**Expected behavior**
The generated page should have the cells A2 and A3 merged.

**Screenshots**
N/A

**Host Info (please complete the following information):**
 - Wiki.js version: Last release

**Additional context**
N/A

**Comment by chris-hs** [comment]
The provided markdown works properly on my instance of wiki.js, but I have found a way to replicate the behavior you describe. Can you make sure you have **Rowspan** turned on in the the rendering settings for the **MultiMarkdown Table** module settings?

If I disable **Rowspan**, I get the behavior you described. Apparently the preview does not respect the module configuration settings for some reason.

**Comment by juliendms** [comment]
Thanks a lot, as it was working in the Preview I forgot to check the issue. Issue closed !
