### ISSUE TITLE
Logo and login screen bg not visible if assets are blocked for guests

### ISSUE THREAD

**Issue by JussiKivimaki** [Requarks/wiki#2581]
**Describe the bug**
If I set so that all content (and assets) require login (guest user group have no access reading pages and assets), it naturally makes custom login bg and site logo unavailable (403 forbidden) since they are assets. 

**To Reproduce**
1. Set custom logo and login bg from settings
2. Deny all access for guests
3. Logout / visit as logged out
4. See the page missing login background and logo

**Expected behavior**
Should skip access check for those two assets. Another subdir for "public" assets?

**Host Info (please complete the following information):**
 - OS: Windows 10
 - Wiki.js version: 2.5.159
 - Database engine: postgres 12

**Comment by chris-hs** [comment]
According to the [documentation](https://docs.requarks.io/auth#login-background-image), this is how the feature is supposed to behave.

The recommended setup is to create a new folder, (e.g. `/assets-public`) and create a a new page rule for the `Guest` group that gives `read:assets` permission. Then you can upload your background image and custom logos to that folder, and guests will be able to see them on the login screen.
