### ISSUE TITLE
Wiki family/farm support? 

### ISSUE THREAD

**Issue by GodBleak** [Requarks/wiki#2583]
**Question**
Is it possible to set up a [wiki family](https://m.mediawiki.org/wiki/Manual:Wiki_family), like with mediawiki?

**Comment by NGPixel** [comment]
Not yet, but it's coming in a future release.

**Comment by GodBleak** [comment]
> Not yet, but it's coming in a future release.

Hate to ask, but do you have a rough ball park on when we can expect this? 

I'm designing my site around this feature, and am trying to decide if I want to wait for this feature or brush up on PHP and use mediawiki in the interim.
