### ISSUE TITLE
WYSIWYG editor inconsistent with actual page rendering for markdown

### ISSUE THREAD

**Issue by AuspeXeu** [Requarks/wiki#2584]
**To Reproduce**
1. Go to editor and use underscores to make text italic
2. See text being bold in the preview
3. See text being italic once page is saved

**Expected behavior**
Render markdown consistently

**Screenshots**
![image](https://user-images.githubusercontent.com/2115696/96085197-c1a11080-0ec0-11eb-8b95-29b561d4b223.png)
![image](https://user-images.githubusercontent.com/2115696/96085207-c4036a80-0ec0-11eb-90aa-fe074140b654.png)

**Host Info:**
 - Wiki.js version: 2.5.159

**Additional context**

**Comment by chris-hs** [comment]
It is a known issue that the preview panel does not use the server rendering settings. PR #2219 attempts to address this issue for a number of rendering modules.
