### ISSUE TITLE
Why cas option grey?

### ISSUE THREAD

**Issue by liqt91** [Requarks/wiki#2589]
**Question**
I installed  Wiki.js 2.5.159 on centos7.5 with mysql and chinese configed.
but why cas option grey? I only have cas to do the auth  :(

**Host Info (please complete the following information):**
OS: centos7.5
Wiki.js version: 2.5.159
Database engine: mysql 8.0.11

![image](https://user-images.githubusercontent.com/13084800/96225595-e7fba480-0fc3-11eb-90c4-1f6210aa5008.png)

**Comment by chris-hs** [comment]
Usually features that are not implemented yet are disabled. The CAS Module is on the [official roadmap](https://docs.requarks.io/releases/roadmap) for 3.x.

**Comment by liqt91** [comment]
> Usually features that are not implemented yet are disabled. The CAS Module is on the [official roadmap](https://docs.requarks.io/releases/roadmap) for 3.x.

thx, I wait
