### ISSUE TITLE
Can't insert image (JSON error)

### ISSUE THREAD

**Issue by IIPoliII** [Requarks/wiki#2592]
I have the latest Wiki.JS version and I am uploading my content to a private github repo.
It's running on Ubuntu 18.04 LTS and I am using the node version.

When I try to add an image to one of my page it instantaly returns me the error "Network error: JSON.parse: unexpected character at line 1 column 1 of the JSON data" I was able 1 month ago to use the images with ease but now I can't use them (also with images that were already there).
I always get this error and don't see anything in the node server is there some kind of log somewhere where I could see the error?
Thanks for your help

(Also my page is protected by CF but it shouldn't be an issue because it's when I click save and it needs to render the page)

**Comment by NGPixel** [comment]
Whiteliste your IP in cloudflare and try again.

**Comment by IIPoliII** [comment]
Same thing happens sadly :/

**Comment by IIPoliII** [comment]
Looks like sometimes it could take a lot of time to get applied
