### ISSUE TITLE
SSL not working

### ISSUE THREAD

**Issue by damiantoczek** [Requarks/wiki#2595]
My SSL isnt working, I SSH to my server but there is not NGINX running so I have no idea how WikiJS works and how SSL should be working on it.

OS: Ubuntu 18.04, Docker (digital ocean)
Wiki.js version: 2.5.159
Database engine: postgreSQL 11.8

**Comment by NGPixel** [comment]
Have you [read the docs](https://docs.requarks.io/install/digitalocean#automatic-https-with-lets-encrypt)?

There's no nginx in that image.
