### ISSUE TITLE
Custom Subdomain Assistance

### ISSUE THREAD

**Issue by DylsterDev** [Requarks/wiki#2596]
**Question**
Describe in details what you are trying to achieve and where do you need guidance.

**Host Info (please complete the following information):**
OS: Ubuntu
Wiki.js version: 2.5.159
Database engine: Postgres

Hiya,

I am trying to get my wiki onto my sub domain. It is currently running on my VPS and is only accessible via IP:port and after hours trying to get it to work on my sub domain I have had no luck. It hasn't produced any errors nor shown any obvious problems with the code. The config.yml file is also setup with the sub domain.

**Comment by Frankstar** [comment]
`yoursubdomain.example.com` is redirecting to the same IP as `example.com` ?
On which port is your node instance running?
is there a webserver/proxy infront of the node-server?

it sound like an DNS issue and not an wikijs issue.
