### ISSUE TITLE
Can't access Wiki.js when logged in to company VPN

### ISSUE THREAD

**Issue by jord8on** [Requarks/wiki#2597]
**Describe the bug**
When employees, who are connected to our company VPN, try to access our instance of Wiki.js, they encounter a 404 error or "Site Cannot Be Reached" error.

Is this a bug? Or expected behavior? Is there something I can tweak on the Wiki.js side that will allow users to access our wiki? Or is this something that needs to be addressed/adjusted on the VPN side? If so, any suggestions?

**Additional context**
We use GSuite at my company so we are using the Google Authentication option, and have turned off all the other login options.

**To Reproduce**
1. Go to "https://docs.artemishealth.com'
2. See error

Note: If a person is not logged into our company VPN, then they do not get an error and can use their Google OAuth account to provision a new account or to log in.

**Expected behavior**
Users should be able to be connected to our VPN and still access the Wiki. 

**Screenshots**
After someone who is logged into our company VPN, tries to login to our wiki.js instance, they get this screen:

![image (11)](https://user-images.githubusercontent.com/20749549/96507834-f988ba80-1216-11eb-9212-d3929eb3eca1.png)

**Host Info:**

![image](https://user-images.githubusercontent.com/20749549/96506560-115f3f00-1215-11eb-907d-10119bcdb2ca.png)

**Comment by NGPixel** [comment]
That's an issue with your VPN... not Wiki.js.

**Comment by jord8on** [comment]
Thanks for the insight @NGPixel... super helpful!
