### ISSUE TITLE
Rendering issues on code blocks and mermaid diagrams in 2.5.159

### ISSUE THREAD

**Issue by merlock-lk** [Requarks/wiki#2602]
**Describe the bug**
After updating to version 2.5.159, code blocks within tabsets and mermaid diagrams no longer render correctly:
- code blocks have a very odd styling applied to them which makes the text blurry and adds a light background
- mermaid diagrams no longer render but instead display as code blocks

**To Reproduce**
1. Go to any page with tabsets containing code blocks (the code block must be inside of a tab frame)
2. Make any change to the page anywhere (the change doesn't matter, the goal is to re-render the page after saving the change)
3. Hit save
4. Exit the edit mode and look at the code blocks in your tabset: they are now rendered incorrectly.

Note: while this describes how to make the issue appear on existing pages with tabsets, I highly suspect any new pages created with tabsets & code blocks will also have this issue (not verified).

**Expected behavior**
The code blocks and mermaid diagrams should render correctly

**Screenshots**
Unfortunately I downgraded my wikijs to version 2.5.144 for testing so I can no longer reproduce this issue for screenshots.

**Host Info (please complete the following information):**
 - OS: Ubuntu Server 19.10 (running in VirtualBox)
 - Wiki.js version: 2.5.159 (docker-compose)
 - Database engine: postgres:12.3-alpine

**Additional context**
I verified that this issue does not occur when I downgrade to version 2.5.144. In fact, the same steps that make the issue appear (i.e.: edit a page to re-render it) in 2.5.159 make the issue disappear in 2.5.144. Specifically:
- perform the steps to reproduce in version 2.5.159
- downgrade to 2.5.144
- open the page: observe that issue is still there.
- edit the page and save to re-render it: observe that the issue is now gone.

Inspecting the DOM in my browser indicates that the "correct" code blocks (i.e.: those rendered properly) have more css classes than those rendered incorrectly by the above steps (I do apologize, I should have noted down these differences at the time. Currently I can no longer reproduce this issue since I downgraded to 2.5.144).

This issue also seems to affect mermaid diagrams. I had copy-pasted an example diagram which was rendering correclty. As soon as I edited the page where it was located, the diagram disappeared and was replaced with a code block (I did not make any changes to/near the diagram itself). I can confirm that this issue does not occur in 2.5.144.

**Comment by JussiKivimaki** [comment]
I can reproduce this on 2.5.159. Code blocks inside tabset render incorrectly. Code blocks outside of tabsets on the same page render correctly. Inside tabsets code blocks are missing the `prismjs` classes and so the styling will be off:

```
<pre class="  language-none">
 <code class="language-  language-none">
 </code>
</pre>
```
![codeblock_2_5_159](https://user-images.githubusercontent.com/50416559/97972711-9b8ad400-1dcd-11eb-8e00-4b2e6abd9b70.png)

**Host info:**
OS: Linux / docker
Version: 2.5.159
DB: postgres 13.0

**Comment by JussiKivimaki** [comment]
Tested this on 2.5.170 and the problem is gone at least for the code blocks. Different OS tho (Windows).

**Comment by merlock-lk** [comment]
Thank you for the update. I can also confirm that both code blocks and mermaid diagrams render correctly in version 2.5.170.

**Comment by naseer** [comment]
I am on `2.5.197` and this happens all the time - even without tabsets - preview is okay, but when the page is saved, mermaid goes to codeblock mode
