### ISSUE TITLE
Unable to access uploaded plaintext asset

### ISSUE THREAD

**Issue by jtapsl** [Requarks/wiki#2603]
**Describe the bug**
When I upload a .txt file asset, I an unable to link to that asset

**To Reproduce**
1. Create a new page in the richtext editor.
2. Click on Insert Assets and upload a text file (extension .txt).
3. Choose the uploaded text asset and click Insert.
4. Save the page and attempt to follow the link.
5. There is an error "This page does not exist yet. Would you like to create it now?"

**Expected behavior**
I expect to be able to view or download the text file.

**Screenshots**
![assets_view](https://user-images.githubusercontent.com/42975697/96663237-4c00ce80-131e-11eb-9680-dcf2d5a68d99.PNG)
![textfile_asset_link](https://user-images.githubusercontent.com/42975697/96663244-502cec00-131e-11eb-9d10-1778468726be.PNG)

**Host Info (please complete the following information):**
 - OS: Red Hat 8.2
 - Wiki.js version: 2.5.159
 - Database engine: PostgreSQL 10.14

**Additional context**
I experience the same behavior with an asset subfolder or an asset uploaded at the root level.

**Comment by NGPixel** [comment]
Extensions .md, .html and .txt are reserved for pages. Either zip or change the extension of files to get them as downloads.

**Comment by Hallo5000** [comment]
For anyone looking into the same problem: A simple workaround is to just remove txt from the page extensions under Settings > General.
