### ISSUE TITLE
SSl Certificate Question

### ISSUE THREAD

**Issue by simongottschalk** [Requarks/wiki#2605]
I signed up on Amazon AWS to run WIKI.JS as a service (as per your documentation).
All is going well, except we cannot securely access the service using https.
 
What do I need to do to sort this out?

The site is
ec2-18-222-138-97.us-east-2.compute.amazonaws.com

Hope you can help ....

**Comment by Frankstar** [comment]
did you read [this?](https://docs.requarks.io/install/config)

**Comment by simongottschalk** [comment]
Hi Franz

 

Are you anything to do with WIKI.JS

The problem is that I am using it as a “service” on AWS.

So I do not have access to the underlying server (or if I do I haven’t found it yet).

 

Simon

**Comment by NGPixel** [comment]
Wiki.js on AWS is not run "as a service", it is merely an EC2 image with Wiki.js pre-installed. You're still running the server on your own account and have full access to it.

Access your server via SSH and follow the instructions as detailed [here](https://docs.requarks.io/install/aws#automatic-https-with-lets-encrypt).
