### ISSUE TITLE
sort articles by name  from A to Z

### ISSUE THREAD

**Issue by guimachadooo** [Requarks/wiki#2606]
Hello, a dumb question that I couldn't find the answer.

Look the attach, my articles are not running on sequence, 1, 2, 3.. 9, 10, 11..

how can I do that?

OS: [Windows 10, Docker]
Wiki.js version: [2.5.159]
Database engine: [mysql 5.7]
![menu](https://user-images.githubusercontent.com/54110006/96758483-37b7e280-13ad-11eb-8e8b-775c05b9b306.PNG)

**Comment by NGPixel** [comment]
Pages are sorted by alphanumeric order, not by "numeric" order.

A workaround would be to use left padding on the numbers, e.g.:

```
01. Painel - Dashboard
02. Cursos
03. Biblioteca
...
10. Planos de Assinatura
11. Cupom de Desconto
```
