### ISSUE TITLE
Links in Table of Contents not working

### ISSUE THREAD

**Issue by n-tanchev** [Requarks/wiki#2607]
**Describe the bug**
Clicking on a the links in the Table of Contents doesn't scroll down to the clicked heading, and produces the following error in the console:
```
TypeError: Target must be a Number/Selector/HTMLElement/VueComponent, received undefined instead.
    at M (app.js?1601761667:350)
    at Object.T (app.js?1601761667:350)
    at click (theme0.js?1601761667:2)
    at qt (app.js?1601761667:350)
    at a.n (app.js?1601761667:350)
    at qt (app.js?1601761667:350)
    at a.t.$emit (app.js?1601761667:350)
    at a.click (app.js?1601761667:350)
    at qt (app.js?1601761667:350)
    at HTMLDivElement.n (app.js?1601761667:350)
```

**To Reproduce**
1. Click on one of the links in the table of contents on any page

**Expected behavior**
The page to be scrolled down to the clicked link heading

**Host Info (please complete the following information):**
 - OS: Docker Container
 - Wiki.js version: 2.5.159
 - Database engine: postgres 11.7

**Additional context**
It seems there are no anchors generated, when inspecting the pages' html source

**Comment by NGPixel** [comment]
TOC links work just fine here: https://docs.requarks.io/releases

Are you using the markdown or visual editor?

**Comment by n-tanchev** [comment]
I'm using the markdown editor, and none of the headings in the page's content haven an id attribute, so I'm assuming that is the reason the scroll doesn't work.

**Comment by vkatsuba** [comment]
Hi All,

Have the same issue.
Used `MD` , add into page `[Links](#links)` and below `# Links` , save page and try click to the link Links in the page as resoult we ca see that the scrolling does not occur and in console we can see error:
```javascript
Uncaught Error: Target element "#links" not found.
    M https://wiki.tpip.net/_assets/js/app.js?1603683027:350
    T https://wiki.tpip.net/_assets/js/app.js?1603683027:350
    onclick https://wiki.tpip.net/_assets/js/theme0.js?1603683027:2
    mounted https://wiki.tpip.net/_assets/js/theme0.js?1603683027:2
    mounted https://wiki.tpip.net/_assets/js/theme0.js?1603683027:2
    ie https://wiki.tpip.net/_assets/js/app.js?1603683027:350
    Xt https://wiki.tpip.net/_assets/js/app.js?1603683027:350
```
OS: Linux
Browser: `Firefox 82.0.2`

Regards,
--V

**Comment by vkatsuba** [comment]
Hi All,

Have the same issue.
Used `MD` , add into page `[Links](#links)` and below `# Links` , save page and try click to the link Links in the page as result we ca see that the scrolling does not occur and in console we can see error:
```javascript
Uncaught Error: Target element "#links" not found.
    M https://some.page.net/_assets/js/app.js?1603683027:350
    T https://some.page.net/_assets/js/app.js?1603683027:350
    onclick https://some.page.net/_assets/js/theme0.js?1603683027:2
    mounted https://some.page.net/_assets/js/theme0.js?1603683027:2
    mounted https://some.page.net/_assets/js/theme0.js?1603683027:2
    ie https://some.page.net/_assets/js/app.js?1603683027:350
    Xt https://some.page.net/_assets/js/app.js?1603683027:350
```
OS: Linux
Browser: `Firefox 82.0.2`

Regards,
--V
