### ISSUE TITLE
Breadcrumbs folder link to a default page

### ISSUE THREAD

**Issue by changsijay** [Requarks/wiki#2608]
**Question**
if I have a page which link is `https://mywiki.com/en/cloud/aws/cli/index`
the breadcrumbs is `/cloud/aws/cli/index`

if I click the `cli` (folder) in the breadcrumbs, could it default link to `index` or `home` page?

I am confused if I click `cli` to ask me to create a page `/cloud/aws/cli`
then, there would be a `folder` and a `page` the same name?

**Host Info (please complete the following information):**
OS: Ubuntu 20.04, Docker
Wiki.js version: 2.5.159
Database engine: mysql 8.0.21

**Comment by NGPixel** [comment]
That's not how it works. You need to create a page at the path occupied by the folder. For example, if you have a page at `/cloud/aws/cli/something`, the index page for the parent `cli` folder would be at path `/cloud/aws/cli`.
