### ISSUE TITLE
Missing items from navigation

### ISSUE THREAD

**Issue by timeandtimeago** [Requarks/wiki#261]
### Actual behavior
Some times some or all items (pages and folders) will be missing form the navigation.
You can only find pages if you know their URL.
### Expected behavior
The pages should be listed under "all pages"

Is there any way to flush and rebuild (the button for it says coming soon) so taht the navigation will rebuild itself? I have already tried bouncing the server and restarting wiki.js and nginx.

<img width="825" alt="screen shot 2017-10-05 at 8 36 05 pm" src="https://user-images.githubusercontent.com/8980822/31259523-f755c6c4-aa0c-11e7-81c1-aeb9b5c7114c.png">

**Comment by NGPixel** [comment]
Check the logs for any error. If a page or folder is missing from the index, it usually means the parser crashed while processing the page contents.

**Comment by timeandtimeago** [comment]
It is quite possible that a parser crashed as the server experienced a memory leak on another app, causing it to require a reset. Is there any practical way to get the parser to "re-index" the pages after this kind of thing happens?

I can't provide logs as I deleted the wiki.js application and re-installed it to quickly solve the problem.

**Comment by NGPixel** [comment]
All pages are re-indexed upon start (or restart) of the app.

**Comment by Zajozor** [comment]
This happened to me, because i had outdated version of mongoDB. Installing latest (version > 3) helped me.
Sorry if not your case, but may help someone.
https://docs.mongodb.com/manual/tutorial/install-mongodb-on-debian/

**Comment by vnkmpf** [comment]
Hi,
I have the same problem.
I use WikiJS with Docker.

I zipped the whole directory and moved to another server.
So there is git repository, mongo files, cached JSON files.
This way everything works with other projects.

On the old server I had wiki 1.0.5 while on the one I have 1.0.12.
When I run wiki, it behaves as timeandtimeago describes. Navigation is empty. Also search results are empty. With direct URL I can access my pages though.

When I connect to the mongo container and list entries collection on the old server, I see all the pages. When I do the same on the new one, nothing is returned.

Can you please tell in short how does the re-indexation work? Like - does it fill DB from git repository?

**Comment by timeandtimeago** [comment]
I was only able to solve this by doing a clean instal of wikijs. Then ported all the data over.

**Comment by vnkmpf** [comment]
I tried mongodump and mongorestore. It worked, until docker container was restarted.
I think it's pretty admin-unfriendly to have to do a clean install.

**Comment by NGPixel** [comment]
Try disabling mathjax in your config.yml then restart Wiki.js.

**Comment by vnkmpf** [comment]
I have tried it before, I that comment in another issue.
What did work for me was to use different Dockerfile - actually the old one, and rewrite just few lines.
Seems like the problem was not really in 1.0.12 (as it works now), but I don't know.

**Comment by timeandtimeago** [comment]
I have found the cause for my case of this problem.
The root of my issue was that my web server was not configured to allow body requests over a couple mb - causing the git pushes from the wiki to fail. For what ever reason, the page indexing ceases to work when git commits start failing.

I discovered this while trying to manually commit the repo folder - and I got the following error. "RPC failed; HTTP 413 curl 22 The requested URL returned error: 413 Request Entity Too Large"

The fix is to configure your web server (in my case NGINX) to allow larger request bodies. [Configure NGINX to allow larger body](https://stackoverflow.com/questions/4947107/nginx-upload-client-max-body-size-issue)

Once I updated NGINX to allow larger HTTP requests body size (50m),
Restarted NGINX and WikiJs, and presto. Problem solved. 

Hope this helps anyone having this issue in the future.

**Comment by palmada** [comment]
Hi, I am getting this error as well. It shows fine when I start the app with `pm2 start server -n wiki`. But when I reboot the server, the menu disappears. `pm2 restart wiki `fixes it.

**Comment by taelfrinn** [comment]
> All pages are re-indexed upon start (or restart) of the app.

Can you point out where that is supposed to happen? As far as I can tell, there is a memory only search index that is only kept in ram, and only updated as each page is changed. I dont see where the index gets rebuilt on startup in the code. 

I would like to debug it, as mine is blank as expected after each restart.

**Comment by JLopeDeB** [comment]
Hi, I've been struggling with this issue for couple of days now. I've tried a lot of things, including reinstalling several times and configuring the Wiki with a new mongodb database. In our git repository we have several pages and directories, but the navigation bar only shows one or two pages each time (pretty much the same ones) on each restart. The pages are there, git syn is OK, if I navigate using the url of the page, it works. It's just that the navigation bar from the "all" pages doesn't show all pages and directories available. Log doesn't show errors either. Let me know if you need me to send to config info or logs. Thanks in advance for your help.

**Comment by timeandtimeago** [comment]
Unfortunately my organization was never able to permanently resolve this. 

It’s the primary reason we moved away from using this tool.

**Comment by Finezzio** [comment]
> ### Actual behavior
> Some times some or all items (pages and folders) will be missing form the navigation.
> You can only find pages if you know their URL.
> 
> ### Expected behavior
> The pages should be listed under "all pages"
> 
> Is there any way to flush and rebuild (the button for it says coming soon) so taht the navigation will rebuild itself? I have already tried bouncing the server and restarting wiki.js and nginx.
> 
> <img alt="screen shot 2017-10-05 at 8 36 05 pm" width="825" src="https://user-images.githubusercontent.com/8980822/31259523-f755c6c4-aa0c-11e7-81c1-aeb9b5c7114c.png">

I'm so sorry for writing in this place. Just finding solution how to edit navigation bar like you.
Can you help me ? mk@hrms.pl

Best Regards
Marek

**Comment by vitoravancini** [comment]
Was this ever solved? I'm trying version 2.5 and it is still happening
