### ISSUE TITLE
wiki.js has 4 second modal 'rendering' dialog per save

### ISSUE THREAD

**Issue by dirtminer** [Requarks/wiki#2611]
**Question**

Are there some configuration options I  can try to make this more usable ?

**Host Info (please complete the following information):**
OS:  Alpine Edge, running in user-space container 
Wiki.js version: 2.5.159
Database engine: postgresql-12.4-r1  
Node.JS version:  nodejs-12.19.0-r0   

** Example Render pass **

```
Loading configuration from /home/wikijs/wiki/config.yml... OK
2020-10-23T03:57:10.590Z [JOB] info: Rendering page ID 3...
2020-10-23T03:57:11.056Z [JOB] info: Using database driver pg for postgres [ OK ]
2020-10-23T03:57:12.504Z [JOB] info: Rendering page ID 3: [ COMPLETED ]
Loading configuration from /home/wikijs/wiki/config.yml... OK
2020-10-23T03:57:12.956Z [JOB] info: Rebuilding page tree...
2020-10-23T03:57:13.528Z [JOB] info: Using database driver pg for postgres [ OK ]
2020-10-23T03:57:13.737Z [JOB] info: Rebuilding page tree: [ COMPLETED ]
2020-10-23T03:57:13.762Z [MASTER] info: (STORAGE/DISK) Creating file [en] sandbox...
```

**Comment by NGPixel** [comment]
Don't you think if it was possible, it would be the case by default? It takes 4 seconds because there're a lot of steps involved when you save a page... Rendering, sending it to all storage modules you enabled, rebuilding the page tree to account for new/updated/removed links inside the page, update the search engine index, update the page cache, save to DB, etc.

**Comment by aberfan** [comment]
I was trying this out as well, and it takes significantly longer than 4 seconds to me. "lightweight and powerful" indeed.

**Comment by NGPixel** [comment]
This depends on your server CPU speed... Some steps (storage and search) will be moved to a different queue in 3.x, which should cut the wait time by half, but it still has to go through all your rendering modules in sequence.

You could also try to disable as many rendering modules that you don't need as possible.

**Comment by zzz945** [comment]
I wonder if it is possible not to rebuild the whole tree when create/update/move/delete one page?
