### ISSUE TITLE
File equal to or larger than 500KB is not saved in local filesystem.

### ISSUE THREAD

**Issue by ints81** [Requarks/wiki#2620]
**Question**
I'm trying to use the wiki.js container with MariaDB 10 in Synology. 

When i upload a file equal to or larger than 500KB, the file is not saved in the container. but there is a record in MariaDB that the file is uploaded.

So i changed mariadb configuration(`max_allowed_packet`) and wiki.js configuration, but it doesn't worth.

I guess there are some configuration files for file upload limit, but i don't know where they are.

**Host Info (please complete the following information):**
OS: wiki.js 2.5.159 image, Docker
Wiki.js version: 2.5.159
Database engine: mariadb 10

**Comment by NGPixel** [comment]
Is there any error in the logs when uploading?

The db column for mariadb is set to LONGBLOB, which has a max size of 4GB. So there's definitely some configuration either at the DB or network level that prevents it from being saved.

**Comment by ints81** [comment]
I solved the problem by changing DB from mariadb to postgres. close this issue.
