### ISSUE TITLE
Listening port to 80

### ISSUE THREAD

**Issue by peutre** [Requarks/wiki#2621]
**Question**

My actual configuration is **listening port** to **3000**
I would like to change it for **80**.
That way i don't have to precise http://mywiki:3000 and i just have to go to http://mywiki

Even if i do into my **config.yml**
```
#port: 3000
port: 80

```
It's not working, any idea ? 

Host Info:

OS: CentOS Linux release 7.6.1810 (Core)
Wiki.js version: 2.5.126
Database engine: postgres
I don't have firewall active

**Comment by NGPixel** [comment]
What "doesn't work" exactly? be more specific... Do you have any errors in the logs?

**Comment by peutre** [comment]
I understood why, i saw that into the log 👍 

`warn: listen EACCES: permission denied 0.0.0.0:80`

My user wiki doesn't have permission to open a port under 1024.
The easiest solution without using sudo is to do for rh system :

```
yum install libcap -y
setcap cap_net_bind_service=+ep /bin/node
```
