### ISSUE TITLE
Active Directory Authentication does not work

### ISSUE THREAD

**Issue by powerstow** [Requarks/wiki#2624]
**Question**
Hi

I've installed Wiki js following the official docker setup guide.
Everything is working great except when I try to authenticate users with LDAP.

Here is a screenshot:
https://i.imgur.com/9h2ljfP.png

I've checked all the settings and they are correct. It's only Wiki js that has LDAP problems for some reason.
There are no error entries in the log with the command: docker logs wiki

When users try to connect it says: "Invalid email / username or password."

I would appreciate any help. Thank you.

**Host Info:**
OS: Ubuntu 20.04, Docker
Wiki.js version: 2.5.159
Database engine: PostgreSQL 11

**Comment by thnk2wn** [comment]
Same problem here, even after upgrading to 2.5.170 which indicated in release notes that it fixed an AD strategy error.

![image](https://user-images.githubusercontent.com/120529/97446921-5e25d280-1905-11eb-8332-e8433a110bf3.png)

- Wiki.js 2.5.170
- Node 14.14.0
- Postgres 11.8

**Comment by kumashiro** [comment]
I can confirm. This is written to log when saving LDAP configuration and when trying to log in:

```
[MASTER] error: Authentication Strategy LDAP / Active Directory (74143d16-4e97-49fc-81d6-a47822773737): [ FAILED ]
[MASTER] error: ENOENT: no such file or directory, open
```

Turning on "LDAP debug" flag does not produce any more information.

**Comment by kevynb** [comment]
I found out that the problem only happens when you check the "Use TLS" checkbox and you don't provide a certificate Path.

It's because of some code in `server/modules/authentication/ldap/authentication.js`
```javascript
tlsOptions: (conf.tlsEnabled) ? {
            rejectUnauthorized: conf.verifyTLSCertificate,
            ca: [
              fs.readFileSync(conf.tlsCertPath)
            ]
          } : {},
```

The server tries to read the empty filename on the filesystem, doesn't find it and thus fails to persists the LDAP configuration.
Temporarily disabling TLS allowed me to setup and test the LDAP Auth mechanism successfully.

What is the expected behaviour here? Should we skip reading the file if `verifyTLSCertificate` is set to `false`?
I think we should also try to throw a more explicit error than `ENOENT: no such file or directory, open`.

I might find some time to create a PR in the next few weeks to fix the problem.

**Comment by kumashiro** [comment]
Disabling certificate validation should allow verification if possible (i.e. CA certificate for the server can be found in the specified directory), but should not fail if verification is not possible (i.e. no CA certificate, `tlsCertPath` not accessible, server certificate expired etc). In other words, disabling `verifyTLSCertificate` should not mean "do not verify at all".

**Comment by kevynb** [comment]
I think we agree, I might not have been clear enough in my writing. Rephrasing to be sure.

The `rejectUnauthorized` option is sent straight to the node.js `tls` module. The [node.js doc](https://nodejs.org/api/tls.html#tls_tls_connect_options_callback) states the following: 

> rejectUnauthorized \<boolean>: If not false, the server certificate is verified against the list of supplied CAs. An 'error' event is emitted if verification fails; err.code contains the OpenSSL error code. Default: true.

From what I understand it's all or nothing.

What I propose:
`tlsEnabled`: true, `verifyTLSCertificate`: true => read `tlsCertPath`
`tlsEnabled`: true, `verifyTLSCertificate`: false => __do not__ `fs.readFileSync(conf.tlsCertPath)`
`tlsEnabled`: false `verifyTLSCertificate`: false => __do not__ `fs.readFileSync(conf.tlsCertPath)`
