### ISSUE TITLE
How to disable guest access?

### ISSUE THREAD

**Issue by maorui2k** [Requarks/wiki#2627]
**Question**
I want to set the wiki site for private team use. How can I disable the guest access. So that only registered user can read/write topics.

**Host Info (please complete the following information):**
OS: [e.g. Ubuntu 18.04, Docker]
Wiki.js version: [e.g. 2.0.1]
Database engine: [e.g. postgres 9.7, mysql 5.7]

**Comment by Igorgro** [comment]
Select "Guest" user in admin panel and set all rights to deny.

**Comment by chris-hs** [comment]
The **Guest** user is also a part of the **Guest** group, so you can also alter permissions at the group level as well.

**Comment by maorui2k** [comment]
Got it, thx!
