### ISSUE TITLE
Always display login screen when user not authenticated

### ISSUE THREAD

**Issue by ankyfive** [Requarks/wiki#2630]
**Question**
Hello,
I would like the login screen to be displayed if the user has not been authenticated, currently the login screen is displayed when the user click on the login button.
Thanks

**Host Info (please complete the following information):**
OS: Debian 9.12
Wiki.js version: 2.5.159
Database engine: postgres 9.6.17

**Comment by chris-hs** [comment]
It sounds like you want to remove guest access - i.e. you want users to have to log in to access content.

Here is the documentation on how to accomplish this: [Private Wiki](https://docs.requarks.io/groups#private-wiki
)

**Comment by ankyfive** [comment]
Works great thanks for your help
Thanks for this wonderful wiki :-)
