### ISSUE TITLE
filter and orderBy input fields to group graphql API query

### ISSUE THREAD

**Issue by kurtis318** [Requarks/wiki#2633]
**Question**
I am trying to figure out what I must include in the graphql query for groups.   The input fields are filter and orderBy but of course the schema does not describe the syntax of what string values must be supplied.  I'm trying to filter on a specific email value but if I give just the email (kurtis318@gmail.com) for the filter input parameter I sill get ALL users.  Can anyone tell me what the syntax is for these fields?

Is there some place in the code that I can look to figure this out without having to post?  Thanks...

**Host Info (please complete the following information):**
OS: Fedora 32 Server
Wiki.js version: 2.5.159
Database engine: postgres 12.4

**Comment by NGPixel** [comment]
These fields were removed a long time ago and no longer have any effect.

Use the `users.search` query instead.

**Comment by kurtis318** [comment]
Both users and groups have a list query but only users have a users.search.  I suspect the fields were removed for both list queries.  Any chance of getting a groups.search query?

**Comment by NGPixel** [comment]
There's no search query for groups because the list is usually very short. I suggest querying the list and find the item you need from the results.
