### ISSUE TITLE
How to add git storage to a website deployed on heroku?

### ISSUE THREAD

**Issue by ucsk** [Requarks/wiki#2634]
**Question**
I am grateful for being able to use such an elegant application. However, I have an idea. I want to deploy the website locally, then generate a static webpage and publish it on GitHub pages. Does this work?

**Host Info (please complete the following information):**
OS: [Windows 10, nodejs]
Wiki.js version: [2.5.170]
Database engine: [mysql 8.0]

**Comment by ucsk** [comment]
Sorry, I have found a solution to this problem.
I hope you **delete this issue** to keep this code warehouse pure, thank you!

**Comment by kylebakerio** [comment]
@ucsk could you please elaborate? I'm wondering about this same question.... and in the future, please leave solutions you find available for others out there. Good karma and all. :)
