### ISSUE TITLE
Adding video in markdown page

### ISSUE THREAD

**Issue by ankyfive** [Requarks/wiki#2635]
**Question**
Hello,
I use markdwon editor and it is supposed to allow HTML code.
I would like to insert a video in a page so I tried like this : 
<iframe width="560" height="315" src="/myvid.mp4" frameborder="0">
</iframe>
But it does not work.
Any help would be appreciated.
Thanks

**Host Info (please complete the following information):**
OS: Debian 9.12
Wiki.js version: 2.5.159
Database engine:postgres 9.6.17

**Comment by smcardle** [comment]
Have you tried using the <video> element instead of the <iframe> ???

**Comment by ankyfive** [comment]
<video> element works !
Thanks
