### ISSUE TITLE
Insert table with markdown editor

### ISSUE THREAD

**Issue by ankyfive** [Requarks/wiki#2637]
**Question**
Hello,
We use the markdown editor and it seems that there is an icon to insert directly tables, but ours is grey.
I tried to activate multimakdown tab in the rendering options but it has no impact.
Is there a way to have this icon to insert tables ?
Thanks a lot :-)
You are the best wiki !

**Host Info (please complete the following information):**
OS: Debian 9.12
Wiki.js version: 2.5.159
Database engine:postgres 9.6.17

**Comment by JussiKivimaki** [comment]
Mine is inactive too, but the table syntax is supported, see:

https://www.markdownguide.org/extended-syntax/#tables

**Comment by ankyfive** [comment]
Hi !
Thanks for your reply, it is what I did, but I would like to make it run ...

**Comment by NGPixel** [comment]
Use the markdown syntax to create tables. The UI button doesn't do anything yet.

**Comment by ankyfive** [comment]
Ok thanks :-)
