### ISSUE TITLE
Stuck in configuration process > Checking your system for compatibility

### ISSUE THREAD

**Issue by akerd** [Requarks/wiki#264]
### Actual behavior

After launching the command

`node wiki start 80`

and opening localhost at port 80 I am able to see the welcome page and start the configuration process, but it hangs with message "Checking your system for compatibility..." and I have no idea why. 

Is it possible to understand the reason why the system check is not able to go on?

I tried to use also the default port 3000 but same problem.

### Steps to reproduce the behavior

Windows Server 2016 behind corporate proxy

I installed the pre-requisites:

- Node.js 6.11.4
- Mongo DB 3.4.9
- Git 2.14.2

Powershell install script completed successfully.
I run the command "node wiki configure 80" and launched Internet Explorer 11 to connect to localhost.

**Comment by Modest-as** [comment]
Hi,

I've noticed this behavior today myself. I was also using IE... Tried with firefox and it worked like a charm. Anyway, I hope this comment will make it easier to replicate.

**Comment by NGPixel** [comment]
This will be fixed in 2.0.

As a workaround for 1.x, avoid using IE for setting up Wiki.js.

**Comment by NGPixel** [comment]
Fixed in 2.0 (c94e2d5700724cd2dc3a4735bbe95e9cf1b567e2)

**Comment by akerd** [comment]
Thank you, I confirm that 1.x installation procedure works using another browser.
