### ISSUE TITLE
Custom Login Screen?

### ISSUE THREAD

**Issue by shahasad78** [Requarks/wiki#2642]
**Question**
I was wondering where we configure the look of the Login screen?  How do I replace the background Wiki JS logo? The CSS? etc...

**Host Info (please complete the following information):**
 Linux | Docker
Wiki.js version:  2.5.159
Database engine: PostgreSQL 11.8

**Comment by ankyfive** [comment]
You will find the info here : https://docs.requarks.io/auth
In  Login Background Image
