### ISSUE TITLE
Demo site not being created / Runme.io to be defunct after Dec. 1, 2020.

### ISSUE THREAD

**Issue by shimizurei** [Requarks/wiki#2649]
**Question**
Error message while attempting to run the demo:

```
Oops!
No app has been found with ID "5ad463aa-078d-4471-aac9-199dc41ed896. Please (re)generate a new button in order to run your application. Please go back to the generator page and create a button and run url.
```

Also, footer of demo host states: `!! Service will be shutdown and become unavailable from 01.12.2020 !!`

**Host Info (please complete the following information):**
N/A

**Comment by NGPixel** [comment]
Yes, the service is shutting down unfortunately. So until an alternative is found, a demo won't be available.

**Comment by shimizurei** [comment]
Then shouldn't references to the demo on the readme be strukthrough until an alternative is found? So people like me hoping to test the program aren't frustrated finding a non-working process?

**Comment by NGPixel** [comment]
It's already the case....?

**Comment by shimizurei** [comment]
Not from what I can see...

![Screenshot 2020-11-03 19 09 40](https://user-images.githubusercontent.com/3500094/98054193-4ddf8d00-1e08-11eb-8b92-d2012e2594b4.png)

**Comment by NGPixel** [comment]
Have you tried clicking on the link?

**Comment by shimizurei** [comment]
Yes, I did.

Why not just strike through the demo on the readme?

Example: ~~Demo~~ (demo site down until further notice due to defunct demo host)

It's kind of disappointing to click a link and be told "Oh sorry, it's no longer available" when it should be known before the user wastes a click. Just my 2 cents.
