### ISSUE TITLE
使用插入文件方式上传图片，其他用户登录查看图片无法正常显示；换插入图片方式，保存提示：“Network error: Response not successful: Received status code 413”

### ISSUE THREAD

**Issue by miocoo** [Requarks/wiki#2650]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Host Info (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04, Docker]
 - Wiki.js version: [e.g. 2.0.1]
 - Database engine: [e.g. postgres 9.7, mysql 5.7]

**Additional context**

**Comment by NGPixel** [comment]
Write a proper ticket, not just a title with no info.
