### ISSUE TITLE
How-to restrict access to wiki.js for only one AD group?

### ISSUE THREAD

**Issue by LetArch** [Requarks/wiki#2651]
All works fine, but I need to restrict access to our wiki.js for only one AD group?

**Our host:**
OS: Linux - CentOS (core) 7.8.2003 x64
Wiki.js version: 2.5.170
Database engine: PostgreSQL 13.0

**AD connect config:**
![111](https://user-images.githubusercontent.com/3818210/97877868-40a69d80-1d37-11eb-946f-d3546484128a.png)

**Comment by NGPixel** [comment]
https://requarks.canny.io/wiki/p/map-ldap-groups-as-roles
