### ISSUE TITLE
Login doesn't work on Heroku

### ISSUE THREAD

**Issue by sokolmarek** [Requarks/wiki#2652]
**Describe the bug**
If you deploy the app to heroku through wikijs site, login doens't work. It says invalid username/password. This applies to both http and https.

**To Reproduce:**
1. Deploy app to heroku
2. Try to login

**Expected behavior**

**Host:**
 - OS: Heroku
 - Wiki.js latest
 - Database engine: postgres 12

**Comment by NGPixel** [comment]
Duplicate of #2558
