### ISSUE TITLE
Invalid email / username or password. when it is correct after install

### ISSUE THREAD

**Issue by dwaynelofton** [Requarks/wiki#2654]
After setup, wikijs inits and I try to put in the email address and password I used during setup. It says invalid. I've gone into postgres and reset the bcrypt'ed password over and over (using https://bcrypt-generator.com/). I've even created a new user directly in the database. Both say invalid username/password no matter what i do.

don't know what else to try.

i cant use the reset function built in because i've never gotten in to setup the smtp.

**Host Info (please complete the following information):**
OS: Windows 2016
Wiki.js version: 2.5.159
Database engine: postgres 13

**Comment by NGPixel** [comment]
Is the email address in lowercase?

**Comment by dwaynelofton** [comment]
> Is the email address in lowercase?

It wasn't no. I reinstalled wikiks and used lowercase.

**Comment by NGPixel** [comment]
Does it work now?

**Comment by dwaynelofton** [comment]
> Does it work now?

Yes, if it was because the address had an uppercase letter in it then that's dumb. They should convert it to lower if it's a problem.

**Comment by NGPixel** [comment]
Yes this is a known bug and will be fixed soon.
