### ISSUE TITLE
Navigation tree not up to date

### ISSUE THREAD

**Issue by ankyfive** [Requarks/wiki#2655]
**Question**
Hello,

I have deleted some files and folders manually cause they are no more used.
My problem is that they are still present in the navigation tree...
I have tried different things, like rebuild tree, empty cache, restart the wiki but they are still present.
How to remove them from the navigation tree ?
I saw that they are in the pagetree table, is possible to delete the records in the DB ?

Thanks.

**Host Info (please complete the following information):**
OS: Debian 9.12
Wiki.js version: 2.5.159
Database engine:postgres 9.6.17

**Comment by NGPixel** [comment]
Deleting files on disk won't magically delete them in the DB. Delete the pages using the UI, not directly on disk.
