### ISSUE TITLE
Unable to assign write:styles or write:scripts to page rules

### ISSUE THREAD

**Issue by PaulD987** [Requarks/wiki#2658]
In the global group permission tab there is options to assign write:styles and write:scripts for a group, but on the "Page Rules" tab when assigning permissions for a specific page rule there are no options to assign write:styles or write:scripts to specific page rules. This means that, as far as I can work out, only administrators are actually able to edit individual page styles etc.

1. Go to Administration Area
2. Click on Groups
3. Click on + New Group and create a group called "Test"
4. Select the group called "Test"
5. Select the "Permissions" tab
6. Tick the write:pages, manage:pages, write:styles and write:scripts permissions
7. Select the "Page Rules" tab
8. For the default rule for / add "Create Pages" and "Edit + Move Pages"
9. Observe that there are no options to add write:styles and write:scripts for the page rule
10. Click Update Group
11. Assign a user to this group
12. Log on as a user, select Edit for a page and then the Page link... observer that the Script and Style tabs are greyed out.

**Expected behavior**
I would expect there to be an option to assign write:styles and write:scripts for specific page rules.
**Host Info **
 - OS: Docker
 - Wiki.js version: 2.5.170
 - Database engine: postgres 13 

**Additional context**
If there is a wide table on a page, it isn't possible to get to the right hand side of the table... the workaround I came up with was to add a style to the page of

.page-col-content {
  overflow-x: scroll
}

This makes the page contents scrollable horizontally... Users aren't able to add this CSS themselves to a page, it is only accessible to an admin.

**Comment by PaulD987** [comment]
Forgot to say that looking at the code, the options appear to have been missed from client/components/admin/admin-groups-edit-rules.vue

**Comment by PaulD987** [comment]
Discovered that there is of course the option to add a little extra CSS for the theme being used, which has solved the reason I went down this whole path... but the actual bug of not being able to set permissions for write:styles and write:scripts still stands!

**Comment by Kyushin** [comment]
Same issue, when applying write:styles permission, there is no way to enable styles modification from pages edition mode.

**Comment by PaulD987** [comment]
I believe this has been fixed in the latest version via PR #2829 so going to close this out.
