### ISSUE TITLE
Update submodule in github storage

### ISSUE THREAD

**Issue by rafaelcorbellini-egsys** [Requarks/wiki#2660]
**Question**

I already have several repositories with wiki on github, I would like to use wikijs to be able to aggregate all of them, I thought about cloning the wikijs storage project and inside it adding the existing github wiki as a sub-module, but apparently the sync pull does not considers submodule.

is there any way to deal with this situation?

**Comment by NGPixel** [comment]
Git submodules are not supported at the moment.

You can follow this feature request:
https://requarks.canny.io/wiki/p/submodules-for-create-wiki-of-wikis
