### ISSUE TITLE
Importing pandoc markdown files

### ISSUE THREAD

**Issue by account-sxf** [Requarks/wiki#2661]
**Question**
I've exported our knowledge base from OneNote to markdown files in directories (no spaces but title case lettering are present in these files and directories). As there are thousands of files we want to avoid manually recreating each page. How do we import markdown files quickly in to wiki.js?

We could re-export the OneNote files into a different format, but I specifically chose wiki.js for it's handling of markdown which is my preferred format.

**Host Info:**
OS: Windows Server / Windows 10
Wiki.js version: 2+
Database engine: postgres

**Comment by NGPixel** [comment]
There're many utilities you can use to batch rename all files to kebab-case formatting.

You can import all markdown files using the Local File System storage module. Point to your directory and click Import All.

**Comment by account-sxf** [comment]
Happy for this to be closed by the owner if they have nothing to add. Thanks @NGPixel that's a good pointer, cheers.
