### ISSUE TITLE
smtp setup for digital ocean

### ISSUE THREAD

**Issue by sattitan19** [Requarks/wiki#2663]
**Question**
Describe in details what you are trying to achieve and where do you need guidance.

**Host Info (please complete the following information):**
OS: Ubuntu 18.04, Docker
Wiki.js version: 2.5
Database engine: postgres 9.7

have created a droplet in digital ocean and looking to configure email for user registration verification.. can someone suggest which one to use and does digital ocean blocks smtp for new accounts?

**Comment by NGPixel** [comment]
This is unrelated to digitalocean. You need an SMTP server to send emails. If you don't have one, there're several services you can use, e.g.:

- Gmail
- ImprovMX
- Sendgrid
- Mailgun
etc.
