### ISSUE TITLE
Wiki.js binds to IPv6 localhost rather then IPv4 localhost on Fedora26

### ISSUE THREAD

**Issue by ghost** [Requarks/wiki#267]

**Comment by neptunerx** [comment]
its possible everything is binding to IPv6 in Fedora 26, I just installed caddy server and it's also bound to the IPv6 stack

**Comment by neptunerx** [comment]
sysctl net.ipv6.bindv6only
net.ipv6.bindv6only = 0

**Comment by neptunerx** [comment]
uname -a returns: Linux localhost.localdomain 4.13.4-200.fc26.x86_64 #1 SMP Thu Sep 28 20:46:39 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

cat /etc/*release* returns:
Fedora release 26 (Twenty Six)
NAME=Fedora
VERSION="26 (Twenty Six)"
ID=fedora
VERSION_ID=26
PRETTY_NAME="Fedora 26 (Twenty Six)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:fedoraproject:fedora:26"
HOME_URL="https://fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=26
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=26
PRIVACY_POLICY_URL=https://fedoraproject.org/wiki/Legal:PrivacyPolicy
Fedora release 26 (Twenty Six)
Fedora release 26 (Twenty Six)
cpe:/o:fedoraproject:fedora:26

SELinux is set to permissive

**Comment by markeganfuller** [comment]
A temporary workaround for this is to edit the listen call at https://github.com/Requarks/wiki/blob/master/server/configure.js#L420 to include an address e.g.

```javascript
server.listen(port, '0.0.0.0')
```

**Comment by AritroMukherjee** [comment]
Thanks @markeganfuller  for the update. 
When running node wiki configure on Nginx Server,I faced similar issue with IPV6.  The workaround step by @markeganfuller worked , but if i need to add an IP address in place of 0.0.0.0, what should be procedure?
