### ISSUE TITLE
NPM install Fibers@5.0.0

### ISSUE THREAD

**Issue by PrinsGeryha** [Requarks/wiki#2671]
**Question**
Wiki.js wont install from cpanel/node.js

Fibers@5.0.0 failing at npm install

**Host Info (please complete the following information):**
OS: Linux arch x64
Wiki.js version: 2.5.170
Database engine: postgres 9.2.24

> 132 verbose stack Error: fibers@5.0.0 install: `node build.js || nodejs build.js`
132 verbose stack spawn ENOENT
132 verbose stack     at ChildProcess.<anonymous> (/opt/alt/alt-nodejs14/root/usr/lib/node_modules/npm/node_modules.bundled/npm-lifecycle/lib/spawn.js:48:18)
132 verbose stack     at ChildProcess.emit (events.js:314:20)
132 verbose stack     at maybeClose (internal/child_process.js:1051:16)
132 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
132 verbose stack From previous event:
132 verbose stack     at runAction (/opt/alt/alt-nodejs14/root/usr/lib/node_modules/npm/lib/install/actions.js:74:13)
132 verbose stack     at actions.<computed> (/opt/alt/alt-nodejs14/root/usr/lib/node_modules/npm/lib/install/actions.js:50:17)
132 verbose stack     at execAction (/opt/alt/alt-nodejs14/root/usr/lib/node_modules/npm/lib/install/actions.js:191:18)
132 verbose stack     at processImmediate (internal/timers.js:458:21)
132 verbose stack From previous event:
132 verbose stack     at /opt/alt/alt-nodejs14/root/usr/lib/node_modules/npm/lib/install/actions.js:159:15
132 verbose stack From previous event:
132 verbose stack     at withInit (/opt/alt/alt-nodejs14/root/usr/lib/node_modules/npm/lib/install/actions.js:175:13)
132 verbose stack     at runSerial (/opt/alt/alt-nodejs14/root/usr/lib/node_modules/npm/lib/install/actions.js:158:10)
132 verbose stack     at doSerial (/opt/alt/alt-nodejs14/root/usr/lib/node_modules/npm/lib/install/actions.js:139:3)
132 verbose stack     at Array.<anonymous> (/opt/alt/alt-nodejs14/root/usr/lib/node_modules/npm/node_modules.bundled/slide/lib/bind-actor.js:15:8)
132 verbose stack     at LOOP (/opt/alt/alt-nodejs14/root/usr/lib/node_modules/npm/node_modules.bundled/slide/lib/chain.js:15:14)
132 verbose stack     at /opt/alt/alt-nodejs14/root/usr/lib/node_modules/npm/node_modules.bundled/slide/lib/chain.js:18:7
132 verbose stack     at doParallel (/opt/alt/alt-nodejs14/root/usr/lib/node_modules/npm/lib/install/actions.js:123:30)
132 verbose stack     at Array.<anonymous> (/opt/alt/alt-nodejs14/root/usr/lib/node_modules/npm/node_modules.bundled/slide/lib/bind-actor.js:15:8)
132 verbose stack     at LOOP (/opt/alt/alt-nodejs14/root/usr/lib/node_modules/npm/node_modules.bundled/slide/lib/chain.js:15:14)
132 verbose stack     at /opt/alt/alt-nodejs14/root/usr/lib/node_modules/npm/node_modules.bundled/slide/lib/chain.js:18:7
132 verbose stack     at runSerial (/opt/alt/alt-nodejs14/root/usr/lib/node_modules/npm/lib/install/actions.js:157:30)
132 verbose stack     at doSerial (/opt/alt/alt-nodejs14/root/usr/lib/node_modules/npm/lib/install/actions.js:139:3)
132 verbose stack     at Array.<anonymous> (/opt/alt/alt-nodejs14/root/usr/lib/node_modules/npm/node_modules.bundled/slide/lib/bind-actor.js:15:8)
132 verbose stack     at LOOP (/opt/alt/alt-nodejs14/root/usr/lib/node_modules/npm/node_modules.bundled/slide/lib/chain.js:15:14)
132 verbose stack     at /opt/alt/alt-nodejs14/root/usr/lib/node_modules/npm/node_modules.bundled/slide/lib/chain.js:18:7
132 verbose stack     at /opt/alt/alt-nodejs14/root/usr/lib/node_modules/npm/lib/install/actions.js:163:5
133 verbose pkgid fibers@5.0.0
134 verbose cwd /home/velocxkr/wiki.velocitygaming.no
135 verbose Linux 3.10.0-962.3.2.lve1.5.39.el7.x86_64
136 verbose argv "/opt/alt/alt-nodejs14/root/usr/bin/node" "/opt/alt/alt-nodejs14/root/usr/bin/npm" "install" "--prefix=/home/velocxkr/nodevenv/wiki.velocitygaming.no/14/lib"
137 verbose node v14.7.0
138 verbose npm  v6.14.7
139 error code ELIFECYCLE
140 error syscall spawn
141 error file sh
142 error errno ENOENT
143 error fibers@5.0.0 install: `node build.js || nodejs build.js`
143 error spawn ENOENT
144 error Failed at the fibers@5.0.0 install script.
144 error This is probably not a problem with npm. There is likely additional logging output above.
145 verbose exit [ 1, true ]

**Comment by NGPixel** [comment]
That's not how you install Wiki.js. Follow the [instructions](https://docs.requarks.io/install).

**Comment by PrinsGeryha** [comment]
When running Node Server on Linux installation, the logging stops on rebuilding Page tree. Any suggestions there?

I'm using a web host to do this. Through cpanel and Node.JS selector.

**Comment by Smankusors** [comment]
> the logging stops on rebuilding Page tree.

it's already running normal there.
