### ISSUE TITLE
How to add sitemap.xml file to site? 

### ISSUE THREAD

**Issue by I3rett** [Requarks/wiki#2676]
Hi!

My wiki https://sofubiki.com is connected to a Digital Ocean space as the storage. 

I have a site.xml file to upload to the root of my site, but I'm guessing adding this to the root of the DO Space would be the wrong thing to do? How do I add it to the root of my public site with the domain https://sofubiki.com/sitemap.xml? 

Many thanks
B

**Comment by NGPixel** [comment]
Simply upload it via Wiki.js by editing any page and uploading an asset, put it in the root folder.

**Comment by I3rett** [comment]
That makes sense! thanks Nicolas!
