### ISSUE TITLE
Can't login anymore (login form missing)

### ISSUE THREAD

**Issue by j5k** [Requarks/wiki#2677]
### Actual behavior
I've set the login background image, but missed to give permission. Now the browser can't load this image anymore (Error 402). The Problem now: I can't login too, since the login form is missing!

### Expected behavior
I can see the login form to sign in

### Steps to reproduce the behavior
1. Set login background image in the settings
2. Image with no public access right
3. Logout
4. Login form is missing with errors in the browser console

**Comment by NGPixel** [comment]
try with `/login?all=1`

**Comment by j5k** [comment]
This helped, thanks a lot!
