### ISSUE TITLE
disable browse button on wiki

### ISSUE THREAD

**Issue by sattitan19** [Requarks/wiki#2679]
**Question**
Q1 : all the pages created are visible in the browse section.. i want a way to disable displaying all the pages in browse section or disable the browse button all together .
Q2: How to remove the section with tags and last edited by . or is there a way to shift this to some different location.

**Host Info (please complete the following information):**
OS: Ubuntu 18.04, Docker
Wiki.js version: 2.5.170
Database engine: postgres 11.8

**Comment by NGPixel** [comment]
1. Administration Area > Navigation
2. No that's not possible. Planned for a future release.
