### ISSUE TITLE
Fail to connect on the Docker Postgres DB_HOST with container name since update to last stable version 

### ISSUE THREAD

**Issue by benrob42** [Requarks/wiki#2681]
**To Reproduce**
1. The docker running the postgres database is called db
2. The docker running requarks/wiki:2 is called wiki
3. docker-compose is using environment variable with DB_HOST=db
4. Connection failed for the docker wiki to reach the docker db
from docker logs wiki, getaddrinfo ENOTFOUND error

**Expected behavior**
I expect a correct connection.

**Host Info (please complete the following information):**
 - OS: Debian 10, docker 19.03.8 
 - Wiki.js version: 2.5.170
 - Database engine: postgres 13.0

**Additional context**
If i get the IP from docker inspect db, i replace DB_HOST=db container to DB_HOST=IP of the container, then it works fine.
Where is the problem ? It was working previously to the switch to last version. My previous version was from may 2020.

**Comment by NGPixel** [comment]
Make sure your wiki container is on the same network as your db container?

I'm using the same container names + config and I can't reproduce your issue.

**Comment by ChipWolf** [comment]
We can replicate something similar ![](https://i.cwlf.uk/zqz8L)

Single-node deployment

**Comment by benrob42** [comment]
Thanks for your answer

Make sure your wiki container is on the same network as your db container?
They are on the same network.
Do not forget that i set the IP of the db container to the DB_HOST, it is working fine.

**Comment by benrob42** [comment]
Updating the docker version, it works correctly.
