### ISSUE TITLE
Configuration filepath mismatch

### ISSUE THREAD

**Issue by kmpm** [Requarks/wiki#2685]
**Describe the bug**
The path to the used configuration file shown in the admin UI does not match what is shown in the server output.

**To Reproduce**

1. set CONFIG_FILE environment variable to /wiki/custom/config.yml
2. Start you wiki server
2. Take note of configuration path displayed during startup `Loading configuration from /wiki/custom/config.yml... OK`
3. Log in to the wiki
2. Navigate to Administration -> System Information
3. Note the name of the configuration file: `/wiki/config.yml`
4. Notice the difference

**Expected behavior**
I expect the configuration file used to be the one that I define using the CONFIG_FILE  environment variable to be used.
And I expect the server log output to match what is displayed in the UI.

**Host Info (please complete the following information):**
 - OS: Alpine Linux 3.11 (docker image requarks/wiki:2.5.170)
 - Wiki.js version: 2.5.170
 - Database engine: postgres 11

**Additional context**
The server does not seem to pick up the custom config file. At least not all settings like logLevel.

**Comment by NGPixel** [comment]
CONFIG_FILE is not a valid env parameter when using Docker, mount your custom config file to the proper location instead:
https://docs.requarks.io/install/docker#alternative-mount-the-config-file
