### ISSUE TITLE
Empty reply from the webUI

### ISSUE THREAD

**Issue by Lightningblade** [Requarks/wiki#2686]
**Question**
![image](https://user-images.githubusercontent.com/30607152/98654246-5a9b3e00-233e-11eb-98af-0d3febede365.png)

I've setup a network in docker for both the wiki.js and postgres container.

I've then setup a default postgres database from the portainer app templates, added a postgres superuser as default user afterwards a wiki user with CREATEDB permissions and added a wiki database for the wiki.js' wiki user to use. (Connected to the network)

Afterwards I set up the wiki.js container with environment variables (Screenshot later).

The wiki shows:
![image](https://user-images.githubusercontent.com/30607152/98653997-055f2c80-233e-11eb-827f-73e4c9ccebb2.png)

and postgres shows:
![image](https://user-images.githubusercontent.com/30607152/98654016-0c863a80-233e-11eb-83ec-55343f65a097.png)

but when I try to connect to the website (I tunneled the ports 4443 and 4000 via SSH) firefox shows:
![image](https://user-images.githubusercontent.com/30607152/98654655-e01eee00-233e-11eb-9497-120cea3fa4af.png)

and also if i curl from the docker host machine (Ubuntu) itself it shows:
```
<user>@<server>:~$ curl localhost:4443
curl: (52) Empty reply from server
<user>@<server>:~$ curl localhost:4000
curl: (52) Empty reply from server
<user>@<server>:~$ curl localhost:2468
curl: (7) Failed to connect to localhost port 2468: Connection refused
```
Where the last port is for reference on a port that isn't being used.

**Host Info**
OS: Ubuntu 18.04, Docker with portainer
Wiki.js version: 2
Database engine: Postgres 9.7

**Comment by Smankusors** [comment]
> I tunneled the ports 4443 and 4000 via SSH

how do you tunnel it?

**Comment by Lightningblade** [comment]
-L  on the SSH command
So like this
```ssh -L 4000:localhost:4000 <user>@<server>```

4000 because 3000 is in use by grafana

**Comment by Smankusors** [comment]
> -L on the SSH command
> So like this
> `ssh -L 4000:localhost:4000 <user>@<server>`
> 
> 4000 because 3000 is in use by grafana

but Wiki.js container uses port 3000 and 3443. You should publish ports with 3443:3443 and 4000:3000. After that, you can tunnel it via SSH like you just write.

**Comment by Lightningblade** [comment]
Thank you, using the default ports worked. I think it is because I followed a strange guide that configured different ports.
