### ISSUE TITLE
Attempting to run Wiki.js on a separate port

### ISSUE THREAD

**Issue by james-pierian** [Requarks/wiki#2688]
**Question**
I am running wiki.js in docker (portainer being used), I already have one wiki on this machine running on the standard setup (port:3000 so accessible on :80), I am trying to run a second wiki on another port (the port is less important to me but attempting port:6000 at the moment).
I have assigned the wiki port 6000 in portainer when setting it  up (using the editor) and I've gone into the container and amended the config.yml file to include port 6000 however, I am guessing I'm missing something as im getting no response.

**Host Info (please complete the following information):**
OS:Ubuntu 20.04, Docker with portainer
Wiki.js version: 2
Database engine: postgres:11-alpine

Any support would be greatly appreciated

**Comment by NGPixel** [comment]
the docker image always listens on port 3000, you shouldn't change that. Change the mapped port on the host instead...

**Comment by james-pierian** [comment]
Understood - Working now as expected, thank you for your help!
