### ISSUE TITLE
Wrong version definition (After upgrading to version 1.0.10 the content still shows the version as 1.0.9)

### ISSUE THREAD

**Issue by adrianokerbermenvia** [Requarks/wiki#269]
For some reason, after upgrading the project to version 1.0.10 the system version keeps showing version 1.0.9 but the new features (from version 1.0.10) are enabled.
```
Current Version: v1.0.9
Latest Version: v1.0.10 (Published 2 days ago)
```

This might be a problem of wrong version definition...

**Comment by NGPixel** [comment]
Yes, this is an oversight while publishing 1.0.10. I'll manually edit the package today to set the correct version. It won't apply to people who already upgraded thouh, but if that bothers you, you can simply change the version number in `package.json` and restart Wiki.js.

**Comment by NGPixel** [comment]
1.0.11 is now using the correct version.
