### ISSUE TITLE
Locale doesn't apply to visual editor

### ISSUE THREAD

**Issue by ThomasGrabner** [Requarks/wiki#2692]
**Question**
I configured a locale (german). However, the tooltips in the visual editor remain english. Everywhere else, localization seems to work fine. Is there something I missed?

**Host Info (please complete the following information):**
OS: Ubuntu 20.04, Docker
Wiki.js version: 2.5.170
Database engine: postgres 11

**Comment by NGPixel** [comment]
Some parts of Wiki.js are not localized yet. Full localization is planned for the upcoming 3.0 version.
