### ISSUE TITLE
Error pulling 2.5 image on RHEL

### ISSUE THREAD

**Issue by Torrent007** [Requarks/wiki#2697]
**Question**
I tried to pull docker image on a RHEL server but it stuck:
```bash
$ docker pull requarks/wiki:2.5
2.5: Pulling from requarks/wiki
cbdbe7a5bc2a: Pull complete
378c9540b231: Pull complete
fd5173d17220: Pull complete
72f138d46980: Pull complete
74382a44e606: Pull complete
4f4fb700ef54: Pull complete
ab5ff9e03eb3: Pull complete
1fea9e8e8c69: Waiting
9f0cf322f125: Download complete
2b3bef2c2387: Download complete
851aa5803f4c: Download complete
8d5a10bb333d: Download complete
0490c826c8fe: Download complete
```

I successfully pulled image for 1.0
I failed to pull 2.x
is RHEL server not supported ?

**Host Info :**
**OS:** Docker on RHEL 7
**Docker version:** Docker version 19.03.13, build 4484c46d9
**Wiki.js version:** 2.5.170

**Comment by NGPixel** [comment]
Looks like a network issue on your side or with the repository? Try again?
