### ISSUE TITLE
How to update my wikijs deploy to the latest version?

### ISSUE THREAD

**Issue by zasshuwu** [Requarks/wiki#2699]
**Question**
I deployed wikijs v2 on a Heroku container with postgres. I see that there are new updates to the framework and I need help on updating since I haven't seen docs on how to do it anywhere. Thanks.

**Host Info (please complete the following information):**
OS: Linux - Alpine Linux (linux) 3.11.6 x64 (Heroku)
Wiki.js version: 2.5.159
Database engine: postgres 12.4
Runtime: Nodejs 14.12.0

**Comment by NGPixel** [comment]
The [docs page for Heroku](https://docs.requarks.io/install/heroku) clearly warns against using it if you're not knowledgeable on upgrading it yourself. Unless someone can chime in on how to do it, as far as I'm concerned, I won't be able to help you.

**Comment by zasshuwu** [comment]
> The [docs page for Heroku](https://docs.requarks.io/install/heroku) clearly warns against using it if you're not knowledgeable on upgrading it yourself. Unless someone can chime in on how to do it, as far as I'm concerned, I won't be able to help you.

Thank you for the reply.
So after fooling around with the Heroku postgres backup stuff, I think I managed to unofficially "upgrade" my wikijs instance, (e.g. mywiki-prod) by:

1. Getting a postgres dump of my data (latest.dump) from heroku
2. Creating a new instance of wikijs (e.g. mywiki-dev)
3. (Important) Going through the first visit of the wikijs app first before importing the data dump or else the instance corrupts itself
4. Importing the data dump
5. Reload et voila (existing creds were also imported)

Detailed instructions on how to export & import Heroku postgres could be found **[here](https://devcenter.heroku.com/articles/heroku-postgres-import-export)**.
