### ISSUE TITLE
Support Azure Active Directory

### ISSUE THREAD

**Issue by koallen** [Requarks/wiki#27]
Hi, I'm deploying this system onto my own server and I need to authenticate users with Azure Active Directory (i.e. work/school account from Microsoft). Could you add support for this? Currently the `Microsoft Login` is only for Microsoft accounts.

**Comment by NGPixel** [comment]
Can definitely be added. However, I want to get Beta 9 released ASAP so I'll push this one for Beta 10.

**Comment by NGPixel** [comment]
Added in Beta 11

Commit 7c1dd8b92af762fd18bf4ded7ecc64dc3bca583d
