### ISSUE TITLE
Cant delete permissions and they dont work

### ISSUE THREAD

**Issue by KovganIV** [Requarks/wiki#270]
I added user and make his permissions.
I can move page, but i cant edit it or create new.
And I cant delete permissions.

![screen shot 2017-10-12 at 00 04 06](https://user-images.githubusercontent.com/7087925/31454830-fc4b4e78-aee0-11e7-9080-d1c478ff1adf.png)
![screen shot 2017-10-12 at 00 04 17](https://user-images.githubusercontent.com/7087925/31454831-fc7a4020-aee0-11e7-9220-a5205453b9d8.png)
![screen shot 2017-10-12 at 00 04 28](https://user-images.githubusercontent.com/7087925/31454832-fca80730-aee0-11e7-90fe-dbd47529a46e.png)

**Comment by NGPixel** [comment]
Because of bug #147, you must add a permission rule to `/edit` and `/create`. This will be fixed in 2.0.
