### ISSUE TITLE
Dificuldade de Imagens em Grupos

### ISSUE THREAD

**Issue by ViniciusLima7** [Requarks/wiki#2700]
Olá boa tarde, estou usando o wiki.js

E criei algumas paginas e defini as permissões por grupo.
Nos grupos específicos eles conseguem visualizar aquilo que eu liberei de acordo com as regras de página.
Porém as imagens não são visíveis apenas quando coloco o usuário dentro do grupo administrador ai sim ele consegui ver as imagens o que pode ser?

**Comment by NGPixel** [comment]
Please write tickets in english.
