### ISSUE TITLE
graphql update page mutation: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by triffid** [Requarks/wiki#2702]
**Describe the bug**
Getting " Cannot read property 'map' of undefined" for page update mutations

**To Reproduce**
Feeding

	mutation {
		pages {
			update (id:2, content:"This page edited via API") {
				responseResult {
					errorCode,
					message,
					succeeded,
					slug
				}
			}
		}
	}

into https://my-wiki-host/graphql via web browser gives me

	{
		"data": {
			"pages": {
				"update": {
					"responseResult": {
						"errorCode": 1,
						"message": "Cannot read property 'map' of undefined",
						"succeeded": false,
						"slug": "TypeError"
					}
				}
			}
		}
	}

Which seems like either an internal error, or a message that's just as obtuse as the one that appears when I forget to put the authorization token into http headers.

**Expected behavior**
Either page text gets changed, or receive a _meaningful_ error message that suggests the proper way to do it.

**Host Info (please complete the following information):**
 - OS: Docker Container (Linux)
 - Wiki.js version: 2.5.170
 - Database engine: PostgreSQL 11.8

**Additional context**
I'm having a terrible time trying to find any documentation for this API - seems like there's a machine-readable schema but no tutorials or examples anywhere, so I'm left stumbling about in the dark trying to guess what query format I need to do what I want.

**Comment by NGPixel** [comment]
The API is self-documented using GraphQL. You can go to `/graphql` on your installation to launch the GraphQL Playground. You can build queries from there and see the full documentation on the right.

**Comment by triffid** [comment]
A list of functions and parameters is hardly documentation, and it offers zero clue why I might be getting "Cannot read property 'map' of undefined" back from the server for what seems like a fairly simple query.

**Comment by a-stoyanov** [comment]
I've also ran across this issue and it seems to be a bug. It goes away when you declare the id argument as a **Int!** type variable and pass it to the mutation like so:

`mutation Page(
  $id: Int!
  $content: String!
  $description: String!
  $tags: [String]!
  $title: String!
  $isPublished: Boolean!
) {
  pages {
    update(
      id: $id
      content: $content
      description: $description
      tags: $tags
      title: $title
      isPublished: $isPublished
    ) {
      responseResult {
        succeeded
        errorCode
        slug
        message
      }
      page {
        id
        path
        title
      }
    }
  }
}`

VARS
`{
"id": 21, 
"content": "HELLO WORLD!",
"title": "page title",
"description": "page description",
"tags": ["patching", "maintenance"],
"isPublished": true
}`
