### ISSUE TITLE
How create this elements? 

### ISSUE THREAD

**Issue by WilliamEstrela** [Requarks/wiki#2703]
**Question**

![image](https://user-images.githubusercontent.com/5386302/99070073-5b2a1380-258e-11eb-8479-ab1d9db87f40.png)

![image](https://user-images.githubusercontent.com/5386302/99070284-b22fe880-258e-11eb-818c-39b424a34cef.png)

How create ?

**Comment by Igorgro** [comment]
See here: https://docs.requarks.io/en/editors/markdown
