### ISSUE TITLE
How create this elements?

### ISSUE THREAD

**Issue by WilliamEstrela** [Requarks/wiki#2704]
**Question**
![image](https://user-images.githubusercontent.com/5386302/99070925-ee177d80-258f-11eb-9073-6f6351063ae4.png)

**Host Info (please complete the following information):**
OS: Linux - Alpine Linux (linux) 3.11.6 x64 (Heroku)
Wiki.js version: 2.5.159
Database engine: postgres 12.4
Runtime: Nodejs 14.12.0

**Comment by danvilar** [comment]
For the first one:

```
- [The Basics *New to Wiki.js? Learn how to use it and create your first page.*](/guide/intro)
- [Folder Structure & Tags *Learn how to categorize your pages for an easier browsing experience.*](/guide/structure)
- [Manage Pages *How to create, edit and manage your pages.*](/guide/pages)
- [Using Editors *Learn how to use the various editors.*](/editors)
- [Using Assets *How to upload and manage assets such as images and documents.*](/guide/assets)
{.links-list}```

As for the second:

```
## Blockquotes

### Tab {.tabset}

#### Usage

Using a **greater-than** symbol, followed by a space, before each line of text.

#### Shortcuts
- By selecting text, then clicking the ![Blockquote](/assets/ui/ui-markdown-blockquotes.png =x30){.radius-4} button in the toolbar.

#### Examples
...

```

**Comment by WilliamEstrela** [comment]
The second not works 
![image](https://user-images.githubusercontent.com/5386302/99120238-4757cf00-25d9-11eb-9706-a55f94ccf0f7.png)
