### ISSUE TITLE
I accidentally deleted a page, is there any way to restore the page？

### ISSUE THREAD

**Issue by ZhouJiaZhi** [Requarks/wiki#2707]
**Question**
I accidentally deleted a page, is there any way to restore the page？

**Host Info (please complete the following information):**
OS: macOS
Wiki.js version: [e.g. 2.5.170]
Database engine: [mysql 5.7.30]

**Comment by NGPixel** [comment]
Not via the UI (coming in a future release). The deleted content is still available in the database in the pageHistory table. You'll need to copy the content data you need and create a new page from it.
