### ISSUE TITLE
How to implement the generic OAuth2 authenticator?

### ISSUE THREAD

**Issue by Emaxoso** [Requarks/wiki#2709]
**Question**
Hi, I'm trying to implement the OAuth2 authentication to a generic OAuth2 server, but from the configuration of "Generic OpenID Connect / OAuth2" I can't choose what scopes to ask, It always fallback to "openid openid profile email" 

**Host Info**
OS: Debian 10, Docker latest
Wiki.js version: 2.5.170
Database engine: 10.5.5-MariaDB-1:10.5.5+maria~focal

**Comment by NGPixel** [comment]
The scopes are not editable from the UI. You can change them in `/server/modules/authentication/oidc` but that will apply to all openidc modules. You could instead duplicate that module folder and customize it however you like.

The default scopes are pretty standard for OpenIDConnect, not sure why you need to change them though...
