### ISSUE TITLE
Using/configuring other Syntax Highlighting options in the Visual editor?

### ISSUE THREAD

**Issue by tdkl** [Requarks/wiki#2713]
Hi,

I see that there's a limited set of Options in the Visual Editor what kind of Code Syntax highlighting there is. For instance, i'd wish to use "Bash" and "Powershell" and for that I have to use the Markdown editor, which you can't switch on the fly once selected. 

Is there an option to configure what the Syntax highlighting options are in the Visual editor? I'm interested in implementing Wiki.js in my Organization, but this is a deal breaker if it's not possible.

**Host Info (please complete the following information):**
OS: CentOS 8
Wiki.js version: 2.5.170
Database engine: Postgres 10.14

**Comment by pwnyprod** [comment]
for now you cant, i think this is an topic for the [canny feedback](https://requarks.canny.io/wiki) page.
