### ISSUE TITLE
error msg in console

### ISSUE THREAD

**Issue by ZhouJiaZhi** [Requarks/wiki#2714]
**Question**
When I start wikijs, the console reports an error
<img width="948" alt="截屏2020-11-16 23 03 59" src="https://user-images.githubusercontent.com/20750357/99268595-52706080-2860-11eb-8dfe-14efcbcba421.png">

**Host Info (please complete the following information):**
OS: macosx
Wiki.js version: 2.5.170
Database engine:  mysql 5.7。30

**Comment by NGPixel** [comment]
Possibly a hard connections limit on your database server.

**Comment by ZhouJiaZhi** [comment]
Yes, I checked the number of MySQL links, **wikijs** will use 6 links, and I used 3 by myself. When I set the max_connections of MySQL to 10, the console did not report any error messages.

1. Why does wikijs use so many links?
2. Is the number of links fixed?

<img width="1126" alt="截屏2020-11-17 01 21 19" src="https://user-images.githubusercontent.com/20750357/99285977-34602b80-2873-11eb-96c1-57d7d78e8773.png">
<img width="987" alt="截屏2020-11-17 01 23 11" src="https://user-images.githubusercontent.com/20750357/99286181-77ba9a00-2873-11eb-89b9-4cfa67ad45f7.png">

**Comment by pwnyprod** [comment]
you can chanage the number of active connections in the my.cnf in the mysql container (or where your sql server is). I think its okay for js to have this number of active connections because of many processes stay connected because of intervals.

**Comment by NGPixel** [comment]
Wiki.js is using a connection pool to improve performance, as multiple tasks can run in the background at the same time.

You can limit the max number of connections by editing your config.yml and set the `pool.max` option.
