### ISSUE TITLE
Is all wikijs data stored in the database?

### ISSUE THREAD

**Issue by ZhouJiaZhi** [Requarks/wiki#2715]
Is all wikijs data stored in the database?
If I want to migrate wikijs to another server, do I just need to migrate the data in the database, and then install a new wikijs on the new server to start it?

**Comment by seanecoffey** [comment]
Yes all relevant data is stored in the database. 
There is a guide for transfering between servers here: 
https://docs.requarks.io/install/transfer

**Comment by ZhouJiaZhi** [comment]
Great, Thanks
