### ISSUE TITLE
Restriction on Sharing and Printing the Page.

### ISSUE THREAD

**Issue by swapnil28490** [Requarks/wiki#2717]
**Question**
How to restrict the users from sharing and printing page?
I can see that every user can share and print, I cannot find any configuration setting to restrict the same.

**Host Info (please complete the following information):**
OS: [CentOS 7]
Wiki.js version: [2.5.170]
Database engine: [postgres 11]

Thanks in advance

**Comment by NGPixel** [comment]
You'll be able to hide these buttons in the upcoming 3.0.

However, that doesn't prevent anyone from printing the page using the system dialog or copy/pasting the link manually... This isn't something you can restrict.
