### ISSUE TITLE
LDAP Authentication

### ISSUE THREAD

**Issue by akitchen796** [Requarks/wiki#2724]
**Question**
I am trying to get LDAP authentication working on a wiki I'm building but I'm having no luck with it.
I've tried several different combinations for the various fields and every time I attempt an LDAP connection I'm hit with Invalid username/email and password. 
I've turned on the LDAP debugging option but get no LDAP logs in the server console so I don't know if it's even making a successful connection to the domain controller.
LDAP is working as we have other applications that use LDAP for user authentication and management,
See below for an anonymised screenshot of our setup
![image](https://user-images.githubusercontent.com/74665690/99548424-8ce91300-29b0-11eb-9d00-d2810e1302ba.png)

**Host Info (please complete the following information):**
OS: Windows Server 2019 Datacenter Version 1809 Build 17763.1518
Wiki.js version: 2.5.170
Database engine: Postgres 13.0

**Comment by NikoGrano** [comment]
I was able to setup it correctly. However, your issue is missing information about your LDAP structure, so its impossible to help you.

**Comment by avignat** [comment]
> I've turned on the LDAP debugging option but get no LDAP logs in the server console so I don't know if it's even making a successful connection to the domain controller.

Same here can't get it to work and don't know what fails

**Comment by NikoGrano** [comment]
It's pretty useless to post issues with "I have same issue, please help" without providing any useful details about the issue like current configuration for wiki.js/ldap directory.

**Comment by TonyBostonTB** [comment]
Apart from what @NikoGrano said, you should make sure that you're finding actual users with what you've configured there and try with 'ldapsearch' and the filters you used on the LDAP Server itself. 
One thing here is, that you're talking about configuring LDAP but this is Active Directory...

**Comment by avignat** [comment]
I have a similar config except for the cert part.
Even with log set to the maximum level and LDAP debug enabled there is nothing in the logs at all.
Where I'm lost it's that it is not the first service I want to connect to a LDAP but this time I have no lead to find out what's wrong.

**Comment by NikoGrano** [comment]
@avignat Configuration on Wiki.js side depends on the LDAP configuration used. Without understanding your LDAP structure there is no possible way to help you. 

Debugging, LDAPS on Wiki.js is somehow bugged at least based on my testing, so only correct way to get this working is by understanding your LDAP structure and Wiki.js configuration and work the issue based on that information.

@akitchen796 you don't seem to be active on this issue. If your issue has been resolved, please close.

**Comment by akitchen796** [comment]
I've managed to make it work with user@domain.local 
Search filter (userPrincipalName={{username}})
Unique ID Mapping userPrincipalName

I got curious and replicated the settings which were unchanged part from the above 2 fields instead using sAMAccountName and now it works with just username? I have no idea what's transpired there.

For anyone else reading, this guide I found was very useful in helping with the LDAP mappings for various server versions. [http://www.selfadsi.org/user-attributes.htm](http://www.selfadsi.org/user-attributes.htm)

So I now have 2 working LDAP auth and I'm very lost as to why it didn't work before. Top uses userPrincipalName bottom uses sAMAccountName
![image](https://user-images.githubusercontent.com/74665690/100082459-2b0d2b00-2e40-11eb-9c1d-b9519365c4df.png)

 I appreciate you nice guys trying to help, I'm going to go ahead and close this, now its all working

**Comment by NikoGrano** [comment]
I have no experience setting up LDAP on AD, but in case of FreeIPA, I have been using following:
```
(&(&(&(objectClass=posixAccount)(|(memberOf=cn=admins,cn=groups,cn=accounts,dc=example,dc=com)(memberOf=cn=wiki,cn=groups,cn=accounts,dc=example,dc=com)))(nsaccountlock=FALSE))(uid={{username}}))
```

This basically translates to;
((ObjectClass = PosixAccount **AND** (Member Of admins **OR** Member Of wiki)) **AND** (Account not Disabled) **AND** uid = username)

Like said, not sure how this works on AD, but would recommend to test your setup once more with disabled users and users without group (OU) to access to the Wiki.js Tough this all is dependent about your need after all.
