### ISSUE TITLE
link to file:///

### ISSUE THREAD

**Issue by fvassura** [Requarks/wiki#2727]
Hi,
I would like to link a file using [this](https://stackoverflow.com/q/32563078) syntax.

Why is it not possible?

I tried many combinations ( \<a href=...> tag too ) but no one works, it always choose http:// protocol

Host Info:
 - OS: Windows Server 2012 R2
 - Wiki.js version: latest
 - Database engine: default

**Comment by NGPixel** [comment]
Because it's a security issue and very bad practice, which the link you provided explains in details?
