### ISSUE TITLE
failed to authenticate LDAP

### ISSUE THREAD

**Issue by PabloMelo11** [Requarks/wiki#2729]
**Describe the bug**
I'm having an 'invalid email / username or password' error

And I saw that several issues are open with the same problem, would it be a bug in version 2.5.170?

 - OS:Ubuntu 20
 - Wiki.js version: 2.5.170
 - Database engine: postgres

![1](https://user-images.githubusercontent.com/38293087/99710708-a907b580-2a7f-11eb-9d46-d9326d9dd921.png)

![2](https://user-images.githubusercontent.com/38293087/99710717-ae650000-2a7f-11eb-9e16-e0d8c0e4b8fa.png)

**Comment by NikoGrano** [comment]
I was able to setup it correctly. However, your issue is missing information about your LDAP structure, so its impossible to help you.

**Comment by PabloMelo11** [comment]
I managed to adjust the admin user and password
