### ISSUE TITLE
Rendering issue

### ISSUE THREAD

**Issue by harold-whistler** [Requarks/wiki#2734]
**Describe the bug**
After i trying to publish new page it processing rendering long time and then giving this error:
`Network error: JSON.parse: unexpected character at line 1 column 1 of the JSON data`
However page going to be published
**To Reproduce**
1. Go to 'New page' and add content, press Save.

**Expected behavior**
Page going to be render quick as it contain markdown text only.

**Host Info (please complete the following information):**
 - OS: Ubuntu 20, Docker
 - Wiki.js version: 2.5.170
 - Database engine: included in docker compose

**Additional context**
Elastics search attached as search engine.

**Comment by NGPixel** [comment]
Are you using cloudflare or some other reverse-proxy?
