### ISSUE TITLE
Developer GraphQL returns "Get query missing"

### ISSUE THREAD

**Issue by kurtis318** [Requarks/wiki#2736]
### Actual behavior
GET query missing.
### Expected behavior
Should see GraphQL playground 
### Steps to reproduce the behavior
Sign in as Admin
Click on Administration cog icon
Expand Developer Tools in left navigator
Click on GraphQL
See this page:
![image](https://user-images.githubusercontent.com/8187747/99753203-6f4ca400-2aab-11eb-8183-250e0aeb69ef.png)

**Comment by kurtis318** [comment]
Sorry,

OS=Linux - Fedora (Thirty Three) 33 x64
Wiki.js version=2.5.170
Database engine=PostgreSQL 12.4
Node.js version=14.14.0

**Comment by NGPixel** [comment]
Are you loading `/graphql`?

**Comment by kurtis318** [comment]
Yes, I am loading /graphql from the Wiki.js interface I described above.  The URL is hostname:3000/graphql .

**Comment by liziker** [comment]
I have the same issue...

OS=Linux - Ubuntu Server (focal) 20.04 x64
Wiki.js version=2.5.170
Database engine=(PostgreSQL) 13.1 (Ubuntu 13.1-1.pgdg20.04+1）
Node.js version=14.15.4

**Comment by liziker** [comment]
I have the same issue...

OS=Linux - Ubuntu Server (focal) 20.04 x64
Wiki.js version=2.5.170
Database engine=(PostgreSQL) 13.1 (Ubuntu 13.1-1.pgdg20.04+1）
Node.js version=14.15.4
