### ISSUE TITLE
Question: Possible to login by request?

### ISSUE THREAD

**Issue by UrsLange** [Requarks/wiki#2737]
**Question**
Hey Folks,

I have a wiki.js deployment in place, currently using authentication by Keycloak, which again syncs it's users against our LDAP.
We have an Intranet that people use and where they authenticate, using the same LDAP data.

My question is now: Can I implement an authentication pipeline, such that users already logged into the intranet, when clicking on a specific link within said intranet are already logged in to the wiki without any further steps?

**Host Info (please complete the following information):**
OS: Debian 10, Docker
Wiki.js version: 2.5.170
Database engine: postgres 11

Deployment is in Docker (requarks/wiki:2 Image f439bc73d690)

Thank you!

**Comment by NGPixel** [comment]
Not at the moment, but you can follow this feature request:
https://requarks.canny.io/wiki/p/allow-forward-auth-sso-using-remote-user-header
