### ISSUE TITLE
It is possible to login with the ad always having the email registered ??

### ISSUE THREAD

**Issue by PabloMelo11** [Requarks/wiki#2738]
Hey guys, I wonder if I can log into wikijs using AD authentication, without necessarily having the email registered with AD?

For example, I have some users registered with AD, but without the email. If I try to log in with the user who doesn't even have the email registered, he fails because he doesn't have the email in AD.

Is there any way to log in even if the user does not have an email registered in AD?

OS: Ubuntu 20
Wiki.js version: 2.5.170
Database engine: POSTGRES

**Comment by NGPixel** [comment]
No, an email is always required to login.
