### ISSUE TITLE
Wiki.js as a service on windows

### ISSUE THREAD

**Issue by ankyfive** [Requarks/wiki#2739]
**Question**
Hello,
I would to to have wiki.js running on background task or as a service.
Could you please help me on how to do that ?
Is it possible to set it as a windows service ?
I saw pm2-service-install but I don't know how to use it.

Any help would be very appreciated
Regards

**Host Info (please complete the following information):**
OS: [Windows 10 64bits]
Wiki.js version: [2.5.170]
Database engine: [postgres 13]

**Comment by germeshausen** [comment]
I have looked for the same solutions today and was able to solve this task with nssm. 

http://nssm.cc

Steps I used:
`nssm install wiki`
- Set Path to node.exe
- Starting directory is the Wiki folder
- Argument the full path to the /server/index.js
Done, save and start service.

**Comment by NGPixel** [comment]
There are several options listed in the docs:
https://docs.requarks.io/install/windows#run-as-service

**Comment by ankyfive** [comment]
Thanks :-)
