### ISSUE TITLE
No ability to create nested topics on sidebar navigation

### ISSUE THREAD

**Issue by ARMOMaureen** [Requarks/wiki#2741]
**Describe the bug**
when defining my sidebar on a custom mode I wish to create a sub-topic to topic listing and can't seem to find this function.

**To Reproduce**
1. Go to 'Navigation'
2. Click on 'custom navigation'
3. Scroll down to 'Add' button
4. Select a page to show as a link and apply (post selecting a header)
5. Select any other page to add as an additional link and there is no option to place it under the link in step 4, only on the same level

**Expected behavior**
Ability to create another level of links (pages/topics) beyond the header and a link under it

**Screenshots**

**Host Info (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04, Docker]
 - Wiki.js version: [e.g. 2.0.1]
 - Database engine: [e.g. postgres 9.7, mysql 5.7]

**Additional context**

**Comment by NGPixel** [comment]
https://requarks.canny.io/wiki/p/dropdown-navigation-items
