### ISSUE TITLE
Regression: cannot access a tag by direct link if containing spaces or special chars

### ISSUE THREAD

**Issue by mkalam-alami** [Requarks/wiki#2743]
**Describe the bug**
Tags return no results if they have been directly accessed by their URL, and contain spaces or special characters (like accentuated letters). When the tag search page is loaded this way, the entire tag search page gets broken, not returning any results until navigating somewhere else.

**To Reproduce**
1. Create a page with a tag containing a space
2. View the page and click the tag link - to search all pages containing this tag
3. The search returns no results
Additional hints:
4. Toggle tags on the left menu
5. Watch the broken URL in the address bar (eg. `/t/tag with space/othertag?sort=title`)

Alternate scenario:
1. Go to the tags page
2. Click a tag containing a space, it will return correct results
3. Refresh the page with F5 to encounter the same bug

**Expected behavior**

Tag having spaces or accents do not break tag search.

**Screenshots**

![gif](https://user-images.githubusercontent.com/694508/99908031-62fd5c80-2ce0-11eb-9636-63979bee6256.gif)

**Host Info (please complete the following information):**
 - OS: Debian 10
 - Wiki.js version: 2.5.170 (freshly migrated from 2.2.51)
 - Database engine: PostgreSQL 11.9

**Additional context**
This worked fine on WikiJS 2.2.51.  
I suspect this is a problem with the handling of route parameters, if so it is probably an easy fix.  
If not easily reproduced it could be related to my migration from WikiJS 2.2.

**Comment by NGPixel** [comment]
You should avoid using spaces in tags... Usually you would use dashes (e.g. `tag-with-space`).

Still a bug but not a common use case.
