### ISSUE TITLE
How to upload asset using the GraphQL API.

### ISSUE THREAD

**Issue by dazzag24** [Requarks/wiki#2746]
**Question**
The GraphQL interface allows the creation of pages, but I cannot see how you can upload image assets?

The docs only show these end points:

![image](https://user-images.githubusercontent.com/1055831/99984964-9d7cfd00-2da5-11eb-9dd8-9032a0ff5dcc.png)

Any advice appreciated.

Thanks

**Comment by NGPixel** [comment]
Uploads are done via a REST API:

https://github.com/Requarks/wiki/blob/dev/server/controllers/upload.js#L13

**Comment by dazzag24** [comment]
Hi,

Thanks for replying.  Is this REST API for uploading images documented anywhere?

Thanks
