### ISSUE TITLE
how do I remove the rights to publish from a wikijs user?

### ISSUE THREAD

**Issue by jnading** [Requarks/wiki#2749]
**Question**
Describe in details what you are trying to achieve and where do you need guidance.

**Host Info (please complete the following information):**
OS: [e.g. Ubuntu 18.04, Docker]
Wiki.js version: [e.g. 2.0.1]
Database engine: [e.g. postgres 9.7, mysql 5.7]

**Comment by jnading** [comment]
I need to have different user rights in my Wikijs account. I want to base user levels on the ability to read, write and/or publish content. Right now, everyone in there can do anything How do I do this?

**Comment by NGPixel** [comment]
Have you read the docs?

https://docs.requarks.io/groups

**Comment by jnading** [comment]
Yes, but clearly it didn’t answer my questions. 

I have users, roles and page rules setup. Is it the page rules that are supposed to control this?

**Comment by NGPixel** [comment]
Yes, page rules define precisely which pages can be accessed and what actions can be performed on them.
