### ISSUE TITLE
Feature Request: Allow different language versions of same entry

### ISSUE THREAD

**Issue by johnnyshields** [Requarks/wiki#275]
It would be great if Wiki.js allowed different language versions of the same same page, similar to wikipedia. Ideally language should be selectable by user account and also by root path (/en/, /fr/, etc) for non-logged in users. If a page is not available in a given locale, the system should "fallback" to whatever locale is available (e.g. English, or based on some system rule)

From Wikipedia:

![image](https://user-images.githubusercontent.com/27655/31576415-2e4dd9c6-b135-11e7-9599-d737639f130e.png)

**Comment by NGPixel** [comment]
Please post feature requests on https://wikijs.canny.io/features
