### ISSUE TITLE
wiki.js get a continuously post request to /graphql

### ISSUE THREAD

**Issue by troyliu0105** [Requarks/wiki#2750]
**Question**
I deployed wiki.js on my server via docker/docker-compose. and from reverse-proxy log, I get a continuously post request to /graphql. Can I disable it?
![IMG_0143](https://user-images.githubusercontent.com/5518286/100042445-6dd20180-2e46-11eb-962c-8af0b5455383.jpg)

**Host Info (please complete the following information):**
OS: Archlinux x86_64
Wiki.js version: 2.5.170
Database engine: MariaDB (10.4.17)

**Comment by NGPixel** [comment]
No, this is the API...
