### ISSUE TITLE
Paste image from clipboard doesn't work

### ISSUE THREAD

**Issue by alexhome82** [Requarks/wiki#2767]
**Question**
Please help me, pasting an image from the clipboard does not work. The project is very large and we are trying to paste an image from the clipboard, nothing happens, we have to paste a lot of pictures. It works only if you first add it to the Word, then copy it from the Word and add it to the wiki.

**Host Info (please complete the following information):**
OS: Ubuntu 18.04
Wiki.js version: 2.5.170
Database engine: sqllite

**Comment by NGPixel** [comment]
Pasting images is not yet supported. This is coming in a future release.
