### ISSUE TITLE
File upload size

### ISSUE THREAD

**Issue by olaeke** [Requarks/wiki#2768]
**Question**
Is it possible to set the file upload size to "unlimited"? I have a need to upload files larger than what a 32bit signed integer allows in the file size setting. 

**Host Info (please complete the following information):**
OS: Windows 10 
Wiki.js version: 2.4.105
Database engine: postgres 12.3

**Comment by NGPixel** [comment]
No and even if it was possible, it's a terrible idea to upload such large files in Wiki.js. Use a proper storage location instead (like AWS S3, Azure Blob, etc.).
