### ISSUE TITLE
Export full history of pages change

### ISSUE THREAD

**Issue by nekuic** [Requarks/wiki#2778]
**Question**
Is there any way to see history of pages changing? Is there any way to get it though API call? 

**Host Info (please complete the following information):**
OS: Ubuntu 18.04, Docker
Wiki.js version: 2.5.159
Database engine: postgres 11.9

**Comment by jeresuikkila** [comment]
You could get that information through the [GraphQL API](https://docs.requarks.io/dev/api).

This example query (with the authorization header set as JSON in the bottom of the GraphQL playground) might be what you are looking for:
```graphql
query {
  pages {
    history(id: 4) {
      total
      trail {
        versionId
        versionDate
        authorName
        actionType
        
      }
    }
  }
}
```

If you don't know the id of the page you want to see history for, you could use a query like this:
```graphql

query PageList {
  pages {
    list{
      id
      path
      title
    }
  }
}
```

**Comment by nekuic** [comment]
I try your second query and get an error:

```
"extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: Forbidden",
            "    at field.resolve (/wiki/server/graph/directives/auth.js:47:17)",
            "    at field.resolve (/wiki/node_modules/graphql-extensions/dist/index.js:134:26)",
            "    at field.resolve (/wiki/node_modules/apollo-server-core/dist/utils/schemaInstrumentation.js:52:26)",
            "    at resolveFieldValueOrError (/wiki/node_modules/graphql/execution/execute.js:502:18)",
            "    at resolveField (/wiki/node_modules/graphql/execution/execute.js:460:16)",
            "    at executeFields (/wiki/node_modules/graphql/execution/execute.js:297:18)",
            "    at collectAndExecuteSubfields (/wiki/node_modules/graphql/execution/execute.js:748:10)",
            "    at completeObjectValue (/wiki/node_modules/graphql/execution/execute.js:738:10)",
            "    at completeValue (/wiki/node_modules/graphql/execution/execute.js:626:12)",
            "    at /wiki/node_modules/graphql/execution/execute.js:527:16",
            "    at runMicrotasks (<anonymous>)",
            "    at processTicksAndRejections (internal/process/task_queues.js:93:5)",
            "    at async Promise.all (index 0)"
          ]
        }
      }
```

Is it a problem with configuration? How can we solve this?

**Comment by jeresuikkila** [comment]
Your configuration is fine. The problem is you're not authenticated. The server needs to know you are allowed to see these pages and to do that you need to send the "Authentication" header. To get an API token, follow the instructions in the [documentation](https://docs.requarks.io/dev/api) under Authentication. Then add it to your query by expanding the "HTTP Headers" section of your GraphQL expolorer like this: 
```json
{
  "Authorization": "Bearer eyJhbGc...aXczt18H6437W"
}
```

**Comment by nekuic** [comment]
My task is - I need to see all changes from all pages from wikijs. 

So, If your workaround is (from GrafQL):
1. Get page id from PageList query.
2. See changes from every page one-by-one. 

Is it correct? 

Wikijs don't have an API to get a list of all changes from all pages. Correct?

**Comment by jeresuikkila** [comment]
I'm not an expert or Wikijs developer, so I can't be sure but that is what I would suggest trying as it would get the job done.

**Comment by NGPixel** [comment]
You can't see the history for all pages at once, no. There's no resolver for that at the moment.

The best solution however would be to connect a git repository to your wiki. You can then view history across the whole repository from there.
