### ISSUE TITLE
How to remove social buttons and others

### ISSUE THREAD

**Issue by WilliamEstrela** [Requarks/wiki#2781]
**Question**
How to remove this elements

![image](https://user-images.githubusercontent.com/5386302/101024904-8bdce780-3553-11eb-8af4-2167732bcf3a.png)

Host Info (please complete the following information):
OS: Linux - Alpine Linux (linux) 3.11.6 x64 (Heroku)
Wiki.js version: 2.5.159
Database engine: postgres 12.4
Runtime: Nodejs 14.12.0

**Comment by NGPixel** [comment]
Not possible at the moment. Planned for v3.
