### ISSUE TITLE
Impossible to set a /public path readable by guest

### ISSUE THREAD

**Issue by luke7263** [Requarks/wiki#2788]
Hi,

I've done exactly what I read on the docs :

- gave all read access to guest group
- create a /public/test page
- grant all read access to the path beginning by /public

But guest user cannot read the public/test page.. :( .. If I grant exactly to the path /public/test, neither not working.
The only thing that works is granting all read access to the path /, but in that case, guest can read everything.

But : if I deny access to /public path for a authenticated user, it works : that real user cannot see /public page(s), that's perfect.

Conclusion : there might be a bug with guest group management.

Best regards.

**Comment by luke7263** [comment]
Sorry,

I use MariaDB (mysql 15.1) on Debian (10.6)
And I've used  last Docker version to install Wiki.js as described on the docs, no problem for this, Docker image is requarks/wiki:2.5

Thanks.

**Comment by chris-hs** [comment]
I am using Wiki.js version 2.5.170, and I have a similar setup with guest permissions, and it's working for me. Here is how I have my **Guest** group permissions set up. I am curious how your setup differs from mine.

Allowed **Permissions**
- read:pages
- read:assets
- read:comments
- write:comments

**Page Rules**
I have a rule for *Path Starts With...* `/helpdesk` (in your case it would be `/public`). These are the allowed permissions for that rule:
- read:pages
-  read:assets
- read:comments
- write:comments

I created a test page at `/helpdesk/test/test`, and a guest user was able to access it.

**Comment by luke7263** [comment]
I just set rights exactly as you did, but guest user is always redirected to login page. 

Check http://wiki.place67.com:3000

**Comment by chris-hs** [comment]
OK, that happens if the guest user does not have permissions to access to the `/home` page. I have a page rule to allow guest access to pages tagged `Public`, and I added that tag to my home page. Then the guest user is not immediately redirected to the login page. 

The guest user should still be able to access pages in the `/public` folder even without being able to access the home page. My guest user could still reach pages under `http://wiki.company.com/en/helpdesk/` even if they were redirected to login if trying to access `http://wiki.company.com/`

**Comment by luke7263** [comment]
Got it, I just set access rights to /home, it's fine.
About media managing, there is something not trustful at all : a user A member of group G1 must first load a file (image for example) to display it in its post, ok. But a user B member of group G2 will be able to attach that same file to its own post. 
So wiki.js cannot be used since media are shared among everybody whatever the group they belong to.
My opinion is a file should be directly inserted in a post without the use of an media space, first for security and confidential reasons, second because most of the time a media is used one time only.
Anyway thanks for the great work and your support.

**Comment by NGPixel** [comment]
@luke7263 Media assets are still governed by page rules. You can't see or attach assets you don't have access to.
