### ISSUE TITLE
Reduze size of wiki loading: 7.8MB of assests loaded everytime (fresh install)

### ISSUE THREAD

**Issue by kalak-sudo** [Requarks/wiki#2792]
**Question**
Hi! I have just installed it on my system, and the default template is 7.8MB in size when the page is fully loaded.

How can I reduce the size and have a more SEO-compatible and lightweight wiki? For example:

_assets/js/admin.js?1603683027 -> 1.3MB
_assets/js/app.js?1603683027 -> 2.2MB

Is there any way to use a "minimal theme" or reduce the size of the files loaded, in any way? 

Thanks! 

**Host Info (please complete the following information):**
OS: Debian 10
Wiki.js version: 2.5.170
Database engine: postgres 11.9

**Comment by NGPixel** [comment]
This is being addressed in the upcoming v3.

Note that these files are not loaded every time, but only once. They are cached in your browser afterwards.
