### ISSUE TITLE
Network error: Response not successful: Received status code 413

### ISSUE THREAD

**Issue by beerygaz** [requarks/wiki#2797]
**Question**
I get the above error when trying to save a large page.  The page is large due to an innserted draw.io image, but removing the tags and just pasting the large block of (what appears to be) base64 text into the page generates the same error.  The total size of the page is 1.2Mb

I have set the Admin/Security/MaxUploadSize to 5242880 bytes (5Mb) but still see this error.

I have eliminated my reverse proxy (Trefik) by bypassing the proxy to no avail.

I can confirm that if I reduce the page size from 1.2Mb to 770k it will save, so the issues exists somewhere in that range, but I don't know where that constraint exists.

**Host Info (please complete the following information):**
OS: Docker
Wiki.js version: 2.5.170
Database engine: git

**Comment by NGPixel** [comment]
the max upload size is for assets only, not for page content, so changing it won't have any effect.

The body parser for requests is limited to 1Mb. Draw.io diagrams can quickly cause the page to go over that limit. It will be addressed in a future release, but in the meantime you can increase the limit manually by changing this line:

https://github.com/Requarks/wiki/blob/a1f1cd7356ddc2ba9054aa0f39b0b9f3f43ce3f8/server/master.js#L94

**Comment by bestwnh** [comment]
Hi @NGPixel,

I like to contribute this issue. It prevents me to create some pages with base64 images. And my company use it with AWS so it is a bit hard to modify the code. So I just hope I can make sure this can be config in the next version.

But seems like I need to request access to the translation web service first for the locale files before local development right? I tried gitter but all I see is a 404 page. So could you tell me what do I need to do? My gitter account link from my GitHub so just feel free to contact me.

**Comment by JohnnyDevCraft** [comment]
Is there an easy way to handle this in a running container, or will this require a redeploy of a new image?

**Comment by JohnnyDevCraft** [comment]
So I updated the master.js to the following:

`app.use(bodyParser.json({ limit: '10mb' }))`

and I'm still getting a 413 when I try to attach a 1.2 MB PDF to an article.  Any thoughts on what I should try next?

**Comment by davidib2001** [comment]
Same here, tried 
app.use(bodyParser.json({ limit: '50mb' }))
with same result.
Anybody?  Th elack of being able to use visual ais in wiki really limits it's usefulness

**Comment by TheLouD1** [comment]
not sure why @NGPixel closed this as completed on Jan 14, 2023 as it's still very much an issue ??

just like @JohnnyDevCraft before me : I tried to change the value from 1 to 20mb per pages but nothing changed... actually I have a "client max body size 50M" showing at the bottom of all my pages now, even tho there is no such line in the master.js file so im terribly confused on where this comes from (made an issue for this as a discussion not a pull)

but my main issue here is that the limit still is 1mb even after swapping from 1 to 20 ! all I find online would be a nginx issue but this is a wiki is host locally, not available from outside and therefore I do NOT use any reverse proxy

any idea on how to *actually* to increase the limit ?

**Comment by florent4014** [comment]
Wanted to user a big drawio figure but it seems that when it's larger than 5MB~ wiki.js just won't save it.
Instead throwing : "Network error: Response not successful: Received status code 413" 

I tried the above workarounds but none worked. That's so frustrating to not being able to illustrate things in a documentation.
