### ISSUE TITLE
Navigation disappearing

### ISSUE THREAD

**Issue by intralizee** [Requarks/wiki#280]
I'm a new user of wiki.js and I really like the visual design & functionality.

Thank you for the development. 🙂

I'm stumped on this issue because it seems like many users would not be able to navigate using wiki.js at this current moment for sites using the framework.

### Actual behavior

Navigation disappears when browser is half my screen in width on my MacBook Pro.

I'm assuming this design is intentional but I'm not able to find the way to view the wiki's navigation when it happens. 

### Expected behavior

I'm guessing there should be a button created somewhere where a user may toggle the navigation and fill up the screen when "screen real-estate" is limited.

### Steps to reproduce the behavior

Resize browser width to half screen.

Mobile appears to have issue of no navigation panel as well.

**Comment by NGPixel** [comment]
This is standard behavior on Wiki.js 1.x as there's no mobile menu. This will be added in 2.0.

**Comment by intralizee** [comment]
Awesome, I'm looking forward to the feature. 
In the meantime I'll just create a navigation by links in the wiki.
