### ISSUE TITLE
Unclear docs for Docker

### ISSUE THREAD

**Issue by gempain** [Requarks/wiki#281]
In the [database section](https://docs.requarks.io/wiki/install/database) of the documentation, it would be nice to indicate to users using the `docker-compose.yml` that the mongo url to use is as follows:

```
db: mongodb://wikidb:27017/wikijs
```

where `wikidb` is the name given to the mongo service in the compose file.

Credits to [a SO thread](https://stackoverflow.com/questions/34711642/docker-mongo-image-connection-refused-from-other-container).

Also note that the [example config file](https://github.com/Requarks/wiki/blob/master/config.sample.yml) mentions that you can use an environment variable to define the db url:

```
# ---------------------------------------------------------------------
# Database Connection String
# ---------------------------------------------------------------------
# You can also use an ENV variable by using $ENV_VAR_NAME as the value

db: mongodb://localhost:27017/wiki
```

but I haven't been able to find out how to use such variable in my docker compose file. Would it possible to clarify the docs on this aspect too ?

Keep up the good work !

**Comment by NGPixel** [comment]
I added info concerning the db in the docker-compose page:
https://docs.requarks.io/wiki/docker/compose

**Comment by gempain** [comment]
Beautiful :) Thanks a lot for the clarification !

@NGPixel Could you tell me (I don't mind opening a new issue, but it might just be quicker to do it here) how to use an environment variable to declare the db parameter, as the example config file mentions ?

**Comment by NGPixel** [comment]
Simply use `$(VARIABLE_NAME)` as the value of any parameter.
