### ISSUE TITLE
Button labels and single sign on

### ISSUE THREAD

**Issue by navara99** [Requarks/wiki#2840]
Hello, 

I have installed wiki.js and am hoping you can help me with 2 issues. 

The first issue is that all of the buttons are labelled in an odd way. For example in this image the button should just be apply but it says actions.apply. This is the case with all buttons. 

![PXL_20201218_184638715~2](https://user-images.githubusercontent.com/76225365/102649805-dce60180-4137-11eb-8743-a4475bc91553.jpg)

My second issue is that I can't seem to find a way to enable single sign on so that everyone in the active directory can access the wiki without having to log on manually. I am not sure if you guys have this feature available yet. Please let me know if this is possible.

Thank you for taking the time to read this and I hope you guys can help me out with this.

OS : Windows 10,
Wiki.js Version : 2.5.170,
Database engine : PostgreSQL version 13.1
Node.js version 14.15.1

**Comment by navara99** [comment]
> You haven't provided the required info about your host! (OS, Wiki.js version, Database engine)

Windows 10, Version 2.5.170, Postgresql

**Comment by NGPixel** [comment]
Wiki.js needs access to the internet to download locale files.

If that's not possible, you need to manually sideload the locale files:
https://docs.requarks.io/install/sideload

SSO is not available yet.
