### ISSUE TITLE
"Network error: Unexpected token < in JSON at position 0"

### ISSUE THREAD

**Issue by openspork** [Requarks/wiki#2842]
When I try to import from a v1 wiki.js via git, I get this error "Network error: Unexpected token < in JSON at position 0"

I get the same error when going to Storage > "Import Everything"

This are the errors I get in my browser console:
![image](https://user-images.githubusercontent.com/24689334/102677356-dfa41f00-4156-11eb-8658-bc2379c26a03.png)

The import partially completes -- most pages are imported.  Some pages, however, show in the local repo (the git clone seems to be fine) but never end up in the postgres database.  Then I click links to them in the wiki they prompt to be created.

Running:
**Host Info (please complete the following information):**
 - OS: Debian 10
 - Wiki.js version: 2.5.170
 - Database engine: PostgreSQL 13.1
 - Node.js version: 15.4.0, 14.14.3

This issue takes place both with and without an nginx reverse proxy.

Thanks!

**Comment by NGPixel** [comment]
This is simply the reverse proxy (or your browser) timing out, however the process still continues in the background, so you can ignore the error.

Make sure all filenames respect the naming rules (kebab-case). Check the process logs for any error. Pages that fail to render will not be imported.
