### ISSUE TITLE
Followed all of the steps to install wiki.js but getting error on last step.

### ISSUE THREAD

**Issue by Enukora** [Requarks/wiki#2850]
I followed all of the steps outlined for the installation instructions for wiki.js but when I try to perform the final step of running Wiki.js using the command "node server" I am getting an error saying 'Module_Not_Found.  Can someone assist me with what I may be doing wrong here?

<img width="597" alt="Screen Shot 2020-12-21 at 7 27 34 PM" src="https://user-images.githubusercontent.com/76460478/102841646-98ba6180-43c2-11eb-8269-103da07fd291.png">

Thank you

**Comment by Enukora** [comment]
I am using MacOS, latest version of Wiki.js, Database engine: PostgreSQL on Google Cloud Platform (GCP)
<img width="597" alt="Screen Shot 2020-12-21 at 7 27 34 PM" src="https://user-images.githubusercontent.com/76460478/102841646-98ba6180-43c2-11eb-8269-103da07fd291.png">

**Comment by NGPixel** [comment]
Which version of node are you using?

**Comment by Enukora** [comment]
I downloaded version 15.5.0

<img width="530" alt="Screen Shot 2020-12-22 at 5 06 28 PM" src="https://user-images.githubusercontent.com/76460478/102944446-0b394900-4478-11eb-9d38-074ee0a5f35c.png">

**Comment by NGPixel** [comment]
You need to run `node server` from the `wiki-js` folder.
