### ISSUE TITLE
BUG: MathJax renders correctly in preview, but incorrectly in rendered page

### ISSUE THREAD

**Issue by iosengineer** [Requarks/wiki#2851]
**Describe the bug**
I'm having an issue in rendering where MathJax renders perfectly in edit mode, but appears as blanks in view mode. Any ideas?

**To Reproduce**
1. With MathJax enabled for rendering...
1. Create a page with MathJax in markdown mode. For example:

```
# Controller

## Fabrication

The plating current calculations:

$$
  PlatingCurrent_{max}(A) = Area(m^2) * 98.43A\\ 
  PlatingCurrent_{min}(A) = Area(m^2) * 32.81A
$$

give a maximum plating current of $342.53mA$ and a minimum of $114.17mA$ for the board area of $0.00348m^2$ (87mm x 40mm), using the premixed plating bath.
```

1. Note that in the editor preview, this is rendered correctly
1. Save the page
1. Note that in the actual rendered page, this is not rendered correctly

**Expected behavior**
Rendered page should match the editor preview 

**Screenshots**

- ![Editor preview](https://canny.io/images/248686224dcd7a9383fb8a5b585a5df4.png) *correct editor preview*
- ![Rendered page](https://canny.io/images/665944a3687086ece9ced71cd19c75f9.png) *erroneous rendered page*

**Host Info (please complete the following information):**
 - OS: MacOS Catalina AND Ubuntu 20.10
 - Wiki.js version: 2.5.170
 - Database engine: postgres 12

**Additional context**
- Browser: Nativefier v8.0.7

**Comment by NGPixel** [comment]
Try to disable **Sanitize HTML** under Admin > Rendering > HTML > Security. Then re-save your page.

**Comment by iosengineer** [comment]
Yep. That fixed it.

Thanks,
Adam

**Comment by scienceasdf** [comment]
Another alternative method is to disable server mathjax renderer, inject mathjax.js in the page instead to render formulations in the client side.

**Comment by Filip-K** [comment]
The issue is still there in the newest wiki.js. The workaround suggested by @NGPixel works, but is not intuitive nor easy to find. Should we maybe add it to do the docs? (Probably [here](https://docs.requarks.io/en/rendering) under Mathjax, where the incompatibility with Katex is already mentioned.)
