### ISSUE TITLE
Security Bug! Multiple Slack Authentication Strategies Use Only the Last Defined Client ID and Secret

### ISSUE THREAD

**Issue by darrengoldner** [Requarks/wiki#2854]
**Describe the bug**
When more than one Slack Authentication Strategy is configured, only the last configured authentication strategy's client ID and secret are used. This appears universal for any installed/configured Slack authentication strategy and represents a significant risk of security breach if the last configured authentication strategy is a published/non-private Slack app. I.e., if the last installed Slack authentication strategy includes a client ID and secret for a Slack app that is published [whether or not it's in the slack app directory, it's accessible to all workspaces]: all Wiki users who authenticate via ANY slack strategy will authenticate via the last installed App against the workspace they choose and be provisioned/authorized to that last strategy's groups.

**To Reproduce**
1. Install one Slack authentication strategy A with App A in Workspace A.
2. Test, confirm that authentication strategy works.
3. Install second Slack authentication strategy B, with App B in Workspace B.
4. Test, confirm the second strategy works for authentication versus workspace B.
5. Attempt to login via first authentication strategy A, see that it is attempting to authenticate via the App created in Workspace B, produces a invalid_team_for_non_distributed_app error.
6. Publish the Slack App B [not necessary to actually list it on the Slack Directory]
7. Attempt to login/authenticate via Strategy A: See successful authentication, but **Authorization based on Strategy B**

**Expected behavior**
When a user attempts to login via a specific authentication strategy, that strategy's client ID and secret are what's used to authenticate against Slack. Then, that strategy's authorization/group provisioning is what is applied to the user.

**Screenshots**

**Host Info (please complete the following information):**
 - OS: Ubuntu 18.04, Docker
 - Wiki.js version: 2.5.170
 - Database engine: Postgres 11.8
 - Operating System - Docker Container (Linux)

**Additional context**

**Comment by NGPixel** [comment]
Duplicate of #2554
