### ISSUE TITLE
SSL Certificates

### ISSUE THREAD

**Issue by robert-danowski** [Requarks/wiki#286]
Are you thinking about adding possibility of using SSL certificates (https protocol instead of http) it could be important especially when you have server and client part on different machines.

**Comment by NGPixel** [comment]
I don't think Wiki.js should handle https to be honest.
This is something better handled by a reverse proxy, such as nginx.

There's an article with a sample configuration in the docs:
https://docs.requarks.io/wiki/admin-guide/setup-nginx#https-reverse-proxy-example

I'll most likely write a more complete tutorial in the future.

**Comment by robert-danowski** [comment]
Thanks for quick answer.

**Comment by aam1r** [comment]
Is this something that can be reconsidered for v2.0?

For example, a built-in Let's Encrypt SSL option would be awesome

**Comment by NGPixel** [comment]
V2 has support for SSL. Let's encrypt could be added later on.
