### ISSUE TITLE
Logged in user gets a prompt to log in on an Unauthorized page.

### ISSUE THREAD

**Issue by jtagcat** [Requarks/wiki#2862]
**Describe the bug**

Steps to reproduce the behaviour:
1. Foo is in group Tomato.
1. Tomato disallows access to pages tagged 'no-tomato'.
1. Foo can see a page tagged with 'no-tomato'.
1. When Foo (logged in!) clicks on the page listing item (or opens via link), they get 'Unauthorized', and a link to log in (they're already logged in).

**Expected behaviour**
Don't offer to re-login. Just stick with back button, or 'insufficient privileges' or something.

**Host Info (please complete the following information):**
 - OS: Docker
 - Wiki.js version: 2.5.170
 - Database engine: 10.5.5-MariaDB-1:10.5.5+maria~focal

**Comment by jtagcat** [comment]
Downstream bug: https://git.k-space.ee/k-space/overnode-cluster/issues/71

**Comment by NGPixel** [comment]
The button says "Login As..." which offers the possibility to login as another user with more priviledges.

Closing as this behavior will no longer apply in the upcoming v3.
