### ISSUE TITLE
User in multiple groups, one allowing, and other disallowing access.

### ISSUE THREAD

**Issue by jtagcat** [Requarks/wiki#2863]
**Describe the bug**
1. Foo is in group Tomato, and Beans.
1. Bar is in group Tomato.
1. Tomato disallows access to pages tagged 'no-tomato'.
1. Beans allows access to pages tagged 'no-tomato'
1. Both Foo and Bar cannot access a page tagged 'no-tomato'.

**Expected behavior**
 - Foo can access page tagged 'no-tomato'. Bar cannot access that page.

**Host Info (please complete the following information):**
 - OS: Docker
 - Wiki.js version: 2.5.170
 - Database engine: 10.5.5-MariaDB-1:10.5.5+maria~focal

**Comment by jtagcat** [comment]
Downstream bug: https://git.k-space.ee/k-space/overnode-cluster/issues/71

**Comment by NGPixel** [comment]
This is the expected behavior. A DENY rule will always override an ALLOW rule on the same specificity level.

https://docs.requarks.io/groups

**Comment by jtagcat** [comment]
More specific path overrules a more generalized one. Can a 'more specific tag' override an other tag or something?

This may be expected behaviour, but when not using paths, and basing your perms on tags, multi-group structure is desired.

**Comment by NGPixel** [comment]
This is not possible at the moment. All tags have equal specificity. Submit a [feature request](https://requarks.canny.io/wiki).
