### ISSUE TITLE
Wiki.js seems to show the wrong expiration date for the SSL cert

### ISSUE THREAD

**Issue by JetForMe** [Requarks/wiki#2867]
**Describe the bug**
Wiki.js seems to show the wrong expiration date for the SSL cert. In this screenshot you can see it thinks it's 1/2/2021, but really it's 3/26/2021. The cert recently renewed, but the previous one was set to expire 05 Jan 21 21:30 +0000.

![Screen Shot 2020-12-26 at 18 59 50 ](https://user-images.githubusercontent.com/401600/103163034-4061d600-47ad-11eb-86a5-81c24db9edbf.png)

## Info

Version: 2.5.170
OS: Docker Container (Linux)

**Comment by ravenzachary** [comment]
I am seeing this same bug on my installation. I will open a new bug and cross-reference here since this bug was marked invalid based on the required fields.

**Comment by ravenzachary** [comment]
I have added the ticket here: https://github.com/Requarks/wiki/issues/2945
