### ISSUE TITLE
broken text

### ISSUE THREAD

**Issue by Lemon553311-dev** [Requarks/wiki#2869]
![image](https://user-images.githubusercontent.com/60439353/103173237-39e16600-4862-11eb-9114-6748f656a2c5.png)
What is wrong and how do I fix this?

also I am getting this error in console
getaddrinfo EAI_AGAIN

**Comment by NGPixel** [comment]
Make sure the node process has access to the internet.

If that's not possible, you need to sideload locale files manually:
https://docs.requarks.io/install/sideload
