### ISSUE TITLE
Local fresh installation does not work

### ISSUE THREAD

**Issue by mredigonda** [Requarks/wiki#287]
### Actual behavior

![screenshot-2017-10-24 personal wiki](https://user-images.githubusercontent.com/25920622/31969486-29cda63e-b8eb-11e7-9e21-91fcc5c10af6.png)

### Expected behavior

I expected a wiki like all others I've seen using wiki.js.

### Steps to reproduce the behavior

I just installed it (all the checks were okay) on my machine (not in a remote server) and it looks like this, and it's also not functional since I can't do anything.

**Comment by NGPixel** [comment]
Your `host` parameter in wrong in your `config.yml`

https://docs.requarks.io/wiki/troubleshooting#weird-display-no-styling
