### ISSUE TITLE
App's CSS file invalid path after custom build on Linux production server

### ISSUE THREAD

**Issue by clement-or** [Requarks/wiki#2875]
**Describe the bug**
First, I'm not a webpack expert, I've used it a bit but that's about it.
When you build your own `assets` folder (using [manual build instructions](https://docs.requarks.io/dev#manual)), if you upload it to a **Linux machine** (with latest Wiki.js linux version), the `app.<number>.css` file won't be found, as the `<number>` is wrong. 
It results in broken styles (for example, dark mode becomes grey).

EDIT : It happens too on Windows.
I am currently trying to reproduce the issue using Docker, I'll post the results a bit later.

**To Reproduce**
1. Make a clean Wiki.js install on your Linux machine. Let's call it `wiki-prod`
2. Somewhere else, clone the repo and call it `wiki-dev`
3. Setup wiki-dev according to manual installation
4. (optional) Run `yarn dev`: the styles aren't broken
5. `yarn build` on wiki-dev
6. `mv wiki-dev/assets wiki-prod/assets`
7. `node-server` on wiki-prod
8. When you go to localhost:<port>, styles are broken You can see an error in your browser console stating that app.<number>.css is missing.

**Expected behavior**
No error, all styles work.

**Host Info (please complete the following information):**
 - OS: KDE Neon 5.20.2 and Debian 4.19.152-1
 - Wiki.js version: 2.0.0 (official build)
 - Database engine: MySQL, MariaDB

Hope this is helpful

**Comment by clement-or** [comment]
After a bit of investigation : 
* The issue also happens using Docker, though I'm not used to Docker so I might have messed up
* The issue only happens when using a custom theme. Though the theme perfectly works in dev mode, it breaks on production.

**Comment by NGPixel** [comment]
You can’t copy just the assets folder and expect it to always work. Views are generated to load the corresponding files under /server/views. These need to be copied as well.

**Comment by clement-or** [comment]
I think this should be specified on [this part of the docs](https://docs.requarks.io/dev/themes#manually).
> yarn build
> This will generate a new folder named assets. Copy + Paste this folder to your production server and restart your wiki.

**Comment by NGPixel** [comment]
Added.
