### ISSUE TITLE
CKEditorError: ob is undefined

### ISSUE THREAD

**Issue by moksamedia** [Requarks/wiki#2876]
**Describe the bug**
I'm seeing a lot of errors in the web console. "CKEditorError: ob is undefined." Seems to be triggered by deleting newlines/empty lines. See screenshot below. I add some simple content and put cursor to the beginning of the line or an empty line and delete.

Testing some more. This definitely seems to be a problem with blank lines. If I press enter a few times and backspace the blank lines, I get the errors. Interestingly, if I go to the top of the blank lines and use the delete button (to delete the blank lines from "above"), I don't seem to be able to get this error.

Also, I have reproduced this using both the @requarks/ckeditor5 dependency and an separate local ckeditor5 dependency. When I try the sample/index.html editor in the local ckeditor5, I cannot reproduce this issue.

**Screenshots**
![Screenshot from 2020-12-31 20-51-07](https://user-images.githubusercontent.com/1304311/103433646-05dfab00-4baa-11eb-8040-13ddd8973ffe.png)
![Screenshot from 2020-12-31 20-51-16](https://user-images.githubusercontent.com/1304311/103433647-08420500-4baa-11eb-9d6b-e96f20732405.png)

**Host Info (please complete the following information):**
 - OS:PopOS 20.10, docker
 - Wiki.js version: 2.5.17
 - Database engine: postgres

**Comment by moksamedia** [comment]
Also getting a very similar "undefined has no properties" error.

![Screenshot from 2021-01-01 09-49-42](https://user-images.githubusercontent.com/1304311/103443713-c4d1b000-4c16-11eb-950c-783f57031c15.png)

**Comment by NGPixel** [comment]
Are you using Firefox? Have you tried another browser?

**Comment by moksamedia** [comment]
Yes I was. And yes, using Chrome fixed it. What's the problem with firefox?

Thanks.

**Comment by NGPixel** [comment]
See #2758
