### ISSUE TITLE
Can't login to admin account

### ISSUE THREAD

**Issue by Sillanium** [Requarks/wiki#288]
### Actual behavior
When I am entering admin-login creds i have an error "Invalid Login"
### Expected behavior
When I am entering admin-login creds i gets admin page
### Steps to reproduce the behavior
Go to GitHub Repository https://github.com/Requarks/wiki
In section "Cloud Install" click "Deploy to Heroku"
Fullfill form
Go to Login page
Try to login
-------------------------------------
I have try typing email from Config Vars, many different combinations. Including admin/admin and other combinations. I also have try run node wiki configure via heroku-cli. But get an error "ENOENT no such file or directory, stat '/app/assets/favicon.ico'".

**Comment by NGPixel** [comment]
The default password is `admin123`, as specified on the install page.

**Comment by tao** [comment]
Which install page and where does it say `admin123`? I've read the docs and searched for this password too and the only one I can find is `MartyMcFly88`.

I installed via the `Deploy to Heroku` button and `admin123` does indeed work with my email address however I only found that out from issue...

**Comment by NGPixel** [comment]
![image](https://user-images.githubusercontent.com/15522395/32082830-42c791ca-ba8c-11e7-99e8-d3555dcac7a0.png)

Not the most obvious I agree, but it's there.

Wiki.js 2.0 will no longer rely on environment variables to create the admin account so this will no longer be an issue soon.

**Comment by FabianTe** [comment]
But what is the default username?!

**Comment by FabianTe** [comment]
It's the `WIKI_ADMIN_EMAIL` ENV for the Dockerfile.

**Comment by cgwic** [comment]
simple workaround for local installation on the first run is to:
set ```WIKI_ADMIN_EMAIL``` environment var
and use this diff
```diff
diff --git a/server/libs/auth.js b/server/libs/auth.js
index c9b7e12..a795ca7 100644
--- a/server/libs/auth.js
+++ b/server/libs/auth.js
@@ -280,7 +280,7 @@ module.exports = function (passport) {
         })
       }
     }).then(() => {
-      if (process.env.WIKI_JS_HEROKU) {
+      if (process.env.WIKI_ADMIN_EMAIL) {
         return db.User.findOne({ provider: 'local', email: process.env.WIKI_ADMIN_EMAIL }).then((c) => {
           if (c < 1) {
             // Create root admin account (HEROKU ONLY)
```

If wiki db already exists: drop it and start wiki again.

Also workaround is to create admin user, based on info in [auth.js](https://github.com/Requarks/wiki-v1/blob/da0452efbba697c179d895f94eaafff7e577db91/server/libs/auth.js#L288)
