### ISSUE TITLE
laggy key repeat in Safari browser

### ISSUE THREAD

**Issue by bitworm** [Requarks/wiki#289]
When editing a wiki page in Safari, displayed characters lag behind keystrokes.  I have a rather fast key-repeat rate and notice this most when holding down [space] or [del].

This is not observed in the search bar or on Chrome.

**Comment by NGPixel** [comment]
Can you replicate the issue here?
https://simplemde.com/

**Comment by bitworm** [comment]
@NGPixel Yes, I can reproduce it there.  It also seems to worsen with longer files (even blank space).

**Comment by NGPixel** [comment]
Report this issue in SimpleMDE repo then:
https://github.com/sparksuite/simplemde-markdown-editor
