### ISSUE TITLE
Error when viewing source of previous page revision

### ISSUE THREAD

**Issue by Chrisc-c-c** [Requarks/wiki#2890]
**Describe the bug**
When trying to view the source of a previous version of a page, the source fails to load and I instead receive the following error page:

Oops, something went wrong...
/wiki/server/views/source.pug:7 5| block body 6| #root > 7| page-source( 8| :page-id=page.id 9| locale=page.localeCode 10| path=page.path The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined

**To Reproduce**
1. Open a wiki page.
2. Click on History.
3. Click the three dots next to a page revision.
4. Click "View Source".

**Expected behavior**
Revision source should be shown

**Host Info (please complete the following information):**
 - OS: Docker
 - Wiki.js version: 2.5.170
 - Database engine: Postgres 11.7

**Comment by mihailim** [comment]
Confirming, this happens with the non-Docker version as well.

* OS: Ubuntu 18.04
* Wiki.js version: 2.5.170
* Database engine: Postgres 13.1

**Comment by slysiou** [comment]
I get the same issue:
`/wiki/server/views/source.pug:7 5| block body 6| #root > 7| page-source( 8| :page-id=page.id 9| locale=page.localeCode 10| path=page.path The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined`
