### ISSUE TITLE
Customization (CSS/Views)

### ISSUE THREAD

**Issue by steckerhalter** [Requarks/wiki#29]
So installed `wiki.js` via npm. What is the preferred way to customize the Views or the CSS?

Could you give some short instructions? I edited the `Views` directly under `./Views` which worked at least. The `css` is minified and I'm not sure how to update it properly.

Another question would be: if I want to include content from an RSS feed on the home page for example, should I write a module or how would I do that?

**Comment by thomasmiguelthompson** [comment]
I was able to edit all of them by just switching between minified and non-minified CSS and editing that way, and views is the same way :3

Tbh, no clue on the second one, but GitHub might be a start, as we run our Discord bot grabbing pages from a pages.md that we've setup

**Comment by steckerhalter** [comment]
@thomasmiguelthompson Thanks. Yes I thought so too about the CSS, but it would be better to be able to modify the SCSS and generate the CSS since that is more efficient than meddling with the CSS directly.

**Comment by thomasmiguelthompson** [comment]
Yeah, agreed :3

**Comment by NGPixel** [comment]
Layout can be edited under `./views` as you found out.`

However, you cannot edit CSS directly. You must clone the Wiki.js github repo directly to get the developer files, which are not included in release packages / npm. SCSS files are found under `./client/scss` and can be compiled by running `gulp css-app`.

There's no easy theming functionnality at the moment, but something that could be added in future releases.

**Comment by steckerhalter** [comment]
@NGPixel thanks, I did this and got it to work. To develop `gulp css-app watch` is useful.

**Comment by steckerhalter** [comment]
Theming functionality would be great. But better think it out well :)

**Comment by steckerhalter** [comment]
@NGPixel Looks like you removed gulp from the project. How do I compile the css now?

**Comment by NGPixel** [comment]
To compile for production:
```sh
$ npm run build
```

To run in dev mode and watch for changes:
```sh
$ npm run dev
```

If you use the dev mode, you must run `npm run build` before deploying to generate a production version of the bundle. The dev mode doesn't uglify the bundle and certain libs are set to run in debug mode.

**Comment by steckerhalter** [comment]
@NGPixel thanks for explaining...

**Comment by ps3331333** [comment]
I'm trying to change and recompile the `scss` files, but I'm new to `node.js` so please bear with me. This is what I did: 
* I installed `wiki` in directory `wiki.js`. It works fine.
* I downloaded `wiki-master` from github (into a zip file).
* I extracted the contents `wiki-master` in the contents of `wiki.js` directory (to match the directories).
* I changed the `scss` files.

But when I try to recompile with `npm run dev` I get errors. What am I doing wrong?

**Comment by Losses** [comment]
@NGPixel Is it possible to create two blank files on a specific folder (like userScript.js, userStyle.css), make wiki.js load these file by adding these file on template HTML.
Anyone want to customize their wiki just need to edit the files and don't need to rebuild anything.
Is this a good idea?

(just a suggestion for further versions)

**Comment by NGPixel** [comment]
@Losses This has already been addressed in 2.0.

**Comment by sub0ne** [comment]
> @Losses This has already been addressed in 2.0.

any documentation on this feature? How can this be done?
