### ISSUE TITLE
Search Only Searches The Name of Pages

### ISSUE THREAD

**Issue by Ashkaan** [Requarks/wiki#2914]
**Describe the bug**
The search function does not provide results for any body or header text.  The only results provided are of the names of pages.

**To Reproduce**
1. Go to Search
2. Type anything you know is on a page
3. See no results

**Expected behavior**
I would expect to be able to search text body, headers, and page names.

**Screenshots**
<img width="860" alt="Screen Shot 2021-01-13 at 4 07 01 PM" src="https://user-images.githubusercontent.com/5667978/104527386-77abf180-55b9-11eb-9625-c4489b7ec911.png">
The phrase "pay day" is on several pages.

<img width="1108" alt="Screen Shot 2021-01-13 at 4 07 27 PM" src="https://user-images.githubusercontent.com/5667978/104527400-7d093c00-55b9-11eb-8142-ae98700edd74.png">
The word "welcome" is on several pages.

**Host Info (please complete the following information):**
 - OS: Docker
 - Wiki.js version: 2.5.170
 - Database engine: "Database - Basic" (I think this is file based)

**Additional context**
This instance is totally default with no interesting settings.

**Comment by arnerb** [comment]
I don't think this is an issue, but simply the default demo setting (only searches page title + description), see here:
see this: https://requarks.canny.io/wiki/p/search-for-content-and-title

If you think the default search functionality should be extended for easier demo purposes, you can upvote this:
https://requarks.canny.io/wiki/p/search-page-content

**Comment by Ashkaan** [comment]
I see.  That makes sense.  I shouldn't have assumed the search was searching body as well.  I upgraded the search by changing to Postgres.
