### ISSUE TITLE
Issue :: path must be absolute or specify root to res.sendFile

### ISSUE THREAD

**Issue by iAcolyte** [Requarks/wiki#2930]
**Describe the bug**
Can't assess to uploaded files:  path must be absolute or specify root to res.sendFile
Equals to this problem: https://github.com/Requarks/wiki/issues/2463
**To Reproduce**
Upload a file, insert it into project.
Administration -> Utilities -> Flush Pages and Assets Cache

**Expected behavior**
Assess to uploaded files

**Screenshots**

**Host Info (please complete the following information):**
 - OS: Openhabian ( armbian  (raspberry PI)) and Ubuntu Remote Server
 - Wiki.js version: 2.5.170
 - Database engine: [sqlite3]

**Additional context**

**Comment by Fakhri-Hasanzadeh** [comment]
Suggested solution:


this line:
```yaml
await sendFile(cachePath, { dotfiles: 'deny', root: "/opt/wiki/" })
```


replace with this line:
```yaml
try {
await sendFile(cachePath, { dotfiles: 'deny' })
}catch (error) {
await sendFile(cachePath, { dotfiles: 'deny', root: '/opt/wiki/' })
}
```

**Comment by iAcolyte** [comment]
Yes, it works.  Thank you!
The main issue is we use it in Docker for one of our projects. Are this fix will be available in the next version of Wiki.js?

**Comment by Fakhri-Hasanzadeh** [comment]
> Yes, it works. Thank you!
> The main issue is we use it in Docker for one of our projects. Are this fix will be available in the next version of Wiki.js?

I don't know. we fix it with this solution in our team and I share it with you

**Comment by h-marti** [comment]
> 
> 
> > Yes, it works. Thank you!
> > The main issue is we use it in Docker for one of our projects. Are this fix will be available in the next version of Wiki.js?
> 
> I don't know. we fix it with this solution in our team and I share it with you

We got the same issue on our docker deployment. Any date for a fix on the image ? Thx
