### ISSUE TITLE
two domains connected to wiki.js, is it possible?

### ISSUE THREAD

**Issue by robert-danowski** [Requarks/wiki#294]
Can i configure wiki in that way that i can use two domains without this "Weird display, no styling" problem?

For example I have new domain which hasn't page rank at all (wiki works from locations where domain isn't blocked by firewall), so I created proxy using heroku address and then... address in browser is ....herokuapp.com (is reachable) but wiki doesn't work.

**Comment by NGPixel** [comment]
Not possible in Wiki.js 1.x.

Wiki.js 2.0 will have that capability.
