### ISSUE TITLE
How to close a content tab ({.tabset})?

### ISSUE THREAD

**Issue by SilentLunZ** [Requarks/wiki#2952]
If I have a content tab:

> # Tabs {.tabset}
>## First Tab
>
>Any content here will go into the first tab...
>
>## Second Tab
>
>Any content here will go into the second tab...
>
>## Third Tab
>
>Any content here will go into the third tab...

and then want to continue after it with plain text, how can I let wik.js know that my Tabs are finished?

If I continue to write text, it is getting displayed in the last tab. But how does it get displayed beneath it (without making a new headline)

**Comment by NGPixel** [comment]
See https://github.com/Requarks/wiki/discussions/2882
