### ISSUE TITLE
Why I am unable to use images that I manually inserted in git repository?

### ISSUE THREAD

**Issue by Rogach** [Requarks/wiki#297]
### Actual behavior

Several files were moved into git repository, and committed there.

When opening "Insert Image" dialog, it is empty.

### Expected behavior

When opening "Insert Image" dialog, newly inserted images are visible.

**Comment by NGPixel** [comment]
Restart Wiki.js to rescan the images. They must be located in the uploads folder.

**Comment by Rogach** [comment]
Did that, image chooser still shows empty directory.

**Comment by Rogach** [comment]
Also, when trying to insert images one-by-one, using "upload image" button, the following happens:

1. Image is placed into `uploads/`.
2. After several second "Unable to fetch updated listing" error is displayed. No errors are logged anywhere at that moment.
3. After reloading, listing is still empty.

The following errors happens on each startup:
```
events.js:182
       throw er; // Unhandled 'error' event
       ^
 
 Error: ENOENT: no such file or directory, lstat '/root/journal.rogach.org/.git/index.lock'
```

**Comment by Rogach** [comment]
I'm currently investigating, but for now it seems that something in `entries.js` traverses the directory tree, including the `.git` folder, and tries to stat `.git/index.lock`, which is only there for very short period of time. 

Probably this problem leads to all my problems with files.

P.S. Man, error handling in nodejs is ugly. Can't even get a normal stack trace :(

**Comment by Rogach** [comment]
So, the resulting analysis:

1. `global.git.resync` in `agent.js` triggers git operations, which result in `.git/index.lock` being created and then deleted shortly afterwards.
2. If wiki is quite small, so that parsing and processing files in root directory happens quickly, `.git/index.lock` is returned from `fs.readdir(".git")`, but `fs.lstat(".git/index.lock")` right afterwards returns ENOENT. *(I have no idea why that happens - I tested this on Vultr VM, maybe something strange with network disks?)*
3. `klaw` library is used in this project for directory tree traversal, and it hard-stops on this error, which happens before getting to `uploads` directory (since `.git` sorts before it, presumably).

Adding filter to `klaw` invocation fixes all the problems (manually inserted files are visible, newly inserted images also work):

```js
        klaw(repoPath, {
          filter: function(pathItem) {
            return !pathItem.endsWith(".git/index.lock");
          }
        })
```

I would be happy to submit a PR, if you would like.

**Comment by Rogach** [comment]
Fixing the problem upstream does not seem to be possible, since `klaw` seems to be a little abandoned - this exact issue has no response from maintainer for 4 months already.

**Comment by NGPixel** [comment]
Thanks for looking into this! Submit a PR with the fix and I'll accept it.

**Comment by Rogach** [comment]
Done!
