### ISSUE TITLE
Enter the security code generated from your trusted device

### ISSUE THREAD

**Issue by covationlabs** [Requarks/wiki#2990]
**Describe the bug**
I don't know why I am getting this popup even after disabling 2fa.

<img width="587" alt="Screenshot 2021-01-31 at 7 36 16 AM" src="https://user-images.githubusercontent.com/69179167/106372588-1183e480-6397-11eb-8d52-81c029f67308.png">

**To Reproduce**
1. Go to 'wiki.prodeasy.com'
2. Click on 'login'
4. See an error

**Expected behavior**
The popup should not come, as it is not allowing me to log in.

**Screenshots**

**Host Info (please complete the following information):**
 - OS: Ubuntu 18.04,
 - Wiki.js version: Latest
 - Database engine: SqLite
 
How can I log in now? I only have the ssh and DB access now! How can I revoke this!

**Comment by NGPixel** [comment]
Not sure how you got into that state, but you can manually disable 2FA on your account in the database (`users` table) by changing the `tfaIsActive` value to `false`.
