### ISSUE TITLE
Change default visibility to private

### ISSUE THREAD

**Issue by mnpenner** [requarks/wiki#3034]
**Describe the bug**

I just installed wikijs2 and imported my wikijs1 data from github (which itself is giving periodic errors, but that's a different issue). Once I got my data in I decided to open a new incognito tab to my wiki to checkout the login screen only to discover all my data was public! I don't think this is the case with wikijs 1 but I think this needs to be made much more prominent so that users don't accidentally expose all their data when importing from earlier installations. Either during setup let users choose "public" or "private" or just default Guest to not have read access.

**To Reproduce**
1. Use wiki js 1 for a few years
2. Finally get around to installing wiki js 2
3. Import your data from github
4. Surprise! You just made everything public

**Expected behavior**

Must login before being able to see wiki

**Screenshots**

n/a

**Host Info (please complete the following information):**
 - OS: Docker/Helm
 - Wiki.js version: 2.5.x
 - Database engine: MariaDB

**Additional context**

[The guide](https://docs.requarks.io/groups#:~:text=Private%20Wiki,global%20permissions%20on%20the%20account.) tells you how to turn off Guest access. Turn it off before importing if you want to keep your wiki private.

**Comment by NGPixel** [comment]
Yes this will be addressed in 3.0 by making it clearer at installation time.

**Comment by bluepuma77** [comment]
Maybe add a switch during the installation process (when creating the admin):

**Default public: yes/no**

**Comment by bluepuma77** [comment]
I am new to Wiki.js, Docker installation was a breeze, even setting up SSL and redirection.

```
docker run \
  --name wiki \
  --restart unless-stopped \
  -p 80:3000 \
  -p 443:3443 \
  --env SSL_ACTIVE=true \
  --env LETSENCRYPT_DOMAIN=wiki.my.tld \
  --env LETSENCRYPT_EMAIL=me@my.tld \
  --env DB_TYPE=sqlite \
  --env DB_FILEPATH=/data/db.sqlite \
  -d requarks/wiki:2
```

After searching the settings for 10 minutes I still haven't found a way to make everything private.

Maybe add a switch during the installation process (when creating the admin):

**Default public: yes/no**

**Comment by bluepuma77** [comment]
Finally found the info on the [groups](https://docs.requarks.io/en/groups) page:

**Private Wiki**

To make your wiki completely private and require authentication in order to view any page, simply modify the Guest group in the Administration Area -> Groups section. Either change the default Page Rule from Allow to Deny, or remove all global permissions on the account. Both methods will result in the same behavior.

**Comment by NGPixel** [comment]
Closing this issue as private wiki is now the default in the upcoming v3.
