### ISSUE TITLE
Allow single pod non-postgres with Helm

### ISSUE THREAD

**Issue by mnpenner** [Requarks/wiki#3035]
Creating new issue from https://github.com/Requarks/wiki/issues/2911#issuecomment-774391439 to not pollute too much.

I understand postgres is a requirement for multi-pod, but a single pod is good enough for my tiny wiki.

(Also I'm not totally sure why it wouldn't work with multiple pods as long as there's only 1 db pod; but you can let us install ourselves to keep wikijs simple, as long as there's an option for BYO DB)

**Comment by NGPixel** [comment]
Because pods have local cache to avoid pinging the DB on every single request. PostgreSQL offers native pub/sub support which is required to notify other instances that a cache item needs to be refreshed.

**Comment by NGPixel** [comment]
Closing as 3.0 will be Postgres-only.
