### ISSUE TITLE
Failed to start: ENOENT: no such file or directory, open '/server/app/data.yml'

### ISSUE THREAD

**Issue by FaserF** [Requarks/wiki#3064]
**Describe the bug**
I am trying to start wiki.js, but I am getting the error that the file  '/server/app/data.yml' does not exist. But it definitly is there (extracted it before with tar and checked via CLI), I have also given 755 permission on that explicit file.
The normal config.yml is there too.

**To Reproduce**
Wget the server files, extract it and then start it with "node /wiki/server"

**Expected behavior**
The wiki.js server does start with no error.

**Host Info (please complete the following information):**
 - OS: Homeassistant OS - building a docker addon myself
 - Wiki.js version: 2.5.170
 - Database engine: latest mariadb

**Additional context**
```
-rwxrwxr-x    1 1001     121           3027 Oct 26 04:28 /wiki/server/app/data.yml
FAILED
ENOENT: no such file or directory, open '/server/app/data.yml'
>>> Unable to read configuration file! Did you create the config.yml file?
Loading configuration from /config.yml...
```

**Comment by NGPixel** [comment]
Because your working directory is wrong.

`node /wiki/server` -> working directory is / = wrong

The process needs to be started from `/wiki` using `node server`

**Comment by FaserF** [comment]
I am very sorry. Thank you so much for helping with that simple problem. 
I have now finished building the HomeAssistant Wiki.JS Addon and its working 👍🏼 
https://github.com/FaserF/hassio-addons/tree/master/wiki.js
