### ISSUE TITLE
Wrong 2FA URL

### ISSUE THREAD

**Issue by NiTRoeSE** [Requarks/wiki#3076]
### Actual behavior

Wiki.js genrates a wrong 2FA (ttop) URL

### Expected behavior

Generating a working 2FA URL for ttop authenticator apps

### Steps to reproduce the behavior

Configure 2FA JWT via Settings -> Security -> JWT Configuration -> JWT Audience
Set your URL like "urn:sub.domain.de"

Wiki.js always generates a URL like:

`otpauth://totp/FAQ|Test Site:hans.wurst@my.mail.de?secret=JNOSH47PRIUADA36LQYDRENOSH4YASB`
(Instead of url the site name is set)

but it should be

`otpauth://totp/sub.domain.de:hans.wurst@my.mail.de?secret=JNOSH47PRIUADA36LQYDRENOSH4YASB`

### My Setup

I running wiki.js in docker with postgresdb
Maybe i misunderstand something with 2FA but if i change the url manually and swap the Site-Name with the site url it works.
Version: Wiki.js 2.5.170

Thanks for your work & regards

**Comment by NGPixel** [comment]
You're confusing 2FA and JWT which are completely unrelated. The 2FA url is supposed to contain the site name, not the url and definitely not the JWT audience (again, unrelated).

You can't use special characters in your site name if you plan on using 2FA. Change your site name to something like "Test Site" and it should work just fine.
