### ISSUE TITLE
Revert Changes to Articles (+2 others)

### ISSUE THREAD

**Issue by thomasmiguelthompson** [Requarks/wiki#31]
Just a small feature request while I'm here: In the future, could you possibly add reverting changes to a previous commit to combat vandalism? Right now, we have a public wiki that only a few people can edit, but we'd like to allow others to edit it in the future :3

**Comment by thomasmiguelthompson** [comment]
Also, while I'm making a request, perhaps have edit previews so that we can see exactly what we're adding before we add it

(very sorry, one last one: perhaps have a toggle for pages to *not* get pushed to the GitHub repo, because those are unreleased features that we aren't allowed to publicly share, and we'd like to be able to make wiki articles before those features come out)

**Comment by NGPixel** [comment]
The history (with revert) feature and the ability to preview is planned.

Your last request would be a bit challenging to implement though. For now I would suggest using a private repo if you have content that shouldn't be viewed directly.

**Comment by NGPixel** [comment]
Preview of the history feature:

![history-mock1](https://cloud.githubusercontent.com/assets/15522395/25567758/fd07da7e-2dc2-11e7-954e-392064e04fc5.png)

**Comment by NGPixel** [comment]
Moved ticket to Feature Board: https://wikijs.canny.io/features/p/history--revert-to-previous-version

Closing this ticket.
