### ISSUE TITLE
How do users link other wiki page?

### ISSUE THREAD

**Issue by huyhoang-goappable** [Requarks/wiki#310]
How do users link other wiki page they created to the main wiki page? Says I have 7 projects going on, each one has its own wiki page. I want the main page have a list of [Project 1] [Project 2] ..., when user click on these links, it will take them to the designated wiki page.

**Comment by NGPixel** [comment]
Use Markdown syntax to create links to other pages:
https://docs.requarks.io/wiki/user-guide/markdown-syntax

**Comment by dayuoba** [comment]
@NGPixel the link is missing 
> https://docs.requarks.io/wiki/user-guide/markdown-syntax

**Comment by NGPixel** [comment]
@dayuoba https://docs-legacy.requarks.io/wiki/user-guide/markdown-syntax
