### ISSUE TITLE
When I click "Profile", it automatically searches my email

### ISSUE THREAD

**Issue by closewall** [Requarks/wiki#3104]
**Describe the bug**
I just configured my email settings to enable self-registration.
I made myself a new account on my wiki, and it all works fine, but when I click to navigate to my profile, for some reason it automatically searches the email address I registered with

**To Reproduce**
1. Setup and configure self-registration
2. Register a new user
3. Click on "Profile" at the top right
4. It automatically searches for the email I registered with.

**Expected behavior**
Nothing. I expect a clean profile page without any automatic searches.

**Screenshots**
1. https://i.imgur.com/qb69ym7.png
2. https://i.imgur.com/zgrXHLJ.png

**Host Info (please complete the following information):**
 - OS: Unraid 6.8.3
 - Wiki.js version: 2.5.170
 - Database engine: postgres 12.3

**Additional context**
It's only a minor bug, but still a bug so I thought I'd report it.

**Comment by NGPixel** [comment]
Make sure you don't have any browser extensions that autofill fields

**Comment by closewall** [comment]
> Make sure you don't have any browser extensions that autofill fields

I don't have any extensions that do that, but I'm using Ungoogled Chromium so I assume my browser thinks it's a login field.
