### ISSUE TITLE
Can't upload assets as regular user

### ISSUE THREAD

**Issue by humboldtux** [Requarks/wiki#3109]
**Description**
I can't upload assets as regular user. Regular user belongs to a group with a page rule with all possible permissions on the page i want to upload assets to. But i get error "Error during upload" when i try to upload an asset.

With a user member of the built-in Administrators group, i can upload the same file on the same page.

As administrator i can create an assert folder and it is shown in the Assets Medias dialog. As regular user, i can create a folder,
no error is shown, but the asset folder is not shown. I get an error if i try to create an asset folder previously created by administartor, even if i can't see this previously created folder.

In my Nginx logs i can see the following messages for the failed regular user upload:

```
"POST /graphql HTTP/2.0" 200 87 "https://website/page"
"POST /u HTTP/2.0" 403 95 "https://website/page"
"POST /u HTTP/2.0" 403 95 "https://website/page"
```
And these for the successful administrator upload

```
"POST /graphql HTTP/2.0" 200 218 "https://website/page"
"POST /u HTTP/2.0" 200 2 "https://website/page"
"POST /graphql HTTP/2.0" 200 221 "https://website/page"
```

**Host Info (please complete the following information):**
 - OS: Debian 10
 - Wiki.js version: Wiki.js 2.5.170
 - Database engine: postgresql 11.10

**Comment by dualmacops** [comment]
Does the group have the write:assets in permission and the Upload Assets permission in page rules?

**Comment by humboldtux** [comment]
Yes it does: all assets permissions and all assets page rules.
