### ISSUE TITLE
Folders Listing lacking Scroll Bar

### ISSUE THREAD

**Issue by Roachmen** [Requarks/wiki#311]
### Actual behavior
Media Folders beyond a certain count that is dependent upon resolution are inaccessible due to lack of scroll bar. (See attached image for example)
### Expected behavior
Click and drag a  scroll bar to see additional folders
### Steps to reproduce the behavior
Create the folders manually in the repo folder under uploads. Restart wiki.js. Or create enough folders from the image insert manager.
![image folders unviewable](https://user-images.githubusercontent.com/20803311/32632140-18623408-c568-11e7-8f55-67628d01f8ce.PNG)

**Comment by gordosgithub** [comment]
I'm having the same issue, it's extremely frustrating. It also pushes the "save/discard" buttons down off of the page so the only way to get rid of the window is to zoom ur browser view way out and click them.

This issue also applies to the "file container" part of the window not having a scrollbar. In other words, if u have more pictures than will fit in the right hand container, it will also break.

This is all on top of the fact that there is no way to create subfolders inside the file editor, and if u do create subfolders manually in your repo/uploads directory they will not be displayed in the file editor window, nor will their contents.

I've had a lot of big bugs with the file editor on this wiki, but this particular combination of bugs makes it virtually unusable for people with a lot of files.

NOTE: i did find the lines of CSS in firefox dev tools that need "scroll:overflow;" added to them, but the way the files are packed locally on my server makes it hard for me to find where i can actually edit my own CSS.

**Comment by EvanCarroll** [comment]
We got around this by running

    section.is-gapless { overflow:scroll } 

in `layout.pug`

**Comment by NGPixel** [comment]
Fixed in 1.0.76

**Comment by coom** [comment]
Hi,

I got the exactly same issue. Using version v1.0.117.

Should that be fixed or am I using a wrong version of WikiJS ?

**Comment by bilkobe** [comment]
Have same problem with v1.0.117.
