### ISSUE TITLE
Slow loading time of the homepage

### ISSUE THREAD

**Issue by hell1ano** [Requarks/wiki#3117]
My original issue is that my wiki.js site is very slow to load for the users, even trying locally on the same host as the installation.
Also note that I'm running an offline-installation with sideloaded assets, everything does despite the load times work very good with this usecase.

Now to the issue, it seems to be everytime the client/browser requests the homepage.
While I'm at a page accessing different features the site is very responsive, for example in the Admin-panel (/a/*) changing between the pages are super quick.
After analyzing the nginx logs of the client requests, I see the main difference being that the clients keep doing "POST" queries to the /graphql URL when entering the wiki.js page.
This alone seem to be the performance hog making the website run slow.

After doing a manual check on the graphql URL I cannot even get an response from this interface (I thought this is intended as afterall it's an offline installation).

However due to the clients still trying to use graphql for something the load time of the webpage is almost 15 seconds for the homepage. Once you have landed on the site the navigation itself is fine and very responsive.

**To Reproduce**
1. Go to your wiki URL
2. Check the browser/http log
3. Check for POST entries for /graphql entries

**Expected behavior**
I would like to see decent loadtimes, is there any possibility to turn of the graphQL POSTs?
Option two is if there is any way to get it to work during an offline installation, is it possible?

**Host Info (please complete the following information):**
 - OS: Windows Server 2019
 - Wiki.js version: Latest release
 - Database engine: Latest stable Postgres

**Comment by NGPixel** [comment]
GraphQL is the core API system handling all requests, not something you can disable...

If it takes 15 seconds to load a page, you definitely have a major issue somewhere as this is not normal. Even on a basic low-powered raspberry pi, it would take at most 1-2 seconds to load a page.

**Comment by hell1ano** [comment]
I understand thanks @NGPixel, then there probably is some feature being loaded on the homepage of wiki.js which is the cause. I will have to troubleshoot some more then I guess. 
As I dont see any issues in the online installation, so my guess is some core component trying to contact a service online.
Will do a network trace and get back with this information.

**Comment by hell1ano** [comment]
I found and resolved this issue in my installation/fork.
The cause is in the file server\views\master.pug which tries to get two external CSS-files.

"all.css" from https://use.fontawesome.com/releases/v5.10.0/css/all.css
font-awesome.min.css from https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css

By downloading these files manually and putting them in the cache folder and changing the links in master.pug and also legacy\master.pug.
This should be noted or instructed in the offline installation, because failure to do so will slow down the page massively.
Will share my commit if needed, but guessing @NGPixel has a better way to solve this issue.

**Comment by mckaygerhard** [comment]
its there any way to load all resources locally ?
