### ISSUE TITLE
2FA and require password change on first login cannot be used together

### ISSUE THREAD

**Issue by soke1556** [requarks/wiki#3146]
**Describe the bug**
If 2FA and "Require password change on first login" are BOTH active for Local Database it causes users to stay on a continuous loop between request for token and password change form.

**To Reproduce**
1. Go to Security settings and Enable 2FA
2. Create a local database user.
3. Enable Requiere password change on first login for the new user.
4. Now try to login with the new user following the instructions on a brand new session (incognito mode on Chrome)

**Expected behavior**
1. User inputs username and password.
2. System asks user to enrol 2FA
3. System asks for token to verify enrolment
4. System shows form to change password
5. User changes password
6. User get access.

**Host Info (please complete the following information):**
 - OS:  Ubuntu (bionic) 18.04 x64
 - Wiki.js version: 2.5.170
 - Database engine: postgresql 10.15
 - Node.js: 12.13.1

**Comment by jrose-stac** [comment]
We have experienced this same behavior and added some logging to the user login process on our deployment.

What we see in the logs:

1. User is prompted to set up 2FA
2. User sets up 2FA code (delta on code is 0, code is verified)
3. 2FA setup finishes successfully
4. User authentication token is not validated (by userKeys.validateToken), password change form never displayed

If the user refreshes the page and attempts to log in again, they'll get a token failed error. When this happens to a user for us they are unable to log in without us resetting their password/clearing their 2FA.

If the user waits 24hrs, they will be able to successfully attempt to log in and receive a password change prompt.

**Comment by NGPixel** [comment]
Fixed in v3.
