### ISSUE TITLE
Slack integration is returnig invalid_auth

### ISSUE THREAD

**Issue by chessbr** [Requarks/wiki#3149]
**Describe the bug**
I configured the Slack integration according to the steps documented

**To Reproduce**
1. Just follow the steps for Slack integration from https://docs.requarks.io/auth/slack
2. Try to login using Slack
4. See the error

**Expected behavior**
The login should go through

**Screenshots**
![image](https://user-images.githubusercontent.com/8770370/109213484-6bf24400-778f-11eb-994a-27ebaf73bbe5.png)

**Host Info (please complete the following information):**
 - OS: Ubuntu 18.04
 - Wiki.js version: 2.5.170
 - Database engine: Postgres 12

**Additional context**
I've tried nearly everything, remove the auto registration, removed the domains, it won't work, althrough the users are listed as connected in Slack.

**Comment by chocobn69** [comment]
Hi, I faced exactly the same problem. Fresh install -> Slack integration -> invalid_auth
Using docker-compose Wiki.js (2.5.170)

**Comment by Corfus** [comment]
Hi, I can confirm the same problem, too.

In the debug-mode I got this feedback:
![Screenshot from 2021-03-05 23-43-17](https://user-images.githubusercontent.com/12698546/110182341-e153b980-7e0c-11eb-980d-fc999b378e34.png)

Perhaps something changed in the interface of Slack. I will try to find the origin of the issue.

**Comment by Corfus** [comment]
Okay I found the issue.
Slack needs a Post-Request to handle the Request: [https://api.slack.com/methods/users.identity](https://api.slack.com/methods/users.identity)

In the @aoberoi/passport-slack package it will be used a Get-Request, when you adapt the get to a post. It works fine.

[https://github.com/aoberoi/passport-slack/blob/5ccb3b40f294f88d170ce631554582665795dad2/src/strategy.js#L155](https://github.com/aoberoi/passport-slack/blob/5ccb3b40f294f88d170ce631554582665795dad2/src/strategy.js#L155)

Tomorrow I will start a Pull-Request to fix this in @aoberoi/passport-slack.
