### ISSUE TITLE
Images not loading after process restart

### ISSUE THREAD

**Issue by HurricaneDancer** [Requarks/wiki#3158]
**Describe the bug**
When hosting the application with PM2, the images fail to load once the process has been restarted. It just shows the name of the image on the page. 

**To Reproduce**
1. install pm2 
2. Change your directory to the application
3. use pm2 start ./server/index.js --name Wiki.js
4. upload an image 
5. insert it into the page and save it 
6. restart the process with pm2 (pm2 restart Wiki.js) 
7. View the page - the image is now only the name 

**Expected behavior**
The image should still render after restart and re-uploads should not be necessary, 

**Screenshots**

![image](https://user-images.githubusercontent.com/44342932/109470810-93d7f500-7a78-11eb-84db-69af312a2e65.png)

**Host Info (please complete the following information):**
 - OS: Ubuntu Linux 18.04.2 
 - Wiki.js version: 2.5.170
 - Database engine: MySQL 8.0.23

**Comment by HurricaneDancer** [comment]
Hi there. Is this issue going to be resolved?

**Comment by NGPixel** [comment]
I can't replicate your issue.

**Comment by phamkhanh07** [comment]
im facesing same error, when view image in new tab "Internal Server Error"
