### ISSUE TITLE
Naming files

### ISSUE THREAD

**Issue by streuselbroetchen** [Requarks/wiki#3180]
Description:
When renaming an files in a folder exactly like another file one gets no warning and therefor override the file

To Reproduce
1. Upload an file
2. Name it like another file
3. File gets overrided

Host Info (
 - OS: Linux - CentOS (linux) 8 x64
 - Wiki.js version: 2.5.170
 - Database engine:PostgreSQL 12.1, 127.0.0.1

**Comment by NGPixel** [comment]
This is the intended behavior. Feel free to post a feature request [here](https://feedback.js.wiki/wiki).
