### ISSUE TITLE
Uncaught ReferenceError: FuseBox is not defined

### ISSUE THREAD

**Issue by aka-toxa** [Requarks/wiki#319]
### Actual behavior
Got error **Uncaught ReferenceError: FuseBox is not defined** in the console, no buttons works

### Expected behavior
Working button in UI of wiki

### Steps to reproduce the behavior
I've tried to reinstall wiki to the different directories many times and every time I got this error in the chrome console and most of UI elements don't work

**Comment by NGPixel** [comment]
What's your browser, version and OS?
