### ISSUE TITLE
Case sensitivity for email address

### ISSUE THREAD

**Issue by koallen** [Requarks/wiki#32]
I have a wiki system configured with Google authentication. I noticed that if I put any uppercase letters in a user's email, the authentication will fail because Google converts email addresses to all lowercase automatically when calling the callback URL. I think the code for authenticating user should ignore the cases when comparing email addresses since email addresses are case-insensitive.

**Comment by NGPixel** [comment]
Fixed in upcoming Beta 9

bfcec5a91c60664b06ef66b894a91d4022ed0452
