### ISSUE TITLE
Question: Will WikiJS version 3.0 with Quasar Vue framework work on a raspberry pi?

### ISSUE THREAD

**Issue by kbfifi** [Requarks/wiki#3203]
### Actual behavior
Version 2.5.159 on Linux docker host,  PostgreSql 11, is running fine on my raspberry like SBC: Rock64, 4GB 
### Expected behavior
Version 3 still works on the board
### Steps to reproduce the behavior
not relevant

Background:
One of the main reasons for me to choose for WikiJS is its small footprint and thus the ability to run it on a Raspberry Pi. I see promising anouncement about server side rendering. That suggests a total new concept. Will client side still work, so my SBC board can keep up with it?
Will Quasar Vue framework at all be very challenging/possible for my board?

Hopefully, because I use WikiJS almost every day!

**Comment by kbfifi** [comment]
Added

**Comment by NGPixel** [comment]
Yes it will work just fine.
