### ISSUE TITLE
Error trying to read page with group API key

### ISSUE THREAD

**Issue by revofever** [Requarks/wiki#3205]
When creating an API key with *any* group permissions, I am not authorized to view a page. That is the only call I have tried so far. However, creating a key with "Full Access" or Administrator group permissions works fine.

1. Create a new test group and check all the permission boxes and save.
2. Create a new API key using that group's permissions.
3. Go to your.wiki/graphql and enter the following

```
query{
  pages {
    single(id: 1){
      title
    }
  }
}
```
Under http headers enter
```
{
  "Authorization": "Bearer yourApiKey"
}
```

This should show the title of the page, but I get an error.

```
{
  "errors": [
    {
      "message": "You are not authorized to view this page.",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [
        "pages",
        "single"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stack": "PageViewForbidden 6013: You are not authorized to view this page.\n    at single (/wiki/server/graph/resolvers/page.js:165:17)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)",
          "code": 6013,
          "message": "You are not authorized to view this page.",
          "stacktrace": [
            "PageViewForbidden 6013: You are not authorized to view this page.",
            "    at single (/wiki/server/graph/resolvers/page.js:165:17)",
            "    at processTicksAndRejections (internal/process/task_queues.js:93:5)"
          ]
        }
      }
    }
  ],
  "data": {
    "pages": {
      "single": null
    }
  }
}
```

**Host Info**
 - OS: DO Docker Container (Ubuntu 18.04)
 - Wiki.js version: 2.5.170
 - Database engine: Postgres 11.8

**Comment by NGPixel** [comment]
You need to assign page rules as well. Global permissions alone don't do anything.

https://docs.requarks.io/groups

**Comment by txstreet** [comment]
Sorry, I did not mention that step because it automatically creates a page rule that should work. I've tried deleting and re-adding the page rule as well. Still not working.

![Screenshot_20210311_193703](https://user-images.githubusercontent.com/76406418/110874339-8e14b780-82a1-11eb-962b-4647a19926f0.png)

**Comment by revofever** [comment]
Sorry, I did not mention that step because it automatically creates a page rule that should work. I've tried deleting and re-adding the page rule as well. Still not working.

![Screenshot_20210311_193703](https://user-images.githubusercontent.com/8880715/110874715-417dac00-82a2-11eb-9dbe-ef6983fea2ed.png)

**Comment by Bravo2333** [comment]
I get the same wrong, i dont know is there  the group rule or api key makes this forbidden.

**Comment by LuccaPrado** [comment]
Not actually solved! Probably both of you, @Bravo2333  and @tomx-eth faced this because of the way that access is validated on single resolver.
On server/graph/resolvers/page.js on method named single we have this:
```
 /**
     * FETCH SINGLE PAGE
     */
    async single (obj, args, context, info) {
      let page = await WIKI.models.pages.getPageFromDb(args.id)
      if (page) {
        if (WIKI.auth.checkAccess(context.req.user, ['manage:pages', 'delete:pages'], {
          path: page.path,
          locale: page.localeCode
        })) {
          return {
            ...page,
            locale: page.localeCode,
            editor: page.editorKey,
            scriptJs: page.extra.js,
            scriptCss: page.extra.css
          }
        } else {
          throw new WIKI.Error.PageViewForbidden()
        }
      } else {
        throw new WIKI.Error.PageNotFound()
      }
    },
```

So the user/token without manage:pages and delete:pages get the forbidden response. While it should only need the read:pages permission IMO

**Comment by Henrik-3** [comment]
IMO the permission check is false for the graph endpoint, especially as the permission check is different for the frontend/user/source view:

https://github.com/requarks/wiki/blob/407aacfa19021f4b9b4cbaa24fc9524e359b876f/server/controllers/common.js#L444
https://github.com/requarks/wiki/blob/407aacfa19021f4b9b4cbaa24fc9524e359b876f/server/controllers/common.js#L81

Is this intended or actually wrong?
