### ISSUE TITLE
Unable to stop server/index.js

### ISSUE THREAD

**Issue by rarguelloF** [Requarks/wiki#323]
I'm running wiki.js on my ubuntu server using systemd instead of pm2. 

For that, I had to set the entry point to server (`server/index.js`) instead of the main `wiki.js` script (since this one dettaches itself using pm2). I found this a little bit frustrating until I figured out I had to use the server script instead the wiki.js one, so IMHO all the pm2 part could be moved separately, since the process manager part shouldn't have anything to do with the application itself.

The problem itself comes when systemd tries to stop the service, which is unable to (it keeps spawning more processes). The same happens when executing the `server/index.js` from the terminal and pressing CTRL+C. The only way to stop the process is killing it.

Thanks in advance!

**Comment by NGPixel** [comment]
pm2 is optional. You can start Wiki.js manually by using `node server`

In your case, it fails to stop because of an issue with your git, which prevents the app from syncing upon shutdown.

**Comment by rarguelloF** [comment]
@NGPixel thanks for your response! Now that I fixed my git issues it shut downs properly.

However, IMHO, I think this behaviour is a bug, since the application should be capable of shutting down gracefully even if not able to sync with the git repo.

**Comment by NGPixel** [comment]
This behavior will be fixed in 2.0.
