### ISSUE TITLE
Git initialization problems

### ISSUE THREAD

**Issue by rarguelloF** [Requarks/wiki#324]
The documentation says the required version is 2.7.4 or later. With that version, I was getting the following error on initialization:

```js
{ code: 1,
message: '`git --git-dir=/opt/wikijs-it/repo/.git --work-tree=/opt/wikijs-it/repo pull origin master` failed with code 1',
stderr: 'Host key verification failed.\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n',
stdout: '' }
```
And when I upgraded to latest version (on ubuntu, adding the git-core ppa) I got the following one:

```js
{ code: 1,
message: '`git --git-dir=/opt/wikijs-it/repo/.git --work-tree=/opt/wikijs-it/repo pull origin master` failed with code 1',
stderr: 'Warning: Permanently added the RSA host key for IP address \'192.30.255.112\' to the list of known hosts.\r\nfatal: Couldn\'t find remote ref master\n',
stdout: '' }
```

So, 2 questions about this:
- Is the required git version ok? Maybe the docs should be updated accordingly.
- Should the repo be initialized in some specific way? Maybe adding a README or something?
 Would be cool to clarify this questions in the docs.

Thanks a lot in advance!

**Comment by NGPixel** [comment]
- Git 2.7.4 has been tested to work fine.
- The remote git repository must be initialized first.

**Comment by smhanes15** [comment]
This may not apply to you, but having just setup Wiki.js and getting the same error after configuring remote git post-install, I thought I'd comment with what I did.

`node wiki stop`
`cd repo`
`git pull origin master`

This may or may not prompt with adding host to known hosts.
This may or may not prompt with a merge message.

`git push origin master`
`node wiki start`

Checked the error log in logs/wiki-error... for a repeat of the message. I am however waiting to see if the periodic remote sync works. Could not find documentation on how often this occurs and haven't dug into the code to find it.

**Comment by NGPixel** [comment]
@smhanes15 Git sync occurs every 5 mins.

**Comment by rarguelloF** [comment]
@NGPixel In the first error, it was complaining about authentication to the repo, and the second one was about complaining about the git repo not initialized, and the only thing I did between those 2 steps was to update the git version.

I will double-check this, now that my git repos are initialized (will test again with both git versions and will let you know if the same happens).
