### ISSUE TITLE
NPM Package Updated

### ISSUE THREAD

**Issue by Smuggla** [Requarks/wiki#325]
### Actual behavior

```
npm install wiki.js@latest
```
Installs `1.0.5`
### Expected behavior
```
npm install wiki.js@latest
```
Installs `1.0.11`

Thanks!

**Comment by NGPixel** [comment]
1.0.5 is the version of the npm package, not the actual Wiki.js installation, which will be 1.0.11.

You should instead use the recommended installation method for your OS as detailed in the docs:
https://docs.requarks.io/wiki/install

The npm package is simply calling these commands and is left solely for backward compatibility. It is not maintained and not the recommended way to install Wiki.js.
