### ISSUE TITLE
Error: EACCES: permission denied, mkdir '/root/.pm2/logs'

### ISSUE THREAD

**Issue by ankh2054** [Requarks/wiki#329]
### Actual behavior

I'm running WikiJS using docker and I am starting wikijs as a non root user.
When WikiJS invokes PM2 it automatically tries to run as root and cannot continue.

`Error: EACCES: permission denied, mkdir '/root/.pm2/logs'`

### Expected behavior

Need to run this in a production environment and therefore cannot use root to run WikiJS.
Need to be able to run WikiJS as non root user.

### Steps to reproduce the behavior

```
su nonrootuser
node wiki.js start 
```

**Comment by NGPixel** [comment]
Do not use pm2 if using docker. You should instead start the server directly:

`node server`

**Comment by ankh2054** [comment]
Thanks,

When I  run using node server it's trying to pull from the GIT repository. 

```
2017-11-22T09:25:45.855Z - info: [AGENT] Performing pull from remote Git repository...
2017-11-22T09:25:45.875Z - info: [AGENT] Git repository is OK.
Username for 'https://github.com': XXXXXXXX
Password for 'https://XXXXXXX@github.com': 
2017-11-22T09:26:02.272Z - error: [AGENT] Unable to fetch from git origin!
2017-11-22T09:26:02.272Z - error: [AGENT] Unable to push changes to remote Git repository!
2017-11-22T09:26:02.273Z - error: [AGENT] One or more jobs have failed:  
{ code: 1,
  message: '`git --git-dir=repo/.git --work-tree=repo pull origin master` failed with code 1',
  stderr: 'remote: Repository not found.\nfatal: repository \'https://github.com/Organization/Repo/\' not found\n',
  stdout: '' }
```

**Comment by ankh2054** [comment]
thanks, that did the trick.
