### ISSUE TITLE
Code to create admin user during docker creation.

### ISSUE THREAD

**Issue by ankh2054** [Requarks/wiki#332]
### Actual behavior

I am working on my own Dockerfile and was hoping you can share your code in creating the admin user during install using the ENV variable. 
In our production environment, we never use rebuild docker images and always create from scratch and important for us to be Abel to automate the process, which includes the creation of admin user.

https://github.com/ankh2054/wiki-js

**Comment by NGPixel** [comment]
Set these 2 environment variables to enable automatic admin account creation:

WIKI_JS_HEROKU = 1
WIKI_ADMIN_EMAIL = your_email@domain.com

**Comment by ankh2054** [comment]
Was hoping you could share the actually JS code as I’m building my Docker from scratch.

**Comment by NGPixel** [comment]
https://github.com/Requarks/wiki/blob/d05f6821842da5c5d8e0ee56815c68b2aa080e93/server/libs/auth.js#L239

It's not something you can simply copy paste on its own though, you need the mongoose orm with a valid connection.

**Comment by ankh2054** [comment]
Thanks Nicholas,

Much appreciated, I will give it a go :)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
