### ISSUE TITLE
Explicitly state that wiki docs.requarks.io/wiki is a live demo

### ISSUE THREAD

**Issue by RayBB** [Requarks/wiki#334]
When I found this repo I was searched for a demo in the repo and the docs but was baffled that there was no life example up.

I ended up just setting it up with Heroku really quick and then was surprised to realize that docs.requarks.io/wiki is basically a demo. It was just so beautiful and well done that I hadn't realized it.

I'm just suggesting that somewhere you explicitly write that it's a demo so that it's easier for people to realize (I now notice that it says powered by wiki.js at the bottom of the docs page).

Alternatively, it would be nice to have a demo setup where people could actually login and edit pages  so they can see the editor side. Then just have the demo auto reset / delete every hour or so.

Thanks for the great software!

PS: The software works fairly well on mobile but is a little rough around the edges. Maybe mention on your readme whether or not you plan to make it fully mobile friendly.

**Comment by NGPixel** [comment]
Thanks! Added some text on the README page.

2.0 will be fully optimized for mobile.
