### ISSUE TITLE
Node.js version is too old. Minimum is v6.6.0 while installing wiki.js

### ISSUE THREAD

**Issue by sach589** [Requarks/wiki#336]
My current node.js version is :

```
node --version

v9.2.0
```

But when i am going to configure wiki.js by node wiki configure getting response :

Browse to `http://localhost:3000` to configure Wiki.js!

By Browsing `http://localhost:3000` i am getting this error :

`Node.js version is too old. Minimum is v6.6.0`
[https://stackoverflow.com/questions/47546114/wiki-js-node-js-version-is-too-old-minimum-is-v6-6-0-while-installing-wiki-js](url)

![screenshot-2017-11-29 wiki js configure](https://user-images.githubusercontent.com/34086507/33360990-2ef31dce-d4fc-11e7-9441-9dde9a4c48a9.png)

**Comment by Bamieh** [comment]
how are you running the wiki? are you using any form of containers?

**Comment by NGPixel** [comment]
Looks like you're running Wiki.js using another version of Node.js. Make sure the process launching Wiki.js is actually referencing your node 9.2.0 version.

(btw, the "solution" you posted on stackoverflow is wrong. You're simply negating the condition, this is not a fix!).

**Comment by MichaelHabib** [comment]
I had the same problem & noticed that : Even after node update, the terminal instance still referenced the old node version so starting a new terminal then running ```node wiki configure``` worked for me.
