### ISSUE TITLE
Malfunction in Code Block

### ISSUE THREAD

**Issue by RixzZ** [Requarks/wiki#34]
Hello,

I noticed that some characters can break the code block.

Like this command:
![captura de pantalla 2017-03-16 a las 4 55 02](https://cloud.githubusercontent.com/assets/1339272/23981173/de13b264-0a04-11e7-8b65-d2eedc33d9f7.png)

When you save it appears like this:
![captura de pantalla 2017-03-16 a las 4 54 52](https://cloud.githubusercontent.com/assets/1339272/23981177/e50832c0-0a04-11e7-8a5d-a519015d9b2a.png)

Can it be fixed?

Thanks in advance.

**Comment by NGPixel** [comment]
Fixed for Beta 12 (4632330d7c8a9fa1bfb231c222e393658b95d707) (#118)
