### ISSUE TITLE
[Question] Is this a correct way to workaround with custom port configuration?

### ISSUE THREAD

**Issue by deforder** [Requarks/wiki#342]
I've encountered some problem when I choose not to use the default port (80/443) which cause browser to load incorrect path for resource files( see #296 and #339 for more details).

Therefore, I have changed one statement in `server/configure.js` to resolve this issue but I don't know that this will be the correct way or it will break other part of the code.

Original Statement

`conf.host = req.body.host`

to

`conf.host = req.body.host+((req.body.port != "80" && req.body.port != "443")?":"+req.body.port:"")`

This will change host parameter value in config.yml from `host` to `host:port`.

Is this the right way to fix the issue?

**Comment by NGPixel** [comment]
Port and host are 2 completely concepts. Port is what the server listens on while host (which can include a port) is what the client use to access the site. When using reverse proxies, both ports will usually have completely different values.

You're supposed to include the port in the host value if different than 80/443.

**Comment by LionNatsu** [comment]
I think the best way to prevent such misconfiguration is explaining this explicitly on the configure guide. As you just explained, the word Host could be ambiguous. It is usually and basically a "hostname" or domain or IP address. But when we talk about Application Layer (e.g. HTTP/HTTPS here), it may include the port.

A few examples for users (web masters) will be enough, I think.

"e.g. 123.123.123.123, wiki.yourdomain.com, localhost, localhost:3000, wiki.example.com:5000. In short, the part in URL which is following :// and before /"
