### ISSUE TITLE
SSH connection to git on non-standard port

### ISSUE THREAD

**Issue by dsukhin** [Requarks/wiki#346]
### Actual behavior

When setting up wikijs, I am trying to add my remote git server. I run ssh on port 2200 instead of 22 so provided a url in the form ssh://git.domain.com:2200/user/repo 

When wikijs goes to test this, it returns

> Error: ssh: Could not resolve hostname git.domain.com:2200: Name or service not known
 Could not read from remote repository. Please make sure you have the correct access rights and the repository exists.

### Expected behavior

I would have expected wikijs to connect properly instead of trying to resolve the hostname with the port attached. Is there another way to do this?

### Steps to reproduce the behavior

See "Actual behavior" section for steps to reproduce

**Comment by dsukhin** [comment]
I got around this by using HTTP and simple authentication.... would have liked to use ssh but this bug made it impossible

**Comment by NGPixel** [comment]
Have you tried formatted as `user@git.domain.com:2200/user/repo.git` instead?

**Comment by b-douglas** [comment]
Hey also, you could do a docker build and setup your SSH config to get it to work.

The following would help.

```echo '
Host github
     User git
     Hostname github.com
     IdentityFile ~/.ssh/github.key
     Port 2200
' > /root/.ssh/config
```

Then your git setup would simply be `github:/user/repo.git`

Hope this helps!

I use ssh config to setup git all the time.  It makes it much easier to get all the parameters correct.

Note: If this is a docker, you would have to add those lines to your Dockerfile, and do a docker build to build a custom image.

But, that's super easy.

**Comment by vnkmpf** [comment]
I have problem with custom port in version 2.0.12.
I set method ssh, provide url in the following format: `user@my.git.server:2222/foo/bar.git` and it doesn't work.
My hack is to edit `git/storage.js` - add `-p 2222` to `ssh command` and then provide URL without port, but with `ssh://` scheme. Which is bad, but is the one way I made it work.
This is however rewritten after saving git administration page.

Can you please add a custom port input in git administration?
