### ISSUE TITLE
Confirm before navigating away from create/edit page

### ISSUE THREAD

**Issue by ryanilg** [Requarks/wiki#35]
It would be great to have a (javascript) confirmation before allowing the user to navigate away from a create or edit entry page, if content has been enter or has changed.

I have lost quite a few changes by accidentally navigating away. Since the editor does not use a standard text area, text is not retained when you switch pages.

I personally have "swipe back and forth" enabled on my mac, and I am constantly loosing edits.

**Comment by NGPixel** [comment]
Moved ticket to Feature Board: https://wikijs.canny.io/features/p/confirm-before-navigating-away-from-createedit-page

Closing this ticket.
