### ISSUE TITLE
VERSION not resolving in install.sh

### ISSUE THREAD

**Issue by justin-calleja** [Requarks/wiki#350]
In `install.sh` the following is not resolving:
```
VERSION=$(curl -L -s -S https://beta.requarks.io/api/version/stable)
```

### Actual behavior
Doesn't work (VERSION variable doesn't get set).

### Expected behavior
Proper install.

### Steps to reproduce the behavior

Follow this instruction in getting started [install guide](https://docs.requarks.io/wiki/install):

```
curl -sSo- https://wiki.js.org/install.sh | bash
```

**Comment by NGPixel** [comment]
It's now back online.
