### ISSUE TITLE
Wiki fails to start in normal mode.

### ISSUE THREAD

**Issue by mikeymop** [Requarks/wiki#351]
### Actual behavior
I started `node .\Wiki.js configure` in powershell
I browse to localhost:3000 and complete the setup.

It says it will now reload into normal mode and my prompt in ps says the same.
It never happens however. I tried setting my site in setup to 127.0.0.1, to localhost:80 localhost:8080 and localhost:3000 to no avail.

When this happens, I am given a log file, and the error 
```ps
× Error: EPERM: operation not permitted, lstat 'C:\Users\michaeld\Documents\Wiki\jswiki\logs\wiki-output-0.log'
```
Is printed, however I cannot take ownership or even read the log files. I tried to take it as admin and I cannot either.
### Expected behavior
finishing wiki.js config or runnings `node .\wiki.s start` would open the server on my specified url (localhost).

### Steps to reproduce the behavior
```ps
> node -v
v9.3.1
> npm -v
5.4.1
> node .\wiki.js configure
browse to localhost:3000!!
#freezes at rebooting into normal mode
^C
> node .\wiki.js start
Error: EPERM: operation not permitted.
```

**Comment by NGPixel** [comment]
- Try with an LTS version of node (8.9.3)
- Use `node wiki start`. No need to write the whole path and file extension...
