### ISSUE TITLE
Question : Can i add pages and structures directly to GitHub to upload my wiki ?

### ISSUE THREAD

**Issue by Neuliaus** [Requarks/wiki#357]
### Upload new .md files to github and re configure wiki via terminal

AWS EC2 t2.medium 
Private GitHub repo
HTML to markdown converted keeping HTML div, and formats (work when done directly to wiki)

If now available happy to move this to request, just not sure if can be done

**Comment by NGPixel** [comment]
Yes you can add content directly via GitHub. New content or modifications will be synced every 5 minutes automatically.
