### ISSUE TITLE
Descending multiple directories in /uploads

### ISSUE THREAD

**Issue by joshuaauger** [Requarks/wiki#358]
### Actual behavior
When mounting a location or symlinking to /uploads it only traverses one directory down.
### Expected behavior
When browsing files you should see subdirectories
### Steps to reproduce the behavior
Create /uploads/test/test/test.mp4 and you cannot see it, but /uploads/test/test.mp4 works.

**Comment by NGPixel** [comment]
Not a bug. This is as designed.

You can submit a feature request for 2.0 though:
https://requests.requarks.io/wiki
