### ISSUE TITLE
Failure to Configure and Start - Ubuntu

### ISSUE THREAD

**Issue by B1ue-W01f** [Requarks/wiki#361]
Im trying to install and run wiki.js on Ubuntu Server.

I'm able to get through configuration but wiki.js wont launch in normal mode and terminal is full of errors along the lines of: 

`Error: EACCES: permission denied, mkdir /home/bluewolf/.pm2`

Thats not where the application or node_modules are already installed (all are under /srv/wiki.js), it wouldnt ever be where they are installed and all methods of installing, from using npm (eww) to manually placing the files results in exactly the same issue.

Google is full of related npm issues and I'm all out of ideas.

**Comment by NGPixel** [comment]
give write permissions to the user running wiki.js for path `/home/bluewolf/.pm2`

This is where the process management library is storing its configuration. If you don't want to use the process management, you can instead start Wiki.js using command `node server`.
