### ISSUE TITLE
Lose All Pages information 

### ISSUE THREAD

**Issue by agaubert** [Requarks/wiki#362]
### Actual behavior

I can create new pages and it is displayed in the section all pages, except when I reboot the container and I reconnect on the home page I have nothing in the section all pages.

yet these pages created previously are well saved ( thanks to my volume ^ ^) and I find them well in the repo directory of my container.

### Expected behavior

Keep the data in the section " all pages " after container reboot.

### Steps to reproduce the behavior

**my config.yml configuration :** 

host: https://mysite.com
port: 443

paths:
  repo: ./repo
  data: ./data

db: mongodb://wikidb:27017/wiki

**my docker-compose.yml configuration :**

version: '3'
services:
  wikidb:
    image: mongo
    expose:
      - '27017'
    command: '--smallfiles --bind_ip wikidb'
    environment:
      - 'MONGO_LOG_DIR=/dev/null'
    volumes:
      - ./data/mongo:/data/db
  wikijs:
    image: 'requarks/wiki:latest'
    links:
      - wikidb
    depends_on:
      - wikidb
    ports:
      - 127.0.0.1:3000:443
    environment:
      WIKI_ADMIN_EMAIL: admin@example.com
    volumes:
      - ./config.yml:/var/wiki/config.yml
      - ./data:/var/wiki/data
      - ./repo:/var/wiki/repo

If you want more information like logs do not hesitate to ask me ^^

**Comment by NGPixel** [comment]
Try to disable mathjax in your config.yml:

```yaml
features:
  mathjax: false
```

**Comment by agaubert** [comment]
I have disable mathjax in my config.yml but i've the same issue ^^'

Thank you for answering me so quickly

**Comment by agaubert** [comment]
Do you have any other advice?

**Comment by NGPixel** [comment]
Have you checked for errors in the /logs files?
