### ISSUE TITLE
How does one reset the administrator password?

### ISSUE THREAD

**Issue by p-na** [Requarks/wiki#366]
It seems like there's no (documented) way of resetting the administrator password. Could you please describe how to generate a hashed password, so that I'd be able to replace the hash in the database (if that's possible)?

**Comment by NGPixel** [comment]
Run the configuration wizard to change the admin password.

```
node wiki stop
node wiki configure
```

**Comment by Starefossen** [comment]
So that did not work in the latest version; I had to go into PostgreSQL in order to reset my admin password like this:

```
psql -u wikijs -p wikijsrocks
\c wiki
PREPARE passwordreset (int, text) AS UPDATE users set password=$2 where id = $1;
EXECUTE passwordreset(1, '$2y$12$pVvLBrwZhfIPGI23dcnWduCb8zT304F4RCCDh7MREAJ1k1EBJEfSq');
```

This will change your password to `changeme` and you can log in and change it via the admin ui.

**Comment by AaronNGray** [comment]
once you have change the administrator's password using PostgreSQL as above resetting it in the browser does not work anymore and the passwords lost.

I am using an IP on a local network :-

    http://192.168.1.128:3000/a/users/1
