### ISSUE TITLE
SSH issue on Ubuntu 16.04

### ISSUE THREAD

**Issue by robin-lc** [Requarks/wiki#367]
Hello,

I'm trying to install Wiki.js on Ubuntu 16.04 (lightsail instance).
Problem is: i can't connect Wiki.js to my github repo using ssh.

After running `node wiki configure` everything is working fine until git check:  `Permission denied (publickey). Could not read from remote repository. Please make sure you have the correct access rights and the repository exists.`

I generated my ssh keys with `ssh-keygen -t rsa -b 4096 -C "your_email@example.com"` in `/home/ubuntu/.ssh/`. I added the private key to ubuntu with ssh-add and i copied the public key to my github account.

I tried to debug with tips on this page: https://help.github.com/articles/error-permission-denied-publickey/ but it didn't work.
When i run `ssh -vT git@github.com` in a terminal, it works: `Hi! You've successfully authenticated, but GitHub does not provide shell access` but when wiki.js is trying to connect, it doesn't.
I installed it first on a local VM with the same process and it worked too.

Other things i tried:
* add `PubkeyAcceptedKeyTypes +ssh-dss` in /etc/ssh/ssh_config and in ~/.ssh/config
* add manually public key in `authorized_keys` file in ~/.ssh/
* "Skip this step" button to configure git manually
* using basic auth with a token

Do you have any idea to help me?

**Comment by NGPixel** [comment]
The user wiki.js runs on most likely doesn't have read access to your ssh key.

The key must be accessible + readable by wiki.js process and not passphrase encrypted.

**Comment by robin-lc** [comment]
Hi,
Thanks for your answer :)
I checked which user were running wiki.js but it wasn't the problem. Actually, I didn't find a solution to this problem so i finally tried on a new instance running Amazon Linux and it works :)
