### ISSUE TITLE
Loss all pages after container removal

### ISSUE THREAD

**Issue by hobogithub** [Requarks/wiki#368]
Hello!

I run wiki.js in docker with docker-compose.yml and config.yml from examples. I have mongodb volume on my host. Everything is working. I'm creating home page. I stop and start docker. All my data are in place. But when I remove containers and create it again I loss all pages. In this case, the user created earlier is saved.

I would be grateful for any advice.

**Comment by tomjsalmon** [comment]
It sounds like your DB is fine, but your repo connection is failing.
Are you using SSH or HTTPS for the git repo? Have you confirmed your SSH key or username/password?
You can get into the wikijs container by running `docker-compose exec wikijs /bin/bash`. From there you can check /logs/wiki-stderr.log to see if it is logging any errors.

As a workaround you could also mount /var/wiki/repo as a volume, so you don't lose the data when git pushes fail.

**Comment by hobogithub** [comment]
Thanks for the answer. Yes, the problem was a repos. I added volume for /var/wiki in docker-compose file, and I have all my info after remove containers.

**Comment by mdanetzky** [comment]
Please change the manuals to reflect this information.
We just lost two weeks of work, because we assumed, that all pages are stored in mongodb.
