### ISSUE TITLE
Showing "modal.[text]" instead of just "[text]"

### ISSUE THREAD

**Issue by Andre601** [Requarks/wiki#369]
### Actual behavior
Things like the searchbar or the confirm/discard buttons show text like "search.placeholder" or "modal.create"
### Expected behavior
It should show "search" or "create" f.e.
### Steps to reproduce the behavior
Most likely a issue on installation.
Is there a way to fix that?

**Comment by NGPixel** [comment]
Which language are you using? And do you have any errors in the browser consoles upon loading the page?

**Comment by Andre601** [comment]
english.

And I get a error about mixed content (The site has https through cloudflare, but some content like http://wiki.powerplugins.net/js/i18n/en.json gets blocked.)

**Comment by NGPixel** [comment]
That's because your `host` parameter in your `config.yml` is using `http://` instead of `https://`

**Comment by Andre601** [comment]
Changing it to https should change it then, right?

**Comment by Andre601** [comment]
Ok.
The mentioned issue is fixed, but there's still the message about the DevTools.
Can that be ignored?

**Comment by NGPixel** [comment]
You can ignore yes.
