### ISSUE TITLE
Handle long lines of code

### ISSUE THREAD

**Issue by koallen** [Requarks/wiki#37]
Currently if a block of code it too long, the whole page will become that long. Could you make the code block scroll like how GitHub handles such situations?

```
This is a loooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooong line of code
```

**Comment by NGPixel** [comment]
Fixed for Beta 10

3c637183284cee12cf9ea3788461e1d8d3600578
