### ISSUE TITLE
Microsoft account login is overlapped

### ISSUE THREAD

**Issue by CheHaoKang** [Requarks/wiki#371]
### Actual behavior
The **Microsoft login account** is overlapped by "**Powered by Wiki.js**".
https://i.imgur.com/zQXDY6Z.png

### Expected behavior
Not overlapped

### My settings
https://i.imgur.com/0GEuS7j.png

**config.yml**
>>>>>>>>>
title: Wiki
host: 'http://localhost'
port: 80
paths:
  repo: ./repo
  data: ./data
uploads:
  maxImageFileSize: 3
  maxOtherFileSize: 100
lang: en
langRtl: false
public: false
auth:
  defaultReadAccess: false
  local:
    enabled: true
  google:
    enabled: true
    clientId: GOOGLE_CLIENT_ID
    clientSecret: GOOGLE_CLIENT_SECRET
  microsoft:
    enabled: true
    clientId: MS_APP_ID
    clientSecret: MS_APP_SECRET
  facebook:
    enabled: false
    clientId: FACEBOOK_APP_ID
    clientSecret: FACEBOOK_APP_SECRET
  github:
    enabled: false
    clientId: GITHUB_CLIENT_ID
    clientSecret: GITHUB_CLIENT_SECRET
  slack:
    enabled: false
    clientId: SLACK_CLIENT_ID
    clientSecret: SLACK_CLIENT_SECRET
  ldap:
    enabled: false
    url: 'ldap://serverhost:389'
    bindDn: cn='root'
    bindCredentials: BIND_PASSWORD
    searchBase: 'o=users,o=example.com'
    searchFilter: '(uid={{username}})'
    tlsEnabled: false
    tlsCertPath: 'C:\example\root_ca_cert.crt'
  azure:
    enabled: false
    clientId: APP_ID
    clientSecret: APP_SECRET_KEY
    resource: 00000002-0000-0000-c000-000000000000
    tenant: YOUR_TENANT.onmicrosoft.com
  oauth2:
    enabled: false
    clientId: OAUTH2_CLIENT_ID
    clientSecret: OAUTH2_CLIENT_SECRET
    authorizationURL: OAUTH2_AUTH_URL
    tokenURL: OAUTH2_TOKEN_URL
sessionSecret: cf3db30db32c85cd07a4e821eec56688484110e9e8524ab66a28627db003a6a0
db: 'mongodb://localhost:27017/wiki'
git: false
features:
  linebreaks: true
  mathjax: true
externalLogging:
  bugsnag: false
  loggly: false
  papertrail: false
  rollbar: false
  sentry: false
theme:
  primary: indigo
  alt: blue-grey
  viewSource: all
  footer: blue-grey
  code:
    dark: true
    colorize: true
<<<<<<<<<

Thanks for all your efforts,
Kang

**Comment by NGPixel** [comment]
Wiki.js 1.x has partial support for mobile or very small resolution screens. 2.0 will have a fully responsive layout.

This behavior is already fixed in 2.0.

**Comment by CheHaoKang** [comment]
Gorgeous!!!
Thanks for the update.
