### ISSUE TITLE
unable to bind git account

### ISSUE THREAD

**Issue by CheHaoKang** [Requarks/wiki#374]
### Actual behavior
When binding the git account, it always says **Error: Couldn't find remote ref master**
https://i.imgur.com/rklHLd2.png

I've followed the document [https://docs.requarks.io/wiki/install/git](https://docs.requarks.io/wiki/install/git).
Furthermore, I am sure the git project exists, the username and password are correct.
https://i.imgur.com/0VqP3lt.png

However, the binding still fails.

### Environment
https://i.imgur.com/39JcPE5.png

Thanks,
Kang

**Comment by NGPixel** [comment]
Your remote repository is not initialized.

**Comment by CheHaoKang** [comment]
Thanks for the pretty fast reply.

I create the init commit.
https://i.imgur.com/stUGmZ8.png

Now, the message becomes **Error: no common commits From https://github.com/CheHaoKang/wiki * branch master -> FETCH_HEAD * [new branch] master -> origin/master refusing to merge unrelated histories**.
https://i.imgur.com/GOjMI8n.png

Is there anything I am missing?

Thanks,
Kang

**Comment by NGPixel** [comment]
Delete the local `/repo` folder and try again.

**Comment by CheHaoKang** [comment]
Thank you very much.
It works.

Kang

**Comment by CrazyCxl** [comment]
I meet the same error.
My solution is to enter `./repo` and run `git remote add origin https://github.com/xxx/xxx.git`

**Comment by elaich** [comment]
I'm having this same issue, can you help me out?

I delete the local `./repo` folder but the error is still there.

`fatal: refusing to merge unrelated histories`

My remote git repository is initialized.

**Comment by koxon** [comment]
Hello, 
I got the issue on Heroku. I'm running the beta version. 
How can I resolve this ?

thank you
