### ISSUE TITLE
Search bar - Searching articles 

### ISSUE THREAD

**Issue by den1622** [Requarks/wiki#376]
I'm wondering how the searchbar function works in wiki.js. 

I thought it worked from headers to pull pages, but am getting some inaccurate results from searching. 

Is there any format I can adopt to get better results and sharper searching? 
![2018-01-17 11_56_42-tbc knowledgebase](https://user-images.githubusercontent.com/30255659/35020766-92ea9e7c-fb7d-11e7-8f86-e703d657d998.png)

**Comment by NGPixel** [comment]
It's a weight-based search:

- title: +3
- path: +2
- subtitle: +1
- content: 0

The title field can match 2 consecutive words, while other fields match only 1.

The built-in search engine will be much more accurate in 2.0. And will accept 3rd party search engines as well.
