### ISSUE TITLE
Horizontally long tables do not have a scroll bar

### ISSUE THREAD

**Issue by Sabinno** [Requarks/wiki#3761]
### Info
OS: CentOS 8.4
Wikijs version: docker 2.4.170
Db engine: postgresql

### Actual behavior
Tables are cut off by the horizontal edge of the browser's viewport

### Expected behavior
Tables should have their own scrollbar or, less ideally, the entire page should at least have a scrollbar if there is content that is unable to wrap

### Steps to reproduce the behavior
1. Create a table that is longer than the browser viewport (very easy for mobile browsers)
2. View it

**Comment by Sabinno** [comment]
Updated op

**Comment by NGPixel** [comment]
Please post under **Discussions**, not Issues.
