### ISSUE TITLE
what about supporting tables in the markdown

### ISSUE THREAD

**Issue by lafar6502** [Requarks/wiki#377]
### Actual behavior

'Table support coming soon' message when trying to add a table

### Expected behavior

You know what is expected. Essential function - no alternative

**Comment by NGPixel** [comment]
A table editor is coming in 2.0.

In the meantime you can still write them using markdown syntax or use an online table generator:
https://www.tablesgenerator.com/markdown_tables

**Comment by lafar6502** [comment]
thanks, i wasnt aware tables are supported in markdown.
