### ISSUE TITLE
docs.wiki.requarks.io SSL error

### ISSUE THREAD

**Issue by alexanderpepper** [Requarks/wiki#38]
There seems to be an SSL issue with docs.wiki.requarks.io. 
I get ERR_SSL_PROTOCOL_ERROR when trying to go there.

Looking forward to being able to try out your Wiki software.

**Comment by NGPixel** [comment]
Yes I noticed intermittent issues with the SSL. (works for me atm, but had the same issue yesterday). I'll investigate the issue.

**Comment by NGPixel** [comment]
Problem has been fixed.

Documentation can now be accessed at https://docs.requarks.io/wiki
