### ISSUE TITLE
Searching Korean Does Not Work

### ISSUE THREAD

**Issue by channprj** [Requarks/wiki#380]
### Actual behavior
> Note: It's similar to #148, #184, and I think these are the almost same issue.

There is no result when searching Korean.

### Expected behavior
Should return relevant search results.

#### OS:
macOS High Sierra

#### Browser:
Google Chrome v63.0.3239.132

#### Step:

1. Create a page with Korean
2. Search in Korean
3. Search result is empty

**Comment by NGPixel** [comment]
Non-latin characters will be fully supported in 2.0.

**Comment by lifeisdream** [comment]
Does that mean that Russian symbols don't work at search as well before 2.0 release? 
I can't search currently by rus =(
