### ISSUE TITLE
Folder name in each document page

### ISSUE THREAD

**Issue by vnerozin** [Requarks/wiki#382]
Is it possible to avoid duplicating documents folder name in each page name?
<img width="442" alt="screen shot 2018-01-24 at 15 26 25" src="https://user-images.githubusercontent.com/10763628/35332374-d1ad9166-011b-11e8-9c2c-64832c2bb483.png">

**Comment by nicolasg-playster** [comment]
This behavior occurs because you didn't specify a title for your pages. Set a a proper title to each and that title will be displayed in the All Pages section.

**Comment by vnerozin** [comment]
Thank you!
