### ISSUE TITLE
Database Connection Error: 3D000 undefined:undefined

### ISSUE THREAD

**Issue by Bambiee** [Requarks/wiki#3928]
What is this thing that prevents me from going forward??

Database Connection Error: 3D000 undefined:undefined

I'm trying to install it on mac, and it sent me this error at the final step: node server

**Comment by WeebHiroyuki** [comment]
Can you show us a template of your configuration file?

**Comment by Bambiee** [comment]
i can send you a screenshot of it... im not a tech guy...


> Can you show us a template of your configuration file?

i can send you a screenshot of it... im not a tech guy...
link:https://drive.google.com/file/d/1CCmoSWwzFYqWMtLnVHqZBO63jMXzJN8S/view?usp=sharing
