### ISSUE TITLE
public: true doesn't work

### ISSUE THREAD

**Issue by DawidCh** [Requarks/wiki#40]
Hello.
I have installed wiki.js and set public: false at the begining. Now I would like to have it installed in public mode. I have modified properties, restarted application but it still asks me for credentials, and says that I do not have rights to see home page. how to fix that?
Regads, Dawid.

**Comment by NGPixel** [comment]
Does the Guest account have Read rights on the root path?

**Comment by DawidCh** [comment]
Yes, I set them but I had to restart the wiki. Now it works.
Thanks.
