### ISSUE TITLE
Limit scope with GoogleID

### ISSUE THREAD

**Issue by kevinmui** [Requarks/wiki#400]
Hi, is there a way to limit the scope of who can access the wiki when utilizing GoogleID?  Currently, anyone with a valid Google+ can access (mute since we'd need to manually set Role), but that means that an e-mail needs to be preemptively created under users.

Is there a way so that, anyone with a specific @domain.com (using Google OAuth, or in this case "GoogleID") be able to log in as Read Only?

Thanks

**Comment by NGPixel** [comment]
Planned for 2.0:
https://requests.requarks.io/wiki/p/whitelist-domains-for-google-auth-provider
