### ISSUE TITLE
The server is down..

### ISSUE THREAD

**Issue by HO2AST** [Requarks/wiki#4039]
Your server is down with some messages below

Docker Flow Proxy: 503 Service Unavailable
No server is available to handle this request.

**Comment by AjdinDev** [comment]
@NGPixel Issue is still present.

**Comment by kapenzo** [comment]
Still present.
![image](https://user-images.githubusercontent.com/16196222/120333533-15e1ef00-c2f0-11eb-8645-b8a7f33df84e.png)

**Comment by NGPixel** [comment]
The issue is being investigated...
