### ISSUE TITLE
Having too many images in one upload folder results in the image select tool to become unusable

### ISSUE THREAD

**Issue by james7132** [Requarks/wiki#406]
### Actual behavior
Too many images expands the dialog beyond the scope of the browser screen.
### Expected behavior
Some scroll mechanism that keeps the Add control on-screen and allows scrolling through the uploaded images.
### Steps to reproduce the behavior
1. Upload a large number of images to the same directory.
1. Click the image tool.
1. Select the aforementioned directory.
1. See the "Discard" and "Insert Image" controls move off the screen.

Screenshot of this happening.
![image](https://user-images.githubusercontent.com/3137680/36142125-fd52acd0-105b-11e8-8723-a8486e1056f8.png)

**Comment by gordosgithub** [comment]
This issue has been posted a bunch, the devs don't seem to care to fix it by adding a simple overflow:scroll  to the CSS for the image/folder viewer. Every time the issue gets re-posted they just label it "duplicate" or "deferred" even though it literally makes the wiki unusable.

We had to fix it ourselves in our own files, here's a duplicate issue with a solution in comments https://github.com/Requarks/wiki/issues/311

**Comment by NGPixel** [comment]
Fixed in 1.0.76

@gordosgithub The fastest way to get something fixed is to submit a PR.
