### ISSUE TITLE
Oauth does not give read access

### ISSUE THREAD

**Issue by monoxane** [Requarks/wiki#408]
### Actual behavior
Oauth authorised accounts return an email error

![screenshot from 2018-02-17 14-24-45](https://user-images.githubusercontent.com/16844830/36337620-656dc10c-13ee-11e8-8a89-8c07709c5d7e.png)

### Expected behavior
Oauth accounts get read only access to the wiki if they are not in the user db with write access

### Steps to reproduce the behavior
1. set the following
```public: false
auth:
  defaultReadAccess: true
  local:
    enabled: false
  oauth2:
    enabled: true
    clientId: xxx
    clientSecret: xxx
    authorizationURL: https://xxx
    tokenURL: https://xxx
```
2. log in via oauth (need to patch the oath button on the login screen as @NGPixel discovered)
3. ???
4. no profit (get the error from above)

### Other info
using docker-compose file according to the install wiki, on debian 8

**Comment by NGPixel** [comment]
As discussed on Gitter, this is caused by a non-standard oauth response.

**Comment by monoxane** [comment]
Yeap, sorry, forgot to close this.
