### ISSUE TITLE
Redirect to port

### ISSUE THREAD

**Issue by roccosette** [Requarks/wiki#409]
Hi !

I'm trying to install Wiki.js on my serveur, but where i go to the port 3000 with m browser, i have an CSS error.

On the dev tab, i see Wiki.js trying to access localhost app.js without port 3000. How can i fix that ?

Thank's

**Comment by NGPixel** [comment]
Your `host` config is wrong. You must add the port :3000 in the host.

**Comment by roccosette** [comment]
Where ?

**Comment by NGPixel** [comment]
In your config.yml file.

**Comment by roccosette** [comment]
It's work, thank's :)
