### ISSUE TITLE
Save

### ISSUE THREAD

**Issue by roccosette** [Requarks/wiki#410]
Sorry again for this topic, but how to save and restore data ?

Just save the data directory ?

**Comment by NGPixel** [comment]
No. The data directory contains cache and other temporary files.

Only the `/repo` folder is required.
It is also a good idea to backup the DB, however it doesn't contain any actual content data. Only users.

**Comment by roccosette** [comment]
So articles created are in the repo folder ?

**Comment by NGPixel** [comment]
yes
