### ISSUE TITLE
Creating Redirection custom views

### ISSUE THREAD

**Issue by primetoxinz** [Requarks/wiki#4147]
### Discussed in https://github.com/Requarks/wiki/discussions/3912

<div type='discussions-op-text'>

<sup>Originally posted by **primetoxinz** May  4, 2021</sup>
Currently running 2.5.170 and went to make a Redirection custom view
![image](https://user-images.githubusercontent.com/4721642/117053909-87298480-ace7-11eb-920e-99752e3dffd3.png)
And found that the button does not work.

I went and investigated the [source](https://github.com/Requarks/wiki/blob/f55caab359ca7715012e3f9a3b9e31f16cccf399/client/components/editor/editor-modal-editorselect.vue#L126) and found that this action is commented out.

Is there a plan to readd this feature? 

</div>

**Comment by Wdavery** [comment]
That is a coming soon feature, slated for v3.0 I believe.
