### ISSUE TITLE
Problem of Wiki Page and Directory in Chinese

### ISSUE THREAD

**Issue by choicky** [Requarks/wiki#42]
Hi, thanks for this wiki.

I install the latest version and do some testing.

If a wiki page name is in Chinese, it's shown correctly in web browser. However, in `repo` directory it's not save in Chinese, such as `e6b58be8af951.md`.

If a wiki page is inside a directory in Chinese, the directory is shown correctly in web browser.  However, in `repo` directory it's `e6b58be8af95`.

**Comment by NGPixel** [comment]
This is most likely a side-effect of the path conversion to kebab-case. I would suggest using alphanumerical characters in filenames for now. You can still use Chinese when defining the title and subtitle of pages.

**Comment by KimDaesap** [comment]
I have the same problem.
I use Korean, but the characters are not displayed correctly in document name and <! - TITLE ...>, <! - SUBTITLE: ...>.

**Comment by NGPixel** [comment]
Just like #65, non-alphanumerical characters are not recognized when parsing the title and subtitle tags. This will be fixed soon.

**Comment by choicky** [comment]
@NGPixel Appreciated.  Waiting for the update.

**Comment by NGPixel** [comment]
@KimDaesap Do you have an example where Korean content in TITLE and SUBTITLE are not displayed?

I tested with:
```
<!-- TITLE: 이미지 -->
<!-- SUBTITLE: 이미지 -->
```
and it displays just fine.

**Comment by KimDaesap** [comment]
When creating a document in Korean <! - TITLE: -> and <! - SUBTITLE: ...> also appears in the content, such as the document name.
Of course, it is not a problem to fix it in Korean.

* create document
![1](https://cloud.githubusercontent.com/assets/5153125/25048601/409317d8-2178-11e7-8605-2fd7e6c69e42.png)

* template
![2](https://cloud.githubusercontent.com/assets/5153125/25048605/43a3a8de-2178-11e7-9b58-4a14cb213d67.png)

**Comment by NGPixel** [comment]
Fixed for Beta 11 (fe313baf67cfd73d5eee041f96ec3b27be59c16a)
