### ISSUE TITLE
The home button in the page path (upon the page content) always redirects to the base locale

### ISSUE THREAD

**Issue by krolsekat** [Requarks/wiki#4210]
The home button in the page path (upon the page content) redirect to the principal language home page whatever the language choosed.
@NGPixel, do you confirm that this message and the previous are in the same ticket?

_Originally posted by @ba-moun in https://github.com/Requarks/wiki/discussions/3696#discussioncomment-508678_

I'm also experiencing the same behaviour.

**Comment by NGPixel** [comment]
Please don't open duplicate tickets.
