### ISSUE TITLE
spell check tools do not work in wiki editor

### ISSUE THREAD

**Issue by timeandtimeago** [Requarks/wiki#424]
No spell check tools work when editing content in the wiki editor. 
Not even built-in chrome spell check works. 
I have also tried downloading Grammarly and similar tools to try and get spell checking working on the wiki editor.

Is there any way to make spell check tools recognize the content for spell checking?

**Comment by NGPixel** [comment]
Short answer: **no**

Long answer: The editor is using SimpleMDE, which is using CodeMirror. CodeMirror isn't a standard textbox. There's an [issue](https://github.com/codemirror/CodeMirror/issues/1017) opened on the codemirror repo if you want to track it, but so far it's not happening.

If it's implemented in CodeMirror, then it will be available in Wiki.js.

**Comment by dweremeichik** [comment]
I'm seeing no spell checking in Firefox, everything from this issue only references Chrome.
Is there any reason that spellcheck is set to false on the codemirror div?

Additionally, if Codemirror is really that bad at handling spelling (arguably an important feature), have you considered other options?
I realize that this was marked as "wontfix", however from the outside looking in at the projects goals and current tool set: wouldn't it make sense to leverage something like [tiptap](https://tiptap.scrumpy.io/)? Its powered by VueJS and Prosemirror. Note that in the examples spellcheck is [turned off](https://github.com/scrumpy/tiptap/blob/daa2776ced29c724740d812f6f84c5e5f4b57e8e/examples/Components/App/index.vue). 

You can do a lot more with tiptap than you can with SimpleMDE. It will give you the ability to easily add tables, it has a collaboration module, and more.
Side note: Prosemirror is made by the same guy that made Codemirror.

**Comment by NGPixel** [comment]
V2 is no longer using SimpleMDE so this topic is no longer relevant.

**Comment by dweremeichik** [comment]
👍 will open a new issue.
