### ISSUE TITLE
Updating the wiki system fails under Windows 2012 server

### ISSUE THREAD

**Issue by lafar6502** [Requarks/wiki#429]
Trying to update wiki.js to recent version
npm update

### Actual behavior
error message at the end of npm update:

'opencollective' is not recognized as an internal or external command,
operable program or batch file.
wiki@1.0.12 F:\unitech\wiki
+-- i18next-express-middleware@1.0.11
+-- mongodb@2.2.35
+-- search-index-adder@0.3.11
+-- stopword@0.1.10
`-- vee-validate@2.0.5

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\ch
okidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}
)
npm WARN enoent ENOENT: no such file or directory, open 'F:\unitech\wiki\node_mo
dules\constantinople\node_modules\is-expression\package.json'
npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none was installed
.
npm WARN @vue/test-utils@1.0.0-beta.12 requires a peer of vue-server-renderer@2.
x but none was installed.
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\tools\\nodejs\\node.exe" "C:\\tools\\nodejs\\node_modules\\np
m\\bin\\npm-cli.js" "update"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! fuse-box@2.2.31 postinstall: `opencollective postinstall`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fuse-box@2.2.31 postinstall script 'opencollective postin
stall'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fuse-box package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     opencollective postinstall
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fuse-box
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fuse-box
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     F:\unitech\wiki\npm-debug.log

F:\unitech\wiki>

### Steps to reproduce the behavior
do npm update

**Comment by NGPixel** [comment]
Please use the official installation powershell script, as explained in the docs:
https://docs.requarks.io/wiki/install
