### ISSUE TITLE
How do I get changes to server/libs to take effect?

### ISSUE THREAD

**Issue by fireundubh** [Requarks/wiki#430]
How do I get changes to `server/libs/*.js` to take effect?

For example, I'm trying to increase the number of heading levels shown in the sidebar, but even if I insert a deliberate error into `markdown.js`, my test server is unaffected. Do I need to restart the server?

**Comment by NGPixel** [comment]
Have you tried?

In Node.js, any changes to a source file requires a restart of the application. Unlike PHP, source files are not read on every request, but compiled on start.

**Comment by fireundubh** [comment]
Is there a command to restart the server? Or do I need to `kill` the process?

**Comment by NGPixel** [comment]
Why don't you use the dev mode as explained in the [docs] (https://docs.requarks.io/wiki/dev-guide) which has an automatic restart on file changes?

**Comment by fireundubh** [comment]
All right. Well, for anyone else interested:

Command | Description
--- | ---
`node wiki start` | Start Wiki.js process
`node wiki stop` | Stop Wiki.js process
`node wiki restart` | Restart Wiki.js process
`node conf [port]` | Configure Wiki.js using the web-based setup wizard

Source: `wiki.js` in the root wiki path
