### ISSUE TITLE
Deploy to heroku can't found vendor.js & app.js

### ISSUE THREAD

**Issue by lordzpipo** [Requarks/wiki#431]
### Actual behavior
```js
vendor.js Failed to load resource: the server responded with a status of 404 (Not Found)
app.js Failed to load resource: the server responded with a status of 404 (Not Found)
```
### Expected behavior
all assets load without problem
### Steps to reproduce the behavior
1. pressing `Deploy to Heroku` in Github
2. fill all the info request by Heroku 
3. deploy

extra info:
new to Wiki.js, trying to use Heroku as my hosting service, please guide me how to solve this

**Comment by VitorGarcia23** [comment]
I'm having the same problem. If i access the url of the vendor.js or app.js, the source code opens on browser, but for some reason the application can't find them.
