### ISSUE TITLE
After installation on windows, unable to use due to 404 on app.js and vendor.js

### ISSUE THREAD

**Issue by txitguy** [Requarks/wiki#434]
### Actual behavior
After installation the app gets a 404 not found on app.js and vendor.js in the console logs.  Functionality does not work.

### Expected behavior
All files should load without 404s and the wiki should be operational.

### Steps to reproduce the behavior

- On Windows, met the prerequisites and installed using `iex ((New-Object System.Net.WebClient).DownloadString('https://wiki.js.org/install.ps1'))`.
- Run `node wiki configure`
- Go through the configuration process
- Open developer tools and load the app.  You will see the 404 errors and there will be no working functionality other than logging in.

![wikijs](https://user-images.githubusercontent.com/7252793/37009078-18ea6994-209a-11e8-95c6-45d4d0e11a4c.PNG)

**Comment by NGPixel** [comment]
Your `host` parameter is wrong in your `config.yml` as explained in the docs:
https://docs.requarks.io/wiki/troubleshooting#weird-display-no-styling

**Comment by txitguy** [comment]
I'm stupid, sorry.  Thanks.
