### ISSUE TITLE
Git Commit Guidelines

### ISSUE THREAD

**Issue by Zalimben** [Requarks/wiki#435]
### Actual behavior
Git Commit Guidelines are missing.

### Expected behavior
In the file where the contribution rules are defined ( [Contributing File](https://github.com/Requarks/wiki/blob/master/CONTRIBUTING.md)  ) I think it would be nice to add the rules for commit messages (a git message template)

**Comment by NGPixel** [comment]
Added semantic commit style section to Contributing file.
