### ISSUE TITLE
New pages in repo do not build (not added through web interface)

### ISSUE THREAD

**Issue by WimMar** [Requarks/wiki#438]
### Actual behavior

New pages which I have committed through git (not added manually through the site) are correctly in the *repo* directory, but they do not get "built".. (They do not show up) I tried restarting the wiki and mongodb but no avail. Is there a terminal command to rebuild pages?

### Expected behavior

  I would've expected the cache to update and add the pages..

### Steps to reproduce the behavior

  - I run wiki.js without apache/nginx, MongoDB v3.6.3, node v9.8.0
  - Add new pages locally or through git (not through the web interface)
  - Check site

**Comment by NGPixel** [comment]
Do the files you added respect the kebab-case naming format? Otherwise they will be ignored.

**Comment by WimMar** [comment]
Turns out they didn't have a title in the valid format (woops ^^)

> I wish it was okay with taking my markdown heading as title though
