### ISSUE TITLE
Markdown code block colorized

### ISSUE THREAD

**Issue by Ti-Tom** [Requarks/wiki#439]
Brace and highlight aren't fully compatible.
Ex: brace use `apache_conf` & highlight need `apacheconf` (or `apache`).

Code blocks are not colorized.

**Comment by NGPixel** [comment]
@AritroMukherjee Stop posting the same question in 3 different topics, which are completely unrelated to your issue. This is spam and you'll get banned the next time. Your `host` config is wrong, as explained in the [docs](https://docs.requarks.io/wiki/troubleshooting#weird-display-no-styling).
