### ISSUE TITLE
Enable (basic) markdown for sidebar

### ISSUE THREAD

**Issue by Isotop7** [Requarks/wiki#44]
When using markdown for headings, it is not used in the sidebar.

Would be cool to have this feature or at least normalize the strings by filtering markdown out of it.

![image](https://cloud.githubusercontent.com/assets/8883656/24112959/7d20b8ea-0d9b-11e7-80da-05dcba161442.png)

**Comment by NGPixel** [comment]
Fixed for Beta 12 (309010953a8a4a43e55c9f77f11d64fcfb322ece)
