### ISSUE TITLE
 Error: Not enough memory. Minimum is 768 MB.

### ISSUE THREAD

**Issue by EvilAcid** [Requarks/wiki#442]
### Actual behavior
i have a 20gb Droplet from DigitalOcean, but i cant install your wiki. 

Ich habe ein 20Gb Droplet mit CentOs7 bei Digital Ocean. Bei der Installation kommt aber der Fehler das ich zuwenid Speicher habe.

[Picture from Space](https://i.imgur.com/3MGjfbC.png)

gibt es dazu eine lösung?

**Comment by NGPixel** [comment]
768 MB of RAM, not disk space. You have 20GB of disk space, not RAM.

**Comment by EvilAcid** [comment]
oh i dont read it not so exactli. thank you, i have now update my droplet to 1Gb

**Comment by padomu** [comment]
> 768 MB of RAM, not disk space. You have 20GB of disk space, not RAM.
> 
> I suggest you upgrade your droplet to the new pricing. The minimum is now 1GB.

How come wiki.js needs such a big amount of ram? The docs say it needs 100-200mb, which is okay, but 700+? How come?
