### ISSUE TITLE
DiscardSave Document inactive

### ISSUE THREAD

**Issue by laoshaw** [Requarks/wiki#443]
First time installation, skip the git and installed well, login, then saw a tiny draggable edit-window for markdown. however the "DiscardSave Document" above the window can not be activated, and the UI is so barebone I suspect something is not correct at all.

long time node user, ubuntu 16.04 64bit, node 8.10.0, tried various ways.

also, wikijs does not support local git (i.e. git in local directory without ssh/http protocol) is also strange.

**Comment by NGPixel** [comment]
Your `host` parameter in your `config.yml` is wrong. It must reflect the URL you're actually using to access the wiki, including custom ports, https, etc:
https://docs.requarks.io/wiki/troubleshooting#weird-display-no-styling

Set `git: false` if you don't want to use remote sync.

**Comment by laoshaw** [comment]
Thanks. that fixed it.
