### ISSUE TITLE
Images not load and no console error!

### ISSUE THREAD

**Issue by MmKargar** [Requarks/wiki#4440]
### Discussed in https://github.com/Requarks/wiki/discussions/4424

<div type='discussions-op-text'>

<sup>Originally posted by **MmKargar** September 14, 2021</sup>
`mariadb : 10.5`  
`wikiJs : 2.5.214 `  
I needed to upgrade my database from `mariadb 10.4` to  `mariadb 10.5` and i made a backup from my database , but after upgrade when i was trying to import my database it gave me `ERROR 1032 (HY000) at line 827: Can't find record in 'tags'` error!  
after lot of search i figure out its mysq bug! and needs to increase mysql buffer size but not suggested and seems risky. so i did not.  
instead i remove some the line insert to `tags table and users table` that error cames! after import i insert `tags and users` data manually in seprated queries and it was ok.  
but after all everything is show up but not images!
it is showing imageas like this :
![image](https://user-images.githubusercontent.com/11253027/133205760-d7020892-4212-4ee5-ad1f-83138f6b18c9.png)

And i have no error in console!
What do you think is the problem?
Thanks.</div>

**Comment by voipiran** [comment]
I have the same problem
I have tried to change my Host, files and DB are transfer correctly, Wiki is up but the images are not shown!

thank you in advanced

**Comment by MmKargar** [comment]
the problem was with the database export , it was damaged the images.
