### ISSUE TITLE
Wiki.JS and Guthub.

### ISSUE THREAD

**Issue by EvilAcid** [Requarks/wiki#448]
### Actual behavior
For what is the Github Account?

will wiki js upload the .md files to github?

and when i chance one file of github, wil this chance the file too on my server in Wiki.js?

sorry for my bad EN.. im from Swiss =)

**Comment by NGPixel** [comment]
The git repository is for backup purposes. So if you connect your GitHub account, files you create in Wiki.js will be synced with your GitHub repo. Changes you make on GitHub will also be reflected in your Wiki.

**Comment by MostHated** [comment]
Is this 100% needed though? Does it have to be connected to github if you don't want it to be? I don't have a private repo account.

**Comment by MostHated** [comment]
I must have missed it. I got to the point where it said: "Git 2.7.4 or later is required."

**Comment by NGPixel** [comment]
@MostHated It is required. You're mixing up Git and GitHub.
