### ISSUE TITLE
Mathjax support

### ISSUE THREAD

**Issue by bitworm** [Requarks/wiki#45]

**Comment by dsimmie** [comment]
+1

**Comment by jacobo-diaz** [comment]
+1 to add math support with MathJax. It's the way [Gollum](https://github.com/gollum/gollum/wiki#mathematics) works.

**Comment by NGPixel** [comment]
Latex support is not in my plans for the near future. But MathJax is definitely something that can be added. I'll try to get it implemented in an upcoming beta.

**Comment by jacobo-diaz** [comment]
Maybe what @bitworm meant with Latex support was actually math support, i.e., the possibility to add math formulas using latex markup, which is basically (part of) what MathJax does. 

Thank you for the effort!

**Comment by bitworm** [comment]
tested, works great.

**Comment by AaronNGray** [comment]
This does not support a lot of LaTeX packages AFAICS like the Semantics package in order to do inference rules for example. It only seems to support basic maths equations. So it does not seem to have LaTeX support as such. Hope I can be corrected !
