### ISSUE TITLE
YouTube videos too big on smartphones

### ISSUE THREAD

**Issue by symsymmas** [Requarks/wiki#452]
### Actual behavior
When displaying a page with a YouTube video on my Smartphone, this video is too large. Only the half of the video is displayed.

### Expected behavior
When displaying a page with a Youtube video on my Smartphone, this video fits my Smartphone's width.

### Steps to reproduce the behavior
1- Create a page with a YouTube video.
2- Access to this Web page thanks to a Smartphone browser.

**Comment by NGPixel** [comment]
Wiki.js 1.x is not compatible with mobile / tablets.

2.0 will be bring full compatibility.
