### ISSUE TITLE
supporting tag in markdown

### ISSUE THREAD

**Issue by laoshaw** [Requarks/wiki#454]
can we have tag support in wiki.js, e.g. put a Tag line in the meta-info like what static site generator are doing and wiki.js is also tracking them? with Tag for each wiki page it will be easier to categorize etc. 

drupal and wordpress for example both have great Tag support, also those static-site-generators.

Thanks.

**Comment by NGPixel** [comment]
This is already planned for 2.0. You can track its status on the feature request board.
