### ISSUE TITLE
How do I log-in to the demo site?

### ISSUE THREAD

**Issue by thedonquixotic** [Requarks/wiki#457]
How do I log-in? I want to see what the admin backend etc looks like, and how good the UX is before I commit to the process of installing it etc.

**Comment by NGPixel** [comment]
There's no demo site... Unless you're talking about the docs wiki for which we obviously don't provide admin access.

The best way to try it is to install it, which takes 2 mins using docker.

**Comment by thedonquixotic** [comment]
Not everyone uses Docker yet. I know as a dev it's annoying to deal with
people who aren't the same level of technical knowledge as you but for a wiki
project, it's kind of a must that you make it accessible, if you actually want
anyone to use the product.










On Fri, Mar 16, 2018 2:20 PM, Nicolas Giard notifications@github.com  wrote:
Closed #457.

**Comment by ws-h-ono** [comment]
I definitely suggest to set up an official admin capable demo site...
It's important to know how the editing and its system capabilities are when deciding which wiki to use.

I knew about wiki.js for a year or so but I didn't realize it was so complete inside the admin interface with so many useful features already available until I installed it today...
