### ISSUE TITLE
tools/fuse is missing when creating a fresh wiki

### ISSUE THREAD

**Issue by JCaraballo113** [Requarks/wiki#460]
<img width="205" alt="screen shot 2018-03-18 at 6 55 52 pm" src="https://user-images.githubusercontent.com/6374766/37572199-059501e4-2ade-11e8-953d-9d287eba31ad.png">

Followed the getting started guide, ran the config. Tried to use `yarn run dev` and I keep getting the following: 

<img width="842" alt="screen shot 2018-03-18 at 6 57 00 pm" src="https://user-images.githubusercontent.com/6374766/37572212-2dbab3bc-2ade-11e8-8cda-2bd7f3c6e1bf.png">

I already tried running `npm i` so that's not it. Documentation is sadly lacking in troubleshooting :/

**Comment by NGPixel** [comment]
It is well documented [here](https://docs.requarks.io/wiki/dev-guide)

You're having this issue because you are using a release build instead of the actual source code. The release build does not have development files.
