### ISSUE TITLE
No styling applied when starting the wiki

### ISSUE THREAD

**Issue by JCaraballo113** [Requarks/wiki#461]
### Actual behavior
<img width="1440" alt="screen shot 2018-03-18 at 7 52 07 pm" src="https://user-images.githubusercontent.com/6374766/37572759-2ccf23fe-2ae6-11e8-9593-3ad17994626a.png">

### Expected behavior
Pretty sure it should look something like this or do we need to style the wiki?
<img width="1440" alt="screen shot 2018-03-18 at 7 54 37 pm" src="https://user-images.githubusercontent.com/6374766/37572764-3f138280-2ae6-11e8-96da-3935397ab335.png">

### Steps to reproduce the behavior
`node wiki start`

**Comment by NGPixel** [comment]
https://docs.requarks.io/wiki/troubleshooting#weird-display-no-styling

Your `host` parameter in `config.yml` doesn't match the URL you're using to access the wiki.
