### ISSUE TITLE
Local Authentication Disabled in login

### ISSUE THREAD

**Issue by rakeshdavid** [Requarks/wiki#4611]
### Discussed in https://github.com/Requarks/wiki/discussions/4610

<div type='discussions-op-text'>

<sup>Originally posted by **rakeshdavid** October 20, 2021</sup>
Hi,

Is there a way to enable Local Auth via URL or other means? I disabled local auth and locked myself out of Admin mode.

I intend to disable local auth, but I need an admin user. 

Context:
While implementing AUTH0, I wanted to disable local login without realizing that my Auth0 account is not an Admin. I need to make my AUTH0 account admin, but I am not sure I found any answers.

Any help is much appreciated.

RD

</div>

**Comment by wisetux** [comment]
Hello Rakesh, you can try accessing local auth by navigating to http://localhost:3000/login?all and then using the admin account you originally used to setup to login.

**Comment by rakeshdavid** [comment]
@wisetux @Azayzel Thank you so much, I appreciate it. It worked!!
