### ISSUE TITLE
Header hidding the title when accessing an URL pointing this title − Smartphone

### ISSUE THREAD

**Issue by symsymmas** [Requarks/wiki#465]
### Actual behavior
On a Smartphone, when a user access to a hyperlink pointing a title (ex. : http://<web-site>/#title), this title is hidden by the header of the Web site.

### Expected behavior
On a Smartphone, when a user access to a hyperlink pointing a title, this title is visible and under the header of the Web site.

### Steps to reproduce the behavior
With your Smartphone, go to a hyperlink pointing to a title.

**Comment by NGPixel** [comment]
Mobile is not supported in 1.x. Full support is coming in 2.0.
