### ISSUE TITLE
Logo page can be on the subtitle

### ISSUE THREAD

**Issue by symsymmas** [Requarks/wiki#467]
### Actual behavior
When using a Smartphone, the logo page can be on the subtitle.

### Expected behavior
A user using a Smartphone to access a page with a logo and a subtitle can see both of them with no problem at all.

### Steps to reproduce the behavior
1) Create a page with a logo and a subtitle.
2) Access to this page with a Smartphone.

**Comment by NGPixel** [comment]
Mobile is not supported in 1.x. Full support is coming in 2.0.
