### ISSUE TITLE
Unwanted links generated

### ISSUE THREAD

**Issue by palladium313** [Requarks/wiki#468]
### Actual behavior
When using text, often when referring to file names, if the extension happens to be a possible web top level domain it will automatically create an HTTP link attempting to point to "file_title"."file"extension". In my case I am documenting a series of Bash scripts and ".sh" triggers the auto-generation forcing me to reference them all using the string syntax, but having random strings littered all over the wiki makes it look awful.
### Expected behavior
Links should only be generated when using the link syntax, or there should be a setting to turn off this behavior.
### Steps to reproduce the behavior
![wiki_code_links](https://user-images.githubusercontent.com/8900841/37709587-0e16e31e-2ce1-11e8-94d3-eb6c4e4852f4.png)
leads to:
![wiki_links](https://user-images.githubusercontent.com/8900841/37709590-105e7240-2ce1-11e8-9345-94a472abdc54.png)

I am using the docker container for my wiki. I recently updated it to the latest version, I have observed this behavior in both Firefox and Chrome.

**Comment by NGPixel** [comment]
This behavior is as designed. If you want to disable it, modify this file to set the option to `false`:
https://github.com/Requarks/wiki/blob/master/server/libs/markdown.js#L27

**Comment by palladium313** [comment]
Thank you for the follow up and workaround, I will give it a try. I do feel that being able to control this functionality would be a nice security improvement since it would help protect the readers.
I also think that there should be a mention of this functionality on https://docs.requarks.io/wiki/user-guide/markdown-syntax , the user guide indicates the only way to generate links is with the links syntax, which is what lead me to believe it could be a bug or something else interfering.
