### ISSUE TITLE
delete pages on local server

### ISSUE THREAD

**Issue by Victorfy** [Requarks/wiki#470]
### Actual behavior
installed wiki in local server, unfortunately, create some folder and pages we don't need. we can delete pages but can't delete folders. 

### Expected behavior
it seems can't delete folders in wiki.js. So I want to delete folders through change some data in local server, what should i do?

### Steps to reproduce the behavior
Try to delete a folder from wiki.js in local server data

**Comment by NGPixel** [comment]
Delete the folder locally and restart Wiki.js.

This behavior will be fixed in 2.0.

**Comment by josephsmartinez** [comment]
You add Express to a stack and delete anything. Not recommended for production use.

'''docker
##############
  # Mongo Express should only be used privately for development purposes.
  # https://hub.docker.com/_/mongo-express
  ##############
  mongoexpress:
    image: mongo-express
    restart: always
    ports:
      - '8081:8081'
    links:
      - wikidb:mongo
    depends_on:
      - wikidb
    environment: 
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_SERVER=wikidb
      # - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      # - ME_CONFIG_MONGODB_ADMINPASSWORD=example
'''
