### ISSUE TITLE
links on the wiki to the web server are misidentified as internal links

### ISSUE THREAD

**Issue by Albus** [requarks/wiki#4739]
I currently run Wiki.js on port 80 and a web server on the same machine that is on port 8080. I've found that links on the wiki to the web server are misidentified as internal links. For example, a link to http://hostname:8080/x is rendered as http://hostname/:8080/x.

I fixed this by modifying line 53 in  ./server/modules/rendering/html-core/renderer.js from

      if (isHostSet && href.indexOf(WIKI.config.host) === 0) {

to

      if (isHostSet && href.indexOf(WIKI.config.host) === 0 && href.indexOf(WIKI.config.host+":") < 0) {

Perhaps there is a better way you would like to identify this situation, but addresses to the same server on different ports should be treated as external links. A possible exception might be when the port is the Wiki.js port, but if the author has explicitly given a port it should probably be respected.

_Originally posted by @jpcoles in https://github.com/Requarks/wiki/discussions/4013_

**Comment by NGPixel** [comment]
Fixed by a50712ea8085bb25c062252fe31cf90d7bd00d03
