### ISSUE TITLE
[RFC] Feature request: Draw/AttachedFiles/Comments

### ISSUE THREAD

**Issue by kopax** [Requarks/wiki#474]
Hi everyone and requarks team,

We have just tested a few Wiki-likes.

WikiJS got is on top of our most appreciated opensource framework because it fits our requirement. (Docker/ACL/LDAP)
.
WikiJS is good because it provide a smart integration with Git and it handles tree structure, LDAP Docker, and ACL.

There is another one, really good Wiki like, called [BookStack](https://github.com/BookStackApp/BookStack ), but unfortunately, they miss categories (which literally kill their app for large-scale documentations), and they do not have a tree structure, also their ACL doesn't permit much.

However, I have a few feature request comparison I would like to purpose, and a few come from them:

**Major missing features**:

1. Copy image and paste in markdown `CTRL+V`
1. ability to do draw, BookStackApp implemented it with https://github.com/jgraph/drawio/ (It is directly in the app, and pretty powerful for writing specification in the browser, it's all HTML5.).

**Minor missing features**:

1. Comments to article.
1. We can link files in markdown but we can't attach files to the article without adding links in the markdown documentation.
1. Customize the banner with a Logo
1. Markdown editor from BookStack has a live and pure markdown editor mode that I prefer, but that's personal opinion.

I would like to know if it's on requarks roadmap at some point.
Particular attention to drawio. which literally is a very useful gadget.

**Comment by NGPixel** [comment]
Please use https://requests.requarks.io/wiki for feature requests.

Most of the features you listed are already on the roadmap for 2.0.

**Comment by kopax** [comment]
Thanks for the link, I have recreated the post https://requests.requarks.io/wiki/p/rfc-feature-request-drawattachedfilescomments

**Comment by NGPixel** [comment]
https://github.com/Requarks/wiki/blob/master/README.md#200---dev

**Comment by kopax** [comment]
Im not sur to see what is exactly gonna be included from my report.
Also, do you know if it is possible to translate the markdown in v2 (multinlingue)
