### ISSUE TITLE
Localization Issue

### ISSUE THREAD

**Issue by joshaven** [Requarks/wiki#475]
### Actual behavior
The localization seems to be broken.  For example, the search at the top says "serach.placeholder" instead of "Search..." like specified in the ./server/locals/en/browser.json file.  This has been the behavior since install and I haven't modified or customized anything related to the localization and I am not seeing anything in the logs that indicates a problem.  I checked file permissions and I checked that the config file was set for "lang: en".  Any advice?

Note: it's not only the search when you go to cancel an edit the popup window says "modal.discardpagetitle", it seems that everything that is localized is not using the localization.

The live site can be viewed at http://wiki.wisp.live

### Expected behavior
Proper localization.

**Comment by NGPixel** [comment]
Your webserver doesn't serve .json files properly. Look at the console and you'll see a `Failed to load https://wiki.wisp.live/js/i18n/en.json: Response for preflight is invalid (redirect)`.

I'll close this issue as it's not an issue with Wiki.js.

**Comment by joshaven** [comment]
Thank you!

In case anyone else has this issue I found out that it was because the site was being served on http and the config.yml had the host set to https so the issue was related to cross-site javascript.  One possible programmatic solution to protect against this could be removing the http/https from the request like //domain.tld/js instead of https://domain.tld/js which should auto select the protocol based on the current protocol so I understand.
