### ISSUE TITLE
Issue with Markdown table headers spanning columns

### ISSUE THREAD

**Issue by davidflypei** [Requarks/wiki#4775]
### Actual behavior
Outputs:

| General Info ||

and then the rest of the table.

![Screenshot_20211211_144442](https://user-images.githubusercontent.com/27733532/145688002-e386c4ff-9100-45e6-b407-37e69ae66f10.png)

### Expected behavior

First header to span two other headers in the row down.

![Screenshot_20211211_143918](https://user-images.githubusercontent.com/27733532/145687991-bf1df49a-a1c6-47d3-95ba-593b95871d92.png)

### Steps to reproduce the behavior

Make a table in markdown. 

```
| General Info ||
| Header | Description |
|--------|-------------|
| Tracking # | Tracking number. Clicking on the number will take you to Canada Posts tracking page for that number. |
| Mailed On | The date the tracking number was created or mailed on. |
| Delivery Standard | The date that Canada Post said it will be delivered. |
| Delivery Date | The date the tracking number was delivered. |
```
Then publish the page and look at it in the wiki. Version on wiki does not match the preview in the editor.

Editor view:
![Screenshot_20211211_144629](https://user-images.githubusercontent.com/27733532/145688070-a3f7f251-4415-4fb1-886e-998d5e19d5ea.png)

Wiki view:
![Screenshot_20211211_144832](https://user-images.githubusercontent.com/27733532/145688138-5dde1253-ef70-4c6b-961e-f2e34231d79f.png)

**Comment by NGPixel** [comment]
That's not valid markdown and isn't supported on GitHub either. File an [improvement request](https://requarks.canny.io/wiki) instead as this isn't a bug.

**Comment by davidflypei** [comment]
So if it isn't valid then why is the preview rendering it? I can make an improvement request but it's weird that the preview is rendering it but then it doesn't render on the page.

**Comment by NGPixel** [comment]
The fact that it works in the editor preview is more of an accident than a planned feature. The editor was never made to support that syntax, which is why I suggested creating an improvement request so that it can be properly implemented at all stages.

**Comment by markus-96** [comment]
I also ran into this issue, so I have to add up on this.

Sorry for stepping in here, but why is this not a planned feature? As far as I can tell, the syntax used here is multimarkdown tables. It is marked as completed here: https://feedback.js.wiki/wiki/p/support-multimarkdown-tables and also has a merged PR: https://github.com/requarks/wiki/pull/2126

**The solution**: you only have to enable "MultiMarkdown Table" in the Adminpage, under "Rendering" -> "markdown". The fact that the table is rendered correctly in the editor even though multimarkdown table is disabled could be considered a bug if you ask me.

The same issue is described here: https://github.com/requarks/wiki/discussions/4962
