### ISSUE TITLE
Windows 7 Install? Error 

### ISSUE THREAD

**Issue by bchdubois** [Requarks/wiki#478]
### Trying to install Using Windows 7
Just made sure all my requirements are up to date (nodejs/mongo/git/etc).

When trying to install using powershell (run as admin) I am getting errors.

I set the Bypass fine, but then run the next install step which fails.

### Powershell output
`PS E:\wiki> Set-ExecutionPolicy Bypass

Execution Policy Change
The execution policy helps protect you from scripts that you do not trust. Changing the execution policy might expose
you to the security risks described in the about_Execution_Policies help topic. Do you want to change the execution
policy?
[Y] Yes  [N] No  [S] Suspend  [?] Help (default is "Y"): Y
PS E:\wiki> iex ((New-Object System.Net.WebClient).DownloadString('https://wiki.js.org/install.ps1'))
Exception setting "SecurityProtocol": "Cannot convert value "tls12, tls11, tls" to type "System.Net.SecurityProtocolTyp
e" due to invalid enumeration values. Specify one of the following enumeration values and try again. The possible enume
ration values are "Ssl3, Tls"."
At line:1 char:28
+ [Net.ServicePointManager]:: <<<< SecurityProtocol = "tls12, tls11, tls"
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyAssignmentException

Add-Type : Cannot add type. The assembly 'System.IO.Compression.FileSystem' could not be found.
At line:2 char:9
+ Add-Type <<<<  -AssemblyName System.IO.Compression.FileSystem
    + CategoryInfo          : ObjectNotFound: (System.IO.Compression.FileSystem:String) [Add-Type], Exception
    + FullyQualifiedErrorId : ASSEMBLY_NOT_FOUND,Microsoft.PowerShell.Commands.AddTypeCommand

Add-Type : Cannot add type. One or more required assemblies are missing.
At line:2 char:9
+ Add-Type <<<<  -AssemblyName System.IO.Compression.FileSystem
    + CategoryInfo          : InvalidData: (:) [Add-Type], InvalidOperationException
    + FullyQualifiedErrorId : ASSEMBLY_LOAD_ERRORS,Microsoft.PowerShell.Commands.AddTypeCommand

 __    __ _ _    _    _
/ / /\ \ (_) | _(_)  (_)___
\ \/  \/ / | |/ / |  | / __|
 \  /\  /| |   <| |_ | \__ \
  \/  \/ |_|_|\_\_(_)/ |___/
                   |__/
   < INSTALL >

Specify the full path where Wiki.js should be installed (e.g. C:\wiki):
Path: E:\wiki
[1/6] Fetching 7zip helper... OK
[2/6] Fetching latest build... Exception calling "DownloadFile" with "2" argument(s): "The underlying connection was clo
sed: An unexpected error occur
red on a send."
At line:62 char:25
+ $downloader.DownloadFile <<<< ("https://github.com/Requarks/wiki/releases/download/v$VERSION/wiki-js.tar.gz", "$curPa
th\wiki-js.tar.gz")
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : DotNetMethodException

OK
[3/6] Fetching dependencies... Exception calling "DownloadFile" with "2" argument(s): "The underlying connection was clo
sed: An unexpected error occur
red on a send."
At line:66 char:25
+ $downloader.DownloadFile <<<< ("https://github.com/Requarks/wiki/releases/download/v$VERSION/node_modules.tar.gz", "$
curPath\node_modules.tar.gz")
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : DotNetMethodException

OK
[4/6] Extracting app files...
ERROR: The system cannot find the file specified.
E:\wiki\wiki-js.tar.gz

System ERROR:
The system cannot find the file specified.
Error: 7-Zip encountered a fatal error while extracting the files
At line:46 char:14
+     2 { throw <<<<  "Error: 7-Zip encountered a fatal error while extracting the files" }
    + CategoryInfo          : OperationStopped: (Error: 7-Zip en...cting the files:String) [], RuntimeException
    + FullyQualifiedErrorId : Error: 7-Zip encountered a fatal error while extracting the files

PS E:\wiki>`

### Trying Manual Install
Download the wiki-js.tar.gz and node_modules.tar.gz files directly from the GitHub Releases.

1. Extract wiki-js.tar.gz to the location of your choice.
2. Extract node_modules.tar.gz in a folder named node_modules in the same folder where you extracted the wiki-js.tar.gz package. ***(assume this is at same level as wiki-js folder or should it be in wiki-js)***
3. Rename the file config.sample.yml to config.yml ***(then attempted to run 'node wiki configure' - but complains 'cannot find module 'bluebird' I have installed npm install --global bluebird)*** 
4. See steps above to configure and run Wiki.js.

**Comment by NGPixel** [comment]
Windows 7 doesn't have the necessary Powershell version to run the installation script properly. Upgrade to Windows 10 as no support will be given for Windows 7 (MS has ended mainstream support 3 years ago by the way).

If you want to install it manually, you shouldn't install any npm modules (installing bluebird globally is pointless as this is a dependency, not a global executable). The node_modules folder needs to be inside the wiki.js folder.
