### ISSUE TITLE
Multi-language?

### ISSUE THREAD

**Issue by steckerhalter** [Requarks/wiki#48]
Hi, I'd like to ask if multi-language is planned. This is often a deal-breaker in web frameworks and then grafted on in a half-baked fashion. So I'd like mention it early on :smile:

**Comment by NGPixel** [comment]
Yes, multi-language support was implemented from the very beginning (English + French). Right now, very few components are using it, but this will change very soon.

Beta 9 will see the addition of Korean, German, Spanish, Portuguese and Russian as available choices during setup.

Beta 10 will have full UI translations.

**Comment by steckerhalter** [comment]
@NGPixel Thanks. Does that mean that I can have page content in different languages? I imagine when my browser has English as a language I would see the English Home and when I have French it would show the French Home. Wikipedia somehow connects translations of a page but it uses language subdomains which isn't great. I think it should be possible to specify the language for a page and then add translations for the same page (with language-specific slugs).

**Comment by NGPixel** [comment]
I was strictly speaking about the UI. Having multilingual content is another issue by itself and a very complex one to address. I'm not fond of using sub-domains for locale/language either.

I suggest using language folders at the root for now. (e.g. /en/something and /fr/something)
A feature to automatically redirect to the correct base language folder could be added in the future, based on this setup.
