### ISSUE TITLE
Search does not match text located within code block

### ISSUE THREAD

**Issue by sensiblemedia** [Requarks/wiki#481]
### Actual behavior
A search does not appear to match against text within a code block
### Expected behavior
Would expect search function to match against text located within code block 
### Steps to reproduce the behavior
Create page with a code block and search for a word located within code block.

**Comment by sensiblemedia** [comment]
Apologies but I just found similar previous post here #453

**Comment by NGPixel** [comment]
This is as designed. Most users wouldn't expect code to trigger unwanted results during search.

Post a [feature request](https://requests.requarks.io/wiki) to have the option in v2.
