### ISSUE TITLE
Upload of asset fails with: Cannot read property 'toLowerCase'

### ISSUE THREAD

**Issue by drx777** [Requarks/wiki#4825]
### Actual behavior
An asset fails to be uploaded.

### Expected behavior
An asset is uploaded successfully.

### Steps to reproduce the behavior
When I upload an asset, I get the following error message in the log after the progress bar reaches 100% and stalls there:

```[MASTER] warn: Cannot read property 'toLowerCase' of undefined```

and the request fails with code 400.

wiki.js version: 2.5.264 (issue occurred already with 2.5.201 prior to update, but upload did use to work on this machine)
node.js version: 12.22.7
maria db version: 10.3.22
client MacOS 12.1, Safari or Chrome

(side note: When I try to upload an asset that I select in a folder that is a symlink, the upload fails directly)

**Comment by GrafAviator** [comment]
I have the exact same problem on docker     image: requarks/wiki:2

Just started to set up Wiki.js for the first time and ended up with this error while trying to upload documents for the first time.

Tried wiki.js 2.4 version on docker. Upload does work in old version.

**Comment by TwiggyG85** [comment]
Same here after Update to 2.5.264 no problem on 2.5.260 (think this was my version before)

**Comment by NGPixel** [comment]
Fixed by e84c15b926843a32d23b7e71e2d2f4622dfca9e7
