### ISSUE TITLE
Wiki.Js download section

### ISSUE THREAD

**Issue by Guevarabrik** [Requarks/wiki#485]
Hi , 
I have installed wiki.js before 2 days and i am still new to it, everything is working just fine, I am facing one problem at the moment. I would like to create a download section, where files can be published for others to download.
Is this option possible ?

thx.

**Comment by NGPixel** [comment]
Yes. You can upload files from the editor and place links on your page.

**Comment by Guevarabrik** [comment]
Hi NGPixel,
thanks for answering me, 
i already knew that, but my question is : can i upload files for example MSI files, that could be directly downloaded by other users who visit my page?

thx.

**Comment by NGPixel** [comment]
Yes, using the method I posted above.
