### ISSUE TITLE
Setup Repository After Launch

### ISSUE THREAD

**Issue by voteleobrown** [Requarks/wiki#487]
Setup without git to test, then wanted the backup so created repository and entered the settings into config.yml 

Repository was not initialized, this may be the problem but after restarting the wiki with updated config no entries appeared, which obviously was pretty nerve recking, but after changing the config back to 

git: false

and removing the other git settings, my entries reappeared.

My question now is can I just initialize the repository and continue on as I was planning, or is there any threat of data loss?

How do I retroactively add a repository without risk of data loss?

**Comment by NGPixel** [comment]
Git repository must be initialized. Simply add your files to your git repository. A pull will be executed on start.

**Comment by voteleobrown** [comment]
Just those in 'repo/'?

**Comment by NGPixel** [comment]
Yes
