### ISSUE TITLE
How to change favicon of the webseite?

### ISSUE THREAD

**Issue by Guevarabrik** [Requarks/wiki#488]
Hi, 
can anyone tell me where to change the favicon for the wiki website?

thx

**Comment by NGPixel** [comment]
You can change the favicon.ico file located in the /assets folder.

**Comment by Guevarabrik** [comment]
Thank you very much @NGPixel ,
 i will try it 👍

**Comment by Guevarabrik** [comment]
@NGPixel  i did change the file with my own favicon.ico, i then restarted wiki but nothing really happened. i still see the wiki favicon in my browser tab.
do you know any other solutions? or did i do that the correct way?

thx

**Comment by NGPixel** [comment]
Clear your browser cache.

**Comment by Guevarabrik** [comment]
hi @NGPixel,
i already changed the favicon.ico file in the /assets folder, cleared my browser cache and nothing happened. is there any other way to do that?
