### ISSUE TITLE
Setting admin password on Heroku

### ISSUE THREAD

**Issue by mmmikko** [Requarks/wiki#489]
Everything went fine with Heroku deployment, but now I'm unable to figure how to set password / run config on heroku shell, as I think access to eg. port 3000 is blocked. How can I set the admin password?

**Comment by NGPixel** [comment]
There's no setup on Heroku. You simply login with the email you specified on the Heroku variables page and password `admin123`

**Comment by mmmikko** [comment]
Thank you! Somehow I missed the mention of the password.
