### ISSUE TITLE
Creating page (empty) gives a weird bug

### ISSUE THREAD

**Issue by agrgic** [Requarks/wiki#49]
Steps to reproduce:

- Create a page, and just leave the title and empty subtitle and save
- When you link to the page and enter it, it will say there is no page and if you want to create one, when you do, it says the page already exists (but there is no entry in Mongo)

**Comment by NGPixel** [comment]
Fixed for Beta 10.

956d3aca088d51d3266ee5d33616bc89f69c48ed
