### ISSUE TITLE
Brackets in pre-formatted code block break page display

### ISSUE THREAD

**Issue by shrank** [Requarks/wiki#4915]
### Actual behavior
If you put the example below into a pre-formatted block, it breaks the page display. The rendering itself seems to be fine. The HTML is delivered to the browser and looks correct. But the code is not display, instead, all content of <body> is removed.

```
<body>
<!---->
</body>
```

### Expected behavior
show rendered html
### Steps to reproduce the behavior
put this into an empty page:

EXAMPLE START
\```
{{ 
Hello World }}
\```
EXAMPLE END

tested on Version 2.5.170

**Comment by NGPixel** [comment]
Upgrade to latest version.
