### ISSUE TITLE
error: Invalid character in header content ["Content-disposition"]

### ISSUE THREAD

**Issue by 0v3rd0z3d** [requarks/wiki#4930]
### Discussed in https://github.com/Requarks/wiki/discussions/4929

<div type='discussions-op-text'>

<sup>Originally posted by **0v3rd0z3d** January 24, 2022</sup>
![image](https://user-images.githubusercontent.com/65501113/150765398-db697628-c45c-495b-a3d0-d0cf84c02a73.png)
![image](https://user-images.githubusercontent.com/65501113/150765497-7eff5aff-7eab-4d73-b260-56ba28418f21.png)
Acquired an"internal server error" while trying to open assets. Names are in Russian characters.
Not having this error with filenames in english characters.
Versions of wikijs with this issue: 2.5.268, 2.5.272
Not having this error in version: 2.5.201
Thank you in advance!</div>

**Comment by dcfreedom** [comment]
Same issue here. But file name is in Traditional Chinese.

**Comment by hendrikma** [comment]
Same issue here.

"ü" (HTML &uuml; // ASCII Code 129) Doesn't work.

"ä" (HTML &auml; // ASCII Code 132) works 😕

**Comment by MrakoMaks** [comment]
similarly :(

**Comment by dcfreedom** [comment]
This should fix the issue.

wiki/server/models/assets.js

--- assets.js.old       2022-04-02 04:58:00.161301315 +0800
+++ assets.js   2022-04-02 04:57:28.598543664 +0800
@@ -174,7 +174,7 @@
 
       // Force unsafe extensions to download
       if (WIKI.config.uploads.forceDownload && !['.png', '.apng', '.jpg', '.jpeg', '.gif', '.bmp', '.webp', '.svg'].includes(fileInfo.ext)) {
-        res.set('Content-disposition', 'attachment; filename=' + fileInfo.base)
+       res.set('Content-disposition', 'attachment; filename=' + encodeURIComponent(fileInfo.base))
       }
 
       if (await WIKI.models.assets.getAssetFromCache(assetPath, cachePath, res)) {

**Comment by NGPixel** [comment]
@dcfreedom Please submit a PR with the fix.

**Comment by NGPixel** [comment]
Fixed by 05b405395432901c561eff51e8a2b94c6220ac7e
