### ISSUE TITLE
The wikijs instance deployed by herokuapp.com does not load styles

### ISSUE THREAD

**Issue by mathsicist** [Requarks/wiki#494]
The wikijs instance deployed by herokuapp.com does not load styles. Yesterday I tried to installed wikijs on my own server. I spent a lot of time without success - the styles didn't want to load properly. There are many similar already reported issues but still, I wasn't able to fix it. Then I decided to use herokuapp, just for a try, and I found out that it doesn't work as well. Can you confirm that it's a configuration problem or just a bug?
![image](https://user-images.githubusercontent.com/24816670/38673575-0281f106-3e52-11e8-983a-4acde26d2429.png)

**Comment by NGPixel** [comment]
Styles don't load because you set the incorrect host in the config. It must match exactly what you're using to access the site as a client, as explained on https://docs.requarks.io/wiki/troubleshooting#weird-display-no-styling

**Comment by marek-siemieniuk** [comment]
I'm not able to set ports on herokuapp.com. Could you show me an example config file? My configuration looks something like this:
```
host: http://localhost:80
port: 3000
```

**Comment by mathsicist** [comment]
I'm not able to set ports on herokuapp.com. Could you show me an example config file? My configuration looks something like this:
```
host: http://localhost:80
port: 3000
```
