### ISSUE TITLE
Wiki.js 3.0 Feature GitLab setup ?

### ISSUE THREAD

**Issue by craph** [Requarks/wiki#4955]
### Discussed in https://github.com/Requarks/wiki/discussions/4954

<div type='discussions-op-text'>

<sup>Originally posted by **craph** February  1, 2022</sup>
Hello, 

After reading the feature about storage with GitHub, will it be possible to use GitLab instead of GitHub ?

Thank you very much.

Best regards and good job so far Nicolas.</div>

**Comment by dgwetzel** [comment]
Yesterday I configured our wiki.js instance to work with our self hosted gitlab. (private key authentication).
I think the git integration should work with any "git server".

**Comment by dgwetzel** [comment]
ouh sorry, its regarding version 3. I use version 2.

**Comment by matutter** [comment]
Is there GitLab support coming in 3? https://docs.requarks.io/storage/git

**Comment by craph** [comment]
Thank you @matutter I missed this page :)
