### ISSUE TITLE
Official Docker Repo is 2 months old

### ISSUE THREAD

**Issue by technojunkie** [Requarks/wiki#496]
### Actual behavior
Official container on docker hub is 2 months old, but many recent changes have been committed

### Expected behavior
Many containers I use from docker hub use build triggers to automatically rebuild as changes are committed, it appears that wiki.js does not. Could this be added?

**Comment by NGPixel** [comment]
This is already the case. The docker hub image is up to date. The last release was 1.0.78, as listed [here](https://github.com/Requarks/wiki/releases).

Releases are not built after every single commit.
