### ISSUE TITLE
Unable to embed wiki in an iframe

### ISSUE THREAD

**Issue by PedroFMBranco** [Requarks/wiki#4995]
I'm trying to embed the wiki in an iframe, already with the security setting for it set to the right value.
Settings -> Security -> Block IFrame Embedding: Off.

However I'm still facing issues related with the usage of the local storage
```
Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
```

I've only tried this in local environment, but from what I know I'm still going to have the same issue after deploying to a remote environment. 

Note: The wiki and remote environments are going to be subdomains of the same domain.

**Comment by NGPixel** [comment]
This isn't related to Wiki.js. You're trying to access a context outside the iframe and the browser blocks it.
