### ISSUE TITLE
"Local" git repo

### ISSUE THREAD

**Issue by Isotop7** [Requarks/wiki#5]
Hi,

is it possible to use the wiki with a "local" repo only for testing purposes? So that it doesnt use git pull/push and only commits changes locally?

**Comment by NGPixel** [comment]
I guess it could be added quite easily. I'll add an option in the coming days to disable the remote git.

**Comment by NGPixel** [comment]
Git remote sync can now be disabled by setting `git: false` in config.yml. It will be available in **Beta 5** which will be released in a few days.

In the meantime, you can simply replace the file `/libs/git.js` with the latest version from the master branch.

Nick

**Comment by NGPixel** [comment]
Beta 5 is now available.

**Comment by stuartpb** [comment]
I just checked: the `repo` directory for my wiki appears to have no commits made. Does `git: false` turn off Git *altogether*? I just want to have it so that it uses the repository without a remote sync location.

**Comment by NGPixel** [comment]
No, commits are still being made but no pull/push calls.

**Comment by stuartpb** [comment]
Well, commits aren't being made on my wiki (at least, not in the `repo` directory where I just ran a `git log -p` and got only the initial commit back), so there's clearly a bug somewhere.

**Comment by MMI** [comment]
This matches my experience. I didn't see any git activity until I set up an external git server.
