### ISSUE TITLE
Dont display editors name publicly (or add option)

### ISSUE THREAD

**Issue by b90g** [Requarks/wiki#5003]
Either in general or via group permission to hide an editors name from the public

https://github.com/Requarks/wiki/blob/7988fa62ca2df508e517976a017e6367e833eaa9/server/views/page.pug#L21

Right now i manually patch
```
-      author-name=page.authorName
+      author-name=page.authorId
```

the permission `read:pages` seems to include `authorName`

**Comment by NGPixel** [comment]
https://requarks.canny.io/wiki/p/hide-usernames-from-public
