### ISSUE TITLE
Impossible to sync git repository with Azure DevOps since 2.5.272

### ISSUE THREAD

**Issue by laellyo** [Requarks/wiki#5062]
We have an issue since few weeks with the GIT synchronization capability of WikiJS.

### Actual behavior
Without any change on Azure DevOps credentials (SSH or PAT), we meet an error when we deploy the WikiJS version 2.5.272 or above. 

For SSH:

> Unable to negotiate with XX.XX.XX.XX port 22: no matching host key type found. Their offer: ssh-rsa fatal: Could not read from remote repository. Please make sure you have the correct access rights and the repository exists. error: Could not fetch origin 

For PAT:
> fatal: Authentication failed for 'https://dev.azure.com/xxxxx/yyyyyy/_git/wiki/' error: Could not fetch origin 

In logs, the only related logs I found are:

> 2022-02-28T15:51:44.837622999Z 2022-02-28T15:51:44.837Z [MASTER] [33mwarn[39m: fatal: ambiguous argument 'staging': unknown revision or path not in the working tree.
> 2022-02-28T15:51:44.837872402Z Use '--' to separate paths from revisions, like this:
> 2022-02-28T15:51:44.837883702Z 'git <command> [<revision>...] -- [<file>...]'

### Expected behavior

If we rollback to version 2.5.268, everything works fine again, without changing any GIT settings in WikiJS.

### Steps to reproduce the behavior

If a dedicated Azure DevOps repo + PAT is required to help you to find the root cause, feel free to contact me. I will do my best to provide you temporary resources.

Thanks in advance for your help !

**Comment by maffelbaffel** [comment]
Same issue unfortunatly. We are using the currently latest version 2.5.277
