### ISSUE TITLE
wikijs doesn't work with a preexisting repo containing only an empty file

### ISSUE THREAD

**Issue by zeyangl** [Requarks/wiki#507]
Running Docker version.

### Actual behavior
git failed to sync with remote
### Expected behavior
git syncs with remote
### Steps to reproduce the behavior
install as the documentation
create a new gitlab repo
create a readme file in the repo.
configure gitlab repo link wikijs-config.yml
start wikijs service
observe error message in log:

{ code: 128,
  message: '`git --git-dir=repo/.git --work-tree=repo pull origin master` failed with code 128',
  stderr: 'From http://192.168.1.xxx:8088/wiki/wiki\n * branch            master     -> FETCH_HEAD\nfatal: refusing to merge unrelated histories\n',
  stdout: '' }

**Comment by NGPixel** [comment]
Delete your local ./repo folder then restart Wiki.js and it will sync properly. You cannot have different contents on the local and remote repositories.

**Comment by Zombiehamser** [comment]
Hello! I'm sorry, I have the same problem. Where I can find ./repo of Wiki.JS? I try search all "repo" from host machine to docker container, and find nothing.

**Comment by Zombiehamser** [comment]
> Delete your local ./repo folder then restart Wiki.js and it will sync properly. You cannot have different contents on the local and remote repositories.

Hello! I'm sorry, I have the same problem. Where I can find ./repo of Wiki.JS? I try search all "repo" from host machine to docker container, and find nothing.
