### ISSUE TITLE
Database error when rebuilding page tree when moving multiple pages simultaneously

### ISSUE THREAD

**Issue by twnk** [requarks/wiki#5080]
I am using the GraphQL API to execute multiple page moves in quick succession. The page moves all seem to execute correctly, but the GraphQL API returns an error for all but one operation.

According to the page move code, each page move calls the rebuild-tree job asynchronously:
https://github.com/Requarks/wiki/blob/b7f50633f3b455471f3db93a89cb4bbf3a528b77/server/models/pages.js#L733-L734

The `pageTree` table is truncated by each of these operations, ie each rebuild of the page tree is a total wipe and restart. This makes sense, but the tree rebuild operation should probably be behind some kind of lock so that only one rebuild can execute at one time, otherwise the collisions will cause errors. The errors are not major, because when a final rebuild executes, any inconsistencies are wiped anyway and replaced with a fresh tree.  

The error presented via the GraphQL response is a series of
 ```
 Code: 1 
 Slug: Error 
 Message: Error when running job rebuild-tree: insert into "pageTree" - duplicate key value violates unique constraint "pageTree_pkey"
```

The error as appears in the server log is
```
7T12:01:34.089Z [JOB] info: Rebuilding page tree...
7T12:01:34.099Z [JOB] info: Rebuilding page tree...
7T12:01:34.110Z [JOB] info: Rebuilding page tree...
7T12:01:34.121Z [JOB] info: Rebuilding page tree...
7T12:01:34.132Z [JOB] info: Rebuilding page tree...
7T12:01:34.144Z [JOB] info: Rebuilding page tree...
7T12:01:39.552Z [JOB] info: Using database driver pg for postgres [ OK ]
7T12:01:39.563Z [JOB] info: Using database driver pg for postgres [ OK ]
7T12:01:39.573Z [JOB] info: Using database driver pg for postgres [ OK ]
7T12:01:39.583Z [JOB] info: Using database driver pg for postgres [ OK ]
7T12:01:39.592Z [JOB] info: Using database driver pg for postgres [ OK ]
7T12:01:39.600Z [JOB] info: Using database driver pg for postgres [ OK ]
7T12:01:41.523Z [JOB] error: Rebuilding page tree: [ FAILED ]
7T12:01:41.524Z [JOB] error: insert into "pageTree" ("ancestors", "depth", "id", "isFolder", "isPrivate", "localeCode">
7T12:01:41.528Z [JOB] error: Rebuilding page tree: [ FAILED ]
7T12:01:41.528Z [JOB] error: insert into "pageTree" ("ancestors", "depth", "id", "isFolder", "isPrivate", "localeCode">
7T12:01:41.531Z [JOB] error: Rebuilding page tree: [ FAILED ]
7T12:01:41.531Z [JOB] error: insert into "pageTree" ("ancestors", "depth", "id", "isFolder", "isPrivate", "localeCode">
7T12:01:41.535Z [JOB] error: Rebuilding page tree: [ FAILED ]
7T12:01:41.535Z [JOB] error: insert into "pageTree" ("ancestors", "depth", "id", "isFolder", "isPrivate", "localeCode">
7T12:01:41.582Z [JOB] error: Rebuilding page tree: [ FAILED ]
7T12:01:41.582Z [JOB] error: insert into "pageTree" ("ancestors", "depth", "id", "isFolder", "isPrivate", "localeCode">
7T12:01:41.803Z [JOB] info: Rebuilding page tree: [ COMPLETED ]
```
Note this is the logs for a 6-page simultaneous move, and the 6th page tree rebuild succeeds. 

A partial improvement would be for the page move code to simply disregard page tree rebuild errors or not return them to the client, as they don't seem to affect the actual page move. I assumed when receiving these errors that the pages failed to move, but in fact, the pages move just fine.

**Comment by NGPixel** [comment]
Closing this issue as the page tree no longer needs to be rebuilt in v3.

**Comment by gazi786** [comment]
> Closing this issue as the page tree no longer needs to be rebuilt in v3.

When is v3 stable being released.
