### ISSUE TITLE
Suggestion: Support mathematical expressions & diagram

### ISSUE THREAD

**Issue by stevenxi** [Requarks/wiki#512]
This is not a bug, just a suggestion.

If wiki.js could support mathematical expressions & diagram, it would be very helpful.

Currently it's doable through a 3rd party lib, also open source with Apache license.

https://stackedit.io/

Declare, just found this project online, I have nothing to do with it.

**Comment by NGPixel** [comment]
You can already use mathematical expressions (although a bit buggy sometimes) using TeX syntax.

Diagram support is planned for 2.0.

**Comment by sebmaynard** [comment]
On the homepage at https://wiki.js.org/, under "Rendering", it says:

Diagrams
Easily generate diagrams such as UML, Flowcharts, Sequence and more

Is that not the case yet?

**Comment by NGPixel** [comment]
@sebmaynard Coming in a future beta release.
