### ISSUE TITLE
Refused to execute script on clean install + configure

### ISSUE THREAD

**Issue by millman2394** [Requarks/wiki#513]
`Refused to execute script from 'http://localhost:8080/localhost/js/vendor.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.`

`Refused to execute script from 'http://localhost:8080/localhost/js/app.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.`

After running the configure and getting through that successfully, it goes to the dashboard with no assets being loaded. 

https://imgur.com/a/hUj1Evi

```
host: 'http://localhost:8080'
port: 8080
```

**Comment by NGPixel** [comment]
Your host is wrong in your config.yml:

https://docs.requarks.io/wiki/troubleshooting#weird-display-no-styling

**Comment by millman2394** [comment]
```
host: 'http://localhost:8080'
port: 8080
```

I'm including the port 8080 in my host, like your instructions say. Can you show me why it's wrong? This is what I have in config.yml
