### ISSUE TITLE
suggestion: Automatically suffix host when configuring wiki

### ISSUE THREAD

**Issue by Unitech** [Requarks/wiki#515]
Hi,
When I did `node wiki configure` I missed to configure the right host there:
![image](https://user-images.githubusercontent.com/757747/39677478-d604af00-517b-11e8-9f07-c2a7a1b35c2b.png)

When I put port 3000 and I started the wiki, it failed to load the asset. I did not understood why at first but then I realized that I had to set the right host, suffixed with the port.

Maybe it would be nice to directly suffit the host with the right port if it's not != 80! Just my 2 cents

**Comment by NGPixel** [comment]
The port is different if you're using a reverse-proxy like nginx.

This has been addressed in 2.0 where the host is no longer necessary.
