### ISSUE TITLE
Able to deploy to Google App Engine?

### ISSUE THREAD

**Issue by millman2394** [Requarks/wiki#516]
I'm having many issues trying to deploy an app to Google Cloud (App Engine).

After trying to deploy an app that works locally, I get:

```
Updating service [default] (this may take several minutes)...failed.
ERROR: (gcloud.app.deploy) Error Response: [9]
Application startup error:

> wiki@1.0.78 start /app
> node wiki start

\u2714 Wiki.js has started successfully.
```

If i try to configure inside Google Cloud Shell and open web preview on port 8080 (or wherever)

`Error: failed to connect to server [address] on first connect [MongoError: connection 0 to address timed out]`

**Comment by NGPixel** [comment]
Do you have a MongoDB instance running? Seems like it can't connect to it. Use command `node server` instead when running in a container-like host. You'll get more meaningful logs.

**Comment by raymond180** [comment]
Hi Alex @millman2394 ,

Will you be able to guide me the process of deploying wiki.js on Google Cloud App Engine? I have no experience working with node.js and Google Cloud Platform. Just need a brief guide. I have successfully deployed it on Heroku but I need to move it to GCP. Thank you!! 

Sincerely,
Raymond

**Comment by KevinGP10** [comment]
Hi, have you recently tried to do this again? I am trying to launch wiki.js on google app engine but am having no luck connecting to my DB...

I think I am just missing the correct host? It doesn't work when I use the public IP, nor the instance connection name. 

Could you please share your successful config.yaml file?
