### ISSUE TITLE
Email Parser marks valid email addresses as invalid on account creation

### ISSUE THREAD

**Issue by Fidgetcetera** [requarks/wiki#5174]
### Actual behavior
When making a new user from admin dashboard (I have open registration disabled), emails with a period in the body (ie thisismy.email@example.com) are marked as invalid and prevent account creation.

### Expected behavior
This type of email should be considered valid. Gmail & other providers make active use of this character, making "exa.mple@gmail.com" equivalent to "example@gmail.com", and generally, the range of what emails are valid is really big. Another valid email that I suspect the parser won't like is "@"@example.com - quotes around text cause the entire quoted phrase, according to RFC 5322 (and older versions of the spec!), to be treated as though the quotes and everything inside were a single character.

### Steps to reproduce the behavior
1. Create new user with email address that contains a period
2. The email is marked as invalid

**Comment by NGPixel** [comment]
I was able to create a new local user with a period (`test.user@example.com`) without any issue...:

<img width="282" alt="image" src="https://user-images.githubusercontent.com/15522395/162658802-19b1b556-1ff6-461f-ac42-37046e83ac60.png">

The validation is done using the Validator.js library (https://validatejs.org/#validators-email) on both the client and server.

As for "@"@example.com, while it may be in the spec, it will definitely not be "fixed" if the validator rejects it. This is a very edge case scenario...

**Comment by Fidgetcetera** [comment]
Ahhh shoot, okay. I just figured it out. I didn't see that I had whitespace around the email mistakenly, and in re-typing the email, I didn't include that, and then assumed it was the period in the email that broke it. My bad!
