### ISSUE TITLE
Does the search support chinese

### ISSUE THREAD

**Issue by michaelllh** [Requarks/wiki#520]

**Comment by NGPixel** [comment]
Not in 1.x, but it will be in 2.0.

**Comment by yuhr123** [comment]
Hi @NGPixel , is there any temporary solution for this? We like and want to using Wiki.js with the feature of search support Chinese language.

**Comment by FalseSummer** [comment]
> Not in 1.x, but it will be in 2.0.

Here is machine translation
I tried to deploy it for enterprise use, but I found that it does not support Chinese search
I tried elasticsearch-analysis-ik but it still didn't work
Hope the following version can use Chinese search, thank you
