### ISSUE TITLE
Where to find version in the UI

### ISSUE THREAD

**Issue by kopax** [Requarks/wiki#521]
How can we find in the UI the version of wiki JS ?

We have installed our `:latest` image 4 month ago,  we were waiting for `svg draw` in browser features and improvement for text editor. Is it release already ?

**Comment by NGPixel** [comment]
Settings > System Info

**Comment by kopax** [comment]
@NGPixel thanks for your reply, I do not have `System Info` in my `Settings`.

I have:

- My Profile
- Stats
- Logout

I am using LDAP for user account, is it related?

**Comment by NGPixel** [comment]
You must have a very old version then. You can look in `package.json` for the version.

**Comment by kopax** [comment]
I have the following version:

```json
  "name": "wiki",
  "version": "1.0.78",
```

I would like to upgrade, but I am already using the latest image:

```Dockerfile
FROM requarks/wiki:latest

ADD config.yml /var/wiki/config.yml
ADD git.pem /etc/wiki/keys/git.pem
RUN chmod 600 /etc/wiki/keys/git.pem
```

This image was build 6 weeks ago, is this what you meant by `veryold`?

**Comment by NGPixel** [comment]
1.0.78 is the latest version. Are you an administrator on the wiki? That would explain why you don't see System Info.

**Comment by kopax** [comment]
Well... I am not sure, I have been using it directly with LDAP using the `test` user we have created for it.

The first user was a test account, the 2nd user and password was created with SHA1. This user was unable to login into wiki.js until we changed the password to CLEAR Password. 

It's the only account we have and everyone use it, I was waiting for wiki.js upgrade.

If this is not the admin account, then what is the admin account ? (we only have two users on the ldap branch)

**Comment by NGPixel** [comment]
The admin account is defined in your dockerfile, e.g.:
`ENV WIKI_ADMIN_EMAIL admin@example.com`

Default password is `admin123`, which you should change upon login.

**Comment by kopax** [comment]
I have been able to login using the `admin` account and I am able to see my version thank you.

Regarding security, do you think the LDAP plugin will soon accept different encryption? 
We can only connect if we store password in clear text which is not acceptable.

Generally, a ldap client should never take predecence for encryption/decryption, for that we should use ldapsearch.
