### ISSUE TITLE
Doesn't install properly!

### ISSUE THREAD

**Issue by physiii** [Requarks/wiki#522]
### Actual behavior
css not loading properly, no way of saving file - see attached image

![screenshot from 2018-05-10 10-09-23](https://user-images.githubusercontent.com/6277642/39877014-5d42c8ce-543a-11e8-9f8d-6aa2229c6e72.png)

### Expected behavior
the wiki shown in the demo

![screenshot from 2018-05-10 10-14-45](https://user-images.githubusercontent.com/6277642/39877229-03bdb222-543b-11e8-94e0-79c7cc4f5e8d.png)

### Steps to reproduce the behavior
curl -sSo- https://wiki.js.org/install.sh | bash

**Comment by NGPixel** [comment]
Your `host` is wrong in your config.yml

https://docs.requarks.io/wiki/install/troubleshooting#weird-display-no-styling-missing-css
