### ISSUE TITLE
LDAP account passwords must use CLEAR TEXT otherwise they can't login

### ISSUE THREAD

**Issue by kopax** [Requarks/wiki#524]
Following issue https://github.com/Requarks/wiki/issues/521

I have the following version:

- version: 1.0.78

Our LDAP user can only connect if the encryption used for the password is `CLEAR TEXT`.

Is this on the roadmap for v2? Is there a possible fix? 

Our current strategy was to create only one user to prevent password stealing, but then we do not have permissions management within our wiki.

**Comment by NGPixel** [comment]
We use the `passport-ldapauth` strategy:
https://github.com/vesse/passport-ldapauth

You can check all available options, but any missing feature should be reported there. Wiki.js does not handle the actual ldap operations.
