### ISSUE TITLE
Page Navigation

### ISSUE THREAD

**Issue by sventer** [Requarks/wiki#53]
When creating new pages that don't appear in the navigation pane on the left.

I create pages like:
/mypage and
/mydir/mypage

The pages are created and the content seems to by correct.

I can navigate to the pages by entering the URL in the browser address bar.

OS Windows 10
Wiki.js v1.0.0-beta.8

**Comment by NGPixel** [comment]
The sidebar lists the contents of the current page, not a list of pages. A tree view of all pages will come in Beta 10.

See #21
