### ISSUE TITLE
Can i use monotype font in editor?

### ISSUE THREAD

**Issue by balazsadam** [Requarks/wiki#530]
I would like write tables, but it is very hard with non monotype font. 
Can i switch to another font, maybe in code?

Thanks

**Comment by NGPixel** [comment]
- Clone the repo and install npm dependencies as explained in the [docs](https://docs.requarks.io/wiki/developers/developer-guide)
- Edit line 305 from [editor.scss](https://github.com/Requarks/wiki/blob/master/client/scss/components/editor.scss#L305) and change `$core-font-standard` for `$core-font-monospace`
- Rebuild client files: `npm run build`
- Copy the generated .js files from `/assets` to your server.
