### ISSUE TITLE
Page with url "/edits" requires login to read despite wiki being set to public

### ISSUE THREAD

**Issue by walczakp** [Requarks/wiki#537]
### Actual behavior
On our wiki we created a page under URL "/edits". This probably triggers the authentication mechanism, as wiki asks for login if the page is visited without user login. All other pages are read-only just fine, just this page requires login to even read content.
Wiki.js  v1.0.78 (from docker image)
Node.js Version: v8.9.4

### Expected behavior
Page with url "/edits" should be viewable without login on current settings.

### Steps to reproduce the behavior
Set up wiki to be publicly available read-only, create page with url "/edits" and try to visit it (the best would be to use different browser to have clean cookies).

**Comment by NGPixel** [comment]
A path starting with `/edit` is system-reserved and will cause such issues because of the way the permissions work. Avoid creating pages starting with this path.

This will no longer be an issue in 2.0 as there won't be such reserved words.
