### ISSUE TITLE
Question: external API for search on wiki pages

### ISSUE THREAD

**Issue by vnerozin** [Requarks/wiki#538]
Hi, Wiki.js Team,

We are using Wiki.js for help pages, but help pages are also integrated in our platform as readonly context help. Currently we want to implement search across these pages, but Wiki.js already solving this task, since it indexing pages and has integrated search. 

Is it possible to use Wiki.js for this task? Do you have an external API to get search results?

**Comment by NGPixel** [comment]
1.x doesn't have any API.

This will be introduced in 2.0 as the GraphQL API.
