### ISSUE TITLE
advice for project name and storage

### ISSUE THREAD

**Issue by choicky** [Requarks/wiki#54]
This project is being developed frequently. It would be known by more and more people. However, it's hard for people to identify which wiki because wiki is a common name. A unique name would be better, such as quarkwiki or like.

This wiki currently uses mongodb and txt for storage at the same time. I think it makes it difficult to backup or transfer to other server. I think use only txt or only database should be better.

**Comment by NGPixel** [comment]
The name is "Wiki.js", not just "wiki".

All content is stored on-disk. MongoDB only purpose if to store users, sessions, bruteforce attempts, index cache, etc. You don't need the contents of the MongoDB for backup or transfer. Only the on-disk content is needed.

I might offer Loki.js as a replacement for MongoDB in the future. This is file based and would remove the dependency on MongoDB.
