### ISSUE TITLE
Newly installed wiki will not load

### ISSUE THREAD

**Issue by joelft** [Requarks/wiki#544]
### Actual behavior
The wiki will not load in my web browser
"localhost didn't send any data." error when trying to view the wiki - after waiting for about 5 minutes

### Expected behavior
Able to see my shiny new wiki

### Steps to reproduce the behavior
I am running the docker setup via docker-compose by following the directions [HERE](https://docs.requarks.io/wiki/install/docker#using-docker-compose).

docker does not seem to be throwing any errors, and the wiki *appears* to be starting correctly

**Comment by wannessels** [comment]
I have the same issue, trying to set up via docker-compose on a fresh ubuntu 18.04

`$ sudo docker-compose up
Creating network "wikijs_default" with the default driver
Creating wikijs_wikidb_1 ...
Creating wikijs_wikidb_1 ... done
Creating wikijs_wikijs_1 ...
Creating wikijs_wikijs_1 ... done
Attaching to wikijs_wikidb_1, wikijs_wikijs_1
wikidb_1  | 2018-06-12T20:40:47.938+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=0f92bfdf609c
wikidb_1  | 2018-06-12T20:40:47.938+0000 I CONTROL  [initandlisten] db version v3.6.5
wikidb_1  | 2018-06-12T20:40:47.938+0000 I CONTROL  [initandlisten] git version: a20ecd3e3a174162052ff99913bc2ca9a839d618
wikidb_1  | 2018-06-12T20:40:47.938+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.1t  3 May 2016
wikidb_1  | 2018-06-12T20:40:47.938+0000 I CONTROL  [initandlisten] allocator: tcmalloc
wikidb_1  | 2018-06-12T20:40:47.938+0000 I CONTROL  [initandlisten] modules: none
wikidb_1  | 2018-06-12T20:40:47.938+0000 I CONTROL  [initandlisten] build environment:
wikidb_1  | 2018-06-12T20:40:47.938+0000 I CONTROL  [initandlisten]     distmod: debian81
wikidb_1  | 2018-06-12T20:40:47.938+0000 I CONTROL  [initandlisten]     distarch: x86_64
wikidb_1  | 2018-06-12T20:40:47.938+0000 I CONTROL  [initandlisten]     target_arch: x86_64
wikidb_1  | 2018-06-12T20:40:47.938+0000 I CONTROL  [initandlisten] options: { net: { bindIp: "wikidb" }, storage: { mmapv1: { smallFiles: true } } }
wikidb_1  | 2018-06-12T20:40:47.940+0000 I -        [initandlisten] Detected data files in /data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
wikidb_1  | 2018-06-12T20:40:47.940+0000 I STORAGE  [initandlisten]
wikidb_1  | 2018-06-12T20:40:47.940+0000 I STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
wikidb_1  | 2018-06-12T20:40:47.940+0000 I STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
wikidb_1  | 2018-06-12T20:40:47.940+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=1412M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),cache_cursors=false,log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),statistics_log=(wait=0),verbose=(recovery_progress),
wikidb_1  | 2018-06-12T20:40:48.880+0000 I STORAGE  [initandlisten] WiredTiger message [1528836048:880663][1:0x7f0c45fd2a00], txn-recover: Main recovery loop: starting at 8/7168
wikidb_1  | 2018-06-12T20:40:49.004+0000 I STORAGE  [initandlisten] WiredTiger message [1528836049:4498][1:0x7f0c45fd2a00], txn-recover: Recovering log 8 through 9
wikijs_1  | 2018-06-12 20:40:49,043 CRIT Supervisor running as root (no user in config file)
wikijs_1  | 2018-06-12 20:40:49,051 INFO RPC interface 'supervisor' initialized
wikijs_1  | 2018-06-12 20:40:49,051 CRIT Server 'unix_http_server' running without any HTTP authentication checking
wikijs_1  | 2018-06-12 20:40:49,052 INFO supervisord started with pid 1
wikidb_1  | 2018-06-12T20:40:49.065+0000 I STORAGE  [initandlisten] WiredTiger message [1528836049:65498][1:0x7f0c45fd2a00], txn-recover: Recovering log 9 through 9
wikidb_1  | 2018-06-12T20:40:49.123+0000 I STORAGE  [initandlisten] WiredTiger message [1528836049:123171][1:0x7f0c45fd2a00], txn-recover: Set global recovery timestamp: 0
wikidb_1  | 2018-06-12T20:40:49.146+0000 W STORAGE  [initandlisten] Detected configuration for non-active storage engine mmapv1 when current storage engine is wiredTiger
wikidb_1  | 2018-06-12T20:40:49.146+0000 I CONTROL  [initandlisten]
wikidb_1  | 2018-06-12T20:40:49.146+0000 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
wikidb_1  | 2018-06-12T20:40:49.146+0000 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
wikidb_1  | 2018-06-12T20:40:49.146+0000 I CONTROL  [initandlisten]
wikidb_1  | 2018-06-12T20:40:49.157+0000 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
wikidb_1  | 2018-06-12T20:40:49.158+0000 I NETWORK  [initandlisten] waiting for connections on port 27017
wikijs_1  | 2018-06-12 20:40:50,055 INFO spawned: 'wikijs' with pid 8
wikijs_1  | 2018-06-12 20:40:51,651 INFO success: wikijs entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

`

**Comment by wannessels** [comment]
Found my problem, I hadn't set the hostname to _mongodb_ in config.yml

> Make sure to set the db parameter to point to the mongo container. In the example docker compose file, the mongo container is named wikidb. As such, the db connection string should be set to: mongodb://wikidb:27017/wiki

**Comment by wannessels** [comment]
any errors in the logs?
`(sudo) docker-compose logs`

**Comment by joelft** [comment]
I see no errors. Ports are forwarded correctly (according to 'docker container ls').

**Comment by NGPixel** [comment]
You won't see any useful info in these logs, you must look in the /logs folder of the container.

**Comment by joelft** [comment]
@NGPixel
Ahh ok. Thank you for pointing me in the right direction. 

I viewed the logs and found a git error (typo on my part), which I fixed, but I'm still getting the same Problem. No new errors are being shown in /logs/wiki-stderr.log.

ERR_CONNECTION_RESET when trying to view my wiki.

**Comment by joelft** [comment]
Wow... I feel dumb. I did forward the ports correctly, but I had the wrong port in config.yml.

Sorry for this long issue for such a silly mistake. @NGPixel you did help me find the git error, though :)
