### ISSUE TITLE
Commit messages should be in present tense(imperative) instead of past tense

### ISSUE THREAD

**Issue by ramirahikkala** [Requarks/wiki#546]
### Actual behavior
Commit messages created by wiki starts with Added, Updated etc.
### Expected behavior
Common way is to write commit messages in present tense / imperative. So 'Add' instead of 'Added' etc.

**Comment by NGPixel** [comment]
Note taken for future commits.

**Comment by ramirahikkala** [comment]
I mean the commits that wiki makes automatically when it stores changes to git.

**Comment by omkarnix** [comment]
Hi, As a first timer, can I pick up this issue?
