### ISSUE TITLE
Can't access newly-installed wiki through hostname

### ISSUE THREAD

**Issue by mdibello** [Requarks/wiki#547]
### Actual behavior
After installing the wiki and running through the configuration, I am unable to access the wiki from the hostname (http://localhost:4096). I am, however, able to access the wiki via the port (http://localhost:3001), but without css.

### Expected behavior
I expect to be able to access the wiki from the the hostname I've provided, with css styling.

### Steps to reproduce the behavior
1. Install and configure wiki.js:
 - hostname = http://localhost:4096
 - port = 3001
2. Navigate to `http://localhost:4096` => unable to connect
3. Navigate to `http://localhost:3001` => can connect, but without css

### System Info
OS: Arch Linux
Kernel: 4.16.13-2-ARCH
Git: 2.17.1
Node.js: 10.4.0
MongoDB: 3.6.5-1
Memory Available: 7818 MB

**Comment by mdibello** [comment]
Update: I tried making the port on the hostname the same as the port so that:
- hostname = `http://localhost:40961
- port = `4096`
and everything worked fine.

My confusion with this issue arose from the troubleshooting page, in the section about the CSS styling issue. The text reads:

"For example, if you access your wiki at https://my.host.com:1234, you must set your host to  https://my.host.com:1234. This has no relation to the server port. It must match exactly the URL and port used by the client to access the wiki."

The assertion that the hostname has no relation to the server port led me to think that the port in the hostname and the server port _should not_ be the same. Must these two ports be the same (assuming the hostname includes a port)?

It's possible that I'm the only one who's had this issue, but, to me at least, this point was immensely confusing.

**Comment by garethwarry** [comment]
Could definitely be phrased a bit clearer, but it's written like that because Wiki.js recommends setting up a standard web server in front of node. For example, a reverse proxy using nginx. That's how that port number can be different than the host name's port number. The port number is the internal port the server listens on. The host name's port number is the port number accessible through nginx for HTTPS.

**Comment by NGPixel** [comment]
As @garethwarry mentionned, this is for reverse proxies. If you don't use any then the port and host will likely be the same.

The `host` part is no longer present in 2.0, so this should clear any confusion.
