### ISSUE TITLE
nginx reverse proxy example seems to work but the wiki.js theme and graphics are not showing

### ISSUE THREAD

**Issue by linkdragon70** [Requarks/wiki#549]
I read and executed the reverse proxy configuration example for wiki.js. (Https://docs.requarks.io/wiki/administration/setup-nginx-reverse-proxy)

Everything seems to work on the redirection side, but nginx can not keep the wiki.js themes, the home screen is white and only text appears.
___________________________________________________________________________________________________
Here is my nginx configuration:

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name @myserver.com;

    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:50m;
    ssl_session_tickets off;

    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers (... long line)
    ssl_prefer_server_ciphers on;

    ssl_certificate /etc/letsencrypt/live/@myserver.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/@myserver.com/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/@myserver.com/chain.pem;

   location / {
        proxy_set_header Host $http_host;
        proxy_pass http://127.0.0.1:1337;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_next_upstream error timeout http_502 http_503 http_504;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
        }
________________________________________________________________________________________________________

This is a representative image of the problem:

https://gyazo.com/e3f7adc3ed845fe484ce946a1c4bbfcd
_________________________________________________________________________________________________________

I did not modify the config.yml file, except for the http 1337 port to match the nginx reverse proxy configuration.

If you have an idea of the problem, I am open to any solutions from you.
Thank you!

**Comment by jbarnat** [comment]
I come across this project just yesterday, made a false assumption that command: `wiki configure` reads port number from **config.yml** but it doesn't. Try to run command like this:
```
node wiki configure 1337

**Comment by linkdragon70** [comment]
Actually, when i do the node wiki configure 1337 command, the nginx reverse proxy works and displays the wiki.js graphics. Despite this, after the configuration, the same phenomenon occurs. The reverse proxy does not display the graphic content.

**Comment by JoshuaMart** [comment]
In your config, you have set http or https ? 
If you have set http modify it to https

**Comment by NGPixel** [comment]
You must set the `host` parameter in `config.yml` to the full URL the client will enter.

**Comment by linkdragon70** [comment]
Big thanks! It was only to put the host in https ... I was sure that I did not need, that the reverse proxy of nginx was going to do the translation automatically. Thanks again!
