### ISSUE TITLE
cannot install behind proxy

### ISSUE THREAD

**Issue by nio101** [Requarks/wiki#55]
Hello,

When trying to install wiki.js behind an HTTP/HTTPS proxy, npm installs the dependencies (when properly configured), but the install.js script fails because the https.get function used to access github doesn't take the proxy into account... :(

**Comment by NGPixel** [comment]
Good point, I'll put an alternative installation method to get around this.

**Comment by NGPixel** [comment]
Fixed for Beta 10.

3c637183284cee12cf9ea3788461e1d8d3600578

**Comment by nio101** [comment]
thank you! :)
