### ISSUE TITLE
Feature Request: Upgrade Path

### ISSUE THREAD

**Issue by geraldsnm** [Requarks/wiki#550]
In order to be able to use this in the enterprise, need to have a clear understanding of the upgrade path (updating mongo schema/software/etc). 

If this is already covered by the standard install process that's fine too! Just need confirmation on how updates to wiki.js is handled on existing installs.

**Comment by NGPixel** [comment]
https://docs.requarks.io/wiki/install/upgrade

Wiki.js 2.x will introduces in-place upgrade from the UI.
