### ISSUE TITLE
Subfolder hosting

### ISSUE THREAD

**Issue by nvpmai** [Requarks/wiki#552]
Hi,

Do wiki.js support subfolder?

For example if we want to link it to holistics.io/docs instead of docs.holistics.io, would this be possible?

We want to do this for SEO purpose.

Thanks,
Mai

**Comment by NGPixel** [comment]
No, a subfolder installation is not supported. However, there's absolutely no difference from a SEO perspective to using a subdomain vs a subfolder, it's treated equally the same as confirmed by Google.
