### ISSUE TITLE
Empty reply from server using docker-compose

### ISSUE THREAD

**Issue by jasonsturges** [Requarks/wiki#554]
### Actual behavior

Using `docker-compose up` results in empty response from server.

```
$ curl -I http://localhost
curl: (52) Empty reply from server
```

Similar to #529 and #544, but I'm not seeing any errors in my logs

Configuration:
- [docker-compose.yml](https://gist.github.com/jasonsturges/9ddf1c7128c88d6535cf2f44dda6c3c4#file-docker-compose-yml)
- [wiki-config.yml](wiki-config.yml)

Output:
- [Command line output](https://gist.github.com/jasonsturges/9ddf1c7128c88d6535cf2f44dda6c3c4#file-command-line)
- [supervisord.log](https://gist.github.com/jasonsturges/9ddf1c7128c88d6535cf2f44dda6c3c4#file-supervisord-log)
- [wiki-stderr.log](https://gist.github.com/jasonsturges/9ddf1c7128c88d6535cf2f44dda6c3c4#file-wiki-stderr-log) (empty file)
- [wiki-stdout.log](https://gist.github.com/jasonsturges/9ddf1c7128c88d6535cf2f44dda6c3c4#file-wiki-stdout-log)

### Expected behavior

Http response of some kind, even if error.

### Steps to reproduce the behavior

Use sample documentation [config.yml](https://github.com/Requarks/wiki/blob/master/config.sample.yml), changing the mongodb url from localhost to wikidb:

```db: mongodb://wikidb:27017/wiki```

Use the documentation [docker-compose.yml](https://github.com/Requarks/wiki/blob/master/tools/docker-compose.yml)

Launch docker compose:

```$ docker-compose up```

**Comment by jasonsturges** [comment]
Sorry, issue was the port after all.

My `config.yml` specified the port at 80

```
host: http://localhost
port: 80
```

However, I still had the port 3000 binding in my `docker-compose.yml`

```
    ports:
      - '80:3000'
```

I simply needed to change the `docker-compose.yml` to:

```
    ports:
      - '80:80'
```

**Comment by yeurplc** [comment]
can't get It work in Docker :

nor with Docker run 

```bash
sudo docker run -d --restart always \
    -p 5000:80 \
    -e "WIKI_ADMIN_EMAIL=admin@example.com" \
    -v wiki.conf:/var/wiki/config.yml \
    -v wiki.log:/logs \
    -e "MONGO_URL=mongodb://db" \
    -e "ROOT_URL=http://192.168.1.20:5000" \
    --link "mongodb:db" \
    --name wiki \
    requarks/wiki
```

same errors with docker-compose :


```bash
wikijs    | 2018-07-16 08:00:29,627 CRIT Supervisor running as root (no user in config file)
wikijs    | 2018-07-16 08:00:29,633 INFO RPC interface 'supervisor' initialized
wikijs    | 2018-07-16 08:00:29,634 CRIT Server 'unix_http_server' running without any HTTP authentication checking
wikijs    | 2018-07-16 08:00:29,634 INFO supervisord started with pid 1
wikijs    | 2018-07-16 08:00:30,637 INFO spawned: 'wikijs' with pid 8
wikijs    | 2018-07-16 08:00:31,066 INFO exited: wikijs (exit status 1; not expected)
wikijs    | 2018-07-16 08:00:32,072 INFO spawned: 'wikijs' with pid 14
wikijs    | 2018-07-16 08:00:32,482 INFO exited: wikijs (exit status 1; not expected)
wikijs    | 2018-07-16 08:00:34,488 INFO spawned: 'wikijs' with pid 20
wikijs    | 2018-07-16 08:00:34,917 INFO exited: wikijs (exit status 1; not expected)
wikijs    | 2018-07-16 08:00:37,927 INFO spawned: 'wikijs' with pid 26
wikijs    | 2018-07-16 08:00:38,347 INFO exited: wikijs (exit status 1; not expected)
wikijs    | 2018-07-16 08:00:39,349 INFO gave up: wikijs entered FATAL state, too many start retries too quickly
```
