### ISSUE TITLE
problem of git version checking

### ISSUE THREAD

**Issue by choicky** [Requarks/wiki#56]
Wiki.js version: 1.0 Release - Beta 9

Installation succeeded.

Continue with configuration wizard? Yes

```
Error: Git version is too old. Minimum is v2.7.4.
```

```
git --version
git version 2.7.4
```

**Comment by NGPixel** [comment]
Indeed, I'll release a fix tonight.

In the meantime, you can manually edit configure.js and change the value to 2.7.4 to get past it:
https://github.com/Requarks/wiki/blob/master/configure.js#L94

**Comment by NGPixel** [comment]
Fixed for Beta 10

6fdea32a509c50acf7f7ad98ef10966e3fbedca7

**Comment by danny-idingo** [comment]
I am having the same problem.

wiki.js@1.0.0-beta.12.13 

git --version
git version 2.8.1
