### ISSUE TITLE
New repo - Cloud Foundry deployment for Wiki.js

### ISSUE THREAD

**Issue by seafre** [Requarks/wiki#561]
### Actual behavior
Wiki.js unable to be deployed to Cloud Foundry

### Expected behavior
Deploy to Cloud Foundry

### Steps to reproduce the behavior
Contribution for new repository under Requarks. Deployment to IBM Cloud Foundry with DevOps Toolchain pipeline working but is rough - https://github.com/seafre/wiki-ibm-cloud-foundry

**Comment by NGPixel** [comment]
Thanks! However the deploy button and some config have the wrong git repo url.

**Comment by seafre** [comment]
Mistake fixed in subsequent commits 👍

**Comment by NGPixel** [comment]
I imported the project into https://github.com/Requarks/wiki-ibm-cloud-foundry and you should have write access.

I added a deploy button to the main repo as well (and some fresh new buttons for Docker and Heroku!)
