### ISSUE TITLE
Error: Not enough memory. Minimum is 768 MB.

### ISSUE THREAD

**Issue by choicky** [Requarks/wiki#57]
Some low end vps offer no more than 512 MB memory.  I think wiki.js should be able to run at such low end vps.

**Comment by NGPixel** [comment]
It's able to. The issue is with `npm install`, which often freezes and crash. If all dependencies are installed however, it will run just fine with 512 MB.

I'll test do some tests again with the new Beta 9 to check if it now works fine on 512 MB...

**Comment by NGPixel** [comment]
Unfortunately, `npm install` still gets killed on a 512MB RAM machine. So I'll leave the 768MB minimum requirement for now.

**Comment by choicky** [comment]
I have a low end VM allocated 768MB momery.  However, it's 1000 * 1000 * 768 rather than 1024 * 1024 * 768.  Therefore, I'was thrown "Not enough memory. Minimum is 768 MB."

The VM is KVM based and a swap momery of 768 momery is also allocated which is 1024 * 1024 * 768. However, swap momery is exluded in os.totalmem().

I think swap momery should be included.

**Comment by NGPixel** [comment]
Unfortunately there's no easy way to get the swap partition size. I changed them minimum to use decimal (1000) instead of binary (1024) in Beta 12, so you should no longer get the error.
