### ISSUE TITLE
Missing edit/create/delete buttons

### ISSUE THREAD

**Issue by bitworm** [Requarks/wiki#577]
I just installed wiki.js and the edit/create/delete buttons that should be in the upper right hand side are not visible on any page:
![image](https://user-images.githubusercontent.com/7471955/42407104-6c512ccc-816a-11e8-916e-b4964f46c244.png)

This was the result of the following installation process:
- installed prereqs (mongo required creation of `/data/db`, still requires `mongod` on reboot)
- installed wiki.js, followed the config
- reboot; call `node wiki start` from previously installed/synced wiki in ~/Dropbox

What should the install process be for syncing a wiki across Dropbox?

**Comment by NGPixel** [comment]
You need to login first (in the sidebar)

**Comment by bitworm** [comment]
ah.  Ok, thank you.
