### ISSUE TITLE
Talk/discussion feature

### ISSUE THREAD

**Issue by izahn** [Requarks/wiki#58]
Most wikis that I've used have a mechanism for discussing edits. (For example, https://www.mediawiki.org/wiki/Help:Talk_pages)

Is that planned for Wiki.js?

**Comment by NGPixel** [comment]
Could be an interesting feature to implement. There's just the matter of where these comments would be saved (either in the DB or as file(s) within the github repository). There's definitely some planning to do before implementing such feature.

**Comment by NGPixel** [comment]
Moved ticket to Feature Board: https://wikijs.canny.io/features/p/talk--discussion-feature-per-page

Close this ticket.

**Comment by rexunderlinehxiao** [comment]
Is that planned for 2.0 ?

**Comment by jabyrd3** [comment]
is there anywhere i can track this? I'd also be happy to implement it; i think having these end up in the git repo would be absolutely stellar if possible

**Comment by johnaweiss** [comment]
WANT!

**Comment by eeshugerman** [comment]
Updated feature board link is https://requarks.canny.io/wiki/p/talk--discussion-feature-per-page

Please upvote there to express your interest

**Comment by johnaweiss** [comment]
@eeshugerman  Why did you give me a thumbs down here?

**Comment by eeshugerman** [comment]
It's kind of rude to post feature request comments that do not add to the discussion when you could simply 👍/upvote, especially on volunteer/community projects, especially on a three year old closed issue. But I suppose my 👎 without explanation was rude too. No hard feelings?

**Comment by johnaweiss** [comment]
ok. I am clearly in support of this feature. The link above was a dead link, i tried to upvote over there and couldn't. Not my fault!
thx
