### ISSUE TITLE
Search returns results that are not accessible for the current user

### ISSUE THREAD

**Issue by martindines** [Requarks/wiki#580]
Search returns results that are not accessible for the current user. These results may contain sensitive and/or confidential information which should not be visible to users without read permission.

### Actual behavior

Search results are not filtered by the current user's access permission

### Expected behavior

Search results are filtered by the current user's access permission

### Steps to reproduce the behavior

1. Create a user with Deny permission for page `/example`
2. Log in as above user
3. Search 'example' and see `/example` page listed. This page is not accessible by the user and therefore should not return in search

**Comment by NGPixel** [comment]
Duplicate of #492
