### ISSUE TITLE
Dockerhub lacks fresh, automatic builds

### ISSUE THREAD

**Issue by ikarulus** [Requarks/wiki#583]
### Actual behavior
Docker image on dockerhub lacks automatic builds. Last build dates back to 5 months ago.

### Expected behavior
Fresh builds of v1.0 tagged stable or latest and v2.0 tagged latest or e.g. dev.

### Steps to reproduce the behavior
Try to pull requarks/wiki or :eyes: https://hub.docker.com/r/requarks/wiki/tags/.

**Comment by NGPixel** [comment]
Docker images are up-to-date and automated.

1.0.78 is the latest stable version, which is about 5 months old. No further updates are being released for the 1.x branch as work is now being done on the 2.0 branch, which will be released later this year.
