### ISSUE TITLE
Persistent navigation, or other navigation options?

### ISSUE THREAD

**Issue by MostHated** [Requarks/wiki#587]
Hello,
   I was wondering if there is more information on how to customize or have different options for the navigation? I see that the main site has a very different navigation setup when going to subpages but I have not seen any information on the setup. Also, is there a way to have actual links to other pages directly in the navigation instead of having it take you to an anchor in the current page so that I can have one consistent navigation panel that can perhaps have collapsable fold down menus? If I link directly to a subpage using a subfolder in the URL, it doesn't show anything about the main navigation and often will be scrolled down slightly so you can't easily see the "Home" button and it looks like the current menu items on that subpage are all that exist. 

Thanks,
-MH

**Comment by NGPixel** [comment]
The navigation in 1.x is not customizable (it's coming in 2.0). The sidebar reflects the contents of the current page + home + go back link if the folder also has a page of the same name.
