### ISSUE TITLE
Left Menu - Scrollbar

### ISSUE THREAD

**Issue by alexdel35** [Requarks/wiki#588]
### Actual behavior

There is no scrollbar when the left panel is too large to display all the options.
(tested under Chrome 67.0.3396.99 & Firefox 61.0.1 (64 bits))

### Expected behavior

Propose a scrollbar when the left panel is too large to display all the options.

### Steps to reproduce the behavior

Create a large menu in the left panel.

**Comment by NGPixel** [comment]
Duplicate of #170
