### ISSUE TITLE
When setting a custom port via `node wiki configure`, doesn't use that port for fetching js files.

### ISSUE THREAD

**Issue by jclangst** [Requarks/wiki#589]
### Actual behavior
See title. Will load the initial request to custom port (in my case 3005). But the asset requests still go to localhost with no port extension.

![screenshot from 2018-07-26 13-37-47](https://user-images.githubusercontent.com/13301098/43278439-24016530-90d9-11e8-9e84-56fea4c7a3dc.png)

### Expected behavior
Maybe I'm mistaken, but i'd expect them to go to the listening port?

Edit:

Ok. I think I figured it out. I had to specify the port in the url string as well as in the port input. It might be nice for it to be a little more clear that the url is the endpoint for a custom server OR the main wiki.js server. For whatever reason, I thought the input was simply requesting for the port to be a seperate from the url input. I'll leave this open (even though it **is** solved) as a potential enhancement. If you think the issue is just me being dumb, feel free to close it.

**Comment by gitbufenshuo** [comment]
the same problem that i met
