### ISSUE TITLE
Search on the docs wiki doesn't work

### ISSUE THREAD

**Issue by kub1x** [Requarks/wiki#59]
Hey, 
I went to the [documentation site](https://docs.requarks.io/wiki/install) put *git* into the search box and got *No results found* ;) 
Cheers

**Comment by NGPixel** [comment]
Search is disabled by default in guest mode (which is what you're in while browsing the docs site). This will be fixed in a later release.

**Comment by NGPixel** [comment]
Fixed for Beta 11 (d02b4a359186508fe1b4061ce8b0bbb765955e5b)
