### ISSUE TITLE
Forcing Git pushes and pulls

### ISSUE THREAD

**Issue by Ekultek** [Requarks/wiki#594]
This isn't an issue, it's just a couple questions. How often does git do the push and pull from the master branch (if the time is hardcoded where can I find it?), also, is there a command that can be given to the `wiki` to force a git pull or a git push?

IE:
 - `sudo node wiki git-pull` === `git pull origin master`
 - `sudo node wiki git-push` === `git commit -m "<RAND>"`

**Comment by NGPixel** [comment]
Sync occurs every 5 minutes:
https://github.com/Requarks/wiki/blob/master/server/agent.js#L82

You can manually perform a git pull or push using standard git commands from the repository folder (it's an actual git directory).

**Comment by Ekultek** [comment]
Cool thank you!
