### ISSUE TITLE
No Changelog for v1.0.102

### ISSUE THREAD

**Issue by antonin-a** [Requarks/wiki#596]
### Actual behavior
The last update on [CHANGELOG ](https://github.com/Requarks/wiki/blob/master/CHANGELOG.md) is v1.0.78 - 2018-02-23.

### Expected behavior
As v1.0.102 is available since yesterday I try to find the changelog before updating.

### Steps to reproduce the behavior
NA

Thanks a lot for this powerfull tool ! I looking forward the 2.0 version :)

**Comment by NGPixel** [comment]
Be patient, changelog and other info will be updated later today.
