### ISSUE TITLE
google id authentication

### ISSUE THREAD

**Issue by seanrenton** [Requarks/wiki#599]
### Actual behavior
can't seem to get google Id authentication figured out using the heroku deployment of wiki js

### Expected behavior
I was hoping there was a quick and easy way to add in the credentials from my google cloud service to use the google id login but can't seem to find anyway of doing this can you please advise me on how to do so?

**Comment by NGPixel** [comment]
You need to fork the [wiki-heroku](https://github.com/Requarks/wiki-heroku) repository and edit the `wiki/config.yml` file with your google authentication settings. Then deploy the app to Heroku using your forked repository.

**Comment by maeldd** [comment]
@seanrenton if you are looking for an exemple : https://github.com/maeldd/wiki-heroku/blob/5e13cd8651b91d103d87d98a641c97f621155ccc/wiki/config.yml
