### ISSUE TITLE
[BUG] "Create/Authorize User" modal on /admin/users doesn't do anything post-submit

### ISSUE THREAD

**Issue by ThomasWo** [Requarks/wiki#6]
Version: 1.0 Release - Beta 2

Summary:
After pressing submit on the "Create / Authorize User" modal on the /admin/users page, the modal disappears, but nothing happens with the data that I entered.  No additional user appears on the page and Chrome Dev Tools don't log any network traffic sending to the server.  I've tested this using both the "Local Database" and "Google ID" provider options.

Steps to repro:
0. Have an instance of Requark Wiki installed/set up with existing super user
1. Navigate to /admin/users and click "Create / Authorize User"
2. Enter information for user (You could use Google ID if for speed)
3. Click "Authorize User"

Expected Outcome:
4. The modal to disappear, the user to be authorized and listed on the /admin/users list page

Actual Outcome:
4. The modal disappears, but nothing happens to confirm that I've authorized a new user.  No amount of page refreshing makes this work.

Additional Notes:
Thanks for the great work so far, I'm looking forward to using this more!

**Comment by NGPixel** [comment]
Thanks for this detailed feedback!

This modal isn't linked to anything yet, as noted in the release notes for beta 2. It should be completed in the coming days with Beta 3.

However, you can already "create" social accounts (google, ms, etc.) by trying to login with that account. Once you reach the forbidden page (or the homepage if the guest feature is enabled), the user will appear in the list. You can then assign the proper access rights for that user. This behavior might change in the future to avoid polluting the user list with unwanted accounts, but in the meantime, you can use this workaround.

Nick

**Comment by NGPixel** [comment]
The Create / Authorize User dialog is now working properly in Beta 3. Also, the workaround explained above is no longer valid as accounts are now required to be authorized / exists to be able to login at all.

[https://github.com/Requarks/wiki/releases/tag/v1.0-beta.3](https://github.com/Requarks/wiki/releases/tag/v1.0-beta.3)

Nick

**Comment by ThomasWo** [comment]
Woot!  Thank you!
