### ISSUE TITLE
Problem running on alternative port

### ISSUE THREAD

**Issue by tristanbettany** [Requarks/wiki#600]
### Actual behavior

When running on a alternative port instead of port 80, not all pages are correctly accessible or do not load assets and scripts. The configure pages work fine on its custom port of 3000 however after configuring for running on a custom port, the urls in the source files do not seem to apply the port along with the host when loading in assets and scripts in the header.

### Expected behavior

Should be able to access the entire project on a custom port without failing assets and scripts

### Steps to reproduce the behavior

Install wikijs on a newly provisioned server and configure it during the installation process to use a port other than port 80. Then try and visit the installation afterwards to be served up a broken application.

**Comment by NGPixel** [comment]
The value you've set for `host` is incorrect. If you're using a custom port, you must include it in your host config as well.

https://docs.requarks.io/wiki/install/troubleshooting#weird-display-no-styling-missing-css
