### ISSUE TITLE
Running as user other than root

### ISSUE THREAD

**Issue by tristanbettany** [Requarks/wiki#601]
### Actual behavior

Trying to run ```node wiki start``` in a user other than root for an installation running on default port 80. Message presents as a successful start. The software is not listening for connections and not running. Running ```node wiki configure``` in a user other than root works as expected, perhaps due to defaulting to port 3000 instead of 80.

### Expected behavior

Should be able to run the server from another user other than root for security.

### Steps to reproduce the behaviour

Create a new user in linux. Install in a directory owned by that user. Run through the installation on port 3000 and configure the software to run on port 80. Afterwards starting the wiki as that user will not work. Starting it as root will work fine.

**Comment by NGPixel** [comment]
This is normal and not related to Wiki.js itself.

Listening to port 80 from any node software is not permitted by default on most linux systems. Check this [article](https://docs.requarks.io/wiki/install/troubleshooting#error-listening-on-port-xx-requires-elevated-privileges) for possible solutions.
