### ISSUE TITLE
Initial Setup fails on creating "Administration Account"

### ISSUE THREAD

**Issue by ChristianAEDev** [Requarks/wiki#602]
### Actual behavior
- Enter email/password for administrator on "Administration Account" screen during the initial setup
- Click "Continue"

The following error message is shown:
```
insert into "locales" ("code", "createdAt", "isRTL", "name", "nativeName", "strings", "updatedAt") values ($1, $2, $3, $4, $5, $6, $7) returning "id" - duplicate key value violates unique constraint "locales_code_unique"
```

### Expected behavior
No error is thrown after clicking "Continue" and the setup can be successfully finished.

### Steps to reproduce the behavior
- Checkout the *dev*-Branch
- Run `yarn` in the root folder of the project
- Run `docker run --name wikijs-postgres-dev -e POSTGRES_PASSWORD=wikijsrocks -e POSTGRES_USER=wikijs -e POSTGRES_DB=wiki -p 5432:5432 -d postgres` to setup a Docker container for the database
- Run `docker run -d -p 6379:6379 --name wikijs-redis-dev redis` to setup a Docker container for redis
- Rename `config.sample.yml` into `config.yml`
- Change the parameter `port` from 80 to 8080
- Run `yarn run dev`
- Open http://localhost:8080
- Follow the steps of the setup till reaching the *Administration Account* screen

**Comment by NGPixel** [comment]
Fixed. Make sure to empty the DB before trying again.
