### ISSUE TITLE
installation instructions don't take into account a parent directory with a `node_modules` directory inside of it

### ISSUE THREAD

**Issue by beaugunderson** [Requarks/wiki#61]
I followed the installation instructions from a directory `~/p/wiki-js` and ended up with all of the files in my home directory instead because of a pre-existing `node_modules` directory there.

**Comment by NGPixel** [comment]
That's the normal behavior of npm, and not an issue related to Wiki.js to be honest. But I guess not everybody is aware of this behavior so I'll add a note in the instructions.
