### ISSUE TITLE
[IDEA] Template for new document

### ISSUE THREAD

**Issue by muxahuk** [Requarks/wiki#613]
Hey

I don't know if u have considered this, but adding a templates for new documents would be really good.

Basically in admin area you would have "templates" section where you can add/edit/delete templates.

And then when you click "add new document" you can select 1 of created templates as a base for you'r document.

For ex.

- I create a template "technical specification" with some markup.
- I click create new document
- I choose my "technical specification" template
- I see the content that i created for template in my new file

As an alternative and better user experiance the "template" selection could be done after document is being created.

- I create a template "technical specification" with some markup.
- I create new document
- I see a dropdown list that i can click to apply a template
- After i click to 1 of templates
1. if i have content in my markup i see a prompt asking 'Are you sure you want to overwrite you'r content with a "{templateName}"'
2. if i have no content or i click "yes" on 1.
- I see the content that i created for template in my file

Thanks

**Comment by NGPixel** [comment]
https://requests.requarks.io/wiki/p/templates
