### ISSUE TITLE
git version check fails on mac os

### ISSUE THREAD

**Issue by rcraggs** [Requarks/wiki#62]
`git --version` (on my mac at least - Sierra) returns

`git version 2.11.0 (Apple Git-81)`

configuration.js uses regexs etc to check the version but tells me the "Git version is too old" although my version is newer than the required 2.7. 

I think the `81` at the end of that string is causing problems

**Comment by NGPixel** [comment]
Fixed for Beta 11

Commit 8daa772c619d6f12c214881ce03cda471bacee8f
