### ISSUE TITLE
wiki.js between git repo how time synchronization frequency

### ISSUE THREAD

**Issue by duanzhanling** [Requarks/wiki#627]
### Steps to reproduce the behavior

wiki.js between git repo how time synchronization frequency

how change synchronization frequency

**Comment by linkdragon70** [comment]
Already responded to this request

@NGPixel : Sync occurs every 5 minutes:
https://github.com/Requarks/wiki/blob/master/server/agent.js#L82

**Comment by duanzhanling** [comment]
@linkdragon70 ok,tks
