### ISSUE TITLE
wiki.js chokes on certain pages ERR_EMPTY_RESPONSE/502

### ISSUE THREAD

**Issue by mnpenner** [Requarks/wiki#630]
### Actual behavior

Page should load.

### Expected behavior

Page does not load. Returns `ERR_EMPTY_RESPONSE` when accessed directly, or "502 Bad Gateway" when accessed through nginx reverse proxy.

### Steps to reproduce the behavior

Create a wiki page with this content:

https://gist.githubusercontent.com/mnpenner/9c9aaadba38db24b2926044535b7ba85/raw/2fbc8814e8953f8ad5f0b91b20b772249dc93c9e/snippets.md

I have a few other pages that are failing too. Not sure what's causing it.  There's not a load of content on there.

Other pages like [this one](https://gist.githubusercontent.com/mnpenner/9c9aaadba38db24b2926044535b7ba85/raw/66a5d48066c5f5e3852e6a396b1b9637fc865dbe/screen.sh) load perfectly fine, so I'm not sure what it's choking on.

I say "choking" because it takes like 30 seconds before it craps out and gives me a 502, it's not an immediate failure.

I'm using a $5 VM from Digital Ocean w/ 1 GB memory, 25 GB SSD and 1vCPU.

Let me know if there's some more logging/debug info I can get for you.

**Comment by NGPixel** [comment]
Try to disable mathjax in your config.yml (and restart Wiki.js afterwards)
