### ISSUE TITLE
What 2.0 Bottlenecks can we help with?

### ISSUE THREAD

**Issue by speckofthecosmos** [Requarks/wiki#639]
Hi, working with a large movement org and we'd love where 2.0 is going. Is there something we can do to help you? We could fundraise or recruit developers or documentation writers.

**Comment by NGPixel** [comment]
Any type of help is appreciated!

For development, we especially need help on storage modules:
https://blog.requarks.io/developers-wiki/

To contribute financially, we are on OpenCollective:
https://opencollective.com/wikijs

**Comment by almereyda** [comment]
The blog link currently times out with Cloudflare.

> Error 522 Ray ID: 46adbfb9ee586397 • 2018-10-16 21:52:19 UTC
Connection timed out

**Comment by NGPixel** [comment]
@almereyda It's now back online
