### ISSUE TITLE
Fix your documentation website it's broken

### ISSUE THREAD

**Issue by webbby** [Requarks/wiki#642]
Your website https://docs.requarks.io/wiki tries to make cross origin script requests which are blocked and your page doesn't function right.

```
Access to Script at 'https://www.gitbook.com/public/js/space-part-09.437f3bac.js' 
from origin 'https://docs.requarks.io' has been blocked by CORS 
policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. 
Origin 'https://docs.requarks.io' is therefore not allowed access.
The response had HTTP status code 522.
```

**Comment by baer95** [comment]
![screenshot from 2018-09-26 17-54-17](https://user-images.githubusercontent.com/3203975/46092499-48d59b80-c1b5-11e8-8b6f-6c3f5a9e024e.png)

I could not reproduce the issue?

**Comment by baer95** [comment]
Tried it on Ubuntu 18.04.1, Firefox 62.0 and Chrome 69.0.3497.100. Both works, as resource seems to provide a `access-control-allow-origin: *` header in my case.

But I get this different error in both browsers:

![screenshot from 2018-09-26 21-02-44](https://user-images.githubusercontent.com/3203975/46102829-8ba46d00-c1cf-11e8-8b08-bf8ddccd0ad9.png)
