### ISSUE TITLE
Failing to load resource after installation

### ISSUE THREAD

**Issue by breakfastmeansbreakfast** [Requarks/wiki#643]
Hi guys

Installation goes without a hitch, I run `npm start` in the new wiki directory but then it doesn't display properly. See screenshot:

https://imgur.com/a/JHQuFC5

Weirdly, the installation process loads all the css etc successfully.

**System**
OS: Debian 9.5 stretch
Apache2
Kernel: x86_64 Linux 4.9.0-8-amd64
Shell: bash 4.4.12
DE: XFCE
WM: Xfwm4
CPU: Intel Core i5-3340M CPU @ 3.4GHz
GPU: Mesa DRI Intel(R) Ivybridge Mobile 
RAM: 1064MiB / 3861MiB

**Comment by winkelement** [comment]
Have you checked https://docs.requarks.io/wiki/install/troubleshooting#weird-display-no-styling-missing-css?

**Comment by breakfastmeansbreakfast** [comment]
Just checking my config and it seems to marry up with the web address, what do you think?

`host: 'http://localhost'
port: 9999`

**Comment by NGPixel** [comment]
As stated in the link above, you must include the put in your host if it's different then 80 or 443.

**Comment by breakfastmeansbreakfast** [comment]
Sorry - misread that link totally. Now working! 

Thanks for your help guys.
