### ISSUE TITLE
Is it possible to ask wiki.js to PULL from repository ?

### ISSUE THREAD

**Issue by lapinvert** [Requarks/wiki#647]
Appart from first set up where remote repo is cloned, I see that wikijs pulls the changes from time to time, but :

- Is there a defined pulling rule / frequency ? 
- Can we force him to pull without going into shell ?

**Comment by winkelement** [comment]
> * Is there a defined pulling rule / frequency ?

I think a sync happens every 5 minutes. See #627

**Comment by NGPixel** [comment]
A sync occurs automatically every 5 mins. It first pulls, then push.

There's no way to force pull/push from the UI yet. This is coming in 2.0.
