### ISSUE TITLE
Is there an easy way to curl for version info of the wiki instance?

### ISSUE THREAD

**Issue by drduker** [Requarks/wiki#653]
### Actual behavior
curl https://wiki.example.com/api/info or something like this:
404
### Expected behavior
run command and get version info.
### Steps to reproduce the behavior

This shouldn't be a feature just a lack of API documentation perhaps?

**Comment by NGPixel** [comment]
No, that's not possible in v1. You'll be able to query the version via the GraphQL API in v2, provided you have a valid API token.
