### ISSUE TITLE
504 Gateway Timeout

### ISSUE THREAD

**Issue by gl-ronak** [Requarks/wiki#659]
I am running wiki js on Ubuntu 16.04 AWS EC2 instance. 
Here are the configuration settings:
![1 general](https://user-images.githubusercontent.com/23177844/46841590-cab0f180-cd7d-11e8-9de7-5d62c71f8073.PNG)

Everything else was default setting and I skipped Git step.

I am getting 504 error when port is less than 1024. If port is greater than 1024 then the CSS doesn't load.

I did try Solution A & B on this page but it was still not able to make wiki work
https://docs.requarks.io/wiki/install/troubleshooting#weird-display-no-styling-missing-css

**Comment by NGPixel** [comment]
Look at the logs by starting wiki.js in interactive mode `node server`

504 error is a gateway error. Make sure it works without a proxy in front of it first.

**Comment by gl-ronak** [comment]
error: [SERVER] Port 80 is already in use!

**Comment by gl-ronak** [comment]
@NGPixel Thanks for the help. I got everything working for port 80
![image](https://user-images.githubusercontent.com/23177844/46886000-69852e80-ce0e-11e8-85bb-e503ac55957f.png)

But now the css won't load.
![image](https://user-images.githubusercontent.com/23177844/46886046-8f123800-ce0e-11e8-849c-a774830c62d3.png)

Refused to execute script from 'http://ec2-xx-xxx-xxx-xxx.compute-1.amazonaws.com/login' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

**Comment by NGPixel** [comment]
Your `host` config is wrong in `config.yml`. It must match exactly the url you're using as a client.

**Comment by gl-ronak** [comment]
Thanks! It working
