### ISSUE TITLE
Image file upload fails

### ISSUE THREAD

**Issue by KimDaesap** [Requarks/wiki#66]
Uploading an image several times will cause file uploads to fail.
After the failure, file was created in the wiki's repo path.

1. Select upload file
![issue-01](https://cloud.githubusercontent.com/assets/5153125/24997808/f1fa911a-2072-11e7-8a00-5499b4c280b7.png)

2. Upload failed
![issue-02](https://cloud.githubusercontent.com/assets/5153125/24997877/3469b602-2073-11e7-8710-40a75c75ddb5.png)

3. Wiki's repo
![issue-03](https://cloud.githubusercontent.com/assets/5153125/24997934/604753ba-2073-11e7-9354-abad115f4a7f.png)

**Comment by efimlosev** [comment]
Do  you use any proxy like Nginx?

**Comment by KimDaesap** [comment]
No, local network environment. 
We will test the cause of the more accurate occurrence. Maybe the problem is caused by uploading a Korean file name.

**Comment by StevenH001** [comment]
I had this same issue as well. Mine was due to the Node.exe cmd window being closed out of. Yours may be different, but its worth a check.

**Comment by NGPixel** [comment]
The *Unable to fetch updated listing* error occurs when the thumbnail could not be generated within 10 seconds (after upload). So it's possible the thumbnail process eventually completed and would be available if you closed and re-opened the image manager.

Adding a more verbose error would most likely help identify the cause.

**Comment by KimDaesap** [comment]
Sorry, this is my mistake.
I closed the Node cmd window with no output, which is a problem.
Resolved.

![issue-04](https://cloud.githubusercontent.com/assets/5153125/25031001/74da0264-2104-11e7-8e7d-38e6b82fbc7e.png)

**Comment by reidaragasoster** [comment]
I have the same issue. But I'm running in docker ( compose) . Any tips ?
I can se the files are uploaded in /data/temp-upload in in wikijs container.
