### ISSUE TITLE
Editing on iPad

### ISSUE THREAD

**Issue by idm** [Requarks/wiki#660]
### Actual behavior
iPad editor behaviour is strange, almost irritating

- Caps key doesn’t release after typing a letter
- No obvious way to select sequence of characters
- Double-tap on a word places cursor at start of word

### Expected behavior
Expected text editing to be similar to editing this text

### Steps to reproduce the behavior
Open a page for editing on an iPad (A1822 with iOS 12.1)

**Comment by NGPixel** [comment]
mobile editing is not supported on 1.x. Proper support is coming 2.0.

**Comment by memespring** [comment]
In the meantime , is there a way of disabling codemirror and reverting to a textarea?
