### ISSUE TITLE
Nice to have a little more advanced file manager

### ISSUE THREAD

**Issue by efimlosev** [Requarks/wiki#67]
Hello,
First, thank you for the wonderful project.
Second, it would be nice if we  are able to move directories and files

Many thanks,
Efim

**Comment by NGPixel** [comment]
You can already move files by right-clicking the file and use the Move option.

**Comment by NGPixel** [comment]
Moved ticket to Feature Board: https://wikijs.canny.io/features/p/move-or-rename-folders-in-image--file-manager

Closing this ticket.
