### ISSUE TITLE
Self-dogfood documentation / demo missing

### ISSUE THREAD

**Issue by almereyda** [Requarks/wiki#670]
### Actual behavior

Currently wiki.js' documentation is hosted by GitBook. There is also no accessible demo linked from wiki.js.org

### Expected behavior

According to https://indieweb.org/selfdogfood it is advisable for FLOSS producers to use their own software themselves. For a project like a wiki, for example the documentation could be written with wiki.js to demonstrate its features.

**Comment by almereyda** [comment]
This is on purpose, as of https://github.com/Requarks/wiki#demo

**Comment by NGPixel** [comment]
@almereyda The GitBook hosting is temporary, until DigitalOcean decides to finally enable Kubernetes on our account, at which point will be able to switch back to a documentation site on Wiki.js.

**Comment by almereyda** [comment]
Thanks for letting me know. Best wishes for the way towards v2 from here.
