### ISSUE TITLE
Just wanted to drop by and say good job and I am looking forward to 2.0

### ISSUE THREAD

**Issue by jcklpe** [Requarks/wiki#672]
This project looks extremely promising and I'm surprised how far it's come since I last looked at it a couple of months ago! Very exciting!

I also logged a couple of requests on your feature request website and took the 1.x version for a spin. 

Can't wait to see 2.0. 

I'm also not a very good developer, I'm a UX Designer learning code, but if you ever need any help on the frontend let me know. I'm taking some classes on React and I'm a pretty hand CSS/HTML/Vanilla JS- Animation sort of guy. I can throw out some pretty swell visual pizzazz if you're up for it.

**Comment by NGPixel** [comment]
Thanks!
