### ISSUE TITLE
Idea - use Dillinger.io frontend for editor

### ISSUE THREAD

**Issue by jakguru** [Requarks/wiki#673]
Not a bug so much as an idea,

Use the editor w/ preview such as is found here:

https://github.com/joemccann/dillinger - http://dillinger.io/

As i'm writing, i find that it's much easier when i can preview what I'm writing in real time.

**Comment by NGPixel** [comment]
This is already in the upcoming v2:

![dw2ps-huqaajk8s](https://user-images.githubusercontent.com/15522395/47269937-6555c100-d532-11e8-915c-a36ce63c5d1e.jpg)
