### ISSUE TITLE
Search function Wiki.js

### ISSUE THREAD

**Issue by wikipictures** [Requarks/wiki#676]
### Actual behavior
I added some documents in my Wiki. I use this wiki to generate a clear overview of all the standard company documents

### Expected behavior
when i type a specific subject in the search bar he give me the suggestion. But i excpected that he led me straight to the page where that subject is explained. Now he only lead me to the page were it is stated but i have to scroll down some lenghts to finally find the subject which i am looking for. Cannot search for more than 2 words as well within the search bar.

### Steps to reproduce the behavior
--

**Comment by NGPixel** [comment]
These are limitations of the search engine in 1.x. It will be addressed in 2.0.

**Comment by wikipictures** [comment]
When will 2.0 be done? Or is t already in progress?

Thank you in advance.

Kind regards

Op 25 okt. 2018 om 04:40 heeft Nicolas Giard <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


These are limitations of the search engine in 1.x. It will be addressed in 2.0.
