### ISSUE TITLE
Trouble starting WikiJS with Docker

### ISSUE THREAD

**Issue by bassail** [Requarks/wiki#677]
### Actual behavior
WikiJS is not accessible through my web browser : HTTP 503
### Expected behavior
WikiJS is accessible and asks for login
### Steps to reproduce the behavior

Hello, 

I have a problem running WikiJS with Docker : 
I use the offcial image (I guess) : requarks/wiki:latest

Here is my Docker compose file : 

version: '3'
services:
  wikidb:
    image: mongo:3
    expose:
      - '27017'
    command: '--smallfiles --bind_ip ::,0.0.0.0'
    environment:
      - 'MONGO_LOG_DIR=/dev/null'
    volumes:
      - /home/user/tools/wikijs/data:/data/db
  wikijs:
    image: 'requarks/wiki:latest'
    links:
      - wikidb
    depends_on:
      - wikidb
    ports:
      - '5080:5080'
    environment:
      WIKI_ADMIN_EMAIL: user@mail.fr
      #VIRTUAL_HOST: domain.xx
      #VIRTUAL_PORT: 5080
    volumes:
      - /home/user/tools/wikijs/install/config.yml:/var/wiki/config.yml

I haven't changed much of the sample configuration file available here : https://github.com/Requarks/wiki/blob/master/config.sample.yml

except the port : 5080 and the "git" part, which is now like (I just want to test wikiJS first, without any git repo): 
`git: false` 

Here are the logs I get when running my containers with `docker-compose up` : 
2018-10-24 14:12:34,127 CRIT Supervisor running as root (no user in config file)
2018-10-24 14:12:34,170 INFO RPC interface 'supervisor' initialized
2018-10-24 14:12:34,171 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2018-10-24 14:12:34,171 INFO supervisord started with pid 1
2018-10-24 14:12:35,179 INFO spawned: 'wikijs' with pid 10
2018-10-24 14:12:36,840 INFO success: wikijs entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

MongoDB seems to be starting well also

Can anyone provide any help ? 

Thank you

**Comment by NGPixel** [comment]
Look into the `/logs` folder for errors

**Comment by bassail** [comment]
Just found out I ommited something in the config.yml.

The line db: mongodb://localhost:27017/wiki was still untouched.

Should have been set to : mongodb://wikidb:27017/wiki

My bad, didn't read the documentation very well !

Thank you
