### ISSUE TITLE
Can't set up wiki.js using ssh keys on github

### ISSUE THREAD

**Issue by padomu** [Requarks/wiki#679]
### Actual behavior
So I just installed wiki.js on my sever and started the configuration manager. I'm not a crack when it comes to git so I might miss something but the configuration manager fails to lead me through the configuration.

When I try to add a github repo using:

Repository-Url: https://github.com/<user>/<repo>
Branch: master
Authentification: SSH
Private Key Location: /etc/wiki/keys/my-key [no file ending]
Verify SSL: Yes

I also don't have a passphrase. This results in:

Error: Couldn't find remote ref master

If I try Repository-URL: git@github.com:<user>/<repo>.git I get the same error.

For me, git@github:com:<user>/<repo>.git isn't a url though. It's not clear what is wanted here. Make an exmaple of the formatting needed please.

Anyway, what should I do now? Th repo is empty on github, no idea what I can do else.

I also allowed write access in the github repo and I added the ssh key to the repo itself.

### Expected behavior
I expect to have an example format string in the desciprtion below the url field and basically I expect to just add the URL (or git@...) for an empty git repo and it works. If additional work is neede, I'd expect it to be stated.

EDIT: I solved it by doing an initial commit myself. That somehwo probably created the branch master? I don't know. I really think this is bad usability and should be changed. If you state that you need an empty repo, then I don't assume I have to do such things.

**Comment by NGPixel** [comment]
Is your Github repository initialized? This is a requirement.

You can see an example of the url format in the docs:
https://docs.requarks.io/wiki/install/installation/git#using-ssh

**Comment by padomu** [comment]
I got it working now, thanks. Also, i saw that after setup (ssh with a file)
