### ISSUE TITLE
Direct access to file/image manager

### ISSUE THREAD

**Issue by koallen** [Requarks/wiki#68]
Currently, one can only access the file/image manager in the editing mode. I think it would be good to allow user to access it directly from the home page or maybe settings page? This would provide a centralised location to manage all the files and images.

Potential use case:
Suppose I clone the git repo of the wiki and edit locally, having such a feature would allow me to first upload a bunch of images and insert the images in my editor. Without this feature, I would have to go into editing mode while I'm not really editing in the browser.

Thanks.

**Comment by NGPixel** [comment]
Moved ticket to Feature Board: https://wikijs.canny.io/features/p/image--file-manager-in-account-area

Closing this ticket.
