### ISSUE TITLE
Can't use IP only

### ISSUE THREAD

**Issue by padomu** [Requarks/wiki#681]
### Actual behavior
So I did the configuration process and it seemed to work. The CSS wasnt loading which probably is part of the problem here, but something wiki like was shown. As host I entered my ip like "xxx.xxx.xxx.xxx". I also tried"http://xxx.xxx.xxx.xxx". If I do the first one and the setup is done I get redirected to "xxx.xxx.xxx.xxx:3000/xxx.xxx.xxx.xxx". Then it tries to create that site, which is expected. I probably get redirected to that because there is no / in front of "xxx.xxx.xxx.xxx" but anyway, in the end I don't know how I can use wiki.js with an IP only.

I don't have a domain at the moment so I'd like to just run it on the ip of the server. I also tried custom ports and what not.

> title: My Wiki
> host: xxx.xxx.xxx.xxx
> port: 80
> paths:
>   repo: ./repo
>   data: ./data
> uploads:
>   maxImageFileSize: 3
>   maxOtherFileSize: 100
> lang: en
> langRtl: false
> public: true
> auth:
>   defaultReadAccess: false
>   local:
>     enabled: true
>   google:
>     enabled: true
>     clientId: GOOGLE_CLIENT_ID
>     clientSecret: GOOGLE_CLIENT_SECRET
>   microsoft:
>     enabled: true
>     clientId: MS_APP_ID
>     clientSecret: MS_APP_SECRET
>   facebook:
>     enabled: false
>     clientId: FACEBOOK_APP_ID
>     clientSecret: FACEBOOK_APP_SECRET
>   github:
>     enabled: false
>     clientId: GITHUB_CLIENT_ID
>     clientSecret: GITHUB_CLIENT_SECRET
>   slack:
>     enabled: false
>     clientId: SLACK_CLIENT_ID
>     clientSecret: SLACK_CLIENT_SECRET
>   ldap:
>     enabled: false
>     url: 'ldap://serverhost:389'
>     bindDn: cn='root'
>     bindCredentials: BIND_PASSWORD
>     searchBase: 'o=users,o=example.com'
>     searchFilter: '(uid={{username}})'
>     tlsEnabled: false
>     tlsCertPath: 'C:\example\root_ca_cert.crt'
>   azure:
>     enabled: false
>     clientId: APP_ID
>     clientSecret: APP_SECRET_KEY
>     resource: 00000002-0000-0000-c000-000000000000
>     tenant: YOUR_TENANT.onmicrosoft.com
>   oauth2:
>     enabled: false
>     clientId: OAUTH2_CLIENT_ID
>     clientSecret: OAUTH2_CLIENT_SECRET
>     authorizationURL: OAUTH2_AUTH_URL
>     tokenURL: OAUTH2_TOKEN_URL
>   oidc:
>     enabled: false
>     clientId: OPENID_CONNECT_CLIENT_ID
>     clientSecret: OPENID_CONNECT_CLIENT_SECRET
>     issuer: OPENID_CONNECT_ISSUER
>     userInfoUrl: OPENID_CONNECT_USER_INFO_URL
>     authorizationURL: OPENID_CONNECT_AUTHORIZATION_URL
>     tokenURL: OPENID_CONNECT_TOKEN_URL
>     emailClaim: OPENID_CONNECT_EMAIL_CLAIM_PATH
>     usernameClaim: OPENID_CONNECT_USERNAME_CLAIM_PATH
> sessionSecret: d5c3311aff20181717fbbf9abe9d50486d58d31e184a66b174b4fc5238d37ace
> db: 'mongodb://localhost:27017/wiki'
> git:
>   url: 'https://github.com/user/repo'
>   branch: master
>   auth:
>     type: ssh
>     username: marty
>     password: MartyMcFly88
>     privateKey: /etc/wiki/keys/my-key.pem
>     sslVerify: true
>   showUserEmail: true
>   serverEmail: default@foo.com
> features:
>   linebreaks: true
>   mathjax: true
> externalLogging:
>   bugsnag: false
>   loggly: false
>   papertrail: false
>   rollbar: false
>   sentry: false
> theme:
>   primary: indigo
>   alt: blue-grey
>   viewSource: all
>   footer: blue-grey
>   code:
>     dark: true
>     colorize: true

EDIT: There is no other web server running.

### Expected behavior

Somehow get it working using the IP.

**Comment by NGPixel** [comment]
You need to use a valid URI for the `host`.

So for an IP, that would be `http://xxx.xxx.xxx.xxx`

**Comment by padomu** [comment]
> You need to use a valid URI for the `host`.
> 
> So for an IP, that would be `http://xxx.xxx.xxx.xxx`

I tried that, I am going to retry. Exactly what I do:

Set up /var/www with myuser:www-data as owners. (No idea where else, I dont know node.js at all). I am logged in as "myuser":

$ mkdir wiki && cd wiki
$ curl -sSo- https://wiki.js.org/install.sh | bash
$ node wiki configure

Now run the config and user "http://xxx.xxx.xxx.xxx" in the host input and got redirected to "xxx.xxx.xxx.xxx" where I get "Firefox can’t establish a connection to the server at xxx.xxx.xxx.xxx"

Config.yml

> title: My Wiki
> host: 'http://xxx.xxx.xxx.xxx'
> port: 80
> paths:
>   repo: ./repo
>   data: ./data
> uploads:
>   maxImageFileSize: 3
>   maxOtherFileSize: 100
> lang: en
> langRtl: false
> public: true
> auth:
>   defaultReadAccess: false
>   local:
>     enabled: true
>   google:
>     enabled: true
>     clientId: GOOGLE_CLIENT_ID
>     clientSecret: GOOGLE_CLIENT_SECRET
>   microsoft:
>     enabled: true
>     clientId: MS_APP_ID
>     clientSecret: MS_APP_SECRET
>   facebook:
>     enabled: false
>     clientId: FACEBOOK_APP_ID
>     clientSecret: FACEBOOK_APP_SECRET
>   github:
>     enabled: false
>     clientId: GITHUB_CLIENT_ID
>     clientSecret: GITHUB_CLIENT_SECRET
>   slack:
>     enabled: false
>     clientId: SLACK_CLIENT_ID
>     clientSecret: SLACK_CLIENT_SECRET
>   ldap:
>     enabled: false
>     url: 'ldap://serverhost:389'
>     bindDn: cn='root'
>     bindCredentials: BIND_PASSWORD
>     searchBase: 'o=users,o=example.com'
>     searchFilter: '(uid={{username}})'
>     tlsEnabled: false
>     tlsCertPath: 'C:\example\root_ca_cert.crt'
>   azure:
>     enabled: false
>     clientId: APP_ID
>     clientSecret: APP_SECRET_KEY
>     resource: 00000002-0000-0000-c000-000000000000
>     tenant: YOUR_TENANT.onmicrosoft.com
>   oauth2:
>     enabled: false
>     clientId: OAUTH2_CLIENT_ID
>     clientSecret: OAUTH2_CLIENT_SECRET
>     authorizationURL: OAUTH2_AUTH_URL
>     tokenURL: OAUTH2_TOKEN_URL
>   oidc:
>     enabled: false
>     clientId: OPENID_CONNECT_CLIENT_ID
>     clientSecret: OPENID_CONNECT_CLIENT_SECRET
>     issuer: OPENID_CONNECT_ISSUER
>     userInfoUrl: OPENID_CONNECT_USER_INFO_URL
>     authorizationURL: OPENID_CONNECT_AUTHORIZATION_URL
>     tokenURL: OPENID_CONNECT_TOKEN_URL
>     emailClaim: OPENID_CONNECT_EMAIL_CLAIM_PATH
>     usernameClaim: OPENID_CONNECT_USERNAME_CLAIM_PATH
> sessionSecret: bbe5396e1d5a76a0cd51cd3d3f7a202b5670b7731e7d169a14d1fd538caaa95e
> db: 'mongodb://localhost:27017/wiki'
> git:
>   url: 'https://github.com/<user>/<repo>'
>   branch: master
>   auth:
>     type: ssh
>     username: marty
>     password: MartyMcFly88
>     privateKey: /etc/wiki/keys/<mykey>.pem
>     sslVerify: true
>   showUserEmail: true
>   serverEmail: default@foo.com
> features:
>   linebreaks: true
>   mathjax: true
> externalLogging:
>   bugsnag: false
>   loggly: false
>   papertrail: false
>   rollbar: false
>   sentry: false
> theme:
>   primary: indigo
>   alt: blue-grey
>   viewSource: all
>   footer: blue-grey
>   code:
>     dark: true
>     colorize: true


so I don't really know what else to do.

**Comment by winkelement** [comment]
I can recommend [haproxy](http://www.haproxy.org/) for that purpose. 
Check the internet for some example configs like here https://codeburst.io/building-a-nodejs-web-server-with-haproxy-and-lets-encrypt-on-debian-stretch-2fbf16cfba3a

**Comment by padomu** [comment]
I did try authbind, which worked for the configuration manager "authbind node wiki configure 80". But it didn't for "authbind --deep node wiki start". So now that I know the problem was that I tried to run it on port 80 as non-sudo I set it up again on port 3000. Then I run "DEBUG=* node wiki start", it does not work. See:

> $ DEBUG=* node wiki start
>   pm2:paths pm2 home resolved to /home/pascal/.pm2 /home/pascal +0ms
>   pm2:conf Using 2 parallelism (CONCURRENT_ACTIONS) +15ms
>   pm2:client Using RPC file /home/pascal/.pm2/rpc.sock +297ms
>   pm2:client Using PUB file /home/pascal/.pm2/pub.sock +5ms
>   pm2:interface:daemon Getting interaction info +1ms
>   pm2:interface:daemon [PING INTERACTOR] Trying to connect to Interactor daemon +1ms
>   axon:sock connect attempt null:/home/pascal/.pm2/interactor.sock +0ms
> ⠋ Initializing...  axon:sock error ENOENT +256ms
>   axon:sock ignored ENOENT +5ms
>   pm2:client [PING PM2] Trying to connect to server +264ms
>   axon:sock connect attempt null:/home/pascal/.pm2/rpc.sock +2ms
>   axon:sock connect +4ms
>   axon:sock add socket 0 +4ms
>   axon:queue flush 0 messages +1ms
>   axon:sock closing +1ms
>   axon:sock closing 1 connections +0ms
>   pm2:client Daemon alive +11ms
>   axon:sock remove socket 0 +1ms
>   pm2:client Launching RPC client on socket file /home/pascal/.pm2/rpc.sock +1ms
>   axon:sock connect attempt null:/home/pascal/.pm2/rpc.sock +4ms
>   axon:sock connect +0ms
>   axon:sock add socket 0 +0ms
>   axon:queue flush 0 messages +0ms
>   pm2:client RPC Connected to Daemon +3ms
>   pm2:client Calling daemon method pm2:getMonitorData on rpc socket:/home/pascal/.pm2/rpc.sock +9ms
>   pm2:client Calling daemon method pm2:getMonitorData on rpc socket:/home/pascal/.pm2/rpc.sock +10ms
>   pm2:client Calling daemon method pm2:restartProcessId on rpc socket:/home/pascal/.pm2/rpc.sock +7ms
>   pm2:client Calling daemon method pm2:notifyByProcessId on rpc socket:/home/pascal/.pm2/rpc.sock +6ms
> ✔ Wiki.js has started successfully.
>   axon:sock closing +34ms
>   axon:sock closing 1 connections +0ms
>   axon:sock remove socket 0 +1ms
>   pm2:client PM2 RPC cleanly closed +3ms
>   pm2:cli The session lasted 0.05s +0ms
>   axon:sock attempting reconnect +54ms
>   axon:sock closing +0ms
>   axon:sock closing 0 connections +0ms
>   pm2:interface:daemon Interactor Daemon not launched +54ms
>   axon:sock connect attempt null:/home/pascal/.pm2/interactor.sock +1ms
>   axon:sock error ENOENT +0ms
>   axon:sock ignored ENOENT +0ms

and

> host: 'http://xxx.xxx.xxx.xx'
> port: 3000
> paths:
>   repo: ./repo
>   data: ./data

I'm running it on debian.

**Comment by NGPixel** [comment]
You should run Wiki.js on a port above 1024 and use a reverse proxy to listen on the standard HTTP 80/443, such as nginx or haproxy.
