### ISSUE TITLE
V2: Mis-match in attribute type of model/navigation

### ISSUE THREAD

**Issue by garywong-bc** [Requarks/wiki#682]
### Actual behavior
v2.x install on macOSX 10.13 with mysql 5.7 backend fails with `config: should be array` after entering administrator email and password.  Manual dependencies, and not docker.

### Expected behavior
Able to install wiki 2.0 to 'setup complete'.

### Steps to reproduce the behavior
yarn dev

NOTE:
line 208 of server/setup.js is throwing the error
```
await WIKI.models.navigation.query().insert({
```

Since line 208 calls "JSON.stringify()" I suspect that navigation.js model should be:
```
gwong@mbp:views (bugfix/navigatorModel)$ git diff --cached
diff --git a/server/models/navigation.js b/server/models/navigation.js
index a035709..5457bdc 100644
--- a/server/models/navigation.js
+++ b/server/models/navigation.js
@@ -16,7 +16,7 @@ module.exports = class Navigation extends Model {
 
       properties: {
         key: {type: 'string'},
-        config: {type: 'array', items: {type: 'object'}}
+        config: {type: 'string'}
       }
     }
   }
```

**Comment by NGPixel** [comment]
Fixed by fb29dd511bfaa7117cf5e7c550e672690718454b
