### ISSUE TITLE
Error: Cannot find module './build/Release/DTraceProviderBindings

### ISSUE THREAD

**Issue by chrisvel** [Requarks/wiki#691]
### Actual behavior
`node wiki configure` works fine. I can setup wikiJS without any changes other than the defaults. 

When I try to execute `node wiki start` I get a message 
_✔ Wiki.js has started successfully._ 
but it's... fake. The server never starts or it starts and it fails later. Let's see.

The only way I can start the server is by running `node server` where I get 3 similar error messages:
```
2018-11-05T15:56:03.786Z - info: [SERVER] Wiki.js is initializing...
2018-11-05T15:56:03.981Z - info: [SERVER] Checking data directories...
2018-11-05T15:56:03.984Z - info: [SERVER] Data and Repository directories are OK.
2018-11-05T15:56:04.604Z - info: [SERVER] Checking Git repository...
{ Error: Cannot find module './build/Release/DTraceProviderBindings' ....
```
Finally everything works fine. 

EDIT: If I run a `node install` then when finished (with errors), it again starts with `node server` only and I got a new error:

```
Unhandled rejection MongoError: The field 'background' is not valid for an _id index specification. Specification: { v: 2, ns: "wiki.bruteforces", key: { _id: 1 }, name: "_id_1", background: true, unique: false }
    at Function.MongoError.create (/Wiki/node_modules/mongoose/node_modules/mongodb-core/lib/error.js:31:11)
    at /Wiki/node_modules/mongoose/node_modules/mongodb/lib/db.js:1093:80
    at /Wiki/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:469:18
    at process._tickCallback (internal/process/next_tick.js:61:11)
```
System: macos mojave 
Node: 10.13.0

### Expected behavior
Server should start in the background

### Steps to reproduce the behavior
- Install 
- node wiki start

**Comment by joker-danta** [comment]
System: macos mojave
Node: 10.13.0
MongoError: The field 'background' is not valid for an _id index specification. Specification: { v: 2, ns: "wiki.bruteforces", key: { _id: 1 }, name: "_id_1", background: true, unique: false }
    at Function.MongoError.create (/Users/work/Desktop/wiki-1.0.102/node_modules/mongoose/node_modules/mongodb-core/lib/error.js:31:11)
    at /Users/work/Desktop/wiki-1.0.102/node_modules/mongoose/node_modules/mongodb/lib/db.js:1093:80
    at /Users/work/Desktop/wiki-1.0.102/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:469:18
    at process._tickCallback (internal/process/next_tick.js:61:11)

**Comment by NGPixel** [comment]
You need to accept the license agreement in xcode. This is a weird bug specific to macOS.

**Comment by chrisvel** [comment]
> You need to accept the license agreement in xcode. This is a weird bug specific to macOS.

Xcode license accepted, but issue still persists.

**Comment by chrisvel** [comment]
Fallback to node **v10.13.0,** re-run `npm install `and `node wiki start` works fine. 

I get some errors in `node server` but I guess it's not that important right now.
