### ISSUE TITLE
Problem: Create New Document

### ISSUE THREAD

**Issue by dewilldi** [Requarks/wiki#694]
I can't create new document (no homepage). After the first login it looks like this.
![wiki](https://user-images.githubusercontent.com/44968661/48343571-fff97980-e672-11e8-8672-3d5777748759.png)

**Comment by winkelement** [comment]
Have you checked you set the port number explicitly in the `host` parameter? 
https://docs.requarks.io/wiki/install/troubleshooting#weird-display-no-styling-missing-css

**Comment by dewilldi** [comment]
Yes, that's the solution.
Thank you for your prompt reply.
