### ISSUE TITLE
Suggestion: Add sequence & workflow diagram support to Markdown

### ISSUE THREAD

**Issue by dilworm** [Requarks/wiki#700]
is there a plan to support sequence and workflow diagram in editor.
just like   https://www.websequencediagrams.com/

**Comment by winkelement** [comment]
There is a Milestone for the 2.1 release to implement a [Mermaid module](https://github.com/knsv/mermaid).

> 2.1 Milestone
> 
>  Diagrams as code (Mermaid module)

**Comment by dilworm** [comment]
thanks
