### ISSUE TITLE
Vue-devtools working for developers

### ISSUE THREAD

**Issue by debelingIL** [Requarks/wiki#709]
### Actual behavior
Trying to use Vue chrome extension and encounter this message

> Vue.js is detected on this page. Devtools inspection is not available because it's in production mode or explicitly disabled by the author.

### Steps to reproduce the behavior
I simply cloned the repo and ran the configuration script. 
```
yarn run dev
```

I tried changing the configuration in `client/js/app.js`
```
Vue.config.devtools = true
```
How do I turn on the dev tools so I can start debugging vue components I want to add?

**Comment by NGPixel** [comment]
`yarn run dev` will load the full version of vue.js which includes support for the dev tools (as defined [here](https://github.com/Requarks/wiki/blob/master/tools/fuse.js#L55).

Try flushing the cache on your browser? I can't replicate this error when running in the dev mode.
