### ISSUE TITLE
modify file structure from within wiki

### ISSUE THREAD

**Issue by bitworm** [Requarks/wiki#71]
I don't think (?) it's possible to delete or easily modify a folder in the repo from the wiki itself.  Currently I do file structure edits from terminal and wiki page edits from within the wiki.

**Comment by NGPixel** [comment]
You can move files from the Wiki, but it's currently not possible to move a folder. Delete will be added as a root admin feature only.

**Comment by markfox1** [comment]
An honest question: Why would deleting a page or a folder be such a protected feature?

We are looking at using Wiki.js for our in-house knowledge-base. Certainly, we would want to delete pages and folders eventually.

**Comment by NGPixel** [comment]
@markfox1 Documentation being critical, you usually don't want to be able to delete it easily, hence why it will be restricted to admins. However, more permissions will be added in the future, so you'll be able to grant the right to delete to any user.

@bitworm
Subscribe to this feature request for updates:
https://wikijs.canny.io/features/p/image--file-manager-in-account-area

Closing this issue.

**Comment by aphentik** [comment]
Hello,
Is it now possible to delete a folder ? How to delete it if we set the wrong name ?
