### ISSUE TITLE
Docker image instructions are unclear or missing information

### ISSUE THREAD

**Issue by jonathanapp** [Requarks/wiki#710]
### Actual behavior
http://localhost:8080 doesn't render anything.

### Expected behavior
Unknown, never got it working.

### Steps to reproduce the behavior

1.) The instructions link ("View docker specific instructions for WIki.js.") at the bottom of https://hub.docker.com/r/requarks/wiki/ is a 404.

2.) The real Docker instructions at https://docs.requarks.io/wiki/install/docker are vague:

"In the example above, the port 3000 is the port defined in your config.yml, while 8080 is the port that is exposed publicly."

What config.yml file? The local file or the container file? The example .yml file provided has the port set to 80.
Am I to change it to 3000? 
If so, do I also change this line below?

`# INCLUDE CLIENT PORT IF NOT 80/443!`
`host: http://localhost`

I've tried every combination of ports to no avail. Sixty extra seconds of the author's time would likely clear up all of this.

**Comment by lshahar** [comment]
I just install this project now at the first time, it little bit confusing the documents and the example config. 
I found that the docker-compose is running with external port 80 and internal port 3000 ,
The example of the configuration is running under 80, so edit the docker-compose and put port 80:80.

at the config.yml , change the url to the expected url, for example in my case i'm running the docker-compose from virtual machine so i have change to the external ip address of the VM .

Good luck.

**Comment by NGPixel** [comment]
In config.yml:
- `host` should reflect what the client is using to access your wiki. (e.g `http://example.com`)
- `port` should be left to 3000. This is what the Node.js server listens on.

In your docker command, use `-p 80:3000`, which means expose port 80 publicly and use port 3000 internally on the container.

v2 will not have this confusing setup.
