### ISSUE TITLE
Does not check for config.yml file when running in dev mode

### ISSUE THREAD

**Issue by e-e** [Requarks/wiki#714]
### Actual behavior
running `yarn run dev` with no `config.yml` file in place throws an error:
```
 Error: ENOENT: no such file or directory, open '\path\to\wiki\config.yml'
```
I realize that the configuration step is required first, but this case should be caught anyways.

### Expected behavior
Should verify that the file exists and if not gracefully exit with an appropriate message
### Steps to reproduce the behavior
1. `git clone` a new copy of the repo
2. `yarn install`
3. `yarn run dev`
3. After build step, `ENOENT` error should be thrown due to no `config.yml` file

**Comment by NGPixel** [comment]
This scenario is handled gracefully in 2.0. Will close this issue as 1.x is not actively maintained.
