### ISSUE TITLE
Side-by-side Markdown editor

### ISSUE THREAD

**Issue by dandv** [Requarks/wiki#718]
Any thoughts on using a side-by-side Markdown editor with automatic synchronization?

This would make editing posts, especially longer ones, quite a bit more pleasurable.

An excellent open-source implementation of this is @benweet's [StackEdit](https://github.com/benweet/stackedit), which is also easily [embeddable](https://github.com/benweet/stackedit#ecosystem). You can try it live at https://stackedit.io.

![image](https://user-images.githubusercontent.com/33569/49350181-dbd1fc80-f662-11e8-853b-c87933322c38.png)

**Comment by NGPixel** [comment]
This is already in the upcoming v2.

**Comment by dandv** [comment]
Merci, @NGPixel! Happy to see Wiki.js get the green checkmark for Preview [on WikiMatrix](https://www.wikimatrix.org/show/wiki-js), and greetings from a fellow [wiki developer](https://github.com/mojomojo/mojomojo/graphs/contributors) :)
