### ISSUE TITLE
fail to download ELF file

### ISSUE THREAD

**Issue by wellsleep** [Requarks/wiki#724]
### Actual behavior
can't download ELF file after uploading it by 'insert file'
### Expected behavior
it should be able to download
### Steps to reproduce the behavior
1. find a ELF file without suffix
2. upload it using 'Insert File' on edit page
3. the file will be uploaded successfully
4. but when click on the link or copy the URL, you'll not be able to get the file
5. however, if you rename the file to add any suffix (e.g. .zip) after the filename, it will work. so now i'm using this workaround to share ELF.

I think it might be a html rendering issue.

**Comment by wellsleep** [comment]
It seems that the url like `http://192.168.3.76:8080/uploads/exercises/whatamitoyou` was parsed as a HTML page instead of a true binary path for downloading. I think this is the problem.

**Comment by NGPixel** [comment]
extension-less files are not supported. Consider renaming the file with a temporary extension or zipping it instead.
