### ISSUE TITLE
new ldap user problem

### ISSUE THREAD

**Issue by toneti85** [Requarks/wiki#727]
### Actual behavior

When creating a new user no option for ldap is shown. Besides actually I have only enabled local and ldap but all the rest are shown

![image](https://user-images.githubusercontent.com/33319360/49732083-b4d88380-fc7d-11e8-9aa7-13501dad1a4b.png)

### Expected behavior

Be able to create user from ldap

### Steps to reproduce the behavior

Settings -> User - > Create user

**Comment by BurnsCommaLucas** [comment]
@toneti85 I have this same issue, what was your solution?

**Comment by yalh76** [comment]
Maybe because users have to be created before in ldap.

Wiki.js only authenticate existing ldap users.

It’s what application with ldap authentication do.

**Comment by BurnsCommaLucas** [comment]
I'm already pointing the auth.ldap section of config.yml to an existing AD server with active users if that's what you mean. 

Additionally my auth.google.enabled, auth.microsoft.enabled etc are all set to false, yet they still show up in the "Providers" dropdown for new users.

**Comment by yalh76** [comment]
well, not completly sure of the response I gave... Maybe someone who really knows wiki.js would have a better answer

**Comment by toneti85** [comment]
this is what I have finally in config.yml and it is working right now

auth:
  defaultReadAccess: false
  local:
    enabled: true
  ldap:
    enabled: true
    url: 'ldap://dcserver:389'
    bindDn: 'CN=test,OU=test,OU=test,DC=test,DC=com'
    bindCredentials: test
    searchBase: 'DC=test,DC=com'
    searchFilter: '(samaccountname={{username}})'
    tlsEnabled: false
    tlsCertPath: '/etc/ca.cert'

**Comment by BurnsCommaLucas** [comment]
@toneti85 are you able to select the LDAP option when creating a new user? Can you post a picture of your list with the LDAP option showing?

There is some kind of disconnect between the config file and what is actually being displayed for me. The full AUTH section of my config.yml is:
```auth:
  defaultReadAccess: false
  local:
    enabled: true
  google:
    enabled: false
    clientId: GOOGLE_CLIENT_ID
    clientSecret: GOOGLE_CLIENT_SECRET
  microsoft:
    enabled: false
    clientId: MS_APP_ID
    clientSecret: MS_APP_SECRET
  facebook:
    enabled: false
    clientId: FACEBOOK_APP_ID
    clientSecret: FACEBOOK_APP_SECRET
  github:
    enabled: false
    clientId: GITHUB_CLIENT_ID
    clientSecret: GITHUB_CLIENT_SECRET
  slack:
    enabled: false
    clientId: SLACK_CLIENT_ID
    clientSecret: SLACK_CLIENT_SECRET
  ldap:
    enabled: true
    url: 'ldap://160.160.9.113:389'
    bindDn: 'cn=PDX-SA-TomcatAU'
    bindCredentials: <PASSWORD>
    searchBase: 'ou=users,ou=portland,dc=eina,dc=evrazinc,dc=ad'
    searchFilter: '(samaccountName={{username}})'
    tlsEnabled: false
    tlsCertPath: 'C:\example\root_ca_cert.crt'
``` 
but despite everything ldap and local being the only ones set to true, my providers dropdown looks like this:

![2019-04-12 08_40_58-IT Knowledge Wiki](https://user-images.githubusercontent.com/9172192/56049618-c353ac00-5cfe-11e9-80d3-2ea002c545f8.png)

**Comment by toneti85** [comment]
there is no need to create a user for ldap. If the user belongs to the
bindDN login and creation is automatic
