### ISSUE TITLE
How to change mongodb to postgres in wikijs 

### ISSUE THREAD

**Issue by sreddy6** [Requarks/wiki#729]
I tried to change the default mongodb to postgres but while starting the setup it is showing the above error

![image](https://user-images.githubusercontent.com/33825807/50147034-2ac29780-02db-11e9-9ccc-1f5c33998b09.png)
![image](https://user-images.githubusercontent.com/33825807/50147062-3a41e080-02db-11e9-98f9-970d6bf142f1.png)

**Comment by NGPixel** [comment]
And where did you see Postgres being a valid option? You must use mongodb.
