### ISSUE TITLE
wikijs 2.0  Editing Chinese small problems

### ISSUE THREAD

**Issue by lacatc** [Requarks/wiki#733]
Write Chinese in the wikijs 2.0markdown editor, edit it again after saving, Chinese becomes garbled, is this a problem?

![wikijss](https://user-images.githubusercontent.com/37959871/50540231-fa2b0980-0bc8-11e9-8272-cb2df1af1545.png)

**Comment by NGPixel** [comment]
Fixed in 3b285c5074c3cec08ab36ad5570b7a306f5f4eb1
