### ISSUE TITLE
Installation Documentation for Windows Does Not Open

### ISSUE THREAD

**Issue by thousandtyone** [Requarks/wiki#737]
### Actual behavior
https://docs.requarks.io/wiki/install/installation
Click on Windows Tab to show installation directions on Windows. 
Nothing happens.

### Expected behavior
The Tab should open and show you the direction.

### Steps to reproduce the behavior
1. Visit https://docs.requarks.io/wiki/install/installation
2. Click on Windows Tab to see instruction. The tab does not open.

**Comment by markuswochnik** [comment]
Can't reproduce with Firefox 64, everything fine.

Which browser are you using and could you post some console output if there are any error messages?

**Comment by NGPixel** [comment]
I extracted both tabs into their separate sections.
