### ISSUE TITLE
Restore from mongo

### ISSUE THREAD

**Issue by gfelot** [Requarks/wiki#738]
### Actual behavior
Seems that if I just save config.yml I cannot make a fresh install with the same MongoDB instance and let the app restore the article from the DB. So why having a MongoDB running somewhere ? It seems to me it's not hard to implement to check if the instance already have document in a collection and ask if we want to restore or delete everything. Maybe you already implemented if in the v2 since your are switching from the NoSQL world to SQL (and why did you change that ?)

**Comment by NGPixel** [comment]
Content is not stored in the DB. It is reindexed from what's in the Git repository on disk on startup. The DB only contains users and login related data.

**Comment by gfelot** [comment]
So why is the purpose of the `entries` collection in mongo ?

**Comment by NGPixel** [comment]
For caching purposes.

**Comment by gfelot** [comment]
Ok... that's why you are migrating to Redis for the v2 ?
And why not using mongo anymore since the articles are documents ?

**Comment by gfelot** [comment]
Ok thanks.
As someone who had use Mongo a bit I'm not totaly agree with some of your statement.
I understand the extension of other DB and in particular SQL-like DB.
Great work by the way !
