### ISSUE TITLE
Google Suite 'Critical security alert' when setting up mail (Wiki.JS 2.0.0-beta.11)

### ISSUE THREAD

**Issue by sleepadru** [Requarks/wiki#746]
### Actual behavior
Unable to sign-in to Google due to WikiJS not meeting security standards set by Google

### Expected behavior
Able to send mail normally through authentication

### Steps to reproduce the behavior

 - Have a user through Google Suite
 - Setup mail authentication in WikiJS using your Google Suite credentials
 - Save settings and ask users to register accounts

**Comment by sleepadru** [comment]
![Critical security alert](https://maho.ispretty.moe/e7NM3hxY58tFAXTw2ixoWu060VrOvtMh.png)

**Comment by sleepadru** [comment]
Current workaround for this for users running Google Suite (Not recommended):

 - Have your administrator setup 'Less secure apps' through admin.google.com -> Security -> Basic Settings -> Less secure apps
 - Enable 'Less secure apps' through your Google Account settings -> Security -> Less secure app access

This *should* also apply to users not using Google Suite, and you can skip the first step.

**Comment by NGPixel** [comment]
Google authentication is not yet working in the current beta. It will be upgraded to work with the latest requirements.

**Comment by WinEcos** [comment]
> Google authentication is not yet working in the current beta. It will be upgraded to work with the latest requirements.

Microsoft OneDrive is working fine ?

**Comment by NGPixel** [comment]
@WinEcos No. Only the local authentication is working in beta.11

**Comment by NGPixel** [comment]
Google auth available in beta build 115.
