### ISSUE TITLE
Viewing a webpage before wiki.js has finished booting results in a public error

### ISSUE THREAD

**Issue by Concision** [Requarks/wiki#749]
### Actual behavior
On the Wiki.js beta docker build, loading the home page (url: `/`) on the website before it has finished it's boot process results in a an exception being thrown. The resulting webpage shows only a raw stack-trace from express. Here is the log (as well as the exception that is shown publicly): https://pastebin.com/raw/4byNdEu6
Each stack-trace that occurs was me attempting to load a webpage.

### Expected behavior
Expected behavior would probably have refused the connection until ready or provided a wiki.js-esque looking page. Printing the stack-trace seems to only happen when debug mode is enabled (by default, it seems to be in the beta?), but probably should not reveal that information to the end user.

### Steps to reproduce the behavior
Restarting the Wiki.js container on a slow host tends to make the boot process take a significant amount of time (10 seconds); attempting to view a webpage before the boot sequence finishes will result in viewing a stack-trace.

**Comment by NGPixel** [comment]
Fixed errors in the logs (936dfbca545abeddfce1a69dabeb56a26319a105)

As for the the stack trace being displayed on the webpage, this is only when running the app in dev mode (with NODE_ENV set to `development`).
