### ISSUE TITLE
Move page functionality no longer working

### ISSUE THREAD

**Issue by ryanilg** [Requarks/wiki#75]
The "move" button in the move modal no longer works with beta 10. 

When the modal opens, the following error is displayed in the console, which is blocking the functionality that would normally trigger when clicking the move button.

```
TypeError: d.setInputSelection is not a function
```

This ultimately means you can no longer move pages.

**Comment by NGPixel** [comment]
Fixed for Beta 11 (89f1f3343ce640773d5acc331c2565264d58f512)
