### ISSUE TITLE
fs.readdirAsync is not a function

### ISSUE THREAD

**Issue by Arsur** [Requarks/wiki#753]
### Actual behavior
Dev Docker Container does not start. 
```
Loading configuration from /wiki/config.yml... OK
2019-02-05T09:36:37.675Z [MASTER] info: =======================================
2019-02-05T09:36:37.685Z [MASTER] info: = Wiki.js 2.0.0-beta.25 ===============
2019-02-05T09:36:37.686Z [MASTER] info: =======================================
2019-02-05T09:36:41.185Z [MASTER] info: Redis connection: [ OK ]
2019-02-05T09:36:41.216Z [MASTER] error: fs.readdirAsync is not a function

```
### Expected behavior
Should Start
### Steps to reproduce the behavior
i use this docker-compose file
[wikijs-docker-compose.txt](https://github.com/Requarks/wiki/files/2831711/wikijs-docker-compose.txt)

**Comment by NGPixel** [comment]
You're using the dev image which is not supported. Use the `beta` image instead.

**Comment by yalh76** [comment]
Same problem using https://github.com/Requarks/wiki/archive/2.0.0-beta.33.tar.gz and installing manually (Not in docker)

fs.readdirAsync doesn't seem to be a nodejs function

**Comment by mmajko** [comment]
> You're using the dev image which is not supported. Use the `beta` image instead.

Could you elaborate?

**This doesn't seem as invalid issue.**

This is bug introduced in [2.0.0-beta.14](
https://github.com/Requarks/wiki/releases/tag/2.0.0-beta.14) and currently on Node v11.9.0 installation, there really isn't any `fs.readdirAsync` function.

Maybe there could be a relevance with bluebird Promises implementation? (bluebird stuff comes up when I google the function)

**Comment by NGPixel** [comment]
The `dev` tagged docker images should not be used. They are the result of continuous integration and maybe have breaking bugs.

You should either:
- Run the latest beta image, using the `beta` tag.
- Run the dev environment by following the [docker dev instructions](https://docs-beta.requarks.io/dev#using-docker)

The `fs.readdirAsync` is not a built-in function of Node, it's a promisified version. However the package `fs-extra` doesn't append Async to the method names like Bluebird does, which is why it breaks. This bug will be fixed very soon.

**Comment by mmajko** [comment]
@NGPixel The issue is not relevant with Docker containers. Just cloned the repo, configured and started.

**Comment by NGPixel** [comment]
@mmajko This is not my point. If you file an issue and find a bug while running an `dev` image, I'll flag it as invalid and ask you to try again using one of the 2 supported methods I listed above. This is to avoid wasting time investigating issues that might result of the user running an old version of the dev image or simply a build that went wrong and generated a broken image.

Like I said, the bug will be fixed shortly.
