### ISSUE TITLE
2.0 Production Release Notification

### ISSUE THREAD

**Issue by tylerjgarland** [Requarks/wiki#755]
Is there any chance you can use this or something else to send a notification to people interested that 2.0 is ready to go? I check github from time to time, but I just though people might like something that can subscribe to when 2.0 is ready and there's an upgrade path for 1.0 users. 

I am aware of the blog, but I'm just envisioning an email when 2.0 is stable. If your blog can support that, that works too!

**Comment by NGPixel** [comment]
This is a good idea.

👍 above to get notified for now. I'll setup a better system soon.

**Comment by NGPixel** [comment]
This is a good idea.

Use [wiki.requarks.io/newsletter](https://wiki.requarks.io/newsletter) to subscribe!

**Comment by tylerjgarland** [comment]
Thanks @NGPixel !

**Comment by TatriX** [comment]
Any ETA on the release? Is it safe to make a new wiki with 2.0 or should I wait for the final release?

**Comment by tylerjgarland** [comment]
@TatriX , it's still in beta, not production ready yet.

**Comment by fourgates** [comment]
I would also be interested in knowing if there is a rough estimate for when 2.0 will be stable. My company is interested in using Wiki.js for a project and we have a deadline of May 30th, 2019. Would you recommend we wait for 2.0 or use 1.x?

**Comment by tylerjgarland** [comment]
@fourgates , 1.0 works great for production. I use it now. 2.0 once released will have an upgrade path so you don't have to worry.

**Comment by FranklinYu** [comment]
@tylerjgarland How long will 1.x be supported after release of 2.x? It takes time to migrate.

**Comment by tylerjgarland** [comment]
I believe features are no longer being developed for 1.x

**Comment by NGPixel** [comment]
@FranklinYu 1.x is no longer being maintained, with the exception of critical security issues.

**Comment by FranklinYu** [comment]
@NGPixel @tylerjgarland So non-security bug fix (such as Requarks/wiki-v1#36) won’t be fixed? v1.0.117 will be the last release?

**Comment by NGPixel** [comment]
Unless someone else wants to fix it and make a PR, I'm no longer working on 1.x.

**Comment by mitchellknight** [comment]
Best guess for a stable 2.0? Days, weeks, months, years? I have a few projects that I would like to start on 2.0 and I'm just deciding if these projects should wait or if I should find another solution. I've had major issues with 1.x that I hope will be resolved with 2.x.

**Comment by NGPixel** [comment]
@mitchellknight This summer.

**Comment by ewaycorp** [comment]
Hi @NGPixel We are also  planning to use your 2.x version as we are willing to deploy it using mysql. Please let us know how soon you will release this version and we can start using this. Currently we are trying your 2.x version and facing issue on Media Upload section. Is there any patch update for Media Upload fix. Please let us know. We are eagerly waiting for your response. 
Thanks
Joydeep

**Comment by FranklinYu** [comment]
@ewaycorp I think issue for Media Upload should be discussed in a separate issue instead of here.

**Comment by NGPixel** [comment]
@ewaycorp Media Upload is not yet available. Look for future beta releases with that functionality.

**Comment by TautFlorian** [comment]
Are we going to see the Release soon @NGPixel ?
As we can see your going fast with development 👍

**Comment by tylerjgarland** [comment]
@TautFlorian , this summer.

**Comment by BrendanBall** [comment]
I just tried out the latest 2.0 using docker, and it feels like an alpha product, not a beta. I can almost not do anything. Most of the core features are greyed out or broken.

**Comment by NGPixel** [comment]
![130l](https://user-images.githubusercontent.com/15522395/60646141-921fdf00-9e08-11e9-8862-19e0148f5f7c.gif)

**Comment by aiveras** [comment]
We are very excited about the new version, when will it be released, can you estimate it better now that the summer is about to end?

**Comment by tylerjgarland** [comment]
Don't forget summer in the southern hemisphere is in December.

**Comment by FranklinYu** [comment]
At least this is better than releasing a beta-quality version in stable channel. If I have to choose, I prefer to stay in the safe side (or I can just use the beta release).

**Comment by herrlich10** [comment]
Very excited to see the rapid progress and appreciated the hardworking of the maintainer.
Is it possible to release an upgrader from 1.0.x to current beta version, so that users experiencing issues with v1 (which is no longer maintained) can at least try the new beta version (of course, at their own risk) and, if with luck, continue working with wiki.js in their projects. I believe this will also speed up the testing process of the new version.
Many thanks for providing this amazing tools!

**Comment by tylerjgarland** [comment]
Yeah, we've been waiting for someone to create a PR for the upgrade tool
but no takers yet. Know anyone?

**Comment by another-guy** [comment]
I am currently conducting a comparative review of Wiki.js (2.0), Confluence, xwiki, Notion.so, and MediaWiki.

Wiki.js and xWiki are the most appealing systems I'm going to recommend my company to pick from. However, without at least a tentative release date it's going to be very hard to "sell" Wiki.js to the upper management.

Am I looking at the right place for the milestones? If so, the release is already significantly behind (which I am fine with) — correct me if I'm wrong. I mean, we're past _summer_, and no update is made in this issue.

Don't get me wrong. I'm all for "it takes what it takes" to release a stable product or service. Yet, I'm also all for the clear communication of the timeline/date.

P.S. I am well-aware it's open source and people don't get payed for their work here. Thus, please don't interpret my message as a demanding one.
Thank you for all of your work Wiki.js contributors! 👏 👏 👏

**Comment by aam1r** [comment]
The latest update that I saw was on Twitter: https://twitter.com/requarks/status/1183958286581878784

And also this tweet: https://twitter.com/requarks/status/1184444172088102912

No specific dates though, but good progress being made it seems 🙂

**Comment by another-guy** [comment]
> The latest update that I saw was on Twitter: https://twitter.com/requarks/status/1183958286581878784
> 
> And also this tweet: https://twitter.com/requarks/status/1184444172088102912
> 
> No specific dates though, but good progress being made it seems 🙂

Thank you for these references! I think, our organization will need to pass on wiki.js for now. Hopefully, we're going to give it a chance some time later.

**Comment by jonathanrbowman** [comment]
Thanks so much for all the work on this project - excited to see the rc hit the scene!

Is there already a docker image for it, or has that not been posted up yet?

**Comment by aiveras** [comment]
You can download it from the dockerhub: https://hub.docker.com/r/requarks/wiki/tags
The tag is still the beta one, but it's already the new release candidate, as you can see on the creation date.

**Comment by tylucaskelley** [comment]
Is there a place to see a roadmap / remaining backlog of issues? Deployed the latest release candidate just now but noticed a ton of things still grayed out in the admin dashboard and missing features like profiles editing, logging, etc.

Don't interpret this as me being pushy or demanding - I think this is a great effort and once done it'll be the obvious go-to for the organization I work with! Just want to get an idea of where things are at and what should be expected for the initial 2.0 release.

**Comment by NGPixel** [comment]
Final 2.0 release will be available in the coming days. No new features will be introduced until that release. The focus right now is on fixing bugs.

**Comment by Cylix** [comment]
For people who are looking into switching to the v2, just sharing my experience.

We are using wiki v1 for our company. We have about 30 users and 300 pages so that you have an idea of our scale.

I switched to the v2 today. Overall, I'm satisfied with the result though there are a few issues and the transition requires a bit of manual work to fully get it done.

I listed the issues I encountered in https://github.com/Requarks/wiki/issues/1174.

In particular:
- some links may be broken due to some incompatibilities between v1 and v2 if your internal links contain underscores/dots, so may need to manually fix these links
- permissions are not working as expected, there is some glitch somewhere. Our team being small, that's less of a problem for us for now, but this part is not as solid as the v1 for now
- there is some page content size limitation due to the DB config. If you currently have some pages with a looooot of content (I don't know the limit, but it is pretty large), they will not make it all the way through to the v2 and you will have to break them down.

My team will start using the v2 next week, so I'll keep an eye on whether there are more issues or if it is smooth, but so far it looks good on my end besides what's listed above.

**Comment by NGPixel** [comment]
Stable 2.0.1 is now available! A detailed blog post and a newsletter is coming in the next few days.

**Comment by zhinuok** [comment]
Stable 2.0.1 Search function is yet  dose not work? The search function seem still doesn't to work often when I use.

**Comment by FranklinYu** [comment]
@zhinuok Please create a new issue.
