### ISSUE TITLE
Docker-Compose example redirecting to 404

### ISSUE THREAD

**Issue by StephanMeijer** [Requarks/wiki#756]
### Actual behavior

URL for Docker-compose example redirects to 404

### Expected behavior

Link being removed or edited accordinly

### Steps to reproduce the behavior

1. [Open README](https://github.com/Requarks/wiki#docker)
2. Click link _see example_

<img width="685" alt="screenshot 2019-02-11 at 22 24 57" src="https://user-images.githubusercontent.com/3169264/52594502-f63b0a00-2e4b-11e9-85d2-97f6f685793c.png">

**Comment by NGPixel** [comment]
Fixed!
