### ISSUE TITLE
V1.0.102 Crash on Configure

### ISSUE THREAD

**Issue by io-craft** [Requarks/wiki#758]
Can't configure tag v1.0.102, it crashes during `node wiki.js configure`, with "Not Found". No log data.
No changes, default tag.

**Comment by FiyaFly** [comment]
Try using 'node wiki configure' instead of 'node wiki.js configure'. as long as you're in the root wiki directory, this should work.

**Comment by io-craft** [comment]
Worked! But now I have found the Heroku deployment repository as well. So migrating over to that. Thank you! Can close!
