### ISSUE TITLE
No logout button on small screen

### ISSUE THREAD

**Issue by hopfenzapfen** [Requarks/wiki#76]
When opening the wiki on a small screen the sidebar disappears which makes the "logout" button inaccessible. A solution could be to add a "logout" button at the footer of the page on small screens

**Comment by NGPixel** [comment]
Wiki.js isn't optimized for mobile and tablet yet. That's on the todo list. A few things don't work or display right when not on a desktop size screen.

**Comment by hopfenzapfen** [comment]
Yes, I also noticed some other problems on small screens but they didn't affect the functionality directly. But good to hear that it's already on the todo list :)
