### ISSUE TITLE
Missing 2.0.0-beta.42 Release download file

### ISSUE THREAD

**Issue by raphaelriehl** [Requarks/wiki#763]
Hi,
When i want to download latest release with following command:
`https://github.com/Requarks/wiki/releases/download/2.0.0-beta.42/wiki-js.tar.gz`
I have a 404 Not Found Response.

Thanks in advance for resolution.

**Comment by raphaelriehl** [comment]
I'm sorry, i didn't read this:

> Wiki.js 2.0.0 BETA (build.42) is now available! Full details + links coming tomorrow.

I close this issue.

**Comment by NGPixel** [comment]
This is actually a bug. Thanks for reporting :+1:

**Comment by NGPixel** [comment]
Fixed
