### ISSUE TITLE
Can not find module 'lodash'

### ISSUE THREAD

**Issue by WinEcos** [Requarks/wiki#766]
### Actual behavior
[root@localhost abc]# node server
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'lodash'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
### Expected behavior
running wiki server.
### Steps to reproduce the behavior
execute 'node server'

**Comment by WinEcos** [comment]
have some 'loadsh*' folder under 'node_modules' folder ,
see the screenshot as bellow
![2019021912_001](https://user-images.githubusercontent.com/9930176/52990066-5419b400-3441-11e9-94e0-2863e54cf5ea.png)

**Comment by NGPixel** [comment]
You're missing the standalone `lodash` folder. Did you use the package provided [here](https://github.com/Requarks/wiki/releases/download/2.0.0-beta.42/wiki-js.tar.gz)?

This archive includes the lodash folder, so either you're using the wrong archive or the extraction failed to output everything.

**Comment by WinEcos** [comment]
> You're missing the standalone `lodash` folder. Did you use the package provided [here](https://github.com/Requarks/wiki/releases/download/2.0.0-beta.42/wiki-js.tar.gz)?
> 
> This archive includes the lodash folder, so either you're using the wrong archive or the extraction failed to output everything.

i used the release channel with wget url path .

**Comment by NGPixel** [comment]
Try downloading the package again...

**Comment by WinEcos** [comment]
> Try downloading the package again...

Solved ! thanks so much !
