### ISSUE TITLE
Show Version error

### ISSUE THREAD

**Issue by lacatc** [Requarks/wiki#767]
### Actual behavior
![20190219011941](https://user-images.githubusercontent.com/37959871/52991845-68fa4580-3449-11e9-891b-60f201aca72f.png)
Current Version:2.0.0-beta.42
Latest Version:2.0.0-beta.11

### Expected behavior
Current Version:2.0.0-beta.11
Latest Version:2.0.0-beta.42

But now my version is 42, why show 11?

### Steps to reproduce the behavior
install wikijs  Version:2.0.0-beta.42

I really like the wikijs program, I hope that the official version of 2.0 will appear.

**Comment by WinEcos** [comment]
i think that the beta.11 was field info of table in database.

**Comment by NGPixel** [comment]
Fixed.
