### ISSUE TITLE
Testing beta using docker-compose fails

### ISSUE THREAD

**Issue by JFossey** [Requarks/wiki#768]
I am testing out wiki platforms and really like wiki.js, specifically the new version 2. So I am trying to get up and running using docker-compose and it fails with an error.

Any guidance how I can troubleshoot this. I dont really know where to look.

### Actual behavior

```
$ docker-compose up --force-recreate
Recreating core_wiki_db ... done
Recreating core_wiki    ... done
Attaching to containers_wikidb_1, containers_wikijs_1
wikidb_1  | WARNING: no logs are available with the 'none' log driver
wikijs_1  | 2019-02-19 16:10:46,679 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
wikijs_1  | 2019-02-19 16:10:46,687 INFO RPC interface 'supervisor' initialized
wikijs_1  | 2019-02-19 16:10:46,688 CRIT Server 'unix_http_server' running without any HTTP authentication checking
wikijs_1  | 2019-02-19 16:10:46,688 INFO supervisord started with pid 1
wikijs_1  | 2019-02-19 16:10:47,691 INFO spawned: 'wikijs' with pid 7
wikijs_1  | 2019-02-19 16:10:47,860 INFO exited: wikijs (exit status 1; not expected)
wikijs_1  | 2019-02-19 16:10:48,863 INFO spawned: 'wikijs' with pid 13
wikijs_1  | 2019-02-19 16:10:49,035 INFO exited: wikijs (exit status 1; not expected)
wikijs_1  | 2019-02-19 16:10:51,040 INFO spawned: 'wikijs' with pid 19
wikijs_1  | 2019-02-19 16:10:51,210 INFO exited: wikijs (exit status 1; not expected)
wikijs_1  | 2019-02-19 16:10:54,216 INFO spawned: 'wikijs' with pid 25
wikijs_1  | 2019-02-19 16:10:54,385 INFO exited: wikijs (exit status 1; not expected)
wikijs_1  | 2019-02-19 16:10:55,388 INFO gave up: wikijs entered FATAL state, too many start retries too quickly
```

### Expected behavior

To be able to access the wiki setup wizard on port 80

### Steps to reproduce the behavior

Use sample config with only difference being related to using specific mount point.

```
services:
  wikidb:
    volumes:
      - /data/wiki.js/pgsql:/var/lib/postgresql/data

  wikijs:
    volumes:
      - ./wiki.js/config.yml:/wiki/config.yml
```

**Comment by climblinne** [comment]
I tested two version with same results. Once on my linux NAS by putting everything by hand together (following the docker-compose file) and on the other hand with docker for windows and the `docker-compose.yml` file. Both ending with the same error message.

**Comment by JFossey** [comment]
Interesting, To my knowledge the mongoose node module is related to MongoDB and MongoDB has been dropped for SQL databases.

I try to confirm if I am getting the same error.

**Comment by maxidev** [comment]
+1 same error here.

**Comment by NGPixel** [comment]
So it turns out there was an error in the deployment script, which tagged an old v1 image as the beta. This has been resolved.

You'll need to force pull the latest beta image:
```
docker pull requarks/wiki:beta
```

Then follow the instructions from the docs as usual.

Sorry about that!
