### ISSUE TITLE
"Run as service" not working

### ISSUE THREAD

**Issue by worra95** [Requarks/wiki#769]
### Actual behavior
Wiki 2.0.0-beta.42 can't be run as a service!

### Expected behavior
Wiki 2.0.0-beta.42 can be run as a service!

### Steps to reproduce the behavior
Using Ubuntu 18.04 LTS with MariaDB.
Install/configure Wiki JS 
Perform steps as mentioned in the guide. At starting/enabling the service Wiki following errors appear:
![image](https://user-images.githubusercontent.com/47828905/53115965-c2489e80-3547-11e9-8e6c-aec8a828255a.png)
After Permission denied I made the index.js executeable for everyone, now the exec format error appears.
wiki.service looks like this:
![image](https://user-images.githubusercontent.com/47828905/53116087-13f12900-3548-11e9-8b91-879badf147ec.png)

**Comment by NGPixel** [comment]
Instructions have been updated:
https://docs-beta.requarks.io/install#run-as-service
