### ISSUE TITLE
Estonian (et) locale duplicate

### ISSUE THREAD

**Issue by winkelement** [Requarks/wiki#771]
### Actual behavior
Estonian locale shows up twice.
### Expected behavior
Only one locale per language.
### Steps to reproduce the behavior
Run latest beta, go to "Admin" -> "Locale".

<img width="1385" alt="bildschirmfoto 2019-02-23 um 18 41 13" src="https://user-images.githubusercontent.com/3525191/53289807-26af6c00-379b-11e9-9564-6311643a296c.png">

**Comment by NGPixel** [comment]
Removed duplicate.
