### ISSUE TITLE
Admin -> Navigation -> Page - can't select

### ISSUE THREAD

**Issue by keiranmraine** [Requarks/wiki#780]
### Actual behavior

When trying to select a page to link in the navigation administration pane the select page option doesn't appear to do anything (I have 1 page other than Home).

Checked Chrome console for error messages but none found.

### Expected behavior

List of existing pages should be shown

### Steps to reproduce the behavior

1. Start a docker compose based release
    * `2.0.0-beta.43` (although the UI claims `42` is newer??)
    * Configured to link in ssh private key
1. Do basic setup and create homepage
1. Link git repo (ssh) via admin
1. Create FAQ page
1. Attempt to add link to FAQ in navigation side panel:
    * Add -> Link -> Target Type -> Page -> Select Page...

**Comment by NGPixel** [comment]
The page selector is not finished yet. You need to use External Link in the meantime. e.g `/your/page`

**Comment by keiranmraine** [comment]
FYI, this gives `Cannot read property 'set' of undefined` when you try to 'apply' changes.

The new item is saved to the example navigation in that element (navigating away from this panel it is retained), but it isn't propagated to the user display.

Removal gives the same error, but removes it from the admin example navigation pane.

**Comment by zachdoty** [comment]
I am also having the bug "warning Cannot read property 'set' of undefined" when trying to update nav items

**Comment by zippy4** [comment]
> I am also having the bug "warning Cannot read property 'set' of undefined" when trying to update nav items

Same here, I can't update any links with that error.

**Comment by NGPixel** [comment]
Fixed in beta 84

**Comment by stefaanMLB** [comment]
Same problem in 2.0.0-beta.115: Nothing happens after pressing the Select Page... button.

**Comment by NGPixel** [comment]
@stefaanMLB https://github.com/Requarks/wiki/issues/780#issuecomment-471510109
