### ISSUE TITLE
Specify path to git binary

### ISSUE THREAD

**Issue by spomata** [Requarks/wiki#783]
### Actual behavior
I am trying to run Wiki.js on a system with two versions of git installed. The dedicated git v.2 installation for Wiki.js is in a /opt subfolder, but I cannot find a way to specify the path to Wiki.js so I'm stuck in configuration. This is more of a request for help rather than an issue.
### Expected behavior
Specify git binary path in configuration.

### Steps to reproduce the behavior
1. Run "node wiki configure" on CentOS 7 or any Linux environment running git v. 1.8.x

**Comment by NGPixel** [comment]
Added custom git binary path option. Will be available in the next beta.
