### ISSUE TITLE
error: Failed to setup HTTPS server parameters:

### ISSUE THREAD

**Issue by winecos** [Requarks/wiki#784]
### Actual behavior
2019-03-15T08:59:05.100Z [MASTER] info: =======================================
2019-03-15T08:59:05.102Z [MASTER] info: = Wiki.js 2.0.0-beta.42 ===============
2019-03-15T08:59:05.102Z [MASTER] info: =======================================
2019-03-15T08:59:05.990Z [MASTER] info: Loading GraphQL Schema...
2019-03-15T08:59:06.173Z [MASTER] info: GraphQL Schema: [ OK ]
2019-03-15T08:59:06.295Z [MASTER] info: HTTPS Server on port: [ 3030 ]
**2019-03-15T08:59:06.295Z [MASTER] error: Failed to setup HTTPS server parameters:
2019-03-15T08:59:06.295Z [MASTER] error: fs is not defined**
### Expected behavior
use HTTPS to access website 
### Steps to reproduce the behavior

1.enable SSL config in config.yml as bellow:
ssl:
  enabled: true

2. set the PEM files path as bellow:

> 
> key: /home/wwwroot/Ph/to/private.pem 
> cert: /home/wwwroot/Ph/to/public.pem

(reference this link https://stackoverflow.com/questions/991758/how-to-get-pem-file-from-key-and-crt-files  to convert PEM from cert.key and cert.crt file )

saved it .

3.execute "node server" in the root folder.

4. display error message in "Actual behavior" .

what is mistake ?

**Comment by NGPixel** [comment]
Fixed. Will be in the next beta.

**Comment by winecos** [comment]
@NGPixel thanks for the new beta.68 and also cannot  access the website .
if directed the URL address , will opening the index.js file after set up the SSL parameters in the config.yml
can't show the web page

would you like share more details info ?

Thanks

**Comment by winecos** [comment]
BTW,
[t@localhost docs]# pm2 log 0
[TAILING] Tailing last 15 lines for [0] process (change the value with --lines option)
/root/.pm2/logs/server-error.log last 15 lines:
0|server   |     at doListen (net.js:1471:7)
0|server   |     at args.(anonymous function) (/root/.nvm/versions/node/v10.15.0/lib/node_modules/pm2/node_modules/event-loop-inspector/index.js:138:29)
0|server   |     at process._tickCallback (internal/process/next_tick.js:63:19)
**0|server   | Error: listen EADDRINUSE: address already in use ip:3030** (i used 3030 as port)

the port always LISTEN ? if execute the "node server" .
