### ISSUE TITLE
using HTTPS and directly open index.js file 

### ISSUE THREAD

**Issue by winecos** [Requarks/wiki#785]
BTW,
[t@localhost docs]# pm2 log 0
[TAILING] Tailing last 15 lines for [0] process (change the value with --lines option)
/root/.pm2/logs/server-error.log last 15 lines:
0|server   |     at doListen (net.js:1471:7)
0|server   |     at args.(anonymous function) (/root/.nvm/versions/node/v10.15.0/lib/node_modules/pm2/node_modules/event-loop-inspector/index.js:138:29)
0|server   |     at process._tickCallback (internal/process/next_tick.js:63:19)
**0|server   | Error: listen EADDRINUSE: address already in use ip:3030** (i used 3030 as port)

the port always LISTEN ? if execute the "node server" .

_Originally posted by @winecos in https://github.com/Requarks/wiki/issues/784#issuecomment-473725967_

**Comment by NGPixel** [comment]
As stated in the error message, you're trying to use a port that is already taken by another process. Use another port...

**Comment by winecos** [comment]
yes,
if i changed another port , still tell me the same port have already taken by another process.
such as : 3000,93,3034,etc.

i'm not sure what's wrong ...
