### ISSUE TITLE
Any one deploy success wiki.js with the latest version:beta.68 ?

### ISSUE THREAD

**Issue by winecos** [Requarks/wiki#786]
### Actual behavior
open the broswer to access the website as bellow:   
![2019031816_002](https://user-images.githubusercontent.com/9930176/54517666-494d3300-499d-11e9-97cf-2ea697348788.png)
### Expected behavior
open website

### Steps to reproduce the behavior
![2019031816_001](https://user-images.githubusercontent.com/9930176/54517798-a812ac80-499d-11e9-84ba-cae1d1c57b3b.png)

**Comment by winkelement** [comment]
Obviously another service is already running on port 93. Try changing the port for wikijs to something else (e.g. 3000).

**Comment by winecos** [comment]
> Obviously another service is already running on port 93. Try changing the port for wikijs to something else (e.g. 3000).

yep,solved it .
thanks for your help~
