### ISSUE TITLE
Host key verification failed. fatal: Could not read from remote repository

### ISSUE THREAD

**Issue by winecos** [Requarks/wiki#787]
### Actual behavior
After set up git parameters in the "Storage" panel as bellow
![2019031911_001](https://user-images.githubusercontent.com/9930176/54578573-34bf7800-4a3b-11e9-85ca-d665155e8659.png)

### Expected behavior
git storage will be success.

### Steps to reproduce the behavior
1.set up the SSH key on the server machine with github help docs.
2.copied and then set it up the ssh key on the github setting panel .(SSH and GPG keys)
3.filled in the parameters on the Git tab of admin panel .

**Comment by NGPixel** [comment]
https://www.thegeekdiary.com/how-to-fix-the-error-host-key-verification-failed/
