### ISSUE TITLE
v2.0 search doesn't works

### ISSUE THREAD

**Issue by Nicolab** [Requarks/wiki#788]
Hello,

First, very good job. Thanks a lot.

---

Wiki.js 2.x

### Actual behavior

Screen with the error:

![Screen](https://i.imgur.com/X5W2eFz.png)

### Expected behavior

The search result.

### Steps to reproduce the behavior

https://docs-beta.requarks.io/ 

I only searched keywords (example: _module_)

**Comment by NGPixel** [comment]
Fixed. Will be available in the next beta release and it's already live on the docs website.

**Comment by Nicolab** [comment]
Thank you :+1:
