### ISSUE TITLE
 Beta68 search doesn't  work on Postgres version 10

### ISSUE THREAD

**Issue by quickerlab** [Requarks/wiki#789]
### Actual behavior
Node v10.15.0
Postgres V10.3 (Installed by apt of Ubuntu 18.04)
Select Postgres  as search engine 

No results found when searching and console log show:

`2019-03-18T09:26:18.886Z [MASTER] warn: Search Engine Error:
2019-03-18T09:26:18.886Z [MASTER] warn: SELECT word, word <-> $1 AS rank FROM "pagesWords" WHERE similarity(word, $2) > 0.2 ORDER BY rank LIMIT 5; - operator does not exist: text <-> unknown`

Note: When select Baisc DB as serarch engine, it works fine.

### Expected behavior

Postgres  search engine works fine

### Steps to reproduce the behavior
Made some attempts, but still fail.
1. Reindex
2. Create new page
3. Delete database with fresh install.

**Comment by NGPixel** [comment]
Try again using Beta Build 84, it should work now.

**Comment by MichaelPaulukonis** [comment]
I'm having this exact error in 2.0.0-beta.208 with Node 12.4.0, PostGres 11.3 on Mac Mojave

I don't recall seeing the error before today.

**Comment by tionis** [comment]
I can confirm this Issue still exists in Version 2.1.113

**Comment by evarganov** [comment]
I have same problem on v2.3.81, Node 12.16.2, Postgres 12.3
