### ISSUE TITLE
Markdown doesn't work properly?

### ISSUE THREAD

**Issue by efimlosev** [Requarks/wiki#79]
Hello,

If  I add a list item then and **bold text** it will not interpret it will shown as ``` **bold text ** ```

**Comment by NGPixel** [comment]
Can you post an example of the markdown not being generated properly?

**Comment by efimlosev** [comment]
![screenshot from 2017-04-22 05-45-58](https://cloud.githubusercontent.com/assets/11035141/25304578/00206654-271f-11e7-91e3-3d7327df0d10.png)
2. ~~Try to avoid installing 2008  on new supermicro servers. it doesn't have drivers for network adadapters.~~ ** Efim fixed It. Please say him thank you**

**Comment by efimlosev** [comment]
Seems it should work that way ((. Please close the issue

**Comment by NGPixel** [comment]
That's normal Markdown behavior. You must not use any space between `**` and the text to make it bold. Otherwise the parser will ignore it.

**Comment by iecompattest** [comment]
It's very easy to make some words **bold** and other words *italic*

**Comment by iecompattest** [comment]
It's very easy to make some words **bold** and other words *italic*

**Comment by iecompattest** [comment]
It's very easy to make some words**bold** and other words*italic*
