### ISSUE TITLE
GraphQL error: INSERT INTO "pagesVector"

### ISSUE THREAD

**Issue by TheWorms** [Requarks/wiki#791]
When validating creating a page : 

`GraphQL error: INSERT INTO "pagesVector" (path, locale, title, description, tokens) VALUES ( '$1', '$2', '$3', '$4', (setweight(to_tsvector('french', '$5'), 'A') || setweight(to_tsvector('french', '$6'), 'B') || setweight(to_tsvector('french', '$7'), 'C')) ) - bind message supplies 7 parameters, but prepared statement "" requires 0`

**Comment by NGPixel** [comment]
Fixed in Beta 84
