### ISSUE TITLE
Fresh docker install - "Unauthorized You cannot create the page"

### ISSUE THREAD

**Issue by kingfisher77** [Requarks/wiki#792]
### Actual behavior
After fresh install with docker-compose (2.0.0-beta.84) and click on "Create Home Page" results in "Unauthorized You cannot create the page" after login.

### Expected behavior
After login and click on "Create Home Page" should create a Home Page and log me in to wiki.js.
 
### Steps to reproduce the behavior
Fresh install of 2.0.0-beta.84 with provided docker-compose template. Everythin is fresh, volumes, container and images deleted before fresh install.

**Comment by kingfisher77** [comment]
Hi, i cannot find information about what "triaged" means 😄 Do you will have a look at this issue?

**Comment by NGPixel** [comment]
Just tested with the docker-compose example. I was able to login, then create the homepage and save without any issues.
