### ISSUE TITLE
Option to avoid external requests to CDNJS and Google Fonts?

### ISSUE THREAD

**Issue by zmwangx** [Requarks/wiki#793]
I just tried Wiki.js v2 using the requarks/wiki:beta Docker image. Overall it's very pleasant, but I was slightly surprised to see external requests to CDNJS for `material-design-iconic-font` and Google Fonts for Roboto, Varela Round, Source Code Pro and Material Icons. I host my Wiki.js instance on my LAN and would prefer everything to be local for both performance and privacy reasons. AFAIK v1 was entirely local, so this is to some extent a regression for me.

(General arguments against CDNJS and Google Fonts: (1) They aren't universally fast around the world -- Google Fonts isn't even available in China, for instance. (2) Some people are inevitably going to be uncomfortable with Google tracking on a self-hosted service -- yeah I noticed `Referer Policy: same-origin` which is a good start, but still.)

Maybe an entirely self-hosted option could be made available? If there are license issues with Google Fonts (?), some DIY pointers would be much appreciated.

---

### Actual behavior

External requests to CDNJS and Google Fonts.

### Expected behavior

At least an option to self-host all the assets.

### Steps to reproduce the behavior

Self-explanatory.

**Comment by NGPixel** [comment]
Please create a feature request [here](https://requests.requarks.io/wiki) instead.

**Comment by zmwangx** [comment]
Sure, will do. (In my defense, I consider this more of a regression than a feature.)

**Comment by zmwangx** [comment]
Confirmed fix in latest beta, thanks.
