### ISSUE TITLE
Create new user doesnt work

### ISSUE THREAD

**Issue by FlonTaut** [Requarks/wiki#794]
### Actual behavior
Clicking on "Create" doenst do anything
### Expected behavior
New User should be created
### Steps to reproduce the behavior
Try to create a new user on Local with the latest beta

**Comment by winecos** [comment]
feature not ready~

**Comment by NGPixel** [comment]
Feature will be available in an upcoming beta release.

**Comment by IAmAlexMichael** [comment]
This feature is still missing. When will it be finished? Or is there any alternative to do it over the command line?

**Comment by JLopeDeB** [comment]
Hi, is this feature still not ready? I'm surprised I'm able to create new groups and groups rules, but my "New User" button is disabled in latest 2.0 version (updated few minutes ago). BTW, thank you so much for doing this project, your work is awesome.

**Comment by sindhus** [comment]
So what is the work around? Create users directly in Database?

**Comment by felipevsw** [comment]
> Update: I turned to google ol' SQL for directly updating the users table. Its cumbersome but works. I really hope you guys release updates to the beta version soon.

So basically inserting a new line in the users table directly in the database and restarting the service would "create" the user? I could do that for now.
