### ISSUE TITLE
wiki.js and apache on same server

### ISSUE THREAD

**Issue by daurer** [Requarks/wiki#8]
Hi,

I am trying to run wiki.js and apache on the same server, similar to this approach: [http://stackoverflow.com/questions/9831594/apache-and-node-js-on-the-same-server](http://stackoverflow.com/questions/9831594/apache-and-node-js-on-the-same-server)

This kind of works, but now wiki.js is searching for all the assets on the root level (e.g. mydomain.com/css) instead of the level of the wiki (e.g. mydomain.com/mywiki/css)

Do you have a suggestion on how to fix this? Or can you recommend another way of running wiki.js and other apache services on the same server?

Thanks,
Benedikt

**Comment by NGPixel** [comment]
The issue is not running wiki.js and apache on the same server. This is done easily and the link you provided is correct. Wiki.js was simply not designed to run inside a subfolder, at least not right now.

I would suggest using a subdomain (e.g. wiki.yourdomain.com). The rest of the setup is the same (using ProxyPass in Apache).

Is there any reason you must use a subfolder instead of a subdomain/domain?

Nick

**Comment by daurer** [comment]
Thanks for your answer. I currently have no (or very little) control over the DNS entries for the domain, so subdomain is not a solution at the moment. But I realized that I can just use mydomain.com:port for now. Maybe not the most beautiful solution, but it works.  

Benedikt

**Comment by rubberduck203** [comment]
@NGPixel what kind of work would need to happen to enable running in a subdirectory? I would much prefer this over using a subdomain or port. Happy to do the work and submit a PR if you can push me in the right direction here.

**Comment by choicky** [comment]
@rubberduck203 I think you can put wiki.js anywhere you want. If you would like the URL seems like `domain.com/subdirectory` you need a web server such as nginx and a suitable rewrite nginx rule.

**Comment by rubberduck203** [comment]
The app uses a number of absolute paths. This makes proxying something like

    domain.com:3001/

To

    domain.com/wiki

nigh impossible. I've dealt with this kind of thing before, and while it might *appear* to work at first, you'll quickly find broken links. 

The installation wizard explicitly states that Wiki.Js doesn't support this. I'm just trying to get a feel for what kind of work it would take to get it there.

**Comment by NGPixel** [comment]
The next beta will have support for sub-directories.

**Comment by rubberduck203** [comment]
Sweet. I'll be looking forward to this and the history viewer.
If there's anything I can do to help, feel free to ping me @NGPixel

**Comment by yansern** [comment]
Is the next beta out yet?

**Comment by NGPixel** [comment]
The current stable release has basic support for subdirectories.

2.0 will introduces full support.

**Comment by minexew** [comment]
How do you specify the subdirectory?
I've been trying
```
host: "https://my.domain.com/wikijs"
```
But I get immediately redirected to https://my.domain.com/login instead of https://my.domain.com/wikijs/login

This is using the "requarks/wiki:latest" Docker image. I haven't been able to find out which exact version that is.

**Comment by NGPixel** [comment]
You must use a reverse proxy such as nginx to use subdirectories.

**Comment by minexew** [comment]
That's exactly what I'm doing. Nginx on the host OS and wikijs under docker-compose.
The problem is, when I open "https://my.domain.com/wikijs" in the browser, Wikijs seems to redirect to "/login", which ends up being https://my.domain.com/login

**Comment by s00500** [comment]
Hey I have the same problem, this is not really working yet...

**Comment by s00500** [comment]
Otherwise please provide an example for nginx,
(I also see that it is working on a subdir for the docs of the wiki...)
I am using `location ^~ /wiki {` and it is not working, what could be the solution?
What is used in the documentation config?

**Comment by matthiashammerschmidt** [comment]
Hello,
Today I also wasted to much time to get the wiki.js running behind nginx.
it redirects instantly to https://domain.ex/login instead of https://domai.ex/wiki/login.

the problem is, that there is no prefix in the configuration.

But on the other side https://docs.requarks.io/wiki works as i expected?
Can you explain / give any hind why it works for you?

thank you

**Comment by NGPixel** [comment]
There's only partial support for a subfolder installation. (e.g. /login doesn't work)
Full support is coming in 2.0.

The docs website isn't using a subfolder: https://docs.requarks.io/

**Comment by hashguide** [comment]
Hello,
I am trying to setup wiki.js and just wondering what I have to do to get the wiki.js homepage to show on the root domain. Do I need apache to set this up or is node supposed to take care of this?

**Comment by choicky** [comment]
@hashguide 

Please refer to the Doc https://docs.requarks.io/wiki/admin-guide/setup-nginx

In the reverse-proxy example, nginx is proxied to local port 3001.

Therefore, when you install wiki.js, you should config wiki.js listen to `http://localhost:3001 `

**Comment by NGPixel** [comment]
After further consideration, running Wiki.js in a subfolder path will not be supported in 2.0. It adds too much complexity to various components. If a domain / sub-domain is not an option for you, a reverse-proxy could address this issue, but no support will be provided for this.

**Comment by rubberduck203** [comment]
I’m sorry, but I’m confused. The problem is that a reverse proxy won’t work because there are absolute paths instead of relative ones.

**Comment by NGPixel** [comment]
@rubberduck203 There are no absolute paths in 2.0.

**Comment by rubberduck203** [comment]
Ahh. Okay. Perfect!

**Comment by alvinburgos** [comment]
@rubberduck203 how did you make your reverse proxy work? I tried to do it with nginx and used proxy_pass but I also keep getting redirected to `/login` instead of `/<subdir>/login`

**Comment by rickywu** [comment]
not understand how complex to support sub-directory, hope will support this feature

**Comment by garethwarry** [comment]
I'm setting up a wiki for the corporation I work for, and I was really hoping to use this, but this issue is preventing that. I get there are deadlines and priorities for everything, but this is a huge limitation, and it would have been very nice to see this as a higher priority issue.

**Comment by NGPixel** [comment]
@gunnarleffler Subdomains have always been supported...

**Comment by gunnarleffler** [comment]
My apologies, it was late when I wrote that. What I meant to write was: It would be nice to have relative path functionality such that wiki.js can run under a sub directory. e.g. subdomain.corporate.intranet/wiki 

For various reasons in my situation, setting up subdomains like wiki.subdomain.corporate.intranet are less than optimal. I'd like to set up a wiki per project as a sub-domain.

Other wikis do this, however I'd like to start using a wiki built with a more modern tech stack like wiki.js =)

I think there are many others in a similar situation, and might go along way to increasing user share. I'd be willing to pitch in if need be.

**Comment by NGPixel** [comment]
@gunnarleffler You'd still need to setup a reverse-proxy to achieve that. Other wikis are mostly PHP which makes them really easy to run within a subfolder. Node.js apps don't run in folders or within the scope of a webserver. They are standalone apps.

At the moment, there're no plan to allow subfolder installations. They are a real pain to support in Node.js. A dedicated hostname is the way to go.

**Comment by gunnarleffler** [comment]
From my experience it's fairly straightforward to get a node.js app to run under a reverse proxied subfolder. 

Thanks for your time. Cool project BTW.

**Comment by rickywu** [comment]
@NGPixel Can we change webpack config publicPath as publicPath: '/wiki', to archive this?
I just want to try it but got build failed.

**Comment by smacz42** [comment]
Disappointed that this isn't able to be put in a subdirectory.

**Comment by justinacolmena** [comment]
> Disappointed that this isn't able to be put in a subdirectory.

1. It is not difficult at all to rewrite URLs in either Apache or Nginx and pass requests for a specific subdirectory on to Node.js after stripping the subdirectory from the request.
1. The difficult part then is that any **internal literal URLs** generated by the software must be prepended with your chosen subdirectory before being served within the content.
1. It may be possible  --- and I have seen it done, e.g. with http://www.squid-cache.org/ or other web proxy --- to **filter the content served by Node.js** in order to fix the internal literal URLs by inserting or prepending the desired subdirectory.

This same problem, with software-generated literal IPv4 addresses, was a hindrance to web deployment on IPv6. There are solutions, but they may not be as simple as one may wish.

**Comment by vincent-polite** [comment]
Sorry for updating this thread, but is the official stance that subdirectory support is NOT supported and not possible with reverse proxy and that the only supported scenario is a dedicated subdomain?

**Comment by NGPixel** [comment]
@justinacolmena See #1417 for the actual technical reasons.
@vincent-polite Correct. You need a subdomain.

**Comment by Maximvdw** [comment]
For us the main use case for using a subdomain is as the use of the wiki in a corporate network where http://intranet/docs would show documentation about the intranet. "Intranet" being the hostname of the server. (NOTE we have no control on the DNS server at the moment to create subdomains for local machines)

**Comment by Smankusors** [comment]
> For us the main use case for using a subdomain is as the use of the wiki in a corporate network where http://intranet/docs would show documentation about the intranet. "Intranet" being the hostname of the server. (NOTE we have no control on the DNS server at the moment to create subdomains for local machines)

you are in control of your corporate network right? Why not spawning a DNS server inside your network? Also many router supports custom hosts if you use router as a DNS.

**Comment by pathnirvana** [comment]
This is a dealbreaker for us too as we are unable to get subdomain. Tried using wikijs with a subfolder today with ngnix reverse-proxy and was lucky to find this thread so I was able to give up the idea of using wikijs fast without wasting any time.

**Comment by Hokwang** [comment]
Today I deploy wiki.js on kubernetes, I am using ingress-nginx,
and set `path: /wiki` does not work. 

And I can't find solution.

**Comment by rubberduck203** [comment]
@Hokwang thats because it’s unsupported. The maintainer has made it clear he’s either unwilling or unable to fix the code, or willing to accept any help fixing it. 

You can use a subdomain instead of a path, if that’s an option for you.

**Comment by smetis** [comment]
confused that maintainer keep saying uses reverse proxy but I still can't get reverse proxy to work (apache), error pointing to wikijs looking for assets under root not my subfolder. 

spent a good 8hrs today to test out everything including the github storage (the reason I consider wikijs), then to find out subfolder reverse proxy doesnt work, huge bummer!

**Comment by NGPixel** [comment]
@smetis It's clearly indicated in the docs [requirements page](https://docs.requarks.io/install/requirements#domain) that a subfolder installation is not supported.

**Comment by jinrudals** [comment]
i quite understood @NGPixel concer, but for those who want at least try,

```
server {
        listen 9631;
        server_name localhost;
        client_max_body_size 1G;
        #rewrite ^(/.*)$ /wiki/$1 last;
        location ~^/wiki/(.*)$ {
                rewrite ^/wiki/(.*)$ /$1 break;
                proxy_set_header Host $http_host;
                proxy_pass http://localhost:9876;
                proxy_set_header X-Forward-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Real-IP $remote_addr;


                sub_filter_once off;
        }
        location ~^/(?!wiki/)(.*) {
                rewrite ^/(.*) /wiki/$1 break;
                proxy_pass http://localhost:9631;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_set_header Host $host;
        }
}
```

The abov wikijs.conf (nginx) one workied for me to use subfolder.

**Comment by beremour** [comment]
Is there any plans to make subdirectory work ? Very confusing...
