### ISSUE TITLE
Dependencies & connection issue

### ISSUE THREAD

**Issue by telekomancer** [Requarks/wiki#80]
Hi, i tried for ... maybe 16hrs to install the wiki and i found some issues:

- First: dependencies are not clear and i spend HOURS trying to figured out which dependencies should i had. So i must check with several tools until i found it
- Second: The server (node wiki start, after a successful install) say: "Wiki.js has started successfully." but when i tried to access to "wikisite" the famous issue: "Cannot connect", so in linux (the server) i checked for the running instance and listen port, and doesn't running ... so please... error handling ... must be fixed.

So i'll help with dependencies attaching a file with the content (i haven't use node.js before, so it's a clean install.)

[npm_installed.txt](https://github.com/Requarks/wiki/files/949231/npm_installed.txt)

**Comment by NGPixel** [comment]
You should have asked for help on Gitter or Twitter. You would have saved a lot of time...

The only dependencies are Node.js, Git and MongoDB, which are clearly explained in the docs:
https://docs.requarks.io/wiki/prerequisites#software

Everything else is automatically installed and configured for you by running `npm install wiki.js@latest`
which again, is fully explained in the docs:
https://docs.requarks.io/wiki/install

Check in the **/logs** folder for the error log as to why the server doesn't start correctly.

**Comment by NGPixel** [comment]
Do you still need help or I can close this issue?
