### ISSUE TITLE
file "wiki.js" seems to be missing from the released package

### ISSUE THREAD

**Issue by sillykelvin** [Requarks/wiki#800]
### Actual behavior
When decompressed the downloaded `wiki-js.tar.gz`, there is no "wiki.js" file.

### Expected behavior
"wiki.js" should be in the release package.

### Steps to reproduce the behavior
Download from the [releases page](https://github.com/Requarks/wiki/releases), e.g. 2.0.0-beta.84, and then decompress the package.

**Comment by NGPixel** [comment]
This is as designed. Use `node server` to start Wiki.js.

At the moment, the wiki.js file is used solely for dev purposes and is not included in the build package.
