### ISSUE TITLE
Storage: Usage multiple git modules

### ISSUE THREAD

**Issue by climblinne** [Requarks/wiki#806]
As described in https://github.com/Requarks/wiki/issues/565 there are some people, who would like to have the feature to use multiple repositories.

The idea of multiple repositories would deliver one wiki site with one unique search.
An example would be multiple libraries, each in it's own repository (with a 'doc' folder containing markdown files). In the wiki you will see all 
Markdown files together with one search over all.

**Comment by NGPixel** [comment]
See https://requests.requarks.io/wiki/p/multi-git-repo-support
