### ISSUE TITLE
Views using absolute paths

### ISSUE THREAD

**Issue by sertys3** [Requarks/wiki#807]
### Actual behavior
I'm trying to put wiki.js behing my nginx in a sub-folder of it's own. Like that : https://domain.com/wiki/
The reason for that is simple - i want it as part of my already existing app and i don't wanna put it on a separate subdomain and federate an extra certificate.
Unfortunately my proxied requests are getting stonewalled by the hardcoded absolute paths for the static or otherwise assets.
This for instance in the setup page:
`    script(
      type='text/javascript'
      src='/js/runtime.js'
      )
`

### Expected behavior

Maybe someone could elaborate on the reason why this has been implemented in that manner?
I would either prefer to see a config variable for url path or at least have relative paths in the views so this beautiful app is "embeddable" in at least one more way.

**Comment by mdyrhaug** [comment]
Does your config.yml have this as a host:   https://domain.com/wiki/

**Comment by sertys3** [comment]
My config :

port: 3000
host: 'https://domain.com/wiki/'

# ---------------------------------------------------------------------
# Database
# ---------------------------------------------------------------------
# Supported Database Engines:
# - postgres = PostgreSQL 9.5 or later
# - mysql = MySQL 5.7.8
# - mariadb = MariaDB 10.2.7 or later
# - mssql = MS SQL Server 2012 or later
# - sqlite = SQLite 3.9 or later

db:
  type: sqlite
  # PostgreSQL / MySQL / MariaDB / MS SQL Server only:
  #host: localhost
  #port: 5432
  #user: wikijs
  #pass: wikijsrocks
  #db: wiki
  # SQLite only:
  storage: /wiki/wiki.sqlite

trustProxy: true

**Comment by mdyrhaug** [comment]
I do not know if it causes your problem, but the docs say do not add a trailing slash to host config.

"The full hostname of the site, as accessed by the user. Do not add a trailing slash. You must add the port if you expect users to access your wiki via a non-standard port."

**Comment by NGPixel** [comment]
Subfolder installations are not supported. Use a subdomain instead.
