### ISSUE TITLE
No action triggered on the profile's buttons

### ISSUE THREAD

**Issue by Nox-404** [Requarks/wiki#809]
Nothing happend when clicking on any buttons on the user's profile

### Actual behavior

Nothing happend

### Expected behavior

A request to be sent to actually save the changes

### Steps to reproduce the behavior

1. Install wikijs via docker-compose with postgres
2. Create the admin user with the setup page
3. Login
4. Go to your profile
5. Edit your name
6. Try to save

* Wiki.js `2.0.0-beta.91`
* Node `10.15.3`
* Postgres `11.2`

**Comment by NGPixel** [comment]
The user profile page is not done yet.
