### ISSUE TITLE
Make git commit header include identity of user that made a change

### ISSUE THREAD

**Issue by hawken93** [Requarks/wiki#81]
Currently wiki.js seems to commit as the configured account, but I would like it to set committer=wiki system, author=user who made the change.

Currently:
```
git show --pretty=fuller
..
Author:     Wiki ..
..
Commit:     Wiki ..
..
```

I would want:
```
git show --pretty=fuller
..
Author:     User ..
..
Commit:     Wiki ..
..
```

This would help a lot when I work with with the wiki directly on repository, knowing who made which changes. As for setting "committer" to wiki I think it says "the wiki committed this on behalf of the user"

**Comment by oivindoh** [comment]
Subscribing to this. Currently trying out this package in a tiny team of IT-inclined people, but even then it's a bit of a pain to figure out the ever-looming question of _which one of you evolved monkeys did **this**?_

**Comment by NGPixel** [comment]
Upcoming Beta 11 will set the name and email of the user who did the change as the commit signature. I'll add an option to use a static email though, as not everyone wants user emails to be shown in git commits.

**Comment by NGPixel** [comment]
Added for Beta 11 (8f3a6ed9f30e0c5186fa0be6cf70c911ae5b72d0)
