### ISSUE TITLE
Database Initialization Error: password authentication failed for user "wikijs"

### ISSUE THREAD

**Issue by outZoNe** [Requarks/wiki#811]
Hi. 
I'am download `docker-composer.yml` and run it's. But I got an error like the screenshot: http://prntscr.com/ncqd4p. Please help me.
what am I doing wrong?

**Comment by NGPixel** [comment]
This is because the db container isn't ready when wiki.js is attempting to connect. Simply run `docker-compose up` again and it should be ready.

I'll add a script to wait for the port to be available in the next build.
