### ISSUE TITLE
Missing port definition in GIT module

### ISSUE THREAD

**Issue by climblinne** [Requarks/wiki#812]
### Actual behavior
Our git / gerrit server has the following access to the ssh project:
    

`git clone ssh://username@myserver.de.com:29418/mypath/wiki`

Wiki.js (beta 91) uses default port 22, when entering the git path in wiki.js git module.
### Expected behavior
Access git server by using port 29418. 
### Steps to reproduce the behavior
Enter ssh path to git configuration path

**Comment by NGPixel** [comment]
You can set the port in the `Repository URI` field by using an SSH syntax instead of SCP syntax, e.g. `ssh://[user@]host.xz[:port]/path/to/repo.git/`

**Comment by climblinne** [comment]
I got the following error message:

```
ssh: connect to host myserver.de.com port 22: Connection refused
wiki_1  | fatal: Could not read from remote repository.
```

When using `ssh://username@myserver.de.com:29418/mypath/wiki`

**Comment by climblinne** [comment]
Ok, I forgot the ssh:// in front and need some special tuning for ssh inside VMWare (with docker):

ssh config:
```
Host *
   ServerAliveInterval 600
   TCPKeepAlive yes
   IPQoS=throughput
```
