### ISSUE TITLE
Small Usability Change when adding Git Repo

### ISSUE THREAD

**Issue by ndom91** [Requarks/wiki#814]
This is regarding 2.0.0-beta.84

When adding an HTTP (Basic) git repo as a storage backend, the helper text tells the user to enter it in the format: `https://github.com/org/repo.git` 

However, in the backend code, it does the following: 

```js
await this.git.addRemote('origin', `https://${this.config.basicUsername}:${this.config.basicPassword}@${this.config.repoUrl}`) 
```

Which means, it would try to add the following repo and fail: `https://user:password@https://github.com/org/repo.git`

Maybe edit that to make it clear to add the URL **without** the protocol (https).

I just had this issue, fortunately it was easy to figure out, but others may not be so quick to find where the issue lay in the future.

See Screenshot:
![image](https://user-images.githubusercontent.com/7415984/56505110-f6761680-651a-11e9-946e-672506b69611.png)

**Comment by NGPixel** [comment]
Good catch! I’ll revise the text and implement a filter so that it works with both options.

**Comment by NGPixel** [comment]
Fixed. Will be available in the next beta build.
