### ISSUE TITLE
nginx reverse proxy for wiki.js on docker not working when location path is specified

### ISSUE THREAD

**Issue by Prakkie** [Requarks/wiki#816]
### Actual behavior

When nginx is configured with location path like

```
    location /**wiki** {
         proxy_set_header Host $http_host;
         proxy_set_header X-Real-IP $remote_addr;
         proxy_pass http://base11.me.org:8181;
         proxy_http_version 1.1;
         proxy_set_header Upgrade $http_upgrade;
         proxy_set_header Connection "upgrade";
         proxy_next_upstream error timeout http_502 http_503 http_504;
         proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
     }
```
404 error happens. Redirect happens from:
https://host.me.org/wiki
to
https://host.me.org/login

### Expected behavior

redirect to https://host.me.org/wiki/login

### Steps to reproduce the behavior

Set nginx conf as mentioned above.
Set config.yml `host` as `host: https://host.me.org/wiki`

Please let me know if I am missing something..
Thanks..

**Comment by NGPixel** [comment]
You cannot use a subdirectory. Wiki.js must run at the root level.

**Comment by MLukman** [comment]
> You cannot use a subdirectory. Wiki.js must run at the root level.

That's so helpful, not!

At least you should take this as a room for improvement, as a feature request. I was just thinking of installing wiki.js and I'm stuck behind a docker host that does not have a privilege of having subdomains for each spawned container and only have to make do with an nginx reverse proxy. If wiki.js can't support sitting behind it then goodbye.

**Comment by col-panic** [comment]
That is really bad - I have the same scenario here. Don't know how complicated this would be to implement, but it too prevents me from using wikijs.

**Comment by NGPixel** [comment]
I listed the reasons here why this won't be supported:

https://wiki.js.org/feedback/p/support-hosting-wikijs-at-subpath

**Comment by col-panic** [comment]
I reverted to providing the service on an alternative port - which is acceptable in our scenario.
