### ISSUE TITLE
Out-commented sections still shown in sidebar

### ISSUE THREAD

**Issue by hopfenzapfen** [Requarks/wiki#82]
I out-commented a section like this:

```
<!---
# About me

 Find out more  [about me](aboutme) 
--->
```

The section is not shown in the content box of the wiki (as intended) but there is still a sidebar entry to "About me" which is a bit confusing since that section doesn't exist.

**Comment by NGPixel** [comment]
Fixed for Beta 12 (25c105cdc27a8610b05bd4e1b1f9ad161b614151)
