### ISSUE TITLE
LDAP/AD Auth - Beta v2.115 - Successful Login redirects to Login Page

### ISSUE THREAD

**Issue by ndom91** [Requarks/wiki#824]
User seems to authenticate correctly - I get the green toast "Authentication Succesful" or something along those lines.. 

But then it just redirects back to the /login route. 

Is there anywhere else I can check on this? I can't find logs anywhere..

Also, I realize this is a beta and this release just came out a few days ago - but thats why I'm trying to help here!

**EDIT**: In the `Users` section, the user also seems to be correctly added. With the correct displayName, email, assigned to the correct group, etc. Auth provider is `ldap`

**Comment by NGPixel** [comment]
You need to assign the user to a group which has read permissions on the homepage. This weird redirect to login behavior will be fixed in a future beta.

**Comment by ndom91** [comment]
Hmm, I gave the group every right available and its still redirecting to the homepage.

**Comment by ndom91** [comment]
@NGPixel I tried your commit in common.js line, removing line 140 and 141. However, this did not fix the issue.

**Comment by NGPixel** [comment]
You'll want to apply this commit as well then: 0d2aa56b79498994dcfa1c303c40c0910464d867

Make sure the group has...
- `read:pages` enabled under Permissions
- An Allow entry with `read:pages` for `Path Starts With...` empty path under Page Rules

Are you using the docker image or manual installation?

**Comment by ndom91** [comment]
@NGPixel with the allow entry in page rules it finally worked! Thanks!
