### ISSUE TITLE
PostgreSQL authentication failed for user "wikijs"

### ISSUE THREAD

**Issue by dafegit** [Requarks/wiki#825]
### Actual behavior
I have the default settings in config.yml:

[root@CETPMGIP001 wiki]# cat config.yml 

  user: wikijs
  pass: wikijsrocks
  db: wiki
  
I created the user in PostgreSQL DB:

postgres=# CREATE USER wikijs WITH PASSWORD 'wikijsrocks';
CREATE ROLE
postgres=# \du+
                                          List of roles
 Role name |                         Attributes                         | Member of | Description 
-----------+------------------------------------------------------------+-----------+-------------
 postgres  | Superuser, Create role, Create DB, Replication, Bypass RLS | {}        | 
 wikijs    |        
 
 
postgres=# \l
                                  List of databases
   Name    |  Owner   | Encoding |   Collate   |    Ctype    |   Access privileges   
-----------+----------+----------+-------------+-------------+-----------------------
 postgres  | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 template0 | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
           |          |          |             |             | postgres=CTc/postgres
 template1 | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
           |          |          |             |             | postgres=CTc/postgres
 wiki      | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
(4 rows)

But when I try to Run Wiki.js I have the error:

[root@CETPMGIP001 wiki]# node server
Loading configuration from /Datafiles/wiki/config.yml... OK
2019-05-02T15:39:03.318Z [MASTER] info: =======================================
2019-05-02T15:39:03.321Z [MASTER] info: = Wiki.js 2.0.0-beta.84 ===============
2019-05-02T15:39:03.321Z [MASTER] info: =======================================
2019-05-02T15:39:03.583Z [MASTER] error: Database Initialization Error: Ident authentication failed for user "wikijs"

**Comment by NGPixel** [comment]
This is an issue with your PostgreSQL server, not wiki.js, as explained here:
https://confluence.atlassian.com/bitbucketserverkb/fatal-ident-authentication-failed-for-user-unable-to-connect-to-postgresql-779171564.html

**Comment by dafegit** [comment]
Hi,

I changed the METHOD to trust and worked.
```
/var/lib/pgsql/11/data/pg_hba.conf

# TYPE  DATABASE        USER            ADDRESS                 METHOD

# "local" is for Unix domain socket connections only
local   all             all                                     peer
# IPv4 local connections:
host    all             all             127.0.0.1/32            trust
```

Thanks.

David
