### ISSUE TITLE
Not able to access wikijs

### ISSUE THREAD

**Issue by ottipc** [Requarks/wiki#827]
### Actual behavior
Cannot access wikijs over ip and port

### Expected behavior
access wikijs over ip and port

### Steps to reproduce the behavior
just install wikijs

Hi... i am not able to access my wikijs instance.
My config looks like ;

title: XXX
host: 'http://37.61.202.252:3555'
port: 3555
...

Logs are saying 

> 2019-05-05T05:01:05.422Z - info: [SERVER] HTTP/WS server started successfully! [RUNNING]
2019-05-05T05:01:05.508Z - info: [SERVER] Search index flushed and ready.
2019-05-05T05:01:05.508Z - info: [SERVER] Remote Git syncing is disabled. Not recommended!
2019-05-05T05:01:05.517Z - info: [SERVER] Git repository is OK.
2019-05-05T05:01:05.693Z - info: [AGENT] Background Agent is initializing...
2019-05-05T05:01:06.643Z - info: [AGENT] Checking Git repository...
2019-05-05T05:01:07.635Z - info: [AGENT] Remote Git syncing is disabled. Not recommended!
2019-05-05T05:01:07.642Z - info: [AGENT] Git repository is OK.
2019-05-05T05:01:07.661Z - info: [AGENT] Running all jobs...
2019-05-05T05:01:07.879Z - info: [AGENT] All jobs completed successfully! Going to sleep for now.
2019-05-05T05:05:00.912Z - info: [AGENT] Running all jobs...
2019-05-05T05:05:00.919Z - info: [AGENT] All jobs completed successfully! Going to sleep for now.

if i do a wget localhost:3555, everything seems fine and the the right index.html is loaded.
but it is not possible to access over http://37.61.202.252:3555

netstat shows me that the application is running :

> netstat -tupln
`tcp        0      0 0.0.0.0:3555            0.0.0.0:*               LISTEN      6400/node /var/wiki `

if i do an apache proxypass conf :

<Location /pcwikijs>
                ProxyPreserveHost On
                ProxyPass http://localhost:3555
                ProxyPassReverse http://localhost:3555
</Location>

and start the apache, it always return to /login, telling me :

Not Found

The requested URL /login was not found on this server.

but when i do a wget on the localhost:3555 it is working.
in the end i even dont want  the config like this : 'http://37.61.202.252:3555', but like 'localhost:3555', and the config with apache like i do with any other nodejs application i have running on the server.
It is working with about 5 different node applications in  the server, but not with the wikijs!

I read all the other issues, but no one was working for me.
you can even try on the url : http://37.61.202.252:3555/ ... no error in console!

I have a Centos 7, 

`# mongod --version
db version v4.0.9
git version: fc525e2d9b0e4bceff5c2201457e564362909765
OpenSSL version: OpenSSL 1.0.1e-fips 11 Feb 2013
allocator: tcmalloc
modules: none
build environment:
    distmod: rhel70
    distarch: x86_64
    target_arch: x86_64
`

`node --version
v10.15.3`

I read that it shouldnt be a bug, but i think it is one... because the proxy pass is always routing to /login, which is not found but on all other node js applications it is working like i want.

i really like this wiki and would be very sag not able to use it!

 What i am doing wrong???

**Comment by ottipc** [comment]
I found out that this must be a small bug in wiki js!

when i set my proxy pass like :

 <Location /pcwikijs>
                #ProxyPreserveHost On
                ProxyPass http://localhost:3555/login
                ProxyPassReverse http://localhost:3555/login
  </Location>
.. so to that Login path ( you see at the login at the end ) the proxy pass is working ( but without css ), but after login i got again : 

Not Found

The requested URL /login was not found on this server.

In this Ticket afascina gave advice how it works for him, but in my case it is not possible to set the wikijs on port 80! 

So i tried all for hours, but this is definitely not solvable with apache.
there must be this redirect to the /login in the code and this prevent me to solve this problem with the apache.

Maybe there is a way to solve it with complicated Rewrite Rules or anything else, but this shouldnt be the point.
Slowly but surely i get desperated!

**Comment by NGPixel** [comment]
This is not a bug. You cannot run Wiki.js inside a subfolder, it's not supported. Use a subdomain instead.

**Comment by ottipc** [comment]
didnt get it run with apache...
now i usend nginx and a subdomain... now it is running.

Sorry for circumstances.

Greetz Otti
