### ISSUE TITLE
Azure AD w/ 2.0.0-beta.115

### ISSUE THREAD

**Issue by a11smiles** [Requarks/wiki#828]
I've followed the instructions per here: https://docs.requarks.io/wiki/install/installation/authentication#azure-active-directory

1) I'm not able to add users. On the "Users" page, "+ Add New User" is grayed out and disabled.  So, all I have are the two users - the local Admin and a guest account.

2) Under authentication, "Azure Active Directory" is grayed out and has a dash next to it.  It won't allow me to click on it.

System Info:
* Ubuntu 18.04 x64
* CPU Cores: 2
* Total RAM: 7.79 GB
* Node.js: 10.15.3
* Database: MySQL 5.7.24

**Comment by NGPixel** [comment]
You're using the wrong doc. This is for v1.

https://docs-beta.requarks.io

**Comment by a11smiles** [comment]
there's no docs [here](https://docs-beta.requarks.io/authentication) for Azure AD.  Before you are quick to close an issue.  Make sure you've adequately provided an answer.

**Comment by NGPixel** [comment]
I'm closing it because you're reporting a bug about something that isn't done yet. Don't create issues for functionality that isn't completed and greyed out.
