### ISSUE TITLE
error: Could not remove config section 'remote.origin'

### ISSUE THREAD

**Issue by DarkMisha** [Requarks/wiki#83]
### Actual behavior
During github repository configuration on web gui wizard I receive error:

error: Could not remove config section 'remote.origin'

I had no errors during installation.

### Expected behavior
Successfully connect to remote github repository

### Steps to reproduce the behavior

Go through installation process on fresh installed ubuntu 16 latest and start configure on web gui wizard

**Comment by NGPixel** [comment]
Which OS and Git version are you using?

**Comment by choicky** [comment]
I was thrown same error.

Ubuntu 16.04.2 LTS
node v6.10.2
git version 2.7.4

**Comment by NGPixel** [comment]
Fixed for Beta 12 (a7c4f42ef073e8ba303dd8b8c001a9f71399828d)

**Comment by NGPixel** [comment]
Patched Beta 11 as well. Simply re-install again to get the patched version.
