### ISSUE TITLE
Azure AD w/ 2.0.0-beta.115 (docs don't exist)

### ISSUE THREAD

**Issue by a11smiles** [Requarks/wiki#830]
I've followed the instructions per here: https://docs.requarks.io/wiki/install/installation/authentication#azure-active-directory

**Docs don't exist for 2.0.0:**
https://docs-beta.requarks.io/authentication

I'm not able to add users. On the "Users" page, "+ Add New User" is grayed out and disabled. So, all I have are the two users - the local Admin and a guest account.

Under authentication, "Azure Active Directory" is grayed out and has a dash next to it. It won't allow me to click on it.

System Info:

Ubuntu 18.04 x64
CPU Cores: 2
Total RAM: 7.79 GB
Node.js: 10.15.3
Database: MySQL 5.7.24

**Comment by a11smiles** [comment]
ended up changing `isAvailable` to **true** in `wiki/server/modules/authentication/azure/definition.yml`.  This allowed me to set the config via the UI (the `config.yaml` file still isn't processed for the Azure AD info).

Therefore, I activated and re-entered my info into client/secret/resourceId, etc. into the form.  The login page now gives me the option of logging in using Azure.  However, when I click on Azure on the login page, `/login/azure` hands and times out.

**Comment by NGPixel** [comment]
It's disabled because it's not done yet. You can't just set an internal flag to true and expect it to work... It's off for a reason.

**Comment by a11smiles** [comment]
Then why are you publicizing features on your website that aren't implemented?

**Comment by a11smiles** [comment]
Additionally, if it's not "enabled" why didn't you tell me that instead of telling me I was looking at the wrong docs?

**Comment by NGPixel** [comment]
Because this is a beta, which means not all features are implemented yet, but they are all under development. Updating the website every time a new feature becomes available would be too time consuming and the goal is to show what is coming and avoid the frequent "will feature X be implemented?" questions.
