### ISSUE TITLE
Page with path not found half of the times

### ISSUE THREAD

**Issue by Benjafil99** [Requarks/wiki#832]
### Actual behavior
When I go to the url of the page without /en/[pageName], it works great, but when I access de page on .../en/[pageName] half of the time I get a page not founds exeption and if I refresh the page, the page is showed correctly.

I use elasticsearch and the search bar always redirect on /en/ so my pages are not showing.

**without /en/**
![image1](https://user-images.githubusercontent.com/50457382/57467856-570e8e80-7251-11e9-9fcf-3d9852b63df3.PNG)

**With /en/**
![images2](https://user-images.githubusercontent.com/50457382/57467891-67266e00-7251-11e9-8c80-0134cdcbc976.PNG)

**If refresh**
![images3](https://user-images.githubusercontent.com/50457382/57467904-70173f80-7251-11e9-8847-1d1e539a5fe5.PNG)

### Expected behavior
The pages should be showing with or without the path /en/

### Steps to reproduce the behavior

Go to a page with /en/ , indexed with elasticsearch and refresh the page many times.

**Comment by NGPixel** [comment]
Indeed, this is very strange. Thanks for reporting.

**Comment by NGPixel** [comment]
Fixed. Will be in the next beta build.
