### ISSUE TITLE
Knex: Timeout acquiring a connection.

### ISSUE THREAD

**Issue by raikoug** [Requarks/wiki#833]
### Actual behavior
Actually when installing, node server return:
[MASTER] error: Database Initialization Error: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?

### Steps to reproduce the behavior
This is just a fresh machine, debian 9, node v11.10.1, postgres 9.6

Am i doing something wrong?

# pg_isready
/var/run/postgresql:5432 - accepting connections

# pg_isready -h localhost -U wikijs
localhost:5432 - accepting connections

**Comment by raikoug** [comment]
hope this won't waste you time, I tried mariaDB and I've maybe the same issue.
```
2019-05-13T10:45:30.229Z [MASTER] info: =======================================
2019-05-13T10:45:30.233Z [MASTER] info: = Wiki.js 2.0.0-beta.115 ==============
2019-05-13T10:45:30.233Z [MASTER] info: =======================================
2019-05-13T10:45:44.476Z [MASTER] error: Database Initialization Error: connect ETIMEDOUT
```

before wasting you time, I just want to make sure I'm not the problem. 
I installed the DB, clean. Create wikijs user, create wiki DB, granted all privileges to wikijs. 
(this is the same procedure i've followed both for postgres and mariadb)
Am I wrong? 

Hope I didn't waste your time.

**Comment by steven-cuthill-otm** [comment]
Think i have the same issue too now, running this in AWS RDS with Aurora PostgreSQL 10.7

```
2019-07-17T17:18:05.709Z [MASTER] [31merror[39m: Database Initialization Error: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
```

Running : 
Build : Wiki.js 2.0.0-beta.230 
Database : Aurora PostgreSQL 10.7
Docker Image : "requarks/wiki:beta"

**Comment by steven-cuthill-otm** [comment]
i fixed this, was a network config issue, but the error message is not very good ( Knex fault )

**Comment by RickCogley** [comment]
@steven-cuthill-otm I'm getting this error with postgres 11. When you say it was a network issue, what exactly did you do to fix, if you don't mind my asking?

**Comment by NGPixel** [comment]
Closing this issue as it's gone stale. Reopen if you're still having the issue.

**Comment by Frankstar** [comment]
got the same error with 2.3.51 - i dont know whats going on. previous versions worked flawlessly

**Comment by mrkhan** [comment]
**Just to document** 
**Context:** Was trying to install wikijs (2.3.77) as docker container and was unable to connect to Postgres DB which was also running as docker container on the same machine. Error message in Container logs was 
`Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?`

**Solution:** `docker network inspect bridge` 
Got the IP of the Postgres Server and replaced this IP for DB_HOST value and gave internal port of Postgres server (i.e 5432 and not external one, which in my case was 25432)

**Comment by iostrovskiy79** [comment]
>>Solution: docker network inspect bridge

Could you or someone else please explain what is meant exactly? In my installation, DB_HOST is a var set in the wiki docker, and its default value is 'db'. I can't imagine you meant changing this var to the Postgres server's IP. It would be reset as soon as one exit the wiki's shell anyway...
