### ISSUE TITLE
The Top-Left Menu Is Covered by the Menubar in Safari

### ISSUE THREAD

**Issue by eiskalteschatten** [Requarks/wiki#834]
### Actual behavior

The top-left menu is covered by the menubar in Safari 12.1 on macOS 10.14.4 (the latest versions as of now). Because of this, it is difficult to use since it disappears as soon as you move the cursor away from the icon.

![Screenshot 2019-05-11 at 12 46 08](https://user-images.githubusercontent.com/3677693/57568696-3da14a00-73eb-11e9-8261-d94dffd905f8.png)

### Expected behavior

The menu should be above the menubar as in Firefox:

![Screenshot 2019-05-11 at 12 47 52](https://user-images.githubusercontent.com/3677693/57568706-6a556180-73eb-11e9-97e3-2a1f1074cc63.png)

### Steps to reproduce the behavior

1. Open an instance of Wiki.js in Safari.
2. Move the mouse over the icon for the menu in the top-left corner.

**Comment by NGPixel** [comment]
Fixed in e8b738aad95f0c57d38d26645376c9498c2a744f
