### ISSUE TITLE
Possible to resize horizontal screen items ?

### ISSUE THREAD

**Issue by stefaanMLB** [Requarks/wiki#845]
Is it possible to resize the blue menu bar on the left and the grey zone on the right (with bookmark, share and print icons) to get more screen real-estate for the pages themselves ?
PS the bookmark, share and print icons don't seem to do anything when clicked on ?

**Comment by NGPixel** [comment]
No it's not possible at the moment but you can submit a [Feature Request](https://requests.requarks.io/wiki)
