### ISSUE TITLE
wiki.js not saving any changes

### ISSUE THREAD

**Issue by SgtSeppel** [Requarks/wiki#847]
### Actual behavior
After creation of a page in the wiki, changes are not saved anymore. 
I can make changes in the wiki and save them. Saving is confirmed.

If I manually check the repository, I can see that a commit is created, everytime I am trying to save a change to the page. 
However, the diff shows, that only the dates have been change. The content is still only the title of the page.

Creation of new pages seems to work. Files are created. But changes to other pages also do not work.

2.0.0-beta.115 running in a docker container.

### Expected behavior
Changes to pages/actual page content is stored in the local repository.

### Steps to reproduce the behavior
- Create page: File is created in local repo and initially commited.
- Create/change content on newly created page and save: File is commited in Git, but no content besides the intial page header is saved.

**Comment by NGPixel** [comment]
Try again with latest build. Reopen this ticket if you're still having issues.
