### ISSUE TITLE
guest can not get read access in latest beta 11

### ISSUE THREAD

**Issue by choicky** [Requarks/wiki#85]
### Actual behavior
In web config wizard, I've enabled "public". However, guest still does not have read access (to home page).

I checked the `config.yml` and found `public: false` as well as `defaultReadAccess: false` were set, though I've enable "public" during web config wizard.

I change the `false` to `true` and `node wiki restart`, guest still does not have read access.

### Expected behavior
guest have read access

### Steps to reproduce the behavior
newly install beta 11.

beta 11 is installed in https://law.ipinfo.cn

**Comment by NGPixel** [comment]
the `public` option is not correctly set from the configuration wizard. However, once you change it manually and restart Wiki.js, it should work just fine.

Looking at your link, it seems like to be an issue with the Guest user. Can you verify if the Guest user has the necessary read access rights?

**Comment by choicky** [comment]
I've restarted but a non-login person still doesn't have read acess.

Did I missing something? Should I create a user named guest ?

**Comment by NGPixel** [comment]
Under **Account > Users**, you should a user named "Guest" in your list. Let me know if that user exists, and if yes, click on it and list the permissions currently assigned to this user.

**Comment by choicky** [comment]
Wom. I did not know there were additional settings in the "Account".  

I firstly thought all options were configured during web config wizard, like [dokuwiki](https://github.com/splitbrain/dokuwiki).  I further thought `config.yml` had all of the options.

I just checked the `Account->Users` and found the Guest's `Access` was set `deny` rather than `allow`.  Once changed to `allow`, guest has read access now.

I think it would be better in web config wizard to enable or disable `public`, and if `public` is enable, guide the user to change or customize Guest's access right

**Comment by NGPixel** [comment]
The Guest user has read-only access to all the site by default. Not sure why yours what set to deny...

The `public` option states whether or not the Guest user can be used. So if you enable `public` during setup, there's no further configuration to be done.

The only bug at the moment is the `public` option not being set correctly during the setup wizard.

**Comment by choicky** [comment]
I don't know why guest access was set to deny. 

I like wiki.js, thank you for your work.

Currently wiki.js does not have Chinese Translation in UI yet. I can perform the translation if you need.  By the way, about ten years ago I performed the Chinese translation for dokuwiki.  However, in recent years I like markdown therefore I'm thinking to find an alternative one.

**Comment by NGPixel** [comment]
That would be great! I'll add the chinese locale soon and let you know. Thanks.

**Comment by choicky** [comment]
@NGPixel The lingohub invitation was accepted and the Chinese translation is done.
The translation job is much fewer than that of dokuwiki. ^_^

**Comment by NGPixel** [comment]
Only the login page and footer are using localized strings at the moment. I'll try to add all other text resources in the coming days... So a lot more text to translate soon!

**Comment by NGPixel** [comment]
Fixed for Beta 12 (a8b8fc417c10ad44f902da7aca970356b49cd91c)
