### ISSUE TITLE
Impossible to continue installation of 2.0.0-beta.115 because MySQL error

### ISSUE THREAD

**Issue by snakeeyes5135** [Requarks/wiki#850]
## Describe the bug
Impossible to conitnue the installation process because i have a MySQL error

## To Reproduce 
1. extract archive
2. on config.yml add database information
3. node server
4. see mysql error

## Expected behavior
continue installation process
i mean the error is in on the json file : (migration file "2.0.0-beta.1.js" failed)

## Screenshots
https://prnt.sc/nrwpro

## Host Info : 
 - OS: Debian 8.7.1
 - Wiki.js version: 2.0.0-beta.115
 - Database engine: MariaDB 10.0.38
 - NodeJS : 12.3.0

## Additional context
I try with MySQL and MariaDB

**Comment by mjhca** [comment]
This is not a bug.  You need to use a version of MySQL (or MariaDB) that supports the json data type.  

- MySQL >=5.7.8, or
- MariaDB >= 10.2.7

See https://mariadb.com/kb/en/library/json-data-type/

**Comment by NGPixel** [comment]
As @mjhca pointed out, your environment does not meet the requirements:

https://docs-beta.requarks.io/install/requirements#database

Upgrade your database and try again.
