### ISSUE TITLE
Assets from github repository folder

### ISSUE THREAD

**Issue by Jsl-1** [Requarks/wiki#851]
**Question**
Hi, 
We would like to have all assets stored in our git repo instead of database, is it planed ?
Thank you for your support,

**Host Info
OS: [e.g. Windows 10, Docker]
Wiki.js version: [e.g. 2.0.0-beta.148]
Database engine: [e.g. mssql]

**Comment by NGPixel** [comment]
Yes, this feature will be available in a future beta build.
