### ISSUE TITLE
FAQ item for Git as a backing store - will DB be rebuilt from Git content?

### ISSUE THREAD

**Issue by paul-hammant** [Requarks/wiki#852]
https://docs-beta.requarks.io/storage/git

^ I can't find which repo that content is in.  

Git as a backing store: livin' the dream, but what's that about making a RDBMS choice too?  Is that an cache/index? Can it be wiped and then rebuild from Git content?  I'm asking because I'm interested in knowing if it is possible to backup (he he, clone) the Git store and consider that all needed to rebuild the content and navigation of a wiki.js site is in there. Sure, there's some user/password database that's needed too - but thing needing backup in order to claim "no content/history lost chief" is the Git repo, or the Git repo and some other bits and pieces?

**Comment by NGPixel** [comment]
The DB is the primary content source, along with stuff like users, permissions, tags, etc.

Content can be backed up in a git repository and kept in sync. New content created outside of the wiki will automatically be imported as part of the sync.

So can you start brand new wiki and import content only found in a git repository? Yes. Just keep in mind that data that only lives in the DB (users, permissions, etc.) will not be restored.

**Comment by paul-hammant** [comment]
Thanks for the update - when restoring from Git (after recreating users in the RDBMS), are all the historical changes linked to the original user?

I ask because it looks like the commits to the repo being done via a single user ID. If the users making individual wiki/content changes are preserved in some way, it it not as multiple committers as in conventional Git concepts.

**Comment by JLopeDeB** [comment]
> 
> 
> The DB is the primary content source, along with stuff like users, permissions, tags, etc.
> 
> Content can be backed up in a git repository and kept in sync. New content created outside of the wiki will automatically be imported as part of the sync.
> 
> So can you start brand new wiki and import content only found in a git repository? Yes. Just keep in mind that data that only lives in the DB (users, permissions, etc.) will not be restored.

I've tried reinstalling several times using the same repo which holds all my pages but the mongodb is not loading all the entries. I can navigate to all pages by manually entering the url, is jus that I can't see them in the "all" pages navigation bar, just like described in [https://github.com/Requarks/wiki/issues/261](url). Any idea on what could be happening?

**Comment by NGPixel** [comment]
@paul-hammant Git history is not imported at the moment. However I suggest requesting it on  https://requests.requarks.io/wiki

@JLopeDeB This discussions concerns v2 only and is unrelated to your issue. Please create a separate issue for your problem.

**Comment by paul-hammant** [comment]
Thanks @NGPixel - I'll request the feature.
