### ISSUE TITLE
Markdown editor Toolbar has incorrect styling for the Error blockquote

### ISSUE THREAD

**Issue by zhukoven** [Requarks/wiki#854]
Markdown editor Toolbar has several in-built styles for blockquotes. An Error blockqoute has incorrect {.is-error} style instead of {.is-danger}

**To Reproduce**
1. Go to the markdown page editor
2. Hover over the blockqoute button
3. Select the Error blockquote option
4. See error in blockquote styling

**Expected behavior**
Error blockqoute should have red gradient like {.is-danger}

**Screenshots**
![image](https://user-images.githubusercontent.com/27201628/58548345-d28cab80-8211-11e9-8fb1-5577ce30a431.png)

**Comment by NGPixel** [comment]
Fixed for next build
