### ISSUE TITLE
Images not uploading or rendering

### ISSUE THREAD

**Issue by constellationdevs** [Requarks/wiki#856]
**Describe the bug**
When using the markdown editor to insert an image.  The image I upload says it saves.  I select the image and it doesn't render.  I can find the image on disk anywhere.  I have tried restarting wiki but that didn't help.  After restart the images are still available in the asset selector,

**To Reproduce**
1. open any page and edit
2. Select insert asset menu on the right
3. upload a new image
4. select image to insert in the file.

**Expected behavior**
I expect the image to save to disk and render on the page.

**Screenshots**
<img width="1579" alt="Edit Tile Development Guide  Constellation Developer Wiki 2019-05-31 16-59-16" src="https://user-images.githubusercontent.com/50887168/58734494-913cfd00-83c5-11e9-881d-2f9d92a6ad41.png">

**Host Info (please complete the following information):**
 - OS: mac
 - Wiki.js version: 2.0.0-beta.148
 - Database engine: postgres

**Comment by NGPixel** [comment]
Images are not saved to disk. Only a cached binary version is stored temporarily on disk.

Open the Dev Tools in your browser and reload the page. Is there any error in the console or the network tab?

**Comment by Madic-** [comment]
Can confirm this behaviour. Images do not get rendered. Only the markdown text gets displayed. Fresh installation of Beta 148. No erros in browser console and only http 200 status codes in network tab

**Comment by constellationdevs** [comment]
No errors on the network tab.  A computer reboot actually fixed the issue for me for the images I had already loaded.  New image after the reboot still don't work.

**Comment by Madic-** [comment]
I've found the reason for my problem. A picture with a space in a filename does not get displayed. Maybe a space does not get translated to %20?

**Comment by NGPixel** [comment]
You should never use spaces in filenames. A future beta will rewrite them automatically but you should still avoid them in general.

**Comment by constellationdevs** [comment]
Looks like I was having the space issue in my file names as well.
