### ISSUE TITLE
Right Nav menu misformed on Firefox Developer Edition

### ISSUE THREAD

**Issue by conor-byrne** [Requarks/wiki#857]
The right menu bar isn't rendering properly.

Using Firefox Developer Edition 68.0b6

Attempting to view https://docs-beta.requarks.io/ gives this problem as does my own installation  Wiki.js 2.0.0-beta.148

Also the Requirements and Suggest a New Feature icons aren't showing in the left menu. You can see the Requirements icon is missing in the screenshot below.

![wikijs_rightnvabar](https://user-images.githubusercontent.com/15220966/58741782-2ddabb80-8415-11e9-8d82-b397412988cc.png)

**Comment by NGPixel** [comment]
Both issues are not present in the current stable release of Firefox. We don't support any dev or beta releases of Firefox. If the problem occurs in a stable release of Firefox in the future, you may reopen this ticket.

**Comment by conor-byrne** [comment]
Hey @NGPixel, thanks for the quick reply! I'm actually getting the same issue in Firefox 67. I completely understand that there are more pressing matters, is there anything I can do to help pin down the issue?
