### ISSUE TITLE
Cannot edit name or other details on Administrator account

### ISSUE THREAD

**Issue by ravenzachary** [Requarks/wiki#858]
**Describe the bug**
In Wiki.js 2.0.0-beta.148, you cannot edit the name or other details of the Administrator account. Any changes attempted will be discarded.

**To Reproduce**

PATH A:
1. Click the Account  icon in the upper-right corner of the page.
2. Click Profile.
3. Select the Name field and start typing a new name.
4. Click the blue Save button in the User Details section.
5. Navigate away from this page return using Steps 1 & 2. The new name was not saved.

PATH B:
1. Click the Admin (Gear) icon in the upper-right corner of the page.
2. Click Users on the left nav.
3. Click Administrator.
4. Click a pencil icon. No interaction.

**Expected behavior**
The ability to edit the details of the Administrator account, including name, photo, etc.

**Screenshots**
None.

**Host Info (please complete the following information):**
 - OS: Linux - Ubuntu Linux (disco) 19.04 x64
 - Wiki.js version: Wiki.js 2.0.0-beta.148
 - Database engine: postgres 11.3
- Node.js: 10.15.2

**Additional context**
None.

**Comment by NGPixel** [comment]
This feature is not completed yet. It will be available in a future beta.
