### ISSUE TITLE
links-list styling forces carriage return when using parentheticals in text

### ISSUE THREAD

**Issue by ravenzachary** [Requarks/wiki#859]
<img width="654" alt="Screen Shot 2019-06-01 at 8 27 48 AM" src="https://user-images.githubusercontent.com/645975/58750464-b6724f80-8447-11e9-98c1-fce189d2192d.png">

<img width="816" alt="Screen Shot 2019-06-01 at 8 27 17 AM" src="https://user-images.githubusercontent.com/645975/58750465-b6724f80-8447-11e9-99f0-8ac83fc7c421.png">

**Describe the bug**
When adding links-list styling into text entry on a wiki page, the use of this styling type forces carriage returns in the text for that line item when using parentheticals in text. The attached screenshots will better help to explain the behavior.

**To Reproduce**
1. Edit a wiki page.
2. Add a list of items with the link-list styling added at the bottom of the list.
3. Modify one of the items to have a hyperlink using markdown followed by text in parentheticals (see screenshots). A carriage return will be added to your list item with no way to remove it.

**Expected behavior**
Link list items will not have a forced carriage return when using parentheticals in text.

**Screenshots**
See screenshots.

**Host Info (please complete the following information):**
- OS: Linux - Ubuntu Linux (disco) 19.04 x64
- Wiki.js version: Wiki.js 2.0.0-beta.148
- Database engine: postgres 11.3
- Node.js: 10.15.2

**Additional context**
None.

**Comment by ravenzachary** [comment]
Additional screenshot showing displayed behavior:

<img width="816" alt="Screen Shot 2019-06-01 at 8 27 17 AM" src="https://user-images.githubusercontent.com/645975/58750510-57f9a100-8448-11e9-8e5b-1ca1417860e9.png">

**Comment by ravenzachary** [comment]
I was able to recreate this behavior in a list without using the link-list styling, so I think this is a general problem with lists and use of parentheticals in text after a markdown hyperlink.

**Comment by NGPixel** [comment]
In the new beta build 174, you can use the following syntax:

```
- [Privacy Option *(PRIV) - Toggle privacy status for players*](/link/to/page)
{.links-list}
```

Notice the text is now within the link caption is enclosed in asterisks. This will now render on the same line with a separator.

**Comment by ravenzachary** [comment]
Excellent, thank you!

**Comment by MostlyDifferent** [comment]
Had the same problem. I think this may be a problem in the CSS. 

See https://github.com/Requarks/wiki/blob/5d43f6ada1d2492a3d67f967560e2a9824845d51/client/themes/default/scss/app.scss
Line 377.

display:block puts ANY link in a links-list on its own line. UNLESS that link is also "em", which overrides it to an inline-block.

In order to get my links to display properly and not each on a separate line within the text, I have to make them bold. But I'd rather not do that... perhaps it should be display:inline-block instead of display:block? Or will that break something else?

Version 2.3.77

**Comment by unquietwiki** [comment]
@NGPixel , hey there. I helped @MostlyDifferent install his setup, and we were wondering if this situation might have to do with any bugs on https://github.com/pugjs/pug . Please advise: we'd like to help make some fixes if that would be useful. Thanks!

**Comment by unquietwiki** [comment]
@NGPixel @MostlyDifferent I think I ran into something else on this issue, and it's not Pug-related. The VueJS pages in client/components refer to a "keyframes" SASS/SCSS include, which may not be applied correctly. The build is refusing to proceed without resolving it. I'm not a CSS-expert, so maybe someone can help me sort it out? The whole point of this branch I am linking is for a PR to deprecate Webpack for Parcel; my experience with Webpack has been... painful.

https://github.com/unquietwiki/wiki/tree/parcel

**Comment by MostlyDifferent** [comment]
@unquietwiki Perhaps that could be related to some of the general rendering bugs like https://github.com/Requarks/wiki/issues/1389 ... but for this issue in particular, I'm 99% confident that that line of CSS is the problem.
