### ISSUE TITLE
Save operation failed due to long article

### ISSUE THREAD

**Issue by choicky** [Requarks/wiki#86]
### Actual behavior
I write a markdown page of about 66KB. When I click the `save changes` button it says `Save operation failed`.

I delete some of the content to shrink the page size to about 20KB.  This time it's saved successfully.

### Expected behavior
Save successfully.

### Steps to reproduce the behavior

The markdown page of 66KB is in [github](https://raw.githubusercontent.com/choicky/law.ipinfo.cn/master/专利/专利法实施细则-2009-年修改版.md)

**Comment by NGPixel** [comment]
Fixed for Beta 12 (fe029ef67d7ef503891cae3b02d92c31c951b02a)
