### ISSUE TITLE
or Oops, something went wrong... Cannot create this page because it starts with a system reserved path.

### ISSUE THREAD

**Issue by gerroon** [Requarks/wiki#860]
Hi

I installed it using docker-compose and using the vanilla docker-compose.yml provided in https://github.com/Requarks/wiki/blob/master/dev/examples/docker-compose.yml

I get the error in the title when I click on `Images&Files`  > `Create`

I am using Wiki.js 2.0.0-beta.148 Docker Compose on Debian Buster.

**Comment by NGPixel** [comment]
The Images & Files feature is not available yet. It's coming in a future release.

**Comment by gerroon** [comment]
I see, thanks. It was not clear
