### ISSUE TITLE
Why do I see those texts instead of the icons on my browser ?

### ISSUE THREAD

**Issue by datatierce** [Requarks/wiki#863]
**Question**
I had the same kind of issues with my aBrowser on Trisquel (1 years ago) and now on my Firefox-ESR 60.7 on Devuan ASCII.

**Host Info (please complete the following information):**
OS: Devuan ASCII
Wiki.js version: https://docs-beta.requarks.io/

![image](https://user-images.githubusercontent.com/3410294/58783439-308a0c00-85e1-11e9-9a17-2197b11960cd.png)

Any idea ? Exlpanation ?

Thanks !

**Comment by NGPixel** [comment]
Are you running Wiki.js behind a reverse-proxy? You need to make sure .woff / .woff2 files are not blocked. Look into your browser dev tools (F11), network tab, to see if the requests made to `/fonts/MaterialIcons-Regular.woff` or `/fonts/MaterialIcons-Regular.woff2` are blocked.

**Comment by datatierce** [comment]
Hello, thanks for your suggestions.

I use the demo website (https://docs-beta.requarks.io/), so I suppose it's not behind a reverse-proxy.

Here is a capture fo the network tab and the .woff fonts are not blocked.

![image](https://user-images.githubusercontent.com/3410294/58869744-263e3f80-86bf-11e9-8c99-4a15566ab900.png)

**Comment by datatierce** [comment]
Haha… found the culprit; my browser.display:use_document_fonts was set to 0 in about:config

I set it back to 1 and now it renders .woff and .woff2 properly.

Regards
