### ISSUE TITLE
Not able to create Navigation Objekt from Type Page.

### ISSUE THREAD

**Issue by J-Ha** [Requarks/wiki#864]
**Describe the bug**
Not able to create Navigation Objekt from Type Page, the Select Menu for a page does not open.

**To Reproduce**
1. Go to '/a/navigation'
2. Click on 'add -> Link -> Target Type: Page -> Select Page...'
3. Select Menu does not open. 

**Expected behavior**
able to select a page

**Host Info (please complete the following information):**
 - OS: [e.g. Arch | Docker]
 - Wiki.js version: [e.g. 2.0.0-beta.115|2.0.0-beta.115|2.0.0-beta.174]
 - Database engine: [e.g. postgres 9.7]

Reproducible with docker or local installation.

**Comment by NGPixel** [comment]
This feature is not yet available. You must use the `External Link` type in the meantime. You can still use internal pages (e.g. `/link/to/page`).
