### ISSUE TITLE
ElasticSearch API Version

### ISSUE THREAD

**Issue by Benjafil99** [Requarks/wiki#865]
**Describe the bug**

In the Wikijs config, the maximum elasticsearch version number is  6.6, but the server doesn't support this version anymore.

**Expected behavior**
The wikijs comboBox should show only the versions availible.

**Screenshots**

![image](https://user-images.githubusercontent.com/50457382/58803971-b2c50100-85de-11e9-9010-2f7eea655ea5.png)

![image](https://user-images.githubusercontent.com/50457382/58803989-bc4e6900-85de-11e9-8de5-f34046ba8036.png)

**Host Info (please complete the following information):**
Ubuntu 18.04, Docker
 - Wiki.js version: [e.g. 2.0.0-beta.174]
 - Database engine: mysql 8
- ElasticSearch 6.6

**Comment by NGPixel** [comment]
elasticsearch just released a new, completely rewritten version of the client library. The implementation will need to be adapted to this new library which may take some time.

**Comment by NGPixel** [comment]
Fixed by b34aa5bab4eecf26bbec84f5b638c6fe71fcc536

Will be available in the next beta build.
