### ISSUE TITLE
Unhandled 'error' event during installation

### ISSUE THREAD

**Issue by DarkMisha** [Requarks/wiki#87]
### Actual behavior
during installation "npm install wiki.js@latest"
i receive error:
> wiki.js@1.0.0-beta.11.1 postinstall /opt/wiki2/node_modules/wiki.js
> node install.js

 __    __ _ _    _    _     
/ / /\ \ (_) | _(_)  (_)___ 
\ \/  \/ / | |/ / |  | / __| 
 \  /\  /| |   <| |_ | \__ \ 
  \/  \/ |_|_|\_\_(_)/ |___/ 
                   |__/

⢀⠀ Initializing...events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: connect EACCES /home/someuser/.pm2/rpc.sock
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
....

### Steps to reproduce the behavior
go trough installation tutorial.

node --version
v6.10.2

mongod --version
db version v3.4.4

git --version
git version 2.7.4

OS: ubuntu 16 latest

**Comment by NGPixel** [comment]
Seems like a permissions issue. Make sure the user you are installing Wiki.js with has the necessary read/write permissions to /home/someuser/.pm2

**Comment by DarkMisha** [comment]
im installing as "sudo -s" 
and also use command
"# sudo npm install wiki.js@latest"

and it does not work,

I have changed privileges for ./pm2 and it start to work
" # sudo chmod 777 /home/someuser/.pm2

Thanks,
installed successfully

**Comment by NGPixel** [comment]
You could also simply change the owner of the the wiki.js installation folder and set the permissions to 755. Then install without using sudo.
