### ISSUE TITLE
Clicking on links while editing a page discards any changes

### ISSUE THREAD

**Issue by eordano** [Requarks/wiki#871]
**Description**
I was editing a page and clicked on a link in the preview. The changes were lost.

1. Make a change on a page (using the markdown editor) 
2. Click on a link
3. Go back
4. Say sayonara to the changes

**Expected behavior**
I would expect a message triggered by the `window.onbeforeunload` event, prompting the user to save the changes.

**Host Info:**
I'm using the 2.0.0-beta.180 build.

**Additional info**
Wiki.js v2 is beautiful, great job!

**Comment by NGPixel** [comment]
Was fixed in 2.0
