### ISSUE TITLE
Fountain markup support

### ISSUE THREAD

**Issue by douglaslassance** [Requarks/wiki#872]
More of a question than an issue. I would like to implement a [Fountain](https://fountain.io/) editor and renderer.

I know that using a wiki for script-writing might not be the first idea that comes to mind, that being said, I think it could be a pretty powerful tool for writers.

I just wanted to know if you thought that could be interesting to have this in wiki.js and maybe get some hints on how editors are supposed to be added.

Let me know.
Thanks.

**Comment by NGPixel** [comment]
I'm not familiar with Fountain but you're more than welcome to write an editor / renderer for it. Wiki.js was built to have any number of editor and rendering pipeline steps.

At the moment, there's no way to "dynamically" add new editors. They must be added directly into the main source code and compiled as part of the project.

I suggest looking into the "editor-code" editor, which is the most basic one and start a new one based on it:
https://github.com/Requarks/wiki/blob/master/client/components/editor/editor-code.vue

The editor choice must be added to the editor selector modal:
https://github.com/Requarks/wiki/blob/master/client/components/editor/editor-modal-editorselect.vue

Finally, a reference must be added to the core editor component:
https://github.com/Requarks/wiki/blob/eb66ae608843501ae41b6189237171976641ce6b/client/components/editor.vue#L64-L66

Feel free to go on [Slack](https://wiki.requarks.io/slack) if you have any questions.
