### ISSUE TITLE
DevQ: should i need to solve it ?

### ISSUE THREAD

**Issue by winecos** [Requarks/wiki#873]
**Question**
Describe in details what you are trying to achieve and where do you need guidance.
![201906111752](https://user-images.githubusercontent.com/9930176/59262704-53b45b80-8c72-11e9-8584-2dcd0ed1aa07.png)

**Host Info (please complete the following information):**
OS: [e.g. Ubuntu 18.04, Docker]
CentOS 7.2
Wiki.js version: [e.g. 2.0.0-beta.115]
2.0.0-beta.180
Database engine: [e.g. postgres 9.7, mysql 5.7]
postgres

**Questions:**
1. i used the docker command " make docker-dev-rebuild" 
2. the terminal told me some error message as you saw above  
3. i'm not sure that was it correct after docker command ? if not ,how to solve it ? 
4. **if it's rebuild successfully and then where can i get the files(client folder) ??**

Thanks a lot

**Comment by NGPixel** [comment]
You can ignore these messages. They are simply warnings that will disappear in the future.

I'm not sure I understand your last question. Which files are you looking for?

**Comment by winecos** [comment]
> You can ignore these messages. They are simply warnings that will disappear in the future.
> 
> I'm not sure I understand your last question. Which files are you looking for?

the final build image package files after with build command .
