### ISSUE TITLE
Fail to import some long named documents from git

### ISSUE THREAD

**Issue by cristichiru** [Requarks/wiki#876]
**Describe the bug**
Some long name documents cannot be imported into the database from git

**To Reproduce**
1. Create a long document in the git repo, e.g `ui/7-tips-and-tricks-from-the-dashboard-experts.md`
2. Import the documents

**Expected behavior**
Document to be imported in wikijs database

**Log**
```
2019-06-12T16:36:18.235Z [MASTER] warn: (STORAGE/GIT) Failed to open ui/7-tips-and-tricks-from-the-dashboard-experts.md
2019-06-12T16:36:18.236Z [MASTER] warn: insert into "pages" ("authorId", "content", "contentType", "createdAt", "creatorId", "description", "editorKey", "hash", "isPrivate", "isPublished", "localeCode", "path", "publishEndDate", "publishStartDate", "title", "toc", "updatedAt") values ($1, $2, $3, $4, $5, $6
, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17) returning "id" - value too long for type character varying(2)
```

**Host Info (please complete the following information):**
 - OS: Docker
 - Wiki.js version: 2.0.0-beta.180
 - Database engine: postgres 9.6

**Comment by NGPixel** [comment]
Paths can be up to 255 chars, so that's unlikely to be the issue. The folder name is most likely the issue. 2 letter folders are reserved for locales and cannot be used for actual content. Try renaming `ui` to something else (3 chars or more).

**Comment by cristichiru** [comment]
You were right, renaming the 2 letter dir, resulted in successful importing the child documents.
We currently wanted to have a full gitlab wiki handled in wikijs and it works quite well.

Some minor things, not related:
1. Syncing with the git repo does not seem to remove old directories. Following your suggestion:
- git cloned the wiki repo
- renamed `ui` dir to `user-interface`
- git add, commit, push to gitlab
- from wikijs -> storage -> git,  Foce sync,, "pull from target".
Now I have both a directory `ui` and a `user-interface` with the same files inside, `ui` being untracked.
2. All files seem to be duplicated with .mdE extension, all untracked by git.
3. Most of files have a "description: " field in the header. A forced "import everything" will not accept them, saying `2019-06-14T13:30:15.758Z [MASTER] warn: (STORAGE/GIT) Failed to open microservices/microservices---events---containers.md
2019-06-14T13:30:15.758Z [MASTER] warn: description: should be string`. Quick fix, add filename to this descrption using find/sed.

**Comment by NGPixel** [comment]
Should be fixed in latest build.
