### ISSUE TITLE
Chrome : Anchor links doesn't move to the correct header/title

### ISSUE THREAD

**Issue by Vagrant39** [Requarks/wiki#879]
Hi, 
using chrome, from another page, links with anchor don't move ton the correct header/title

**To Reproduce**
1. With Chrome, go to https://docs-beta.requarks.io/guide/pages#naming-restrictions

**Expected behavior**
Move to the correct header/title

**Additional context**
Works fine with Firefox

**Comment by NGPixel** [comment]
Fixed by 379d58d06989b49528620de8def967c4f34097a6
