### ISSUE TITLE
yarn dev: error Command failed with exit code 137

### ISSUE THREAD

**Issue by zhuangbiaowei** [Requarks/wiki#881]
**Describe the bug**
~/wiki# yarn run dev

......

  ✔ Compile modules
  ✔ Build modules
  ✔ Optimize modules
  ❯ Emit files

Killed
error Command failed with exit code 137.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Host Info (please complete the following information):**
 - OS: Ubuntu 18.04
 - Wiki.js version: 2.0.0-beta.180
 - Database engine: sqlite

**Comment by NGPixel** [comment]
I'll need some more details than that to help you. Post the full log.

Which version of Node.js are you using?

**Comment by zhuangbiaowei** [comment]
yarn start
yarn run v1.16.0
$ node server
Loading configuration from /root/wiki/config.yml... OK
2019-06-17T15:25:21.961Z [MASTER] info: =======================================
2019-06-17T15:25:21.963Z [MASTER] info: = Wiki.js 2.0.0-beta ==================
2019-06-17T15:25:21.963Z [MASTER] info: =======================================
2019-06-17T15:25:21.963Z [MASTER] info: Initializing...
2019-06-17T15:25:23.158Z [MASTER] warn: DB Configuration is empty or incomplete. Switching to Setup mode...
2019-06-17T15:25:23.159Z [MASTER] info: Starting setup wizard...
2019-06-17T15:25:23.687Z [MASTER] error: ENOENT: no such file or directory, stat '/root/wiki/assets/favicon.ico'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by zhuangbiaowei** [comment]
~/# yarn build

    → [100%] 2797 of 2801 modules :: node_modules/@material-ui/core/List/List.js ~ external
    → [100%] 2798 of 2801 modules :: node_modules/@material-ui/core/Modal/Modal.js ~ external
    → [100%] 2799 of 2801 modules :: node_modules/grapesjs/dist/grapes.js ~ external
    → [100%] 2799 of 2802 modules :: node_modules/@material-ui/core/Modal/isOverflowing.js ~ external
    → [100%] 2799 of 2803 modules :: node_modules/@material-ui/core/Modal/manageAriaHidden.js ~ external
Killed
error Command failed with exit code 137.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by YannickBochatay** [comment]
So was the problem resolved ?

**Comment by zjffun** [comment]
Out of memory may cause this
