### ISSUE TITLE
Upgrade from 1.0 to 2.0 beta

### ISSUE THREAD

**Issue by AchimHentschel** [Requarks/wiki#885]
**Question**
We are running wiki.js version 1 in a docker container with remote git repository to store its content. So far so good.

I just tried to upgrade to 2.0.0 beta 180. A new installation via docker was quite easy. Since I did not care about any user of other configuration I tried and was able to attach a clone of the productive git repository to the new installation. But that way no existing pages were shown in the new installation.

Then I tried to follow the "Upgrade" way you described on https://docs.requarks.io/wiki/install/upgrade. I created a fresh install via docker and then changed to the old config.yml. During startup I then see the following log:
2019-06-18T12:46:50.918Z [MASTER] info: =======================================
2019-06-18T12:46:50.922Z [MASTER] info: = Wiki.js 2.0.0-beta.180 ==============
2019-06-18T12:46:50.922Z [MASTER] info: =======================================
2019-06-18T12:46:50.922Z [MASTER] info: Initializing...
2019-06-18T12:46:51.228Z [MASTER] error: Invalid DB Type

Since version 2.0 does not support MongoDB anymore this error message is quite obvious. not obvious is, how I should then be able to do a migration to 2.0 AND a new DBMS.

**Host Info (please complete the following information):**
OS: [e.g. Debian 3.16.51-3+deb8u1, Docker]
Wiki.js version: [e.g. 2.0.0-beta.180]
Database engine: [e.g. mssql 2012]

**Comment by NGPixel** [comment]
You cannot upgrade to 2.0.0 from 1.x yet. The upgrade page you mentioned is specifically for upgrades from earlier 2.x betas.

Right now if you want to use 2.0 and don't care about keeping users, you need to make sure your content is sync with a remote git repo. Then install a brand new 2.0.0 beta installation (using the install instructions, not upgrade!). Once your wiki is up and running, simply enable the git module in the admin area and do an Import All.

**Comment by AchimHentschel** [comment]
Hi @NGPixel,

that was a really quick response. Solved my migration problem so far.

I get some warnings "String or binary data would be truncated." during the import process which are most probably SQL Server related messages. Not sure if these result in broken pages though.

After the import process (triggered via option on the bottom of the Storage / Git configuration finished I see the message "Network Error: Unexpected token < in JSON at position 0". I guess this is a UTF-8 with/without BOM issue?

Are these two issues already known? Do you want to have two extra issues (bug?) created?
