### ISSUE TITLE
Missi match user name in history page

### ISSUE THREAD

**Issue by rickywu** [Requarks/wiki#886]
after edit page, the history user name still use previous user name

![image](https://user-images.githubusercontent.com/442398/59735411-0c3c5980-9288-11e9-87ac-a0ec031840b2.png)

![image](https://user-images.githubusercontent.com/442398/59735383-f2027b80-9287-11e9-9715-16eacc432bc8.png)

**Comment by NGPixel** [comment]
The history page is not working yet. It will come in a future beta release.
