### ISSUE TITLE
Using it in a fully internetless environment?

### ISSUE THREAD

**Issue by gerroon** [Requarks/wiki#887]
Hi

I would like to use this inside a lan that has no internet connection but I see that when I try it bunc of stuff is broken. Is it possible to run this fully contained so that it does not need any external component like fonts, scripts you name it?

thanks

**Comment by NGPixel** [comment]
Fonts and scripts are entirely local. No client assets are being loaded from the internet.

On the server side, there's a few calls being made to fetch language files and check for updates. A new option for offline mode will be introduced in the upcoming beta build. You'll be able to sideload language files as well.

**Comment by gerroon** [comment]
Hi


Thanks for the folllow up, sounds great. Any date for the beta?

**Comment by gerroon** [comment]
Btw I was using the docker install not sure if it is relevant.

**Comment by NGPixel** [comment]
In a few days
