### ISSUE TITLE
Database Initialization Error: Mysql

### ISSUE THREAD

**Issue by bugs2919** [Requarks/wiki#888]
I have configured the prerequisites, and when I execute the "node server" I got the following error:

Loading configuration from /home/administrator/wiki/config.yml... OK
2019-06-20T11:39:17.939Z [MASTER] info: =======================================
2019-06-20T11:39:17.941Z [MASTER] info: = Wiki.js 2.0.0-beta.180 ==============
2019-06-20T11:39:17.941Z [MASTER] info: =======================================
2019-06-20T11:39:17.941Z [MASTER] info: Initializing...
2019-06-20T11:39:18.221Z [MASTER] error: Database Initialization Error: Client does not support authentication protocol requested by server; consider upgrading MySQL client

User has privileges, even I try to connect from workbench.

![image](https://user-images.githubusercontent.com/49971127/59870041-e7acb400-9351-11e9-9b64-f684e2785a71.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/49971127/59869613-f47cd800-9350-11e9-9818-0fa9c7c42ff4.png)

 - OS: Rhel 7.4 (Stable Version of Wiki.JS been working since 2018)
 - Wiki.js version: 2.0.0-beta.115
 - Database engine: mysql  Ver 8.0.16 for Linux on x86_64 (MySQL Community Server - GPL)
 - Node.js Version: v12.4.0

**Additional context**
I have allready test newer version of mysql, updated nodejs to lastest version, and always getting the same error.

**Config.YML**
![image](https://user-images.githubusercontent.com/49971127/59869848-8ab0fe00-9351-11e9-8b3f-5a612b7a79df.png)

![image](https://user-images.githubusercontent.com/49971127/59869873-97355680-9351-11e9-835b-2a455dd90d4b.png)

**Comment by NGPixel** [comment]
https://docs-beta.requarks.io/troubleshooting#mysql-client-does-not-support-authentication-protocol-requested-by-server-consider-upgrading-mysql-client

**Comment by bugs2919** [comment]
Thanks!!!! that works!!!

**Comment by sergey-shambir** [comment]
When you're using docker-compose, you can add `command` option to initialize MySQL with old auth plugin:
```
services:
  wiki-db:
    image: mysql:8.0.17
    command: --default-authentication-plugin=mysql_native_password
```

**Comment by Siddhu1096** [comment]
@NGPixel  I'm getting [MASTER] error: Database Connection Error: undefined undefined:undefined error. Could you please help me with that?
