### ISSUE TITLE
Page tags not saved

### ISSUE THREAD

**Issue by RichardD2** [Requarks/wiki#889]
**Describe the bug**
Tags added to new or existing pages are not saved.

**To Reproduce**
1. Go to any page;
2. Click on the "Edit Page" button;
3. Click "Page" in the header;
4. Enter one or more tags;
5. Click "OK";
6. Click "Save";
7. Reload the "edit" page;
8. Click "Page" again;

**Expected behaviour**
The tags should be saved.

**Actual behaviour**
The tags are not saved. Both the `pageTags` and `tags` tables have zero rows.

**Host Info:**
 - OS: Windows Server 2016
 - Wiki.js version: 2.0.0-beta.180
 - Database engine: mssql 2016

**Comment by NGPixel** [comment]
This feature is not working yet. It will come in a future beta build.
