### ISSUE TITLE
Unable to running 

### ISSUE THREAD

**Issue by spectrum-zhang** [Requarks/wiki#892]
**Question**
I have use docker to running wiki and looks everything is ok from  portainer and "docker ps", but unable to open ip:300, can someone let me know how to work well?

in case of any issue, I have disable firewall so nothing about it.

**Host Info (please complete the following information):**
OS: [e.g. centos7.3, Docker]
Wiki.js version: [1.0]
Database engine: [ mysql8]

![image](https://user-images.githubusercontent.com/50335164/59982107-b547d300-963f-11e9-8f1e-674193ab5ded.png)

![image](https://user-images.githubusercontent.com/50335164/59982019-c8a66e80-963e-11e9-9803-4e98254097b5.png)

**Comment by NGPixel** [comment]
MySQL is not a supported engine for 1.x. Please read the requirements for 1.0:

https://docs.requarks.io/wiki/install/prerequisites#mongodb
