### ISSUE TITLE
Latest version incorrect in the admin page

### ISSUE THREAD

**Issue by AgarwalSaurav** [Requarks/wiki#893]
**Describe the bug**
I updated from 2.0.0-beta.180 to 2.0.0-beta.208. The admin page says 

> A new version is available: 2.0.0-beta.203

**To Reproduce**
1. Check the administration area after an update.

**Expected behavior**
> A new version is available: 2.0.0-beta.203

**Screenshots**
![Screenshot: Administration Area Dashboard](https://user-images.githubusercontent.com/26050582/60121685-9c2f4700-9751-11e9-9416-575b2aeab001.png)
![Screenshot: Administration Area System Info](https://user-images.githubusercontent.com/26050582/60121686-9cc7dd80-9751-11e9-9bbb-aec8fb6eb95d.png)

**Host Info (please complete the following information):**
 - OS: Linux - Ubuntu Linux (bionic) 18.04 x64 (No docker)
 - Wiki.js version: 2.0.0-beta.208
 - Database engine: postgres 11.4

**Comment by NGPixel** [comment]
Fixed
