### ISSUE TITLE
Initializing  Wiki.js 2.0.0-beta.208

### ISSUE THREAD

**Issue by zhangjiaqing** [Requarks/wiki#894]
**Question**
Describe in details what you are trying to achieve and where do you need guidance.

Actual behavior
Enter email/password for administrator on "Administration Account" screen during the initial setup
Click "Continue"
The following error message is shown:

insert into `users` (`createdAt`, `email`, `isActive`, `isVerified`, `name`, `password`, `tfaIsActive`, `updatedAt`) values ('2019-06-26T08:09:53.576Z', 'test@chinaxxh.cn', true, true, 'Administrator', '$2a$12$xt0Nu9MgQGRVzrtjQ02J8uoTeOBNSz6HJkux.jmmzHuZg.L9Xaix.', false, '2019-06-26T08:09:53.576Z') - Cannot add or update a child row: a foreign key constraint fails (`wiki`.`users`, CONSTRAINT `users_defaulteditor_foreign` FOREIGN KEY (`defaultEditor`) REFERENCES `editors` (`key`))
Expected behavior
No error is thrown after clicking "Continue" and the setup can be successfully finished.

**Host Info (please complete the following information):**
OS: CentOS 7
Wiki.js version: Wiki.js 2.0.0-beta.208
Database engine: mysql 8

**Comment by Smankusors** [comment]
Btw this have been several months, is the latest stable release still happens to you?
