### ISSUE TITLE
Config.yml as mount casuses database error

### ISSUE THREAD

**Issue by gerroon** [Requarks/wiki#897]
Hi

I am trying to use docker compose to run it. If I run most everything default , the stack starts and runs but I want to mount config.yml so I can do some changes in the config, when I do that I get

(under wiki:)
```
volumes:                                                                                                                                                                            
    - /media/wiki.js/wiki/config.yml:/wiki/config.yml
```

```
wiki_1  | 2019-06-28T15:51:48.694Z [MASTER] info: Initializing...                                                                                                                             
wiki_1  | 2019-06-28T15:51:54.573Z [MASTER] error: Database Initialization Error: connect ECONNREFUSED 127.0.0.1:5432                                                                         
wikijs_docker_wiki_1 exited with code 1                                 

```

It seems to me that whatever settings in the config.yml which I just downloaded from the github repo causes database issue and I cant seem to figure it out.

Removing the config.yml mount everything works again. 

Is there a proper way to do this? I am just trying to enable the offline mode

**Comment by NGPixel** [comment]
The error you get is not a config mapping issue. The app simply cannot connect to the DB using the host / port you provided. Provide the correct host / port in your config.yml.

**Comment by gerroon** [comment]
I see, thanks for the reply. SInce I was using everything default, I assumed the default config.yml worked as is.
