### ISSUE TITLE
Footnotes: not rendered in Markdown preview, weirdly rendered on page

### ISSUE THREAD

**Issue by despens** [Requarks/wiki#898]
**Describe the bug**

Footnotes seem to be half-supported: During editing, they are not rendered at all in the preview, when viewing the page, the rendering is weird, and multi-paragraph footnotes, as defined by indentation, do not seem to work.

**To Reproduce**
1. Create a page with [Markdown footnotes](https://www.markdownguide.org/extended-syntax/#footnotes).

**Expected behavior**
Footnotes should render in preview and page view. [Here is how this renders in CodiMD.](https://demo.codimd.org/FsQ_Q7x4TGeI9eDdOrTgLQ?both)

**Screenshots**

Wikijs:
![Screenshot-20190701112110-920x535](https://user-images.githubusercontent.com/571494/60425326-9377be80-9bf2-11e9-98bb-9e4258e190c9.png)

![Screenshot-20190701112140-920x563](https://user-images.githubusercontent.com/571494/60425336-97a3dc00-9bf2-11e9-9efe-9638a909f754.png)

CodiMD:
![image](https://user-images.githubusercontent.com/571494/60425648-43e5c280-9bf3-11e9-83ee-f3aa3703e376.png)

**Comment by NGPixel** [comment]
Fixed by 58b08e54b4197d5257de260f0c6fad6721478349 and 3402afa03c2b4995c062444f8ae4ec10cb4feab0
