### ISSUE TITLE
Cannot send test mail with beta2.0

### ISSUE THREAD

**Issue by MPasadu** [Requarks/wiki#899]
I am using the docker-compose file from https://docs.requarks.io/install/docker which works fine.

But I cannot setup a mail configuration. In fact the mail configuration itself works without showing any errors but when trying to send a test mail, I get the following error:

> 139881074633576:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:252:

**Comment by NGPixel** [comment]
This issue is unrelated to Wiki.js. It means you're attempting to connect via SSL to a mail server that doesn't support it. Check your configuration.
