### ISSUE TITLE
Cannot install WikiJS 2 in Windows 10

### ISSUE THREAD

**Issue by myleskadusale** [Requarks/wiki#902]
### Actual behavior
![image](https://user-images.githubusercontent.com/15656887/60673209-da430e00-9ea9-11e9-9220-d46f5392fe06.png)

### Expected behavior
It should run

### Steps to reproduce the behavior
I followed this steps  https://docs.requarks.io/install/windows

**Comment by NGPixel** [comment]
Most likely your password consisting of numbers? Put them in quotes in your config.yml

**Comment by myleskadusale** [comment]
Thanks it fixed the problem.

Just want to add here in case someone will have same experience after updating the config.yml, create a database named wiki
