### ISSUE TITLE
Where are images ?

### ISSUE THREAD

**Issue by quantom-solar** [Requarks/wiki#903]
**Question**
I use git for versioning my assets (images).
now, i can upload images, but i can't find them in my git repo, and not in the data directory.
I use the docker image.
They are in the database ?

It's very usefull to have the documents in the git repository (like database schema).
Sorry for my bad english.

(Wikijs is a very great tools)
Thx

**Comment by NGPixel** [comment]
Assets will be included in git in the upcoming beta release. At the moment, only pages are pushed.

**Comment by shabbyrobe** [comment]
Great to hear that it's coming! It doesn't appear to work for me in beta.230 though - is this expected?

**Comment by AkimboGogurts** [comment]
As a follow up, is there a path on the local disk where images are stored? I've been trying to find them to drop some things in and haven't had any luck in getting them to show up in the image importer.

**Comment by NGPixel** [comment]
Available in RC.1
