### ISSUE TITLE
Link in activation-mail sets always 'localhost' as host.

### ISSUE THREAD

**Issue by Quving** [Requarks/wiki#904]
I would like to report a bug for the beta version.

At user registration, the Wikijsbeta backend generates a wong activationlink.
Instead of the real hostname such as 'wiki.mydomain.de' it redirects me to localhost.

By editing manually the link in the browser bar the rest works fine.

Best regards
Quving

**Comment by NGPixel** [comment]
You need to set the site url in the admin > General
