### ISSUE TITLE
Registered users cannot be deleted

### ISSUE THREAD

**Issue by Quving** [Requarks/wiki#905]
I would like to report a bug for the beta version.

Once a user is registered, I (as admin) cannot delete the user from the system anymore.

Best regards
Quving

**Comment by Cnidarias** [comment]
I think users cannot be managed at all right now? I also can't assign them to different groups

**Comment by Quving** [comment]
Hello, until now new user's cannot be added by the administrator. But new users can register themselves. 

It's true that registered users cannot be managed for instance to assign them to other groups and cannot be deleted. So make sure that registers users are assigned to a certain group per default. That works! :)

**Comment by NGPixel** [comment]
@Cnidarias @Quving 
Not true, you can currently assign users from the group itself. (Groups > Group XYZ > Users > Assign User)

@Quving Delete users is not implemented yet. It's coming in a future build.
