### ISSUE TITLE
Impossible to install wiki.js on OpenShift

### ISSUE THREAD

**Issue by dgamba** [Requarks/wiki#906]
**Question**
Trying to deploy wiki.js (both v1.x and/or 2.x) on OpenShift I get errors like this one (for v2.x):

`Loading configuration from /wiki/config.yml... OK`
`--`
`  | fs.js:114`
`  | throw err;`
`  | ^`
`  |  `
`  | Error: EACCES: permission denied, open '/wiki/package.json’`
`  | at Object.openSync (fs.js:438:3)`
`  | at Object.readFileSync (fs.js:343:35)`
`  | at Object.Module._extensions..json (internal/modules/cjs/loader.js:718:20)`
`  | at Module.load (internal/modules/cjs/loader.js:600:32)`
`  | at tryModuleLoad (internal/modules/cjs/loader.js:539:12)`
`  | at Function.Module._load (internal/modules/cjs/loader.js:531:3)`
`  | at Module.require (internal/modules/cjs/loader.js:637:17)`
`  | at require (internal/modules/cjs/helpers.js:22:18)`
`  | at Object.init (/wiki/server/core/config.js:55:25)`
`  | at Object.<anonymous> (/wiki/server/index.js:19:16)`

I can open a debug terminal, and it looks like package.json is not readable by the user that is trying to run the container:

`/wiki $ ls -lrt`
`total 96`
`-rw-r--r--    1 node     node          5081 Jun 25 02:22 wait.sh`
`-rw-r--r--    1 node     node           228 Jun 25 02:22 config.yml`
`-rw-r--r--    1 node     node         34520 Jun 25 02:22 LICENSE`
`-rw-------    1 node     node         10577 Jun 25 02:22 package.json`
`drwxr-xr-x    8 node     node           143 Jun 25 02:32 assets`
`drwxr-xr-x  747 node     node         20480 Jun 25 02:32 node_modules`
`drwxr-xr-x   15 node     node           240 Jun 25 02:33 server`
`/wiki $ cat package.json`
`cat: can't open 'package.json': Permission denied`

Any suggestion?
I cannot (I am not the administrator) specify to run the container as root, apparently. 

Thanks!

**Host Info (please complete the following information):**
OpenShift Master: v3.11.0+1c3e643-87
Kubernetes Master: v1.11.0+d4cacc0
OpenShift Web Console: v3.11.0+ea42280

**Comment by dgamba** [comment]
Seems to be linked to this [pull request](https://github.com/Requarks/wiki/pull/795).

Would it be possible to make it compatible also with OpenShift policies (i.e. running it as a random user)?
https://docs.openshift.com/container-platform/3.3/creating_images/guidelines.html#openshift-container-platform-specific-guidelines

Many thanks!

**Comment by bsharrow** [comment]
I was able to get this to run in OpenShift using the below Dockerfile.

```
FROM requarks/wiki:beta

USER root

RUN chgrp -R 0 /wiki /logs && \
    chmod -R g=u /wiki /logs

USER 1001
```

**Comment by aRestless** [comment]
I just spun up WikiJS 2 on OpenShift myself, I think the issue can be closed.

If your OpenShift setup includes adding folders to the base Dockerfile, remember to add the executable bit for the group on those new folders. Example Dockerfile based on @bsharrow's PR that adds sideloaded data:

```
FROM requarks/wiki:2

USER root

RUN git clone https://github.com/Requarks/wiki-localization.git /wiki/data/sideload

RUN chgrp -R 0 /wiki /logs && \
    chmod -R g+rw /wiki /logs && \
    chmod g+x /wiki/data/sideload

USER 1001
```

**Comment by dgamba** [comment]
Many thanks for looking at this issue, and sorry for my very late answer. 
I still didn't have time to come back and re-try installing it on our system, but I am sure it will work after your suggestions!
I will close the issue.
