### ISSUE TITLE
Gitlab Authentication Issue

### ISSUE THREAD

**Issue by GauravSn** [Requarks/wiki#907]
**Bug description**
When GitLab authentication is enabled and the base URL is pointing to **self-managed Gitlab instance** then **login with Gitlab** should redirect to the self-managed instance instead it is redirecting to the **Gitlab.com**.

**To Reproduce**
1. Go to Authentication Settings
2. Select Gitlab authentication strategy
3. Fill Client Id and Client Secret.
4. Add Base URL of self-managed GitLab instance.
5. Enable Gitlab Strategy.
6. Now login with Gitlab

**Expected behavior**
 Login with Gitlab should redirect to the self-managed instance of Gitlab

**Host Info**
 - OS: Docker
 - Wiki.js version: 2.0.0-beta.208
 - Database engine: mysql 5.7

**Comment by NGPixel** [comment]
Fixed for next build.

**Comment by GauravSn** [comment]
2.0.0-beta.230 still has this issue.

**Comment by MasterGordon** [comment]
I've got the same Issue

**Comment by NGPixel** [comment]
@GauravSn Try with the latest release, it should work now.
