### ISSUE TITLE
Spoiler

### ISSUE THREAD

**Issue by tomocrafter** [Requarks/wiki#908]
**Question**
How can I use spoiler to wiki?
I tried to use details and summary, but it doesn't work properly.

**Host Info (please complete the following information):**
OS: CentOS Linux release 7.6.1810 (Core)
Wiki.js version: Wiki.js 2.0.0-beta.208
Database engine: mysql  Ver 8.0.16 for Linux on x86_64 (MySQL Community Server - GPL)

**Comment by NGPixel** [comment]
That's not currently possible but you can suggest this feature at wiki.js.org/feedback
