### ISSUE TITLE
Search with Postgres DB generate "An expected error occurred"

### ISSUE THREAD

**Issue by raikoug** [Requarks/wiki#909]
**Describe the bug**
Searching in wikijs returns "An expected error occurred".
Is "expected" the correct word?!
In docker logs:
```text
2019-07-10T09:42:39.456Z [MASTER] warn: Search Engine Error:
2019-07-10T09:42:39.456Z [MASTER] warn: SELECT word, word <-> $1 AS rank FROM "pagesWords" WHERE similarity(word, $2) > 0.2 ORDER BY rank LIMIT 5; - operator does not exist: text <-> unknown
```
**To Reproduce**
1.Search in the wiki
2. Use postgress

**Expected behavior**
Find results

**Screenshots**
![image](https://user-images.githubusercontent.com/12453509/60959598-c4e63d80-a308-11e9-959e-f5cd4adc9b95.png)

**Host Info (please complete the following information):**
 - OS: Docker, Debian
 - Wiki.js version:2.0.0-beta.208
 - Database engine: postgres 11.4 (Debian 11.4-1)

**Additional context**
Quite fresh, some page, LDAP configuration. Nothing else.

**Comment by doits** [comment]
Postgres search needs the `pg_trgm` extension. So you have to enable it first in your database:

```
CREATE EXTENSION pg_trgm;
```

I think this is something for the docs.

Then the search does something at least, but I think it is still not fully operational (#917).

**Comment by constellationdevs** [comment]
I was having the same issue.  I added the extension suggested above and it fixed the issue for me.

**Comment by dskrvk** [comment]
Note: the module may need to be installed first, see https://dba.stackexchange.com/a/165301/131248
