### ISSUE TITLE
You can see locale strings before they're localized for a brief moment when the site loads

### ISSUE THREAD

**Issue by kurozael** [Requarks/wiki#912]
**Describe the Bug**
When loading a site using Wiki.js, for a very brief moment you can watch strings of text turn from their unlocalized keys (for example, `page.lastEditedBy`) into their localized versions (`Last Edited By`).

**To Reproduce**
_Steps to reproduce the behavior:_
1. Go to a `Wiki.js 2` installation
2. Observe any localized text
3. Observe the error occur

**Expected Behavior**
I would expect that strings are localized before the first time the page is rendered.

**Screenshots**
![Example](https://i.ibb.co/TLHNK4p/download.png)

**Host Information**
 - **OS:** Ubuntu 19.04, Apache2
 - **Wiki.js version**: 2.0.0-beta.208
 - **Database engine:** 10

**Additional Context**
None

**Comment by NGPixel** [comment]
Fixed by d74683b5fd33c0f234b661c5d66eaa2811d27074

Will be available in the next build

**Comment by carlosschuenck** [comment]
When? @NGPixel

**Comment by kurozael** [comment]
> When? @NGPixel

I just updated and this appears to be fixed in `2.0.0-beta.230` 👍
