### ISSUE TITLE
Custom CSS not included in markdown preview

### ISSUE THREAD

**Issue by doits** [Requarks/wiki#915]
**Describe the bug**

You can add custom css code injection under `/a/theme`. This code is not injected in the markdown editor when editing pages.

**To Reproduce**
1. Go to `/a/theme`
2. Inject css, e.g. `h1 { border: 1px solid red !important }`
3. Save and go to your wiki page: every `h1` has a red border
4. Edit page in markdown preview: `h1` has no red border

This means the preview is incorrect.

**Host Info (please complete the following information):**
 - OS: Ubuntu 18.04
 - Wiki.js version: 2.0.0-beta.208
 - Database engine: postgres 10.4

**Comment by NGPixel** [comment]
Fixed in 5689444a17b80372640e0d73bcd94b0e7206b6ba

Will be included in next build.
