### ISSUE TITLE
Github Enterprise on Wiki v1 or v2

### ISSUE THREAD

**Issue by talltechy** [Requarks/wiki#918]
**Question**
considering github enterprise is basically the same thing as github but with a different URL

where in the code can I customize or copy the github authentication and make it so I can point it to our github enterprise server instead? basically its just a URL change, I tried searching the code but whatever the "passport" feature points to I cannot tell

**Host Info (please complete the following information):**
OS: centos 7 / cloudlinux
Wiki.js version: v1 and v2
Database engine: postgresql (latest) mongodb (latest)

**Comment by NGPixel** [comment]
The module docs doesn't expose any option for setting a custom authorization URL. However a quick look at the code shows that `authorizationURL` can be set, so I'll add the option for the next build.

**Comment by NGPixel** [comment]
Added by 8b7122277ad66558191c2c6366c29fe55c271a36
