### ISSUE TITLE
Upgrade missing Step

### ISSUE THREAD

**Issue by sbonaime** [Requarks/wiki#920]
**Describe the bug**
After the step 5 of the Linux upgrade :
```
Extract the package
tar xzf wiki-js.tar.gz -C ./wiki
cd ./wiki
```
I have the following error
```
tar: wiki: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
cd: no such file or directory: ./wiki
```

**Host Info (please complete the following information):**
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.9 (stretch)
Release:	9.9
Codename:	stretch

The problem is linked to step 3 :
```
Delete the application folder.
rm -rf wiki
```
Tar command does not extract to a non existing directory. 
Maybe the step 3 could be modified like that

```
Delete and recreate the application folder.
rm -rf wiki
mkdir wiki
```
or
```
Delete the content of the application folder.
rm -rf wiki/*
```

**Comment by NGPixel** [comment]
Good catch, fixed 👍
