### ISSUE TITLE
node @mdi/font is not displaying

### ISSUE THREAD

**Issue by talltechy** [Requarks/wiki#922]
**Describe the bug**
When attempting to use icons from the Node package for @mdi/font no images load

**To Reproduce**

1. go to https://{install-url}/a/navigation
2. Click `+ ADD` - Link
3. type any **mdi-** style icon in the **Icon** setting box
4. View the list to the left and see there is no icon

**Expected behavior**
a visible icon to be displayed

**Screenshots**
[Example - missing icon](http://cubeupload.com/im/heirtojotunheim/95RPSm.png)

**Host Info (please complete the following information):**
 - OS: centos 7
 - Wiki.js version: 2.0.0-beta.230
 - Database engine: postgres latest

**Additional context**
http://materialdesignicons.com/ - icons from here **do not** work
https://material.io/tools/icons/?style=baseline - icons from here **do** work

**Comment by NGPixel** [comment]
Did you select the Material Design Icons set in Admin > Theme?

**Comment by talltechy** [comment]
ah :) My bad!
