### ISSUE TITLE
Escaping Html tags without &lt or &gt

### ISSUE THREAD

**Issue by xipgroc** [Requarks/wiki#924]
**Question**
Not sure how to escape html tags. I'm currently opening code blocks like this:

```C
 // Code here
```

Whenever I use something similar to html it gets interpreted and won't show up in the code.
Example:

```C
def show_exaplanation_and_image(val, f)
  if f.explanation.present? || f.form_field_image.present?
    val=val+"<div id='lightbox_#{@numinsc}_#{f.id.to_s}' class='lightbox-small'><div>#{f.explanation || ''}</div>"
    val=val+"<img src='" + f.form_field_image_url + "'/>" if f.form_field_image.present?
    val=val+"<div class='close'>X</div></div>"
  end

	return val
end
```

Result:

def show_exaplanation_and_image(val, f)
  if f.explanation.present? || f.form_field_image.present?
    val=val+"#{f.explanation || ''}"
    val=val+"" if f.form_field_image.present?
    val=val+"X"
  end

  return val
end

Is there any way to escape this besides replacing every single symbol to &lt or &gt?

**Host Info (please complete the following information):**
OS: Debian 9
Wiki.js version:2.0.0-beta.230
Database engine: mysql 5.7

**Comment by NGPixel** [comment]
This is only a bug with the preview. If you save your changes, the html will be preserved and displayed correctly.

**Comment by xipgroc** [comment]
Thanks a lot, I didn't notice!
