### ISSUE TITLE
Mysql Database detected but not load

### ISSUE THREAD

**Issue by Benjafil99** [Requarks/wiki#928]
**Describe the bug**
On 208 It was working perfectly but when installing 230, my mysql database was not loading correclty in wikijs, but the page were loading. It is showing this error on many administrative menu: 

![image](https://user-images.githubusercontent.com/50457382/61392154-30da2000-a88c-11e9-842e-7eb9dc4856b3.png)

![image](https://user-images.githubusercontent.com/50457382/61392281-74348e80-a88c-11e9-941c-aa606aa4cb6b.png)

![image](https://user-images.githubusercontent.com/50457382/61392296-7a2a6f80-a88c-11e9-9688-251afcd95ad2.png)

![image](https://user-images.githubusercontent.com/50457382/61392306-81517d80-a88c-11e9-8161-2d90d830cffb.png)

For the information, i have more than 80 pages in my DB.

**To Reproduce**
1. Have Wikijs 230 with mysql 8
2. Start wikijs and mysql
3. Load the administrative menu
**Host Info (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04, Docker]
 - Wiki.js version: [e.g. 2.0.0-beta.230]
 - Database engine: [mysql 8]

**Comment by Benjafil99** [comment]
Error messages on chrome: 
![image](https://user-images.githubusercontent.com/50457382/61396641-24f35b80-a896-11e9-9dcc-642b56938398.png)

**Comment by NGPixel** [comment]
Try to logout and login again. You get these errors because you're either not logged in or it can't connect the server.

**Comment by Benjafil99** [comment]
Thanks!! By logout and login it works!
