### ISSUE TITLE
Generate specific URLs for sections when clicking the anchor icon

### ISSUE THREAD

**Issue by hopfenzapfen** [Requarks/wiki#93]
### Actual behavior
At the moment, when clicking the anchor icon in a section, the page scrolls to that section. When moving my mouse on the anchor tag I can see a URL that includes the section name. F.e. `https://docs.requarks.io/wiki#getting-started`.

After clicking the anchor icon the URL in the address bar doesn't change. When entering the URL `https://docs.requarks.io/wiki#getting-started` manually, the page opens directly at the specified section, which is nice because it allows to send links that target specific sections of a page.

### Expected behavior
It would be nice if clicking the anchor icon would update the URL in the address bar. Another solution would be to find a way to easily copy the URL that includes the section to the clipboard. 

### Steps to reproduce the behavior
Go to a wiki page and click on the anchor icon.

**Comment by hopfenzapfen** [comment]
Just noticed that it would also be nice when the URL in the address bar is also updated when clicking a section in the side bar.

**Comment by NGPixel** [comment]
I want to avoid polluting the address bar with anchor tags since you may to share the page URL without where you were navigating in the page. Provide a copy URL modal when clicking an anchor is a good idea though.

**Comment by NGPixel** [comment]
Added in beta 12 (13bdb2edb7c4ce1bec349d04e75396133045c5eb)

**Comment by hopfenzapfen** [comment]
Is this feature already part of version `v1.0.0-beta.12`? I saw it on the documentation of Wiki.js. But I just updated to this version and it is not working :(

**Comment by NGPixel** [comment]
Yes it's part of Beta 12. Simply click on the anchor icon to open the Copy to Clipboard modal.

Example: https://docs.requarks.io/wiki

**Comment by hopfenzapfen** [comment]
I updated [my wiki](https://wiki.arnezismer.de) with `npm install wiki.js@latest` and went through the config wizard, like I always do, but this time nothing changed. My _System Settings_ page says that my current version is `v1.0.0-beta.12`.
