### ISSUE TITLE
Breadcrumbs on third and higher levels are incorrect

### ISSUE THREAD

**Issue by alesak** [Requarks/wiki#930]
eg.

/public
/public/pimcore
/public//public/pimcore/plugins
/public//public/pimcore//public//public/pimcore/plugins/Template%20Engine

**Comment by alesak** [comment]
sample URI:
[https://docs.requarks.io/install/requirements/internet](https://docs.requarks.io/install/requirements/internet)

**Comment by NGPixel** [comment]
Fixed by c83eb255141e4cce12532081ea7b26821902f318
