### ISSUE TITLE
Navigation links error

### ISSUE THREAD

**Issue by 06Games** [Requarks/wiki#935]
**Describe the bug**
The links in the navigation bar may be wrong if the path of the current page contains `home`

**To Reproduce**
1. Create a page in a folder named home
2. Create a link in the navigation bar to another page.
3. Click the created link.
4. The open page is not the right one

**Expected behavior**
The link should act as on any other page, ie, add the link from the root and not from the folder named home.

**Host Info (please complete the following information):**
 - OS: Debian (stretch) 9.9 arm
 - Wiki.js version: 2.0.0-beta.241
 - Database engine: MariaDB 10.3.14

**Comment by NGPixel** [comment]
`home` is a reserved path, which refers to the root path. Use another name for your folder.
