### ISSUE TITLE
the 2.0 version support latex?

### ISSUE THREAD

**Issue by ZhouYoung** [Requarks/wiki#937]
**Question**
the 2.0 version support latex?
insert math expressionis not available on the edit page;

thx~

**Host Info (please complete the following information):**
OS:  Ubuntu 16
Wiki.js version: 2.0.0-beta.241
Database engine: mysql 8.0.16

**Comment by NGPixel** [comment]
Follow for updates:
https://requarks.canny.io/admin/board/wiki/p/latex-support
