### ISSUE TITLE
wikitext editor is not working

### ISSUE THREAD

**Issue by Antisunny** [Requarks/wiki#946]
**Describe the bug**
markdown editor is the only choice to edit a page
I chose using `wikitext` editor when creating the page.
<img width="784" alt="image" src="https://user-images.githubusercontent.com/2398514/62366073-78cd9800-b558-11e9-9c7a-c9419b81a693.png">
but 

**To Reproduce**
1. Click the top left menu -> Choose `New Page`
2. In the prompt editor chooser, choose `Wikitext`
3. fill the page properties, then click '✓OK'. There will be a blank un-editable page(This is a bug 🐞).
4. click the 'Create' button in the top menu to create a page.(top right)
5. then choose 'edit page' button in the right panel.
6. Suprisingly, markdown editor(expected: wikitext).

**Expected behavior**
1. after click '✓OK' in the page properties prompt, an editor in the choosen type should shown up. (actual: a blank page)
2. to edit a page, the choosen editor should shown up, not the markdown editor. 

**Screenshots**
follow the steps

**Host Info (please complete the following information):**
 - OS: MacOS Mojave 10.14.6
 - Wiki.js version: Wiki.js 2.0.0-beta.241
 - Database engine: 3.24.0

**Additional context**
_empty_

**Comment by NGPixel** [comment]
Which is why the editor is clearly greyed out?

It will be available later this year / in 2020.

**Comment by Antisunny** [comment]
Oh, I see. I thought the editors being grayed out means not being selected yet.
