### ISSUE TITLE
arm64 beta docker container in infinite restart loop

### ISSUE THREAD

**Issue by thelazyanalyst** [Requarks/wiki#950]
**Describe the bug**
I am attempting to install the docker version of wikijs 2 beta on to my Raspberry pi 3 B+ (Raspbian Buster) via docker-ce.

**To Reproduce**
Using the sample config.yml from the install page (with one small tweak for password)
Running docker run -d -p 8080:3000 --name wikijs --restart unless-stopped -v ~/wikijsconfig.yml:/wiki/config.yml requarks/wiki:beta-arm64

Installs and starts the docker container but the container goes into an infinite loop. tailing the logs produces a repetitive error:
standard_init_linux.go:211: exec user process caused "exec format error"

From googling, this appears to suggest this build is not correct for my arch? I am running arm64, so I am a touch confused.

**Expected behavior**
Docker should open a port and present the wiki

**Comment by NGPixel** [comment]
Try again with latest version.
