### ISSUE TITLE
CSS won't load from remote connection.

### ISSUE THREAD

**Issue by DanWin94** [Requarks/wiki#951]
I have set up WikiJS on a windows 10 VM running on a IP address. Everything works fine there on the local host machine. However when I try to connect to it remotely from another computer, everything but the CSS loads.

I have the host set up to 'http://localhost' and port number at 80.

OS: [Windows 10]
Wiki.js version: [1.0.117]
Database engine: [mongoDB 4]

**Comment by finish06** [comment]
@DanWin94 Does the debug console show any errors, e.g. F12 on Chrome and view the console.

**Comment by DanWin94** [comment]
Yes there are four errors, but they pretty much just say that the css isn't loading

**Comment by KingsDevelopment** [comment]
I think @DanWin94 is refering to:
`Failed to find a valid digest in the 'integrity' attribute for resource`

The hashes in the index.html for the css & javascript properties are not up to date.

**Comment by higgs01** [comment]
same error occuring for me. following errors can be seen in chrome dev-tools:
```
Failed to find a valid digest in the 'integrity' attribute for resource 'https://domain/css/app.3f0ec7bfc994316d5963.css' with computed SHA-256 integrity 'W9nrLlKTT0K4L/6dmCLLXPkrS7P+4bpUjnYe2KJ3GPI='. The resource has been blocked.
(index):1 Failed to find a valid digest in the 'integrity' attribute for resource 'https://domain/js/runtime.4e0c8591a3a5f8351574.js' with computed SHA-256 integrity 'qzzeJy/eTcIOdb0Ig13mbIxoQyQDqnvtV/FWZmLI71M='. The resource has been blocked.
(index):1 Failed to find a valid digest in the 'integrity' attribute for resource 'https://domain/js/app.3f0ec7bfc994316d5963.js' with computed SHA-256 integrity 'y1WmaA9KRGfAObC4NiDU+/TPxDV+fwft3Q11TaLXg04='. The resource has been blocked.
```

**Comment by NGPixel** [comment]
Are you using Cloudflare or some other reverse proxy which manipulates the JS/CSS resources?

**Comment by higgs01** [comment]
@NGPixel i'm using cloudflare and turning cloudflare-proxy off resolved the issue. But i think this might be a recurring issue as many people are using cloudflare.

**Comment by NGPixel** [comment]
No need to disable the proxy, just follow the instructions here:

https://docs.requarks.io/troubleshooting#cloudflare-js-css-emojis-fail-to-load
