### ISSUE TITLE
Improve page loading

### ISSUE THREAD

**Issue by AgarwalSaurav** [Requarks/wiki#952]
**Describe the bug**
 When a link is clicked on the navigation bar on the left, the entire page reloads. The screen goes white and then the page comes up. The ideal behavior would have been to have the navigation bar on the left and the top bar fixed, while only the content loads. This exact behavior is present in the admin panel, which is really elegant and easy to use.

**To Reproduce**
1. Go https://docs.requarks.io/
2. Click on Home
3. Observe that the screen goes white
4. Also happens when you click on the link on a page
4. This does not happen with the Admin panel

**Expected behavior**
Screen does not go white. The navigation bar on the left and the header bar on top are fixed.

**Host Info (please complete the following information):**
 - OS: Ubuntu 18.04 direct install
 - Wiki.js version: 2.0.0-beta.241
 - Database engine: postgres 10.9

**Comment by thvozdovic** [comment]
Please do this.

**Comment by iondune** [comment]
I believe this issue might be browser-specific. It's happening for me in Firefox, but not in Chrome.

**Comment by mwasowski** [comment]
> 
> 
> I believe this issue might be browser-specific. It's happening for me in Firefox, but not in Chrome.

Issue is not browser specific, it's just Chrome (and other Chromium browsers like Vivaldi etc.) do not experience the flashing white page. But the page itself is reloaded when navigation takes place. So I second @AgarwalSaurav post, ideal would be to reload just the content frame not the whole page.

**Comment by Maxzor** [comment]
There is already a vuejs router so should not be hard

**Comment by NGPixel** [comment]
Follow https://requarks.canny.io/wiki/p/avoid-complete-site-reload-when-navigating
This is being addressed in 3.0.

---

> There is already a vuejs router so should not be hard

@Maxzor Just because there's already a vue router doesn't make it magically easy. There's a lot more involved, e.g. server-side rendering.

**Comment by LokeYourC3PH** [comment]
+1
Yeah, the white/blank interim loading page is a massive problem, it flashbangs Wiki users all the time, so I am hoping it can get fixed soon.
