### ISSUE TITLE
Links to headers of a page redirect too down in the page

### ISSUE THREAD

**Issue by juliendms** [Requarks/wiki#953]
**Describe the bug**
When you browse a page using a link referering to a sub-section (e.g. /page#header), the page scrolls too down, in the middle of the first line of text after the header.

**To Reproduce**
1. Browse: https://docs.requarks.io/guide/pages#naming-restrictions

**Expected behavior**
You should be redirected just above the header you are trying to reach (see screenshots).

**Screenshots**
Example with the install doc of Wiki.js:
![image](https://user-images.githubusercontent.com/41991731/62685667-64a7f180-b9c3-11e9-9f04-10627dbf8c75.png)

Expected result:
![image](https://user-images.githubusercontent.com/41991731/62685714-7db0a280-b9c3-11e9-9ed6-41c5f4266395.png)

**Host Info (please complete the following information):**
Reproduced on Wiki.js official documentation with Firefox and Chrome browsers.

**Additional context**
Same behavior when clicking on a header in the table of content.

**Comment by NGPixel** [comment]
Fixed by 379d58d06989b49528620de8def967c4f34097a6
