### ISSUE TITLE
(GitHub-flavored) Markdown for Checkbox is erased (not shown symbolically nor even literally)

### ISSUE THREAD

**Issue by poikilos** [Requarks/wiki#959]
**Describe the bug**
In `- [ ] item 1` and `- [x] item 1`, Wiki.js erases the brackets and what is inside (only displaying the bullet and the text after the closing bracket):
- item 1
- item 2

**To Reproduce**
1. enter the following markdown on a page:
```Markdown
- [ ] item 1
- [x] item 2
```

**Expected behavior**
Show `- [ ] item 1` `- [x] item 1` either as literal text, or as unchecked and checked checkboxes respectively:
- [ ] item 1
- [x] item 2

**Screenshots**
N/A

**Host Info:**
 - OS: unknown
 - Wiki.js version: 2.0.0-beta.241
 - Database engine: SQLite

**Additional context**

**Comment by NGPixel** [comment]
I just tested [this page](https://docs.requarks.io/en/editors/markdown#task-lists) (which runs 2.0.0-beta.241) on Chrome, Firefox, Opera, Edge and IE11. They all display the checkboxes properly.
