### ISSUE TITLE
The meaning of the footnote under list of reserved words is unclear.

### ISSUE THREAD

**Issue by poikilos** [Requarks/wiki#961]
<https://docs.requarks.io/guide/pages> says:
- "The paths must match exactly or be the first part of subfolder path. For example, the path registering is accepted while register/test is not."

I'm not sure what that means. Does it mean:
- "A reserved keyword cannot match a path exactly nor be the first part of subfolder path. For example, the path registering is accepted while register/test is not."

**Comment by NGPixel** [comment]
Correct. The docs have been updated.
