### ISSUE TITLE
Will self-hosted git be supported?

### ISSUE THREAD

**Issue by david-libremone** [Requarks/wiki#963]
**Question**

https://docs.requarks.io/storage/git currently lists providers such as GitHub and BitBucket. Reading the GitHub instructions, it looks like it should be possible to use any Git repository that I can `git push` to with SSH authentication, including a self-hosted bare repo, or a self-hosted GitLab CE instance. Is this correct?

**Host Info (please complete the following information):**

N/A

**Comment by NGPixel** [comment]
You can use any git repository. GitHub and BitBucket are just examples.
