### ISSUE TITLE
User page: Assign to Group does not display any interface for adding group

### ISSUE THREAD

**Issue by robin-lee** [Requarks/wiki#964]
**Describe the bug**
"Assign To Group" button not working on link like `a/users/3`.

**To Reproduce**
1. Go to url like 'https://wiki/a/users/3'. User page.
2. Click on 'Assign to Group'
3. No pop up to select group.

**Expected behavior**
I assume a popup or interface of some sort should open up?

**Screenshots**
![image](https://user-images.githubusercontent.com/2003940/63209788-2ecbe100-c118-11e9-8b4b-7893c226d5d1.png)

**Host Info (please complete the following information):**
 - OS: Ubuntu 18.04, Docker
 - Wiki.js version: 2.0.0-beta.241
 - Database engine: postgres:9-alpine

**Additional context**

**Comment by NGPixel** [comment]
User management is coming in the next build.
