### ISSUE TITLE
Sonic search as an option

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [Requarks/wiki#965]
## [Sonic](https://github.com/valeriansaliou/sonic) alternative to Elasticsearch that runs on a few MBs of RAM. 
 a fast, lightweight and schema-less search backend. It ingests search texts and identifier tuples that can then be queried against in a microsecond's time.

Sonic can be used as a simple alternative to super-heavy and full-featured search backends such as Elasticsearch in some use-cases. It is capable of normalizing natural language search queries, auto-completing a search query and providing the most relevant results for a query. Sonic is an identifier index, rather than a document index; when queried, it returns IDs that can then be used to refer to the matched documents in an external database.

It seems like it goes well with wikijs

**Comment by NGPixel** [comment]
You already created a feature request, no need to repost it everywhere.
