### ISSUE TITLE
Modifying configuration settings under Google authentication on Wiki.js 2.0

### ISSUE THREAD

**Issue by devp01** [Requarks/wiki#967]
**Question**
I have set up wiki.js 2.0 with a domain name and I need to change the domain name. I have configured google id authentication for the site. It was working fine. But since I have changed the dns name I need to change the Login URL, Callback URL / Redirect URI and Allowed web origins on the configuration settings for Google authentication and it is not allowing me to edit that section. 

**Host Info (please complete the following information):**
OS: Ubuntu 18.04
Wiki.js version: [e.g. 2.0.0-beta.115]
Database engine:mysql  Ver 8.0.17

**Comment by NGPixel** [comment]
Did you change the site URL under General?

**Comment by devp01** [comment]
Hi NGPixel,
Thank you. It worked.
