### ISSUE TITLE
Navigation drawer stays hidden when resizing the windows

### ISSUE THREAD

**Issue by juliendms** [Requarks/wiki#969]
**Describe the bug**
The navigation drawer stays hidden when switching from the mobile view to the desktop view.

**To Reproduce**
1. Make sure your screen is big enough: when browsing the official doc of Wiki.js, the navigation panel should be on the left part of the screen.
2. Resize the width of your browser small enough to trigger the mobile view: the navigation drawer should come on top of the page.
3. Click on the page to hide the navigation drawer. It is still accessible via the button in the bottom left corner.
4. Resize back your windows to view the desktop view: the navigation panel is not accessible anymore.

**Expected behavior**
When switching from the mobile view to the desktop view, the navigation should always be available, just like when refreshing the page.

**Screenshots**
N/A

**Host Info (please complete the following information):**
N/A

**Additional context**
It seems this property in the CSS stays on the element `v-nagivation-drawer`:
`transform: translateX(-300px);`
Removing it fixes the problem, if you revert the padding of the `v-content` to its default values:
 `padding: 64px 0px 0px 300px;`

**Comment by NGPixel** [comment]
Fixed by dd3699b5012fb5720fc28a5d24e40f41d85ed512
