### ISSUE TITLE
listening on port 80 requires elevated privileges

### ISSUE THREAD

**Issue by Mr-Chimp** [Requarks/wiki#97]
I just freshly installed Wiki.js onto a new Ubuntu Server 16.04 version and the install went without issue as did the configuration step but when I visit the site in my browser it fails to connect. I have checked the logs and see the error about not being able to listen on port 80.

When I start the server I get the Wiki.js has started successfully message but it is not listening on any ports. I did a check with ss -tln and can see port 80 is not in the list.

I did try using sudo node wiki start but then I got an error about finding modules and I don't think that is the correct way to solve this anyway.

**Comment by choicky** [comment]
I'm not the author or a coder. In fact I'm a lawyer😀

I think there may be two reasonsipv6 for your issue.

Firstly，port 80 may have been listened by other service such as  apache or nginx. You can try to have wiki.js to listen to other port such as 3000. If wiki.js starts successfully when listening to 3000, it proves that port 80 has been taken by other service.

If listening 3000 is still failed. It maybe a bug of wiki.js or vps. Some vps has both IPv4 and IPv6 or some more network interfaces, maybe wiki.js is listening to 80 on ipv6 while you are accessing 80 on ipv4.  To avoid such problem, some programs try to listen to 0.0.0.0:port to make sure to listen to the port on both ipv4 and ipv6.

I think wiki.js should listen to a non-80 port by default and instruct user that the port could be changed to 80 if it's not taken yet.

**Comment by Mr-Chimp** [comment]
Thanks for the response, in this instance I don't have a web server running at all so and the output of ss lets me know nothing else is listening on port 80. 

I manually configured the network interfaces that are available for a static IP (this is just a vm we are running locally on our network) so I don't think it could be a problem with it listening on ipv6. After I start wiki.js I can see that nothing is listening on port 80.

**Comment by NGPixel** [comment]
@Mr-Chimp This issue and the solution is explained in the docs: 

https://docs.requarks.io/wiki/troubleshooting#error-listening-on-port-xx-requires-elevated-privileges

**Comment by Mr-Chimp** [comment]
Ideal thanks for that, it looks like it will solve my problem. 

I did look to see if I could find anything about it on the wiki but the search at the top of the wiki returned nothing (I used the phrase in this issue title to search)..

Thanks again

**Comment by dh4rm4** [comment]
New link for the author's answer:
https://docs.requarks.io/wiki/install/troubleshooting#wiki-js-wont-start

**Comment by itsCodyBo** [comment]
Hello,

All the above links no longer point to viable pages. I'm currently facing this issue and there is nothing documented above that can help me. I was hoping somebody could point me to a link that is not currently broken?

**Comment by habqar** [comment]
I'm facing the same problem. and I don't know what is the issue .. I serve to 3000 and I get all time timeOut in this port /.

**Comment by itsCodyBo** [comment]
Hey @habqar I see a few others have had issues as well, I'm not a developer but I was able to get it working about a week after I posted this. Perhaps the legacy docs can help you out:

https://github.com/Requarks/docs-legacy/blob/master/wiki/troubleshooting.md


I believe solution A might have been what I used to fix the issue, as you can see from my code snippet below:

```linux@ip-00-00-0-0:~$ sudo setcap -v cap_net_bind_service=+ep `readlink -f \`which node\``
/usr/bin/node: OK```

**Comment by NGPixel** [comment]
https://docs.requarks.io/en/troubleshooting#error-listening-on-port-xx-requires-elevated-privileges
