### ISSUE TITLE
Developer documentation links broken

### ISSUE THREAD

**Issue by Mordax** [Requarks/wiki#972]
**Describe the bug**
If I hit some of the links on https://docs.requarks.io/, I get 404 errors.

**To Reproduce**
1. Go to 'https://docs.requarks.io/'
2. Click on 'themes' from the nav bar (or 'editors' and then anything but 'markdown'
3. 404 not found

**Expected behavior**
I expect an explanation on how to work and customize part of Wiki.js.

**Screenshots**
![wiki](https://user-images.githubusercontent.com/9853904/63476458-f5b0ab00-c44e-11e9-8927-ba9df3ba9302.gif)

**Host Info (please complete the following information):**
N/A since it's the website

**Comment by NGPixel** [comment]
As noted at the top of the wiki homepage, documentation is being worked on and not all pages are available yet. Missing pages will be added over time.

**Comment by Mordax** [comment]
Do you know when they are planned to be released?
