### ISSUE TITLE
git storage

### ISSUE THREAD

**Issue by oitheatre** [Requarks/wiki#973]
**Describe the bug**
I just set up wiki.js v2 and can't config my ssh storage

**To Reproduce**
1. Run docker-compose using file from [documentation](https://docs.requarks.io/install/docker) (btw it started work properly when I changed wikinet driver to bridge)
2. Go to storage settings pannel and set up it using [doc](https://docs.requarks.io/storage/git)
* ssh,
* git@github.com:blabla url
* path to private ssh key without passphrase 
* master
* ssl on
* and etc
3. Get the error in docker logs: `2019-08-22T21:59:47.333Z [MASTER] warn: Invalid or Inactive Storage Target`. Github doesn't pull my changes.

**Screenshots**

**Host Info (please complete the following information):**
 - Ubuntu 18.04, Docker
 - Wiki.js version: 2.0.0-beta.114
 - Database engine: postgres 9.7

**Comment by oitheatre** [comment]
Basic git settings don't work too.
I execed into running docker container and successfully cloned my repository with basic settings (https url, username and password)

**Comment by NGPixel** [comment]
Please update to the latest version of wiki.js first. If the bug still occurs, we'll troubleshoot.

**Comment by oitheatre** [comment]
@NGPixel sorry, my typo
I have 2.0.0-beta.241 version
![изображение](https://user-images.githubusercontent.com/53797855/63594531-53fc9b80-c5bf-11e9-92f5-09f3f8058092.png)

**Comment by NGPixel** [comment]
Did you activate the git module in the admin (is it checked in the list?)

**Comment by oitheatre** [comment]
@NGPixel yeah, I didn't mark it. Not so obviously.
Now it's working. Thank you very much!

**Comment by NGPixel** [comment]
A visual indicator has been added in the latest build.
