### ISSUE TITLE
Install from Git not Working

### ISSUE THREAD

**Issue by el-j** [Requarks/wiki#974]
clone the repository, setup postgres and configure config.yml ends up in missing assets folder with favicon. after creating assets/favicon, backend switches to setupmode and starts 
but results in :

```
Uncaught SyntaxError: Unexpected token < setup.js:1
Uncaught SyntaxError: Unexpected token < runtime.js:1
```

1. clone repo
2. install with yarn
3. change config.yml and create db for user/passwd/port
4. missing assets folder + favicon
5. creating folder + favicon starts server but results in error

**Expected behavior**
Setup of wiki should start when "yarn start"

**Screenshots**
![Screenshot 2019-08-23 at 09 40 40](https://user-images.githubusercontent.com/2795534/63575895-69f06900-c58b-11e9-8efb-44807a5bc33d.png)

![image](https://user-images.githubusercontent.com/2795534/63575149-a6bb6080-c589-11e9-837d-d0af1d823f1f.png)

**Host Info (please complete the following information):**
 - OS: MacOs Mojave 10.14.6
 - Wiki.js version: git clone from 23.08.19
 - Database engine: postgres 9.7
 - NodeJs: 10.16.2

**Additional context**
Maybe i am missing something but i cannot find any more detailed information on how to setup from git-source... tried with yarn and npm.

**Comment by el-j** [comment]
ok now tried the last release tar.gz and there seems to be an migration file missing:
![image](https://user-images.githubusercontent.com/2795534/63583419-41706b00-c59b-11e9-95bc-4880cbd90546.png)

**Comment by el-j** [comment]
i copyed the 2.0.0-beta.242.js from the master branch to the downloaded package. got the frontend working...

**Comment by el-j** [comment]
ok, this was a problem on my side. i have to run 
```
yarn dev
```
this creates all the frontend
and afterwards 
```
yarn start
```
brings the frontend up as well... 

could be mentioned somewhere in the documentation making it easier to use the 2.0 beta from source. 

nice project by the way! if i can help or add these steps to the documentation please let me know ;)

**Comment by el-j** [comment]
here is what i had to do to get it running:

# wiki.js.org How to

## Setup


### postgres db
make sure you have postgres running
make a new user in postgres with

```
psql postgres
```

#### create user
Create the user for the wiki, like used in the config.yml 
```
CREATE ROLE wikijs WITH LOGIN PASSWORD 'wikijsrocksMore';

```
check if user exists
```
\du
```
#### make user privileg
now the new user must have the privileg to make a new db
```
psql postgres
```

```
ALTER ROLE wikijs CREATEDB; 
```

```
\du
```

#### make Database

```
psql postgres
```
creating the database with
```
CREATE DATABASE wikijs;
```
and move it to the wikijs user with:
```
ALTER DATABASE wikijs OWNER TO wikijs;
```
check with 
```
\l
```

if all is done, leave postgres 

### Start the Wiki first time

before you can run the wiki with the normal start command you need to build the frontend the first time
there for simply run:
```
yarn dev
```
after this the frontend is generated and you are able to use it with:
```
yarn start
```

**Comment by NGPixel** [comment]
That's not the proper way to build assets. Yarn dev will produce non-optimized files with debugging flags.

Use `yarn build` as explained in the [docs](https://docs.requarks.io/dev#building-production-assets).

Also you should be using source from a release tag as you're running unstable code at the moment.

**Comment by el-j** [comment]
thanks for mentioning, but i wanted the state of the art nightly version. this was intended. 
anyways: the tar.gz of the last release is missing the 
```
2.0.0-beta.242.js 
```

**Comment by el-j** [comment]
i close this because i am now running it ;)

**Comment by el-j** [comment]
ok with yarn build i got this at the current working master, seems all css are missing ;)
the dev build works fine for me! is there any shedule-overview of the feature implementation? 
maybe i  would like to assist, because another editor for the files would kick to more "not markdown" users...

![image](https://user-images.githubusercontent.com/2795534/63595803-177a7100-c5ba-11e9-979b-a273fb9c6cf7.png)
