### ISSUE TITLE
GraphQL error on saving pages

### ISSUE THREAD

**Issue by JBleijenberg** [Requarks/wiki#975]
**Describe the bug**
After saving/adding a page, a popup is shown with "GraphQL Error: mapper_parsing_exception".

The request that is done, returns a 200 code and the save actually is succesfull

**To Reproduce**
1. Open any page for editing
2. Save your changes
3. Wait for the popup

**Expected behavior**
To save the page without any errors

**Host Info (please complete the following information):**
 - OS: Docker image, from the default docker-compose file given by Wiki JS instructions
 - Wiki.js version: 2.0.0-beta.241
 - Database engine: MariaDB 10.3

**Additional context**
I'm running WikiJS behind a Nginx reverse proxy for SSL offoading.

**Comment by NGPixel** [comment]
That's actually an elasticsearch error when updating the document in the search index. Which version of elasticsearch are you using?

**Comment by JBleijenberg** [comment]
@NGPixel Ah, that explains my comment here: https://github.com/Requarks/wiki/issues/968#issuecomment-524294848

I'm running ES 6.3.2

**Comment by JBleijenberg** [comment]
@NGPixel upgrading to 7.3.1 fixes both issues.
