### ISSUE TITLE
Automatically convert straight double quotes to curly double quotes

### ISSUE THREAD

**Issue by juliendms** [Requarks/wiki#976]
# Feature

From a typographic point of view, using straight double quote makes no sense. Word processors should automatically convert text enclosed in straight double quotes to text enclosed between an opening and closing double quotes.

Ex: "hello" should be rendered “hello”

Why ? see [here](https://practicaltypography.com/straight-and-curly-quotes.html).

# Implementation

Two solutions:

- Either use the curly quotes characters
- Or use the `<q>` html tag

Note that usual Markdown editors support this feature (dillinger, Typora, etc.).

**Comment by Joshfindit** [comment]
**100% disagree.**
I don’t want “curly quotes” anywhere in any of my rendered pages.

Point 1: Any accidentally unterminated quotes then have a chance to mess up the all quoted strings after it
Point 2: Curly quotes are nightmares when it comes to copy/paste, and not just for code. Copying from the “wrong” browser in to the “wrong” text editor can result in all kinds of nonsense.


As a compromise, do as GitHub does: all quote marks are slanted to the right making them *look* like “curly quotes”

Note: as there is a semantic html tag for it now, I personally *would* be comfortable with the usage of `<q>` tags

**Comment by juliendms** [comment]
My bad, I just saw that this feature is coming as an option in Rendering -> Core just like the line breaks. @NGPixel Can I leave this ticket open until the feature is released then, to keep an eye on it, or do you want me to close it now ?

@Joshfindit  The planned feature wich is an option to activate is actually the best one. As for Point 1, Markdown processors usually insert openning + closing quotes when typing a single straight quote to prevent this (see my examples). I agree with point 2 though, copy/paste could be tricky, let's see the proposed implementation.

Note that the `<q>` tag can prevent the quotes to be copied when selecting the text on a rendered page.

**Comment by juliendms** [comment]
It's working on the pre-release of the 2.1 once the option is activated. Nice work ! Issue closed.
