### ISSUE TITLE
Option to force login

### ISSUE THREAD

**Issue by JBleijenberg** [Requarks/wiki#977]
Our goal is to use Wiki JS for internal documentation etc.

We don't want to IP restrict for accessability for co-workers that work from home.

Now, when they would go to the homepage, and the guest group is not allowed to view anything, the correct page is shown for insuficient permissions

To login, it's an extra step to click the button that is shown.
It would be nice to hae an option to always redirect to the login page whenever a user is not logged in instead of showing the permissions denied page. (at least, on the home page)

**Comment by NGPixel** [comment]
Please submit a [feature request](https://wiki.js.org/feedback), GitHub issues are for bugs / help only.
