### ISSUE TITLE
Unknown authentication strategy "jwt"

### ISSUE THREAD

**Issue by getvivekv** [Requarks/wiki#978]
**Describe the bug**
After a fresh install on a mysql system, the system asked the enter administrator email and password. After this, we got this error.

**To Reproduce**
Install the system using Docker method
Goto the ui and configure admin and click next to see this error

**Expected behavior**
I should be able to get in.

**Host Info (please complete the following information):**
 - OS: Ubuntu 18.04, Docker
 - Wiki.js version: [e.g. 2.0.0-beta.241]
 - Database engine: [e.g. mysql 8]

**Comment by NGPixel** [comment]
Do you have any error in the logs? This error is usually when the server fails to start properly.

**Comment by fferraro87** [comment]
Hi
i've same error when i'm using ssl on config.yml 
i'm installing wiki.js on Plesk, i've no error installing but when i open home page i've that error. do you've solved?
