### ISSUE TITLE
The "Insert Assets" dialog appears below the editor

### ISSUE THREAD

**Issue by winfried-van-loon** [Requarks/wiki#992]
**Describe the bug**
The "Insert Assets" dialog seems to not appear at all, but it’s displayed below the editor.

**To Reproduce**
1. Go to a page
2. Edit this page
3. In the left menu, click "Insert Assets"
4. The dialog does not open within the viewport
5. In the blue bar, "← Back to editor" is displayed
6. Upon scrolling down, the dialog is displayed 

**Expected behavior**
The "Insert Assets" dialog should appear, after clicking the button to select assets to insert into the page. This should happen within the viewport. 

​**Screenshots**
![afbeelding](https://user-images.githubusercontent.com/756956/63758839-b655e480-c8bc-11e9-8500-e1fd5e5f5dcf.png)

**Host Info (please complete the following information):**
 - OS: `Linux - Ubuntu Linux (bionic) 18.04 x64`
 - Wiki.js version: `2.0.0-beta.275`
 - Database engine: `PostgreSQL 10.10`

**Comment by AgarwalSaurav** [comment]
From the slack channel:
It's a bug in the current build
The dialog actually appears below the editor, if you scroll down you can see it.

**Comment by pfwinfried** [comment]
That worked, thanks!
