### ISSUE TITLE
Is it possible to edit HTML/CSS?

### ISSUE THREAD

**Issue by EarlyPacker** [Requarks/wiki#993]
**Question**
I was wondering if it is possible to edit the HTML/CSS to customize the wiki how I want it?

**Host Info (please complete the following information):**
OS:  Ubuntu 18.10
Wiki.js version: 2.0.0-beta
Database engine: mysql 5.7

**Comment by AgarwalSaurav** [comment]
It will be great if we can get couple of simple examples for injecting CSS code in the Admin->Theme page. I can help creating several examples thereafter.

**Comment by juliendms** [comment]
Here is my current theme for the previous build (nav on the right):
https://pastebin.com/jvSC9qNA
The font is added via HTML injection in the header (see below). This CSS:

- limit the width on the content
- Fix alignement in that case
- Remove some margin for the code section, as the width of the content is reduced
- Remove the line below header
- Fix space below and after for headers, to visually separate a bit more the different section
- Change the font for the content only
- Plus some other small stuff.

Here is the HTML injection to import Google fonts for example:
```
<style>
@import url('https://fonts.googleapis.com/css?family=Lora:400,700&display=swap');
</style>
```

**Comment by AgarwalSaurav** [comment]
My modifications:
https://gist.github.com/AgarwalSaurav/895130c9b8731eca49b6144994da601b

- Change max-width
- Change colors of headers
- Change colors of horizontal bar after headers
- Hide horizontal bar for h3 and h4
