### ISSUE TITLE
LDAP Self Registration Does not Work Unless It is also enabled for Local Authentication

### ISSUE THREAD

**Issue by AkimboGogurts** [Requarks/wiki#995]
**Describe the bug**
When using LDAP Self Registration, the create account button will lead to an error even if it is enabled. The only way to get the self registration page to load is to also enable it for local authentication. 

**To Reproduce**
1. Go to Admin
2. Click on Authentication
3. Scroll down to LDAP
4. Enable Self Registration on this and no other method. 
5. Attempt to register, it will give the error that "Registration is disabled. Contact your system administrator."
6. Go back and enable registration for local authentication. 
7. Attempt to register, it will now load. 

**Expected behavior**
Enable self registration for an authentication method without also enabling it for local authentication. 

**Screenshots**
![image](https://user-images.githubusercontent.com/30539535/63878072-aeaa4480-c97d-11e9-82ce-2fe0c801c7bc.png)

**Host Info (please complete the following information):**
 - OS: Debian 9
 - Wiki.js version: 2.0.0-beta.275
 - Database engine: PostgreSQL 9.6.15

**Comment by AkimboGogurts** [comment]
I did a bit more testing, and with both enabled, and selecting to register with ldap login selected, it will actually register a local account instead.

**Comment by NGPixel** [comment]
Did you click on the LDAP button on the login form?

**Comment by AkimboGogurts** [comment]
Yes, in both cases I selected LDAP before the registration button. In the situation when only LDAP self registration is enabled, you must first select LDAP authentication on the login screen before it will show the option to register an account. 

I did a quick run through again (with self-registration enabled for both local and LDAP) and registered an account after selecting LDAP and it created a local account type in the user screen. I'm not able to do the same with only LDAP self-registration enabled as it gives the error when clicking register.

**Comment by NGPixel** [comment]
You cannot "register" an account using LDAP. That's not how it works.

Users can only register an account for local (if enabled). All other strategies must use an existing account. The self-register option means that the user doesn't need to pre-authorized in the wiki to be able to login. His account will be created automatically when he logins the first time.

The fact that the "Create an account" link stays displayed is confusing and this has been fixed in the upcoming release.
