### ISSUE TITLE
Self Registration Page Material Icons Not Displaying Properly 

### ISSUE THREAD

**Issue by AkimboGogurts** [Requarks/wiki#996]
**Describe the bug**
On the Self-Registration page, the Material Design Icons do not display properly. Similar to how they appear in navigation if they are entered without the prefix (mdi-*)

**To Reproduce**
1. Go to Login. 
2. Click on Register an Account
3. The registration page loads, and the icons are displayed as text. 

**Expected behavior**
Icons should display normally. 

**Screenshots**

![image](https://user-images.githubusercontent.com/30539535/63878681-f7163200-c97e-11e9-9f6d-8f2fc3af9932.png)

**Host Info (please complete the following information):**
OS: Debian 9
Wiki.js version: 2.0.0-beta.275
Database engine: PostgreSQL 9.6.15

**Comment by joseantonnio** [comment]
Happens here too. Same steps to reproduce.

**Host Info (please complete the following information):**
OS: Ubuntu 18.04.2 LTS
Wiki.js version: 2.0.0-beta.275
Database engine: MySQL 5.7.26
