### ISSUE TITLE
Page rules not working as intended

### ISSUE THREAD

**Issue by AgarwalSaurav** [Requarks/wiki#998]
**Describe the bug**
Adding a deny rule denies user from all content and results in a login loop.
Scenario: There is a CoreResearch page along with sub-pages. Want a new group to have read access to all the content. However, the new group can write only pages that start with CoreResearch.

Three rules are created:
Rule1-Allow permissions for pages that start with /
1. Read page
1. Read/Use assets
1. Read comments
1. Write comments

Rule2-Permissions for pages that start with /CoreResearch
Allow all

Rule3-Permissions for pages that start with /
Deny all write permissions (compliment of rule1 permissions)

**To Reproduce**
1. Create a new user (let's call it su1)
1. Create a new group (let's call it Core)
1. Create a page called /CoreResearch
1. Give all "CONTENT" permission to group Core from Edit Group
1. Apply 3 rules described above to the group Core (see screenshot)
1. Login with the new user su1 and it would get into a login loop, probably because the new user does not have permission for anything

**Expected behavior**
User su1 is able to read all content and edit pages under /CoreResearch

**Screenshots**
![wikiJS_pageRules_bug](https://user-images.githubusercontent.com/26050582/63904219-3d4eae00-c9de-11e9-9f69-2ae302b63a3a.png)

**Host Info (please complete the following information):**
- OS: Ubuntu 18.04, Linux Install
- Wiki.js version: 2.0.0-beta.275
- Database engine: postgres 10.9

**Additional context**
It might be so that I am not defining the rules correctly. For the guest group, I gave a deny that /CoreResearch should not have any of the permissions. This works perfectly.

**Comment by AgarwalSaurav** [comment]
On further investigation, denying any rule to a new group causes login loop. Perhaps because it denies all permissions. Also, I think adding an allow rule allows everything. Also, I think even if global permissions are set they are not applied until page rules are specified. This is all for new group.

**Comment by owkwen** [comment]
I have this same problem, using version 2.0.0 RC1
I tried to change what Guest group has but it made no difference.
As soon as you add a deny on write for paths starting with / (root), you get Unauthorized for all paths, even for read, which doesn't make sense.

This also contradicts the documentation ( In my situation the first rule is using Path is exactly ):

> Rules are applied in order of path specificity. A more precise path will always override a less defined path.
For example, /geography/countries will override /geography.

Assuming this also means /geography will override /

**Comment by oussamajilal** [comment]
Any update on this? having the same issue on Wiki.js version: 2.0.1

**Comment by AlexandreDC** [comment]
Page rules does not working for me too.

The assets are not shown although configured to read assets.

The Group configuration:

![image](https://user-images.githubusercontent.com/13546351/72071111-d1544e80-32c9-11ea-946a-ed10fab2f393.png)

The page for administrators: 

![image](https://user-images.githubusercontent.com/13546351/72071180-f8128500-32c9-11ea-8ddf-21b3eda47803.png)

The page for this group:

![image](https://user-images.githubusercontent.com/13546351/72071233-15475380-32ca-11ea-9e2a-fa7b36698d1b.png)

**Comment by NGPixel** [comment]
Fixed by 7d23344c7af80909c43e42a383df4d916f7eedf6
