### ISSUE TITLE
Apllication not working on port 80

### ISSUE THREAD

**Issue by przemkiemzwany** [Requarks/wiki#999]
### Actual behavior
I change a port on config.yml

# ---------------------------------------------------------------------
# Port the server should listen to
# ---------------------------------------------------------------------

port: 80

If i start a service,i see the service is running but server not listening on port 80

/etc/systemd/system/wiki.service

[Unit]
Description=Wiki.js
After=network.target

[Service]
Type=simple
ExecStart=/usr/bin/node server 80
Restart=always
# Consider creating a dedicated user for Wiki.js here:
User=wiki
Environment=NODE_ENV=production
WorkingDirectory=/home/ubuntu/wiki

[Install]
WantedBy=multi-user.target

### Expected behavior

Application working on port 80

**Comment by killrazor** [comment]
Could you provide some more detail about the issue you are experiencing?
